{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}长江三峡集团公司总经理李永安先生访问人民大学并发表学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2009-12-15 03:22:59{/dede:field}
{dede:field name='body'}<p align="justify">&nbsp;&nbsp;&nbsp; 12月14日上午，长江三峡集团公司总经理李永安先生访问人民大学。程天权书记会见了李永安总经理。程天权书记向李永安总经理介绍了近年来人民大学学科建设取得的成就，并指出，人民大学的很多老师都曾参与过三峡工程的设计工作，为国家重大水利建设项目作出了贡献。经济学院院长、经济研究所联席所长杨瑞龙教授、经济研究所联席所长毛振华教授、经济学院副院长、经济研究所联席副所长刘元春教授等陪同会见。</p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhybhhh2lf-zy2lf.jpg" alt="" /></p>
<p align="justify"><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会见结束后，李永安总经理在明德主楼0728室经济学院大讲堂发表了题为&ldquo;加快能源结构调整，建设清洁能源集团&rdquo;的学术演讲。经济学院院长杨瑞龙教授主持了演讲会。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100619/z2kymzhybyhzkf-2h2yf.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李永安总经理在目前低碳经济背景下分析了中国能源结构的现状、中国能源结构调整的必然性以及加快中国能源结构调整的措施策略。李永安总经理以他多年在三峡集团的经历，详细介绍了三峡工程作为清洁能源项目的典范是如何节能减排的，以及在新形势下三峡集团的发展展望。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李永安总经理对于清洁能源的发展战略以及先进的&ldquo;四个一&rdquo;水电开发理念，深深地吸引了大家，整个演讲持续了一个半小时。高潮迭起，掌声不断，参加演讲会的同学都表示受益匪浅。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100619/z2kymzhybnylbf-lyfbz.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲结束后，杨瑞龙院长向李永安总经理赠送了人大纪念品，经济学院的学生代表向他敬献了鲜花。 <br />
<br />
李永安先生简介 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李永安，中共十七大代表，第十一届全国政协委员，享受国务院政府特殊津贴专家，教授级高级工程师。曾任湖北省人民政府副秘书长，清江水电开发公司总经理、党委书记，开创了清江流域滚动开发、业主负责的模式，为水电建设管理体制的改革作出了积极探索。1993年调入中国长江三峡集团公司，历任副总经理、党组书记。2003年11月至今，任国务院三峡工程建设委员会副主任，中国长江三峡集团公司党组书记、总经理。李永安同志在大型水电工程建设和运行管理、资本运作、企业管理等方面具有丰富的理论和实践经验。受聘于香港大学、武汉大学、四川大学等著名高校担任荣誉教授、客座教授。 <br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhybhhh2lf-zy2lf_lit.jpg{/dede:field}
