<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","人大艺术学院学子在KAWAI亚洲钢琴大赛中获奖",89,168);
$z[2][4]['name']="title";
$z[3]=Array("field","",170,209);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",211,264);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-13 03:19:17",266,325);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　4月24日，由香港音乐导师同盟和柏斯音乐基金会主办的&ldquo;第三届KAWAI杯亚洲钢琴大赛北京分赛&rdquo;拉开帷幕，此次比赛汇集了北京各大音乐院校以及艺术院校的钢琴精英，并邀请了来自中央音乐学院、中国音乐学院等专业艺术团体的专家、教授作为评委，由于此次参赛的选手人数多（千余名）、水平高（许多选手均为国内外音乐赛事获奖者），比赛竞争异常激烈。 </p>\r\n<p>　　人大艺术学院音乐系07级马龙同学参加了此项赛事，并最终以精湛的琴技和扣人心弦的琴声打动了专家评委们，获得青年专业组三等奖，为人大艺术学院争得了荣誉。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110725/zlzzbyzhnhbnb2f-bhkykn.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p>　　此次获奖是艺术学院学生首次在KAWAI钢琴大赛中获得殊荣。马龙同学的指导教师，艺术学院康毓春老师也因出色的教学和指导，在选送学生参赛的200多名教师中，获得大赛组委会特别颁发的&ldquo;优秀指导教师奖&rdquo;。 <br />\r\n</p>",327,1207);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhnhbnb2f-bhkykn_lit.jpg",1209,1302);
$z[7][4]['name']="litpic";

?>