{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国家版权交易网正式开通仪式隆重举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文化科技园{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月19日下午，值第五届北京文博会开展之际，由中国人民大学国家版权贸易基地创办的国家版权交易网（<a href="http://www.copyrightmall.com">www.copyrightmall.com</a>）在中国国际展览中心举行了隆重的正式开通仪式。国家版权局、中国人民大学和海淀区相关领导出席仪式并致辞。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhmbmn2yf-ymmfb.jpg" /></p>
<p align="center">图为国家版权局版权管理司王自强司长</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhmyh2lkf-knbnf.jpg" /></p>
<p align="center">图为中国人民大学党委常务副书记牛维麟</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;仪式现场，国家版权局版权管理司王自强司长，中国人民大学党委常务副书记牛维麟教授，海淀区委宣传部常务副部长魏怀中，中国音像协会常务副会长兼秘书长王炬，上海新汇娱乐集团副总裁臧彦彬等将香醇的红酒注满印有国家版权交易网LOGO和名字的冰槽，标志着国家版权交易网正式开通。&nbsp; </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhmyhmhzf-nlnff.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 国家版权交易网于2010年8月底上线试运行，旨在为优秀作品的创作方与使用方搭建信息平台和沟通桥梁，促进版权交易与版权相关产业的发展，是目前国内外作品类型最齐全的版权交易网上平台。其核心功能包括两个方面：一方面为著作权人或代理宣传推广作品，实现版权价值最大化；另一方面为作品使用或传播者寻求优秀作品，顺利获得版权授权。网站试运行两个月以来，已经发展来自近20个国家的会员1000多名，挂牌交易项目1600多项，挂牌总额超过12亿元。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 国家版权交易网的开通，吸引了来自世界各地的版权供应方和版权需求方进行版权交易。通过国家版权交易网促成交易的两部作品在现场进行了正式签约，其中中视影视制作有限公司与新疆卫视购片方签订了价值1000万的电视播放协议、作家阎连科将与北京精典博维文化发展有限公司签订了价值100万的出版协议。同时，网站的主办单位中国人民大学国家版权贸易基地还与央视动画有限公司以及国家音乐产业基地（上海）分别签订大客户合作协议和战略合作协议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此外，国家版权交易网的正式开通也标志着&ldquo;中国首届版权拍卖大会&rdquo;正式拉开了帷幕。该活动由中国人民大学国家版权贸易基地主办，得到中国文字著作权协会、中国音像协会、中国广播电视协会电视制片委员会的特别支持。活动正式启动后，将进行为期半年的作品征集和版权拍卖活动。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
<br />
</p>{/dede:field}
{dede:field name='pubdate'}1290388346{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhmbmn2yf-ymmfb_lit.jpg{/dede:field}
