{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第四届红十字国际人道法模拟法庭比赛成功举办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院 文/徐皓月{/dede:field}
{dede:field name='pubdate'}2010-12-15 02:51:45{/dede:field}
{dede:field name='body'}<p>　　由红十字国际委员会（ICRC）、中国红十字会总会（Red Cross Society of China）和中国人民大学法学院联合举办的第四届红十字国际人道法模拟法庭竞赛于12月3日-12月5日在人民大学法学院成功举行，来自全国22所高校法学院的参赛队伍参加了此次竞赛。12月5日下午，第四届红十字国际人道法模拟法庭竞赛在海淀法院顺利落下帷幕。红十字国际委员会东亚地区代表处主任蒂埃里&middot;梅拉先生，中国红十字会副会长郝林娜女士、法学院院长韩大元、法学院国际人道法研究中心主任朱文奇，以及多位法官、参赛队员等出席了闭幕式。 </p>
<p>　　闭幕式由中国人民大学法学院国际人道法研究中心主任朱文奇主持。中国红十字会总会副会长郝林娜对本次模拟法庭竞赛的圆满结表示祝贺，希望高校法律学子在为国际人道事业在中国的推广传播做出自己的贡献。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmhkhfklf-mzzhn.jpg" /></p>
<p>　　红十字国际委员会东亚地区代表处主任梅拉先生首先感谢了各位法官、中国人民大学法学院以及朱文奇教授为本次竞赛付出的辛勤劳动，并赞扬了各支参赛队的精彩表现。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmhnzlhyf-zfhmkm.jpg" /></p>
<p>　　接下来，韩大元院长代表法学院致辞，他首先向参赛的国内外法律专家、国内高校参赛队伍及赛事组织者和志愿服务者表示衷心感谢，并向获奖的参赛队及队员表示祝贺。接着他强调了在高等院校普及国际人道法的重要性，高度评价了各支参赛队的表现，对获奖的团队表示祝贺并提出期望，希望他们再接再励，韩大元院长也坚信各参赛队成员能够成为国际人道法领域的优秀法律人才。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmhnymhnf-zzbmm2.jpg" /></p>
<p>　　本次模拟法庭比赛的赞助方北京市帅和律师事务所的沈腾主任也做了发言，表示了自己对国际人道法模拟法庭比赛的支持和对法学院学子的关心。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmbfzzmzf-z2myfy.jpg" /></p>
<p>　　最后，国际刑事法庭的刘大群法官宣布了本次国际人道法模拟法庭决赛的结果并做了精彩的点评。 </p>
<p>　　本次国际人道法模拟法庭竞赛从12月3日下午的国际人道法开幕式和研讨会开始，为期两天半。红十字国际人道法模拟法庭竞赛已经是连续第四次在人民大学法学院成功举办。自2007年首届比赛以来，该赛事得到国内很多著名高校的肯定，参赛的队伍不断增加，从8支代表队发展到今年的22支代表队，参赛队员的素质和水平更是逐年提高。这为国际人道法在中国的传播及推广提供了很好的平台。比赛过程中，来自国内外的在模拟法庭中担任法官角色的各位专家对参赛队伍和志愿者的表现给予了充分肯定，认为他们的表现十分专业。同时也就参赛队员在对国际人道法等法律知识的认识和掌握方面提出了各自的意见和建议。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmbfhbf2f-zlkzzn.jpg" /></p>
<p>　　本届竞赛中，国际关系学院代表队凭借其出色的表现夺得冠军，而中国政法大学代表队和吉林大学代表队则分获亚军和季军。据悉，前三名的队伍会于明年参加在香港举行的第九届亚太地区高校间红十字&ldquo;国际人道法&rdquo;模拟法庭竞赛。</p>
<p>　　（编辑：易晨）&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmhkhfklf-mzzhn_lit.jpg{/dede:field}
