{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院现代企业环境保护管理硕士（EMBA）学位进修班隆重开学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-03-16 03:04:58{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月16日，由中国人民大学环境学院与中国环境报社联合举办的&ldquo;现代企业环境保护管理硕士（EMBA）学位进修班&rdquo;隆重开学，来自全国（包括港澳在内）各地的政府、企业的环境管理和保护战线的近40名学员将用一年半时间，全面学习和掌握当今先进的环境保护管理知识和方法，成为又一批我国环保领域的高端人才。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 针对目前我国环保领域高端人才短缺的现实情况，本次学位进修班专门设置了环境经济学、管理经济学及环保专业三大课程模块，邀请了中国人民大学等高校的知名学者及国家相关部门的官员、专家，对学员进行面对面的教学。通过学习，学员将丰富完善环境管理知识结构，掌握宏观经济与环保产业的发展方向，提高环境管理、企业管理和经营理念的实战水平。据中国人民大学环境学院院长马中教授介绍，该学位进修班是培养环境保护高端人才的初步尝试，他们将发挥本校在这一领域的专业优势，为环保领域一线人员的培养发挥积极作用。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参加进修班的学员们，全部来自环境管理和环保产业市场开发机构，都是各个岗位的领导干部和业务骨干。大家纷纷表示，学位进修班是更新知识、提高素质的难得机会，也是广结人脉、整合资源的良好平台，希望进修班能长期坚持开办下去，越办越好。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开学典礼由环境学院党委书记刘鹏主持，中国环境报社长兼总编辑杨明森致欢迎辞。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
