{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}牛维麟常务副书记出席北京教育纪检监察工作研究会第五片组专题研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}纪委办公室{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月10日下午，北京教育纪检监察工作研究会第五片组暨&ldquo;13＋1&rdquo;校检预防职务犯罪工作联席会议专题研讨会在人民大学召开。校党委常务副书记、纪委书记牛维麟出席并致辞。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与会人员就中国人民大学纪委、北京体育大学纪委承担的两项课题进行了专题研讨。海淀区人民检察院职务犯罪预防处处长王燕通报了该院查办职务犯罪案件的情况。教育纪工委书记周燕也通报了近期已经部署或即将开展的八项重要工作内容。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 北京市教育纪工委、海淀区人民检察院、北京大学、中国人民大学、中国农业大学、北京科技大学、中央财经大学、北京体育大学、北京外国语大学、北京理工大学、中央民族大学、国际关系学院、北京舞蹈学院、北京财贸职业学院等十四个单位近三十人参加了此次研讨会。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;13+1&rdquo;校检预防职务犯罪工作联席会议是由位于海淀区的北京大学、中国人民大学、中国农业大学等十三所高校与海淀区人民检察院共同构建的一个预防职务犯罪的工作平台。自建立以来，联席会议通过组织展览、举办讲座，定期通报信息等方式，推动了相关高校职务预防职务工作的开展。因为工作效果显著，得到了上级部门的高度评价。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='pubdate'}1289422093{/dede:field}
{dede:field name='litpic'}{/dede:field}
