{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院李珍教授、王虎峰副教授受聘卫生部新农合技术指导组专家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-14 03:36:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月8日，卫生部举行仪式聘任2011-2013年度新农合技术指导组专家。卫生部刘谦副部长出席会议并讲话，向获聘专家颁发了聘书。公共管理学院李珍教授、王虎峰副教授受聘为专家，将参与我国新农合政策研究、专题调研和试点指导等项工作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在随后召开的新农合技术指导组2011年第一次工作会上，参会的王虎峰副教授与其他专家共同研讨了2010年全国新农合运行分析报告，并就有关我国新农合发展的基础性、战略性和前瞻性重大问题的研究提出了建议，得到了有关领导和与会专家的高度重视。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟） <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
