<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","STATSOFT公司向人大统计学院捐赠STAISTICA软件",89,170);
$z[2][4]['name']="title";
$z[3]=Array("field","",172,211);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",213,260);
$z[4][4]['name']="source";
$z[5]=Array("field","2007-04-04 08:08:50",262,321);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<HTML><HEAD><TITLE> STATSOFT公司向人大统计学院捐赠STAISTICA软件 </TITLE><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><style><!--\n .iframestyle{height:expression(1);aho:expression(autoResize()) \n}\n-->\n</style>\n<script>\nfunction autoResize()\n{\ntry\n{\n document.all[\"showDemand\"].style.height=showDemand.document.body.scrollHeight\n}\n catch(e){}\n}\n </script><body><P>&nbsp;&nbsp;&nbsp; 4月2日上午，STAISTICA软件捐赠仪式在明德主楼1030统计学院讲堂举行。STATSOFT总裁Paul Lewicki先生、STATSOFT亚洲区总经理洪哲裕先生出席了捐赠仪式。中国人民大学统计学院院长金勇进教授，首都经贸大学统计学院院长纪宏教授、中央财经大学统计学院院长刘扬教授代表各自学校接受了捐赠证书。　　</P>\r\n<P>&nbsp;&nbsp;&nbsp; 仪式结束之后STATSOFT总裁Paul Lewicki先生作了题目为“The Role of Advanced Analytics in the Global Progress of Civilization”学术演讲。<BR></P>",323,1207);
$z[6][4]['name']="body";
$z[7]=Array("field","",1209,1248);
$z[7][4]['name']="litpic";

?>