{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}STATSOFT公司向人大统计学院捐赠STAISTICA软件{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2007-04-04 08:08:50{/dede:field}
{dede:field name='body'}<HTML><HEAD><TITLE> STATSOFT公司向人大统计学院捐赠STAISTICA软件 </TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style><!--
 .iframestyle{height:expression(1);aho:expression(autoResize()) 
}
-->
</style>
<script>
function autoResize()
{
try
{
 document.all["showDemand"].style.height=showDemand.document.body.scrollHeight
}
 catch(e){}
}
 </script><body><P>&nbsp;&nbsp;&nbsp; 4月2日上午，STAISTICA软件捐赠仪式在明德主楼1030统计学院讲堂举行。STATSOFT总裁Paul Lewicki先生、STATSOFT亚洲区总经理洪哲裕先生出席了捐赠仪式。中国人民大学统计学院院长金勇进教授，首都经贸大学统计学院院长纪宏教授、中央财经大学统计学院院长刘扬教授代表各自学校接受了捐赠证书。　　</P>
<P>&nbsp;&nbsp;&nbsp; 仪式结束之后STATSOFT总裁Paul Lewicki先生作了题目为“The Role of Advanced Analytics in the Global Progress of Civilization”学术演讲。<BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
