{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院学生参加北京歌德学院成立二十周年庆典{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}网络新闻社 彭大伟、段庭辉{/dede:field}
{dede:field name='pubdate'}2008-11-09 01:01:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月1日，北京歌德学院在798艺术区举行了成立二十周年庆典。外国语学院组织德语专业同学前往参加庆祝活动，符晓丹、冯雪珺、郝汉、段庭辉4名同学作为志愿者为庆典提供了服务，获得好评。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 庆祝活动从下午2点持续到凌晨2点。德国驻华大使施明贤、北京歌德学院院长阿克瑟以及众多中德两国文化艺术届知名人士到场祝贺。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 德语专业的同学还参加了当天的&ldquo;歌德沙龙&rdquo;论坛，现场聆听包括德国当代作家马丁&middot;瓦尔泽、国际知名学者迪特&middot;博希迈耶、著名画家陈丹青在内的中德两国文学界、艺术界、传媒界知名人士围绕文学批评所展开的精彩讨论。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c100621/z2kkzlbnykmbzzf-znn2h.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 歌德学院是德意志联邦共和国在世界范围内从事文化交流活动的文化机构。1988年11月1日，歌德学院北京分院正式成立。20年来，歌德学院一方面致力于德语在中国的传播与运用，另一方面从事中德两国在文化领域内的交流与合作。歌德学院不仅在中德艺术文化交流中发挥了重要的作用，而且也是中国改革开放三十年特别是文化交流方面取得巨大发展的历史见证。</p>
<p>（编辑：杨依军）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbnykmbzzf-znn2h_lit.jpg{/dede:field}
