{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}牛维麟常务副书记率教授团考察安徽滁州{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}科研处{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应安徽省滁州市市委书记韩先聪邀请，中国人民大学常务副书记牛维麟教授率领教授考察团一行8人，于12月22-24日对滁州进行了为期3天的考察，科研处处长杜鹏教授、新闻学院常务副院长倪宁教授、财政金融学院院长郭庆旺教授、农业与农村发展学院书记孔祥智教授、财政金融学院任淮秀教授、公共管理学院叶裕民教授、科研处副处长杨燕萍等随同前往。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 位于安徽省东大门的滁州，是《醉翁亭记》和《儒林外史》的诞生地，更是中国改革开放的起点&mdash;&mdash;&ldquo;大包干&rdquo;的发源地。近几年来滁州市不断加快改革开放步伐，创新体制机制，构建了良好的发展环境，吸引了德国博世、西门子、法国乐斯福和国内康佳、盼盼等一大批知名品牌，已形成了家电、机械（汽车）、纺织、化工、农副产品和非金属矿产深加工等支柱产业。本次滁州考察旨在发挥人民大学教授的专业优势，对滁州的经济与社会发展进行多学科、多视角的研讨与交流，为滁州的的建设提出切实可行的建议。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月22日晚，韩先聪书记会见了刚刚抵达滁州的考察团一行，滁州市常务副市长袁华、副市长张陆彪、发改委主任刘茂松、发改委副主任邓继敢等参加会见。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2mb2bhnmf-zlhfh.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩先聪书记高度评价了中国人民大学在人文社会科学领域为国家和社会做出的突出贡献，对人民大学实施教授考察团的举措予以充分肯定，他简要介绍了滁州的经济社会发展状况以及目前正在进行的&ldquo;大滁城&rdquo;建设的有关情况，并期待着人民大学与滁州的合作更加广泛深入。牛维麟常务副书记简要介绍了中国人民大学近年来在学科建设、人才培养、科学研究等方面所取得的成绩，他强调中国人民大学组织教授考察团，是学校倡导教师要&ldquo;走出去、沉下去&rdquo;思路的具体体现，对学校教师了解国情民情、促进多学科交流、加强与地方政府合作具积极意义。牛维麟常务副书记还对近年来滁州所取得的发展与成就给予了高度评价，并与韩先聪书记就校市合作的具体领域进行了探讨。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月23-24日，在滁州市常务副市长袁华、滁州市副市长张陆彪等的陪同下，考察团考察了&ldquo;大滁城&rdquo;建设项目、滁州市经济技术开发区康佳电子、扬子电器、天大管材等知名企业，还来到了中国农村改革的发源地&mdash;凤阳县小岗村，参观了&ldquo;大包干纪念馆&rdquo;，并前往沈浩同志的墓地鞠躬悼念。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2mblfhzkf-22y2h.jpg" alt="" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月24日上午，郭庆旺教授和叶裕民教授分别就&ldquo;中国经济发展中的热点问题&rdquo;、&ldquo;产业转移与统筹城乡发展&rdquo;等问题，为滁州市（县、区）各政府部门负责人、有关重点项目负责人和有关企业负责人做了专题报告.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2mblznnkf-lznyy.jpg" alt="" /></p>
<p>&nbsp;&nbsp; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 两位教授的精彩报告赢得了在场的150多位参会人员的广泛好评。报告会后我校考察团的各位教授与当地有关部门负责人，就&ldquo;大滁城&rdquo;建设、皖江城市带承接产业转移示范区建设、琅琊山旅游区建设的有关问题，进行了热烈而深入的讨论。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在滁期间，学校与滁州市委市政府还就干部挂职锻炼、学校在凤阳县小岗村建立实习实训基地等事宜达成了初步的合作意向。 </p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1293483131{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mb2bhnmf-zlhfh_lit.jpg{/dede:field}
