{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院世博作品再次获奖并登上央视网络春晚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图/文 新闻学院{/dede:field}
{dede:field name='pubdate'}2011-02-28 08:59:54{/dede:field}
{dede:field name='body'}<p>　　继在&ldquo;世博寻宝计划&rdquo;、大学生电视节获奖之后，近日，由新闻学院师生创作的原创视频短片《未来就在这里》再获网络媒体肯定，团队代表也受邀参与首届央视网络春晚的录制。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflznzbybkn2kf-2zhnz.jpg" /></p>
<p>　　1月6日，《未来就在这里》一片脱颖而出，在&ldquo;2010中国网络视频盛典&rdquo;中荣获&ldquo;中国网络视频创意奖&rdquo;。该活动是由中国网络电视台发起，面向中国网民，对年度网络视频文化进行总结、盘点和展望的盛会，历时三月，共评定12个奖项、25位获奖者及作品，得到了广大用户的一致认可。</p>
<p>　　与此同时，拍摄团队还接到中国网络电视台的邀请，作为特别嘉宾参与CCTV首届网络春节晚会的录制。在以年度创意为主题的晚会中，新闻学院学生陈陈（2006级广播电视专业本科）、单溦（2008级广播电视专业本科）与来自台湾艺术大学的赖雅婷，分别作为两岸青年拍客的代表，现场与主持人撒贝宁、王小丫进行互动，以作品展现世博创意。该晚会已于兔年正月初四在央视综艺频道及央视网进行了同步转播。</p>
<p>　　央视网络春晚的相关链接&nbsp;　<a href="http://wlchunwan.cntv.cn/nettv/wlchunwan/special/C22093/classpage/video/20110205/100870.shtml "> http://wlchunwan.cntv.cn/nettv/wlchunwan/special/C22093/classpage/video/20110205/100870.shtml </a></p>
<p>　　（编辑：苏璇）<br />
</p>
<p>　　</p>
<p style="TEXT-ALIGN: left; LINE-HEIGHT: 15pt; MARGIN: 23.25pt 0cm 19.5pt; mso-pagination: widow-orphan" class="MsoNormal" align="left">&nbsp;</p>
<p style="MARGIN: 0cm 0cm 0pt" class="MsoNormal"><span lang="EN-US"><o:p><font size="3" face="Times New Roman"></font></o:p></span></p>
&nbsp;<br />
<p>&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzbybkn2kf-2zhnz_lit.jpg{/dede:field}
