<div id="jianzhang">
<dl>
<dt><a href="[field:arcurl /]" class="l">[field:title /]</a><a href="[field:arcurl /]" class="r">²é¿´ÏêÇé&gt;&gt;</a></dt>
<dd>
<div id="focusImg"><a href="[field:arcurl /]">[field:image /]</a></div>
<div id="jianzhangRight">
<div id="miaoshu">[field:description /]</div>
<div id="anniu"><a href="http://vipwebchat.tq.cn/sendmain.jsp?admiuin=8089018&uin=8349141&tag=&ltype=1&rand=88875860573066531&iscallback=1&agentid=0&comtimes=1081&preuin=8350179&page_templete_id=30278&card_templete_id=1264&buttonsflag=11111111111010&is_appraise=1&style=2&isSendPreWords=0&page=http://www.ruconline.com/hw-ruc/catalog_main.php&localurl=http%3A//www.ruconline.com/plus/list.php%3Ftid%3D14&spage=http://www.ruconline.com/hw-ruc/catalog_main.php&nocache=0.030007191700860858" target="_blank"><img src="/_res/btn_wyzx.gif" alt="" /></a>  <a href="/baoming.html" target="_blank"><img src="/_res/btn_wybm.gif" alt="" /></a></div>
</div>
<div class="c"></div>
</dd>
</dl>

</div>