{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院与保利房地产（集团）股份有限公司签订设立奖学金及“成长基地”协议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-10-29 09:54:30{/dede:field}
{dede:field name='body'}<p>　　10月27日下午，公共管理学院与保利房地产（集团）股份有限公司（保利地产）签订了设立奖学金及&ldquo;成长基地&rdquo;的协议。保利地产胡在新副总经理率部分高管，公共管理学院党委崔军副书记及学生代表参加了签约仪式。仪式由公共管理学院团委书记徐景阳老师主持。 </p>
<p>　　胡在新副总经理在致辞中介绍了保利地产的发展情况，特别称赞了公共管理学院毕业生在公司的出色表现，并表达了同公共管理学院开展深入合作的愿望与热情。崔军副书记代表院长、书记向来宾表示欢迎，同时介绍了公共管理学院的发展状况，重点介绍了学院的学生培养情况。他表示，希望双方能在更广泛的领域内建立起长期合作的关系，实现更高层面的双赢。 </p>
<p>　　随后，胡在新副总经理和崔军副书记代表双方在协议书上正式签字，并进行了进一步的交流与沟通。&nbsp;</p>
<p>　　
&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
