<div id="jianzhang">
<dl>
<dt><a href="[field:arcurl /]" class="l">[field:title /]</a><a href="[field:arcurl /]" class="r">²é¿´ÏêÇé>></a></dt>
<dd>
<div id="focusImg"><a href="[field:arcurl /]">[field:image /]</a></div>
<div id="jianzhangRight">
<div id="miaoshu">[field:description /]</div>
<div id="anniu"><a href="http://qiao.baidu.com/?module=default&controller=webim&action=index&siteid=1105522&groupid=0&groupname=%E6%9D%8E%E8%80%81%E5%B8%88" target="_blank"><img src="/_res/btn_wyzx.gif" alt="" /></a>  <a href="http://zaizhi.ruc.edu.cn/baoming.html" target="_blank"><img src="/_res/btn_wybm.gif" alt="" /></a></div>
</div>
<div class="c"></div>
</dd>
</dl>

</div>