{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院汤维建教授、校友许涛律师受聘最高人民法院首届特约监督员{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-02-04 09:36:50{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月22日，最高人民法院举行第一届特约监督员聘任大会，最高人民法院院长王胜俊向法学院诉讼法教研室汤维建教授、校友许涛律师（国联律师事务所主任律师）等60名特约监督员颁发了聘书。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在聘任大会上，王胜俊强调，聘请特约监督员对法院工作进行监督，是促进司法公开、弘扬司法民主、推进公正廉洁司法、提高司法公信力的重大举措，对于最高人民法院坚持&ldquo;三个至上&rdquo;工作指导思想，围绕&ldquo;为大局服务，为人民司法&rdquo;工作主题，认真落实&ldquo;从严治院、公信立院、科技强院&rdquo;工作方针，创新和深化&ldquo;人民法官为人民&rdquo;主题实践活动，全面做好最高人民法院工作，强化对全国法院工作的监督指导，都具有十分重要的意义。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院常务副院长沈德咏主持聘任仪式，最高人民法院副院长张军宣读了《最高人民法院关于聘任最高人民法院特约监督员的决定》。全国政协常委、副秘书长孙怀山，中央统战部副部长楼志豪作了讲话。最高人民法院副院长万鄂湘、江必新、苏泽林、奚晓明、熊选国，中纪委驻最高人民法院纪检组组长张建南，最高人民法院审委会专职委员王秀红、黄尔梅以及来自中央统战部和各民主党派的有关领导出席了聘任大会。 <br />
</p>
<p>（编辑&nbsp; 燕燕）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
