{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院姚海放博士赴香港大学访问并进行学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-04 10:00:08{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月1日开始，法学院导师姚海放博士应香港大学中国法研究中心邀请，进行短期学术访问。在此期间，姚海放博士先后拜会了香港大学中国法研究中心主任郁光华副教授，全国人大香港基本法委员会委员、香港大学法学院陈弘毅教授，香港大学法律学系主任付华伶教授；查阅了香港大学及法学院图书馆丰富的书籍资讯资料；聆听了包括北京大学中国经济研究中心姚洋教授、中国社科院社会问题研究中心于建嵘教授等专家学者的报告；并与来自商务部、浙江大学法学院、法律教育信托基等单位的访问学者进行充分沟通交流。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 16日，姚海放博士进行了题为&ldquo;农村物权纠纷解决中的法理情&rdquo;的讲座。讲座由香港大学法律学院顾潍遐副教授主持，陈弘毅教授、付华伶教授、赵云副教授、浙江大学法学院李有星教授、商务部服务贸易司徐兴锋处长、进出口公平贸易局聂文慧先生出席。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 姚海放博士首先从农村物权纠纷实践的两个小案例入手，引出话题：物权法的笼统规定，在我国广袤农村物权纠纷实践中，可能需要进行大量变通与适应；物权纠纷解决随物权法实施，才开始漫长的司法实践历程。然后，姚海放博士逐一分析了我国近期物权纠纷的类型及变化，并分析物权纠纷相关主体的不同特征。其中既包括作为农村物权享有主体的集体组织和农民个体，也有作为土地征收一方当事人的政府、作为物权确权裁决者的政府。他结合自己在广西挂职过程所亲历的多个案件，重点对农村物权纠纷中政府的角色、各种考虑与激励驱动等问题进行较为详细的展开分析。最后，他介绍了农村实践中关于物权确权纠纷的具体做法，包括物权法规定的物权凭证确权、实践中采用的实际经营管理确权方法和&ldquo;三个有利于&rdquo;的确权方法。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲完毕后，陈弘毅教授、李有星教授和部分同学进行了提问和交流。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此外，姚海放博士也就内地高校青年教师和学生赴港交流学习的有关事项等内容进行了解与交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
