<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院音乐系参加首都中外妇女庆祝三八国际劳动妇女节联谊演出",89,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",230,283);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-10 08:43:17",285,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月6日，在国家会议中心举办的首都中外妇女庆祝三八国际劳动妇女节联谊演出活动中，来自北京各界的中外妇女代表欢聚一堂，共同庆祝国际劳动妇女节。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式上，全国妇联副主席孟晓驷和国际友人代表、阿尔及利亚驻华大使夫人分别致辞，对中国社会和妇女事业近年来的发展表示赞赏，并祝愿各国妇女姐妹们之间的友谊源远流长。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhm2kzblf-zbkzmh.jpg\" /></p>\r\n<p>&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学艺术学院音乐系代表北京女音乐家协会为中外妇女带来了一场精彩的表演，其中女声小合唱《阿里路亚》和《月亮颂》，小提琴独奏，弦乐四重奏更是展示了音乐不分国界、不分民族的魅力和风采。演出获得了到场嘉宾的一致好评。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />\r\n</p>",346,1269);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhm2kzblf-zbkzmh_lit.jpg",1271,1364);
$z[7][4]['name']="litpic";

?>