{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院学者应邀参加中国联合国人口基金第七周期生殖健康计划生育项目专家研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2011-01-20 01:20:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月6至7日，中国/联合国人口基金第七周期生殖健康/计划生育项目专家研讨会在河北召开，社会与人口学院人口学系刘爽教授与宋健副教授应邀参加。会议由国家人口和计划生育委员会副主任赵白鸽主持，联合国人口基金驻华代表处代表和副代表，人口计生委国合司领导以及来自全国的30余位专家讨论了项目实施方案。</p>
<p>&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国/联合国人口基金项目是由国家人口计生委与联合国人口基金共同实施的国际合作项目，第七周期生殖健康/计划生育项目时间为2011-2015年。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
