{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}丁相顺副教授赴日本早稻田大学、一桥大学参加法律诊所教育国际研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-11 02:58:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月23日至26日,法学院院长助理、亚洲法研究中心主任丁相顺副教授应日本法律诊所教育学会理事长、早稻田大学法律诊所研究所所长宫川成雄教授的邀请，赴日本早稻田大学、一桥大学参加了法律诊所教育国际讨论会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 24日，在早稻田大学举办了&ldquo;东亚法律职业养成与诊所法学教育---中日韩的制度改革与课题&rdquo;的研讨会。中国法律诊所教育委员会主任、清华大学法学院王晨光教授就&ldquo;中国的法律职业养成与法律诊所教育&rdquo;发表了讲演，来自韩国外国语大学的文在完教授发表了关于&ldquo;韩国的法律职业养成与法律诊所教育&rdquo;的讲演，日本早稻田大学的棚村政行教授发表了&ldquo;日本的法律职业养成与法律诊所教育&rdquo;的讲演。王晨光教授、丁相顺副教授与来自韩国高丽大学的尹南根、韩国外国语大学的文在完，早稻田大学的棚村政行、宮川成雄进行了评议和专家讨论。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;25日，丁相顺副教授应邀参加了由一桥大学法科大学院举办的主题为&ldquo;通过诊所教育培养作为&lsquo;社会医生&rsquo;的法律职业&rdquo;的第三届日本法律诊所教育年会。来自日本全国近一百位从事法律诊所教育的法科大学院教授和律师参加了此次年会。应大会组织者邀请，丁相顺副教授发表了&ldquo;中国法律诊所教育：发展的可能性和限度&rdquo;，韩国高丽大学的尹南根教授发表了&ldquo;韩国诊所教育的开展&rdquo;的特别讲演。此外，丁相顺副教授还与来自日本青山学院大学的宫泽节生教授、新泻大学四谷有喜教授，韩国韩国外国语大学的文在完教授就&ldquo;东亚法律职业的养成与法律诊所教育：现状与协作&rdquo;主题展开了专家讨论，就开展东亚法学教育和法律诊所教育交流合作达成了一定的共识。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyhklfknyf-2ylmm.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参加研讨会期间，丁相顺副教授还拜访了明治大学木间正道教授、新任早稻田大学&ldquo;亚洲研究机构&rdquo;机构长小口彦太教授、日本土地法学会会长筱塚昭次教授、成文堂出版社本乡三好总编辑，就开展亚洲法律交流与合作项目事宜进行了探讨，并参加了一桥大学法科大学院举办的招待晚宴。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyhklfknyf-2ylmm_lit.jpg{/dede:field}
