{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院师生参访北京市高级人民法院并举行交流座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-12-10 10:47:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月9日上午，法学院党委书记兼副院长林嘉、副院长刘明祥、副院长王轶、党委副书记郑小敏、院长助理邵明副、办公室主任兼团委书记乔鹏、团委常务副书记邢姝等前往北京市高级人民法院拜访，商谈双方合作事宜、了解北京市法院系统2011年招录政策、看望法学院在北京市高院工作的青年校友代表。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmkylnlmf-lymhh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 北京市高级人民法院党组副书记、副院长贺荣，政治部主任鲁桂华，政治部干部处处长辛振兴，政治部教培处处长吴久宏，政治部干部处副处长李旭辉，行政庭副庭长程琥，民一庭副庭长单国军，研究室主任助理张农荣，民三庭助审员刘晓军，政治部干部处干部徐东热情接待了法学院师生。法学院师生一行参观了北京市高级人民法院大厅、图书馆、电子阅览室、羁押室和信息中心，并对北京市高院的办公现代化和信息化建设给予了高度评价。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmkkfzzlf-h2zmh.jpg" /></p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmkkzfkhf-bzk2l.jpg" /></p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmkkzmnbf-yyl2l.jpg" /></p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmknhhnnf-kbllk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参观结束后，双方举行了交流座谈会。北京市高院党组副书记、副院长贺荣首先致辞。她代表北京市高院欢迎人大法学院老师的来访，对人大法学院为法院系统输送大量优秀人才表示感谢。贺荣副院长指出，双方加强合作，能够推动理论与实践的优势互补，将来能够在教师挂职锻炼、法官兼职教学、建立专家咨询委员会等方面实现合作。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmknbfybf-nbhlf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后林嘉书记兼副院长代表人大法学院致辞。她首先感谢北京市高院的热情接待。在谈到本次拜访的目的时，她说，这次来访，一是历年来法学院不少毕业生进入北京市法院系统工作，特请高院的领导对人大法学院学生的工作情况予以评价和反馈，以进一步改善法学院人才培养的结构和方式；二是了解北京市法院系统2011年的招录计划和相关政策，以利于学院更好地开展就业指导工作。对于贺荣副院长提出的合作设想，林嘉书记兼副院长表示将全力支持，共同建立长期、务实、双赢的合作机制。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmknbbyhf-mmkn2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接下来，北京市高院政治部主任鲁桂华、政治部干部处处长辛振兴、政治部教培处处长吴久宏与法学院刘明祥副院长、王轶副院长、郑小敏副书记等就学生教学培养、实习实践、教师挂职锻炼、法官兼职教学等诸多议题上展开热烈的交流，就有关合作事项达成初步意向。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmknybzyf-zfn2hf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmkylnlmf-lymhh_lit.jpg{/dede:field}
