{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}台湾逢甲大学杨龙士副校长一行访问公共管理学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-09-25 09:21:59{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月16日，台湾逢甲大学副校长杨龙士教授及GIS中心主任周天颖教授一行访问了公共管理学院。公共管理学院院长董克用教授，副院长严金明教授及土地管理系吕萍教授、张跃松副教授等和在土地管理系交流的台湾政治大学地政系博士生庄谷中，热情接待了杨龙士副校长一行，双方进行了深入的交谈。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhbhhlnmf-zyykm.jpg" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 董克用院长向客人介绍了学院的系所构成情况，杨龙士副校长也介绍了逢甲大学建设学院以及公共政策研究所的概况，双方就今后开展更为紧密的合作交流达成初步意向。会谈结束后，董克用院长与杨龙士副校长互换了纪念品。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhbhhlnmf-zyykm_lit.jpg{/dede:field}
