<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","纽约大学杰克布斯教授做客法学院名家刑法讲座",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","图/文 法学院",212,263);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-13 03:05:30",265,324);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月10日，纽约大学法学院教授、刑事司法研究中心主任詹姆斯&bull;杰克布斯（James Jacobs）教授做客&ldquo;名家刑法讲座&rdquo;第91期。讲座主题为&ldquo;刑事定罪判决应否作为公共信息&rdquo;。杰克布斯教授是美国当代著名犯罪学家、刑事法学者，现任纽约大学刑事司法研究中心主任，主要研究领域包括有组织犯罪、仇恨犯罪、量刑、腐败防制等方面的专家。其专著《被解缚的哥特城&mdash;纽约黑帮兴衰史》、《仇恨犯罪：刑法与身份政治》已在国内出版，另有多篇学术论文被引入国内。该讲座由中国人民大学刑事法律科学研究中心主办，中心执行主任、法学院副院长刘明祥教授主持讲座。美国赛顿大学法学院Magaret Lewis副教授、北京师范大学刑事法律科学研究院王秀梅教授、人大法学院比较法研究室主任丁相顺副教授、时延安副教授作为嘉宾参加此次讲座。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110113/z2mhnnhmlnmyknf-lbyfl.jpg\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座中，杰克布斯教授首先就美国目前饱受争议的犯罪记录问题作了简明扼要的介绍，并揭示犯罪记录制度的发展历史及背景。杰克布斯教授向听众着重分析了这一制度的法理问题，即保重公众利益与个人隐私之间的冲突问题。他还从比较法的角度，提出对于这一问题，欧洲国家与美国在态度上的截然反差，进而分析了形成这一反差的文化因素。与会嘉宾和研究生就杰克布斯教授的讲座内容，进行了十分热烈的讨论。杰克布斯对听众提出的问题作了认真的回答和积极的讨论。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：苏璇）</p>",326,1741);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110113/z2mhnnhmlnmyknf-lbyfl_lit.jpg",1743,1835);
$z[7][4]['name']="litpic";

?>