{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}王利明副书记兼副校长会见麦格希教育集团新任总裁巴哈什先生{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}人大出版社{/dede:field}
{dede:field name='pubdate'}2011-04-06 05:49:11{/dede:field}
{dede:field name='body'}<p>　　4月6日上午，王利明副书记兼副校长在人大出版社会见了麦格希教育集团（原名麦格劳-希尔教育出版集团）新任总裁罗伯特&bull;巴哈什先生、国际部总裁格瑞普女士和副总裁/亚太区董事总经理舒亚杰先生一行。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbyblnlmf-2lzmk.jpg" /></p>
<p>　　王利明副书记兼副校长首先向对方介绍了人大出版社在中国出版界的领先地位，指出人大出版社依托人民大学优势学科资源，策划和出版了一批优秀的人文社科类学术著作，从海外介绍和引进了获诺贝尔经济学奖获得者等经济学家的一系列作品，在中国教育界和学术界树立了优质出版品牌；在中国图书&ldquo;走出去&rdquo;方面，人大出版社也取得了优秀的成绩，今年再次获得&ldquo;中国图书对外推广计划&rdquo;单体出版社第一名的殊荣。 </p>
<p>　　巴哈什先生积极回应了王利明副书记兼副校长的发言，介绍了麦格希在美国乃至拉美、印度和澳大利亚等世界各地的教育出版规模和优势地位，并表示，人大出版社与麦格希有着长久的、密切的合作历史，今后还将继续探索新的合作方案和合作模式，进一步扩大合作领域。双方还就数字出版、数字平台和定制出版等方面的合作，进行了深入的探讨。 </p>
<p>　　校长助理、人大出版社社长贺耀敏教授、人大出版社李永强书记、孟超副社长参加了会见活动。贺耀敏社长向巴哈什总裁介绍了人大出版社的概况及与麦格希合作情况，李永强书记向客人介绍了人大出版社的数字出版战略，并表示人大出版社愿意和麦格希教育集团在数字出版领域开展合作。 </p>
<p>　　（编辑：易晨）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbyblnlmf-2lzmk_lit.jpg{/dede:field}
