{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}杨慧林副校长率团访问扬州市并看望“村官”毕业生{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}招生就业处{/dede:field}
{dede:field name='pubdate'}2011-04-01 08:53:25{/dede:field}
{dede:field name='body'}<p>　　3月29日，应中共扬州市委组织部邀请，中国人民大学副校长杨慧林一行访问扬州市，与中共扬州市委常委、组织部长丁纯等相关负责人进行座谈，并看望任职扬州&ldquo;村官&rdquo;的学校2010届毕业生孙霞、巫杰。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbbnkklf-lkfh2.jpg" /></p>
<p>　　座谈中，丁纯部长向杨慧林副校长介绍了扬州市经济社会发展和大学生村官工作的情况，对中国人民大学长期以来对扬州市各项工作的支持表示感谢。他希望学校为建设&ldquo;创新扬州、精致扬州、幸福扬州&rdquo;输送更多人才。杨慧林副校长对扬州市为大学生成长提供的平台表示赞赏，他表示，今后要继续加强中国人民大学与扬州市的联系，鼓励更多的毕业生到扬州市干事创业。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 学校党委组织部副部长张晓辉、招生就业处副处长兼学生就业指导中心主任周荣、扬州市委组织部常务副部长张长金、扬州市委组织部综合干部处副处长兼青年干部处处长陆志林以及孙霞、巫杰也参加了座谈。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbyzkzbmf-hyffh.jpg" /></p>
<p>　　座谈会后，杨慧林副校长看望了任职扬州&ldquo;村官&rdquo;的人民大学2010届毕业生孙霞、巫杰并送去慰问金，了解了他们的工作情况，鼓励两位毕业生勤学苦干，开创美好未来。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年，学校社会与人口学院硕士毕业生孙霞和国际关系学院本科毕业生巫杰被选聘为扬州&ldquo;村官&rdquo;。孙霞工作三个月即被选拔为扬州市瘦西湖街道友谊社区党总支副书记，在同批&ldquo;村官&rdquo;中第一个被提拔为乡镇社区干部，其所带领的&ldquo;起航信息包装与推广工作室项目&rdquo;荣获扬州市首届大学生村官创新创业大赛三等奖。巫杰现任扬州市维扬区双桥街道康乐社区主任助理，他积极参与团委青年志愿者活动，主动开办社区博客，获得了各级领导和基层干部群众的一致好评。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 前不久，在第二轮扬州市各级领导与大学生&ldquo;村官&rdquo;的&ldquo;结对牵手、交友连心&rdquo;活动中，巫杰与市委书记王燕文同志结对，孙霞与市民政局主要负责人结对。此项活动是扬州市培养青年后备干部的重要举措，对&ldquo;村官&rdquo;工作能力和综合素质的提升起到推动作用。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;近年来，扬州市委高度重视大学生村官工作，把选聘优秀高校毕业生到村任职作为干部人才培养的源头工程，已连续两年组织来人民大学宣传推介大学生&ldquo;村官&rdquo;工作。　　</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：苏璇）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbbnkklf-lkfh2_lit.jpg{/dede:field}
