{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院孟虹副教授赴德参加中德科学年活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2010-06-09 08:57:13{/dede:field}
{dede:field name='body'}<p>　　应德国北威州大学联盟邀请，中国人民大学外国语学院德语专业孟虹副教授于五月底赴德国北威州参加&ldquo;2009-2010年中德科教年&rdquo;中国周活动，并先后在多特蒙特大学（Uni Dortmund）、乌帕塔尔综合大学（Wuppertal U/GH ）、明斯特大学（Uni M&uuml;nster）和科隆大学（Uni K&ouml;ln）等多所高校就&ldquo;德国媒体的中国形象&rdquo;做专题报告。</p>
<p>　　此次活动是由德国科教部和中国教育部联合发起、由德国大学校长联席会（HRK）资助的旨在促进中德科教文化交流的一次重要活动。文化周的媒体对话分别由四大高校副校长主持，中国驻德国大使馆教育处公使衔参赞姜锋博士亲自参加了科隆大学的媒体对话活动并发表了热情洋溢的讲话。</p>
<p>（编辑：邢鹏）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
