{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院多位学者出席中国《资本论》研究会第十五次（2010年）学术年会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-11-05 10:55:13{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月29日，中国《资本论》研究会第十五次（2010年）学术年会在西南财经大学举行。中共四川省常委省委宣传部黄新初部长，西南财经大学名誉校长刘诗白教授，西南财经大学校长赵德武教授，中国人民大学副校长、中国资本论研究会会长林岗教授，中国人民大学经济学院卫兴华教授，中国资本论研究会副会长、中国人民大学经济学院党委书记张宇教授，中国人民大学经济学院胡钧教授、邱海平教授、孟捷教授、谢富胜副教授等参加了研讨会。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 出席本次年会的还有来自中国社会科学院、中央党校、中央编译局以及北京大学、清华大学、南开大学、复旦大学等80多所高校的160多位专家学者。会议围绕着&ldquo;《资本论》的基本原理&rdquo;、&ldquo; 《资本论》与国际金融危机&rdquo;、&ldquo; 《资本论》与中国经济改革与发展&rdquo;、&ldquo; 《资本论》的教学&rdquo;等问题进行了深入的研讨，取得了积极的成果。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
