{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学专家学者参加第四届北京中青年社科理论人才“百人工程”学者论坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}党委宣传部{/dede:field}
{dede:field name='pubdate'}2010-12-27 09:40:52{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月24日上午，第四届北京中青年社科理论人才&ldquo;百人工程&rdquo;学者论坛在北京大学举行，本次论坛主题为&ldquo;发展：文化与经济的互动&rdquo;。论坛由中共北京市委宣传部、北京市社会科学界联合会、北京市哲学社会科学规划办公室联合主办，北京市委宣传部副部长傅华，市社会科学界联合会党组副书记、副主席陈之昌，市社会科学规划办主任王祥武，市社会科学界联合会党组副书记崔新建等领导出席会议，来自首都高校的&ldquo;百人工程&rdquo;学者、相关部门领导和师生100余人参加了论坛。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;百人工程&rdquo;学者、中国人民大学经济学院党委书记兼副院长张宇教授结合自己的专业，围绕&ldquo;中国经济模式的文化思考&rdquo;这一主题作了精彩演讲。&ldquo;百人工程&rdquo;学者、文学院副院长张永清教授作了精彩点评。国学院副院长袁济喜教授、经济学院副院长刘瑞教授、财政金融学院岳树民教授、公共管理学院副教授陈立鹏、党委宣传部部长郑水泉教授、副部长侯衍社教授等&ldquo;百人工程&rdquo;学者，以及人民大学师生代表10余人参加了论坛。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 首届北京中青年社科理论人才&ldquo;百人工程&rdquo;学者论坛于2007年4月21日在中国人民大学举行。 </p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
