{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“世界金融期货之父”利奥梅拉梅德访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-04-21 03:01:58{/dede:field}
{dede:field name='body'}<p align="center">　<img alt="" src="/uploads/allimg/c100622/z2kkzlkhy2mklkf-yn2fh.jpg" /></p>
<p>　　4月20日，享誉盛名的&ldquo;世界金融期货之父&rdquo;利奥&bull;梅拉梅德教授访问了人民大学。中国人民大学副校长薛浣白会见了远道而来的梅拉梅德教授，并进行了座谈，陪同座谈的还有财政金融学院副院长赵锡军教授、中国财政金融政策研究中心主任汪昌云教授。与利奥&bull;梅拉梅德教授同时到访的嘉宾还有美国芝加哥大学薛雨川教授和郭恪先生。 </p>
<p align="center">　<img alt="" src="/uploads/allimg/c100622/z2kkzlkhylk2ybf-kybkm.jpg" /></p>
<p>　　薛浣白副校长对梅拉梅德教授的到访表示了热烈的欢迎。友好的问候之后，短暂的座谈会正式开始。在交流中，梅拉梅德教授简要回顾了前几次来华经历，与在座老师们共同分享了在华美好的往事，并表现出了与中国学生见面的急切心情。薛浣白副校长简要介绍了财政金融学院的情况，赵锡军教授特意对梅拉梅德教授于2005年为财金学院捐赠二百余册图书一事再次表示由衷感谢。 </p>
<p>　　随后，梅拉梅德教授在明德主楼830黄达&mdash;蒙代尔讲堂以&ldquo;论道股指期货，解读资本市场&rdquo;为主题发表了精彩演讲，受到了同学们的热烈欢迎。薛浣白副校长、赵锡军教授、汪昌云教授出席了此次演讲。</p>
<p>　　相关链接：　<a href="http://news1.ruc.edu.cn/102449/102450/102496/68740.html">&ldquo;黄达&mdash;蒙代尔讲座&rdquo;：&ldquo;世界金融期货之父&rdquo;利奥&bull;梅拉梅德发表演讲</a></p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlkhy2mklkf-yn2fh_lit.jpg{/dede:field}
