{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院“山寨版”李庄案审判引众多网友关注{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-31 04:00:32{/dede:field}
{dede:field name='body'}<p>　　由法学院何家弘教授在正义网&bull;法律博客发起的&ldquo;李庄案的虚拟陪审团审判&rdquo;引起众多网友的关注和参与，在报名阶段，就出现数十名网友争当该案审判的公诉人、辩护人和陪审员的火爆场面，有的网友对因没有按时报到而失去参与资格痛惜不已。正义网记者孟澍菲专门对这次虚拟审判进行了报道，该次审判也被正义网持续列入头版头条。 </p>
<p>　　值得一提的是，本次虚拟审判也受到了众多网络媒体朋友的关注。著名网络名记者&ldquo;西西里柠檬&rdquo;废寝忘食地蹲点在法庭第一线，以《西西TV》记者的身份对本案的进程进行跟踪报道，并在其主持的&ldquo;新闻会客厅&rdquo;节目中先后对陪审员候选人&ldquo;导弹来了&rdquo;、辩护人&ldquo;无用书生&rdquo;等进行了专访；《疯狂卫视》的草根记者&ldquo;挖煤小子&rdquo;发表署名为&ldquo;淘金小子&rdquo; 的评论员文章：&ldquo;对无用大律师给予&lsquo;合理怀疑&rsquo;&rdquo;。 </p>
<p>　　目前，虚拟审判的审前程序已经完成，博客开设了公诉人工作室、辩护人工作室、陪审员休息室、传媒人工作室和旁听人休息室等几个专门工作室，供各诉讼参与人为庭审作准备，并即将开设书记员／法警工作室。本案的公诉&ldquo;加强团&rdquo;由一蓑风雨、三日坊、李族川、李小东检察官组成，辩护&ldquo;梦之队&rdquo;由江夏侯、狂人1947、asd111、无用书生组成，现在控辩双方正在对候选陪审员行使否决权，并紧张地为即将开始的庭审作最后的准备。按照&ldquo;何法官&rdquo;发出的庭审公告，法庭将于3月31日要求辩护方进行开庭陈述。总之，不论是在现实世界还是网络虚拟世界， &ldquo;山寨版&rdquo;审判的进展和结局及其它可能产生的影响都引起了大家的极大关注。</p>
<p>附：</p>
<p>正义网报道：<a href="http://news.jcrb.com/jxsw/201003/t20100328_337396.html">http://news.jcrb.com/jxsw/201003/t20100328_337396.html</a></p>
<p>何家弘法律博客痴醒斋：<a href="http://hejiahong.fyfz.cn/cat/61745.htm">http://hejiahong.fyfz.cn/cat/61745.htm</a></p>
<p>（编辑：於萍萍）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
