{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国圣母大学（University of Norte Dame）代表团访问中国人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/国际交流处 图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-03-30 09:28:22{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月28日，美国圣母大学常务校长卜立群（Thomas G. Burish）博士率代表团访问中国人民大学。杨慧林副校长会见了客人。随团来访的还有刘氏基金会创始人兼董事会主席刘伟民先生、圣母大学门多萨商学院副院长罗格&bull;黄(Roger Huang)先生、亚洲事务总监刘战（Jonathan Noble）先生以及驻北京办事处工作人员马兰女士。中国人民大学国际交流处处长唐忠教授、商学院副院长毛基业教授、新闻学院院长助理雷蔚真副教授以及王莉丽研究员参加了会谈。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨慧林副校长首先向代表团表达了热烈的欢迎，并向代表团详细介绍了中国人民大学学科特色、学科排名成就以及学校各种国际项目以及最新的国际合作模式和进展。杨校长表示，两校有很多的相似性，双方开展合作一定会有良好前景。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110418/zlflzzhbbyfnlbf-2byhk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 卜立群常务校长也简要介绍了圣母大学的基本情况，强调了国际交往对该校培养高素质人才的重要作用。同时，他还着重介绍了该校的商学院以及新成立的亚洲研究中心，并表达了与中国顶尖高校相关学院进行合作的强烈愿望。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈中，双方还在商学、新闻学以及校际学生交换和教师交流方面广泛交换了意见。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110418/zlflzzhbbyh2nlf-lbfbf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 美国圣母大学座落于印第安纳州，成立于1842年，是一所全美排名前20名的私立大学，多年来以其卓越鲜明的特色，屹立于美国高等教育之林。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbbyfnlbf-2byhk_lit.jpg{/dede:field}
