{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='' text='中国人民大学世纪馆体育场' width='500' height='359'} /uploads/allimg/100612/2-zffyz2zffb2f.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zffkfh.jpg' text='中国人民大学世纪馆夜景' width='500' height='292'} /uploads/allimg/100612/2-zffyz2zffkfh.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zffk2m.jpg' text='中国人民大学世纪馆室内场' width='500' height='333'} /uploads/allimg/100612/2-zffyz2zffk2m.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zffnzz.jpg' text='中国人民大学世纪馆室外足球场' width='500' height='333'} /uploads/allimg/100612/2-zffyz2zffnzz.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zffmfn.jpg' text='中国人民大学世纪馆室外足球场' width='500' height='375'} /uploads/allimg/100612/2-zffyz2zffmfn.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zfzz2f.jpg' text='中国人民大学世纪馆室内活动场' width='450' height='262'} /uploads/allimg/100612/2-zffyz2zfzz2f.jpg {/dede:img}
