{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院召开2007年度国家社科基金重大项目第二次中期成果研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月26日，由经济学院副院长刘瑞教授担任项目首席专家的2007年度国家社科基金重大项目《科学发展观在完善宏观调控体系中的体现研究》课题组召开课题第二次中期成果研讨会。会议内容为课题组内部中期成果汇报、交流及下一年度的课题研究安排。会议由刘瑞教授主持，全体课题组成员参加。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzhkflkmznf-ymllk.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会的第一单元，刘瑞教授首先介绍了会议主要的议程安排。随后，烟台大学李艳丽副教授、经济学院武少俊教授、金乐琴副教授、杨天宇副教授分别针对国家宏观调控对企业的影响效应分析、科学发展观在国家发展规划与计划中的体现、贯彻落实科学发展观与国家发展战略的观念转变、科学发展观在产业政策中的体现等问题先后进行了成果汇报。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100619/z2kymzhkfbkfkhf-kmhlb.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会的第二单元，山东经济学院林晖副教授、经济学院李健美副教授、山东财政学院王静副教授、投资北京国际有限公司王洪涛博士分别就中国资本市场的可持续发展与货币政策的完善、贯彻落实科学发展观与区域政策的完善、宏观调控中的财政政策理念转变与体制调整以及&ldquo;十二五&rdquo;期间北京市投融资规划研究进行了汇报。课题组成员还就各子课题研究工作的进展、成果与下一步研究方向进行了讨论，并在课题组内部形成了共识。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 刘瑞教授最后对本次研讨会进行了总结，肯定了课题组取得的各项中期成果。同时强调要进一步加强课题研究的推进力度，鼓励课题组成员多进行实地调研，形成有针对性的课题成果，为本课题的圆满完成继续努力。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1262209498{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkflkmznf-ymllk_lit.jpg{/dede:field}
