{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国肯特州立大学一行访问新闻学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院 文/裴峥{/dede:field}
{dede:field name='pubdate'}2010-10-27 09:36:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月25日，学院常务副院长倪宁教授会见了来新闻学院访问的美国肯特州立大学一行。肯特州立大学传播学院研究生协调主管林玫辰副教授、国际事务交流副主任泰德&bull;麦科恩、国际项目协调主管黛博拉&bull;戴维斯以及肯特州立大学中国代表处主任李娜博士，新闻学院张迪老师参加会见。双方就学科建设、人才培养等方面进行座谈，表达了进一步加强交流合作的意愿和兴趣。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 美国肯特州立大学已有百年的建校史，是世界最佳200大学之一，新闻传播学院是其优势专业，和中国人民大学已签订合作协议。这次来新闻学院访问，意在促进学生联合培养、双方教师交流合作等事项。倪宁常务副院长向来访嘉宾介绍了学校和学院的有关发展概况、学术地位以及社会影响等，肯特州立大学国际事务交流副主任麦科恩等也对该校的教学组织、学生实践学习等情况做了介绍。双方还就海外交流2+2和3+2项目等细节问题进行了探讨。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，肯特州立大学国际事务交流副主任泰德&bull;麦科恩一行还与新闻学院同学进行互动交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖） <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
