{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院接待英国杜伦大学代表团{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院 文/图 胡婷婷 郑艺菲{/dede:field}
{dede:field name='pubdate'}2011-03-04 02:29:59{/dede:field}
{dede:field name='body'}<p>　　3月2日，英国杜伦大学艺术与人文科学副校长Seth Kunin率代表团来中国人民大学进行访问。外国语学院副院长贾国栋、英语系主任刁克利等在明德国际楼505室会见了代表团成员。 </p>
<p>　　首先，贾国栋副院长对代表团的来访表示热烈欢迎，向他们简要介绍外国语学院相关情况，如系别设置、教研项目、对外交流等。同时，他诚挚表达了对于未来与杜伦大学合作的美好憧憬。英语系主任刁克利，法语系主任徐艳，俄语系副主任陈方也分别针对各自所在系别的情况做了具体介绍。</p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110419/zlflznzm2l2zylf-zlkzy.jpg" /></p>
<p>　　随后，英国杜伦大学现代语言与文学学院院长、法语系教授David Cowling介绍了杜伦大学现代语言与文学学院的情况。他首先指出了他所在学院与外国语学院框架体系的相似之处，表明愿意与中国人民大学进行学术合作。接着，他介绍了英国学生的语言学习情况，由此提出此行的目的，即商讨有关两校合作交流的新项目。在简单介绍了建立汉语语言及历史文化学习研究项目之后，双方深入探讨交换生项目的开展，针对合作细节进行了讨论，如交换生的数量、专业，以及他们在国外可能面对的学习生活问题等。 </p>
<p>　　最后两院领导互换礼物，合影留念。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflznzm2lbmyzf-2ylbn.jpg" /></p>
<p>　　（编辑：易晨）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzm2l2zylf-zlkzy_lit.jpg{/dede:field}
