{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院志愿者参加“国家人口计生委庆祝新中国成立60周年爱国歌曲演唱会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-10-10 09:38:44{/dede:field}
{dede:field name='body'}<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月25日上午，&ldquo;国家人口计生委庆祝新中国成立60周年爱国歌曲演唱会&rdquo;在国家图书馆音乐厅隆重举行。中国人口福利基金会与社会与人口学院的青年志愿者们共同组队，登台演唱了歌曲《我们走在大路上》。大家精神饱满,一展歌喉,放声歌唱祖国。昂扬的旋律激励着大家，表达了志愿者对我国人口福利事业百倍的信心和无私奉献的精神！&nbsp;</p>
<p align="center"><img height="333" src="/uploads/allimg/c100622/z2kkzlknymbzymf-lkfhl.jpg" width="500" alt="" /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 朝着胜利的方向，我们永远向前进</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlknkfzzfnf-hnf2l.jpg" alt="" />&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演出后领导与演员合影 </p>
<p align="left"><br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlknymbzymf-lkfhl_lit.jpg{/dede:field}
