<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","社会与人口学院志愿者参加“国家人口计生委庆祝新中国成立60周年爱国歌曲演唱会”",89,203);
$z[2][4]['name']="title";
$z[3]=Array("field","",205,244);
$z[3][4]['name']="writer";
$z[4]=Array("field","社会与人口学院",246,299);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-10-10 09:38:44",301,360);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p align=\"left\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月25日上午，&ldquo;国家人口计生委庆祝新中国成立60周年爱国歌曲演唱会&rdquo;在国家图书馆音乐厅隆重举行。中国人口福利基金会与社会与人口学院的青年志愿者们共同组队，登台演唱了歌曲《我们走在大路上》。大家精神饱满,一展歌喉,放声歌唱祖国。昂扬的旋律激励着大家，表达了志愿者对我国人口福利事业百倍的信心和无私奉献的精神！&nbsp;</p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c100622/z2kkzlknymbzymf-lkfhl.jpg\" width=\"500\" alt=\"\" /><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 朝着胜利的方向，我们永远向前进</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100622/z2kkzlknkfzzfnf-hnf2l.jpg\" alt=\"\" />&nbsp;<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演出后领导与演员合影 </p>\r\n<p align=\"left\"><br />\r\n<br />\r\n</p>",362,1189);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100622/z2kkzlknymbzymf-lkfhl_lit.jpg",1191,1283);
$z[7][4]['name']="litpic";

?>