<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","董克用教授主持召开教育部“马工程”第三批重点教材《人力资源管理》专家组第一次工作会议",89,211);
$z[2][4]['name']="title";
$z[3]=Array("field","",213,252);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",254,305);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-18 04:54:15",307,366);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月15日，教育部马克思主义理论研究和建设工程第三批重点教材《人力资源管理》专家组第一次工作会议在公共管理学院召开。公共管理学院院长董克用教授作为专家组首席专家主持会议；专家组成员公共管理学院刘昕教授，北京大学肖鸣政教授，首都经济贸易大学杨河清教授，中南财经政法大学陈全明教授、赵琛徽教授，上海大学张昊民教授，西南大学罗洪铁教授以及教育部&ldquo;马工程&rdquo;联络员童宁出席会议；中南财经政法大学陈芳教授、张广科教授和上海大学马君副教授列席会议。</p>\r\n<p align=\"center\"><img alt=\"\" width=\"500\" height=\"333\" src=\"/uploads/allimg/c110419/zlflzn2bbn2h2kf-zmlbf.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，董克用教授介绍了教育部对&ldquo;马工程&rdquo;教材编写的相关要求、时间安排、专家组的工作方式以及经费预算情况；与会专家就《人力资源管理》一书的写作目的、写作思路、写作风格、写作体例以及章节安排展开了讨论，并形成了初步意见。 <br />\r\n　　<br />\r\n　　（编辑：王强）</p>",368,1320);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflzn2bbn2h2kf-zmlbf_lit.jpg",1322,1414);
$z[7][4]['name']="litpic";

?>