{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}董克用教授主持召开教育部“马工程”第三批重点教材《人力资源管理》专家组第一次工作会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 04:54:15{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月15日，教育部马克思主义理论研究和建设工程第三批重点教材《人力资源管理》专家组第一次工作会议在公共管理学院召开。公共管理学院院长董克用教授作为专家组首席专家主持会议；专家组成员公共管理学院刘昕教授，北京大学肖鸣政教授，首都经济贸易大学杨河清教授，中南财经政法大学陈全明教授、赵琛徽教授，上海大学张昊民教授，西南大学罗洪铁教授以及教育部&ldquo;马工程&rdquo;联络员童宁出席会议；中南财经政法大学陈芳教授、张广科教授和上海大学马君副教授列席会议。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2bbn2h2kf-zmlbf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，董克用教授介绍了教育部对&ldquo;马工程&rdquo;教材编写的相关要求、时间安排、专家组的工作方式以及经费预算情况；与会专家就《人力资源管理》一书的写作目的、写作思路、写作风格、写作体例以及章节安排展开了讨论，并形成了初步意见。 <br />
　　<br />
　　（编辑：王强）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2bbn2h2kf-zmlbf_lit.jpg{/dede:field}
