{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院叶林教授参加在沪“内幕交易认定与处理专题研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-29 09:44:09{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月24日，中国人民大学法学院叶林教授应邀参加了中国证监会主办、上海证券交易所承办的&ldquo;内幕交易认定与处理专题研讨会&rdquo;。中国证监会姚刚副主席做了主题发言，行政处罚委员会焦津洪主任和滕必焱副主任主持了研讨会，北京大学和中央财经大学的部分法学专家，最高人民法院、最高人民检察院和公安部以及部分地方公检法机关的人员参加了专题研讨会。叶林教授针对我国规制内幕交易的基本政策、我国资产重组中内幕交易的规制、我国规制内幕交易现行法律的缺陷与改进等三个问题，进行了主题发言。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
