{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院迎来首届武警国防生新生{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-09-10 11:08:15{/dede:field}
{dede:field name='body'}<p>　　9月7日，中国人民大学新闻学院首届武警国防生顺利完成入学注册，正式到学院报到。新闻学院2010级国防班共招收29名新生，为了尽早适应军队生活，2010级国防生于8月22日提前入学，并参加了武警选培办统一组织的体检和军训。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmffym2by2f-lhfln.jpg" />&nbsp;</p>
<p>　　在军训期间，国防班新生每天早上六点零五集合，在学校的世纪馆体育场、明德广场北侧和世纪馆西侧篮球场出操，进行基本的动作训练和队列训练。经历了两周的军训生活，他们磨练了意志、增强了国防观念，为尽快融入部队和大学生活做好了准备。在9月5日的各学院国防生篮球赛中，新闻学院2010级国防班勇夺冠军。 </p>
<p>　　入学报到当天晚上，学院领导班子老师和班主任、辅导员在武警选培办教官的陪同下，参观了国防班新生同学的宿舍，并对国防生们寄以了殷切的期望。 </p>
<p>　　9月8日中午，在明德新闻楼611会议室，学院党委副书记胡百精老师、团委书记阎芳老师、党务秘书刘佳老师和国防生班辅导员刘刚参加了国防班第一次班会。老师们分别介绍了学校和学院的基本情况和以及指导大家如何度过大学生活。班会向同学们布置了开学期间学校学院的新生入学教育安排，并就同学们提出的问题进行了交流和解答。</p>
<p>　　（编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmffym2by2f-lhfln_lit.jpg{/dede:field}
