{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙教授应邀为苏州市委作经济形势分析报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2009-12-17 02:50:30{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年12月16日上午，经济学院院长杨瑞龙教授受苏州市委的邀请，为苏州市委十届十一次全体（扩大）会议作有关当前经济形势与经济结构转型升级的辅导报告。杨瑞龙教授以大量的数据、由表及里的分析对2009年的宏观经济复苏的轨迹及面临的主要问题作了深入的剖析，并对2010年的宏观经济走势作出了判断。杨瑞龙教授还结合苏州的情况对产业结构的升级与培养新的经济增长点提出了自己的看法。杨瑞龙教授的报告引发了参会人员的很大兴趣，并给予了高度的评价。报告会由苏州市委副书记、市长阎立主持。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会前，江苏省委常委、苏州市委书记蒋宏坤、市长阎立、市委副书记徐建明等亲切会见了杨瑞龙院长。杨瑞龙教授向苏州市领导介绍了中国人民大学经济学科在全国的地位，并重点介绍了由经济学院主办的&ldquo;中国宏观经济论坛&rdquo;及其在全国产生的重要影响。苏州市领导表达了希望与中国人民大学多开展合作的愿望。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月16日下午，杨瑞龙院长还顺访了人民大学国际学院（苏州研究院），并与陈甬军副院长就经济学院与国际学院进一步合作进行了深入的讨论。同时，在国际学院王小虎副院长的陪同下，杨瑞龙教授还参观了国际学院的校园。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
