{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院志愿者开展3.15消费者法律知识宣传活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-17 08:56:03{/dede:field}
{dede:field name='body'}<p>　　3月15日，法学院青年志愿者协会组织十余名志愿者开展了&ldquo;3&bull;15消费者法律知识宣传&rdquo;活动。本次活动以发放《3.15消费者法律知识手册》、现场咨询、张贴宣传海报为主要内容，旨在提高消费者法律意识，使消费者了解如何通过法律手段维护自己的合法权益。</p>
<p>　　志愿者们在公共教学楼二楼前设置了宣传咨询点，向过往行人发放《3.15消费者法律知识手册》，并提供咨询服务。虽然前一天刚下完雪，天气还很寒冷，但这丝毫不能阻挡普法志愿者普及法律，践行人大法律人责任的热情。下课时间，志愿者们耐心地向前来咨询以及路过的行人宣传消费者法律知识。</p>
<p>　　普法宣传活动一直是法学院青年志愿者协会主要活动之一，在&ldquo;3&bull;15国际消费者权益日&rdquo;到来之际，开展普法宣传活动，提高消费者维权意识和维权能力是全体志愿者的职责。在今后的时间里，法学院青年志愿者协会将一如既往地积极开展普法宣传活动，提高公民的法律意识。 </p>
<p>　　(编辑：程远芳) <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
