{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院孙久文教授参加中宣部《七个“怎么看”》撰写工作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中宣部理论局组织编写的通俗理论读物《七个&ldquo;怎么看&rdquo;--理论热点面对面&bull;2010》公开发行，经济学院区域与城市经济研究所孙久文教授及其博士生彭薇应邀参加了该书的撰写工作。 <br />
　　从2010年年初开始，中宣部理论局组织力量深入基层开展调研，梳理出&ldquo;怎么看我国发展不平衡&rdquo;、&ldquo;怎么看就业难&rdquo;、&ldquo;怎么看看病难&rdquo;、&ldquo;怎么看教育公平&rdquo;、&ldquo;怎么看房价过高&rdquo;、&ldquo;怎么看分配不公&rdquo;、&ldquo;怎么看腐败现象&rdquo;等七个人们集中关注的热点问题，并组织中央有关部门和理论界部分专家学者撰写了这本通俗理论读物。该书紧密联系当前形势，理论联系实际，对七个问题作出了深入浅出、有针对性和说服力的回答。 <br />
　　孙久文教授和彭薇博士参加了第一章&ldquo;怎么看我国发展不平衡&rdquo;的撰写，并参加了该书的宣传工作,受到中宣部理论局有关领导的赞扬。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1286761334{/dede:field}
{dede:field name='litpic'}{/dede:field}
