{dede:noteinfo notename="人大新闻网人大新闻" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
	{dede:addurls}http://news1.ruc.edu.cn/102392/list.html{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<table width="743" cellspacing="1" bgcolor="#CACCCE">{/dede:areastart}
	{dede:areaend}<table width="100%"><tr><td align=right>{/dede:areaend}
{/dede:listrule}
