<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","韩国首尔大学法学院代表团访问法学院",89,161);
$z[2][4]['name']="title";
$z[3]=Array("field","",163,202);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",204,249);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-06 09:52:54",251,310);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月2日下午，韩大元院长在明德法学楼贵宾室会见了韩国首尔大学法学院院长金建植教授一行，相关副院长、民商法教研室相关教授以及经济法教研室相关教授参加了会见。&nbsp;</p>\r\n<p align=\"center\">&nbsp;<img src=\"/uploads/allimg/c100619/z2kymzylkfnymyf-2zbzz.jpg\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩大元院长向金建植教授简单介绍了法学院的基本情况。他表示，法学院院的韩国法律研究所是人民大学法学院加强与韩国法学院交流合作，提升法学院院国际化水平的重要成果，金玄卿教授也是法学院第一位引进的韩国全职教授，他希望人大法学院与首尔大学法学院能保持合作关系，加强学生、教师、科研等多方面的交流。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 金建植教授表示很乐意来到人民大学法学院与人大法学院各位教授进行学术交流，他很感激人大法学院对他们此行给予的深厚款待。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议中韩大元院长与金建植教授互赠了纪念品，金建植教授还向法学院韩国法律研究所赠送了韩国法律书籍，希望通过韩国研究所加强两院之间在法学研究方面的合作。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议结束后，金建植教授和尹真秀教授在明法601国际会议厅为法学院学生做了主题为&ldquo;韩国公司治理的转换&rdquo;和&ldquo;韩国产品责任法&rdquo;的专题讲座。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）<br />\r\n</p>",312,1682);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100619/z2kymzylkfnymyf-2zbzz_lit.jpg",1684,1776);
$z[7][4]['name']="litpic";

?>