{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国国民党荣誉主席连战会见纪宝成校长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}人民大学访台代表团{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月7日，中国国民党荣誉主席连战会见并宴请了正在台湾访问的纪宝成校长和中国人民大学代表团。会面在台北国宾饭店举行，连主席邀请了不少国民党的要员参加，可谓高朋满座，气氛隆重亲切。 <br />
</p>
<p align="center"><img alt="" width="500" height="281" src="/uploads/allimg/c101126/z2mfkyfhkhmz2lf-hlyyz.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在会谈中，连主席对中国人民大学和纪校长给予了高度的评价。他表示，人民大学在很多领域都非常杰出，是一所受到大家仰慕的学术殿堂；并评价纪校长为&ldquo;一位影响力非常大的教育家，一位卓有成效的学者，一位好朋友&rdquo;。他回顾了今年9月与纪校长在芝加哥大学北京中心会面的情景，对纪校长在呼吁重视人文社会科学、振兴国学等方面所做的努力以及在治理学校中取得的成绩表示高度的赞赏。他认为纪校长在新的世纪，在电脑等新技术迅猛发展的大的趋势下，&ldquo;（呼吁）我们不要忘记重视人文社会科学，这对我们是很窝心（台语为温暖之意）的&rdquo;；他认为纪校长提到要重视国学的发展，&ldquo;这也是做事为人的一个根本问题。&rdquo;纪校长对连主席的关心和盛情接待表示了感谢。他代表人民大学对连主席在两岸关系中做出的杰出的独特的贡献表示了景仰之情，并邀请连主席在方便的时候到人民大学访问。纪校长还介绍了人民大学在学科建设上取得的成就以及对台学术交往，并特别介绍了人民大学台湾校友会和会长朱瓯。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈后，连主席向中国人民大学赠送了精致的法兰瓷纪念品，纪校长也向连主席赠送了中国人民大学徐庆平教授特别书写的字幅&ldquo;接天莲叶无穷碧，映日荷花别样红&rdquo;。字幅内嵌&ldquo;莲（连）&rdquo;字，代表人民大学师生的良好祝福。 <br />
</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c101126/z2mfkyfhkbb22bf-bymb2.jpg" /></p>
<p align="left"><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在之后举行的晚宴中，纪校长与连主席、台湾&ldquo;教育部长&rdquo;吴清基及在座的台湾朋友就两岸政治、经济、社会、教育和两岸关系等诸多问题交换了意见。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhkbkfknf-y2hbb.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陪同连主席参加会见及宴请的有台湾&ldquo;教育部长&rdquo;吴清基、中国国民党副主席林丰正、台湾中华文化总会会长刘兆玄、中兴工程顾问社董事长蔡勋雄、&ldquo;教育次长&rdquo;林聪明、&ldquo;立法委员&rdquo;洪秀柱、&ldquo;立法委员&rdquo;郭素春、政治大学校长吴思华、东吴大学校长黄镇台、台北大学校长侯崇文、中国国民党国政研究基金会执行长蔡政文、政治大学副校长林碧炤和&ldquo;蒋经国基金会&rdquo;执行长朱云汉。&nbsp;<br />
</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c101126/z2mfkyfhkylmmmf-kmyzn.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学代表团成员有国学院常务副院长黄朴民、信息学院院长杜小勇、组织部长高德步、统战部长周淑真、发展规划处处长胡娟和港澳台办副主任李贞实。中国人民大学台湾校友会会长朱瓯及其夫人蒋彭成、中华两岸人道关怀协会秘书长（人大台湾校友会顾问）兰梁筱娟也陪同纪校长参加了会谈及晚宴。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c101126/z2mfkyfhkykbzhf-nm2hn.jpg" /></p>
<p><strong>相关链接</strong>：</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [<a href="http://news1.ruc.edu.cn/102382/71662.html">海峡两岸大学校长论坛系列报道] 论坛将登场 欢迎晚宴为纪宝成校长庆生 </a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71672.html">纪校长率团赴台参加第三届海峡两岸大学校长论坛并作主题发言</a></p>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71728.html">纪宝成校长拜会吴伯雄先生、刘兆玄先生</a></div>
<div></div>
<div></div>
<div></div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </div>
<div>　　 <a href="http://news1.ruc.edu.cn/102392/71729.html">人民大学与台湾清华大学签订校际协议</a></div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71725.html">纪宝成校长接受台湾媒体采访</a></div>
<div></div>
<div></div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71852.html">中国人民大学台湾校友会热烈欢迎纪校长访台</a></div>
<div></div>
<div></div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑&nbsp;&nbsp; 燕燕&nbsp; 王开 易晨）</div>{/dede:field}
{dede:field name='pubdate'}1289337723{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhkhmz2lf-hlyyz_lit.jpg{/dede:field}
