{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院郑保卫教授赴墨西哥坎昆主持气候传播边会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院  文/李玉洁{/dede:field}
{dede:field name='pubdate'}2010-12-29 05:17:48{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月5日，在联合国坎昆气候大会举行期间，由中国人民大学新闻与社会发展研究中心和香港乐施会共同主办的基础四国与墨西哥气候传播边会在墨西哥坎昆举行。研究中心主任郑保卫教授前往坎昆主持会议，并在会上致辞。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnlln2bzh2f-zykl2.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次边会是中国高校首次在国外举办此类会议，也是中国科研机构第一次在国际舞台上启动气候传播议题研究。来自中国、墨西哥、印度、泰国、瑞士等国家的高校、研究机构、新闻媒体和NGO（非政府组织）的专家学者、媒体记者和NGO人士参加了研讨会。与会者就气候变化对发展中国家的危害及影响，以及这些国家如何应对气候变化，做好气候传播等问题进行了研讨。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次边会之前，中国人民大学新闻与社会发展研究中心与香港乐施会先后完成了&ldquo;后哥本哈根政府、媒体、NGO的角色及影响力研究&rdquo;与&ldquo;通往坎昆&mdash;&mdash;气候传播媒体系列行动&rdquo;两个研究项目，对去年的哥本哈根气候大会到今年的坎昆气候大会进行了追踪研究，同时第一次对我国的气候传播现状进行了考察分析，从而为政府、媒体、NGO以及其它第三方更好地推动气候谈判和参与气候应对提供了理论和决策支持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月7日，郑保卫教授利用主持坎昆气候传播边会的机会参观访问了墨西哥卡洛斯&bull;瑟普提恩&bull;加西亚（Carlos Septi&eacute;n Garc&iacute;a）新闻学院，同该校校长何塞&bull;路易斯&bull;巴斯克斯&bull;巴埃萨（Jos&eacute; Luis V&aacute;zquez Baeza）和主管教学的教务主任芬妮&bull;康德拉斯C.（Fanny Contreras C.）等进行了交流，并同该院学生座谈，回答了他们提出的问题。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllnlfhfmf-2lbyf.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 卡洛斯新闻学院是拉美地区第一所新闻学院，创建于1949年5月，为墨西哥新闻界培养了大批优秀新闻人才，在拉美地区享有较高声誉。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnlln2bzh2f-zykl2_lit.jpg{/dede:field}
