{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学产业化项目遴选会召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文化科技园、科研处{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月29日上午，中国人民大学产业化项目遴选会在明德主楼第六会议室召开。中国人民大学党委常务副书记牛维麟教授出席会议并讲话。牛维麟常务副书记介绍了学校参与中关村科学城建设、组建创意产业技术研究院以及推进学术成果产业化的情况，并对产业化项目的遴选工作提出了具体的要求。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自环境学院、统计学院、新闻学院、信息学院、物理系、文化科技园的10个项目参与了本次项目遴选会，项目负责人分别从建设背景、建设意义、优势与特色、投资规模、项目团队等方面介绍了项目的基本情况。遴选会由科研处杜鹏处长主持，专家组成员包括：物理系王孝群教授、化学系艾希成教授、化学系张小岗副教授、文化科技园管委会办公室彭翊主任、科研处杨燕萍副处长、科研处张清明副处长、产业处孔然副处长、文化科技园公司王国成副总经理等。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 作为中关村科学城的第二批建设单位，中国人民大学拟通过本次遴选会选取可以迅速产业化、市场前景好的项目，上报中关村科学城建设项目主管单位，积极争取北京市政府的政策、资金支持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 结合中关村科学城的建设，中国人民大学以创意产业技术研究院为依托，以具体产业化项目为抓手，积极服务于国家战略新兴产业的发展，努力在教育学、科研体制机制改革上先行先试，不断引领技术创新和产业组织创新，为首都产业结构优化升级提供有力支撑，同时促进学校相关学科发展。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1293680705{/dede:field}
{dede:field name='litpic'}{/dede:field}
