{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第二届首都高校研究生统计论坛在人大举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2007-12-19 03:38:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2007年12月12日， 由中国人民大学统计学院主办的&ldquo;第二届首都高校研究生统计论坛&rdquo;在中国人民大学明德主楼成功召开。参与本次论坛的包括有中国科学院、北京大学、北京师范大学、北京交通大学、首都经济贸易大学、中央财经大学、中央民族大学等高校选派的研究生代表。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届论坛首先由中国人民大学统计学院副院长高敏雪教授致开场发言，然后各高校代表分别进行学术报告。报告的内容涵盖了经济统计、数理统计，以及统计软件的最新应用等统计研究前沿领域。论坛最后由中国人民大学统计学院党委副书记宋大我老师进行总结和展望。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届论坛不仅为首都高校的统计学专业研究生提供一个展示最新科研成果的平台，而且通过相互交流和沟通使得大家更深入领会统计知识和方法的应用，实现了在探讨中共同进步，共同提高，增进各高校之间友谊的活动主旨。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 附：（各高校代表的报告论文）<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《多重假设检验及其在计量经济中的应用》，中国人民大学统计学院，蔡正高<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;《统计数据质量的综合评价》，首都经济贸易大学统计学院，胡迪<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《捕获记忆呈指数消退的捕获反应模型》，北京大学概率论与数理统计系，丁丹丹<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《On Estimation for semi-parametric varying coefficinets partial linear model》，北京师范大学数学科学学院，胡涛<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《统计学中的动画：方法展示与数据分析》，中国人民大学统计学院，谢益辉<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
