{dede:noteinfo notename="新闻—人大艺术学院" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl=""
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
	{dede:addurls}http://art.ruc.edu.cn/we-news.html?page=1{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<table width="100%" border="0" cellpadding="0" cellspacing="0" class="listGrid">{/dede:areastart}
	{dede:areaend}      </tr>
          </table>   
    
        
    <div class="page"{/dede:areaend}
{/dede:listrule}
