{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院第二届“歌之翼”红歌大赛揭开序幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院　邢丽{/dede:field}
{dede:field name='pubdate'}2009-04-09 09:28:41{/dede:field}
{dede:field name='body'}<p>　　4月7日下午2点半，社会与人口学院第二届&ldquo;歌之翼&rdquo;红歌大赛初赛在学生活动中心东厅热闹开演，08级本科生于咏捷和车广宇主持了这次比赛。09年&ldquo;五&bull;四&rdquo;声乐比赛优秀歌手程家作、范婧怡、孙俊、钟琳玲、张欣担任此次评审。 <br />
<br />
　　与首届&ldquo;歌之翼&rdquo;不同，在建国60周年的大背景下，第二届&ldquo;歌之翼&rdquo;红歌大赛更加凸显特色，旨在弘扬爱国主义精神，激励同学们为了理想、为了祖国建设奋发向上。与此同时，在大赛组织形式上，本届也有了很大的创新。这次比赛的选手都是以组合的形式参赛，其中本院选手与外院选手的结合更是一大特色，此外，抛却以往单一的歌曲演唱，此次比赛更注重选手在配乐、舞蹈、演唱等方面的配合。 <br />
<br />
　　此外，选手的多才多艺也赢得了评审的高度赞扬，最后，比赛在评委程家作同学的歌声及观众们热烈的掌声中圆满落幕。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
