{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院校友滕佳材任吉林省长春市副市长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-12-13 02:31:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近期，由中组部集中选派到地方交流任职的66名中青年干部陆续到任。选派的66名干部分别来自54个中央和国家机关部委。其中，国家工商总局办公厅主任、法学院校友滕佳材任吉林长春市副市长。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 滕佳材同志生于1964年，中共党员，系法学院1996级在职法律硕士，长期在中央国家机关工作。曾任中国消费者协会秘书长，国家工商行政管理总局消费者权益保护局局长，国家工商行政管理总局办公厅主任。现任吉林省长春市副市长。&nbsp;</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
