<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","法学院校友滕佳材任吉林省长春市副市长",89,163);
$z[2][4]['name']="title";
$z[3]=Array("field","",165,204);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",206,251);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-13 02:31:28",253,312);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近期，由中组部集中选派到地方交流任职的66名中青年干部陆续到任。选派的66名干部分别来自54个中央和国家机关部委。其中，国家工商总局办公厅主任、法学院校友滕佳材任吉林长春市副市长。 </p>\r\n<p align=\"left\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 滕佳材同志生于1964年，中共党员，系法学院1996级在职法律硕士，长期在中央国家机关工作。曾任中国消费者协会秘书长，国家工商行政管理总局消费者权益保护局局长，国家工商行政管理总局办公厅主任。现任吉林省长春市副市长。&nbsp;</p>\r\n<p align=\"left\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）<br />\r\n</p>",314,942);
$z[6][4]['name']="body";
$z[7]=Array("field","",944,983);
$z[7][4]['name']="litpic";

?>