<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","外国语学院举办第二届春季运动会",89,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院",200,249);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-03-11 02:22:47",251,310);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月9日，中国人民大学外国语学院分团委与学生会共同举办的第二届春季运动会正式拉开了序幕。运动会将持续近一个月，面向全院师生，还邀请了部分外籍教师参加，包含篮球、长绳、羽毛球等最受学生欢迎的体育项目，形式丰富，内容有趣。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 外国语学院分团委一贯重视学生课外体育活动，去年就成功举办了首届&ldquo;外院新生春季运动会&rdquo;。今年汲取以往的成功经验，将会为全院学生提供一个展示自我、健身娱乐的精彩平台。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王湘宁）</p>",312,913);
$z[6][4]['name']="body";
$z[7]=Array("field","",915,954);
$z[7][4]['name']="litpic";

?>