{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院副院长刘瑞教授出席中央统战部日本震灾影响研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-22 03:01:49{/dede:field}
{dede:field name='body'}<p>　　3月19日，经济学院副院长刘瑞教授应邀出席中共中央统战部举办的&ldquo;日本地震灾害后续影响与我们的应对策略&rdquo;研讨会。来自中国人民大学、中国社会科学院、中国科学院、新华通讯社、北京青年政治学院、中国华侨联合会等科研院校及相关机构专家学者出席研讨会。 <br />
　　中央统战部有关领导认真听取了专家学者对目前日本地震灾害在国内外各个领域的广泛影响所做的分析和判断。刘瑞教授就日本经济受到地震、海啸、核泄漏三重打击之后可能产生的后果，分别从8个重创产业和6个波及产业做了简略估计，对从四个渠道影响中国经济导致的可能后果做了初步分析，并提出了若干应对建议。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
