{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学2011新年音乐会隆重上演{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-12-31 04:24:33{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月30日晚，由中国人民大学艺术学院主办的2011新年音乐会在逸夫会堂隆重举行。中国人民大学校长纪宝成、常务副校长袁卫、副校长林岗、副校长杨慧林、校长助理刘向兵，学校办公室副主任侯书栋、国际交流处副处长石佳友，艺术学院党委书记兼副院长郑晓华、常务副院长徐唯辛、副院长赵方、副院长王英健，艺术学院顾问徐芳芳女士及学校相关部门领导出席了此次音乐会，与同学们共享了这场音乐盛宴。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhkzyzznf-z2bfkb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 旋律优美的女声小合唱《哈利路亚》和《月亮颂》拉开了音乐会的序幕；张放老师节奏独特、感情热烈的钢琴独奏《拥抱着你》和《我拥有节奏》使大家陶醉在优美的旋律中；郝丹丹老师的两首民歌独唱《山丹丹开花红艳艳》和《龙船调》歌声甜美纯朴，具有鲜明的民族风格和地方特色，和观众巧妙地互动很好地调动了现场的气氛；双簧管、大管与钢琴《普朗克双簧管、大管与钢琴三重奏第一乐章》乐曲优美精致、风趣幽默，大家的思绪也跟着快乐的音符起舞；杨毅老师的男中音独唱《小夜曲》和《啊！中国的土地》真挚的感情随歌声传递，感染了全场观众；室内乐团的同学们为观众完美演绎了《阿帕拉契亚之春》曲目，使观众听得如醉如痴；艺术学院交响乐团演奏的《第五交响曲第一、四乐章》把全场气氛推向了高潮。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhkzmbkmf-zlbfyn.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 整场音乐会以精湛的技艺、美妙的旋律向全校师生传递了新年的祝福。由艺术学院主办的&ldquo;新年音乐会&rdquo;已成功举办了10届，受到全校师生的热烈欢迎，已经成为中国人民大学校园辞旧迎新的一道视听盛宴。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkzyzznf-z2bfkb_lit.jpg{/dede:field}
