{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}首届新浪人大新闻学院实践创新奖学金颁奖典礼在人大举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/图 新闻学院 朗宇{/dede:field}
{dede:field name='pubdate'}2010-06-13 11:40:07{/dede:field}
{dede:field name='body'}<p>&nbsp;　　6月12日下午，首届新浪人大新闻学院实践创新奖学金颁奖典礼在逸夫会议中心举行。新闻学院学生网络团队&ldquo;新周网&rdquo;荣获团体奖，邵甜甜等15名同学荣获首届新浪人大新闻学院实践创新奖学金，其中特等奖2名，一等奖4名，二等奖9名。 <br />
<br />
　　新浪网执行副总裁陈彤先生、新浪网人力资源总监陈颖女士、新闻学院常务副院长倪宁教授、新闻学院党委书记高钢教授出席颁奖典礼，并为获奖学生和团队颁奖。颁奖典礼由高钢教授主持。 <br />
<br />
　　倪宁常务副院长在致辞中高度评价了新浪网的成就，并鼓励获奖同学努力学习、再接再厉，同时也感谢新浪网对人大新闻学院同学的肯定，也希望双方将来能在更广泛的领域内有进一步的合作与发展。 <br />
<br />
　　新浪网执行副总裁陈彤表示，互联网在当今媒介的地位日益凸显，需要大量新闻传媒行业的人才，新浪网在高校中设立奖学金，也是为了培养互联网优质新闻人才，关注新闻教育。 <br />
<br />
　　2008级本科生冯烁在颁奖典礼上代表全体获奖同学发言。她感谢新浪网给予的奖励及精神上的支持与肯定，并表示将继续勤勉学习和工作，取得更优异的成绩。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100619/z2kymzkzzyhhz2f-bmlbl.jpg" /></p>
<p>　　颁奖结束后，学院领导代表新闻学院向新浪网赠送礼物。 <br />
<br />
　　在接下来的互动提问环节中，在座同学分别就新浪微博、新浪对新闻人才的要求等问题与到会嘉宾进行了探讨和交流。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzkzznhybnf-yykfz.jpg" width="500" height="333" alt="" /></p>
<p>　　新浪人大新闻学院实践创新奖学金于2009年设立，此次为该奖学金的首次颁发，获奖团队和个人将获得进入新浪进行参观、实习的机会。 <br />
<br />
　　（编辑：苗育婧） <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzkzzyhhz2f-bmlbl_lit.jpg{/dede:field}
