{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第四届“比较法学术沙龙”在法学院成功举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-12-10 08:35:13{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月6日晚，第四届比较法学术沙龙在明德法学楼304教室成功举行。比较法教研室和国际法教研室共同邀请了法国斯特拉斯堡大学法学院教授NICOLAS NORD教授给同学们做了主题为&ldquo;欧洲人权公约对法国法律影响&rdquo;的精彩演讲。中国人民大学法学院国际法教研室党支部书记杜焕芳老师出席了本次沙龙并担任评议人。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; NORD教授为法国斯特拉斯堡大学法学院教授，专攻国际私法方向，长期致力于比较法研究工作，并曾经在罗马尼亚布加勒斯特大学、俄罗斯Nijni-Novgorod论坛，意大利博洛尼亚大学以及中国政法大学中欧法学院任课。在法国出版过多部著作及评论，并在法国斯特拉斯堡大学及欧洲议会的多个科研项目中任负责人。在本次讲座中，NICOLAS 教授从家庭成员权利、犯罪嫌疑人权利等方面阐明了欧洲人权公约与法国法律传统的不同之处，通过具体的案例说明法国本土法律受到了欧盟人权公约的挑战。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲结束后同学们踊跃提问，NICLOLAS教授回答了同学们关于欧盟人权公约生效前法国法律的适用、欧盟人权公约对法国人权保护进程的全面影响等问题。Nord教授对于人大法学院学生表现出的良好素质表示赞叹，对人大开展国际法、比较法教学和提高法学教育国际化的举措表示赞同和支持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次活动由比较法教研室的邬龙、郎宏、刘璇、李晶晶、李阳阳、李玉等同学负责组织。 &ldquo;比较法学术沙龙&rdquo;是由比较法教研室承办，由&ldquo;国际型比较法法律人才&rdquo;培养计划的同学参与组织的学术活动。&ldquo;比较法学术沙龙&rdquo;使用英文作为工作语言，邀请外国学者、律师等进行讲座，并就相关问题展开讨论，旨在扩大同学的国际学术视野，英文表达水平。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
