{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}迎接北京市党建和思想政治工作集中检查动员部署会召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}迎接北京市党建和思想政治工作集中检查领导小组办公室{/dede:field}
{dede:field name='pubdate'}2012-06-05 10:06:32{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月4日下午，中国人民大学召开迎接北京市党建和思想政治工作集中检查动员部署会议。程天权书记出席会议并讲话，牛维麟常务副书记主持会议并部署相关工作。学校迎检工作领导小组办公室成员和各分党委（党总支）书记参加会议。</p>
<p align="center"><img alt="" src="/uploads/allimg/c120620/zlhfzklzkhb22lf-yzf2k.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛维麟常务副书记就迎接北京市党建和思想政治工作集中检查的背景情况、学校已经开展的工作、下一步的工作安排、需要注意的事项和要求等作了介绍和部署。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记在讲话中强调了迎接检查工作的重要意义、工作原则和要求。程天权书记指出，开展集中检查不仅仅是就党务考评党务，而是对校党委领导学校事业发展情况的全面考察，是推动党建工作进一步规范化、制度化的重要途径。在迎接检查工作中，要坚持&ldquo;以检促建、以检促改、服务中心、重在建设&rdquo;的原则，以迎检工作为契机，系统回顾和总结过去五年来学校的党建和思想政治工作，以迎检工作为动力，扎实做好创先争优第三阶段和基层组织建设年的各项工作，为学校科学发展注入强大的精神动力和组织保障，以优异的成绩迎接党的十八大胜利召开和学校七十五周年校庆。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议正式下发了《关于认真做好迎接北京市党建和思想政治工作集中检查有关工作的通知》（人大校党字[2012]25号），学校迎检工作领导小组办公室和各专项工作小组、各分党委（党总支）将按照通知要求逐一落实各项工作。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，校长助理、学校办公室主任、校庆办公室主任刘向兵介绍了七十五周年校庆义卖活动的有关情况。</p>
<p>（编辑 杨默）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120620/zlhfzklzkhb22lf-yzf2k_lit.jpg{/dede:field}
