<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","新闻学院学生刘畅获“首都高校廉洁文化征文活动”二等奖",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",222,269);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-31 02:29:33",271,330);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月14日下午，北京市委教育工委与北京市教育纪工委在北京教育考试院举行&ldquo;首都高校廉洁文化征文活动&rdquo;颁奖大会，新闻学院2008级新闻学硕士生刘畅同学获二等奖，中国人民大学荣获本次征文活动&ldquo;优秀组织奖&quot;。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;首都高校廉洁文化征文活动&rdquo;由北京市委教育工委与市委教育纪工委联合组织，面向北京市高校征文。征文活动从2009年12月开始，历时5个月，40余所高校经过初评推荐了600多篇优秀稿件，经过专家复评、终审，确定了获奖作者和获奖单位。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />\r\n</p>",332,991);
$z[6][4]['name']="body";
$z[7]=Array("field","",993,1032);
$z[7][4]['name']="litpic";

?>