{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院学生刘畅获“首都高校廉洁文化征文活动”二等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-05-31 02:29:33{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月14日下午，北京市委教育工委与北京市教育纪工委在北京教育考试院举行&ldquo;首都高校廉洁文化征文活动&rdquo;颁奖大会，新闻学院2008级新闻学硕士生刘畅同学获二等奖，中国人民大学荣获本次征文活动&ldquo;优秀组织奖&quot;。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;首都高校廉洁文化征文活动&rdquo;由北京市委教育工委与市委教育纪工委联合组织，面向北京市高校征文。征文活动从2009年12月开始，历时5个月，40余所高校经过初评推荐了600多篇优秀稿件，经过专家复评、终审，确定了获奖作者和获奖单位。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
