{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院院长郭庆旺一行参加中国税务学会年会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-12-07 02:40:14{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月1日到4日，财政金融学院院长、中国税务学会副会长郭庆旺以及学会顾问安体富、常务理事岳树民、理事吕冰洋参加了在福州举行的中国税务学会2010年年会暨全国税收理论研讨会，并分别参加了中国税务学会常务理事会议和学术研究委员会会议。本次会议由中国税务学会主办，与会代表来自中国税务学会、各地税务局和税务学会、各高等院校和研究机构，共约230人参加。国家税务总局副局长解学智和福建省委常委、常务副省长张昌平分别到会祝贺并发表重要讲话。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次会议，主要是总结2010年全国税务研究工作、交流当年各课题研究成果，并讨论2011年课题研究任务。会上，受中国税务学会委托，副会长郭庆旺宣读了中国税务学会关于2010年税收学术研究优秀成果评审情况的通报，人民大学安体富教授的论文《中国中长期税制改革研究》、岳树民教授的论文《中国资本、劳动和消费平均有效税负的比较分析》分别获得2010年度全国税收研究成果优秀论文一等奖。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议期间，郭庆旺教授还主持了12月3日下午的税收理论研讨会，并对会议论文交流者的发言进行了精彩点评。安体富教授作了《中国中长期税制改革研究》专题报告，就中国宏观税负水平判断、优化税制结构、改革税种和完善税收体系等问题进行深入分析，提出了中国中长期税制改革的设计方案，引起与会代表的热烈回应。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
