{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘元春教授就宏观经济形势接受媒体采访{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月21日，经济学院副院长、经济研究所联席副所长刘元春教授先后接受新华社、北京电视台采访，点评2009年的宏观经济数据，并展望2010年中国宏观经济发展趋势。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='pubdate'}1264990290{/dede:field}
{dede:field name='litpic'}{/dede:field}
