<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院刘元春教授就宏观经济形势接受媒体采访",89,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",214,261);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月21日，经济学院副院长、经济研究所联席副所长刘元春教授先后接受新华社、北京电视台采访，点评2009年的宏观经济数据，并展望2010年中国宏观经济发展趋势。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",263,534);
$z[5][4]['name']="body";
$z[6]=Array("field","1264990290",536,586);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",588,627);
$z[7][4]['name']="litpic";

?>