<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","荷兰马斯特里赫特大学经济与工商管理学院副院长Tom van Veen访问经济学院",89,195);
$z[2][4]['name']="title";
$z[3]=Array("field","",197,236);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",238,285);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15日上午，荷兰马斯特里赫特大学经济与工商管理学院副院长Tom van Veen访问经济学院。中国人民大学经济学院党委书记、副院长张宇教授、院院长助理郑新业副教授会见。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c101124/z2mfbmzhfzzhnbf-zlhmz.jpg\" alt=\"\" /></p>\r\n<p><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 双方互相介绍了各自学院的办学特色、课程设置和国际化进程，并就教师互访、学生互换、联合培养等事宜展开了深入讨论，达成了初步合作意向。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当日，张宇书记还陪同纪宝成校长会见了该校校长Gerard Mols教授一行。 </p>\r\n<p>\r\n</p>",287,946);
$z[5][4]['name']="body";
$z[6]=Array("field","1287365108",948,998);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c101124/z2mfbmzhfzzhnbf-zlhmz_lit.jpg",1000,1092);
$z[7][4]['name']="litpic";

?>