{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}荷兰马斯特里赫特大学经济与工商管理学院副院长Tom van Veen访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15日上午，荷兰马斯特里赫特大学经济与工商管理学院副院长Tom van Veen访问经济学院。中国人民大学经济学院党委书记、副院长张宇教授、院院长助理郑新业副教授会见。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbmzhfzzhnbf-zlhmz.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 双方互相介绍了各自学院的办学特色、课程设置和国际化进程，并就教师互访、学生互换、联合培养等事宜展开了深入讨论，达成了初步合作意向。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当日，张宇书记还陪同纪宝成校长会见了该校校长Gerard Mols教授一行。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1287365108{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhfzzhnbf-zlhmz_lit.jpg{/dede:field}
