{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院张国凤副教授参加国防经济与装备发展学术研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-11-26 03:45:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月14日-15日，&ldquo;国防经济与装备发展学术研讨会暨中国国防经济研究中心2010年年会&rdquo;在武汉海军工程大学召开。经济学院教师张国凤副教授参加研讨会，提交了题为《我国军工企业进一步并购重组中需要注意的几个问题》的论文，并作专题发言。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该研讨会是目前我国国防经济领域最高规格的学术会议。近百名来自军委总部、国家经济动员办公室、国家发改委、地方政府相关部门、军地院校及科研院所的领导和专家学者与会。国家经济动员办公室主任周建平、国防大学副校长任海泉分别就&ldquo;我国国民经济动员建设中取得的成就及存在的问题&rdquo;、&ldquo;积极推进我国国防经济理论研究创新发展&rdquo;作了主题报告。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
