{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院举行2010年度夏普奖学金颁奖会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-12-20 11:17:21{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月18日上午，新闻学院2010年度夏普奖学金颁奖会在明德新闻楼611会议室举行，20名品学兼优的本科学生获得奖励，至此新闻学院五年内累计已有100名同学从夏普奖学金项目受益。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 夏普株式会社常务执行役员中国本部本部长菅野信行、夏普上海总代表处和北京代表处所长西冈一人、夏普公司北京代表处副所长郭赤恒，新闻学院院长赵启正、常务副院长倪宁出席了颁奖会。颁奖会由新闻学院党委副书记罗建晖主持。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllkmmlnnf-zknnl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 菅野信行先生代表夏普株式会社致辞，他回顾了夏普公司关爱他人、回馈社会的优秀传统，并表示进行公益慈善事业、为优秀学子提供资助也一直是公司注重的事业，他勉励获奖的同学继续努力，不忘回报社会。菅野信行先生为获得2010年度夏普奖学金的20名同学颁发了荣誉证书，并与他们一一合影留念。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻学院院长赵启正对夏普株式会社富有事业心、创造性的企业文化表示了认同，对获得夏普奖学金的同学们表示热烈祝贺。他勉励同学不仅要努力学习专业知识，更要开阔眼界，将来能够为跨文化交流作出贡献。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻学院常务副院长倪宁在致辞中感谢夏普株式会社为优秀同学提供奖学金，表示新闻学院与夏普株式会社将开展更加广泛的交流合作，希望同学们常怀感恩之心，将获得荣誉看做新的起点，努力学习。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年度夏普奖学金获得者代表也作了发言。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 倪宁常务副院长代表新闻学院向夏普株式会社赠送了附有2010年度夏普奖学金获奖同学名单的纪念品。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllnf2nlyf-2y2zh.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 夏普奖学金自2006年起开始在新闻学院颁发，今年已是第五届，夏普公司每年为新闻学院20名品学兼优、表现突出、家庭经济比较困难的同学提供合计五万元人民币的资助，至今已累计有100名新闻学院学生获得该奖学金。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnllkmmlnnf-zknnl_lit.jpg{/dede:field}
