<?php
$z[0]=Array("field","",32,60);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",72,101);
$z[1][4]['name']="typename";
$z[2]=Array("field","",124,152);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n<li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n",184,367);
$z[3][4]['titlelen']="160";
$z[3][4]['row']="10";

?>