<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院音乐系2003级毕业生潘磊荣获美国大都会歌剧院声乐比赛佐治亚州冠军",89,197);
$z[2][4]['name']="title";
$z[3]=Array("field","",199,238);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",240,293);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-27 10:43:48",295,354);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月20日美国大都会歌剧院声乐比赛在Kennesaw State University表演中心举办，男中音潘磊在此次比赛中勇夺佐治亚州州冠军，并获得晋级东南赛区的通行证。潘磊的演出赢得了当地观众和亚特兰大歌剧协会的高度好评。美国大都会歌剧院声乐比赛已有56年的历史，是国际声乐界最最重量级的专业比赛之一。此次获奖新闻分别被美国的多家报纸和网络媒体报道。 </p>\r\n<p align=\"center\"><img height=\"333\" alt=\"\" width=\"500\" src=\"/uploads/allimg/c110725/zlzzbyzhkhlbynf-2f2zyl.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 潘磊同学2003年就读中国人民大学艺术学院音乐系的声乐专业。经过在校五年的学习，他以优异的成绩毕业后赴美继续深造。在美国学习的同时他经常被邀请参加各种重要的演出。近日他又作为表演嘉宾与当地的交响乐团合作在美国第一所商务孔子学院揭牌仪式音乐会中表演《黄河颂》。演出获得了巨大的成功。当国家汉办网站采访他时，潘磊动情地说：&ldquo;今晚我真的特别激动，我从来没有想过能站在美国的舞台上演唱《黄河颂》，这个经历非常难忘。&rdquo;他还表示以后会和孔子学院一起，为传播中国文化艺术而努力。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n<br />\r\n</p>",356,1478);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhkhlbynf-2f2zyl_lit.jpg",1480,1573);
$z[7][4]['name']="litpic";

?>