{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院韩大元院长、龙翼飞副院长拜访法学院校友会会长祝铭山校友{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-12 09:58:19{/dede:field}
{dede:field name='body'}<p>　　4月6日下午，法学院院长韩大元教授、副院长龙翼飞教授专程到最高人民法院拜访了法学院校友会会长，原最高人民法院常务副院长、一级大法官、十届全国人大常委会委员、内务司法委员会副主任委员祝铭山同志。 </p>
<p>　　韩大元院长向祝铭山校友详细汇报了人大法学院的发展情况，介绍了近年来各项工作取得的成绩和未来的发展战略与规划，以及法学院60周年院庆筹备工作的进展情况。韩大元院长专门向祝铭山校友汇报了法学院创新办学模式、筹备成立中国人民大学律师学院的工作，并代表法学院热诚邀请祝铭山校友担任律师学院首任名誉院长。 </p>
<p>　　祝铭山校友欣然接受韩大元院长的邀请，同意担任中国人民大学律师学院名誉院长，并结合他在世界各国考察的经验为创办律师学院提出了指导意见。 <br />
<br />
　　祝铭山校友在与韩大元院长、龙翼飞副院长的会谈中，对人大法学院建设发展所取得的成就表示了肯定，他还深情回忆了在人民大学读书时的经历，并在法律人才培养等方面提出了希望和建议。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylnhb2kyf-2ybml.jpg" /><br />
<br />
　　祝铭山校友1957&mdash;1964年在中国人民大学法律系攻读本科和研究生。2005年中国人民大学法学院校友会成立，祝铭山校友被推选为会长。</p>
<p>（编辑　安娜）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylnhb2kyf-2ybml_lit.jpg{/dede:field}
