{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院德语专业孟虹副教授在威海参加“一战华工国际学术会议”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}网新社 彭大伟{/dede:field}
{dede:field name='pubdate'}2008-10-08 01:14:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月17日至19日，中国人民大学外国语学院德语专业孟虹副教授赴威海参加由威海市档案馆、山东大学文史哲研究院、美国卡拉玛祖学院、比利时鲁汶大学联合举办的&ldquo;一战华工国际学术会议&rdquo;，并就&ldquo;一战期间的中德关系及其对在德华人的影响&rdquo;做主题报告。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 国家档案局馆室司副司长王雁宾、山东省档案局局长张奎明出席会议，并对会议的召开表示祝贺。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会共有来自比利时、美国、法国、英国、加拿大、澳大利亚以及两岸三地的42位专家学者及华工后裔应邀出席，有18位学者在大会上作主题发言。与会学者围绕&ldquo;一战华工&rdquo;主题，从不同的角度加以解读，澄清了一些被时间烟云掩盖的历史记忆，使得会议探讨的话题相对集中而且深入，营造出良好的学术氛围，取得了丰硕的研究成果。在每场的主持点评和最后的自由讨论环节，各位专家学者围绕着华工的历史作用、华工与社会精英的互动关系、中国的国际化与民族认同、历史的叙述方式乃至上升到历史的认识论与方法论等问题展开讨论，进行了深入的探讨与交流。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
