{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院冯玉军教授主持的“中国宗教活动法律化研究”课题顺利结项{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-15 10:31:19{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月6日上午，由冯玉军教授主持的司法部重点课题&ldquo;中国宗教活动法律化研究&rdquo;结项鉴定会在明德法学楼725会议室举行。参加本次鉴定会的司法部领导有任永安主任，李建胜博士，评委专家分别是中国人民大学法学院孙国华教授、中国社会科学研究院刘作翔教授、国家宗教事务管理局张训谋主任、中央民族大学张俊杰教授、中国人民大学哲学院何虎生教授和魏德东教授。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fmhkbnbf-l2nzl.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 鉴定会首先由司法部李建胜博士介绍课题的基本情况，李建胜博士说，&ldquo;中国宗教活动法律化研究&rdquo;是司法部在2008年设立的重点课题，由冯玉军教授带领的课题组在规定时间内高质量完成了课题要求的任务。本课题成果丰硕，发表多篇有价值的学术论文，提交了很有份量的《中国宗教活动法制化调研报告》，该报告对司法部、国家宗教局、统战部等部门都有强的现实意义和参考价值，受到国家有关领导的高度重视。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 鉴定会第二个环节由课题主持人冯玉军教授作专题报告，冯玉军教授以丰富的数据，大量的图表，详实的材料分析向课题结项专家介绍了课题成果，其中，外国宗教事务及其法律治理研究包括亚洲、欧洲、美洲等14个国家的宗教法律治理情况；中国宗教活动法制化调研报告将中国的佛教、道教、伊斯兰教、基督教、天主教进行对比研究，并从东部、中部、西部不同领域进行比较研究。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 鉴定会第三个环节由专家鉴定组各评委进行评议，发表专家意见。经各位专家评议后，专家组认为，在建设中国特色社会主义法治国家，特别是在胡锦涛主席提出创新社会管理的背景下，宗教活动法制化研究具有很重要的意义。本课题组到全国各地开展了实地调研，与五大宗教人士举行了多次座谈，结合国外14个国家翻译的宗教活动相关资料，对详细的数据资料进行系统分析，发表了多篇有价值的学术论文，撰写出内容详实的宗教活动法制化调研报告，对国家加强宗教事务调整有很好的借鉴意义。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后所有专家一致将该课题成果评定为优秀，鉴定会也在热烈的掌声中圆满结束。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖） <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fmhkbnbf-l2nzl_lit.jpg{/dede:field}
