{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院召开学科建设与发展研讨暨2010年工作总结会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-12-24 11:07:45{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艺术学院学科建设与发展研讨暨2010年工作总结会，于12月18日上午在学院展厅召开。学院领导、各部门负责人及全院教职员工参加了会议。会议由学院党委书记兼副院长郑晓华主持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议首先由常务副院长徐唯辛传达纪校长在&ldquo;艺术学院调研会议&rdquo;中的重要讲话精神，并表示：纪校长一行在艺术学院调研，是推动艺术学院全面发展的重要契机。我们新一届党政班子有责任、有信心在任期内完成学校交给的各项任务，不辜负学校领导对我们的期望。在总结过去一年工作时，肯定了学院在教学、科研、成人教育培训等方面工作的成绩。根据学院规划，重新修订了985实施方案，进一步完善了本科教学改革方案。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在谈到学院的品牌建设及学科特色性时提出，我们要进一步加强国际性的跨文化交流，注重学术的共生与学科的共融，实行开放式教学，打破学科间的格局，注重学生的全面发展。继续扩建当代艺术中心、材料工作室、中国画研究中心、版画工作室，筹备成立表演系。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议期间，领导班子成员就各自分管的工作做了总结报告并提出了相关要求。会议上教师代表对学院的学科建设和发展提出了建设性的意见，各系主任总结了该系在过去一年中的工作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，学院党委书记兼副院长郑晓华在大会上做了总结性的讲话，并着重指出：我们要加强学院师资队伍建设，引进高端人才。要广泛深入研究国内外教学现状，找出学科教学的自我特性，注重独创性。在谈到学院管理工作时，指出了目前各部门在工作中存在的问题，并强调提高学院各层次的管理水平，以顺应学院的发展。最后，郑晓华书记代表学院党政领导班子，向一年来为学院发展、建设作出贡献的全体教职员工表示衷心的感谢，并致以新年祝福。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
