{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘元春教授向上级部门呈报多份《成果要报》获得重视{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-22 04:52:34{/dede:field}
{dede:field name='body'}<p>　　日前，刘元春教授向党和国家领导人以及上级部门呈报题为《流动性回收与新规划效应下的中国宏观经济》、《结构拐点性变化期间的次高速经济：我国&ldquo;十二五&rdquo;时期宏观经济与社会发展情况预测》、《高度关注中国收入分配差距不断扩大的新形成机制》等三份《成果要报》，获得党和国家领导人以及相关领导机构的重要批示，并向刘元春教授进行了进一步咨询。 <br />
　　刘元春教授还多次受邀参加中共中央政策研究室、国家发改委、国家财政部、中宣部、国务院发展中心等部门的内部宏观年度咨询会议，参与讨论宏观走势与物价形势。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
