<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院音乐系2009级康逸琨同学荣获“中国北京国际低音提琴音乐节首届低音提琴中国作品比赛”二等奖",89,221);
$z[2][4]['name']="title";
$z[3]=Array("field","",223,262);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",264,317);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-29 09:35:44",319,378);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由国际低音提琴协会举办的&ldquo;中国北京国际低音提琴音乐节首届低音提琴中国作品比赛&rdquo;中艺术学院音乐系09级低音提琴专业的康逸琨同学荣获中国作品二等奖。此次比赛有来自全国20多所所艺术院校和团体的一百多名选手参加。&nbsp;经过紧张激烈的角逐。康逸琨同学的演奏获得了评委会及业内专家的一致好评，为中国人民大学争得了荣誉。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110725/zlzzbyzhkbfnhyf-2znzkf.jpg\" width=\"333\" height=\"500\" alt=\"\" /></p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110725/zlzzbyzhkblnnzf-22kbzy.jpg\" width=\"333\" height=\"500\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n</p>",380,1076);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhkbfnhyf-2znzkf_lit.jpg",1078,1171);
$z[7][4]['name']="litpic";

?>