{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院音乐系2009级康逸琨同学荣获“中国北京国际低音提琴音乐节首届低音提琴中国作品比赛”二等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-12-29 09:35:44{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由国际低音提琴协会举办的&ldquo;中国北京国际低音提琴音乐节首届低音提琴中国作品比赛&rdquo;中艺术学院音乐系09级低音提琴专业的康逸琨同学荣获中国作品二等奖。此次比赛有来自全国20多所所艺术院校和团体的一百多名选手参加。&nbsp;经过紧张激烈的角逐。康逸琨同学的演奏获得了评委会及业内专家的一致好评，为中国人民大学争得了荣誉。 </p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhkbfnhyf-2znzkf.jpg" width="333" height="500" alt="" /></p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhkblnnzf-22kbzy.jpg" width="333" height="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkbfnhyf-2znzkf_lit.jpg{/dede:field}
