{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院MPA专业学位获批教育部专业学位研究生教育综合改革试点{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-01-18 09:37:25{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部近日下发了《教育部关于批准有关高等学校开展专业学位研究生教育综合改革试点工作的通知》，公共管理学院MPA专业学位顺利获批教育部专业学位研究生教育综合改革试点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 专业学位研究生教育综合改革试点工作是在我国研究生教育结构调整的大背景下提出的，其目的在于促进研究生专业学位教育更好地适应经济社会发展对高层次应用型人才的需要，逐步建立健全具有中国特色的研究生专业学位制度。作为我国人文社科领域主要专业学位之一的MPA的综合改革试点是此项工作的重要组成部分之一。据全国MPA教指委数据，全国（不含港澳台地区）共有146家MPA培养院校，此次有7所高校入选MPA综合改革试点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MPA综合改革试点工作周期为2010年9月至2013年6月。为了更好完成试点任务，人民大学从2010年10月份开始多次召开了MPA专业学位教育发展研讨会，讨论制定了试点工作具体实施方案，从发展战略、培养理念、课程和专业方向设置、学位论文撰写、师资建设、国际交流、社会实践、就业服务、管理制度等方面进行优化、改革和创新。其中，MPA专业方向优化工作已取得阶段性成果，其他各项试点具体工作正在逐步推进、落实中。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2001年成为全国首批24家MPA教育试点单位之一以来，人民大学MPA教育发展不断迈向新的台阶。在2006年国务院学位办组织的全国首批24所MPA试办院校评估中，人大MPA取得了25项指标全优的成绩（获此殊荣的仅两所高校）。在历届的全国MPA优秀论文评选中，人民大学入选的总篇数位居全国前茅。截至2011年1月1日，人民大学已招收3005名MPA研究生，其中2259名研究生已顺利获得公共管理硕士学位。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
