{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院董克用院长率代表团访问欧洲三国{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-11-16 08:51:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月1日&mdash;10日，公共管理学院院长董克用教授，李珍教授、于砚文老师应荷兰财政部的邀请和荷兰有关方面资助，访问了荷兰、挪威和芬兰。代表团参加了由Mn Services公司组织的为期两天半的2010中荷养老金峰会，与荷兰财政部副总司库、荷兰中央银行执行董事、荷兰行业养老金协会主任等专业人士进行了研讨交流，了解荷兰和欧洲的养老金体制架构和运行情况，分享了他们的经验，并对中欧的情况进行了对比研究。参加该会的还有我国人力资源社会保障部、财政部、中国人寿、中石油等机构有关部门负责人。会后，公共管理学院代表团顺访了奈耶诺德工商管理大学（Nyenrode Business University）。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbnnhhmfnmnf-zknfk.jpg" width="500" alt="" /></p>
<p align="center">图为访问团参加中荷养老金峰会</p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbnnhhmy2lnf-2l2kl.jpg" width="500" alt="" /></p>
<p align="center">图为代表团访问奈耶诺德工商管理大学</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 其后，代表团访问了挪威管理学院（Norwegian Management School, BI），看望正在该院学习的公共管理学院两位MPA研究生，董克用院长鼓励他们充分利用这一机会，努力学习，主动交流，从多方角度看待、研究中国问题，学院等着他们学成回国。该院教师表扬公共管理学院学生适应能力强，学习刻苦，给予了很高的评价。董克用院长还与该院公共管理系系主任Catherine Borve Arnesen女士、Kjell Eliassen教授总结了现阶段学生交流工作情况，并做出了未来学生交流计划。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbnnhhmnzmf-lzmlh.jpg" width="500" alt="" /></p>
<p align="center">图为代表团与在挪威学习的MPA研究生交流</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 代表团在芬兰访问了图尔库大学（University of Turku）东亚研究所、社会政策系和国际交流处，了解了对方主要研究学科和研究兴趣，探索了未来在教师互访、合作研究和学生交流等方面的合作机会。</p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbnnhbfn2bmf-hzhzy.jpg" width="500" alt="" /></p>
<p align="center">图为代表团在芬兰访问图尔库大学</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此外代表团还访问了赫尔辛基大学（University of Helsinki）社会科学学院，并在中国人民大学与赫尔辛基大学共建的孔子学院会见了中国人民大学在芬教师。在对欧洲大学的访问中，特别介绍了公共管理学院IMPA全英文硕士项目，得到了欧洲同事的高度关注。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbnnhbzzhfzf-bhyyn.jpg" width="500" alt="" /></p>
<p align="center">图为代表团访问赫尔辛基大学孔子学院</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhhmfnmnf-zknfk_lit.jpg{/dede:field}
