<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","杰赛普国际法模拟法庭辩论赛第八届中国赛区选拔赛近日在人民大学闭幕",89,191);
$z[2][4]['name']="title";
$z[3]=Array("field","",193,232);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",234,279);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-08 02:51:36",281,340);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月4日下午，杰赛普国际法模拟法庭辩论赛第八届中国赛区选拔赛历经4天精彩、激烈的角逐，在中国人民大学落下了帷幕。获得此次比赛的第一名是深圳大学，第二名是人民大学，北京外国语大学和中国政法大学并列第三。共有15名同学获得最佳辩手奖，人民大学学生张委峰、胡宇翔和聂笑阳以第一、第五、第六名的成绩获得该奖。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 比赛的前3名（四支队伍）将代表中国赛区于2010年3月21日赴美国华盛顿参加全球Jessup的比赛。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href=\"http://news1.ruc.edu.cn/102449/102450/102497/67798.html\">杰赛普国际法模拟法庭辩论赛第八届中国赛区选拔赛在人民大学开幕</a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）</p>",342,1129);
$z[6][4]['name']="body";
$z[7]=Array("field","",1131,1170);
$z[7][4]['name']="litpic";

?>