{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院室内乐演出小组访美归来{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-03-23 03:13:37{/dede:field}
{dede:field name='body'}<p align="left">　　应美国科罗拉多州立大学博尔德音乐学院院长邀请，中国人民大学艺术学院音乐系室内乐演出小组在副院长赵方教授率领下对其进行了访问、讲学和演出，近日载誉归来。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 科罗拉多州立大学建校已有一百三十四年，历史上培养出十多位若贝尔获奖者，博尔德音乐学院也因有世界顶尖级室内乐【塔卡什弦乐四重奏组合】而闻名于世。</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在为期一周的访问中，中国人民大学艺术学院室内乐演出小组专场表演了一台具有浓郁中国气息的音乐会，并和博尔德音乐学院的室内乐队共同演出了一台音乐会。美方音乐总监和同行们对人大艺术学院音乐系学生良好的室内乐演奏意识和上手能力给予很高评价，盛赞学生训练有素。赵方教授给博尔德音乐学院作曲系的学生和教授们用自己的作品就中国音乐的特色、现状和发展进行了专题介绍与演讲，富有中国魂韵的音乐和赵方教授生动鲜活的吟唱，使美国同行对中国音乐有了更深的了解。 </p>
<p align="center"><img height="333" alt="" width="500" align="middle" src="/uploads/allimg/c110725/zlzzbyzhn2l2b2f-hknfn2.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人大演出小组访问期间，博尔德城正好上演世界歌剧名作《唐.璜》。而在该剧中，担任男一号的男中音歌唱家吴蔚正是人民大学艺术学院音乐系05届声乐毕业生。开演前该剧艺术总监特地介绍了中国人民大学，整整三个半小时的《唐.璜》演出获得极大成功，全场为之沸腾。</p>
<p align="center"><img height="333" alt="" width="500" align="middle" body="" src="/uploads/allimg/c110725/zlzzbyzhn2khhf-hnl2zf.jpg" /></p>
<p align="left">　　一周的访问安排的十分紧凑而丰富，赵方副院长与美方院长就本科教学、硕士生博士生培养和各类管理问题进行了深入交流，获得了许多有益的经验。美方学校董事会全体董事也饶有兴趣地与人大艺术学院演出小组见面交谈沟通交流。</p>
<p align="left">（编辑：李露希）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhn2l2b2f-hknfn2_lit.jpg{/dede:field}
