{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院教育研究所所长秦惠民教授在日本讲学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-01-13 04:05:55{/dede:field}
{dede:field name='body'}<p>　　受聘为日本同志社大学特聘客座教授的公共管理学院党委书记兼教育研究所所长秦惠民教授，于2010年12月15日至2011年1月14日在日本进行为期一个月的讲学、学术交流及指导研究生等活动，并应邀以&ldquo;中国教育发展中的问题和基本政策&rdquo;为题，为该校教师和研究生进行了学术讲座。</p>
<p>　　同志社大学是日本成立最早的两所私立大学之一，于1875年建校，由第一位在海外取得学位的日本人新岛襄创办。在日本众多的私立大学中，同志社大学始终排名居前。同志社大学通过奖学金制度及互换留学计划等，促进国际理解与国际交流，是日本国际化程度较高的大学之一；美国斯坦福大学等一些欧美名校在该校设有办事处；该校与我校已有十年的校际合作与交流关系。</p>
<p>　　(编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
