{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院成功主办“回顾与展望：媒体侵权责任法律适用研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-04 02:35:04{/dede:field}
{dede:field name='body'}<p>　　2月26日上午，&ldquo;回顾与展望：媒体侵权责任法律适用研讨会&rdquo;在中国人民大学明德法学楼601国际学术报告厅隆重举行。本次研讨会由中国人民大学民商事法律科学研究中心、中国政法大学新闻与传播学院、中国政法大学传播法研究中心、北京市朝阳区人民法院及北京市海淀区人民法院联合主办。中国人民大学民商事法律科学研究中心主任杨立新教授、中国政法大学新闻与传播学院院长宋建武教授、北京市朝阳区人民法院白彦副院长、北京市海淀区人民法院宋鱼水副院长出席研讨会并致辞。</p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110419/zlflzn2fnmh2bhf-znymh.jpg" /></p>
<p>　　会议以我国二十年来媒体侵权责任理论与实践发展的回顾与展望为主题，探讨了在媒体多元化背景下，媒体侵权案件的处理及其新闻自由、个人权利与社会稳定保护之间的平衡等问题。受中国人民大学民商事法律科学研究中心委托，北京市朝阳区人民法院和海淀区人民法院对其二十年来审理的媒体侵权案件进行总结整理，撰写了调研报告。朝阳区法院副院长张雯法官及海淀区法院李颖法官分别就调研成果作主题报告。杨立新教授、中国政法大学李永军教授、李显冬教授、中国政法大学传播法研究中心执行主任徐迅教授、北京市高院民一庭副庭长马军法官等均就相关问题作主题发言。与会学者认为，我国并未制定专门的新闻法，新闻报道的规范主要通过新闻侵权的界定而展开。《侵权责任法》只规定了网络侵权，而未系统规定新闻侵权，但从《民法通则》实施以来，各级法院审理了大量媒体侵权的案件，积累了丰富的经验。媒体侵权案件的处理，既要注重保护受害人的合法权益，也维护媒体新闻报道的自由，使媒体在社会生活中发挥更为重要的作用。本次会议汇集了来自法学界、媒体界和法官、律师等司法实务部门的专家进行交流讨论，取得了丰硕的成果。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fnmkmhbf-2bnfm.jpg" /></p>
<p>　　另外，研讨会还对项目成果之一的《媒体侵权法律适用司法手册》的编制大纲进行了讨论完善，与会学者踊跃发言、各抒己见，对手册的编制提供了有益的建议。 </p>
<p>　　本次会议为民商法中心与欧盟合作项目&ldquo;中欧完善媒体法律保护项目&rdquo;内容（Promoting Legal Protection for the Media in China EIDHR/2010/227-111）。欧盟及英国驻华大使馆为此次会议提供了资助。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fnmnhykf-lmlhm.jpg" /></p>
<p>　　（编辑：贾晓旭）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fnmh2bhf-znymh_lit.jpg{/dede:field}
