{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院迎来2010年MPA“暑期集中”小学期{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-07-13 02:42:48{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月8日，公共管理学院2008级、2009级共400多名公共管理硕士（MPA）研究生在求是楼办理2010年&ldquo;暑期集中&rdquo;小学期报到手续，拉开了公共管理学院第九个MPA&ldquo;暑期集中&rdquo;小学期的帷幕。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次暑期集中的400多名MPA研究生来自全国各地各级单位，有来自中央办公厅、国务院办公厅、中央组织部等中央国家机关的公务员，也有来自地方基层的公务员。来自不同系统、不同地区的MPA研究生齐聚校园，他们将在学校、学院浓郁的人文氛围里，充分利用校内丰富的学习资源，共同学习，互相交流，齐头并进。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次暑期集中从7月8日至8月7日，历时一个月，期间为MPA研究生开设必修课和选修课共50多门；为此，公共管理学院集中了校内外相关领域最优秀的师资力量，聘请了60多位知名教师，其中包括多位著名教授和学科带头人为MPA研究生授课；同时还聘请了多位校外专家为学生开设专题讲座。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次暑期集中得到了学校领导的一贯重视和指导，也得到了学校相关部门一如既往的支持和配合。报到当天下午，公共管理学院副院长兼MPA教育中心主任许光建教授、MPA教育中心办公室副主任王春老师、谢佳宏老师到报到现场和学生宿舍亲切看望和慰问MPA研究生，许院长一行仔细查看了报到事宜和学生宿舍条件，并亲切询问学生们报到后遇到的困难和对学院各方面工作的要求。许院长表示，希望各位同学抓住宝贵学习机会，充分利用学校学院的师资力量、设备资源，努力学习，广交好友，充实而有收获地度过暑期集中学习生活。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
