<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","人大顺利举办“2009 中美哲学论坛——全球化背景下的哲学发展”",89,186);
$z[2][4]['name']="title";
$z[3]=Array("field","",188,227);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",229,274);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-07-28 06:10:11",276,335);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月16日，由中国人民大学哲学院和美国纽约古西堡州立大学哲学与历史系（Department of History and Philosophy, State University of New York at Old Westbury）合办的&ldquo;2009 中美哲学论坛&mdash;&mdash;全球化背景下的哲学发展&rdquo;（Chinese and American Philosophical Forum-Globalization and the Development of Philosophy）在中国人民大学逸夫会议中心举办。会议由哲学院副院长韩东晖教授主持。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，会议的工作语言为英文。校长助理、哲学院院长郝立新教授在致辞中指出，哲学院积极响应学校的国际化战略，此次举办与美国学者的英文研讨会是哲学院国际化的重要标志之一。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）</p>",337,1088);
$z[6][4]['name']="body";
$z[7]=Array("field","",1090,1129);
$z[7][4]['name']="litpic";

?>