{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大顺利举办“2009 中美哲学论坛——全球化背景下的哲学发展”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2009-07-28 06:10:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月16日，由中国人民大学哲学院和美国纽约古西堡州立大学哲学与历史系（Department of History and Philosophy, State University of New York at Old Westbury）合办的&ldquo;2009 中美哲学论坛&mdash;&mdash;全球化背景下的哲学发展&rdquo;（Chinese and American Philosophical Forum-Globalization and the Development of Philosophy）在中国人民大学逸夫会议中心举办。会议由哲学院副院长韩东晖教授主持。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，会议的工作语言为英文。校长助理、哲学院院长郝立新教授在致辞中指出，哲学院积极响应学校的国际化战略，此次举办与美国学者的英文研讨会是哲学院国际化的重要标志之一。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
