{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}学校召开2011年暑期学校工作专题办公会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}教务处   暑期学校项目办公室{/dede:field}
{dede:field name='pubdate'}2010-12-30 10:14:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月27日，学校在明德主楼13层第二会议室召开了&ldquo;2011年暑期学校专题办公会&rdquo;，会议由袁卫常务副校长、杨慧林副校长主持，暑期学校工作领导小组成员单位领导校长助理、财务处处长査显友、教务处处长洪大用、副处长旋天颖，学校办公室副主任王鹏、研究生院培养办主任宋东霞、科研处副处长杨燕萍、人事处副处长徐利、国际交流处副处长程鑫、后勤集团副总经理张国增出席了会议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议首先观看了2010年暑期学校专题片。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 洪大用处长汇报了2010年暑期学校的基本情况。本着&ldquo;再探索、再总结、再提升&rdquo;的原则，在各部门及全校各学院的共同努力下，暑期学校得以成功举办，取得了良好的社会反响，成果显著。2011年暑期学校的各项准备工作正在按部就班地推进，计划开设的课程也基本确定，根据各学院申报和初审，2011年暑期学校计划开设三大系列115门校级核心课程。明年暑期学校将进入第三个年头，计划实现&ldquo;常态化、制度化、品牌化&rdquo;，教务处将继续配合学校其他部门的工作，保证暑期学校持续健康稳定地发展。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议就暑期学校上课方式、师资聘请、助教制度、国际学生招生及住宿、教学管理、教学设施等问题进行了讨论，并作出了相应部署。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 袁卫常务副校长最后指出，暑期学校（国际小学期）是学校提升国际性的长期战略性安排，从2009年和2010年暑期学校基本情况看，不论是课程、学生、及暑期学校核心课程师资结构，暑期学校的各项指标都呈良好的上升状态。但与我们要达到的目标仍有差距。各部门、各学院要进一步研究并做好相关工作，共同协作，保证暑期学校办出特色、办出水平。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
