<?php
$z[0]=Array("match","<tr><td width=\"90%\" align=\"left\" valign=\"top\" style=\"PADDING-RIGHT: 20px; PADDING-LEFT: 20px;PADDING-BOTTOM: 20px;FONT-SIZE: 10.5pt; LINE-HEIGHT: 22px; TEXT-DECORATION: none\">[ÄÚÈİ]</td>",5,216);
$z[1]=Array("trim","£¨±à¼­£º(.*)£©<br />",221,275);
$z[1][4]['replace']="";
$z[2]=Array("trim","£¨±à¼­£ºÑîÄ¬£©",277,325);
$z[2][4]['replace']="";
$z[3]=Array("trim","£¨±à¼­£º°²ÄÈ£©",327,375);
$z[3][4]['replace']="";
$z[4]=Array("function","",380,411);

?>