{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长一行到艺术学院调研指导工作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/艺术学院  图/新闻中心{/dede:field}
{dede:field name='body'}<p align="center">　　<img alt="" width="500" height="333" src="/uploads/allimg/c101126/z2mfkyfbfynhklf-byfl2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月24日下午，纪宝成校长、袁卫常务副校长一行到艺术学院调研。校长助理、研究生院常务副院长吴晓求，校长助理、财务处处长查显友，校长助理、学校办公室主任刘向兵，学校办公室副主任侯书栋、人事处处长郭洪林、发展规划处处长胡娟、教务处处长洪大用、科研处副处长牟峰、研究生院副院长刘凤良、资产与后勤管理处副处长张卯等陪同参加调研。艺术学院领导及全体教授、副教授参加了调研会。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfbfk2mhlf-yzbfk.jpg" /></p>
<p>　　艺术学院常务副院长徐唯辛就艺术学院的学科建设、师资队伍、未来发展目标、目前面临的困难，以及取得的成绩和存在的不足等方面作了工作汇报。学院其他领导和各系部主任、专家教授、青年教师代表，也从不同角度，坦诚地向校长畅谈思想、建言献策。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfbfklhmmf-knkk2.jpg" /></p>
<p>　　袁卫常务副校长在听取了汇报后说，艺术学院既要突出艺术特殊性，又要关注平衡点，既要重视艺术创作，也要重视艺术理论的研究。并对艺术学院认真做好未来5-10年的学科规划和人才培养目标提出了新的要求。 </p>
<p align="center">&nbsp;<img src="/uploads/allimg/c101126/z2mfkyfbfkhzylf-nb2mm.jpg" alt="" /></p>
<p>　　纪宝成校长发表讲话，他首先对艺术学院建院十年以来所取得的成绩和对人民大学艺术氛围影响的日益扩大给予了充分肯定；对为艺术学院建院打下坚实基础的徐庆平院长和其他老一辈专家教授表达了崇高敬意；对克服重重困难为艺术学院发展付出努力的全体教职工表示感谢。 </p>
<p>　　纪校长说，艺术学院要建设一支&ldquo;在主流、入主流、壮主流、引领主流&rdquo;的师资队伍；在学科建设方面，要 &ldquo;体量适中，特而精&rdquo;，通过充分论证和反复调研，制订出一个切实可行的与学校相结合的艺术学院十年腾飞发展战略规划；在人才培养方面，应充分利用人大人文学科背景与学术资源，加强学科交叉融合，提高理论水平，提高外语水平，努力为国家培养优秀人才，为国家艺术繁荣服务、为国家文化产业发展服务；纪校长最后希望艺术学院新一届领导班子要发扬团结协作精神，保持&ldquo;清醒、团结、干事、奉献&rdquo;的工作作风，带领全院教职工共同努力，不断提升国际性，创办国内一流的艺术学科。 </p>
<p>　　纪校长还就艺术学院教学楼、人才引进、经费支持等方面进行现场办公。学校各部处负责人就艺术学院教师反映的问题作了解答。 </p>
<p>　　（编辑：刘伟伟）</p>{/dede:field}
{dede:field name='pubdate'}1290734968{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfbfynhklf-byfl2_lit.jpg{/dede:field}
