{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院宣传中心启动新闻培训{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-04-20 03:47:23{/dede:field}
{dede:field name='body'}<p>　　4月19日晚8点，由哲学院宣传中心组织的本学期系列培训讲座首讲在公教3205展开，《青年人大》副总编辑张静雯结合自己在《青年人大》评论部的实践经验和感受，为宣传中心成员讲解了评论的写作方法和技巧。 </p>
<p>　　此次培训内容和哲学院《爱智》报的内容改版相关，为了进一步增强报纸的可读性，《爱智》报将于近期对报纸第四版内容进行改版。哲学院宣传中心主任韩冰说：&ldquo;报纸的改版主要是为同学们提供崭新的领域，让同学们有施展才华的平台，可以按自己的想法写一些的东西。&rdquo; <br />
<br />

</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
