{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院学生赴日交流 展现人大本科生学术才华{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-07 03:11:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月26日至12月2日，作为&ldquo;日本中央三井信托银行经济学讲座&rdquo;的一部分，主要受日本中央三井信托银行资助，经济学院院长杨瑞龙教授、程华副教授率学生代表团赴日进行学术交流。代表团的成员全部为经济学院本科学生，包括经济学-数学（双学位）实验班的郭豫媚、任君秋拾、许龄珏、王丹娜、冯焌昽，经济学专业的王麒植、国际经济与贸易专业的陈嘉昊和国民经济管理专业的李宏伟。三年前曾赴日访问、目前在日本九州大学攻读硕士学位的夏诗芸也参与了学术交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在日期间，经院师生们先后访问了京都大学、同志社大学和早稻田大学和中央三井信托集团，考察了日本银行、东京证券交易所和Trustee Services信托银行。此次访问是人民大学经济学院本科生代表团第五次访问日本，也是人数最多的一次。经济学院的学生在多个大学用英文进行了学术演讲，我校本科生所显示出的扎实的经济学功底、突出的研究能力与流利的英语表达能力给日方的师生留下了深刻的印象，日方老师由衷地赞叹道，这显示出人民大学世界一流的人才培养质量。这次交流对于增进中日两国学生的交流与友谊，扩大人民大学经济学院在国际上的影响力产生了积极的意义。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月26日，经事先约定，杨瑞龙院长访问了京都大学经济学部，一方面具体落实前不久田中学部长访问人大时与经济学院签署的合作协议，另一方面与京都大学经济学部田中学部长和韩国庆北大学经济学院郑院长详细商谈了三校经济学院之间学分互认、互派交换留学生的项目。同时杨瑞龙院长也与京大经济学院就两院教师之间的交流项目也进行了深入细致的商讨。会谈取得了积极的成果。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月27日，杨瑞龙院长一行访问了日本的同志社大学，并带领经济学院八位同学参加了两所大学共同举办的学术交流会。同志社大学由日本近代著名思想家、教育家新岛襄于1875年创办，是日本四大著名私立大学之一，与我校曾签署合作交流协议。在交流会上，经济学院的陈嘉昊、李宏伟同学和日方Sasaki Ken、Hunase Norikazu同学分别用英文宣读了论文，并分别由Asano Koji、Niwa Sumiko和许龄珏、王丹娜做出评论。讨论会在热烈友好的氛围中进行。会后同志社大学的学生纷纷表示，中国学生们流利清楚的英文表达和熟练灵活的经济学运用能力给他们留下了深刻印象。正如同志社大学西村理教授在会议结束时所说，由人民大学的学生所显示出的中国人追求奋斗的精神值得日本学习，也希望中国同学能够再接再厉，在已有水平的基础上更上一层楼。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnhzmnnk2yf-zy2l2.jpg" /><br />
图为人民大学经济学院李宏伟同学在宣讲自己的论文</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月29日，代表团转赴东京，访问日本著名的私立大学早稻田大学政治经济学部。杨瑞龙院长与早稻田大学经济学科研究科长须贺教授等进行了会谈。我院在2005年与早稻田大学曾签署了以互派教师讲学为主要内容的合作协议，双方互派教师的交流活动已经持续了5年，每年来自对方学校的教师为硕士生上两个学分的课程，取得了良好的教学效果，合作取得了丰硕的成果。在这次会谈中，双方首先就互派教师授课项目的内容进行了磋商，对部分条款提出了修订意见。然后，双方又就互派留学生项目达成了初步意向，今后将进一步对具体细节进行沟通，力争从明年开始互派留学生。 </p>
<p align="center"><img height="332" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnh2ffllbf-2hfyl.jpg" /><br />
图为经济学院师生在早稻田大学的合影</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在会谈之后，举办了中国人民大学经济学院学生论文报告会。参加会议的除了我院学生外，还有早稻田大学的二十多名硕士研究生、博士研究生和教师。早稻田大学政治经济学须贺教授与人民大学的杨瑞龙教授分别致开幕词。我院本科生冯焌昽、任君秋拾、王麒植三位同学用英语宣讲了他们自己的论文&ldquo;A Dynamic Model of The Optimal Carbon Tax and Sustainable Development&rdquo;，&ldquo;A Study of Chinese Residential Electricity Demand Elasticities&rdquo;，&ldquo;Analysis of the mechanism of &lsquo;Dutch Disease&rsquo;&rdquo;。日方的博士研究生Adachi Tsuyoshi、Nakazono Yoshiyuki、Shirai Koji分别就三篇文章做出了认真、详尽的评论，宣讲者当场用英文回答问题，与参会人进行了热烈的讨论。会后三位评论的日本学生都表示，人民大学学生的经济学、数学能力和英文水平完全超出了本科三年级学生应有的水平，他们对人民大学的经济学教育实力表示由衷的钦佩。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnh2fzbmblf-lmknz.jpg" /><br />
图为经济学院学生任君秋拾在早大宣讲自己的论文</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月30日，在中央三井信托集团工作人员的陪同下，人民大学经济学院一行参观考察了中央三井信托银行日本桥支店、日本银行和东京证券交易所，听取了关于日本桥支店和日本银行发展历史的介绍，参观了两处的地下金库，在专业讲解员的引导下对东京证券交易所的历史及现状有了更为深入详细的了解。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnh2fznlmhf-hkm2b.jpg" /><br />
图为程华副教授带领同学们参观东京证券交易所结束时的合影</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月1日上午，人民大学经济学院同学在相关工作人员的陪同下参观了日本Trustee Services信托银行，学习了有关信托业的基础知识和Trustee Services银行的基本情况，听取了银行内部若干部门具体负责人细致周到的讲解，实地参观了部分主要部门。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月1日下午，杨瑞龙院长接受了日媒CSR report的采访，随后率经济学院一行与日本中央三井信托集团的高层领导举行了会谈。会谈正式开始前，中央三井信托银行国际部部长今井先生和国际部两位工作人员向同学们介绍了中央三井信托集团概要和日本的信托业。会谈开始后，中央三井信托集团田边总经理发表了热情洋溢的欢迎词，杨瑞龙院长就&ldquo;中央三井信托银行经济学讲座&rdquo;的实施情况做了介绍。继而由中国人民大学毕业生夏诗芸、2008级实验班学生冯焌昽、任君秋拾作为学生代表发言，表达了对中央三井信托集团的资助以及筱原总一教授定期来人大系统讲授中级微观经济学与中级宏观经济学表示感谢。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当天晚上，杨院长一行十人与中央三井信托集团董事们举行了会餐。中央三井信托银行特别顾问古泽发表开场致辞，希望中日双方能够继续合作，彼此学习。会餐中双方进行了友好而亲切的交谈，并合影留念。中国人民大学经济学院师生代表访问日本取得圆满成功。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnh2f2hykzf-bhzlh.jpg" /><br />
图为筱原总一教授、杨瑞龙院长、程华副教授、经济学院同学与日本中央三井集团董事们的合影</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 访日结束后，人民大学经济学院的八位同学纷纷表示，此次行程对他们扩展视野大有裨益。通过这种学习和交流方式，中日学生加深了对经济理论的理解，增进了对两国经济社会情况的了解，并结下了深厚的友谊。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnh2fbmymzf-yny2z.jpg" /><br />
图为人民大学经济学院学生与同志社大学经济学部学生的合影</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王宝奎；核稿：丁凯） <br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhzmnnk2yf-zy2l2_lit.jpg{/dede:field}
