<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","美联储闪辉博士访问公共管理学院土地管理系并与师生座谈",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",222,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-24 03:27:55",275,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月22日晚，应公共管理学院土地管理系邀请，美联储家庭和房地产金融研究统计部经济学家闪辉（Hui Shan）博士与土管系师生进行了座谈。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 座谈中，闪辉博士就&ldquo;美国房地产市场与联邦和地方政府税收问题&rdquo;做了主题发言，双方并就共同感兴趣的中美房地产市场差异、房地产税收状况等问题进行了较为深入的交流和探讨。闪辉博士对土地管理系博士生的研究方向和内容进行了了解，并结合自身的学术经历，从论文选题、研究方法等方面给土地管理系博士生介绍了从事研究工作的心得体会，为大家提供了宝贵的经验借鉴。北京大学国家发展研究院龚强教授，公共管理学院土地管理系主任吕萍教授，孟繁瑜老师和余华义老师参加了座谈。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟） <br />\r\n</p>",336,1130);
$z[6][4]['name']="body";
$z[7]=Array("field","",1132,1171);
$z[7][4]['name']="litpic";

?>