<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","王晓军教授受邀出席第 28 届国际精算师大会",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",210,257);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-06-05 07:50:42",259,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<HTML><HEAD><TITLE> 王晓军教授受邀出席第 28 届国际精算师大会 </TITLE><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><style><!--\n .iframestyle{height:expression(1);aho:expression(autoResize()) \n}\n-->\n</style>\n<script>\nfunction autoResize()\n{\ntry\n{\n document.all[\"showDemand\"].style.height=showDemand.document.body.scrollHeight\n}\n catch(e){}\n}\n </script><body><P>&nbsp;&nbsp;&nbsp; 5月28日到6月2日, 统计学院王晓军教授接受国际精算学会的邀请出席了在法国巴黎举行的第28届国际精算师大会。我国仅有两位教授受邀请出席这次会议。 </P>\r\n<P>&nbsp;&nbsp;&nbsp; 国际精算师大会是由国际精算学会组织的最具影响力的全球精算盛会，每四年举行一次,是全球最具规模和最高层次的精算领域科学会议。&nbsp; </P>\r\n<P>&nbsp;&nbsp;&nbsp; 来自世界各地的1400多名从事精算理论和实务工作的人员参加了今年的盛会，会议围绕精算业在全球各地的理论和实务上面临的前沿问题所展开。</P>",320,1211);
$z[6][4]['name']="body";
$z[7]=Array("field","",1213,1252);
$z[7][4]['name']="litpic";

?>