{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}最高法刑庭副庭长李睿懿做客德恒证据学论坛 主讲刑事证据的审查认定{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院 文/贾萌 余龙祥{/dede:field}
{dede:field name='pubdate'}2010-12-24 11:06:35{/dede:field}
{dede:field name='body'}<p>　　12月22日晚，德恒证据法学论坛第六十九讲&mdash;&mdash;&ldquo;刑事证据的审查认定：从人命关天的死刑复核谈起&rdquo;在人民大学明德法学楼602会议厅举行。本次论坛由最高人民法院刑事审判第三庭副庭长、中国法学会审判理论研究会刑事审判专业委员会委员李睿懿主讲，中国人民大学法学院刘品新副教授主持了该次论坛。 </p>
<p>　　在论坛中，李睿懿副庭长从坚持证据裁判原则、关于严格死刑案件的证明标准、关于秉持无罪推定的态度、客观性证据优先、关于科学同一认定的方法、实体审查与程序审查并重等多个角度向听众讲解了最高法院以及目前我国法院系统在处理刑事证据问题时的一些做法和经验。在演讲过程中，李副庭长结合了许多人们熟知的案例，用通俗的语言使听众理解知晓死刑复核案件中刑事证据的审查认定情况，精彩的演讲博得在场观众的热烈掌声。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110113/z2mhnnhmyknymhf-ynbyz.jpg" /></p>
<p>　　在最后的互动阶段，参加论坛的学生们积极地向主讲人提出了问题，论坛为同学们揭示了死刑复核案件中证据审查认定的神秘面纱。论坛结束后，同学们纷纷到李副庭长身边请他为自己的书签名留念。</p>
<p>　　（编辑：易晨）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmyknymhf-ynbyz_lit.jpg{/dede:field}
