{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}温海明副教授在美国哲学年会（APA）发表论文{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2011-01-10 10:37:56{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年12月29日，中国人民大学哲学院温海明副教授应&ldquo;美国中国哲学家协会&rdquo;（ACPA）之邀，赴波士顿参加美国哲学年会（APA）东部会议（American Philosophical Association Eastern Division Meeting 2010, Boston），发表了论文《作为心物一体的中国哲学意识：从宋明理学认识论发展的角度看Chinese Philosophical Sensibility as Continuity of Mind-heart and Things/events: A Systematic Reconstruction of Neo-Confucian Epistemology》。波士顿儒家的代表人物南乐山（Robert Neville）对他的发言给予很高的评价，认为他的研究将在中西比较哲学领域内开辟一个新的视域。他的发言引起了与会众多中外学者的热烈讨论，尤其是如何处理中国哲学传统中的认识论意识和道德哲学意识之间的问题。美国哲学年会是美国哲学界一年一度的盛会，来自世界各地的学者齐聚一堂，发表并交流他们最新的哲学研究成果。 <br />
</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnbmhhykbnf-hbmfz.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图为温海明副教授在美国哲学年会(APA)发表论文并回答问题，他的论文评论者为波士顿大学著名教授、波士顿儒家的代表人物南乐山(Robert Neville)教授。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 温海明副教授曾在美国从学于世界著名比较哲学家安乐哲（Roger Ames）教授和成中英教授，深受他们毕生在国际学界推介中国哲学的影响，是中国大陆唯一连续五、六年来每年参加美国哲学年会的学者。他多年来的努力增进了中国人民大学哲学院的国际性，促进了学校中国哲学研究与世界同行之间的沟通和对话，为中国大陆的中国哲学研究越来越有国际性的影响作出了贡献。 </p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnbmhhykbnf-hbmfz_lit.jpg{/dede:field}
