{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院召开2010年离退教师新年茶话会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月23日，2010年经济学院离退教师新年茶话会在明德主楼734会议室召开。经济学院六十余名离退教师参加了茶话会。经济学院院长杨瑞龙教授，党委书记张宇教授，党委副书记明占生、丁凯等出席。新年茶话会由杨瑞龙院长主持。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhymfzbkkf-z2hbbf.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长首先代表学院向参会的离退老教师表达了诚挚的节日问候，祝他们新年快乐、身体健康，并向大家赠送了节日礼物。他向离退教师介绍了学院2009年在教学、科研、国际交流和社会服务等方面取得的工作成绩，以及在提升国际性、推进教学改革等所取得的重要进展。杨瑞龙院长强调，经济学院始终坚持马克思主义经济学的指导地位，发展有中国特色、中国气派的经济学，并将继续努力保持应用经济学和理论经济学在全国经济学科中的领先地位。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 茶话会上，离退教师进行了亲切而热烈的交流。老教师代表学院领导对于离退老教师长期以来的关怀表示感谢，对于学院2009年在学科建设等方面取得的巨大成就感到欢欣鼓舞和无比欣慰，并祝愿学院在2010年事业有更大的发展，再创新的辉煌。许多老教师还就马克思主义经济学的发展前景和经济学院提升国际性等问题提出了自己的建议，杨瑞龙院长表示，要认真研究老教师们的宝贵建议，以优异的工作成绩回报每一位&ldquo;经济学院人&rdquo;。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1262051301{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhymfzbkkf-z2hbbf_lit.jpg{/dede:field}
