{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学召开化学学科规划论证会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/发展规划处 图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-01-07 08:55:06{/dede:field}
{dede:field name='body'}<p>　　12月30日上午，中国人民大学化学学科规划论证会在明德主楼第一会议室召开。来自兄弟院校的专家学者们与人民大学专家学者一道，就人民大学化学系学科规划等问题进行了认真的论证和深入的研讨。纪宝成校长出席会议并做重要讲话。会议由袁卫常务副校长主持。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnlfffnklf-k2mhy.jpg" /></p>
<p>　　论证专家组由清华大学化学系主任张希院士、北京大学化学学院前院长高松院士、北京大学化学学院黄春辉院士、北京大学化学学院院长吴凯教授、清华大学化学系副主任李艳梅教授组成。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnlffz2zylf-nkb2z.jpg" /></p>
<p>　　纪宝成校长重申了人民大学理工科建设&ldquo;有基础、相关联、高起点、入主流，力争高水平&rdquo;的建设思路，指出要建设高水平的理工科，保持体量，突出特色，提升质量。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnlffz2ybkf-mhb2z.jpg" /></p>
<p>　　袁卫常务副校长阐释了化学学科建设的基本方向，坚持基础学科建设的方针。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnlffzlfnhf-zfk2bb.jpg" /></p>
<p>　　化学系曹廷炳主任介绍了化学系的基本情况、一期建设成效和二期建设规划。与会专家针对化学系的现状和未来规划，提出了相关的建议和意见。大家认为：一、化学系的学科规划思路新颖，符合建设一个有特色的化学系的整体要求；二、化学学科作为基础学科，发展方向不能因为强调应用而单一化，还应加强学科基础建设，处理好基础与应用、重点发展与全面提升的关系；三、化学系的发展规划抓住了&ldquo;引进高水平人才&rdquo;这一关键，建议进一步处理好高水平人才与学科发展的关系；四、化学系的进一步发展仍需要学校继续加大投入。</p>
<p>　　学校相关职能部门就化学系面临的实际问题，提出了相应的解决办法。</p>
<p>　　研究生院、发展规划处、教务处、科研处、人事处、实验室建设与设备管理处、财务处、资产与后勤管理处等部处负责人及化学系学科责任教授和相关工作人员参加会议。 </p>
<p>　　(编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnlfffnklf-k2mhy_lit.jpg{/dede:field}
