<div id="jianzhang">
<dl>
<dt><a href="[field:arcurl /]" class="l">[field:title /]</a><a href="[field:arcurl /]" class="r">²é¿´ÏêÇé&gt;&gt;</a></dt>
<dd>
<div id="focusImg">[field:image /]</div>
<div id="jianzhangRight">
<div id="miaoshu"><a href="[field:arcurl /]">[field:description /]</a></div>
<div id="anniu"><a href="[field:arcurl /]" target="_blank"><img src="/_res/btn_wyzx.gif" alt="" /></a><a href="[field:arcurl /]" target="_blank"><img src="/_res/btn_wybm.gif" alt="" /></a></div>
</div>
<div class="c"></div>
</dd>
</dl>

</div>