{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学社会与人口学院辩论队应邀参加北京大学第一届社会学学术辩论赛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学生记者 厉玲玲 周庆誉{/dede:field}
{dede:field name='pubdate'}2009-04-14 09:01:20{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月12日，应第六届北京大学社会学文化节组委会与北京大学社会学系学生会、辩论队的邀请，人民大学社会与人口学院辩论队与北京大学辩论队就&ldquo;判断行为善恶的标准是效果还是动机&rdquo;进行了一场激烈的辩论。最终，张唤同学获得了&ldquo;全场最佳辩手&rdquo;的称号。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次比赛是北京大学社会学系本着&ldquo;学术探讨，交流共进&rdquo;的宗旨举办的第一届社会学学术辩论赛，旨在对辩题进行社会学学术方面的深入探讨。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 比赛在北京大学英杰交流中心第一会议室进行，在简单地介绍了双方辩友之后，比赛正式开始。人民大学社会与人口学院代表梁四维、胡乔宪、钟源、张唤同学团结合作，步步为营，展现了社会与人口学院辩论队的风采。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 首先，梁四维同学从动机的不可测性、不可控性、不可把握性三方面论述了把动机作为判断标准的不合理性，进而说明了效果的易知与可控。立论环节，他通过例证、引用等多种手段，全面而深入地阐释了己方观点。在对方辩友立论陈词结束之后，胡乔宪同学进行了补充陈述，她对对方在立论中所提到的&ldquo;动机可推断&rdquo;、&ldquo;动机更具信度和效度&rdquo;等观点进行了一一驳斥，并进一步强调了己方观点。在更精彩的攻辩环节中，钟源同学利用东京地铁沙林毒气事件这一实例驳斥了对方将动机作为判断标准具有信度效度的观点。场面激烈，异常精彩。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 之后是全场比赛最为紧张激烈的环节&mdash;&mdash;共计八分钟的自由辩论。在自由辩论中，双方辩友展示了清晰的逻辑、敏锐的思维、自信的气度和犀利而不乏幽默的语言。台下观众不时拍手叫好。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后的总结陈词环节，双方的四辩相继发言，对整场比赛进行了梳理，对对方的疏漏加以批驳。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由于本场比赛重在学术交流，双方的准备充分，场上不断出现社会学专业名词和大家的名字。双方辩友在赛后的自由交流中都表示，这样的比赛交流，不仅仅是辩论技巧的切磋，更是社会学学术和兄弟院系感情的交流。人民大学社会与人口学院的梁四维同学作为院学生会副主席感谢了北大方面的邀请，并向对方发出了诚挚邀请，希望双方加强联系、促进交流。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：杨坤峰）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
