{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}来自中国的斗牛士：艺术学院音乐系毕业生在美国歌剧舞台崭露头角{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-05-17 09:20:38{/dede:field}
{dede:field name='body'}<p>　　近日，在美国亚特兰大RIALTO表演中心成功上演了法国歌剧《卡门》，担任该剧斗牛士这一重要角色的是中国人民大学艺术学院音乐系09级毕业生潘磊。他出色的演唱和表演赢得了全场观众雷鸣般的掌声并得到了业内人士的高度好评，美国《多维时报》评语为&ldquo;来自中国的斗牛士，华人音乐界的骄傲&rdquo;。</p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110725/zlzzbyzhnyfyybf-zhbyf.jpg" alt="" /></p>
<p>　　潘磊当年以专业第一名的成绩考入人民大学艺术学院音乐系，在校期间表现优秀，曾被两次推荐去美国表演和学习。现在他获得全额奖学金在佐治亚州立大学音乐学院攻读硕士研究生。世界歌剧大师、卡迪夫声乐比赛评委霍恩女士这样评价到：&ldquo;潘磊是一位来自中国的声乐天才，将会成为美国的传奇&rdquo;。 </p>
<p>　　观看演出的中国人民大学82级校友岳京生先生这样评价到：&ldquo;我有三个没想到， 一没想到在竞争激烈的美国歌剧舞台上主角是位来自中国的年轻人。二没想到他的表现如此出色，毫不逊色于有着丰富经验的美国演员并且赢得了A角出场的表演机会。三没想到这位年轻人竟是出自我亲爱的母校&mdash;&mdash;中国人民大学。&rdquo; </p>
<p>　　（编辑：安娜）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhnyfyybf-zhbyf_lit.jpg{/dede:field}
