{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}著名统计学家赵民德教授讲授“如何提高学术研究能力并撰写高质量的学术论文”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-09-23 04:35:40{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp;&nbsp;应中国人民大学统计学院的邀请，9月20-22日，台湾著名统计学家在统计学院讲堂作了主题为“如何提高学术研究能力并撰写高质量的学术论文”的讲演， 此次讲演是统计学院将要举行的“学术研究与SCI和SSCI论文发表”系列讲座的第一场。中国人民大学统计学院的专任教师和研究生以及部分外院系和外单位人员到场听取了演讲。　　</P>
<P>&nbsp;&nbsp;&nbsp; “学术研究与SCI和SSCI论文发表”系列讲座的内容将涵盖“怎样做研究”、“学术研究与论文发表”、“SCI和SSCI学术论文案例分析”三个专题，共十个部分。　　</P>
<P>&nbsp;&nbsp;&nbsp; 赵民德教授是台湾中央研究院统计科学研究所研究员，著名华人统计学家，美国数理统计学会院士、台湾行政院主计处顾问、国立政治大学商学院民意与市场调查研究中心顾问、中国统计学社理事，曾任七个国际知名学术期刊的编辑委员，现任三个学术期刊的编委，是SCI杂志“Statistica Sinica”的创办人和前任主编，在统计研究特别是SCI和SSCI论文发表方面具有丰富的经验。</P>
<P>&nbsp;</P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
