<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","法学院党委、工会为教职工举办专题健康讲座",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",210,255);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-03-16 09:20:15",257,316);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月10日下午，法学院党委、工会邀请了北京大学人民医院心脏中心的陈源源主任医生为全院教职工作了题为&ldquo;心脑血管疾病的自我管理&rdquo;的健康讲座。院党委书记兼副院长林嘉教授主持了讲座。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;陈源源医生结合高校教职工的工作特点，对&ldquo;三高&rdquo;的危害，高血压等疾病的认知状况、易患因素、心脑血管疾病的自我管理作了讲解，介绍了治疗心脑血管疾病的&ldquo;两架马车&rdquo;，即改善生活方式的治疗和药物治疗相结合的方法。陈源源医生还就教职工提出的一些问题现场作了解答。<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林嘉书记指出，全院教职工在紧张工作的同时一定要注意身体健康，了解与工作方式和生活习惯有关的常见心脑血管疾病及其预防知识，以健康的状态更好地投入到工作之中。<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 广大教职工对学院工会组织的健康讲座活动非常满意，通过讲座了解更多的健康知识，并对陈源源主任医师表示感谢。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （文：路磊&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 编辑：陈汉南）</p>",318,1408);
$z[6][4]['name']="body";
$z[7]=Array("field","",1410,1449);
$z[7][4]['name']="litpic";

?>