{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院温海明副教授赴日本参加“儒学与法华经”国际学术研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2011-03-14 12:51:43{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月28日至3月7日，哲学院温海明副教授受邀赴日本参加&ldquo;儒学与法华经&rdquo;国际学术研讨会，他在会上发表了英文论文&ldquo;Two Versions of Desire-based Subjectivism: A Comparative Study on the Analects and the Lotus Sutra&rdquo;（《两种基于意欲的主观主义版本：关于&lt;论语&gt;与&lt;法华经&gt;的比较哲学研究》）。他的论文从当代元伦理学的相关哲学问题入手，通过考察《论语》中&ldquo;我欲仁斯仁至矣&rdquo;与《法华经》&ldquo;十如是&rdquo;的哲学内涵，探讨儒佛在获得最高智慧之途径的同异。他的论文得到与会来自美国、英国、日本等国的哲学、宗教与东亚研究的教授们的共鸣和好评。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 哲学院客座教授、英国伦敦国王学院中国中心主任姚新中教授也参加了研讨会，他发表的论文是&ldquo;Compassion in the Lotus Sutra and Benevolent Love in the Analects &ndash; A Comparative Study&rdquo;。该研讨会的主办方是日本立正佼成会，会议主要召集人Gene Reeves教授为美国芝加哥大学荣休教授，国际著名的研究佛教和《法华经》的专家；目前是人民大学哲学院特聘教授，用英文为我校师生主讲《法华经》等相关课程。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该国际学术研讨会已经在世界各地连续主办了十几届，历年参会者主要是欧美各国研究中国宗教、哲学以及东亚研究的教授，哲学院的张风雷和魏德东教授前些年曾获邀至美国、日本等地参与该会。 <br />
</p>
<p>（编辑&nbsp; 燕燕）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
