<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公共管理学院举行首届全日制（双证）MPA毕业生座谈会",89,176);
$z[2][4]['name']="title";
$z[3]=Array("field","",178,217);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",219,270);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-28 09:41:00",272,331);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　为总结全日制（双证）MPA教育举办经验，进一步提升MPA培养质量，完善教学管理和服务工作，6月23日下午，公共管理学院MPA教育中心组织召开了首届（2007级）全日制（双证）MPA毕业生座谈会。 </p>\r\n<p>　　公管学院院长董克用教授、全国MPA专业学位教育指导委员会秘书长朱立言教授、副院长兼MPA中心主任许光建教授、院党委副书记王丹老师等公管学院领导以及全体2007级全日制（双证）MPA毕业生参加了座谈。 </p>\r\n<p align=\"center\">&nbsp;<img alt=\"\" src=\"/uploads/allimg/c101124/z2mfbnnhynkkykf-znfmy.jpg\" /></p>\r\n<p>　　出席座谈会的公管学院领导和老师与2007级全日制（双证）MPA毕业生汇聚一堂，分享了全日制MPA毕业班同学三年来的心得和体会，听取了同学们对公管学院MPA教育工作的意见和建议，就MPA教学培养工作进行了全面的座谈和研讨。 <br />\r\n</p>",333,1082);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c101124/z2mfbnnhynkkykf-znfmy_lit.jpg",1084,1176);
$z[7][4]['name']="litpic";

?>