{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院举行首届全日制（双证）MPA毕业生座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-06-28 09:41:00{/dede:field}
{dede:field name='body'}<p>　　为总结全日制（双证）MPA教育举办经验，进一步提升MPA培养质量，完善教学管理和服务工作，6月23日下午，公共管理学院MPA教育中心组织召开了首届（2007级）全日制（双证）MPA毕业生座谈会。 </p>
<p>　　公管学院院长董克用教授、全国MPA专业学位教育指导委员会秘书长朱立言教授、副院长兼MPA中心主任许光建教授、院党委副书记王丹老师等公管学院领导以及全体2007级全日制（双证）MPA毕业生参加了座谈。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c101124/z2mfbnnhynkkykf-znfmy.jpg" /></p>
<p>　　出席座谈会的公管学院领导和老师与2007级全日制（双证）MPA毕业生汇聚一堂，分享了全日制MPA毕业班同学三年来的心得和体会，听取了同学们对公管学院MPA教育工作的意见和建议，就MPA教学培养工作进行了全面的座谈和研讨。 <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhynkkykf-znfmy_lit.jpg{/dede:field}
