<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","社会与人口学院翟振武、段成荣教授受聘担任第六次全国人口普查顾问",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","社会与人口学院",232,285);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-12 02:26:01",287,346);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，国务院第六次全国人口普查领导小组办公室召开会议，宣布成立&ldquo;国务院第六次全国人口普查顾问咨询组&rdquo;。社会与人口学院院长翟振武教授和学院党委副书记、人口学系主任段成荣教授受聘担任顾问。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，共有来自中国人民大学、北京大学、清华大学和中国社会科学院等单位的9位专家学者受聘担任第六次全国人口普查顾问。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />\r\n</p>",348,895);
$z[6][4]['name']="body";
$z[7]=Array("field","",897,936);
$z[7][4]['name']="litpic";

?>