{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院翟振武、段成荣教授受聘担任第六次全国人口普查顾问{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2010-05-12 02:26:01{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，国务院第六次全国人口普查领导小组办公室召开会议，宣布成立&ldquo;国务院第六次全国人口普查顾问咨询组&rdquo;。社会与人口学院院长翟振武教授和学院党委副书记、人口学系主任段成荣教授受聘担任顾问。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，共有来自中国人民大学、北京大学、清华大学和中国社会科学院等单位的9位专家学者受聘担任第六次全国人口普查顾问。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
