<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","丹佛大学赵穗生教授来公共管理学院举办讲座",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",210,261);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-21 09:52:58",263,322);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　2011年3月16日下午，美国丹佛大学国际关系学院终身教授、美中合作中心执行主任、《当代中国》英文期刊主编赵穗生教授受邀来公共管理学院，为公共管理学院师生举行了一场题为&ldquo;奥巴马时期的中美关系&rdquo;的主题演讲。讲座由刘昕教授主持。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110419/zlflzn2bh2mmmhf-zm2m2.jpg\" /></p>\r\n<p>　　在讲座中，赵穗生教授从中美关系的源头讲起，系统分析了中美关系的发展变化，尤其是奥巴马就任美国总统以来的中美关系发展、演变情况，为大家理解中美关系的发展脉络以及当前的国际局势提供了很好的线索。赵穗生教授还与现场师生就中美关系中的一些敏感问题进行了热烈的对话。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110419/zlflzn2bhlhfkzf-2mhll.jpg\" /></p>\r\n<p>　　除此之外，公共管理学院董克用院长还与赵穗生教授进行了简短的交流，刘昕教授、刘伟老师陪同会见。</p>\r\n<p>　　(编辑：席嘉怡)</p>",324,1188);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflzn2bh2mmmhf-zm2m2_lit.jpg",1190,1282);
$z[7][4]['name']="litpic";

?>