{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院91级财政班举行毕业15周年聚会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-04-21 03:20:40{/dede:field}
{dede:field name='body'}<p>　　4月15&mdash;18日，23名来自全国各地的人民大学财政金融学院91级财政专业同学相聚在美丽的西子湖畔，这是他们毕业15年后的又一次团聚，也是该班继毕业5周年和10周年后的第三次大规模庆祝活动。 </p>
<p>　　91级财政班共有37名同学。目前，除了几位同学在国外从事教学、研究和经商外，绝大部分分布在国内的财经领域，从事房地产、证券、银行、税务、财务和政府管理等工作，都已经成为各自单位的中坚力量。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlkhyhhbhyf-nybbb.jpg" /></p>
<p>　　在人间天堂的杭州，大家共赏美丽的西湖美景和西溪湿地风光，回顾了在校期间的学生生活，交流了毕业15年来的人生体验，并展望了美好的新生活。作为当年这个班的班主任，财政系张文春老师也亲赴杭州，带去了学院对每个同学的祝福。 </p>
<p>　　同学们高度肯定了母校近年来的变化，并表示希望有机会回母校看望师长，同时衷心祝愿学校取得更快的发展，更盼望财政金融学院早日进入世界一流。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlkhyhhbhyf-nybbb_lit.jpg{/dede:field}
