{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学校友张勇被任命为国务院食品安全委员会办公室主任{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月23日，中国人民大学校友张勇被国务院任命为国务院食品安全委员会办公室主任，正部长级。经济学院杨瑞龙院长代表全院师生向张勇校友发去贺信表示热烈祝贺。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张勇，男，汉族，浙江富阳人。历任国务院办公厅秘书二局副局长，局长。2003年12月起至今，任国务院副秘书长、国务院机关党组成员、国务院办公厅党委书记。1983年中国人民大学计划经济系（现经济学院国民经济管理系）毕业。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年10月学校举办&ldquo;1979级校友入校三十周年纪念会&rdquo;期间，张勇校友曾返回母院，与昔日的老师、同窗等亲切座谈。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1266960786{/dede:field}
{dede:field name='litpic'}{/dede:field}
