{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}澳大利亚国立大学宋立刚教授做客“人大经济讲堂”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-03 09:41:54{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月1日下午，澳大利亚国立大学宋立刚教授在明德主楼728人大经济讲堂发表了题为China&rsquo;s Metal Intensity in Comparative Perspective的学术演讲。经济学院雷达教授、虞义华博士、杨继东博士、王孝松博士等参加了演讲会。演讲由经济学院副院长刘元春教授主持。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnhzmbnybnf-l2l2m.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 宋立刚教授具体地分析了中国工业化进程中金属消费的强度，并在理论上得出未来中国金属需求的强度和变化路径。他指出结构问题是目前中国经济发展所面临的最大问题，并就低碳经济、中国的城市化进程以及人均国民生产总值等相关问题和现场同学进行互动问答。宋立刚教授利用图表与数据详细地阐述了美国、日本、韩国等国家在其工业化进程中对金属消费的变化。针对城市化进程这个问题，他结合史实向同学们做出了详细的说明并根据其他国家金属需求的变化路径做出了自己的猜想。最后，宋立刚教授指出，我们应该辩证地看待低碳经济所带来的节能减排的要求。他认为，一方面低碳经济给工业化的发展提供了新的困难与要求，但另一方面也提供了一个经济发展、技术跳跃的机遇与挑战。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnhzmk2zkmf-hlybb.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在宋立刚教授对中国工业化进程中的数据统计表进行分析和讲解之后，讲座进入了自由讨论和提问环节。现场师生积极主动地与宋立刚教授交流，气氛热烈活跃。 </p>
<p><br />
<strong>演讲人简介：&nbsp;</strong></p>
<p align="center"><strong><img height="159" alt="" width="130" src="/uploads/allimg/c110113/z2mhnnhzmkbyf-b2ffn.jpg" /></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; 宋立刚教授是澳大利亚国立大学 Crawford 经济与政府学院资深研究员、博士生导师、中国经济与商业项目主任。宋立刚教授的研究领域包括国际贸易、国际经济发展与政策决策、中国经济等。出版专著有《中国所有制变革：进程、现状与展望》、《中国的私营企业研究》及《比较优势的转移：亚太地区的经验研究》等。今年在国内外权威杂志发表的学术论文包括&ldquo;比较优势与中澳双边贸易&rdquo;、&ldquo;快速工业化与能源矿产品市场：东亚环境下的中国&rdquo;和&ldquo;中国国有企业改革的影响与意义&rdquo;等。宋立刚教校1978年进入我校世界经济专业本科就读。曾长期任教于人民大学，并曾担任在人大举办的&ldquo;中美经济学教育交流项目&rdquo;中方执行主任和班主任。 </p>
<p><br />
</p>
<p>
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhzmbnybnf-l2l2m_lit.jpg{/dede:field}
