{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院黎建飞教授为国家食药局领导干部授课{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-12 10:09:16{/dede:field}
{dede:field name='body'}<p>　　经国务院法制办领导推荐，4月9日，法学院黎建飞教授前往国家食品药品监督管理局讲授劳动合同法与社会保险法。国家食品药品监督管理局人事部门领导、局直属事业单位负责人和各省局人事部门负责人听取了讲课。 <br />
<br />
　　黎建飞教授从劳动合同法热点问题入手，讲授了相关问题的立法背景、劳动合同法引发社会持续议论的原因和今后的发展趋势，重点讲解了事业单位劳动人事管理的法律现状及难点与对策、事业单位在劳务派遣用工中应当注意的事项，解答了领导干部来自于实际工作中人事劳动管理的法律问题、政策取向和疑难案例。 <br />
<br />
　　听课的领导干部高度评价黎教授的精彩讲授&ldquo;是不可复制和不可取代的&rdquo;，并且希望黎教授今后能够扩大授课范围，为各省市的主管部门和相关负责同志授课。 </p>
<p>　　（编辑：於萍萍）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
