{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}伊拉斯姆斯大学城市管理发展学院院长Van Rooijen教授访问公共管理学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-10-22 11:55:56{/dede:field}
{dede:field name='body'}<p>　　10月19日上午，荷兰伊斯拉姆斯大学城市管理发展学院院长Van Rooijen教授一行访问公共管理学院。公共管理学院院长董克用教授、城市规划与管理系主任叶裕民教授会见了来宾，双方就学科发展和未来合作进行了交流。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c101124/z2mfbnnhyfhmmkf-bblz2.jpg" /></p>
<p>　　在会谈中，董克用院长向客人简要介绍了公共管理学院的基本情况和学科特点，叶裕民教授介绍了公共管理学院城市规划与管理系的发展历程和办学理念。Van Rooijen教授介绍了城市管理发展学院（IHS）和伊斯拉姆斯大学（Erasmus University Rotterdam）在欧洲和全世界的发展和合作情况。IHS致力于关注城市发展前沿，并从政治、经济、社会、政策等多视角入手，开展城市规划教育，并因此在2007年获得联合国人居大奖。Van Rooijen教授认为公共管理学院规划与管理系的办学理念先进、务实，办学思路、研究方向和正在开展的研究工作符合城市发展的规律，特别是对于中国的城市化高速发展进程具有重要意义。 </p>
<p>　　会谈取得良好的效果，双方在多方面达成一致共识，共同期盼今后能够开展更为紧密的合作交流。</p>
<p>　　（编辑：易晨）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhyfhmmkf-bblz2_lit.jpg{/dede:field}
