<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","纪宝成校长继续担任第三届全国公共管理（MPA）专业学位研究生教育指导委员会第一副主任委员",89,212);
$z[2][4]['name']="title";
$z[3]=Array("field","",214,253);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",255,306);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-24 03:25:09",308,367);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月18日，国务院学位委员会、教育部、人力资源和社会保障部联合召开全国金融等专业学位研究生教育指导委员会成立大会。纪宝成校长继续担任第三届全国公共管理（MPA）专业学位研究生教育指导委员会第一副主任委员，董克用院长被聘为秘书长，公共管理（MPA）教指委秘书处继续设在人民大学。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部副部长杜玉波、教育部部长助理林蕙青、人力资源和社会保障部副部长王晓初、司法部副部长赵大同、财政部副部长王军等有关领导出席了会议。全国各专业学位研究生教育指导委员会主任委员、副主任委员、委员共600余人参加会议。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟） <br />\r\n<br />\r\n</p>",369,1073);
$z[6][4]['name']="body";
$z[7]=Array("field","",1075,1114);
$z[7][4]['name']="litpic";

?>