{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中宣部两次致函感谢中国人民大学专家学者{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}党委宣传部{/dede:field}
{dede:field name='pubdate'}2010-12-28 11:04:50{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，中共中央宣传部理论局两次致函中国人民大学，对马克主义学院完成&ldquo;划清马克思主义同反马克思主义的界限&rdquo;课题调研，经济学院张宇教授，国际关系学院杨光斌教授，马克思主义学院秦宣教授、张雷声教授，哲学院郝立新教授等五位专家完成《划清&ldquo;四个界限&rdquo;学习读本》（以下简称《读本》）的起草修改工作表示感谢。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来函称：在《读本》起草过程中，中国人民大学马克思主义学院承担了&ldquo;划清马克思主义同反马克思主义的界限&rdquo;调研课题。该单位以认真负责的态度、良好的工作作风和较高的理论水平，形成了高质量的研究报告，发表了高质量的理论文章，为《读本》的编写工作做出了积极贡献。中国人民大学经济学院张宇教授，国际关系学院杨光斌教授，马克思主义学院秦宣教授、张雷声教授，哲学院郝立新教授等五位专家参加了《读本》起草修改工作，他们认真负责、不辞辛苦，出色地完成了所承担的工作任务，并对做好这项工作提出了许多好的意见和建议。为此，特对中国人民大学给予的支持表示感谢。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
