{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第六届二十院院际友谊辩论赛四强脱颖而出{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2011-04-11 08:38:09{/dede:field}
{dede:field name='body'}<p>　　4月10日晚，第六届二十院院际友谊辩论赛八强赛在公共教学楼二楼举行。来自哲学院、经济学院、历史学院、外国语学院等八个学院的辩论队，分别就&ldquo;是否应该支持电子竞技&rdquo;和&ldquo;广告是否利于大众消费&rdquo;两个辩题进行激烈辩论。其中哲学院与经济学院的论辩尤为精彩。</p>
<p>　　比赛开始，正方哲学院从价值和需求两方面立论，认为电子竞技具有极大的商业价值，并举例&ldquo;韩国电子竞技为支柱产业&rdquo;证明其观点。此外，正方还指出当今中国电子竞技起步晚，发展缓慢且传播渠道不足，加之主流媒体的偏向性报道使国内电子竞技活动举步维艰，因此需要政府的大力支持从而获利。而反方经济学院则用韩国518家电子竞技企业因国外游戏软件称霸韩国而获利极少的事实进行反击，还列举了美韩两国学生深陷网游的不良影响。最终哲学院选手以更加缜密的论证思路获胜，最佳辩手为正方三辩钟潇。</p>
<p>　　晋级四强的学院还有公共管理学院、信息学院和国际关系学院，最佳辩手分别为公共管理学院赵弈茹、马克思主义学院王乔和外国语学院王亚欣。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
