{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学出版社与经济学院教师代表座谈{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-29 03:47:55{/dede:field}
{dede:field name='body'}<p>　　3月28日下午，人民大学出版社社长贺耀敏、总编周蔚华、经济分社社长刘晶等一行来到经济学院,与经济学院教师代表座谈。经济学院院长杨瑞龙教授、党委书记张宇教授、经济学院副院长刘瑞教授、郭杰教授、院长助理王晋斌教授、陈彦斌教授、区域经济所所长孙久文教授，经济学院吴汉洪教授、郑超愚教授、孟捷教授、于泽副教授、聂辉华副教授参加了座谈会。座谈会由杨瑞龙院长主持。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzknmyhmhf-lkbll.jpg" alt="" /></p>
<p><br />
　　双方就进一步加强合作，继续做好教材建设、学术著作、畅销书等工作进行了深入探讨。 <br />
　　贺耀敏社长首先表达了出版社对经济管理类图书的重视程度。他表达了对经济学院在教材建设、教学经验、教学理念等方面起到模范带头作用的美好愿望。在学术著作方面，他希望加强专业硕士学位教育系列教材的出版，以及新兴专业领域如能源经济学方面教材的出版。还希望经济学院老师能出版些通俗读物，同时期待能把教学成果和数字化更好地结合起来。 <br />
　　杨瑞龙院长详细介绍了经济学院教材规划，计划出版第一批经济类教材计划、国际商务专业硕士系列教材、筹备出版能源经济学系列教材、国际贸易系列教材等四个方面的教材规划，同时希望配合人大出版社的相关工作，扩大在全国经济学科的影响力。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzknmyhmhf-lkbll_lit.jpg{/dede:field}
