<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院杨瑞龙教授继续受聘英国杜伦大学客座教授",89,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",216,263);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，英国杜伦大学商学院发来聘书，继续聘任经济学院院长杨瑞龙教授为该校客座教授，聘期三年。2007年4月，杨瑞龙教授首次受聘该校客座教授。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杜伦大学成立于1832年，是英国最早创立的第三所大学，2009年TIMES 英国大学综合排名第八位。杜伦商学院是一所研究型导向的世界知名商学院，拥有一流的研究实力。根据最新《金融时代》排名，杜伦商学院位列英国商学院前10名。近年来，经济学院与杜伦展开了密切的学术交流与人才培养方面的合作，该院负责人多次来人民大学访问并讲学。 </p>\r\n<p>\r\n</p>",265,857);
$z[5][4]['name']="body";
$z[6]=Array("field","1285727402",859,909);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",911,950);
$z[7][4]['name']="litpic";

?>