<item>
<link>http://www.ruconline.com[field:arcurl/]</link>
<title><![CDATA[[field:title function='html2text(@me)'/]]]></title>
<author>[field:writer/]</author>
<category>[field:typename/]</category>
<pubDate>[field:pubdate function='strftime("%a, %d %b %Y %H:%M:%S +0800",@me)'/]</pubDate>
<guid>http://www.ruconline.com[field:arcurl/]</guid>
<description><![CDATA[[field:description function='html2text(@me)'/] ... <br /><b>文章分类</b>:[field:typename/]<br /><a href="[field:arcurl/]" target="_blank">阅读全文</a> | <a href="[field:arcurl/]" target="_blank">评论回复</a>]]></description>
</item>