{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院首届“世联地产”学生社会实践论坛开幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-05-31 05:17:16{/dede:field}
{dede:field name='body'}<p>　　5月29日，公共管理学院首届&ldquo;世联地产&rdquo;学生社会实践论坛开幕式暨世联地产嘉宾经验分享交流会在求是楼报告厅顺利举行。世联地产创始人佟捷女士、财务总监苏静女士、华北区域人力资源部总经理吴瑜女士、公共管理学院许光建副院长、学生党总支王丹副书记、张秀智老师等嘉宾与来自清华大学、北京大学、中央财经大学等各首都高校的优秀社会实践团队共同出席了开幕式。</p>
<p align="center"><img height="333" src="/uploads/allimg/c100622/z2kkzlnznbbfnzf-hlhkk.jpg" width="500" alt="" /></p>
<p>　　上午9时仪式开始，公共管理学院许光建副院长宣布此次社会实践交流论坛正式开幕并对世联地产嘉宾的到来与支持表示感谢。在致辞中，许光建副院长介绍了公共管理学院的组建历程与学科特色，他强调学院一直以来都对学生的社会实践工作给予高度重视，并希望企业家能够经常与在校学生互动交流，丰富校园社会实践的内容。</p>
<p align="center"><img height="333" src="/uploads/allimg/c100622/z2kkzlnznyfhbnf-bbhby.jpg" width="500" alt="" /></p>
<p>　　作为公共管理学院84级土地经济学系校友的世联地产创始人佟捷女士随后致辞，她首先感谢了母校对她的培养，并回忆了在校时社会实践活动对其设立远大目标和投身自主创业的重大意义。之后，佟捷女士简要介绍了世联地产的发展历程与现阶段概况。</p>
<p>　　佟捷女士致辞结束后，公共管理学院学生党总支王丹副书记对学院社会实践工作开展状况以及学院新社会实践制度进行了系统地介绍。在介绍中，他提出学院社会实践工作今后将秉承&ldquo;教师竞争选题、学生统一组织、专家全程指导、学院资源支持&rdquo;四条原则，并且展望了公共管理学院学生社会实践工作的美好前景。</p>
<p>　　开幕式结束后，佟捷女士为在场听众带来了题为《大学生就业成长路径》的社会实践经验分享讲座。佟捷女士将生动幽默语言风格与具体典型的商业案例相结合，向大家阐释了学校与社会在组织目标构建、内部人际关系上的不同，告诉大家如何认识自我并找到自我定位。在讲演过程中，佟捷女士还积极地与在场师生进行交流互动，并就师生感兴趣的话题展开了热烈的讨论。经验交流会结束后，学生党总支王丹副书记代表学院向佟捷女士赠送了感谢函以及纪念品。</p>
<p align="center"><img height="333" src="/uploads/allimg/c100622/z2kkzlnznylbmyf-yy2my.jpg" width="500" alt="" /></p>
<p>　　此次开幕式结束后，来自社会各界的精英人士和以及首都各高校的优秀社会实践团队将进行一系列交流活动，为学校与社会之间、学校与学校之间开展社会实践工作创建广泛的合作平台。 </p>
<p>　　（编辑　陈慧茹）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnznbbfnzf-hlhkk_lit.jpg{/dede:field}
