{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国密歇根大学福特公共政策学院助理教授菲利普波特博士访问公共管理学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-06-02 09:34:36{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据公共管理学院与美国密歇根大学福特公共政策学院（Gerald R. Ford School of Pubic Policy, University of Michigan）的合作协议，该院助理教授菲利普&bull;波特（Philip Potter）博士于5月13日到25日对公共管理学院进行了访问，并做了两次讲座。讲座分别涉及美国的总统选举制度与对外政策的关系以及相互依赖对国际冲突的缓和作用。在讲座结束后，他还与公共管理学院学生进行针对讲座内容进行了进一步的互动、交流。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在访问期间，波特博士还与公共管理学院董克用院长、蓝志勇副院长、刘伟老师等人对两校即将开展的合作项目和更多领域的合作计划深入交换了意见。波特教授的访问一方面拓宽了公共管理学院学生的国际视野，另一方面也为两院之间的进一步的合作打下了良好的基础。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
