{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}校友陈岳琴入选“2009年中国十大公益律师”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-10 08:51:38{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，Law Firm 50公布了&ldquo;2009年中国十大公益律师&rdquo;，校友陈岳琴律师入选该名单。该评选结果载入了北京市律协的年度工作报告和全国律协的中国律师业发展30年报告。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈岳琴律师，现任北京陈岳琴律师事务所主任、北京市律师协会公益事务专门委员会委员、系人民大学法学院法律硕士、法学博士毕业生，在环境与动物保护、业主维权等公益援助领域成就突出，代表性成果包括：成功阻止北京动物园搬迁案，并促成建设部修改《城市动物园管理规定》；商品房小区配建防空地下室确权案，并向国务院和北京市人大提出关于废止相关法律规定的违宪审查建议、向全国人大常委会提出《物权法》草案立法建议；中消协关于阜阳毒奶粉受害者维权方案设计等。LawFirm50给出的专家评语是：&ldquo;她开启了中国法律硕士的时代，她正在奏响公益律师的时代琴音。&rdquo; <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年8月以来，LawFirm50向中国律师同行、法律工作者和相关政府机关工作人员发出了2800份公益律师调查问卷，截至2009年9月10日，共计回收有效调查问卷2467份，评选出的&ldquo;LawFirm50：2009年中国十大公益律师&rdquo;。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 原文链接：<a href="http://www.lawfirm50.com/news/?action=show&amp;id=155">http://www.lawfirm50.com/news/?action=show&amp;id=155</a> </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）</p>
<p><br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
