{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}郑晓华教授入选“2010中国书法十大年度人物”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-01-04 04:30:01{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《中国书画报》2011年1月1日报道，由该报组织评选的&ldquo;2010中国书法十大年度人物&rdquo;近日揭晓，中国人民大学艺术学院教授、博士生导师郑晓华入选。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 组委会给予郑晓华教授高度评价：2010年，郑晓华教授将艰深的书法专业知识转换为大众喜闻乐见的形式，以轻松易懂的演说形式搬上荧屏授予大众。2010年９月，30集大众书法普及教学片《轻松快乐学书法》（网络版）拍摄完成并在网络开播。11月，20集电视系列讲座《中国历代书法大师&mdash;&mdash;&mdash;影响中国书法发展的20位历史人物》摄制完成并由中国人民大学出版社出版发行。面对全球化背景下频繁的跨文化交流及全球汉语热的兴起，在面向世界各知名大学招生的&ldquo;中国人民大学国际小学期&rdquo;，郑晓华编写了全英文书法教材开课，帮助国际学生在全英文授课中接触、感受中国书法，将中国书法精髓向全世界&ldquo;说&rdquo;开去。 </p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
