{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学环境学院与天津排放权交易所签署战略合作协议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-11-07 10:01:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，中国人民大学环境学院与天津排放权交易所在北京签署战略合作协议，由此拉开了双方在环境保护、节能减排等领域合作的序幕。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据协议，环境学院将利用自身在环境经济学、环境政策和能源管理等领域的研究实力，为天津排放权交易所的发展战略、目标定位、业务类别和产品设计等方面提供支持和指导；并将根据国家在环境、能源领域的发展战略和管理需求，共同设立研究课题，组织力量进行专门研究。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 天津排放权交易所是按照《国务院关于天津滨海新区综合配套改革试验总体方案的批复》中关于在天津滨海新区建立清洁发展机制和排放权交易市场的要求设立的全国第一家综合性排放权交易机构，是一个利用市场化手段和金融创新方式促进节能减排的国际化交易平台。天津排放权交易所由中国石油集团、天津市政府授权机构和美国芝加哥气候交易所（Chicago Climate Exchange）三方合作组建，注册地点位于天津滨海新区。</p>
<p>（编辑：冯雪）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
