{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学生团队撰写论文获得“中国健康传播大会十佳论文奖”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-11-17 09:42:22{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻学院07级学生林雪、黄魏巍、杜尧、叶旭、赵卓5名同学共同调研撰写的论文《重大公共卫生事件中的传播特征及消解方式的研究&mdash;&mdash;以甲型H1N1流感期间的谣言研究为例》荣获&ldquo;第五届中国健康传播大会十佳论文奖&rdquo;，该奖项是由中国健康教育中心、卫生部新闻宣传中心、清华大学国际传播研究中心共同颁发。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmffy2bnbzf-bbllm.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmffy2bnbzf-bbllm_lit.jpg{/dede:field}
