<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","新闻学生团队撰写论文获得“中国健康传播大会十佳论文奖”",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",224,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-17 09:42:22",273,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻学院07级学生林雪、黄魏巍、杜尧、叶旭、赵卓5名同学共同调研撰写的论文《重大公共卫生事件中的传播特征及消解方式的研究&mdash;&mdash;以甲型H1N1流感期间的谣言研究为例》荣获&ldquo;第五届中国健康传播大会十佳论文奖&rdquo;，该奖项是由中国健康教育中心、卫生部新闻宣传中心、清华大学国际传播研究中心共同颁发。 </p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c101124/z2mfbmffy2bnbzf-bbllm.jpg\" width=\"500\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />\r\n</p>",334,916);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c101124/z2mfbmffy2bnbzf-bbllm_lit.jpg",918,1010);
$z[7][4]['name']="litpic";

?>