{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共治理与和谐城市研究中心举行“公共治理与和谐城市学术论坛”首场研究报告会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-03-09 09:09:54{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月3日晚，由公共治理与和谐城市研究中心策划主办的&ldquo;公共治理与和谐城市学术论坛&rdquo;首场研究报告会在中国人民大学求是楼439室举行。公共管理学院公共政策与公共安全研究所教师李文钊，以&ldquo;新时代的治理新科学&rdquo;为题，就诺贝尔奖得主Elinor Ostrom教授的学术发展道路和学术成就做了系统精彩的报告。北京航空航天大学副教授、留美博士杨立华，公共政策与公共安全所副教授张昕，博士生宋学增分别从各自的视角对报告进行了点评。报告会由博士生张晓兰主持。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bhzzf2zf-2llhm.jpg" width="500" height="333" alt="" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与会者一致赞同李文钊老师对Elinor理论认真、系统的解析，也从不同的角度对理论发展的过程、理论的普适性和局限性等方面提出了自己的看法。杨、张两位教授都曾在Elinor Ostrom教授身边学习、工作过，他们以近距离的视角对其理论发展进行了讨论，宋学增同学则从Elinor理论系统之外的宏观角度评价了其理论。李文钊老师的报告和三位点评人的意见引发了在座师生对Elinor Ostrom教授的学术成果的深厚兴趣。报告会不仅具有很强的学术交流性质，而且对师生们拓宽研究思路和方法也有重要启示。大家更深刻地认识到多方位、多视角的探索，以及学术包容的重要性。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，公共治理与和谐城市研究中心主任蓝志勇教授做了总结发言，他高度赞扬了每一位发言者的认真精神和所作的努力，认为这是一次高水准的讨论会；同时希望大家学习Elinor教授立足前人、认真思考、注重方法、敢于对话权威、勇于突破的严谨治学精神，以包容的心态、敢破敢立的精神，推动学科和理论的发展。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;公共治理与和谐城市&rdquo;研究中心经学校批准成立于2011年1月，隶属公共管理学院，以公共治理理论和现代城市治理的多种问题为主要研究方向。中心将连续举行各类论坛，通过邀请相关领域的知名专家和青年学者做学术报告和点评，促进学术交流和自由讨论，倡导求真、求实，跨学科、跨学派，包容、鼓励，以及以中国改革发展为己任的理论联系实际的学术风格。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2bhzzf2zf-2llhm_lit.jpg{/dede:field}
