{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院召开新生家长见面会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院 孙诗颖 井水玉 王梦霞{/dede:field}
{dede:field name='pubdate'}2010-09-14 03:24:53{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;9月9日上午，外国语学院2010级新生家长见面会在明德法学楼举行。外国语学院何其莘院长、党委书记张卫平及相关负责人出席了见面会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 见面会上，何其莘院长首先对新生家长简要地介绍了外国语学院的院情与院史。何院长提出了学习外国语学科的重要性，他认为中国需要一大批人从事语言与相关文化的研究与教学，而英语等外语对中国的改革开放、对外交流、成为世界大国有十分重要的意义。最后何院长对新生表达了对他们的期望和要求。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 听了这次讲座，新生们的触动很大。张亚琪是英语系的一位新生，她曾将英语单纯地看作是一种工具，甚至有转专业的念头，&ldquo;但是何院长的一席话改变了我对外语的态度，我要好好学习英语。&rdquo;一位家长感慨道：&ldquo;听了他的一席话，我对孩子学习英语要提出新的要求：不但要提高她的外语文化修养，还要让她对本土文化有深入的了解，中西贯通。&rdquo; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
