{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院2010-2011学年第二学期学生干部工作会议顺利召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2011-03-03 02:48:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月1日中午，外国语学院2010-2011学年第二学期学生干部工作会议在明德楼310室召开。党委副书记齐畅、分团委书记商竞出席本次会议并讲话。外国语学院学生党支部、班团支部、学生组织等的全体学生干部参加。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzm2zbkynf-zybkf.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，齐畅老师首先在讲话中指出，目前国际国内形势出现很多新变化，作为一名大学生，要有高度的政治责任感和思想觉悟，要有高度的政治敏感性和警惕性，自觉抵制任何不良团体、个人、反对势力的拉拢腐蚀和各种诱惑，进一步提高和完善自己；要树立正确的价值观，增强明辨是非的能力，把个人利益与国家、社会、集体利益联系起来；要&ldquo;自爱、自尊，爱党、爱国，承担责任&rdquo;，加强法律、政治理论的学习。齐老师建议，学生党支部及各班团支部应充分发挥模范作用，以全国&ldquo;两会&rdquo;和学校党校培训等为契机，积极组织同学开展相关活动，营造良好的学习、生活氛围，提高个人的思想道德素质和政治水平，以更好地成为党的接班人。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzm2zmhnf-2zfmh.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，商老师重点针对即将开展的&ldquo;五四&rdquo;文化艺术节活动做了说明，鼓励同学们积极参与，同时布置本学期其他主要工作，如：学生电子注册、重修问题、奖学金证书下发等。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzm2zbkynf-zybkf_lit.jpg{/dede:field}
