{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}K.哥特.罗文霍斯：从全球视角看商品期货市场{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-07-06 11:33:33{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月5日上午9:30，来自耶鲁大学管理学院金融学的K.哥特.罗文霍斯教授在明德主楼830黄达蒙代尔讲堂以&ldquo;从全球视角看商品期货市场&rdquo;为主题发表了精彩的演讲。本次讲座由中国财政金融政策研究中心主任、应用金融系主任汪昌云教授主持，汤珂副教授参加讲座并发表点评。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnmkhhkhlf-zmlkn.jpg" alt="" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; K.哥特.罗文霍斯教授主要研究国际金融和资产定价两个领域。近期，他的研究侧重于对冲基金的策略、共同基金的结算、大宗商品投资以及金融历史方面。罗文霍斯教授的研究成果不仅限于学术期刊，还发表在各类实务型期刊上，受到《华尔街日报》、《金融时报》、《纽约时报》等媒体的关注和引用。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 罗文霍斯教授从全球期货市场的增长、套期保值和投资者对于期货的需求、期货回报的基本准则、投机性需求是否影响价格这四个方面进行了演讲。他首先用色彩鲜明的图标直观的展示了全球范围内各个国家和地区的期货市场发展情况。然后以交易型开放式指数基金（ETF）为着重点，介绍了该市场上的利益增长趋势。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnmkhbfmfbf-2nhnn.jpg" alt="" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接下来，罗文霍斯教授提出了期货交易的两个益处：其一为期货与传统资产阶层有较低的相关性；其二为对比起传统资产阶层，期货市场有着更高的通货膨胀相关性。随后，他提出了影响风险和投资的三个基本原则。最后，罗文霍斯教授总结了本次演讲：首先，期货交易在全球范围内带来了增长的收益；其次，投资者在期货交易中的角色越来越重要；第三，价格风险的基本原则补偿了投资者并由套期保值者的保险支付；第四，投机性需求是否会影响价格还需要更多的调查来研究。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲结束后，汤珂副教授点评了罗文霍斯教授的演讲。汤珂副教授赞扬道：&ldquo;我非常吃惊的看到罗文霍斯教授对中国期货市场的了解如此之深！&rdquo; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在随后的互动环节中，同学们 积极踊跃，提出了一些关于PPT中图表的细节问题。罗文霍斯教授一一耐心解答，并和提问学生进行了观点讨论，互动场面十分和谐。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 罗文霍斯教授近两个小时的专场演讲在老师同学们的热烈掌声中结束了。在演讲中他大量的使用了彩色图表，直观地呈现了数据以及各市场的发展趋势。同时，教授还不停地用手势解释他的观点，整个演讲清晰易懂。在最后的互动环节中，到场学子更是感受到了罗文霍斯教授的平易近人，整个提问过程也使同学们加深了理解。讲座结束后，到场学生纷纷表示受益匪浅。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnmkhhkhlf-zmlkn_lit.jpg{/dede:field}
