{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院学生参与北京市宣武区中小学法律故事征文评选活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-04 02:37:36{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 增强中小学生的法律意识和校园安全意识是今年六一国际儿童节大家关注的焦点。应宣武区中小学教育委员会的邀请，法学院团委安排法学院研究生会李红佳、周龙等同学参加了&ldquo;法律在我身边&rdquo;&mdash;&mdash;北京市宣武区中小学法律故事征文活动的评选工作。参加此次评选工作的还有宣武区法院的法官、著名律所的律师、中小学教师以及教委工作人员等。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 活动当天，志愿者们一大早就来到了宣武区教委。在教委工作人员宣布了征文评选的相关事宜之后，评选工作紧张有序地开展起来。在评选过程中，评委们分为三组，每组负责不同年龄段学生的征文评选。法学院李红佳、周龙等同学秉承着认真负责的态度，仔细的阅读每篇征文，交相传阅一些比较难以定位的文章，积极探讨相关法律问题，时不时的交流评选心得。随后，每组分别制作了本届法律故事案例征文的获奖名单，评选工作至此结束。评委们一致感慨现在中小学生的法律意识较之以前有了很大的提高。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 活动结束后，主持评选工作的教委工作人员对法学院研究生会同学们认真负责的工作态度表示大加赞赏，对志愿者们过硬的专业素质给予了充分的肯定，其他参与评选工作的法官、律师、教师等人员对法学院同学的表现也纷纷赞不绝口。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次征文评选活动是法学院研究生会&ldquo;法制校长助理&rdquo;项目的一部分，&ldquo;法制校长助理&rdquo;是法学院研究生会与北京市宣武区中小学校长期合作的项目，旨在协助中小学校长做好增强青少年法律意识的工作，不仅是法学院同学进行法律实践的一个平台，更是展现人大法学院学生奉献精神和专业素质的窗口。同学们一致表示，此次活动加深了自己对所学理论知识的理解，丰富了自身的法律实践经验，以后会长期坚持下去。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
