{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}王利明副书记兼副校长赴国际学院检查工作{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际学院（苏州研究院）{/dede:field}
{dede:field name='pubdate'}2011-03-24 11:16:12{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月20至22日，中国人民大学党委副书记兼副校长、国际学院（苏州研究院）院长王利明赴国际学院检查工作。21日上午，学院召开中层干部会议，王利明副书记兼副校长听取了本学期开学一个月来工作情况的汇报，并部署了下一阶段的重点工作。会议由国际学院常务副院长陈甬军主持，学院党委副书记兼副院长杨志、副院长王小虎、副院长陈满华，全体中层干部及教师代表参加会议。</p>
<p align="center"><img src="/uploads/allimg/c110418/zlflzzhbhhmlf2f-zymzl.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈甬军常务副院长首先汇报了学院开学一个月来的工作情况。陈甬军常务副院长介绍道，国际学院本学期开学来主要围绕保证教学秩序稳定、加快中法学院报批这两条主线开展工作，学院采取各种措施确保了整体工作的稳定，同时加快了中法学院报批的进度。具体而言，在五个方面推进了工作：第一，加强了全院师生的思想政治工作，确保了学院的稳定，学院师生展现出良好的精神风貌；第二，加强了廉政建设，规范了各项管理制度和工作流程；第三，进行了教师招聘工作，队伍建设取得一定成效；第四，科研工作方面加强了与高教区的沟通协调，科研管理的机制进一步完善，科研目标进一步明确；第五，开展了庆祝&ldquo;三八&rdquo;节等文体活动，丰富了教职工生活。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教务部副主任兼团委书记杨殊还汇报了学生就业的最新情况。&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c110418/zlflzzhbhbbbkhf-2kbmm.jpg" alt="" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王利明副书记兼副校长在听取开学一个月以来工作情况的汇报后表示，教学秩序良好，学生思想稳定，就业工作和科研工作都取得了新的进展，各方面的工作做得及时到位，学院整体处于平稳有序的运行状态。王利明副书记兼副校长分析了学院今年的招生情况，通过报考情况来看，国际学院的品牌已经树立起来，国际学院的建设对于解决学校办学空间紧张、实现学校战略布局来说已经凸显出价值和作用。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王利明副书记兼副校长强调，要从以下三个方面着手，继续做好各项工作：第一，推进队伍建设。要继续做好今年的教师招聘工作，为尽快建立一流的教师队伍打下基础，同时也要重视管理队伍的建设，要建立合理的梯队，要关心每一位教职工的生活，构建一个和谐温暖的大家庭。第二，做好学生工作。在保证生源质量的前提下做好今年的招生工作。要继续高度重视就业工作，为学生提供更多的就业服务，关心就业困难的同学，积极与地方人才机构、企事业单位联系，加强就业过程中的诚信教育。与各办学学院加强联系，安排组织好毕业生的论文答辩工作。同时还要按照隆重节俭的原则组织好首届毕业典礼工作。第三，加快中法学院报批。在学校的大力支持下，学院要克服各种困难和阻力，完成中法学院的报批工作。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王利明副书记兼副校长最后强调，下一阶段的工作任务很明确，对于今后的发展有着重要意义，学院各部门要结合自身工作继续努力，为学院发展贡献力量。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbhhmlf2f-zymzl_lit.jpg{/dede:field}
