{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院孟虹副教授赴德国讲学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2008-10-28 11:18:00{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应德国欧洲管理和科技学院及莱比锡大学的邀请，外国语学院德语专业孟虹副教授于10月12日至10月22日赴德国讲学，参与了欧洲管理和科技学院在其位于科隆附近的格拉赫特皇宫分校举办的第47届&ldquo;总经理管理研修班&rdquo;教学工作。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在德国讲学期间，孟虹副教授围绕&ldquo;国际化管理&rdquo;主题，为来自西门子公司、大众汽车公司、蒂森克虏伯公司等德国和奥地利企业高级管理人员就中德合作跨文化管理作系列讲座，并在中国人民大学与德国莱比锡大学联合创建的莱比锡孔子学院，就当下中德关系做了专题报告。在报告中，孟虹副教授从跨文化角度分析介绍了影响德国形象在中国的历史、政治、经济和文化动因以及新时代中国人对德国的认识与期望等问题。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在德期间，孟虹副教授还与德国柏林洪堡大学学者及联邦议会议员等进行了交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
