{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘元春教授参加中共中央政策研究室和货币政策委员会专题会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-17 06:23:16{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月16日，中国人民大学经济学院副院长、经济研究所联席副所长刘元春教授参加了国家货币政策委员会&ldquo;当前宏观经济形势和货币政策&rdquo;专家咨询会。3月17日，刘元春教授参加了中共中央政策研究室&ldquo;2011年一季度经济形势&rdquo;座谈会。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
