<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院音乐系学生演出小组赴美国奥克拉荷马大学交流演出",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",224,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-10-09 09:17:01",279,338);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　9月30日，中国人民大学艺术学院音乐系学生演出小组，应邀在美国奥克拉荷马大学音乐学院音乐厅举行了访问美国的交流演出，获得极大成功。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhkmhfzbf-lhzbzz.jpg\" /></p>\r\n<p>　　演出团的四位同学分别是王昊，张乃文，史静雅，孙婷。他们分别表演了各自准备的具有鲜明中国特色的乐曲，受到奥克拉荷马大学师生们的热烈欢迎和高度赞扬。访问期间，音乐系副教授齐柏平和艺术学院对外交流顾问徐芳芳女士也就中国音乐及其发展现状做了专题讲学，使美方师生产生很大兴趣，受到一致好评。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhkmkb2lf-lbym22.jpg\" /></p>\r\n<p>　　中国人民大学艺术学院音乐系专业教师和同学为此次访问进行了精心的准备，活动的成功标志着艺术学院音乐系与国际接轨的又一次高水准艺术实践，是中国人民大学艺术学院音乐系专业教学成果的高度展示，也是美国奥克拉荷马大学音乐学院与中国人民大学艺术学院教学交流的结晶。</p>\r\n<p>（编辑：张利英）&nbsp;<br />\r\n</p>",340,1302);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhkmhfzbf-lhzbzz_lit.jpg",1304,1397);
$z[7][4]['name']="litpic";

?>