<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公共管理学院陈立鹏副教授应邀在湖北省师德论坛上作专题辅导报告",89,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",230,281);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-23 05:29:00",283,342);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月21日，应湖北省教育厅的邀请，公共管理学院教育研究所副所长陈立鹏副教授在&ldquo;2010年湖北省师德论坛&rdquo;上作《国家中长期教育改革和发展规划纲要》专题辅导报告，就《规划纲要》的重大意义、基本精神、教育事业改革发展的战略方针、战略目标、战略主题、重点领域及重大改革举措等大家关心的问题，进行了深入细致地讲解，并与参会者分享了他参与《规划纲要》研究制定及参与《规划纲要》解读的心得体会。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 湖北省教育厅有关部门、各市州教育局主管师资工作的副局长、师资科科长、部分学校校长、教师一百余人参加了报告会。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉)<br />\r\n</p>",344,1063);
$z[6][4]['name']="body";
$z[7]=Array("field","",1065,1104);
$z[7][4]['name']="litpic";

?>