<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国人民大学2010新年音乐会隆重上演",89,161);
$z[2][4]['name']="title";
$z[3]=Array("field","",163,202);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",204,257);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-04 10:01:40",259,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　12月30日晚，由中国人民大学艺术学院主办的2010新年音乐会在逸夫会堂举行。中国人民大学副校长杨慧林，中国人民大学副校长薛浣白，中国人民大学艺术学院院长徐庆平教授，学校办公室、艺术学院及学校相关部门负责人出席了此次音乐会，与同学们共享了这场音乐盛宴。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhnfnl2zf-hzbnfy.jpg\" /></p>\r\n<p>　　一曲旋律流畅的双簧管独奏《牧羊姑娘》拉开了音乐会的序幕；抒情歌曲《乡音乡情》牵动了观众们的心情；健康、幽默和轻松的大提琴独奏《回旋曲》使大家心情愉悦；男中音独唱《多情的土地》真挚的感情随歌声传递，感染了全场观众。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhnz2lnlf-h2k2bf.jpg\" /></p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhnz2nmf-hlnzh2.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 音乐系教师的钢琴弦乐五重奏《A大调钢琴五重奏》热情奔放的格调渲染了全场；管弦乐队的同学们凭借娴熟的技巧演绎了《简单交响曲》曲目；两首歌剧重唱《让我们携手同行》、《饮酒歌》更是将现场的气氛推向了高潮，博得了全场阵阵喝彩。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110725/zlzzbyzhnzhfy2f-hhnz2l.jpg\" /></p>\r\n<p>　　整场音乐会以精湛的技艺，透过美妙的音符向人大师生传递着新年的祝福。由艺术学院主办的&ldquo;新年音乐会&rdquo;已成功举办了9届，受到了全校师生的热烈欢迎，已经成为中国人民大学历年新年来临前夕的一道视听盛宴。 </p>\r\n<p>　　\r\n</p>",320,1715);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhnfnl2zf-hzbnfy_lit.jpg",1717,1810);
$z[7][4]['name']="litpic";

?>