{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院“学科国际前沿教师培训”系列讲座举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院  文\陈凯茵 图\裴峥{/dede:field}
{dede:field name='pubdate'}2010-12-02 08:43:25{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月22日&mdash;11月26日中午，新闻学院&ldquo;学科国际前沿教师培训&rdquo;系列讲座在明德新闻楼611会议室举行。本次讲座由美国爱荷华大学新闻与传播学院院长David D. Perlmutter教授主讲，讲座围绕政治传播、视觉传播和新媒体研究展开。新闻学院大部分教师以及部分同学参加了讲座。</p>
<p align="center"><img height="500" alt="" width="333" src="/uploads/allimg/c110113/z2mhnnllkbmmbkf-zlmf2.jpg" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次讲座的主题分别是：美国政治博客的兴起、在线社交媒体和竞选、在线社交媒体社区存在的动机、数字和互联网时代的视觉伦理和博客是否正在改变医疗保健&mdash;&mdash;年轻的国际医务工作者对社交媒体的反应。在讲座中，David D. Perlmutter教授用几个关键词说明了现今这个时代的特点：互联网的、即时性的、交互性的、数字性、直播式的、实名制的、自媒体的，概括来说就是&ldquo;IDS ERA&rdquo;。David D. Perlmutte教授还从美国一档受欢迎的新闻节目入手来切入他的讲座主题，他运用一系列的具体案例丰富讲座内容，直观地介绍了新媒体与美国总统竞选、社交媒体存在动机和新媒体在视觉传播、健康传播中的应用。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110113/z2mhnnllky2nhmf-22mfh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻院老师与David D. Perlmutter教授就讲座内容进行了深入交流，现场气氛热烈。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnllkbmmbkf-zlmf2_lit.jpg{/dede:field}
