{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院师生党员赴西柏坡开展主题党日活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-11-04 09:24:05{/dede:field}
{dede:field name='body'}<p>&nbsp;　　11月1日，中国人民大学环境学院党委一行64人，在院党委书记刘鹏老师的带领下，奔赴被誉为&ldquo;新中国从这里走来&rdquo;的革命圣地西柏坡，举行&ldquo;学习西柏坡精神，践行科学发展观，重温入党誓词&rdquo;的主题党日活动。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100622/z2kkzlnfbl2knkf-hmlmn.jpg" /></p>
<p align="left"><br />
<br />
　　西柏坡是中国共产党领导的&ldquo;解放全中国的最后一个农村指挥所&rdquo;，在西柏坡这个农村指挥所里，党中央运筹帷幄，决胜千里，吹响了建立新中国的号角；在西柏坡，毛主席提出了著名的两个&ldquo;务必&rdquo;&mdash;&mdash;务必保持谦虚敬慎、不骄不躁的作风，务必保持艰苦奋斗的作风。环境学院党委特地组织了此次主题党日活动，就是为了学习党中央及老一辈革命领导人敢于斗争的革命英雄主义精神，戒骄戒躁、艰苦奋斗的创业精神。</p>
<p>　　活动当天，天气异常寒冷，5-6级的大风中夹杂着北京2009年的第一场雪，但环境学院的师生党员们经受住了严寒的考验。清晨6点，按原计划准时出发，一路驱车5个小时到达革命圣地&ldquo;西柏坡&rdquo;。师生们首先参观了&ldquo;中共中央旧址&rdquo;，&ldquo;中共中央旧址&rdquo;内分布着毛泽东、周恩来、朱德、邓小平等老一辈革命领导人的旧居、中央军委作战室、中共七届二中全会会址等。领导人的旧居大都狭小简陋，体现了当时作战条件的艰苦；在只有三张桌子、一部电话的&ldquo;世界上最小的&rdquo;军委作战室里，中共中央夺取了三大战役的胜利，大家对党中央的英明决策感到无比钦佩。 <br />
<br />
　　在中共七届二中全会会址前，学院师生党员重温了入党誓词。大家再次感受到入党时热情澎湃的心情，并表示要坚定不移的拥护中国共产党的领导，努力学习和实践科学发展观，为建设有中国特色社会主义事业、为共产主义理想奋斗终身。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100622/z2kkzlnfbhf2khf-bhhml.jpg" /></p>
<p align="left"><br />
　　此次&ldquo;学习西柏坡精神，践行科学发展观，重温入党誓词&rdquo;主题党日活动，是2009年环境学院党委举办的第一次全院规模的大型主题党日活动，活动时间长达15个小时，来回车程七八百公里。通过参观西柏坡，全院师生党员深深为西柏坡精神所鼓舞，大家纷纷表示将在今后的学习生活中，谨记党中央实事求是及两个&ldquo;务必&rdquo;的教诲，为祖国建设、为振兴中华而拼搏奋斗。</p>
<p>　　（编辑：郑觅）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfbl2knkf-hmlmn_lit.jpg{/dede:field}
