{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}长江学者朱力行教授到人大讲学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-06-03 02:33:19{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp;&nbsp; 6月1日,由统计学院聘任的教育部长江学者、香港浸会大学朱力行教授来到中国人民大学，朱力行教授将在人民大学开展为期近三个月的教学、研究与学术交流。</P>
<P>&nbsp;&nbsp;&nbsp; 期间，朱教授将为统计学院研究生讲授课程“统计应用研究”，同时开设一个研究生研讨班，并通过座谈、讲座等多种方式与师生进行学术研究和交流。</P>
<P>&nbsp;相关背景: <A href="http://www.cernet.edu.cn/20060421/3186851.shtml">“长江学者”教授风采：朱力行</A><BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
