<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","长江学者朱力行教授到人大讲学",89,155);
$z[2][4]['name']="title";
$z[3]=Array("field","",157,196);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",198,245);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-06-03 02:33:19",247,306);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>&nbsp;&nbsp;&nbsp; 6月1日,由统计学院聘任的教育部长江学者、香港浸会大学朱力行教授来到中国人民大学，朱力行教授将在人民大学开展为期近三个月的教学、研究与学术交流。</P>\r\n<P>&nbsp;&nbsp;&nbsp; 期间，朱教授将为统计学院研究生讲授课程“统计应用研究”，同时开设一个研究生研讨班，并通过座谈、讲座等多种方式与师生进行学术研究和交流。</P>\r\n<P>&nbsp;相关背景: <A href=\"http://www.cernet.edu.cn/20060421/3186851.shtml\">“长江学者”教授风采：朱力行</A><BR></P>",308,793);
$z[6][4]['name']="body";
$z[7]=Array("field","",795,834);
$z[7][4]['name']="litpic";

?>