{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本早稻田大学政治经济学部教授到经济学院授课{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-01-08 03:37:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应经济学院的邀请，日本早稻田大学政治经济学部荒木一法教授和白木三秀教授分别于9月22日至25日和12月21日至24日到人民大学，为经济学院的研究生讲授了《日本农业经济》和《博弈论》。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2005年，经济学院与日本早稻田大学政治经济学部签署有关协议，互派教师为学生授课。此次早稻田大学教授来访就是根据该协议安排而进行的。</p>
<p>（编辑：王宝奎；核稿：丁凯）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
