<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","日本早稻田大学政治经济学部教授到经济学院授课",89,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",214,261);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-08 03:37:18",263,322);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应经济学院的邀请，日本早稻田大学政治经济学部荒木一法教授和白木三秀教授分别于9月22日至25日和12月21日至24日到人民大学，为经济学院的研究生讲授了《日本农业经济》和《博弈论》。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2005年，经济学院与日本早稻田大学政治经济学部签署有关协议，互派教师为学生授课。此次早稻田大学教授来访就是根据该协议安排而进行的。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）&nbsp;<br />\r\n</p>",324,813);
$z[6][4]['name']="body";
$z[7]=Array("field","",815,854);
$z[7][4]['name']="litpic";

?>