{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘元春教授受聘央视财经频道宏观经济顾问{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-22 04:48:00{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，经济学院副院长、经济研究所联席副所长刘元春教授受聘为中央电视台财经频道、新华社&ldquo;新华08&rdquo;专业财经网站，北京电视台财经频道等多家知名媒体的宏观经济顾问。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2010年11月以来，刘元春教授先后多次做客&ldquo;新华08&rdquo;、北京电视台、凤凰卫视、东方财经等媒体的高端访谈。 <br />
2010年12月13日，刘元春教授接受中央电视台财经频道《今日观察》采访，发表了题为《2011年宏观调控唯&ldquo;稳&rdquo;，变量来自全球金融危机》的演讲。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
