<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院刘元春教授受聘央视财经频道宏观经济顾问",89,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",216,263);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-22 04:48:00",265,324);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，经济学院副院长、经济研究所联席副所长刘元春教授受聘为中央电视台财经频道、新华社&ldquo;新华08&rdquo;专业财经网站，北京电视台财经频道等多家知名媒体的宏观经济顾问。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2010年11月以来，刘元春教授先后多次做客&ldquo;新华08&rdquo;、北京电视台、凤凰卫视、东方财经等媒体的高端访谈。 <br />\r\n2010年12月13日，刘元春教授接受中央电视台财经频道《今日观察》采访，发表了题为《2011年宏观调控唯&ldquo;稳&rdquo;，变量来自全球金融危机》的演讲。 </p>\r\n<p>\r\n</p>",326,904);
$z[6][4]['name']="body";
$z[7]=Array("field","",906,945);
$z[7][4]['name']="litpic";

?>