<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","英国伦敦大学帝国理工学院Michael Joffe教授做客“世纪经英论坛”",89,188);
$z[2][4]['name']="title";
$z[3]=Array("field","",190,229);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",231,278);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-16 02:36:18",280,339);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月15日，伦敦大学帝国理工学院Michael Joffe教授访问经济学院并发表学术演讲。中国人民大学国际交流处处长唐忠教授、经济学院院长杨瑞龙教授在明德主楼614会议室会见了Michael Joffe教授，院长助理郑新业副教授、王珏副教授、党委副书记丁凯博士等陪同会见。</p>\r\n<p>&nbsp;</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflznzknlbyllf-hnmz2.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p><br />\r\n　　会见中，杨瑞龙院长向Michael Joffe教授介绍了经济学院学科建设的现状以及经济研究所主办的&ldquo;中国宏观经济论坛&rdquo;的相关情况，并向其赠送了2010年的英文版《中国宏观经济分析与预测报告》。Michael Joffe教授表示非常关注中国的经济问题，并希望双方能够进行更多的交流与合作。Michael Joffe教授还与王珏副教授就资本主义经济史的研究进行了深入的学术交流与讨论。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflznzknlmnllf-bhkly.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p><br />\r\n　　会见后，Michael Joffe教授在明德主楼734会议室&ldquo;世纪经英讲坛&rdquo;发表了题为The Root Causes of Economic Growth Under Capitalism的学术演讲。Michael Joffe教授在演讲中就当今世界资本主义制度下经济运行的特点及经济增长的促进因素等发表了独到、深刻的见解。他还与经济学院的师生就公司存在对于经济增长的意义、购买力与经济发展之间的关系等问题进行了热烈的讨论。 </p>\r\n<p>\r\n</p>",341,1675);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflznzknlbyllf-hnmz2_lit.jpg",1677,1769);
$z[7][4]['name']="litpic";

?>