{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院学生结束世界知识产权组织实习返校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-11-30 03:31:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院学生郝卓然、侯磊日前结束了今年四月开始的在世界知识产权组织(WIPO)的实习，返回学校学习。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmnhzlnkf-zybfl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在为期六个月的实习中，两位同学在WIPO法律事务部中主要负责WIPO Lex数据库的建设工作，完成了包括中国、香港特别行政区、澳门特别行政区、日本、韩国、土耳其等二十多个国家和地区的页面建设。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 两位同学表示，在国际组织实习对于专业、语言水平的提高以及适应多元文化环境都非常有帮助。国际组织的工作语言一般为英语或法语，WIPO Lex团队中有来自瑞士、乌克兰、越南、秘鲁、法属布基纳法索等近10个国家的成员，此外还有机会与各国的知识产权部门进行沟通和联络，在WIPO年度大会上与各国与会代表交谈。能够接触不同文化背景、生活习惯、宗教信仰的同事，并与其一起工作是一件非常难得而有趣的经历。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 无论是工作上还是生活上，WIPO对于实习生都提供了很大程度的帮助。不但为实习同学提供了一定的生活补助，而且实习期间可以免费参加世界知识产权组织学会(WIPO Academy)开设的课程和联合国提供的其它语言课程，也可以在WIPO图书馆中借阅最新的学术著作和期刊，提升自身专业素质。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随着法学院国际化建设的不断加快，对外交流的不断加强，提升国际性的着力点已从教师的国际化转向教师与学生的国际化并重。近年来，学院不断创造条件，为学生提供平台，让学生以世界为舞台，参与到国际活动中。在这样的背景下，学院经过长期努力，促成了此次与世界知识产权组织合作的实习项目，并将把其建设成为长期实习项目。法学院第二期赴世界知识产权组织实习的选拔工作已经结束，并将于下月赴日内瓦开始第二期的实习。&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmnhzlnkf-zybfl_lit.jpg{/dede:field}
