{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院进行三江平原湿地保护与可持续发展调研实习{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-07-30 06:47:17{/dede:field}
{dede:field name='body'}<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月15号，在环境学院吴健、王晓霞和昌敦虎三位老师的带领下，环境经济与管理系以及环境科学系的研究生和本科生踏上了为期10天的七星河国家级自然保护区调研实习之路，参与环境学院马中院长主持的亚洲开发银行和GEF基金支持的&ldquo; 三江平原湿地保护项目&rdquo;的部分调研工作。</p>
<p align="center"><img height="346" alt="" width="500" src="/uploads/allimg/c100622/z2kkzlnf2byybmf-zzymh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 实习的主要内容是对七星河周边地区水资源管理、水利工程设施和农业生产等方面进行调研。对七星河国家级保护区管理局、宝清县环保局、农业局以及水务局等进行了部门访谈，并在七星河周边的农村和597农场进行了农户调查。</p>
<p align="center"><img height="355" alt="" width="500" src="/uploads/allimg/c100622/z2kkzlnf2y2blyf-2mknh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;读万卷书，不如行万里路&rdquo;，实习本身就是生动的社会实践课。这期间，调研实习小组的成员们有严谨的学术讨论，师生每每讨论工作到深夜，体会着汲取知识而带来的无尽的快乐。同时大家还感受到东北人民的热情好客和风趣幽默。当地秀美的自然风光还也让师生们忘却调研的辛苦。短短的十天时间，师生之间讨论热烈，欢笑不断。</p>
<p align="center"><img height="336" alt="" width="500" src="/uploads/allimg/c100622/z2kkzlnf2yyzz2f-lyfbf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月26日，环境学院七星河湿地暑期学生调研实习小组圆满完成了这次社会调查实践。宝清的一草一木，一人一景都变成了师生们最深刻的记忆。调研实习小组的全体同学十分珍惜这次社会实践的机会。实习调研不仅丰富了同学们的专业知识，开拓了视野，同时也使同学们更切身体会到了理论联系实际的重要性和必要性。</p>
<p>（编辑：周卓斌）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnf2byybmf-zzymh_lit.jpg{/dede:field}
