{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨志教授获评北京市“群众心目中的好党员”并参加首场巡回报告会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月25日，北京市&ldquo;群众心目中的好党员&rdquo;先进事迹巡回宣讲活动举行了首场报告会，中国人民大学经济学院杨志教授作为首场派出的五名优秀党员代表之一出席报告会，与500余名党员群众一同分享她30余年&ldquo;真情&bull;真想&bull;真干&rdquo;的党员先进事迹。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 今年4月起，北京市委在全市基层党组织和广大党员中深入开展了创先争优活动。在基层广泛推荐提名的基础上，全北京市7.9万个基层党组织和173.9万名党员中共推荐出150名候选人，最终通过公众投票评选表彰出100名北京市&ldquo;群众心目中的好党员&rdquo;。为充分发挥先进典型在创先争优和党员作风建设年活动中的示范引领作用，市委从受表彰的100名北京市&ldquo;群众心目中的好党员&rdquo;中遴选出10名代表，组建先进事迹巡回报告宣讲团。杨志教授从12名高校候选人中脱颖而出，作为唯一一名教师党员典型入选此次巡回宣讲团，具有极强的代表意义。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，从即日起至12月，宣讲团还将在全市陆续举行18场宣讲活动，在全市进一步营造学先进、赶先进、做贡献、当表率的良好氛围。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1288925561{/dede:field}
{dede:field name='litpic'}{/dede:field}
