{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院“部派佛教思想研究”讲座顺利举办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-05-25 11:17:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月19日下午，由中国人民大学宗教高等研究院、哲学院佛教与宗教学理论研究所主办的中国人民大学宗教学术讲座在人文楼五层举办，本次讲座由魏德东副院长主持，台湾政治大学宗教研究所副教授黄柏棋主讲，参加本次讲座的还有中国人民大学哲学院张风雷教授、欧阳谦教授等相关教授。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 黄教授进行题为&ldquo;部派佛教思想研究&rdquo;的演讲，主要分为&ldquo;巴利语的演变&rdquo;和&ldquo;上座部佛教文化&rdquo;两部分内容，首先从印度佛教的起源讲起，中间提及佛教传播过程中的多语言政策以及由于南传佛教之间的交流而引起的巴利语的演变、巴利语的现存的状态和世人对于巴利语存在的误解等实际问题，黄教授还介绍了斯里兰卡和缅甸等地现存的上座部佛教的问题，并将上座部佛教与伊斯兰教进行比对，阐释了佛教的&ldquo;教义的传播胜过一切&rdquo;的观点。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座期间宣方副教授和惟善大师就巴利语的问题和黄柏棋教授进行了更加深入的讨论，惟善大师还就自己在斯里兰卡留学的经历谈及了自己的切身体会。张风雷教授、张雪松老师、惟善大师又和黄教授讨论了由于宗教地域不同而引起的观念差异的问题，并谈及了中国的大乘佛教与东南亚的大乘佛教的差异问题，会场气氛热烈，大家都积极地进行讨论，最后本次讲座在掌声中圆满结束。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
