{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大法学院黎建飞教授荣任北京市残保法修改专家工作组组长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-01 09:06:53{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经北京市人大常委会主任会议研究，《北京市实施〈中华人民共和国残疾人保障法〉办法》修改工作列入2011年市人大常委会立法计划完成项目。为此，市政府残疾人工作委员会组建法律专家工作小组，决定由中国人民大学黎建飞教授任组长，北京大学、中国政法大学、中国社会科学院法学所、北京市政协等单位的专家学者和领导同志为专家成员。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 专家组将负责收集国内外有关残疾人立法资料，参与修改工作组织的各种座谈会、论证会和听取社会组织意见等活动，起草修改工作调研报告及《北京市实施〈中华人民共和国残疾人保障法〉办法修改草案专家意见稿》。 <br />
<br />
　　（编辑：苗育婧） <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
