{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公管学院陈立鹏副教授应邀参加教育部民族教育工作座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-03-11 05:19:26{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为研究、交流民族教育工作，筹备即将召开的第六次全国民族教育会议，教育部于3月1日至2日在甘肃省兰州市召开了全国民族教育工作座谈会。公共管理学院教育研究所副所长陈立鹏副教授应邀参会，并对国务院拟颁发的《加快发展民族教育的决定》、《民族教育分纲要》等文件提出了修改意见。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部民族教育司等有关司局领导，各省、自治区、直辖市教育厅民族教育处处长、基础教育处处长，高校民族预科基地、少数民族高层次人才基础强化基地领导共80余人参加了会议。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
