<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公管学院陈立鹏副教授应邀参加教育部民族教育工作座谈会",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",222,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-11 05:19:26",275,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为研究、交流民族教育工作，筹备即将召开的第六次全国民族教育会议，教育部于3月1日至2日在甘肃省兰州市召开了全国民族教育工作座谈会。公共管理学院教育研究所副所长陈立鹏副教授应邀参会，并对国务院拟颁发的《加快发展民族教育的决定》、《民族教育分纲要》等文件提出了修改意见。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部民族教育司等有关司局领导，各省、自治区、直辖市教育厅民族教育处处长、基础教育处处长，高校民族预科基地、少数民族高层次人才基础强化基地领导共80余人参加了会议。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n</p>",336,950);
$z[6][4]['name']="body";
$z[7]=Array("field","",952,991);
$z[7][4]['name']="litpic";

?>