{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}足球乙级联赛开战 外国语学院对阵马克思主义学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院团学新闻信息中心 文/刘佳 图/周华哲{/dede:field}
{dede:field name='pubdate'}2008-09-26 05:24:53{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月26日中午12点，中国人民大学足球乙级联赛在小足球场准时开战，对阵的双方是外国语学院和马克思主义学院代表队。外国语学院团委书记商竞老师等到场观战。</p>
<p align="center"><img height="333" src="/uploads/allimg/c100621/z2kkzlbnblyyyf-zyyfn.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 上半时比赛刚一开始，场上运动员迅速进入状态，双方互有攻守。外国语学院首先将球送入网窝，但被判越位在先；比赛进行到15分钟，外国语学院后卫解围失误，马克思主义学院抓住机会，先进一球。易地再战，双方势头不减，但外国语学院始终没有占据场上优势。最终，比分定格在1：3。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c100621/z2kkzlbnbhhlmyf-2k2hy.jpg" width="500" alt="" /></p>
<p align="center"><img height="333" src="/uploads/allimg/c100621/z2kkzlbnbhm22yf-lzbhb.jpg" width="500" alt="" /></p>
<p align="center"><img height="333" src="/uploads/allimg/c100621/z2kkzlbnbbhfbkf-hzybf.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 虽然这场比赛以失利告终，但值得一提的是，在比赛中有多名2008级的新生上场，体现了对新生们充分的信任与锻炼；新生们也充分发挥了自己的水平，得到了学长和老师的认可。 <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbnblyyyf-zyyfn_lit.jpg{/dede:field}
