{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院两教授分别当选中国行为法学会执行行为研究会副会长和常务理事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-20 03:59:57{/dede:field}
{dede:field name='body'}<p>　　4月18日,&ldquo;中国行为法学会执行行为研究会成立大会&rdquo;在京召开，中国人民大学法学院汤维建教授当选为研究会副会长，肖建国教授当选为研究会常务理事。</p>
<p>　　中国行为法学会执行行为研究会，是中国行为法学会下属的专门从事强制执行法学研究、宣传和培训的全国性学术团体。该会会员由中国行为法学会中从事强制执行法学研究的会员组成。该会的成立旨在广泛团结和组织全国强制执行法学与法律工作者，加强同国内外相关学科的学术交流与合作，立足中国国情开展强制执行法学研究，为我国强制执行的法制建设提供理论支持，解决长期以来一直受到全国各界普遍高度关注的&ldquo;执行难&rdquo;问题。 </p>
<p>　　此次&ldquo;中国行为法学会执行行为研究会成立大会&rdquo;共有来自全国人大法工委、最高人民法院、最高人民检察院、部分省市区法院、全国高校、中国公证协会、国家开发银行、律师事务所等单位的100余名代表参加，中国行为法学会会长刘家琛、最高人民法院执行局局长俞灵雨、最高人民检察院民事行政检察厅厅长王鸿翼等领导出席并做了重要讲话。 <br />
<br />
<br />
（编辑：贾晓旭 唐川云　李露希） <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
