{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院举办第二十一届教授沙龙{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-04-14 02:34:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月6日中午，法学院第21届教授沙龙在明德法学院601国际学术报告厅举办。正式受聘为中国人民大学法学院助理教授的Alonzo Emery就哈佛大学法学院的法学教育问题，通过自身在中美两国法学院学习的经历，与参会教师共同研讨了两国法学教育模式的利与弊。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fbnhz2nf-zzkmhf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Alonzo教授介绍了哈佛大学法学院所开设的课程以及学分情况，其中重点讲述了美国的案例教学模式：19世纪后期，时任哈佛法学院院长克里斯托弗&bull;哥伦姆布斯&bull;朗德尔(Christopher Columbus Langdell) 将&ldquo;苏格拉底方法&rdquo;---苏格拉底式的案例教学法(Socratic method)引入哈佛大学的法学教育之中，即在课堂上教师针对案例向学生进行提问，引导学生分析思考和讨论案件中的各种疑难情节，在逐步培养学生的逻辑性思维、发散性思维、理解法律法规、了解法制史的同时，掌握对案例进行分析的方法和法律思维模式。此方法受到师生们的热烈欢迎，并在哈佛法学院推广。当然，这种教学方式也存在着不可忽视的弊端：因它的教学方法中涉及的内容与工作无关，占用了上课时的辩论时间，从而剥夺了学生的创造力。Alonzo教授谈到了他在中国法学院学习的经历和感受，他认为在中国的学习使他受益匪浅。他也诚恳的指出，中国学生与美国学生相比，没有更积极的参加课堂讨论，而且阅读量欠缺。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Alonzo教授对人大法学院与哈佛大学法学院合作的残疾人项目----残疾人的法律诊所进行了重点介绍和讲解。他说，在美国案例模式、解决冲突、常规课、诊所教育、实习是法学院学生的必修科目。Alonzo教授在比较法教研室开设的残疾人诊所教育课程中，首先教会大家的是谈判技巧。在此次教授沙龙中，他更是结合幽默风趣的案例，向与会人员展示了一堂生动活泼的法律谈判课。大家在愉快和轻松的氛围下，深刻体会到了谈判无处不在。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 结合Alonzo教授的演讲，参会者们针对哈佛法学院的教学方法以及哈佛大学的教学活动提出了很多具有建设性的问题，也有同学对院长韩大元提出了关于人大法学院的实务性课程问题。韩大元院长介绍说，目前人大法学院的实务性的教学课程有很多，首先法学院很多教授都有律师资格证，部分教授在法院和检察院任职，还有很多课程邀请有实务经验的律师来授课。比如法学院开设的律师学院课程，就是典型的实务性极强的法律课程，学生都可以选修。丁相顺副教授也补充指出，人大法学院引进的诊所教育，即比较法班的残疾人法律诊所，强调中外教师的合作，双语双法教学，既有前沿性的实践课程，又有基础课程。所有这些课程，使人大法学院法律实践体系完善和丰富起来。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩大元院长表示，Alonzo教授作为外籍教授的聘任，只是人民大学法学院与国际接轨、施行国际化的一个开端，今后法学院将聘请更多的外籍优秀教师到人大法学院来授课交流，使人大法学院不仅走在中国法学院的前列，更要努力跻身于世界优秀法学院之林，这需要全体老师和学生的共同努力和奋斗。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fbnhz2nf-zzkmhf_lit.jpg{/dede:field}
