{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}最高人民法院在中国人民大学设立最高人民法院知识产权司法保护研究基地{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院／钟小红{/dede:field}
{dede:field name='pubdate'}2011-04-06 02:30:09{/dede:field}
{dede:field name='body'}<p>　　鉴于中国人民大学在知识产权教学与研究上的突出地位和实力，最高人民法院近日决定，在中国人民大学设立最高人民法院知识产权司法保护研究基地，双方将通过重大课题研究、信息资料交流、培训研讨工作等多种形式，为研究基地开展研究工作提供便利条件。 </p>
<p>　　最高人民法院知识产权司法保护研究基地在中国人民大学的设立，对提高人民大学的知识产权的教学与研究水平，促进向实践学习以及理论研究与实践相结合，进而提高我国的知识产权法治水平，具有重要意义。</p>
<p>　　（编辑：易晨）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
