{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}英国邓肯乔丹艺术设计学院研究生系系主任珍妮特访问艺术学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2009-09-28 04:02:03{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月16日下午，英国邓肯乔丹艺术设计学院研究生系系主任珍妮特访问艺术学院，艺术学院党委书记兼常务副院长郑晓华教授在学院会议室会见了来宾。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 双方首先介绍了各自学院的情况，重点介绍了各自学科特色及课程设置，然后双方就互派师生交流、举办展览等合作事宜进行了友好的商谈，初步达成了先进行教师之间的交流意向。</p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhknnmbf-llkzhh.jpg" alt="" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑 韩宏斌）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhknnmbf-llkzhh_lit.jpg{/dede:field}
