<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","张志伟教授为研究生作“学位论文写作释疑”讲座",89,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",214,259);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-07 09:14:07",261,320);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为了进一步提高哲学院硕、博士研究生的学术素养、论文写作水平，哲学院团委、哲学院研究生会根据同学们的需要，于3月30日下午在教二2115教室举办了第二届&ldquo;以文启智&mdash;&mdash;大哲学类学生学位论文写作释疑&rdquo;讲座。&nbsp;&nbsp;此次讲座特别邀请到哲学院外国哲学专业博士生导师张志伟教授，为广大硕士博士研究生进行论文开题和撰写指导。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflzn2yhnzmnkf-llyym.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张志伟教授从工作中抽出宝贵的时间作了接近两个小时的讲座与交流。整场讲座围绕&ldquo;如何进行大哲学类学术研究和论文写作&rdquo;这个大家现在都普遍关心的话题进行，主要分为三个部分：&ldquo;专业知识的学习&rdquo;、&ldquo;研究能力的训练&rdquo;以及&ldquo;学位论文的写作&rdquo;。张志伟教授结合自己的学术经历，详细论述了论文研究的作用和重要性、研究的一般过程、重要环节、常用方法、学位论文的一般要求和写作要点、论文的汇报答辩要点及论文研究的正确态度等问题。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座过程中，张志伟教授亲切随和，演讲充满激情，话语诙谐幽默，赢得全体师生的阵阵掌声。他的讲演通俗而又不失严谨，在场的同学们受益匪浅。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n<br />\r\n</p>",322,1596);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflzn2yhnzmnkf-llyym_lit.jpg",1598,1690);
$z[7][4]['name']="litpic";

?>