{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2010年中德商标法研讨会成功举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图／文　法学院{/dede:field}
{dede:field name='pubdate'}2010-11-29 04:27:54{/dede:field}
{dede:field name='body'}<p>　　11月23日至24日，由中国人民大学法学院、知识产权学院和德国马普知识产权法、税法和竞争法研究所联合举办的&ldquo;2010年中德商标法研讨会&rdquo;在明德法学楼601国际报告厅顺利举行。来自中国人民大学、北京大学、中国社会科学院法学所、中国政法大学、华东政法大学、西南政法大学、浙江大学、同济大学、华中科技大学、厦门大学、西北政法大学、宁波大学、我国台湾清华大学社会科学法学研究所以及来自德国慕尼黑马普知识产权法、税法和竞争法研究所、维尔茨堡大学、海德堡高等技术学校以及荷兰阿姆斯特丹大学30余位海内外知名知识产权法学者出席了本次会议。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmmfybfkf-zlmnb.jpg" /></p>
<p align="center">　　中国人民大学法学院院长韩大元教授在开幕式致辞 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmmzfm2kf-2knn2.jpg" /></p>
<p align="center">　　德国马普知识产权法、税法和竞争法研究所所长Reto Hilty教授开幕式致辞 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmm2zfnyf-lbnfb.jpg" /></p>
<p align="center">　　中德科学中心主任Heike Strelen博士在开幕式致辞 </p>
<p>　　本次会议在中国商标法第三次修订正在进行中、以及欧洲共同体商标制度亦面临改革的背景下举行。在为期两天的会议中，中外学者就拒绝商标注册的绝对理由和相对理由、商标权利实施等诸多共同关心的议题深入交流了各自的看法和经验，并进行了热烈的讨论。中外学者一致认为，注册商标作为一种资源被滥用的现象十分普遍；为解决注册商标囤积现象，需要改进两国目前实行注册商标制度，加强对未注册商标的保护，促使商标被实际使用。中外学者就促进商标实际使用从商标注册、商标转让以及侵权赔偿等多方面提出了建议。在讨论驰名商标制度时，中方学者间发生了激烈的争论。虽然与会者一致批评了中国驰名商标认定制度中存在的种种问题，指出目前中国驰名商标认定制度已经偏离了建立驰名商标制度的本来意义，但在应当如何改进中国驰名商标保护制度，目前的驰名商标行政认定和司法认定的优劣以及各自的发展等问题上还存在较大的分歧。德国学者介绍了正在磋商之中的《反假冒贸易协定》东京草案，并就其中的修订之处和争议之处提出了自己的看法。与会代表还就商标法相关领域，如地理标志保护制度、商标法和反不正当竞争法的关系等问题发表了各自的看法。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnhmm22bhf-hnzhy.jpg" alt="" /></p>
<p align="center">　　中国人民大学知识产权学院院长刘春田教授作报告 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnhmm2lnzmf-blkz2.jpg" /></p>
<p align="center">　　与会代表热烈讨论 </p>
<p>　　本次会议得到中德科学中心的资助。中德知识产权法学会议每两年轮换在中德举行一次会议，迄今已经举行了三次。通过举行中德会议，两国知识产权学者不仅增进了对两国知识产权制度的理解，也增进了对两国文化了解。两国学者一致表示，希望将本次会议延续成为一种传统，并将积极探讨多方面、多形式的合作。 </p>
<p>　　（编辑：王强）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmmfybfkf-zlmnb_lit.jpg{/dede:field}
