{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中英警察与非法证据排除规则论坛成功举办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-28 02:31:39{/dede:field}
{dede:field name='body'}<p>　　3月25日下午，由中国人民大学法学院诉讼制度与司法改革研究中心承办的中英警察与非法证据排除规则论坛在明德法学楼725会议室举行。论坛由诉讼制度与司法改革研究中心主任陈卫东教授主持，英国伦敦警备司令西蒙&bull;弗耶先生了主题报告。来自最高人民法院、最高人民检察院的多位法官、检察官，中国人民公安大学等院校的诉讼法学者以及人民大学法学院刑事诉讼法教研室的众多师生参加了本次论坛，英国使馆的警务官员也出席了本次论坛。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fy2yhhmf-nmmyb.jpg" /></p>
<p>　　西蒙先生1982年9月通过毕业生入职计划加入伦敦警察署。曾在伦敦警界任多个职务及职位，并于2003年11月升职为警备司令。在论坛上，西蒙先生为中方的实务界、理论界人士及广大师生作了关于警察与非法证据排除规则、秘密侦查手段的主题报告，并与在场中方代表进行了深入而热烈的讨论。来自实务界和理论界的中方代表结合自身的工作实际以及感兴趣的话题，向西蒙先生提出了一系列问题。西蒙先生向与会观众介绍了英国的有关制度，并阐释了自己的观点。此外，还饶有兴趣的向中方代表了解中国关于非法证据排除及秘密侦查的一些制度和做法，使论坛形成有效互动。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fylz2ymf-m2bzm.jpg" /></p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fylzkl2f-zfk2km.jpg" /></p>
<p>　　论坛在和谐、融洽的气氛中圆满结束，中英双方均对论坛的成果表示肯定，并且交换了礼物。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fy2yhhmf-nmmyb_lit.jpg{/dede:field}
