{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}瑞典驻华大使馆官员访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-17 05:29:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月8日，瑞典驻华大使馆经济处官员Per Linner与Jakob Holthuis访问经济学院。经济学院院长助理郑新业副教授、郑超愚教授等就当前中国宏观经济形势和政策等问题与瑞典客人进行了深入讨论。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
