{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“水环境保护的价格与税费政策”国际研讨会成功召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2011-04-15 10:37:42{/dede:field}
{dede:field name='body'}<p>　　4月8日，由中国人民大学环境学院主办的&ldquo;水环境保护的价格与税费政策&rdquo;国际研讨会在安徽省池州市成功召开。研讨会由中国人民大学环境学院院长马中教授主持，国家水体污染控制与治理科技重大专项（以下简称&ldquo;水专项&rdquo;）管理办公室专职副主任周凤保、环境保护部政策法规司副司长别涛、环境保护部环境规划院副院长王金南总工程师、池州市委常委、副市长严琛、北京市水务局副局长刘斌参加此次会议。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hbfkbflf-znfhh.jpg" width="500" height="333" alt="" /></p>
<p>　　100多名来自中央和地方的水环境保护、水资源管理、城市建设、物价管理、林业管理领域有关部门的领导，以及美国、澳大利亚和国内政策研究部门、高等院校、科研机构、非政府组织的专家学者，汇聚平天湖畔，围绕水环境保护政策开展深入的研讨和广泛的交流。 </p>
<p>　　本次会议得到国家水专项管理办公室的精心指导，池州市人民政府的大力支持，环境保护部环境规划院、财政部财政科学研究所、安徽省环境科学研究院、北京大学环境科学与工程学院的大力支持。 </p>
<p>　　中国人民大学环境学院院长马中教授代表环境学院和国家水专项&ldquo;水环境保护价格与税费政策示范研究&rdquo;课题组欢迎与会嘉宾。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hbzzh2mf-2z2y2.jpg" width="500" height="333" alt="" /></p>
<p>　　池州市副市长严琛代表市委、市政府对本次研讨会在池州召开表示热烈欢迎，并介绍了池州市生态环境现状以及经济发展、自然保护区建设情况。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hb22fbkf-lzzym.jpg" width="500" height="333" alt="" /></p>
<p>　　国家水专项管理办公室专职副主任周凤保介绍了水专项在&ldquo;十一五&rdquo;期间取得的进展，并展望&ldquo;十二五&rdquo;工作。水专项课题2008年启动，在三部委的领导下，形成了行政与技术管理的两套体系，为&ldquo;十二五&rdquo;研究工作的开展奠定了良好基础。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hb22bfbf-hylnn.jpg" width="500" height="333" alt="" /></p>
<p>　　环境保护部政策法规司副司长别涛指出并强调，推进水价改革和完善水资源价格形成机制十分必要，并展望了&ldquo;十二五&rdquo;环境保护经济政策。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hb22mzkf-b2lym.jpg" width="500" height="333" alt="" /></p>
<p>　　环境保护部环境规划院副院长王金南总工程师总结了&ldquo;十一五&rdquo;期间我国环境保护取得的经验，强调价格和税费政策在水环境保护中的重要性，对中国人民大学承担国家水专项&ldquo;水环境保护价格与税费政策示范研究&rdquo;课题获得的成果表达了充分肯定，并期望课题组加强成果提炼，形成政策建议。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hb2llhlf-y2ynh.jpg" width="500" height="333" alt="" /></p>
<p>　　北京市水务局副局长刘斌从水资源费征收的目的出发，就水资源费改税、水污染物排污权有偿使用、水价定价等议题与参会人员进行了探讨。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2hb2hbz2f-klbby.jpg" width="500" height="333" alt="" /></p>
<p>　　研讨会在热烈而和谐的气氛中进行，与会专家和领导就水环境保护的价格与税费政策框架、水价定价技术、水污染物排污收费政策、水资源收费政策、污水处理收费政策、水污染物排污权有偿使用政策、再生水开发利用与管理政策、流域生态补偿政策等议题进行探讨，取得了丰硕成果。 </p>
<p>　　最后，中国人民大学环境学院院长马中教授做总结发言，马中教授通过分析水环境的唯一性和不可替代性，论证了水环境保护价格与税费政策研究的重大意义，并要求&ldquo;水环境保护价格与税费政策示范研究&rdquo;课题组成员面向现实、面向科学，进一步挖掘对我国水环境保护富有重大意义的研究成果。</p>
<p>（编辑：吴琰坤）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2hbfkbflf-znfhh_lit.jpg{/dede:field}
