<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","芬兰赫尔辛基大学人文学院Anja Lahtinen博士为公共管理学院师生做学术报告",89,196);
$z[2][4]['name']="title";
$z[3]=Array("field","",198,237);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",239,290);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-29 09:23:25",292,351);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月24日，芬兰赫尔辛基大学人文学院世界文化系Anja Lahtinen博士应邀访问公共管理学院，并为公共管理学院师生做了一场题为&ldquo;省级发展与政府管理质量&mdash;&mdash;转变中的青海&rdquo;的主题报告。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在讲座中，Lahtinen博士从研究背景、研究方法讲起，对相关的治理理论进行了梳理，同时介绍了她在我国进行实地调研的经历和体会，并以青海为例，深入分析了青海在发展中的优势，以及在治理中所存在的一些问题和面临的挑战，提出了自己的一些看法和建议，为大家更好地理解省级发展和政府管理质量提供了思路。Lahtinen博士还现场回答了听众提出的政府危机应对、透明度等方面的许多问题，分享了彼此的经验和看法。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflzn2bhbmklzf-zbnbh.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）&nbsp;<br />\r\n<br />\r\n<br />\r\n<br />\r\n<br />\r\n<br />\r\n</p>",353,1302);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflzn2bhbmklzf-zbnbh_lit.jpg",1304,1396);
$z[7][4]['name']="litpic";

?>