{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}芬兰赫尔辛基大学人文学院Anja Lahtinen博士为公共管理学院师生做学术报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-03-29 09:23:25{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月24日，芬兰赫尔辛基大学人文学院世界文化系Anja Lahtinen博士应邀访问公共管理学院，并为公共管理学院师生做了一场题为&ldquo;省级发展与政府管理质量&mdash;&mdash;转变中的青海&rdquo;的主题报告。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在讲座中，Lahtinen博士从研究背景、研究方法讲起，对相关的治理理论进行了梳理，同时介绍了她在我国进行实地调研的经历和体会，并以青海为例，深入分析了青海在发展中的优势，以及在治理中所存在的一些问题和面临的挑战，提出了自己的一些看法和建议，为大家更好地理解省级发展和政府管理质量提供了思路。Lahtinen博士还现场回答了听众提出的政府危机应对、透明度等方面的许多问题，分享了彼此的经验和看法。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bhbmklzf-zbnbh.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）&nbsp;<br />
<br />
<br />
<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2bhbmklzf-zbnbh_lit.jpg{/dede:field}
