{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}黎建飞教授主编的图书再次被新闻出版总署列为重点推荐图书{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-14 10:49:35{/dede:field}
{dede:field name='body'}<p>　　日前，国家新闻出版总署公布了《2010－2011年农家书屋重点出版物推荐目录》。由黎建飞教授主编，2008年11月在中国人民大学出版的《劳动合同法与实施条例简明问答三百问》被列为重点推荐图书。这是继新闻出版总署将黎建飞教授主编的《身边的法律顾问：劳动合同与社会保障》列为《2009年农家书屋重点出版物推荐目录》后的再次推荐。</p>
<p>　　农家书屋工程建设受到中央高层领导的关注，温家宝总理在《政府工作报告》中强调要突出抓好农家书屋工程等农村文化工程，逐步建立覆盖全社会的公共文化服务体系。《中共中央关于推进农村改革发展若干重大问题的决定》明确指出要推进农家书屋等重点文化惠民工程，尽快形成完备的农村公共文化服务体系。</p>
<p>　　农家书屋在广大农村扎根，使不少人掌握了致富技能，摆脱了贫困的命运。一些富裕起来的农民读者也因此把农家书屋称之为&ldquo;金钥匙&rdquo;、&ldquo;黄金屋&rdquo;、&ldquo;加油站&rdquo;和&ldquo;好基地&rdquo;。黎教授认为，为亿万农民兄弟提供法律服务是一个法律工作者应当履行的社会责任。 </p>
<p>　　(编辑：席嘉怡)</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
