{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院韩大元院长会见东莞市第一人民法院访问团一行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-05 03:31:46{/dede:field}
{dede:field name='body'}<p>　　3月3日下午，法学院韩大元院长在明德法学楼205贵宾室接见了东莞市第一人民法院陈斯院长、研究室邓爱君主任、纪检监察室吴晋城主任、政工科黄春梅科长一行。法学院党委副书记郑小敏、办公室主任兼团委书记乔鹏参加了会见。</p>
<p>　　双方就开展各种形式的合作交流促进法学理论与实践相结合进行了深入的交流，并具体商谈了法学院选派优秀博士生至东莞市第一人民法院挂职实习的合作项目。</p>
<p align="center"><img height="333" src="/uploads/allimg/c100619/z2kymzy2yhfhlkf-znn2k.jpg" width="500" alt="" /></p>
<p> </p>
<p>　　（编辑 陈慧茹）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzy2yhfhlkf-znn2k_lit.jpg{/dede:field}
