{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院“心语”社牵手天通苑趣味运动会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-05-04 10:53:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月25日，北京慧灵携手人民大学社会与人口学院&ldquo;心语&rdquo;青年志愿者协会、天通物业公司、天通苑志愿者协会，在地铁天通苑站附近的露天广场上举办了北京慧灵第二届&ldquo;趣味运动会&rdquo;。来自北京慧灵彩虹组、三原色组、阳光组三个小组的27名智障人士参加了比赛。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 趣味运动会分为蜗牛贴壳、传乒乓球、行走中的蜗牛、少林足球、叮咚投篮等10个项目，中间穿插抽奖、游戏互动等环节，并在运动会举办的同时向市民义卖慧灵学员的手工作品。运动会从下午两点半开始，持续约三个小时。整个比赛过程中，运动员们积极参赛，秩序良好。许多市民也参与进来，为运动员呐喊助威。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 比赛项目结束后，全体社会工作者、运动员、志愿者和参与活动的市民在一名德国社会工作者的带领下，绕广场围成一圈，在音乐声中跳舞鼓掌，趣味运动会一度达到高潮。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;我今天特别高兴，进步很大，短跑项目我是第一名呢。&rdquo;慧灵学员张新伟表示。参与比赛的运动员不仅得到了奖品，更得到了锻炼，这场比赛得到了运动员和市民的一致好评。来自人民大学的志愿者张梦娟同学说：&ldquo;今天感触很多，慧灵的学员们非常可爱和友好，社会工作者们也富有爱心，就像是一个温暖的大家庭，虽然很累，但还是很开心。&rdquo;来自慧灵的社会工作人员也表示，和人民大学的志愿者合作感到非常愉快，也希望以后能在更多的活动中合作。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 北京慧灵是一家专为智障人士服务的非盈利、非政府的社区机构，注册于2000年4月。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 社会与人口学院&ldquo;心语&rdquo;青年志愿者协会下设社会实践部、曙光助残部、青少年项目开发部三个分支，分别承担牛街社区实践、慧灵助残活动、行知小学支教等周次性常规活动，并在每学期举办若干次多名志愿者参与的大型活动。在人民大学2007年十项&ldquo;十佳青协项目&rdquo;评选中，社会与人口学院的两项常规活动获得了&ldquo;十佳&rdquo;称号，是学校唯一入选两项的学院。本学期由&ldquo;心语&rdquo;青年志愿者协会主办的&ldquo;朋辈互助&rdquo;活动在社会与人口学院如期试点性开展，并预计在下学期将活动规模推广至全院新生。这次趣味运动会是&ldquo;心语&rdquo;青年志愿者协会本学期的大型活动之一，人民大学的志愿者主要负责主持、裁判、场地布置、引导运动员入场、物品摆放与管理、奖品颁发、维持现场秩序等工作。据悉，本学期的其他几项大型活动仍在有条不紊地筹划之中。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：周玲） &nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
