{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}统计学院举办非寿险准备金培训班{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}2006-11-27 05:23:12{/dede:field}
{dede:field name='body'}<HTML><HEAD><TITLE> 统计学院举办非寿险准备金培训班 </TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style><!--
 .iframestyle{height:expression(1);aho:expression(autoResize()) 
}
-->
</style>
<script>
function autoResize()
{
try
{
 document.all["showDemand"].style.height=showDemand.document.body.scrollHeight
}
 catch(e){}
}
 </script><body><P>&nbsp;&nbsp;&nbsp; 11月27日上午，非寿险准备金培训班在中国人民大学逸夫第二报告厅举行。中国保监会财产监管部主任郭左践、副主任朱艺等保监会领导参加了开班仪式。原国际精算师协会主席Edward J Levay和原美国意外险精算学会主席Bob Conger到会并做主题演讲。<BR>&nbsp;&nbsp;&nbsp; 本次培训班由中国保监会财产监管部和国际精算师协会（IAA）主办，中国人民大学统计学院与韩国现代海上火灾保险株式会社承办。参加本次培训班的还有来自各地保监局、高等院校的著名专家学者以及多家保险公司的高级管理人员约180人。<BR>&nbsp;&nbsp;&nbsp; 培训班为期两天，共进行19场专题报告，内容涉及非寿险业准备金制度的各个主要方面。保监会的代表从监管部门的角度强调了合理的准备金制度在建立健全中国非寿险精算体系中的重要作用；国内主要保险公司精算部门负责人的演讲以目前中国非寿险业的市场特征和准备金提取方法为核心，分析了当前行业内存在的问题；来自国际精算师协会的专家介绍了计算准备金的前沿方法和案例实务，并从外国精算师的职业现状提出对中国完善非寿险精算体系的建议。<BR>&nbsp;&nbsp;&nbsp; 中国的非寿险业正处于蓬勃发展的阶段，然而相对落后的非寿险精算体系正逐渐成为行业进一步发展的桎梏。在本次培训班上，保险监管部门、专家学者和保险公司三方面的代表进行了充分的沟通交流和相互学习借鉴，在提高非寿险业经营管理水平，完善精算控制管理体系上迈出了重要的一步。<BR>&nbsp;&nbsp;&nbsp; 承办本次培训班的中国人民大学统计学院于1992年设立风险管理与精算专业方向，并在2004年设立风险管理与精算学硕士点和博士点。发展至今已成为中国最大的精算学术机构之一，有着一流的教师团队和备受好评的学位课程与研究项目。此前曾先后承办过中国保险监管与精算实务国际学术讨论会和中澳国际非寿险精算研讨会。<BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
