{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院承担中英合作项目启动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-02-26 04:48:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月20日上午，由中国人民大学环境学院邹骥教授领导的课题组所承担的&ldquo;省市级实施气候变化战略能力建设&rdquo;中英合作项目启动会暨工作计划研讨会在北京国宏宾馆顺利召开。英国大使馆能源与气候变化一等秘书Jonathan Thamson、国家发展和改革委员会应对气候变化司对外合作处处长蒋兆理、中国人民大学科研处处长杜鹏等出席启动会并致辞。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 英国大使馆能源与气候变化一等秘书Jonathan Thamson在致辞中指出，中国人民大学邹骥教授领导的团队在气候变化领域有丰富的工作经验，在国际上享有较高知名度。他对该项目的产出和项目成果的可持续性抱有很高期望，希望该项目的成功实施，能够真正提高中国地方省市实施和执行应对气候变化战略的能力。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学科研处处长杜鹏在致辞中感谢英国政府和国家发改委将&ldquo;省市级实施气候变化战略能力建设&rdquo;这样一个重要的能力建设项目交给中国人民大学去实施，认为这是对中国人民大学的信任，学校对此感到十分光荣和责任重大。邹骥教授所领导的&ldquo;能源与气候经济学项目&rdquo;研究团队依托中国人民大学整体学术和管理平台，已经深入参与了中国多项气候变化政策的研究与制定过程，为成功实施这一项目积累了丰富的项目经验和学术基础。学校会要求研究团队本着对国家负责的态度和精益求精的职业精神，广泛听取各位领导和专家的意见，为提高地方应对气候变化能力做出切实有效的贡献。同时杜鹏处长也代表学校恳切希望中英两国政府相关主管部门和兄弟单位的领导和专家学者，继续对中国人民大学在能源、资源和环境领域的人才培养和科学研究予以大力支持。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，中国人民大学环境学院副院长邹骥教授代表项目执行单位作了专题汇报，对项目实施方案进行了详细阐述并广泛听取了与会者对实施方案的意见和建议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，&nbsp;来自国家发改委、外交部、环境保护部、国家气象局、国家林业局等政府主管部门和来自陕西省、内蒙古自治区、贵州省、吉林省、贵阳市、白山市等地方发改委的领导，以及来自国家发改委能源研究所、环境保护部宣传教育中心等项目合作单位的专家出席了本次启动会，对项目的顺利启动表示祝贺，并对项目实施计划提出具体建议。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnflynzykf-2yyyb.jpg" /></p>
<p><br />
</p>
<p>（编辑：刘恒）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnflynzykf-2yyyb_lit.jpg{/dede:field}
