<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院党委书记张宇教授随中共代表团访问老挝并参加中老两党理论研讨会",89,195);
$z[2][4]['name']="title";
$z[3]=Array("field","",197,236);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",238,285);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月21日至23日，应老挝人民革命党邀请，中共中央政治局委员、书记处书记、中宣部部长刘云山同志率中共代表团访问老挝，并出席中国共产党与老挝人民革命党第一次理论研讨会。理论研讨会主题为&ldquo;社会主义现代化建设中的重大理论和实践问题&rdquo;。经济学院党委书记张宇教授随团参加了研讨会，并作了题为&ldquo;中国发展社会主义市场经济的理论与经验&rdquo;的发言。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会期间，中老双方专家就加强和改进执政党建设、发展社会主义市场经济、工业化和现代化建设等问题进行了深入探讨和交流。研讨会取得了圆满成功。 </p>\r\n<p>\r\n</p>",287,920);
$z[5][4]['name']="body";
$z[6]=Array("field","1288925412",922,972);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",974,1013);
$z[7][4]['name']="litpic";

?>