<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院周业安教授入选“评师网十大经济专业最受欢迎教授”",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",226,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-02 06:10:23",275,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　3月31日，在搜狐教育和评师网联合发布的&ldquo;2010各专业最受欢迎十大教授榜(211院校类)&rdquo;中，经济学院周业安教授被评为2010年全国各高校经济及管理专业最受欢迎十大教授(211院校类)之一。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",336,602);
$z[6][4]['name']="body";
$z[7]=Array("field","",604,643);
$z[7][4]['name']="litpic";

?>