{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院周业安教授入选“评师网十大经济专业最受欢迎教授”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-04-02 06:10:23{/dede:field}
{dede:field name='body'}<p>　　3月31日，在搜狐教育和评师网联合发布的&ldquo;2010各专业最受欢迎十大教授榜(211院校类)&rdquo;中，经济学院周业安教授被评为2010年全国各高校经济及管理专业最受欢迎十大教授(211院校类)之一。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
