{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京高校房地产管理专业委员会2010年年会隆重召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}资产与后勤管理处{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月16日至17日，北京高校房地产管理专业委员会（以下简称&ldquo;北京高校房专会&rdquo;）2010年年会隆重召开。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m2znk2bf-hmmfh.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部发展规划司高校后勤改革处处长朱宝铜、北京市建委住房制度改革处处长王玉明等领导出席会议。清华大学、北京大学、中国人民大学等来自北京40多所高校的60余名房产管理部门负责人参加会议。会议由北京高校房专会主任、中国人民大学资产与后勤管理处处长林建荣同志主持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在开幕仪式上，教育部发展规划司高校后勤改革处处长朱宝铜、北京市建委住房制度改革处处长王玉明先后致辞。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次年会就当前高校房地产管理工作的共性、热点问题邀请各高校代表结合实际工作经验作了主题发言。各高校代表围绕着教学、科研、行政办公用房管理、学校周转性教师公寓管理、解决高校青年教职工住房问题、高校公用房管理模式改革等热点问题进行了热烈的探讨。林建荣主任就《2010房地产市场分析报告》、首都医科大学代表就《首都医科大学供暖费支取工作经验汇报》分别作主题报告。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m22lbzhf-bkkfb.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月17上午，与会代表分为三个小组，就高校房地产管理工作中的共性问题进行了深入、广泛和热烈的讨论。在随后的讨论结果交流会上，各小组分别代表就本组讨论情况做总结发言，同时对北京高校房专会下一步工作重点、运作方式提出建议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在会议的闭幕式上，林建荣主任向大会作北京高校房专会2010年工作报告，通报2010年北京高校房专会人事任免情况，并提请大会通过，与会人员以热烈的掌声一致通过。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林建荣主任指出，本次年会是卓有成效的一次年会，各高校交流让与会代表开阔了视野、拓展了思路，主题发言让与会代表印象深刻、收获良多，各小组讨论热烈。要在现有基础上继续完善北京高校房专会工作职能，加强专题研究，采取多种方式就共性、热点问题召开专题研讨会，促进同行沟通，达成行业共识，推进各高校房地产管理工作。林建荣主任表示，北京高校房专会要继往开来，不断创新，通过为高校做实事、办好事，开展好服务，进一步提高凝聚力和影响力，推动北京高校房地产管理工作跨上一个新台阶。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 北京高校房专会由76所在京高等院校组成，2007年7月6日，人民大学当选为北京高校房专会首届主任单位，资产与后勤管理处处长林建荣当选为北京高校房专会首届主任。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1292879717{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2znk2bf-hmmfh_lit.jpg{/dede:field}
