{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}全国政协经济委员会副主任李德水与经济学院学者进行学术交流{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-10-26 10:52:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月25日上午，全国政协经济委员会副主任、原国家统计局局长李德水教授访问经济学院，与经济学院学者就当前中国汇率问题以及汇率与顺差关系等问题进行了深入研讨。经济学院院长杨瑞龙教授，胡乃武教授以及经济研究所的宏观经济分析与预测课题组成员参加了研讨会。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzh2fblf2f-kmlbh.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，李德水教授对美联储近期采取的货币宽松政策进行了回顾和分析，他提出解决中美关系以及应对汇率的几点政策建议：一是重申汇率政策问题是一个国家主权问题；二是不接受以人民币大幅升值来换取国际货币会议话语权；三是决不与美国或其他国家签订地区性汇率协议；四是要将人民币适度升值与结构调整结合起来；五是中国要在G20会议上发挥更加积极主动的作用。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经济学院副院长刘元春教授，雷达教授，院长助理王晋斌教授和赵勇博士等分别发表了对当前汇率问题的看法。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李德水教授高度评价了人民大学经济研究所的宏观经济形势分析与预测报告，他多次称赞人大经济学院的学术团队特别是青年教师学术功底扎实，潜力很大，并表示同大家交流是件十分愉快的事，很受启发。这也是他在多次出席经济学院举办的&ldquo;中国宏观经济论坛&rdquo;之外，第三次访问经济学院，就当前经济热点问题与人大学者进行研讨。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzh2fblf2f-kmlbh_lit.jpg{/dede:field}
