{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}东海证券董事长朱科敏教授做客“人大经济讲堂”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月12日上午，东海证券有限公司董事长、人大经济研究所联席所长朱科敏教授访问经济学院。期间，朱科敏教授在明德主楼0728会议室举行的&ldquo;人大经济讲堂&rdquo;上发表了题为《企业成长的路径》的学术演讲。演讲会由经济学院院长杨瑞龙教授主持，经济学院胡乃武教授、经济研究所联席副所长朱戎博士、经济学院副院长段秀芳教授、院长助理陈彦斌教授、院长助理郑新业副教授、范志勇副教授、于泽副教授、罗来军副教授、孙文凯博士、虞义华博士、刘小鲁博士、宋枫博士、杨继东博士等参加了讲座。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzznmbhfnf-llnfh.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲中，朱科敏教授通过对东海证券有限公司近年来的发展进行仔细梳理，总结出企业成长所需要的九项关键因素：一是站稳脚跟，二是守住关隘，三是提升士气，四是明确战略，五是企业文化，六是韬光养晦，七是厚积薄发，八是兼并重组，九是温故知新。朱科敏教授指出，在站稳脚跟阶段，要稳定人心和直面矛盾；在守住关隘阶段，要身先士卒，才能最终控制风险；在企业文化的塑造中；东海证券将建立国际大投行作为理想的目标；在韬光养晦阶段，要注重团队合作；在温故知新阶段，要不断总结、寻找差距，迎接更高阶段的循环发展。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在提问与回答环节，朱科敏教授与经济学院师生就企业和股东之间的关系等问题进行了深入讨论。演讲会现场气氛热烈，广大师生对于优秀青年企业家的精彩演讲都感到受益匪浅。 <br />
<br />
朱科敏教授简介 </p>
<p align="center"><img height="190" src="/uploads/allimg/c101124/z2mfbmzzmfbmknf-hb2lm.jpg" width="150" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学硕士、经济学博士。先后就职于中国财政部、中国证监会、东海证券有限责任公司，现任东海证券有限责任公司党委书记、董事长，中国人民大学经济研究所联席所长，中国人民大学经济学院兼职教授。主要科研成果：《城市商业银行上市与公司治理结构优化》，《上海金融》2008年01期；《知识经济社会中劳动价值论的新阐释&mdash;&mdash;读&lt;新资本论纲要&gt;有感》，南大商学评论2005年02期；《秩序&bull;公平&bull;效率&mdash;&mdash;市场法律价值目标模式定位》，《法学》1995年04期；《我国证券公司股权结构理论分析》 上海财经大学出版社 2007年11月等。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1286933390{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzznmbhfnf-llnfh_lit.jpg{/dede:field}
