{dede:noteinfo notename="人大新闻" channelid="1" macthtype="string"
	refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas=""
 nothas="" listpic="0" usemore="0"}
	{dede:addurls}http://www.ruconline.com/new.asp?page=1&anclassid=39&nclassid=415&nclass=新闻动态
http://www.ruconline.com/new.asp?page=2&anclassid=39&nclassid=415&nclass=新闻动态
http://www.ruconline.com/new.asp?page=3&anclassid=39&nclassid=415&nclass=新闻动态{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<td width="91%"><b>新闻动态</b></td>{/dede:areastart}
	{dede:areaend}<form method=Post action=new.asp?anclassid=39&ncla{/dede:areaend}
{/dede:listrule}
