{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}香港中文大学政治与公共行政学系主任王绍光教授来公共管理学院讲学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-07-16 04:26:16{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应中国人民大学公共管理学院行政管理学系主任孙柏瑛教授的邀请，7月13日，著名政治学者、香港中文大学政治与公共行政系主任王绍光教授来公共管理学院为部分博士生、硕士生以及正在参加暑期集中的MPA学生做了题为&ldquo;和谐社会的制度基础&rdquo;的学术讲座。公共管理学院副院长张成福教授、行政管理学系主任孙柏瑛教授联合主持了讲座。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在讲座过程中，王绍光教授结合他多年治学的心得，阐述了国家基本制度建设的重要性，并且从国家建设的八大能力（强制能力、汲取能力、濡化能力、规管能力、统领能力、再分配能力、吸纳能力、整合能力）出发，系统地提出了他在构建和谐社会制度基础方面的观点。同时，王绍光教授还结合大量的实证数据和图表以及生动的事例，深入浅出地分析了中国国家基本制度建设的进展和挑战。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王绍光教授精彩的演讲引发了在场师生的热烈提问和讨论，取得了良好的互动效果。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
