{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院常务副院长张勇先教授率团访问高雄师范大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院冯雨菲　外国语学院杨晓晓{/dede:field}
{dede:field name='pubdate'}2011-03-07 03:06:16{/dede:field}
{dede:field name='body'}<p>　　1月20日至25日，外国语学院常务副院长张勇先教授应邀率代表团访问高雄师范大学。</p>
<p>　　张勇先教授一行受到了高雄师范大学校长戴嘉南博士和文学院院长张玉玲博士等师生的热情接见。在交流座谈会上，戴嘉南校长首先对张勇先教授一行表示诚挚欢迎，并回顾了两校自建立姐妹学校关系之后的互动概况，对人大师生给予了极高的评价。随后，张勇先教授简要介绍了人大的相关情况和外国语学院的相关发展思路，为两校进一步开展更高、更深层次的学术交流和互访奠定了良好的基础。最后，相关人员一同观看了高雄师范大学的宣传片，并合影留念。</p>
<p>　　会后，在戴嘉南校长及师生的陪同下，张勇先教授一行进一步感受了台湾的风土人情，并参观了高雄师范大学附属中学，了解了其语音、视频教学等方面的突出优势。 </p>
<p>（编辑：吴琰坤）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
