
	{dede:addurls}http://www.ruconline.com/new.asp?page=1&anclassid=39&nclassid=415&nclass=新闻动态
http://www.ruconline.com/new.asp?page=2&anclassid=39&nclassid=415&nclass=新闻动态
http://www.ruconline.com/new.asp?page=3&anclassid=39&nclassid=415&nclass=新闻动态{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<td width="91%"><b>新闻动态</b></td>{/dede:areastart}
	{dede:areaend}<form method=Post action=new.asp?anclassid=39&ncla{/dede:areaend}
