<?php
$z[0]=Array("addurls","http://www.ruconline.com/new.asp?page=1&anclassid=39&nclassid=415&nclass=新闻动态\r\nhttp://www.ruconline.com/new.asp?page=2&anclassid=39&nclassid=415&nclass=新闻动态\r\nhttp://www.ruconline.com/new.asp?page=3&anclassid=39&nclassid=415&nclass=新闻动态",3,279);
$z[1]=Array("batchrule","",282,315);
$z[2]=Array("regxrule","",318,349);
$z[3]=Array("areastart","<td width=\"91%\"><b>新闻动态</b></td>",352,421);
$z[4]=Array("areaend","<form method=Post action=new.asp?anclassid=39&ncla",424,503);

?>