<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","日本一桥大学副校长田近荣治教授访问经济学院",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",212,259);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月5日，日本一桥大学副校长田近荣治教授、校长助理前原康宏教授、北京事务所所长志波干雄一行访问经济学院。经济学院杨瑞龙院长会见了日本客人，双方就即将于今年4月在日本东京由两校联合举办的的&ldquo;中国人民大学&mdash;日本一桥大学第一届亚洲政策论坛&rdquo;举行第二轮磋商。双方就若干重大问题取得了一致意见，并就下一步合作事宜做出了分工。经济学院关权教授、郑新业副教授陪同会见。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",261,751);
$z[5][4]['name']="body";
$z[6]=Array("field","1267058559",753,803);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",805,844);
$z[7][4]['name']="litpic";

?>