{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学艺术学院赵方副院长、杨戈芳教授当选为中国音乐家协会室内乐学会首届理事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-06-03 12:20:45{/dede:field}
{dede:field name='body'}<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月25&mdash;27日，中国音乐家协会室内乐学会成立暨室内乐学术研讨会在广州举行，中国人民大学艺术学院赵方副院长、杨戈芳教授应邀参加了成立大会并当选为首届理事。</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次会议汇集当今中国最优秀的室内乐演奏家、教授和国内八大乐团的首席演奏家，就室内乐在中国的发展作了深入的研讨。由于艺术学院音乐系在四年前就将室内乐作为学科发展的重点，在全国成功巡演并产生极大的影响力，与会代表格外重视学院教授在室内乐教学和发展上的学术主张和建议，并给予了高度评价。在室内乐学会成立大会的音乐会上，杨戈芳教授领衔演奏了弦乐四重奏，受到在场一千多观众的热烈欢迎。</p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhkzfnnlf-zzhknl.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkzfnnlf-zzhknl_lit.jpg{/dede:field}
