{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学海外校友穆罕默德塞德福法纳出任几内亚共和国总理{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-31 11:52:12{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12日24日，几内亚孔戴总统任命经济学家、前工商业和私营企业部协调、后续和项目评估司长穆罕默德&bull;塞德&bull;福法纳为几内亚新政府总理。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 穆罕默德&bull;塞德&bull;福法纳曾于2006年9月12日至26日，来人民大学参加了由经济学院承办的商务部援外人力资源开发合作项目&ldquo;非洲法语国家贸易投资研修班&rdquo;。在两周的学习生活中，穆罕默德&bull;塞德&bull;福法纳与其他22名非洲国家官员一起参加了由我校多位著名教授主讲的多场讲座，并参观考察了北京和云南的多个著名企业和名胜古迹。在这一过程中，他对中国产生了深厚的感情，并与人民大学老师和工作人员结下了深厚的友谊，他在研修班总结中说，在人民大学的学习在自己的记忆中留下了美好的回忆，并将使自己终身受益。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 穆罕默德&bull;塞德&bull;福法纳先生1952年1月生于几内亚金迪亚省福里卡里亚市，1976年毕业于科纳克里大学经济与财政学专业，先后赴罗马尼亚和瑞士日内瓦进修，获人口和发展学硕士学位。他先后在计划部、工商会和贸工部就职，并投身商务管理多年。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
