{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院教师赴台参加2010两岸MPA教育论坛与大陆公共管理院长论坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-12-20 11:48:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由全国公共管理硕士（MPA）专业学位教育指导委员会、台湾中华公共事务管理学会主办，海峡两岸MPA教育论坛与大陆公共管理院长论坛于2010年12月5-8日在台北市圆山大饭店和高雄市的中山大学举行。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大陆五十余所高校的公共管理学院院长和MPA教育专家共67人组团参会。朱立言教授作为全国MPA教指委秘书处秘书长和代表团副团长、杨凡作为MPA秘书处办公室主任参加论坛。董克用院长代表公共管理学院院长致辞，并向大会做了&ldquo;构建多层次、全方位的MPA人才培养体系&rdquo;的专题学术报告。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
