{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本九州大学三轮宗弘教授一行访问经济学院并发表学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-16 02:41:01{/dede:field}
{dede:field name='body'}<p>　　3月15日下午，日本九州大学三轮宗弘教授、崛井伸浩副教授以及潘燕萍研究员一行访问经济学院。三轮宗弘教授在明德法学楼0402室进行了合作交流项目宣讲，崛井伸浩副教授发表了题为&ldquo;日本经济停滞的背景：制造业大国的衰退和今后发展的战略&rdquo;的学术演讲。</p>
<p>&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzknhznmyf-yklbz.jpg" width="500" height="333" alt="" /></p>
<p><br />
　　三轮宗弘教授及潘燕萍研究员向同学们介绍了中国人民大学经济学院与九州大学经济学部的共同培养、学生交换等项目情况，并提供了细致热心的留学咨询服务，表示希望有更多经济学院的优秀毕业生前去九州大学进修，共同努力，为加强两校的学术交流与合作做贡献。 <br />
　　崛井伸浩副教授在演讲中着重分析了上世纪九十年代后日本国际竞争力、产业结构、贸易结构等方面发生的深刻变化，并提出日本企业的未来发展战略，强调与中国企业进行战略合作的必要性和重要性。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzknhznmyf-yklbz_lit.jpg{/dede:field}
