{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院孙久文教授参加住房和城乡建设部“十一五”国家科技支撑计划重点项目课题验收会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-29 10:21:00{/dede:field}
{dede:field name='body'}<p>　　3月23－25日，由住房和城乡建设部组织实施的&ldquo;十一五&rdquo;国家科技支撑计划重点项目&ldquo;区域规划与城市土地节约利用关键技术研究&rdquo;在北京召开课题验收会，住建部、中国城市规划院、中科院、中国人民大学、清华大学等单位的12名专家组成课题验收专家委员会对课题进行验收。 <br />
　　经济学院区域与城市经济研究所所长孙久文教授受邀担任课题验收专家并全程参加该项目的课题验收工作。据悉，该项目就区域规划与城市土地节约利用方面的关键技术进行科技攻关，在一些空间集成技术方面取得了突破。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
