{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学法学院与北京市人民检察院举行交流活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院  文/王永娜{/dede:field}
{dede:field name='pubdate'}2010-12-16 09:26:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月13日下午，中国人民大学法学院韩大元院长、林嘉书记兼副院长、刘明祥副院长、肖中华副书记、郑小敏副书记以及刑法教研室主任谢望原教授、诉讼法教研室李奋飞副教授、办公室主任兼团委书记乔鹏、团委常务副书记邢姝和学生代表前往北京市人民检察院参观访问，探讨双方在各领域的合作开展，并看望中国人民大学法学院在北京市检察系统工作的优秀毕业生代表。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmbfk2zlf-zhbz2m.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 北京市人民检察院副局级检察员、政治部副主任高凯，政治部干部处处长张豫、副处长税绍斌，西城区人民检察院党组成员、政治处主任张伟，海淀区人民检察院政治处副主任王宏伟等北京市、区检察院领导热情接待了法学院师生一行，并陪同法学院师生认真参观了北京市反腐倡廉教育基地和院史展览。法学院师生还参观了检察院干警俱乐部，这里中式典雅的布局设计和注重细节的设施设备体现出对干警的人文关怀，给法学院师生留下了深刻印象。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参观结束后，双方举行了交流座谈会。高凯副主任代表市检察院欢迎人大法学院师生的到来，并介绍了参加交流会的北京市检察系统干警，他们都是人大法学院的优秀毕业生，现在已经成长为北京市检察系统的先进代表。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmbz2nfkf-zbkk2m.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩大元院长代表法学院致辞。韩大元院长感谢北京市检察院对法学院六十周年院庆和就业工作的大力支持，感谢各位校友在检察系统争创先进，为人大法律人塑造了良好的形象。韩大元院长还向市检察院领导和校友介绍了人大法学院未来的发展战略以及在发展过程中遇到的机遇和挑战，并着重介绍了法学院&ldquo;健全人格、崇尚法治、追求真理、服务社会&rdquo; 十六字人才培养方针以及 &ldquo;传承、巩固、拓展、改革&rdquo; 八字发展思路。韩大元院长表示，本次访问的主要目的是要了解北京市检察院系统历届毕业生的工作现状和职业感受，结合检察院领导和校友对法学院人才培养工作的评价和反馈，进一步改进学院的教学工作和就业工作。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmbhhyfzf-zyyfzf.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 高凯副主任通过详实的数据资料介绍了人大法学院毕业生在北京市各级检察系统的工作情况，赞扬了人大法学院对中国法学教育和检察官队伍人才培养做出的贡献，也对人大法学院毕业生取得的工作成绩给予了高度的评价。高凯副主任介绍了人大法学院与市检察院在教师挂职副检察长、专家咨询委员会等方面的合作情况，希望继续加深与法学院交流与合作。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmbhbbmlf-zkzyh2.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自北京市各级检察系统的9名优秀校友分别发言。在谈到自己在检察系统岗位上的工作经历与成长历程时，他们总结到法学院的教育栽培为他们奠定了扎实的知识基础，提供了开阔的知识视野，培养了脚踏实地的工作态度和较强的环境适应能力。结合自己的工作经验，各位校友向学院提出了加强职业技能教育和人文精神培养等方面的建议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林嘉书记兼副院长作了总结发言，她表示法学院的老师们为各位校友的杰出工作成绩而感到欣慰。林嘉书记兼副院长表示校友们的建议符合学院人才培养工作改进目标，并表示法学院将进一步加强与北京市检察系统各方面的交流合作。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmbblzb2f-znbby2.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在活动过程中，法学院兼职教授、北京市人民检察院副院长甄贞还与法学院师生一行进行了交流。活动最后，甄贞副检察长等宴请了法学院师生，韩大元院长代表法学院赠送礼物并合影留念。</p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmbblkmbf-zmnmfb.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖） <br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmbfk2zlf-zhbz2m_lit.jpg{/dede:field}
