{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}德国慕尼黑工业大学常务副校长孟立秋教授访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际交流处{/dede:field}
{dede:field name='pubdate'}2011-04-12 09:13:03{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月7日下午，副校长杨慧林教授会见了来访的德国慕尼黑工业大学常务副校长孟立秋教授。陪同孟立秋教授来访的还有该校驻京办事处代表金贞善。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbkbknfbf-zz2fh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;慕尼黑工业大学自进入21 世纪以来连年稳居德国高校排名榜首，2006年成为联邦政府命名的德国首批三所精英大学之一。慕尼黑工大不仅在学术和科研方面占据全球领先地位，学校也十分重视艺术德育方面的发展。慕尼黑工大爱乐乐团是一支由学生，教职员工，教授，校友及社会其他爱乐人士组成的交响乐团，在校内外享有盛名。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会见结束后，孟立秋副校长在学校如论讲堂观看了由中国人民大学学生艺术团交响乐团与德国慕尼黑工业大学交响乐团联袂演出的&ldquo;乐&bull;缘之夜&rdquo;交流音乐会。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbky2llkf-2lmmm.jpg" /></p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://news1.ruc.edu.cn/102449/102451/102463/75238.html">【相关链接】&ldquo;乐&bull;缘之夜&rdquo;中国人民大学学生艺术团交响乐团与德国慕尼黑工业大学交响乐团交流音乐会圆满成功</a>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbkbknfbf-zz2fh_lit.jpg{/dede:field}
