{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院师生应邀参加“六五世界环境日特别论坛”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-06-09 10:27:45{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月5日是世界环境日，在这个有着特殊意义的日子里，人民大学环境学院一行52名学生，在院团委书记王炜老师的带领下参加了在钓鱼台国宾馆举行的由国家环境保护部主办、环保部宣教司和中国环境文化促进会承办的&ldquo;探索中国特色环境保护新道路&mdash;&mdash;六&bull;五世界环境日特别论坛&rdquo;。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年世界环境日联合国主题是：你的星球需要你，联合起来应对气候变化。我国今年的主题是：减少污染&mdash;&mdash;行动起来。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnfh2fbk2f-hy2bl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届论坛旨在从理论研究局面和社会实践层面积极探索中国特色环境保护新道路的可行性、必要性及如何实践中国特色环境保护新道路。论坛特别邀请了全国政协副主席厉无畏出席并致辞，环境保护部部长周生贤作了&ldquo;坚持以建设生态文明为指导，积极探索中国特色环境保护新道路&rdquo;的主题演讲，同时还邀请了全国政协常委、北京大学光华管理学院名誉院长厉以宁、湖北省人民政府副省长赵斌、湖南省人民政府副省长刘力伟作专题演讲。在本届论坛上发表演讲的嘉宾还有：国家发展和改革委员会资源节约和环境保护司副司长何炳光、国务院研究室综合司副司长范必、中科院科技政策与管理科学研究所副所长王毅、中国社会科学院当代中国研究所副所长武力、国家能源专家咨询委员会副主任周大地等。到会的各位领导和专家学者围绕环境保护新道路与新的发展模式、新的发展战略、新的发展体制、新的文化等问题阐述了自己的观点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在主题报告中，环境保护部周生贤部长的主题演讲给大家留下了深刻的印象：他在报告中全面阐述了建设生态文明的题中之义，阐述了环保新道路的各项鲜明特征，并提出了行动中的&ldquo;三个转变&rdquo;。各位领导、专家的精彩演讲博得了场内观众的阵阵掌声，也在环保新道路方面给大家以许多新的启发。参会同学均表示能够如此直接地聆听相关领导、专家、学者的报告，收益良多，感受颇深，在这一过程中加深了自己对于环保新道路的认识与实践理解，很珍惜如此难得的机会。 </p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnfh2kb2bf-bzmzy.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 能够受邀参加由国家环境保护部主办的高端论坛，是人民大学环境学院师生的至高荣誉和对学院学生专业素质的肯定。本次活动开阔了同学们的视野，启发专业思路，让大家在与国家相关领导、学术巨匠的思想交流中迸发出学术火花，更近距离地了解到国家的环境政策、施政方针，以及学术与实践的新成果。整个活动中，人民大学环境学院学生展示出良好的素质，展现了人民大学学生良好的精神风貌，受到了主办方的高度评价和一致好评，活动取得了圆满成功。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfh2fbk2f-hy2bl_lit.jpg{/dede:field}
