{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学理论专家2011年新春联谊会召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}党委宣传部{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月7日下午，党委宣传部举行理论专家2011年新春联谊会。校党委书记程天权出席并讲话，校党委副书记兼副校长王利明，校长助理郝立新出席联谊会。来自学校相关部门的20多位专家学者参加了联谊会。党委宣传部部长郑水泉主持联谊会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记首先代表学校党委向与会专家学者和全校理论工作者表达了新春的祝福。程天权书记指出，在刚刚过去的2010年，学校的理论专家积极参与理论学习、理论宣传和理论研究工作，为人民大学的理论学科建设、理论人才培养和党的理论宣传和理论研究工作做出了积极贡献。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2m2nzhnf-bnzzm.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记指出，当今世界正在发生广泛而深刻的变化。特别是随着经济全球化的深入发展，各种思想文化的交流、交融、交锋日趋频繁，理论研究处在一个比较复杂的环境里。气候变化、金融危机等全球性问题与地区争端、意识形态等问题相互交织，这给高校理论宣传和研究工作不断提出新的课题。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记强调，中国人民大学的理论队伍具有坚定、团结、勤奋等方面的优势与特点。2011年是中国共产党成立90周年，也是辛亥革命100周年，人民大学的理论工作者在新的一年里，要把握好历史机遇，在坚持以马克思主义为指导的基础上，大胆解放思想，勇于创新，拓宽理论研究视野，提升理论研究水平，积极回应和解答现实提出的重大问题，为丰富和发展中国特色社会主义理论体系，为国家经济建设和社会发展，更好地发挥智囊团、思想库作用，为进一步提升学校的社会影响力做出新的更大的贡献。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟） <br />
</p>{/dede:field}
{dede:field name='pubdate'}1294626326{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2nzhnf-bnzzm_lit.jpg{/dede:field}
