{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院开展“为学校学院科学发展建言献策”活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-04-14 02:47:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，人民大学社会与人口学院结合《中国人民大学开展深入学习实践科学发展观活动实施方案》中所列需要研究解决的重点问题，面向全院学生开展了&ldquo;为学校学院科学发展建言献策&rdquo;主题活动。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 活动分为三个步骤：邀请学生代表召开座谈会、进行抽样问卷调查和网上提案征集、汇总整理各类意见和建议。4月1日至6日，学院通过抽样，向本硕博各年级学生共发放调查问卷80份，收集有效问卷79份。问卷围绕教育创新、校园建设、工作制度、校风学风、学习就业、日常食宿、基础设施、社会实践等问题展开了调查。学院分团委对回收上来的问卷进行了录入和分析，并撰写了报告。从调查结果中看，同学们对学校各项工作总体上是放心和满意的，但也有一些值得改进的方面，同学们都在问卷中提出了相应的宝贵建议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这项活动激发了同学们的主人翁意识，有利于了解学生的真实需求和思想动态，从而促进学校学院的科学发展。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张莉）</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
