{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“比较哲学方法论”研讨会在人大召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2009-07-28 06:08:29{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月25日，中国人民大学国际中国哲学与比较哲学研究中心2009&ldquo;比较哲学方法论&rdquo;研讨会在人大逸夫会议中心召开。中国人民大学原副校长兼哲学院院长、现任中国浦东干部学院常务副院长冯俊教授，中国人民大学副校长杨慧林，以及中国人民大学客座教授、美国夏威夷大学哲学系成中英教授共同担任会议主席，北京地区从事中国哲学与比较哲学的学者40余人参加了会议。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强） <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
