<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","“比较哲学方法论”研讨会在人大召开",89,161);
$z[2][4]['name']="title";
$z[3]=Array("field","",163,202);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",204,249);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-07-28 06:08:29",251,310);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月25日，中国人民大学国际中国哲学与比较哲学研究中心2009&ldquo;比较哲学方法论&rdquo;研讨会在人大逸夫会议中心召开。中国人民大学原副校长兼哲学院院长、现任中国浦东干部学院常务副院长冯俊教授，中国人民大学副校长杨慧林，以及中国人民大学客座教授、美国夏威夷大学哲学系成中英教授共同担任会议主席，北京地区从事中国哲学与比较哲学的学者40余人参加了会议。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强） <br />",312,814);
$z[6][4]['name']="body";
$z[7]=Array("field","",816,855);
$z[7][4]['name']="litpic";

?>