<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","学校发展规划处到经济学院就“十年腾飞”学科建设规划进行调研",89,185);
$z[2][4]['name']="title";
$z[3]=Array("field","",187,226);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",228,275);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月24日，经济学院在明德主楼734会议室召开&ldquo;十年腾飞&rdquo;学科建设规划调研会。学校发展规划处处长、高教研究室主任胡娟研究员，发展规划处李红宇副处长、赵玉麟副处长以及规划处相关科室负责人出席了调研会。经济学院院长杨瑞龙教授、党委书记张宇教授，胡乃武教授，副院长刘元春教授、刘瑞教授、郭杰副教授，李军林教授、韩玉军教授，党委副书记丁凯等参加会议。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzhym2m2mzf-zlmzyy.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，杨瑞龙院长介绍了经济学院&ldquo;十年腾飞&rdquo;学科建设规划的总体情况，双方就学科建设规划中的相关发展指标等问题进行了深入讨论。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzhymlknyhf-zhbzzy.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p>&nbsp;<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 发展规划处胡娟处长对学院已取得的成绩和2010年的学科建设规划给予高度评价，并祝愿经济学院的教师能够多出优秀学术成果，为学校的&ldquo;十年腾飞&rdquo;贡献自己的力量。 </p>\r\n<p>\r\n</p>",277,1382);
$z[5][4]['name']="body";
$z[6]=Array("field","1262051787",1384,1434);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c100619/z2kymzhym2m2mzf-zlmzyy_lit.jpg",1436,1529);
$z[7][4]['name']="litpic";

?>