{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第7届宗教社会科学年会在中国人民大学召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-07-30 05:31:20{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月26至27日，第7届宗教社会科学年会在中国人民大学逸夫会议中心隆重召开。中国人民大学副校长杨慧林教授，校长助理、哲学院院长郝立新教授，宗教高等研究院院长、中央文史馆馆员、我校一级教授方立天先生，美国黑人社会学会会长Sandra L. Barnes教授，台湾中央研究院瞿海源研究员，皮尤基金会Brian Grim研究员，美国普度大学中国宗教与社会研究中心主任杨凤岗教授出席会议并致辞。会议由年会发起人、哲学院副院长魏德东主持。 </p>
<p>&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnzzzlm2hf-z2mnk.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式上，杨慧林副校长对会议的召开表示祝贺，指出我校创办的宗教社会科学年会及中美欧暑期宗教学高级研讨班对于促进中国宗教的实证研究发挥了积极的推动作用。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 方立天教授指出，宗教社会科学年会可以说是近年来宗教学界最活跃的板块，生机勃勃，吸引了不同学科的学者参加，形成了学术团队，改变了中国宗教研究的固有版图，对于中国的宗教研究，以及宗教工作，必将发挥越来越大的影响。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨凤岗教授认为，宗教社会科学的创办与发展，从全球视角看，展现了中国宗教自由的新境界，代表着中国宗教研究的开放。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郝立新院长指出，宗教社会科学年会能够吸引中外这么多优秀的宗教学方面专家研讨中国宗教的发展问题，是哲学院的荣幸，希望年会能够取得圆满成功。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届宗教社会科学年会的主题是&ldquo;中国宗教的现状与未来&rdquo;，来自美国、意大利、加拿大、瑞典、瑞士、法国、菲律宾、澳大利亚、新加坡、阿联酋、德国，以及中国各高校、社科院的专家学者160余人参加会议，104人提交的论文被收入会议论文集，为历届年会之最。在短短两天的会议日程里，与会者围绕着宗教市场论、宗教生态论、基督教的实证研究、当代中国民间宗教信仰、以及中国宗教在世界的发展等21个议题进行了卓有成效的探讨。其中，&ldquo;与自然界的演化一样，宗教发展也是一个自组织系统，具有自我调适，保持平衡的能力；过分人为地干预宗教环境，特别是在政策层面的不恰当介入，很可能导致宗教生态的失衡&rdquo;以及&ldquo;中国的宗教也对海外渗透&rdquo;等观点令人耳目一新。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 宗教社会科学年会创办于2004年，由哲学院魏德东副教授发起，迄今已有7年的历史。自第1届年会的20人发表论文，发展到今天的超过100人，生动地体现了该学科的发展。从与会者的学科构成看，今天的宗教社会科学，早已不再局限于传统的宗教学、社会学、人类学、民族学，而已经成为经济学、法学、政治学、国际关系、教育学、心理学和医学等多学科学者共同关注的领域。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnzzzlm2hf-z2mnk_lit.jpg{/dede:field}
