{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}西班牙IE新闻学院来访{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-05-31 02:31:42{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月27日下午，西班牙IE商学院/ IE新闻学院中国代表处首席代表Albert Krisskoy 造访新闻学院并做演讲。Albert用流利的中文向同学们介绍了西班牙IE新闻学院的历史发展和学科建设情况。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 西班牙IE新闻学院是IE商学院（<a href="http://www.ie.edu">www.ie.edu</a>）的下属学院。IE 商学院创办于1973年，拥有来自于25个国家的400多名教授和来自全球81个国家的学生。在世界商学院中，排名位居前列。今年4月，西班牙IE商学院与新闻学院就学术交流、师生往来等事宜达成合作意向。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次活动是由新闻学院广告与传媒经济系具体负责安排的，常务副院长倪宁教授会见了Albert，韩晓宁老师陪同。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
