<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","西班牙IE新闻学院来访",89,147);
$z[2][4]['name']="title";
$z[3]=Array("field","",149,188);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",190,237);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-31 02:31:42",239,298);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月27日下午，西班牙IE商学院/ IE新闻学院中国代表处首席代表Albert Krisskoy 造访新闻学院并做演讲。Albert用流利的中文向同学们介绍了西班牙IE新闻学院的历史发展和学科建设情况。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 西班牙IE新闻学院是IE商学院（<a href=\"http://www.ie.edu\">www.ie.edu</a>）的下属学院。IE 商学院创办于1973年，拥有来自于25个国家的400多名教授和来自全球81个国家的学生。在世界商学院中，排名位居前列。今年4月，西班牙IE商学院与新闻学院就学术交流、师生往来等事宜达成合作意向。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次活动是由新闻学院广告与传媒经济系具体负责安排的，常务副院长倪宁教授会见了Albert，韩晓宁老师陪同。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）<br />\r\n</p>",300,1110);
$z[6][4]['name']="body";
$z[7]=Array("field","",1112,1151);
$z[7][4]['name']="litpic";

?>