{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学召开企业理论与实践暨邓荣霖从教50周年座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/ 校报 谢天武 图/新闻中心  罗豫伟 王开{/dede:field}
{dede:field name='pubdate'}2011-01-09 09:55:45{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在中国经济学研究领域，有&ldquo;厉(以宁)股份、吴(敬琏)市场、邓(荣霖)公司&rdquo;之称，其中&ldquo;邓公司&rdquo;便是指中国人民大学商学院邓荣霖教授，他在30年前率先开创公司研究新领域赢得学界的赞誉。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2m2lykhhf-zfhhbf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月8日下午，由中国人民大学商学院主办、中国人民大学校友会协办的&ldquo;企业理论与实践暨邓荣霖从教50周年座谈会&rdquo;在中国人民大学逸夫会议中心召开。中国人民大学校长纪宝成教授，副校长林岗教授，全国人大常委、财经委员会陈佳贵委员，中国人民大学原副校长杜厚文教授出席。&nbsp;</p>
<p>&nbsp;</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2hfnmhf-zzzfmh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自中国人民大学、中国社会科学院、国务院发展研究中心、国资委、清华大学、北京大学、中央财经大学、北京师范大学、北京交通大学、首都经济贸易大学、华北电力大学、北京工业大学、中国企业联合会等单位的专家学者、企业家和人大师生、校友代表共100多人欢聚一堂，为从1961年中国人民大学工业经济系毕业留校任教，曾担任中国人民大学工业经济系系主任、国务院学位委员会第四届工商管理学科评议组成员的邓荣霖教授庆祝，同时一起畅谈企业理论与实践这一博大而精深的时代论题。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 座谈会上，邓荣霖企业管理研究基金会宣布成立，这是邓荣霖的学生捐资1000万港币为老师献上的贺礼。基金将用于资助中国人民大学的老师和学生开展的关于企业管理的学术研究项目，以及支持企业管理研究领域的重要学术会议召开，论文发表，及专著出版。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓荣霖教授的《论公司》姊妹篇新作《企业论》也在座谈会上与大家见面并受到一致好评。 </p>
<p>&nbsp;</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2hzlmhf-z2zzmy.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学校长纪宝成教授专程到会，向邓荣霖教授表示祝贺和感谢，他用三个&ldquo;热爱&rdquo;形容邓教授从教50周年，&ldquo;热爱教育&rdquo;、&ldquo;热爱课堂&rdquo;、&ldquo;热爱学生&rdquo;，终身从事教育事业，而且终身孜孜以求，与时俱进，培养了无数的学生。纪宝成校长感谢他为中国人民大学企业管理学科发展及中国经济体制改革、特别是建立企业现代制度方面做出了杰出贡献。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 原国家经济委员会主任、原中国企业管理协会暨中国企业家协会会长、中国人民大学老校长袁宝华来信祝贺。袁宝华老校长称赞邓荣霖教授在公司理论与实务、现代企业制度、组织理论与实践、现代企业管理等方面的教学和研究，著作等身，成果累累；作为一位杰出的教师，培养了大批高层次人才，桃李满天下；对推动我国企业改革与发展、特别是现代企业制度的建立颇有贡献。 </p>
<p>&nbsp;</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2bkky2f-zlhk2m.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学商学院伊志宏院长表示，邓荣霖教授已经在教坛辛勤耕耘50载，至今仍活跃在理论研究和管理实践的一线工作岗位上，在学术界、企业界和经济、社会领域仍有较大影响力，这位深爱学校和商学院的学者仍在发挥余热，继续为学校和商学院的发展争光添彩，他的精神令人敬佩、感动。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 全国人大常委、中国社会科学院学部主席团代主席、经济学部主任陈佳贵，北京大学校务委员会副主任、原副校长张国有教授，国务院国有资产监督管理委员会改革局原副局长周放生，中国企业联合会、中国企业家协会于武副理事长，北京住总正华开发建设集团有限公司董事长张小琨分别发言。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2bnzzhf-zhmfnh.jpg" /></p>
<p align="center">图为全国人大常委、中国社会科学院学部主席团代主席、经济学部主任陈佳贵发言</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2bnyymf-zb2l2h.jpg" /></p>
<p align="center">图为北京大学校务委员会副主任、原副校长张国有教授发言</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2bmfnf-zybfhz.jpg" /></p>
<p align="center">图为国务院国有资产监督管理委员会改革局原副局长周放生发言</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2yffnmf-zkbkhy.jpg" /></p>
<p align="center">图为中国企业联合会、中国企业家协会于武副理事长发言</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110113/z2mhnn2m2yzhymf-znlyby.jpg" /></p>
<p align="center">图为北京住总正华开发建设集团有限公司董事长张小琨发言</p>
<p>　　结合邓荣霖教授的研究成果，与会嘉宾就企业理论与实践、现代企业管理、公司制度与企业集团、企业改革与发展、民营企业建制等问题进行了陈述，一致认为，公司问题研究对我国经济体制改革具有极其重要的现实意义和战略意义，邓教授较早系统提出&ldquo;建立并发展具有中国特色的社会主义公司体系&rdquo;的设想、框架和内涵，在我国企业界和理论界受到重视，享有很高的威望。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 谈到企业理论与实践，大家认为，《论公司》反映了邓荣霖教授在国内开创并系统研究公司理论和奠基现代企业制度理论的学术历程，《企业论》则在此基础上对企业成长和发展所涉及的企业制度理论和企业管理理论及其在中国的具体运用进行了全面、深入和独到的研究。作为《论公司》一书的姊妹篇，《企业论》主要收录了邓荣霖教授多年来紧密结合中国实际对企业制度和企业管理进行理论研究的最新进展，研究内容涉及中国企业成长和发展的多个方面，是对《论公司》一书的扩展和深化。《企业论》立足于中国企业发展的现实，采用理论与实践相结合、国内与国外相结合的研究方法，分析问题与解决问题，紧密把握各个历史阶段的中国企业现状和发展趋势，提出了新的思路和对策来推动中国企业理论研究和企业实践的发展。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2m2ylzznf-zmbky2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓荣霖教授的博士生和硕士生代表在会上发言，回忆了跟随邓教授学习、实践的过程，大家在发言中都认为邓荣霖教授能够始终坚持&ldquo;宽以待人、严于律己，取人之长、补己之短，教研结合、教研相长，光阴似箭、耕耘人生&rdquo;的人生格言和&ldquo;专中有博、博中求专，学术思维、创新为魂，实践常青、理论不止，科学知识、代代相传&rdquo;的治学格言，为人师表、治学楷模，令人敬佩。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在自由发言阶段，与会的专家学者认为中国经济能走到现在并取得了巨大发展，在一定程度上是与中国企业的发展息息相关。在企业理论与实践的研究中，如果能解决一个实际问题就是对中国企业发展的贡献。企业是创造财富的主体，是生产力发展的主体，是社会组织的细胞。企业稳定发展关系到社会和谐发展，关系到千万家庭生活状况，是连接社会和家庭的纽带。关于企业理论与实践的研究，既需要遵循我国企业成长和发展的历史沿革和现实情况，又需要借鉴市场经济发达国家企业成长和发展的规律，并实现二者的有机结合。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 进入新世纪以来，中国的经济环境已经发生了深刻变化，无论是国有企业，还是民营企业，都面临着更多的机遇和挑战。在低碳经济时代，发展环境友好企业和企业在&ldquo;三农&rdquo;问题解决中的重要角色等一系列问题，都为中国企业理论和实践研究提供了更多的素材和主题。特别是随着技术信息化和经济全球化的发展，企业理论与实践的研究是一个永无止境的课题，值得我们在今后的研究中继续深入下去。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓荣霖教授在座谈会上将50年历程浓缩成四个&ldquo;感谢&rdquo;：感谢时代，时代给我提供了企业实践的机会和条件；感谢人大，人大为我提供一个理论的基础和条件；感谢同事，包括我的领导，使我在教学研究当中能够做到教研结合，教学相长；感谢家人，让我们能够安心写每一篇文章。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓荣霖教授说，今天的座谈会是一个学术平台，来自方方面面的领导、专家、学者和企业家对当前中国的企业理论或实践，中国企业未来如何发展都表达了真知灼见，精辟的分析，作为一个有50年从教经历的教授而言，他本人只是起了&ldquo;引子&rdquo;的作用，就是把企业理论与实践引出来，让大家思考，所以只起一个探路的作用。知识是无穷尽的，理论在发展，实践在发展，所以他希望自己&ldquo;热爱人生，珍惜时间、追求知识、永无止境&rdquo;。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓荣霖1937年生于福建长乐，1961年毕业于中国人民大学工业经济系，并留校任教。1979年，作为国家公派访问学者赴南斯拉夫大学进修。1982年，回国开创现代企业和公司理论与实践研究的新领域。他率先开设《公司概论》课程，并在国家经济工作部门和经济体制改革部门参与有关企业转制的公司制度研究活动，发表了大量论著及论文。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邓教授在我国经济体制改革领域十分活跃，近年来，他参与了全国国有企业产权制度改革和产权交易问题的专题研究，研究成果已作为国家现代企业制度改革文件的重要依据。此外，还参加了原国家体改委组织的全国控股公司方案的研究，并多次直接向国务院领导汇报研究成果。&nbsp;<br />
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学学校办公室、党委宣传部、校友工作办公室、商学院等相关机构负责人以及企业管理系全体教师，邓荣霖教授指导的研究生出席座谈会。人民日报、新华社、光明日报、经济日报、中国教育报、中国新闻社、第一财经日报、新京报、财经杂志、中国教育电视台等新闻媒体进行了报道。</p>
<p>　　媒体链接<a href="http://www.bj.xinhuanet.com/bjpd_sdzx/2011-01/08/content_21816225.htm">：[新华社]<font face="新宋体">著名经济学家邓荣霖教授迎来从教50周年</font></a></p>
<p>　　　　　　<a href="http://www.chinanews.com/cul/2011/01-08/2774687.shtml">　[中国新闻网]中国公司研究第一人邓荣霖从教50年 &lt;企业论&gt;面世 </a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://edu.people.com.cn/GB/13685780.html"> [人民网]&nbsp;著名经济学家邓荣霖迎来从教50周年</a> <br />
</p>
<p>（编辑&nbsp; 燕燕 王开）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2lykhhf-zfhhbf_lit.jpg{/dede:field}
