{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}世界著名经济学家青木昌彦教授访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-02-05 06:58:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月2日，世界著名经济学家、斯坦福大学经济学系青木昌彦教授（Masahiko Aoki）访问经济学院。经济学院院长杨瑞龙教授会见了青木昌彦教授一行，双方就经济学教学与研究、高层次人才培养以及国际学术前沿等问题进行了广泛而深入的讨论。青木昌彦教授高度评价了经济学院在学科建设、国际性提升等方面所取得的成绩。杨瑞龙院长盛情邀请青木昌彦教授今年下半年到人民大学出席学术会议，他愉快地接受了邀请，并表示愿意为人民大学的人才培养和国际性提升作出自己的贡献。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhkhbfkbhf-zzfbf.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经济学院院长助理郑新业副教授，李军林教授、陶然教授、程华副教授、杨其静副教授等参加了会见。 <br />
<br />
青木昌彦教授简介 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 青木昌彦教授1938年出生于日本名古屋市，1962年东京大学经济系毕业，1967年获明尼苏达大学经济学博士，后陆续担任哈佛大学副教授、日本京都大学教授、斯坦福大学经济系教授，1997年至2001年任日本通商产业研究所所长，2001年4月至2005年任日本经济产业研究所所长。现为美国斯坦福大学名誉教授及日本一桥大学大学院客座教授，东京财团特聘首席研究员。青木昌彦教授是著名的&ldquo;内部人控制&rdquo;理论的提出者，又是长年活跃在国际学术舞台的比较制度理论大师；他深入思考制度转型理论，又用日本、前苏联等国家的制度变迁，来预测和指导中国的制度演进；他是备受尊重的日本经济学家，1990年获日本学士院奖及美国大学出版社协会有泽广巳纪念奖，1993年任瑞典皇家工程科学院外籍院士，1998年获国际熊彼得学会熊彼得奖，2005年，当选国际经济学会(IEA)会长。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 青木昌彦教授的主要著作有：《组织与计划的经济理论》，岩波书店，1971年；《现代企业》，岩波书店，1984年；《企业合作博弈理沦》，牛津大学出版社，1984年；《日本的经济制度分析&mdash;&mdash;信息激励淡判》，剑桥大学出版社，1988年；《经济制度的发展与多元性》，东洋经济新报社，1995年；《比较制度分析》(中译本)，上海远东出版社，2001年；《变迁的十年，不变的视点》，日经商务人文库，2002年。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkhbfkbhf-zzfbf_lit.jpg{/dede:field}
