{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}程天权书记视察图书馆新馆工程{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}校园建设管理处{/dede:field}
{dede:field name='pubdate'}2010-12-22 10:05:29{/dede:field}
{dede:field name='body'}<p>　　12月21日下午，程天权书记视察即将落成的图书馆新馆工程。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2mlbnhfyf-kzyfm.jpg" alt="" /></p>
<p>　　程天权书记逐层查看了图书馆新馆各个区域，详细听取了校园建设管理处、施工单位的工作汇报。视察过程中程天权书记要求在工程建设的最后阶段再接再厉、科学安排，在确保精品的基础上如期交付使用。</p>
<p>　　书记事务助理兼学校办公室副主任李家福、校园建设管理处相关负责人陪同视察。 </p>
<p>　　(编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mlbnhfyf-kzyfm_lit.jpg{/dede:field}
