<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","程天权书记视察图书馆新馆工程",89,155);
$z[2][4]['name']="title";
$z[3]=Array("field","",157,196);
$z[3][4]['name']="writer";
$z[4]=Array("field","校园建设管理处",198,251);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-22 10:05:29",253,312);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　12月21日下午，程天权书记视察即将落成的图书馆新馆工程。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110113/z2mhnn2mlbnhfyf-kzyfm.jpg\" alt=\"\" /></p>\r\n<p>　　程天权书记逐层查看了图书馆新馆各个区域，详细听取了校园建设管理处、施工单位的工作汇报。视察过程中程天权书记要求在工程建设的最后阶段再接再厉、科学安排，在确保精品的基础上如期交付使用。</p>\r\n<p>　　书记事务助理兼学校办公室副主任李家福、校园建设管理处相关负责人陪同视察。 </p>\r\n<p>　　(编辑：王开)</p>",314,816);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110113/z2mhnn2mlbnhfyf-kzyfm_lit.jpg",818,910);
$z[7][4]['name']="litpic";

?>