{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}著名国画家霍春阳教授画展在艺术学院隆重开幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-09-15 03:08:22{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月11日，艺术学院在公共教学一楼1301展厅举办天津美院著名国画家霍春阳教授画展。中国人民大学党委副书记马俊杰教授、艺术学院常务副院长徐唯辛教授、中国人民大学徐悲鸿艺术研究院院长徐庆平教授、博物馆副馆长潘平教授为画展开幕剪彩。&nbsp;</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式上，徐悲鸿艺术研究院院长徐庆平教授发表了热情洋溢的讲话。霍春阳教授向中国人民大学博物馆捐赠了一幅国画作品，学校党委副书记马俊杰教授向画家颁发了人民大学博物馆收藏证书。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艺术学院部分师生参加了展览开幕式。&nbsp;</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 附：霍春阳教授简历及画展部分作品</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 霍春阳，现任天津美术学院教授、硕士生导师，天津美术学院美术馆馆长，中国美术家协会会员，中国书法家协会会员，天津美术家协会副主席，天津画院院外画师，天津青年美协顾问，《人民日报》神州书画院特聘画家，新华社新华书画院特聘画家，中央电视台书画院特聘画家，硕士研究生导师。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhmffnmyf-yzzyf.jpg" /><br />
《雨后牡丹春睡浓》</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhmfynhmf-khm2l.jpg" /><br />
《春风贺喜无言语》</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhmfklmzf-nkykn.jpg" /><br />
《独当春日》</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhmfknymf-myylm.jpg" /><br />
《满眼春风最多恨 无言似笑小桃花》</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：杨阳 陈汉南) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhmffnmyf-yzzyf_lit.jpg{/dede:field}
