{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}沈仲平律师做客“名律师讲坛” 讲解香港打击黑社会犯罪刑事政策{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/法学院 颜卉{/dede:field}
{dede:field name='pubdate'}2010-04-06 10:06:27{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月31日下午，新一期&ldquo;名律师讲坛&rdquo;在明德法学楼国际学术报告厅举行。本期嘉宾是香港律政司副首席检察官，英国、香港高等法院及澳大利亚邦联法院大律师，澳洲首府堪培拉最高法院大律师沈仲平先生为法学院师生做了题为《香港打击黑社会犯罪刑事政策》的学术报告。法学院院长韩大元教授、副院长胡锦光教授出席并向沈仲平律师赠送纪念品，法学院副院长刘明祥教授主持了本期&ldquo;名律师讲坛&rdquo;。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座开始前，刘明祥副院长首先简要介绍了沈仲平律师的法律职业历程。韩大元院长致辞欢迎沈仲平律师的到来，并表示希望今后继续加强我院和香港法律界的学术交流。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylkhbblhf-lylzh.jpg" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座中，沈仲平律师首先回顾了回归前后香港法律的发展走向。沈律师从香港黑社会犯罪组织的起源谈起，描述了香港黑社会犯罪组织在香港的发展情况与当前存在状况。沈律师将黑社会犯罪组织存在的原因总结为主要受经济利益的驱动，在打击黑社会犯罪组织中往往面临犯罪所得合法化与权力部门保护伞等问题。因此在打击黑社会犯罪组织中要着力协调好打击黑社会犯罪组织与反洗钱犯罪、反腐败之间的关系。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 其后沈律师讲到了当前香港地区黑社会犯罪组织的转型，他表示当前黑社会犯罪组织的一个倾向是将进行贩卖人口等犯罪受益用于合法的投资（诸如影视、餐饮、股市、成立公司等），从而掩盖其犯罪所得性质。香港地区一直重视打击黑社会组织犯罪，但在如何保证线人、污点证人的安全方面相关刑事政策也存在着不足之处。讲座中，沈律师广博的知识、风趣的谈吐，赢得了同学们的阵阵掌声。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后的现场提问环节中，参会同学就讲座内容与目前的学术、社会热点问题与沈仲平律师展开了良好的互动，讲座在一片掌声中落下帷幕。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylkhbblhf-lylzh_lit.jpg{/dede:field}
