{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学召开计算机学科规划论证会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}信息学院{/dede:field}
{dede:field name='pubdate'}2011-01-10 02:41:01{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月7日下午，中国人民大学计算机学科规划论证会在明德主楼第一会议室召开。来自兄弟单位的专家学者们与人民大学专家学者一道，就人民大学计算机学科规划等问题进行了认真的论证和深入的研讨。纪宝成校长出席会议并做重要讲话。会议由袁卫常务副校长主持。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m2mzlbyf-yyymm.jpg" width="531" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 论证专家组由中科院数学所陆汝钤院士、中科院软件所林惠民院士、全国政协委员、教育部原副部长，&ldquo;虚拟现实技术与系统国家重点实验室&rdquo;主任赵沁平教授、北京大学校长助理李晓明教授、武汉大学计算机科学学院院长何炎祥教授、新加坡国立大学计算机科学学院院长黄铭均教授组成。&nbsp; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长重申了人民大学理工科建设&ldquo;有基础、相关联、高起点、入主流，力争高水平&rdquo;的建设思路，指出要建设高水平的理工科，保持体量，突出特色，提升质量。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 袁卫常务副校长阐释论证会的目的，总结计算机科学与技术学科建设10年的成果，并对计算机学科未来10年的建设进行规划。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 信息学院院长杜小勇教授介绍了计算机学科近年建设的基本情况以及未来建设的规划。与会专家针对计算机科学与技术学科的现状和未来规划，提出了相关的建议和意见。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大家认为：一、规划的指导思想很好，规划的计算机学科书涉及的各方向都值得发展，但应当不局限于这些方向；应当继续保持住&ldquo;数据库&rdquo;这个优势方向，但优势方向只有&ldquo;数据库&rdquo;一个太少，应有几个优势方向；发展其他方向时，最好能从&ldquo;数据库&rdquo;延伸方向发展，能结合人大的人文社会科学的优势，实现跨学科的融合。二、目前计算机学科的体量太小，队伍规模太小，而最终建设成果和学科排名，不是看人均，而是看总量，因此，需要尽快扩大队伍的规模。三、学科建设归根结底，要靠人才，需要引进高端人才。人才引进应更为灵活，既可以以学科建设带动队伍建设，也可以以队伍建设带动学科建设。对于新的方向，应当搞好团队的引进。四、进一步发展仍需要学校继续加大投入。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研究生院、发展规划处、科研处、教务处、人事处、实验室建设与设备管理处、财务处、资产与后勤管理处等部处负责人以及&ldquo;千人计划&rdquo;入选者周晓方教授、计算机学科其他教授、副教授和相关工作人员参加会议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2mzlbyf-yyymm_lit.jpg{/dede:field}
