{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}世界著名环境经济学专家吴俊杰教授来人民大学讲学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-02-23 10:06:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 世界著名环境经济学专家、美国俄勒冈大学农业与资源经济系教授吴俊杰先生，应中国人民大学环境学院院长马中教授的邀请，于2月12日来到中国人民大学环境学院，开始为期半年的教学与科研工作。</p>
<p align="center"><img height="262" src="/uploads/allimg/c100622/z2kkzlnflh2lnlf-lkmnz.jpg" width="199" alt="" />&nbsp;　　</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 吴俊杰教授将在本学期用英文为具有经济学基础的人口、资源与环境经济学专业硕士开设两门课程：&ldquo;环境经济学与政策&rdquo;（Environmental Economics and Policy） 和 &ldquo;自然资源经济学与政策&rdquo;（Natural Resources Economics and Policy）。授课将于2月26日开始。 　　</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 吴俊杰教授的到来将进一步提高环境学院的专业教学和科研水平，加强环境经济领域的国际交流与合作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 吴俊杰教授是中国教育部与美国国务院共同合作的《中美富布赖特项目》2008年度推荐的20名美国专家之一，是国际环境经济学领域的权威，是国际知名的&ldquo;Emery N. Castle&rdquo;教授，他在环境与自然资源经济学与政策研究、农业环境政策研究等方面具有高深的造诣，担任《环境经济与管理（JEEM）》 (Journal of Environmental Economics and Management)和《土地经济学》（Land Economics）, 和《农业经济学刊》（Journal of Agricultural and Resource Economics）杂志编委，在国际学术界享有极高的声誉。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnflh2lnlf-lkmnz_lit.jpg{/dede:field}
