<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院郑超愚教授论文荣获《金融研究》第一届（2009年度）优秀论文奖一等奖",89,199);
$z[2][4]['name']="title";
$z[3]=Array("field","",201,240);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",242,289);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月13日，《金融研究》第一届优秀论文（2009年度）现场评审会在北京召开，会议评选了六篇获奖论文。其中，经济学院郑超愚教授的《滞后效应、多重均衡与反向软着陆：中国需求管理经验》（《金融研究》2009年第4期）荣获《金融研究》第一届（2009年度）优秀论文奖一等奖。</p>\r\n<p>&nbsp;</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c101124/z2mfbmzhzkkbbkf-ybmyh.jpg\" alt=\"\" /></p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",291,774);
$z[5][4]['name']="body";
$z[6]=Array("field","1288060571",776,826);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c101124/z2mfbmzhzkkbbkf-ybmyh_lit.jpg",828,920);
$z[7][4]['name']="litpic";

?>