{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院郑超愚教授论文荣获《金融研究》第一届（2009年度）优秀论文奖一等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月13日，《金融研究》第一届优秀论文（2009年度）现场评审会在北京召开，会议评选了六篇获奖论文。其中，经济学院郑超愚教授的《滞后效应、多重均衡与反向软着陆：中国需求管理经验》（《金融研究》2009年第4期）荣获《金融研究》第一届（2009年度）优秀论文奖一等奖。</p>
<p>&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbmzhzkkbbkf-ybmyh.jpg" alt="" /></p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='pubdate'}1288060571{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhzkkbbkf-ybmyh_lit.jpg{/dede:field}
