<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","金泽大学人间社会环境研究科科长井上英夫教授来访",89,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",216,267);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-29 09:14:11",269,328);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月24日，日本金泽大学人间社会环境研究科科长井上英夫教授访问人民大学公共管理学院，董克用院长、魏娜教授、娜拉老师、麦秋林老师和于砚文老师参加了会见。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在两院签署的合作协议的框架内，双方协商了学生交流的具体形式，未来公共管理学院有望选拔若干日语或英语能力突出的研究生赴该校留学进修，并能得到减免学费、生活费的待遇，公共管理学院也计划在未来接收对中国感兴趣的日本学生来院进修。此外，双方还计划通过互邀国际会议、互邀短期研究、合作开展课题等形式，继续开展并扩大两院教师交流。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月25日下午杨慧林副校长会见了井上英夫教授，对日本金泽大学提供给人民大学留学生的学习机会，以及学费、奖学金的支持表示感谢，并表示支持进一步增进两校的学术交流和教学合作。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 之后，井上英夫教授在公共管理学院做了关于&ldquo;日本医疗保障制度的现状和问题&rdquo;的讲座，学生们积极提问，共同探讨了两国医疗卫生的发展经验和教训。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;\r\n</p>",330,1414);
$z[6][4]['name']="body";
$z[7]=Array("field","",1416,1455);
$z[7][4]['name']="litpic";

?>