{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}英语年度大戏：演绎文学经典 唱响圣诞欢歌{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/杨依军 刘佳 图/段庭辉 呼显龙{/dede:field}
{dede:field name='pubdate'}2008-12-25 08:28:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 冬日的严寒挡不住文学戏剧爱好者火热的激情。12月23日晚，&ldquo;天有之夜&rdquo;中国人民大学2008英语年度大戏《福尔摩斯与绿宝石》《圣诞欢歌》在逸夫会堂成功上演。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 作为人民大学一年一度的英语戏剧盛宴，由外国语学院2006级英语系同学自导自演的本次年度大戏吸引了来自多个学院的400余名同学到场观看。外国语学院党委书记张卫平，优秀毕业生代表、天有教育集团总裁助理张皓以及英语系中外籍教师等也出席观看演出。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据吉奥夫&bull;班博尔作品改编而成的《福尔摩斯与绿宝石》描述了神探福尔摩斯的一次传奇办案经历。落魄的波平夫人委托福尔摩斯和华生寻找她走失的丈夫埃德加，随着调查的深入，福尔摩斯发现案情另有玄虚。在华生和莱斯特雷德探长的协助下，他终于解开了谜团。在福尔摩斯寻找答案的过程中，遇到了种种阻碍与意外，探案之路格外离奇曲折。性格迥异的人物与高潮迭起的剧情，表现了人性的善恶悲欢，讴歌了为实现正义而坚定不屈的信念。</p>
<p align="center"><img height="332" alt="" width="500" src="/uploads/allimg/c100621/z2kkzlbnklbhbzf-2lblz.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据狄更斯作品改编而成的《圣诞欢歌》则讲述了一个吝啬鬼在平安夜遇见三个幽灵并因此而改变自我的故事。斯柯鲁奇是一家商号的老板，贪婪冷酷而自私。他总认为圣诞节不过是人们从他口袋里&ldquo;抢&rdquo;钱的借口。三个幽灵在平安夜领着他跑遍全城，让他感受到了穷人的善良，目睹了冷酷自私者的下场。他终于醒悟，在圣诞节给办事人员加薪，并乞求上帝祝福每一个人，从而实现了皆大欢喜的局面。半个小时的话剧告诉人们一个道理：欢乐只有分享才能长久，爱只有付出才能真实。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100621/z2kkzlbnkhlhbhf-lylhh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 同学们惟妙惟肖的表演、诙谐幽默的语言、流利地到的语音，不时赢得观众们的阵阵掌声。社会与人口学院大四学生冯启娜说，&ldquo;英语系的同学们有这样的机会很让人羡慕，我也想在毕业时组织同学搞一个类似的活动了。&rdquo;国学院大三的张珂表示，中外文化有许多差异，但有关真、善、美的很多思想精华都是相通的。&ldquo;观看英文戏剧，可以了解一些英美文化，进一步开阔视野，对中国传统文化的研究学习也有一定帮助。&rdquo; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演出结束后，英语系的同学们向外籍教师李大燕、钱伯斯、黛莉等赠送了精心准备的礼物。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大戏导演杨思佳介绍说，作为专业课《英美戏剧欣赏》的期末汇报演出，英语大戏是外国语学院英语系从1994年起每年坚持的传统。经过十多年的努力，这一活动业已成为活跃人民大学校园文化氛围的一个亮点。2008年上半年以前，由于课程安排在第二学期，演出每年6月以毕业大戏的形式举行。今年的活动中，2006级英语专业的50多名同学都参与到了前期排练与其它准备工作当中，密切配合，团结共事，在学习专业课程的同时，锻炼了合作与沟通的能力，增强了集体荣誉感。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：冷严军） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbnklbhbzf-2lblz_lit.jpg{/dede:field}
