{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学召开党风廉政建设责任制检查工作暨全面推进廉政风险防范管理工作启动会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}纪检办公室{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月31日上午，中国人民大学召开党风廉政建设责任制检查工作暨全面推进廉政风险防范管理工作启动会，校党委书记程天权出席会议并讲话。会议由校党委常务副书记、纪委书记牛维麟主持，副校长林岗、校党委副书记兼副校长王利明及校党风廉政建设工作领导小组其他成员、相关单位负责人共39人参加会议。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mnk22klf-lyzyk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年12月2日，学校党委印发《关于开展党风廉政建设责任制检查工作的通知》，对各单位2010年度党风廉政建设责任制落实情况进行检查。按照通知要求，各有关单位认真进行了自查。此次会议上，产业管理处、经济学院、信息资源管理学院、体育部、校医院等5个单位负责人进行了专题汇报。在此基础上，校纪委副书记、监察处处长马周年对学校党风廉政建设责任制工作总体情况进行了总结，并就人民大学全面推进廉政风险防范管理工作的有关要求进行了部署。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，校党委书记程天权、学校党委常务副书记兼纪委书记牛维麟分别发表讲话。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mnkykfmf-hyfky.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛维麟常务副书记指出，落实党风廉政建设责任制，对于建立教育、制度、监督并重的惩治和预防腐败体系，落实反腐倡廉各项工作具有重大意义。从5个单位的汇报来看，各单位均能按照&ldquo;谁主管，谁负责&rdquo;的原则，认真抓好党风廉政建设责任制工作。希望大家在今后的工作中，继续高度重视党风廉政建设，切实履行&ldquo;一岗双责&rdquo;的要求，全面推进本单位、本部门反腐倡廉各项工作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛维麟常务副书记强调，廉政风险防范管理工作关键是找准风险点，正确评估风险等级，并制定出与之相适应的防范措施，其根本目的在于建立惩治和预防腐败的长效机制。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mnkkzbzf-bzknk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记在讲话中指出，党中央历来非常重视党风廉政建设责任制工作，学校按照中央精神和上级部署，做了很多扎实的工作，保障了各项事业的平稳健康发展。按照上级部署，学校已经完成了廉政风险防范管理试点和深入推进工作，今天又举行了全面推进工作的启动仪式，将所有部门都涵盖进这项工作中来。希望全校领导干部继续加强认识，对腐败保持高度警惕，以党风廉政建设责任制和廉政风险防范管理工作为抓手，使本单位党风廉政建设工作上一个新台阶。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1293744965{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mnk22klf-lyzyk_lit.jpg{/dede:field}
