{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院《中国宏观经济分析与预测》被确立为2009年度国家社会科学基金决策咨询项目{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-01-25 02:50:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，经济学院举办的&ldquo;中国宏观经济论坛&rdquo;的研究成果《中国宏观经济分析与预测》经全国哲学社会科学规划领导小组批准，被确立为2009年度国家社会科学基金决策咨询项目。教育部对该成果也十分重视，要求将研究成果同时上报给教育部社科司。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
