<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","刘俊海教授应邀出席“2011中国私募基金年会”",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",212,257);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-03 02:41:13",259,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月25日，由中央电视台财经频道与国金证券联合主办的&ldquo;2011中国私募基金年会&rdquo;在北京举行，本届年会主题是&ldquo;千亿时代私募基金的规范与创新&rdquo;。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自政府部门、金融机构、银行界人士、私募基金和研究机构的知名代表共聚一堂，围绕主题，就如何在政府监管、行业自律和社会监督三个层面加强私募基金规范发展、私募基金行业如何通过自身的不断变革度过&ldquo;瓶颈期&rdquo;并寻求新的突破及私募基金在未来中国资本市场中的地位和影响等方面进行了深入研讨。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学商法学院所长刘俊海教授出席了本次论坛，并以《证券投资基金法的修改对私募证券基金的影响》为题做了精彩发言。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href=\"http://finance.sina.com.cn/money/fund/20110225/11329433278.shtml\">刘俊海：私募基金应适当监管 鼓励自治</a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）</p>",320,1310);
$z[6][4]['name']="body";
$z[7]=Array("field","",1312,1351);
$z[7][4]['name']="litpic";

?>