{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院孙国华教授一行应邀参加俄罗斯联邦立法与比较法研究所85周年院庆系列活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-09 02:38:15{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月26至31日，应俄罗斯联邦政府下属立法与比较法研究所邀请，中国人民大学法学院孙国华教授参加了以&ldquo;法律科学：历史与现代性&rdquo;为主题的第五届国际青年法学家大会暨庆祝俄罗斯联邦立法与比较法研究所建立85周年&rdquo;系列学术活动。中国社科院法学所张少瑜研究员、中国青年政治学院法律系王莉君副教授、北方交通大学法学院陈力铭副教授以及正在俄罗斯访问研究的中央民族大学法学院张俊杰教授也应邀参加了活动&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 俄罗斯科学与教育部部长、最高法院院长及多位俄罗斯联邦科学院院士出席会议，来自俄罗斯联邦、独联体各国、东欧国家以及中国的600余位法律学者参加了此次会议。大会主题发言题目包括：《构想在立法与法律发展中的作用》（俄罗斯总统资政）、《人权：看待问题的新视角》（哈萨克立法研究所所长）、《比较法的乌克兰主张》（乌克兰比较法研究协会学术秘书）、《中国当代立法的发展》（中央民族大学法学院张俊杰教授）以及《法的问题和俄罗斯文化中的人道》（俄罗斯联邦科学院哲学所所长）等。会议第二天，大会组织者安排了公法、法的理论与历史、国际法、比较法等分论坛，继续研讨&ldquo;法学遗产与现代性&rdquo;问题。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 孙国华教授向俄罗斯联邦立法与比较法研究所长赠送了《孙国华自选集》和人大法学院简介，并就俄罗斯如何评价和继承苏维埃法学、法律的概念与法律的客观性等问题同俄方法学专家进行讨论。会议间隙，孙国华教授还专程去医院看望了上世纪50年代在人大法学院任教的老师、苏联专家古道师尼科夫教授，代表人大法学院表示慰问，并祝他早日康复。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
