{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学法学院法律硕士获批教育部专业学位研究生教育综合改革试点{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-01-12 10:33:08{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部近日下发了《教育部关于批准有关高等学校开展专业学位研究生教育综合改革试点工作的通知》，中国人民大学法学院法律硕士顺利获批教育部专业学位研究生教育综合改革试点。根据该文件精神，这次我国的综合改革试点工作，主要任务包括改革专业学位研究生选拔制度；试点高校将在国家统一的招生制度框架下，积极探索有利于吸引具有较大培养潜力的优秀生源的考试办法，完善专业学位研究生培养方案。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 目前，法学院法律硕士工作委员会专门就改革试点举行研讨会，确立了八大任务：一、确立先进、科学和国际化的办学思路和教育理念；二、构建&ldquo;责任、意识、素养、技能&rdquo;四位一体的人才培养目标体系；三、生源质量保证；四、培养模式创新；五、师资队伍建设；六、实习实践基地建设；七、奖助贷体系和就业服务体系；八、管理体制创新。当前我院已启动职务犯罪侦查、国际商事人才、多元纠纷解决、律师实务等方向的法律硕士培养工作。积极探索法律硕士知识产权方向人才、区域性法律高层次人才等培养模式。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，此次法律硕士专业学位研究生教育综合改革试点工作对于推动教育科学发展，鼓励高校积极探索和创新符合专业学位教育特点、具有鲜明特色的法律硕士研究生专业学位教育培养模式和管理体制，加快培养经济社会发展急需的高层次应用型人才有着重要意义。根据教育部通知，全国共有19所高校获批法律硕士改革试点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
