{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}程天权书记出席中国人民大学“北京室内乐团”音乐会 2011年7月3日下午，中国人民大学艺术学院音乐系“北京室内乐团”在北京音乐厅举行室内乐专场音乐会。中国人民大学党委书记程天权、部分部处、兄弟院校领导、业内专家及艺术学院领导徐庆平、郑晓华、{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
