<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","程天权书记出席中国人民大学“北京室内乐团”音乐会 2011年7月3日下午，中国人民大学艺术学院音乐系“北京室内乐团”在北京音乐厅举行室内乐专场音乐会。中国人民大学党委书记程天权、部分部处、兄弟院校领导、业内专家及艺术学院领导徐庆平、郑晓华、",43,320);
$z[1][4]['name']="description";
$z[2]=Array("field","",322,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","",444,481);
$z[5][4]['name']="body";
$z[6]=Array("field","",483,523);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",525,564);
$z[7][4]['name']="litpic";

?>