<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","新西兰怀卡托大学名誉校长吉姆．博尔杰率团访问人民大学",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","国际交流处",222,271);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>　　11月3日，新西兰怀卡托大学(University of Waikato)名誉校长 （Chancellor）吉姆．博尔杰（Jim Bolger）率代表团访问中国人民大学。代表团成员有该校校长 (Vice-Chancellor)罗伊．克劳福德教授、副校长艾德．威姆斯教授以及学校其他部门负责人等11人。杨慧林副校长会见了代表团一行。 </p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c101126/z2mfkyfhyklzzmf-zmkhk.jpg\" /></p>\r\n<p>　　会谈中，双方回顾了两校的交流历史，相互介绍了学校最近的发展情况和国际化方面的举措及成就，并就进一步加强交流、开展更多如学生交换以及联合研究等实质性合作达成一致。 </p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c101126/z2mfkyfhykmbkhf-2hnyy.jpg\" /></p>\r\n<p>　　会谈后，杨慧林副校长与克劳福德校长共同签署了《中国人民大学与怀卡托大学谅解备忘录》以及《中国人民大学和怀卡托大学学生交换协议》。人民大学与怀卡托大学于2004年首次签署合作备忘录，此次签署的谅解备忘录是以过去几年合作实践为基础，对原有协议的接续和更新。同时签署的学生交换协议是将备忘录所及合作的具体化，为人民大学学生参与国际交流提供了又一新的途径。 </p>\r\n<p>　　学校国际交流处处长唐忠等相关人员参加了会谈和签约仪式。 </p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c101126/z2mfkyfhynzhylf-llh2m.jpg\" /></p>\r\n<p>　　（编辑：贾晓旭）</p>",273,1496);
$z[5][4]['name']="body";
$z[6]=Array("field","1289266426",1498,1548);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c101126/z2mfkyfhyklzzmf-zmkhk_lit.jpg",1550,1642);
$z[7][4]['name']="litpic";

?>