{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国驻华使馆新闻发言人史雯珊来新闻学院讲学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-06-03 04:24:25{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月1日，应中国人民大学新闻学院邀请，美国驻华使馆新闻发言人史雯珊(Susan N. Stevenson )女士在新闻学院思科演播室做了题为&ldquo;美国的公共外交&rdquo;的精彩演讲。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 史雯珊女士详细地阐述了她对&ldquo;公共外交&rdquo;的理解，列举了很多中美外交史上经典的公共外交案例。人民大学以及清华大学、北京外国语大学、中国传媒大学等多所高校的同学听取了演讲，并积极回应，围绕国内外的热点话题纷纷提问，史雯珊女士都一一解答。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随同史雯珊女士来院的还有美国驻华大使馆副新闻发言人Robert A. Rains和公共事务专家王蓓女士。新闻学院常务副院长倪宁教授会见了史雯珊女士一行，并高度赞赏史雯珊女士为双方合作所作的努力和贡献。钟新教授等也参加了会见。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
