{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国务院食品安全委员会办公室主任张勇校友致函母校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-03-05 12:05:43{/dede:field}
{dede:field name='body'}<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，纪宝成校长和经济学院都致函给人民大学校友张勇，祝贺他出任国务院食品安全委员会办公室主任，并邀请他在适当的时候回母校看看。3月3日，张勇校友给经济学院发来了热情洋溢、饱含深情的回信，他在写回信中感谢母校的培养，回顾了深切的师生之情，为母校几年来的飞速发展深感骄傲与自豪，并祝愿母校、母院取得更大的辉煌。 <br />
<br />
附：张勇校友来信全文 <br />
尊敬的杨瑞龙院长： <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月24日来信敬悉。衷心感谢母校和母院对我的关心。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 您的亲切问候，又一次唤起我对人民大学学习生活的美好回忆。四年学子生涯，校风之熏陶、师长之关爱、同窗之襄助，点滴真情，历历如昨。四年学子生涯，品行之培养、知识之积淀、恩师之教诲，源头活水，终生受益。&ldquo;立学为民、治学报国&rdquo;的人大精神，始终激励着我朝乾夕惕、勤奋工作。此后我在工作上的每一份成绩，在事业上的每一点进步，都是与母校的培养密不可分的。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 岁月如梭，光阴飞逝，不觉离校已近卅载。这些年，我一直关注着母校和母院的发展进步。学校、院系日新月异的变化，令我由衷地感到自豪；当年的恩师虽年事已高，仍潜心育人、勤耕不辍，令人敬佩；如今同窗们已崭露头角、事业有成，使我更加难忘恩师之隆。尤为有幸的是，去年10月，借母校组织&ldquo;1979级校友入校三十周年纪念会&rdquo;之机，我与诸位同窗重返母院，重温师生浓浓情谊，如沐春风；直观母院不断发展，不胜欣喜。当前，母院始终保持政治经济学的传统优势，各类经济学科齐头并进，发展前景十分广阔。我衷心祝愿母院在开放化、国际化的理念指引下，努力打造我国一流大学的一流学科，在促进学术繁荣、培养优秀人才、建言我国经济改革与发展等方面发挥更大的作用。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 再次感谢您的关心，顺祝胡乃武老师及各位恩师身体健康、母院同学们学业有成！ <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 敬颂 <br />
台安！&nbsp;<br />
<br />
七九级计划专业学生&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张勇&nbsp;<br />
二○一○年三月三日&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 于北京 <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
