{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院孙久文教授课题成果入选国家发改委《“十二五”规划战略研究》{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-22 03:04:11{/dede:field}
{dede:field name='body'}<p>　　日前，由国家发改委主任张平担任主编的《&ldquo;十二五&rdquo;规划战略研究》由人民出版社出版。经济学院区域与城市经济研究所孙久文教授的课题组承担了&ldquo;我国优化生产力布局战略研究&rdquo;重大课题，该课题研究成果入选《&ldquo;十二五&rdquo;规划战略研究》一书。 <br />
　　从2008年开始，国家发改委组织各方面的力量，开展了&ldquo;十二五&rdquo;规划重大课题研究工作。通过深入研究，形成了70多篇、500多万字的研究报告，这些成果对&ldquo;十二五&rdquo;规划的编制具有重要的参考作用。本书是从这些报告精选而成的。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
