{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}台湾政治大学国际关系研究中心代表团访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}港澳台办公室{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月24日下午，中国人民大学杨慧林副校长会见了台湾政治大学国际关系研究中心杨昊一行。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与会双方就两校共同合作研究推广孔子学院进行了探讨，杨慧林副校长系统地介绍了人民大学在海外合作开办孔子学院的情况，对办学战略规划、授课群体研究，以及对孔子学院作为一个文化传播载体的正确诠释和前瞻思考做了精辟的分析。双方都有意愿在孔子学院多学科研究的共同领域加强合作。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈结束后，来访的政治大学代表团访问了中国人民大学汉语国际推广研究所和文学院。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参加会见的还有汉语国际推广研究所、文学院和港澳台办公室相关负责人。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='pubdate'}1290633403{/dede:field}
{dede:field name='litpic'}{/dede:field}
