{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院特色社团在社团集体招新当天受到广泛关注{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院团学新闻信息中心{/dede:field}
{dede:field name='pubdate'}2008-09-24 10:50:06{/dede:field}
{dede:field name='body'}<p>　　9月24日，人民大学学生社团在公共教学二楼前草坪举行了联合招新。尽管下着小雨，外国语学院的Active活力英语社、樱花社、香榭丽社和第三罗马四大品牌社团前仍然人头攒动，前来咨询和报名的同学络绎不绝。&nbsp;&nbsp;</p>
<p align="center"><img height="375" alt="" width="500" src="/uploads/allimg/c100621/z2kkzlbynlnnzbf-2bhkk.jpg" /><br />
　　（老牌十佳社团、北京市优秀社团樱花社吸引了众多对日本文化感兴趣的同学） </p>
<p align="left"><br />
　　樱花社是享誉人大的老牌知名社团，曾获得&ldquo;北京市优秀社团&rdquo;、&ldquo;人大十佳社团&rdquo;等殊荣。据社团负责人，来自2006级日语系的常夷介绍，樱花社本学期除了日语学习班和日本影音放映等已有活动之外，还将推出中日交流论坛、日语风采大赛等中日文化交流活动。 </p>
<p>　　Active活力英语社一直致力于在人大开展寓教于乐的英语活动，曾举办过新东方创始人俞敏洪讲座、美国大使馆留学讲座、2007外语文化节、地铁英语系列教学等活动。据了解，Active活力英语社本学期还将继续掀起人大新一轮的英语&ldquo;听说风暴&rdquo;，&ldquo;我们的宗旨是&lsquo;用英语将年轻的心紧紧相连&rsquo;。&rdquo;，Active负责人，来自2007级英语专业的王菁表示。 <br />
</p>
<p align="center"><img height="375" alt="" width="500" src="/uploads/allimg/c100621/z2kkzlbynhhylhf-llhfh.jpg" /></p>
<p align="center">　　（法语社团香榭丽社展台前人潮涌动）<br />
</p>
<p align="left">　　香榭丽社浓郁的法兰西风情、第三罗马对俄罗斯文化包罗万象的推介都使得人大学子们纷纷趋之若鹜。来自法国的外教Zoulime先生也来到了香榭丽社招新现场助阵。Zoulime表示，香榭丽社为人大学子了解法国文化提供了良好的平台，希望能有更多同学关注法语和法国。 <br />
</p>
<p align="center"><img height="375" alt="" width="500" src="/uploads/allimg/c100621/z2kkzlbynhknmyf-hnkff.jpg" /></p>
<p align="center">　　（俄语专业的第三罗马社团在招新现场）</p>
<p align="left"><br />
　　外国语学院同学除办好已有的外语特色学生社团外，还积极参与创办了满族文化交流协会、百度人大等学生社团，丰富了人大学子的校园文化生活。 </p>
<p align="left">　　在此次全校社团的联合招新中，外国学院学生社团凭借独具特色的异域文化风情、形式多样的外语培训和交流活动，受到了同学们的广泛关注和好评。 </p>
<p>　　（编辑：彭大伟）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbynlnnzbf-2bhkk_lit.jpg{/dede:field}
