{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}统计学院教师代表团赴韩参加“延世大学-中国人民大学统计联合研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-10-16 06:13:55{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp;&nbsp; 应韩国延世大学经济与商学学院应用统计系Byung Soo Kim教授的邀请,10月13-14日,统计学院教师吴喜之、黄向阳、蒋妍、肖宇谷、金阳参加了在延世大学举行的一个为期两天的研讨会——“延世大学-中国人民大学统计联合研讨会”。研讨会期间,双方教师对相关学术问题进行了深入的讨论与交流。</P>
<P>&nbsp;</P>
<P>&nbsp;</P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
