<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","统计学院教师代表团赴韩参加“延世大学-中国人民大学统计联合研讨会”",89,192);
$z[2][4]['name']="title";
$z[3]=Array("field","",194,233);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",235,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-10-16 06:13:55",284,343);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P>&nbsp;&nbsp;&nbsp; 应韩国延世大学经济与商学学院应用统计系Byung Soo Kim教授的邀请,10月13-14日,统计学院教师吴喜之、黄向阳、蒋妍、肖宇谷、金阳参加了在延世大学举行的一个为期两天的研讨会——“延世大学-中国人民大学统计联合研讨会”。研讨会期间,双方教师对相关学术问题进行了深入的讨论与交流。</P>\r\n<P>&nbsp;</P>\r\n<P>&nbsp;</P>",345,702);
$z[6][4]['name']="body";
$z[7]=Array("field","",704,743);
$z[7][4]['name']="litpic";

?>