<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公共管理学院叶剑平教授受聘“中国城市科学研究会住房政策与市场调控研究专业委员会”副主任委员",89,217);
$z[2][4]['name']="title";
$z[3]=Array("field","",219,258);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",260,311);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-15 09:49:32",313,372);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月26日，中国人民大学公共管理学院土地管理系主任、土地政策与制度研究中心主任叶剑平教授出席了&ldquo;中国城市科学研究会住房政策与市场调控研究专业委员会&rdquo;的成立大会，并接受大会聘请出任副主任委员及常务委员。会上，住房保障与城乡建设部仇保兴副部长为叶剑平主任颁发了聘书。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n<br />\r\n</p>",374,794);
$z[6][4]['name']="body";
$z[7]=Array("field","",796,835);
$z[7][4]['name']="litpic";

?>