{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院叶剑平教授受聘“中国城市科学研究会住房政策与市场调控研究专业委员会”副主任委员{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-12-15 09:49:32{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月26日，中国人民大学公共管理学院土地管理系主任、土地政策与制度研究中心主任叶剑平教授出席了&ldquo;中国城市科学研究会住房政策与市场调控研究专业委员会&rdquo;的成立大会，并接受大会聘请出任副主任委员及常务委员。会上，住房保障与城乡建设部仇保兴副部长为叶剑平主任颁发了聘书。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
