{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大经济研究所发布的《中国宏观经济分析与预测报告（2009-2010）》英文版在海外出版发行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-18 05:43:58{/dede:field}
{dede:field name='body'}<p>　　近日，中国人民大学经济研究所发布的《中国宏观经济分析与预测（2009-2010）》英文版经中国人民大学出版社授权，由香港天窗专业出版公司（Enrich Professional Publishing）编辑出版，美国麦格劳&mdash;希尔公司（The McGraw-Hill Companies）面向全球发行。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzknybmbnf-llklm.jpg" alt="" /></p>
<p><br />
　　实现经济学研究成果在海外出版发行，对于践行国家哲学社会科学&ldquo;走出去&rdquo;战略，提升中国文化软实力，特别是建立中国学者在国际学术交流中的话语权，都是非常重要的手段和措施。这次，《中国宏观经济分析与预测（2009-2010）》英文版经过有关学术专家、翻译专家组成的专家组的严格的评审和筛选，入选了&ldquo;中国图书对外推广小组&rdquo;的走出去翻译资助，为该书的顺利出版提供了资金条件。 <br />
　　英文版报告的出版改变了以前中国学者自己翻译、在中国出版社出版的传统出版方式，而是采用和外国出版社合作的方式，严格按照国际出版的规则和惯例办事，采取了严格的步骤出版发行。经过了国际市场调查，中国译者翻译和外国母语润色，英国专业编辑编校根据国际市场规律定价、发行和宣传推广等多个环节，从而，使报告可以与外国读者无障碍沟通。英文版报告的主要读者群体为高校和学术研究机构和政府机构等，成为他们了解中国宏观经济的重要渠道之一。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzknybmbnf-llklm_lit.jpg{/dede:field}
