{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“李庄案虚拟审判与刑事审判制度改革”研讨会隆重举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-06 09:33:35{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月3日，&ldquo;李庄案虚拟审判与中国刑事审判制度改革&rdquo;研讨会在明德法学楼601国际学术报告厅隆重举行。本次会议由检察日报社正义网络传媒与中国人民大学法学院证据学研究所联合主办，来自全国各地的法官、检察官、法学教授、律师、媒体记者以及参与李庄案虚拟审判（&ldquo;山寨法庭&rdquo;）的网友参加了本次会议。此次研讨会由何家弘教授担任主持，中国政法大学诉讼法学研究院名誉院长樊崇义教授、北京理工大学法学院院长谢晖教授以及中国人民大学法学院陈卫东教授担任研讨会点评人。</p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzyhbhlfl2f-by2mk.jpg" alt="" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会上，中国人民大学法学院博士生、李庄案虚拟审判法警兼书记员杨建国首先对李庄案虚拟审判的概况向参会人员进行了介绍，进而提出了自己对陪审员选任制度改革的思考与见解。苏州工业园区人民检察院刑事检察科王勇副科长（李庄案虚拟审判首席检察官）就刑事庭审改革背景下的起诉书格式完善问题发表了自己的看法。随后，中国青少年犯罪研究会刘桂明副秘书长以及四川大学法学院张斌副教授分别对李庄案的警示意义和案件的文本问题进行了探讨，河南省高级人民法院刑二庭陈殿福庭长从实务的角度指出法官在刑事庭审中遇到的问题。最后，重庆大学法学院陈忠林院长围绕陪审团制度发言，并提出中国的陪审团应该由非法律专业人员组成等观点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 三位点评人都对李庄案的虚拟审判及本次研讨会上的发言给予了高度评价，就刑事审判制度改革中的程序和体制问题、中国陪审制度的发展、中国社会结构转型时期的矛盾提出了独到的观点，并鼓励法律界人士对司法制度改革贡献力量。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：徐晶晶）&nbsp;<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyhbhlfl2f-by2mk_lit.jpg{/dede:field}
