
   {dede:match}<tr><td width="90%" align="left" valign="top" style="PADDING-RIGHT: 20px; PADDING-LEFT: 20px;PADDING-BOTTOM: 20px;FONT-SIZE: 10.5pt; LINE-HEIGHT: 22px; TEXT-DECORATION: none">[ÄÚÈİ]</td>
	</tr>
<tr><td><img src="http://images.ruc.edu.cn/templates/{/dede:match}
   {dede:trim replace=""}£¨±à¼­£º(.*)£©<br />{/dede:trim}
{dede:trim replace=""}£¨±à¼­£ºĞÏÅô£©{/dede:trim}
{dede:trim replace=""}£¨±à¼­£ºº«ºê±ó£©{/dede:trim}
{dede:trim replace=""}£¨±à¼­ ÁõÄĞ£©{/dede:trim}
{dede:trim replace=""}£¨±à¼­£º³ÌÔ¶·¼£©{/dede:trim}
   {dede:function}{/dede:function}
