{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院邹骥教授做客人民网谈中国的低碳发展{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2010-07-22 10:54:47{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学环境学院副院长邹骥教授于7月16日做客人民网，就中国低碳发展的减排潜力与市场的调节手段等问题接受专访，并与网友在线交流。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邹骥教授首先指出，受一次性能源比重、能源强度、人均GDP增长与人口等四方因素影响，在保证中国未来的经济增长和改善人民生活水平的前提下，2030年以前中国很难达到温室气体绝对排放的峰值。邹骥教授指出，根据他所领导的团队的研究成果，中国的温室气体排放要到2050年左右才能保持平稳、不再增长。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邹骥教授接着强调了技术在发展低碳经济过程中的重要作用。邹骥教授介绍说，他所领导的中国人民大学能源与气候经济学项目（PECE）在对电力、交通、建筑、冶金、石油化工和水泥六大高碳排放部门进行研究后，识别了388种重点技术，其中又有63种关键技术，支撑中国未来的低碳发展。但是在这63种技术中有42种技术中国是不掌握核心技术的。在这些核心技术上受制于人，可能会成为未来中国发展低碳经济的瓶颈。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此外，邹骥教授还就发展低碳经济的成本、碳税和碳交易的实施前景、联合国气候变化谈判前景等热点问题与嘉宾和网友进行了交流。 <br />
据悉，邹骥教授领导的中国人民大学能源与气候经济学项目（PECE）受UNDP驻华代表处委托，撰写了《中国人类发展报告2009/10&mdash;&mdash;迈向低碳经济和社会的可持续未来》。报告回顾了中国温室气体排放的现状，分析了未来的低碳发展情景和关键技术的需求，并提出了中国发展低碳经济的技术路线图和政策路线图。报告不仅回答了&ldquo;什么是低碳经济&rdquo;、&ldquo;中国该怎样发展低碳经济&rdquo;等问题，也为邹骥教授在访谈中的观点提供了研究基础。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
