{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本九州大学代表团访问经济学院并举行硕士生交换项目宣讲会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月21日上午，日本九州大学经济学院院长川波洋一教授一行访问经济学院。经济学院院长杨瑞龙教授会见川波洋一院长一行。经济学院副院长刘瑞教授、赵国庆教授、院长助理郑新业副教授、杨其静副教授陪同会见。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自人民大学与九州大学硕士生联合培养项目合作协议签署以来，经济学院已向九州大学经济学院派出4名交换生。此联合培养项目的顺利开展，有利于提高学生的科研能力和学术水平。这一项目的建立和发展是学院落实学校全面提升国际性的具体成果。和日本九州大学的合作有助于学院国际性的提升，是创建世界一流的经济学院的有益助力。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhyylkh2f-hkzhb.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长首先对代表团的来访表示欢迎，并回顾了双发签署合作协议后取得的丰硕成果。随后，双方具体商谈了进一步深化合作的细节。杨瑞龙院长还向九州大学代表团介绍了学校提升国际性的新举措，并向客人详细介绍了学院新建立的中国经济全英文硕士项目。九州大学客人对这一新项目表现出浓厚兴趣，希望双方就此展开新的合作。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 同日下午，日本九州大学代表团在明德主楼经济学院617会议室举行硕士生交换项目宣讲会。经济学院副院长刘瑞教授主持宣讲会，教务科科长沈明霞参加会议。九州大学代表团就该校经济学院基本情况、人民大学-九州大学共同教育项目、全英语课程项目和硕士课程、博士课程等内容进行了宣讲。宣讲会吸引了大批学生参加，效果良好。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1261707208{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhyylkh2f-hkzhb_lit.jpg{/dede:field}
