{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙院长一行成功访美{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-01-21 05:15:19{/dede:field}
{dede:field name='body'}<p>　　2011年1月4日－10日，经济学院院长杨瑞龙教授，经济学院副院长、教育部国际商务硕士专业学位教学指导委员会委员刘元春教授，经济学院国际商务硕士专业学位项目主任程大为副教授等赴美国访问。 <br />
　　1月4日至6日，杨瑞龙院长一行访问了美国加州蒙特雷国际研究院，该院教务长Amy Sands博士、国际商务和政策学院院长施瑜玮教授等会见了经济学院代表团，双方就联合培养国际商务专业硕士等问题进行了深入而富有成效的工作讨论，并签署了合作协议。合作内容主要包括中美双方互派留学生、国际商务硕士项目的教学科研合作及教师互访等。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110217/z2mkmlhhlz2fkhf-znfkf.jpg" width="500" alt="" /></p>
<p><br />
　　2010年，教育部指定中国人民大学经济学院为我国第一批招收国际商务硕士的基地。为了将国际商务硕士项目在开办之初就建立在国际水平上，经济学院全方位积极推动该项目的国际合作。蒙特雷国际研究院是首批和国际商务硕士项目合作的国外院校之一。施瑜玮院长、助理院长Toni Thomas女士和Devin Lueddeke先生已于2010年两次来华访问了经济学院，举办了精彩的学生讲座，并和国际经济系的教师就国际商务硕士项目进行了工作经验交流和合作内容的商讨。 <br />
　　1月7日至10日，杨瑞龙院长一行前往丹佛市，参加了2011年留美经济学年会。会议期间，杨瑞龙院长会见了斯坦福大学经济学院洪瀚教授、范德比尔特大学经济系系主任李彤教授等知名学者，就当前世界和中国的经济形势、经济学发展前沿等问题进行了深入交流。1月7日至8日，杨瑞龙院长、刘元春副院长等专家对应聘人民大学经济学院的优秀海外人才进行了面试，应聘者都是在美国一流大学的博士学位获得者，学术潜力巨大，其中还有不少是欧美籍人士。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110217/z2mkmlhhlz2fkhf-znfkf_lit.jpg{/dede:field}
