{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哥斯达黎加大学新闻传播学院院长来访新闻学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院    文/周卷施{/dede:field}
{dede:field name='pubdate'}2011-03-15 03:26:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月8日上午，中国人民大学新闻学院常务副院长倪宁教授会见了来访的哥斯达黎加大学新闻传播学院院长Carolina Carazo。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 倪宁常务副院长对Carolina Carazo教授到访表示热烈欢迎，并向Carolina Carazo教授介绍了学院的基本情况，强调要积极建立两个学院之间的联系，全方位加强合作。倪宁教授还详细了解了Carolina Carazo教授本次来人大访学的情况，邀请她为新闻学院的老师和同学介绍哥斯达黎加的新闻传播业以及新闻传播学术研究的概况。倪宁教授还表示，将全力支持Carolina Carazo教授在人大访学，在学术研究和生活上提供必要的帮助。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Carolina Carazo院长对人大新闻学院和倪宁常务副院长的热情接待表示衷心感谢，并将继续推动哥斯达黎加大学新闻学院和人大新闻学院的联系与合作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，中国人民大学负责在哥斯达黎加大学建立了孔子学院。Carolina Carazo教授此次到人大将进行为期六个月的访学，在此期间将为人大新闻学院的同学授课，还将与相关教师开展广泛交流。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
