{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学财政金融学院教师调研成果受到中央领导高度重视并收到中国科协发文表扬{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-06-11 03:16:34{/dede:field}
{dede:field name='body'}<p>　　近日，中国科学技术协会调研宣传部专门发文，就其上报的由中国人民大学黄文彬博士完成的研究报告&mdash;&mdash;《学术不端行为日趋多样化，青年和高学历者问题最严重》受到中央领导同志高度重视并做出重要批示一事予以特别表扬。</p>
<p>　　来文称，&ldquo;研究报告经中国科协2009年9月上报后，受到中央领导同志的高度重视，并做出了重要批示，为推动科研人员和科技工作者的道德诚信建设做出了积极贡献。希望您与课题组的同志们继续努力，认真践行科学发展观，坚持以人为本，深入调查研究，及时反映科技工作者的现实需求和利益关切，为提高决策科学民主化水平做出应有的贡献。&rdquo;</p>
<p>　　据悉，该研究报告系中国科协2008年重大调查研究类课题&ldquo;科技工作者科研道德与诚信状况调查&rdquo;的主要研究成果之一，该报告主要由财政金融学院教师黄文彬博士完成，文中的观点和建议颇具新意，论证充分。</p>
<p></p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
