{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中央和国家机关司局级干部“环境保护低碳经济及可持续发展专题班”在中国人民大学开讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/图 环境学院{/dede:field}
{dede:field name='pubdate'}2010-06-09 09:56:01{/dede:field}
{dede:field name='body'}<p>　　6月7日，由中共中央组织部主办、中国人民大学承办、由环境学院教师团队为主讲的中央和国家机关司局级干部自主选学首期专题班&mdash;&mdash;&ldquo;环境保护低碳经济及可持续发展专题班&rdquo;在中国人民大学正式开讲。中国人民大学副校长冯惠玲，中国人民大学环境学院院长马中和中国人民大学培训学院院长李湘出席了开学典礼。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfyhbnbnf-lbhll.jpg" /></p>
<p>　　冯惠玲副校长代表学校对前来参加培训的学员表示热烈的欢迎并作了热情洋溢的开幕致辞。冯惠玲副校长向学员介绍了人民大学作为共和国建设者的摇篮、中国人文社会科学高等教育的重镇、马克思主义教学和研究重要基地的三个办学优势特色，并概述了学校的办学历史和办学理念，最后表示学校将提供良好的教育资源和周到的教学服务，全力做好各项培训工作。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfybzhnzf-hn2fb.jpg" /></p>
<p>　　开学典礼后，环境学院院长马中教授为学员讲授第一课，主题为&ldquo;中国环境保护与经济发展的两难与双赢&rdquo;。马中教授从中国发展的环境经济特征，尴尬的两难，历史的经验，可能的双赢，环境财政这五方面讲解了环境保护和其中的机遇。马中教授还结合环境学院主要研究的&ldquo;三江湿地&rdquo;和&ldquo;黄山&rdquo;两个实例来分析当前环境问题的发展与演化。课后马中教授和各位参与培训的学员就实际工作中遇到的各种问题进行了交流探讨。</p>
<p>　　据悉，本次专题班共有31位来自不同单位的司局级领导干部学员，培训将连续进行5天，从理论、形势等角度讲授我国环境保护、低碳经济与可持续发展的相关知识。参与授课的教师主要为环境学院的知名教授。</p>
<p></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfyhbnbnf-lbhll_lit.jpg{/dede:field}
