{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本大学商学院李克教授访问经济学院并发表学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月28日下午，日本大学商学院李克教授访问经济学学院并在明德楼主楼617会议室世纪经英讲坛上发表了题为&ldquo;Financial Integration in East Asian Equity Markets&rdquo;的演讲。经济学院院长杨瑞龙教授主持了演讲会。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhkfzzlnhf-hkyfz.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李克教授通过对当今亚洲经济一体化的研究，阐述了其带来的金融和资产的一体化问题。研究方法上，李克教授选择了ICPAM 的研究方法，通过整个金融市场频率、频度变化的一致性来评价金融市场的一体化。数据选取上，李克教授选取了亚洲12个主要国家及美国的金融市场数据，并用各个国家的GDP作为权数弥补国家贸易额之间的差别。通过研究，李克教授发现，在短期中，非理性行为羊群效应起作用；而在长期中，区域间价值、理性程度上升，金融市场紧密程度上升。李克教授还探讨了亚洲一体化下台湾的发展问题，以及中国政府不同部门对亚洲金融一体化的不同态度等现实问题。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲结束后，杨瑞龙院长希望同学们要有多关注亚洲一体化，特别是中日韩金融关系，关注人民币在亚洲、世界上扮演的角色。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhkf2bhzmf-bmnnz.jpg" width="139" height="186" alt="" /></p>
<p><br />
<br />
李克教授简介 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李克教授现任日本大学商学院终身教授，中国人民大学经济学院兼职教授，《亚太经济评论》(Pacific Economic Review)联合主编（SSCI Listed Journal），澳大利亚莫纳士大学&ldquo;国际超边际分析与经济组织研究中心&rdquo;核心研究员，在&ldquo;新型古典经济学&rdquo;的领域中有丰硕的研究成果。近五年来，共在SSCI级别的经济学期刊上发表论文15篇，在SCI和管理类期刊上发表论文5篇。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1262052782{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkfzzlnhf-hkyfz_lit.jpg{/dede:field}
