{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院成立能源经济研究中心 做好能源经济专业人才培养{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月25日下午，经济学院召开专门会议，成立能源经济研究中心。会议经讨论，成立了经济学院能源经济学科建设委员会。委员会主任由杨瑞龙院长担任，刘瑞教授、郑新业副教授担任副主任，金乐琴教授担任秘书长，宋枫博士担任副秘书长。会议就能源经济专业的培养方案、师资再造、2011级招生工作等进行了讨论，并作出相关工作部署。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年7月，国家教育部新批准了140个全国高等学校战略性新兴产业相关本科新专业，经济学院申请的能源经济专业获批，这也是人民大学唯一获批的专业，也是北京高校唯一新增的经济学类本科专业，主要培养面向21世纪的具有较高专业素养、较强应用技能和科研能力的能源经济专门人才。</p>
<p>（编辑：王宝奎；核稿：丁凯）&nbsp;<br />
</p>{/dede:field}
{dede:field name='pubdate'}1288061330{/dede:field}
{dede:field name='litpic'}{/dede:field}
