{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}马赛商学院校长访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/国际交流处 图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-01-11 10:29:23{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月10日下午，纪宝成校长会见了来访的马赛商学院校长Bernard BELLETANTE教授。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在会见中，纪宝成校长简要介绍了中法学院建设的进展，纪校长表示，待中国教育部正式批准后，希望中法双方能够共同努力办好中法学院，做到让两国教育界满意，让两国学生满意。双方高校基于中法学院这一平台进一步促进学生交流、带动教师和科研合作。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mlhnfyzf-bmfml.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bernard BELLETANTE校长对人民大学商学院通过EQUIS认证表示祝贺，他回顾了与人民大学的合作历史。Bernard BELLETANTE校长表示将继续支持中法学院建设，并希望该项目能早日得到教育部批准。马赛商学院未来将逐步扩大来人民大学交流的学生规模和层次，并加强教师在教学和科研方面的合作。</p>
<p>&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mlbbnzyf-yyll2.jpg" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 党委副书记兼副校长王利明，国际交流处处长唐忠、财政金融学院院长郭庆旺等参加了会见。法国方面陪同来访的还有参与中法学院建设的魏让方（Jean-Francois VERGNAUD）教授和卜雨歌（Hugues BOITEAU）先生。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静 成敏）<br />
<br />
<br />
<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mlhnfyzf-bmfml_lit.jpg{/dede:field}
