{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}华中科技大学考察团访问新闻学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-06-22 03:56:29{/dede:field}
{dede:field name='body'}<p>　　6月21日上午，华中科技大学设备处处长余定国教授、教务处处长许晓东教授、实验中心主任张华鸣教授、华中科技大学新闻与信息传播学院院长张昆教授（我院1986届校友）、副院长张顺教授、副院长舒咏平教授一行来新闻学院访问。常务副院长倪宁教授会见来宾，广播电视系主任周勇副教授、实验室高级工程师许建平参与会见。</p>
<p>　　新闻学院常务副院长倪宁教授向考察团详细介绍了新闻学院在教学与实验设备的前期建设、后期管理与维护等方面的情况。考察团一行表示，人民大学新闻学院一直领跑我国新闻教育领域，在教学与实验设施的建设和管理方面的经验十分值得借鉴和学习。</p>
<p>　　考察团还参观了新闻学院的思科网真演播室、平面编辑实验室和非线性编辑实验室，并对新闻学院正在展出的&ldquo;方正杯报纸版面设计大赛&rdquo;的作品表示了赞赏。 </p>
<p>（编辑：毛岩政）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
