<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","人大学子在全国高校德语专业辩论赛中获得优胜奖",89,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院",214,263);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-11-18 11:38:46",265,324);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 全国高校德语专业第二届大学生辩论赛于11月14日至15日在广东外语外贸大学举行，人民大学获得优胜奖。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，此次活动由教育部高等学校外语专业教学指导委员会德语分会和歌德学院共同主办，来自全国各地的39所高校代表队参加了这次大赛。经过激烈角逐，上海外国语大学和北京外国语大学分获冠亚军。中国人民大学外国语学院2006级德语专业本科生孙聪、段庭辉获得优胜奖。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此外，人民大学德语专业外教Andreas Wistoff还作为评委参加了这次大赛的评审工作。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n<br />\r\n</p>",326,997);
$z[6][4]['name']="body";
$z[7]=Array("field","",999,1038);
$z[7][4]['name']="litpic";

?>