{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学台湾校友会热烈欢迎纪校长访台{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}人大赴台代表团{/dede:field}
{dede:field name='body'}<p>　　11月5日晚，中国人民大学台湾校友会在台北玺宴饭店设宴，欢迎纪宝成校长一行访问台湾，台湾校友会成员和人民大学在台交流学生70多人参加了宴会，其中不少学生来自于台湾中部和南部。 </p>
<p>　　宴会开始前，人民大学台湾校友会会长朱瓯对纪校长和代表团一行表示欢迎，并特别回顾了这两天陪同代表团访问的情形，表达作为一个人大人的骄傲。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhnzhnfkf-hyzkl.jpg" /></p>
<p>　　纪校长在讲话中对台湾校友会表示感谢，向大家亲切介绍了胡锦涛主席九月来校视察的情况和学校最近的发展变化，并向台湾校友会赠送了人民大学郑晓华教授书写的条幅&ldquo;春华秋实&rdquo;。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhnzmyb2f-bbykn.jpg" /></p>
<p>　　得知纪校长两天前在台湾度过了生日，台湾校友会特别为纪校长准备了生日蛋糕，并向纪校长赠送有所有参加人员签名的生日贺卡。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhn2f2llf-ymmmy.jpg" /></p>
<p>　　在台交流的同学即兴表演了刚刚学会的台湾流行舞蹈表示祝贺，人民大学国学院一在台交流学生还特别向校长赠诗。会场气氛热烈温馨，校友欢欣，师生相得，其乐融融。 </p>
<p>　　人民大学台湾校友会是在台湾地区第一个正式核准成立的大陆高校校友会。会长朱瓯博士毕业于人民大学法学院，现为中国国民党中央评议委员，曾任国民党中央社会工作会主任和台北市主委，为促进人民大学对台交流作出了重要贡献。</p>
<p>　　相关链接：[<a href="http://news1.ruc.edu.cn/102382/71662.html">海峡两岸大学校长论坛系列报道] 论坛将登场 欢迎晚宴为纪宝成校长庆生</a> </p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71672.html">纪校长率团赴台参加第三届海峡两岸大学校长论坛并作主题发言</a></p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71725.html">纪宝成校长接受台湾媒体采访</a></p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71728.html">纪宝成校长拜会吴伯雄先生、刘兆玄先生</a></p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71729.html">人民大学与台湾清华大学签订校际协议</a></p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71803.html">中国国民党荣誉主席连战会见纪宝成校长</a></p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71835.html">台湾新党主席郁慕明宴请纪宝成校长一行</a></p>
<p>　　　　　　　<a href="http://news1.ruc.edu.cn/102392/71836.html">纪宝成校长率团参访台湾&ldquo;中央研究院&rdquo;</a>　　　</p>
<p>　　（编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1289521948{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhnzhnfkf-hyzkl_lit.jpg{/dede:field}
