{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}郑保卫教授参加“纪念穆青诞辰90周年暨新闻名篇与名记者全国学术研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2011-03-15 03:33:47{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月12日，新闻学院郑保卫教授应邀参加了在郑州举行的&ldquo;纪念穆青诞辰90周年暨新闻名篇与名记者全国学术研讨会&rdquo;，并作了题为《论穆青的记者成才观》的大会主题发言。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次研讨会由郑州大学穆青研究中心、新闻与传播学院、新华社河南分社、中共河南省开封市委共同主办。中国记协书记处书记李存厚、新华社秘书长张锦，以及河南省有关部门的领导出席研讨会。穆青的亲属代表、穆青当年采访过的老模范及其亲属代表，以及兰考有关部门的代表也应邀参加了研讨会。来自全国新闻院校、研究机构和新闻媒体的专家、学者在会上围绕记者成才等问题展开了交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会后，与会代表前往兰考焦裕录纪念园拜谒了焦裕录墓，参观了焦裕录事迹展览，还到杞县参观了当年穆青就读的中学。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
