{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}强世功教授做客“法理论坛” 主讲“司法能动与中国的婚姻家庭”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-21 02:42:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; 3月15日晚，中国人民大学法学院法学理论教研室主办的&ldquo;法理论坛&rdquo;第七十四讲&ldquo;司法能动与中国的婚姻家庭&mdash;&mdash;从最高人民法院关于《婚姻法》的司法解释三谈起&rdquo;，在明德法学楼601学术报告厅隆重举行。本次论坛由北京大学法学院博士生导师强世功教授主讲，中国人民大学法学院尤陈俊讲师主持，评议人为中国人民大学法学院史彤彪教授、冯玉军教授和张龑讲师。来自北京大学法学院、北京航空航天大学法学院、北京邮电大学法律系、中国社科院近代史研究所、美国哥伦比亚大学、法制日报社、法律出版社和法学院的共100余位师生参加了本次论坛。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fymnbfkf-lnfzf.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;强世功教授首先就最高人民法院关于《婚姻法》的司法解释三（征求意见稿）尤其是其中第11条的规定，阐释了当前我国家产制式微而个人财产制主导的趋势。他认为，从历史的角度来看，1950年代后，我国婚姻家庭领域确立了家庭共有财产制，1993年法律扩大了共有财产的范围。而2001年修订的婚姻法，明确了个人（分割）财产制；2003年的婚姻法司法解释二采用了市场竞价的方式确定争议房屋的产权。新近的婚姻法司法解释三（征求意见稿）第11条&mdash;&mdash;&ldquo;夫妻一方婚前签订不动产买卖合同，以个人财产支付首付款并在银行贷款，婚后不动产登记于首付款支付方名下的，离婚时可将该不动产认定为不动产权利人的个人财产&rdquo;，更是对传统的共有家产制的摧毁，表现出房产分割中的市场经济逻辑。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;紧接着，强教授分析了最高人民法院出台婚姻法司法解释三的背景。他认为，最高人民法院关于理想家庭的法律想象，实际上就是按照&ldquo;爱情归爱情，财产归财产&rdquo;的逻辑，将家庭变成了分别拥有个人感情和财产的两个人组合在一起的&ldquo;合伙生意&rdquo;，其理想模式就是&ldquo;AA制契约婚姻&rdquo;，而这无疑是充满后现代主义婚姻价值观的激进想象。最高法院在这里采用了物权法中的个人主义原则，以期将&ldquo;司法为民&rdquo;转化为&ldquo;司法便民&rdquo;。然而，这种做法实际上方便了当事人离婚，不利于维持家庭的稳定，以至于&ldquo;司法为民&rdquo;和&ldquo;司法便民&rdquo;的结果变成了服务、方便于那些想离婚或希望离婚很容易的人。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，强教授认为几个婚姻法司法解释共同体现了最高人民法院在婚姻法领域的&ldquo;司法能动&rdquo;倾向。诸如婚姻法司法解释三这样的&ldquo;准立法&rdquo;色彩的司法解释的推出，表明最高法院正在&ldquo;司法能动&rdquo;的理念支配之下深刻侵入家庭关系之中。这种以摧毁家庭为代价的失当侵入，将导致了司法能动的一个意外后果&mdash;&mdash;婚姻的再封建化。而现代法治的要求之一是法院和司法的适当节制。对社会秩序的调整，除了依靠法律，还需要道德、宗教、习惯等规范的共同作用。我们需要将法律的帝国变为法律共和国。 </p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110419/zlflzn2fkf2hhzf-hkkby.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在评议阶段，冯玉军教授赞同强教授的两个观点，即不是法律越多越好，&ldquo;法到深处无善治&rdquo;，以及要对司法能动主义保持警惕。同时，冯老师也提出商榷意见。他认为主讲人带有理想主义的前见，而法官、律师则是从现实主义出发解决问题的。他反问道，试想AA契约制与模糊共产制，那种更能降低社会成本呢？ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 评议人张龑讲师认为，婚姻法的解释三体现了从法治浪漫主义向现实主义和个人主义婚姻家庭观的转向，强教授的讲座充满了批判，但这可能会导致虚无的倾向。张老师还对司法克制是法治的一个美德的观点表示异议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 评议人史彤彪教授对强世功教授回母校举办讲座表示欢迎，并对强教授的法律理想主义和对弱者的关怀以及对司法克制的追求表示赞赏，但他同时也指出没有必要过分担心婚姻法司法解释所可能带来的负面后果。他认为，为了增进司法审判的效率，确立一个标准，AA制也未尝不可。&nbsp; </p>
<p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="/uploads/allimg/c110419/zlflzn2fkflfklf-bbbkh.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在互动环节，主持人尤陈俊老师认为强世功教授对&ldquo;家产制&rdquo;概念的运用可能需要斟酌和再定义。尤老师指出，学界所理解的&ldquo;家产制&rdquo;概念，通常来自马克斯&bull;韦伯的支配社会学，而强教授所谓的&ldquo;家产制&rdquo;显然不同于马克斯&bull;韦伯的用法，为了避免同名异意所可能引起的混淆，应该加以界定和说明。另外，尤老师也强调，中国目前的家庭形态究竟为何、城市和农村的家庭有哪些差别，这些都应该是最高法院婚姻法司法解释出台之前和学者评论司法解释之时需要详细调查和研究的内容。北京大学法学院车浩讲师、北京航空航天大学法学院毕洪海讲师、法律出版社刘文科编辑等嘉宾和一些同学，也分别表达了自己的看法并提出问题，强老师在最后作出了整体回应。论坛在充满学术争鸣的热烈氛围下圆满结束。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fymnbfkf-lnfzf_lit.jpg{/dede:field}
