{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院马中院长会见荷兰Arthur Mol教授{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2010-06-03 09:09:00{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月1日，马中院长会见了到访我院的荷兰瓦格宁根大学Arthur Mol教授，张磊副教授、博士生金书秦参加了会谈。马中院长首先对Arthur Mol教授表示了欢迎，随后详细介绍了目前正在进行的生活污水处理价格机制研究项目、区域和城市清洁空气项目、黄山教学基地建设等情况。双方就建立更加紧密的合作关系进行了探讨。合作内容包括共同申请、参与彼此研究项目，联合培养硕、博士研究生，在高水平国际性期刊发表论文等。</p>
<p></p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
