<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","环境学院马中院长会见荷兰Arthur Mol教授",89,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","环境学院",208,255);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-03 09:09:00",257,316);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月1日，马中院长会见了到访我院的荷兰瓦格宁根大学Arthur Mol教授，张磊副教授、博士生金书秦参加了会谈。马中院长首先对Arthur Mol教授表示了欢迎，随后详细介绍了目前正在进行的生活污水处理价格机制研究项目、区域和城市清洁空气项目、黄山教学基地建设等情况。双方就建立更加紧密的合作关系进行了探讨。合作内容包括共同申请、参与彼此研究项目，联合培养硕、博士研究生，在高水平国际性期刊发表论文等。</p>\r\n<p></p>",318,782);
$z[6][4]['name']="body";
$z[7]=Array("field","",784,823);
$z[7][4]['name']="litpic";

?>