<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","澳大利亚墨尔本大学文学院院长马克康赛丹教授访问公共管理学院",89,185);
$z[2][4]['name']="title";
$z[3]=Array("field","",187,226);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",228,279);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-18 03:33:23",281,340);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　4月14日下午，澳大利亚墨尔本大学文学院(Faculty of Arts, The University of Melbourne)院长马克&bull;康赛丹(Mark Considine)教授、亚洲研究院高佳博士和墨尔本大学北京办事处工作人员一行3人应邀访问公共管理学院。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflzn2bbyblbzf-z2yfh.jpg\" alt=\"\" /></p>\r\n<p>　　公共管理学院院长董克用教授会见了来访的澳大利亚客人。在会见中，董院长首先对康赛丹教授和高佳博士的到访表示欢迎，双方就学院间的合作交流、学者交流和硕士生互访交流等方面交换了意见。随后，双方院长共同签署了《合作执行协议2011-2013》。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflzn2bbymzbf-2hkyn.jpg\" alt=\"\" /></p>\r\n<p>（编辑：吴琰坤）&nbsp;<br />\r\n</p>",342,1059);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflzn2bbyblbzf-z2yfh_lit.jpg",1061,1153);
$z[7][4]['name']="litpic";

?>