{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}澳大利亚墨尔本大学文学院院长马克康赛丹教授访问公共管理学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 03:33:23{/dede:field}
{dede:field name='body'}<p>　　4月14日下午，澳大利亚墨尔本大学文学院(Faculty of Arts, The University of Melbourne)院长马克&bull;康赛丹(Mark Considine)教授、亚洲研究院高佳博士和墨尔本大学北京办事处工作人员一行3人应邀访问公共管理学院。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bbyblbzf-z2yfh.jpg" alt="" /></p>
<p>　　公共管理学院院长董克用教授会见了来访的澳大利亚客人。在会见中，董院长首先对康赛丹教授和高佳博士的到访表示欢迎，双方就学院间的合作交流、学者交流和硕士生互访交流等方面交换了意见。随后，双方院长共同签署了《合作执行协议2011-2013》。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bbymzbf-2hkyn.jpg" alt="" /></p>
<p>（编辑：吴琰坤）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2bbyblbzf-z2yfh_lit.jpg{/dede:field}
