<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","“中国商业媒体的现状与未来”专题讨论会在新闻学院举行",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",222,269);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-14 08:54:56",271,330);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　5月12日下午，由中国人民大学新闻学院和中国美国商会媒体与娱乐论坛首次合作的&ldquo;中国商业媒体的现状与未来&rdquo;专题讨论会在中国人民大学明德新闻楼3层的网真演播室举行。</p>\r\n<p>　　道琼斯通讯社北京分支机构负责人J.R. Wu，央视9套《对话》栏目制片人和主持人杨锐以及中国人民大学财政金融学院副院长赵锡军等嘉宾应邀出席，《经济学人》杂志驻华记者Ted Plafker主持了讨论会。</p>\r\n<p>　　与会人员就中国经济、传媒发展现状、中国媒体在当今社会条件下应承担的责任、新媒体技术背景下&ldquo;草根新闻&rdquo;给传媒带来的改变等话题进行了讨论，并就中国商业媒体发展现状以及未来发展趋势谈了自己的看法。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzkfmlnknyf-nnynz.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p>　　在互动环节，现场观众就09年经济数据的发布、软实力和硬实力构建过程中传媒的作用、媒介与政府关系等话题与嘉宾进行了交流。</p>\r\n<p>　　此次专题讨论会吸引了来自中国人民大学10多个院系的120名师生和美国商会会员参与。</p>\r\n<p>　　（编辑　陈慧茹）&nbsp;<br />\r\n</p>",332,1334);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100619/z2kymzkfmlnknyf-nnynz_lit.jpg",1336,1428);
$z[7][4]['name']="litpic";

?>