<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中央机构编制委员会办公室吴知论副主任来公共管理学院作讲座",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",226,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-27 10:59:53",279,338);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月21日，公共管理学院兼职教授、中央机构编制委员会办公室吴知论副主任应邀为公共管理学院2010级行政管理系博士生作了题为&ldquo;中国行政管理体制改革回顾与展望&rdquo;的专题讲座。董克用院长代表学院对吴主任的到来表示欢迎，蓝志勇副院长主持讲座。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该讲座为公共管理学院&ldquo;中国公共管理改革与发展高层论坛&rdquo;系列讲座之一。在讲座过程中，吴主任精彩的演讲内容、诙谐流畅的语言、良好的互动，以及立足于中国本土政治和管理环境的研究风格、独到凝炼的学术视角、勤于思考的钻研精神，均给同学们留下了深刻的印象。同时，吴主任还认真地一一回答了同学们的提问。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n<br />\r\n</p>",340,1077);
$z[6][4]['name']="body";
$z[7]=Array("field","",1079,1118);
$z[7][4]['name']="litpic";

?>