{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中央机构编制委员会办公室吴知论副主任来公共管理学院作讲座{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-12-27 10:59:53{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月21日，公共管理学院兼职教授、中央机构编制委员会办公室吴知论副主任应邀为公共管理学院2010级行政管理系博士生作了题为&ldquo;中国行政管理体制改革回顾与展望&rdquo;的专题讲座。董克用院长代表学院对吴主任的到来表示欢迎，蓝志勇副院长主持讲座。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该讲座为公共管理学院&ldquo;中国公共管理改革与发展高层论坛&rdquo;系列讲座之一。在讲座过程中，吴主任精彩的演讲内容、诙谐流畅的语言、良好的互动，以及立足于中国本土政治和管理环境的研究风格、独到凝炼的学术视角、勤于思考的钻研精神，均给同学们留下了深刻的印象。同时，吴主任还认真地一一回答了同学们的提问。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
