{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院与韩国金融投资协会合作签字仪式隆重举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院 文/姚泽宇{/dede:field}
{dede:field name='pubdate'}2010-11-26 08:34:00{/dede:field}
{dede:field name='body'}<p>　　11月25日，中国人民大学财政金融学院与韩国金融投资协会合作签字仪式于明德主楼830会议室隆重举行，双方就开展广泛的长远合作事项达成协议。中国人民大学财政金融学院院长郭庆旺，韩国金融投资协会副会长张建相、组长卢贯植等领导和嘉宾出席了本次合作签字仪式。财政金融学院院长助理类承曜担任主持人。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110113/z2mhnnblkff2n2f-zmhbm.jpg" /></p>
<p>　　郭庆旺院长在致辞中对张建相副会长一行的到来表示感谢。郭院长表示，韩国金融投资协会是在&ldquo;韩国资本市场综合法&rdquo;实施以后，由韩国的所有证券公司及资产管理公司组成的民办协会，财政金融学院很荣幸也很乐意为韩国金融投资协会提供一个交流与学习的广阔平台，并希望与韩国金融投资协会继续保持良好的合作关系，共同为两国资本市场发展做出应有贡献。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnblkz2llmf-2mfbn.jpg" /></p>
<p>　　随后，张建相副会长对财政金融学院的热情款待表示衷心感谢。张副会长谈到，韩国金融投资协会在积极聚集韩国金融界精英群体以适应国际金融环境外，还肩负着提高韩国证券投资风险管理能力、提供充足后勤保障等方面的重任，同时，世界金融市场的变化对韩国资本市场力量的增强提出了更高的要求。在中韩两国交流日益频繁的背景之下，中国人民大学财政金融学院与韩国金融投资协会的合作能为中韩两国培养更多金融领域人才，同时为两国专家学术交流提供更广阔的平台。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnblkzkmkyf-lmfzy.jpg" /></p>
<p>　　在签字仪式中，郭庆旺院长与张建相副会长共同在合作备忘录上郑重签字，互赠精心准备的礼物，并与在场嘉宾们亲切合影留念。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnblkff2n2f-zmhbm_lit.jpg{/dede:field}
