{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院陈卫东教授率“中欧遏制酷刑项目”考察团访欧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院  文/魏晓娜{/dede:field}
{dede:field name='pubdate'}2010-05-18 02:30:41{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，中国人民大学法学院诉讼制度与司法改革研究中心主任陈卫东教授率领&ldquo;中欧遏制酷刑项目&rdquo;访欧考察团在斯特拉斯堡、日内瓦、哥本哈根和阿姆斯特丹进行了为期10天的访问。由陈卫东教授主持的诉讼制度与司法改革研究中心与英国英中协会、荷兰马斯特里赫特大学合作申请的欧盟&ldquo;遏制酷刑&rdquo;项目目前已经进入到第二期。项目的总体目标是加强遏制酷刑方面的研究工作，推动中国落实联合国反酷刑公约及其任择议定书。项目的主要内容包括羁押巡视制度、酷刑受害人的投诉与处理机制、非法证据排除规则等相关遏制酷刑机制。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次访问也主要围绕上述议题展开。考察团先后访问了欧洲理事会反酷刑委员会，与该委员会主席帕尔马先生（Mr Mauro Palma）进行会晤；访问日内瓦警察局；与国际红十字会就反酷刑问题进行会谈；参观了瑞士的Champ-Dolon监狱；与国际反酷刑协会进行会谈；由瑞士、英国的羁押巡视官介绍两国国家羁押巡视制度的运作情况；与丹麦人权中心进行会谈；访问丹麦国家检察院，与副总检察长进行会晤；访问丹麦的Vestre F&aelig;ngsel监狱、与丹麦监狱与缓刑服务局官员进行会谈；在阿姆斯特丹警察局参观访问并在阿姆斯特丹地方法院旁听聆讯。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次考察团成员包括：陈卫东教授、最高人民法院刑四庭庭长杨万明、最高人民检察院公诉厅副厅长黄河、国家检察官学院吉林分院院长王文生、全国人大法工委刑法室一处调研员汤卫平、王倩，英中协会高级项目经理欧泊怀。法学院教师魏晓娜、程雷随行。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyhmklzmyf-zzlm2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：徐晶晶）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyhmklzmyf-zzlm2_lit.jpg{/dede:field}
