{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}赵国权先生向哲学院捐资设立阳光创业奖学金{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-04-01 03:46:02{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月31日下午，由中国人民大学哲学院、北京阳光君桥科技投资有限公司主办，中国人民大学管理哲学研究中心承办的赵国权先生客座教授聘任仪式暨阳光创业奖学金颁奖典礼在中国人民大学学生活动中心多功能厅隆重举办。本次活动场面庄严正式，气氛热烈。参加本次典礼的领导有中国人民大学校长助理、哲学院院长郝立新教授，中国人民大学哲学院副院长魏德东教授等。仪式由管理哲学研究中心执行主任刘敬鲁教授主持。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnhbnhmfkf-zbmkz.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郝立新院长介绍了赵国权董事长创业经历，代表中国人民大学哲学院和管理哲学研究中心向赵国权先生表示感谢，并希望赵先生一如既往地支持关心帮助哲学院的发展。哲学院党委副书记苏昊老师宣读了获奖同学名单，赵国权先生为获得首届阳光创业奖学金的十名同学颁发了证书及奖金，并与同学们合影留念。在激昂的校歌声中，郝立新院长为赵国权先生颁发了哲学院客座教授聘书。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 阳光创业奖学金由赵国权先生个人捐资设立，捐赠金额为人民币叁拾万元。旨在鼓励哲学学子们努力学习，培养创业意识，服务社会、回报母校。</p>
<p><strong>【相关链接</strong>】</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 赵国权，男，一九五四年生，四川重庆市人。毕业于贵州大学哲学系，学士学位；北京大学光华管理学院，硕士学位。曾在贵州省政府，海南省政府，北海市委工作，历任副处长、处长、副秘书长等职。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一九九四年下海经商，曾担任中保信实业投资公司总裁，香港昌运风险投资公司总裁，华夏西部投资有限公司总裁。现任北京阳光君桥科技投资有限公司董事长。中国知名投资专家。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnhbnhmfkf-zbmkz_lit.jpg{/dede:field}
