{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长《大学的探索》一书出版发行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='body'}<p>　　近日，纪宝成校长著作《大学的探索》一书由我校出版社正式出版发行。 </p>
<p>　　《大学的探索》收录了纪宝成校长2000年9月任职以来至2009年9月为止关于办什么样的中国人民大学、如何办好中国人民大学的一系列讲话和文章。全书共三卷、90余万字，分为&ldquo;总体办学思路与新的启航&rdquo;、&ldquo;人民大学与人文社会科学&rdquo;、&ldquo;学科建设的一个体系与三个意识&rdquo;、&ldquo;大师、大楼、大气&rdquo;、&ldquo;科学管理与&lsquo;真情、真想、真干&rsquo;&rdquo;、&ldquo;塑国民表率、育社会栋梁&rdquo;、&ldquo;接续文脉、重振国学&rdquo;、&ldquo;兼容并蓄与提升国际性&rdquo;等八个部分。 </p>
<p>　　该书反映了纪宝成校长结合中国人民大学的办学实践，对大学精神、大学理念、大学功能、大学使命和责任、大学发展战略、大学组织、具体办学举措、中国大学如何办成世界一流大学等诸多问题进行的思考和探索、实践和创新，很多方面其实不单纯是大学发展的事件，对社会发展和文化发展都产生了积极的影响。 </p>
<p>　　因此，该书忠实记录了纪宝成校长和人大师生员工九年来团结奋进、开拓创新、全心全意办好人民大学的风雨历程和发展画卷，同时也从一个侧面折射出新世纪以来中国高等教育改革和发展取得的巨大成就和面临的挑战。相信《大学的探索》一书的出版，能够对于关心中国人民大学的读者、关注中国大学改革和发展的读者提供参考和借鉴。</p>
<p><a href="http://news1.ruc.edu.cn/102731/71888.html">附：《大学的探索》编者前言</a></p>
<p>　　（编辑：毛岩政）</p>{/dede:field}
{dede:field name='pubdate'}1289611505{/dede:field}
{dede:field name='litpic'}{/dede:field}
