{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京市监察局来函感谢人民大学及经济学院彭丽红副教授{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-23 05:38:20{/dede:field}
{dede:field name='body'}<p>　　近日，北京市监察局来函感谢经济学院彭丽红教授为民主监督工作所作出的贡献，并感谢人民大学对彭丽红副教授工作的大力支持与帮助。 <br />
　　来函中说，经济学院副教授，民盟市委委员，海淀区政协委员彭丽红副同志，2008年4月被聘为北京市政府第七批特约监察员。三年来，该同志认真履行特约监察员工作职责，积极参与北京市党风廉政建设和反腐败工作，为北京市反腐倡廉建设作出了积极贡献。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
