{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本九州大学木佐茂男教授续聘人大法学院暨宪政与行政法治研究中心客座教授{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院 王雁雄{/dede:field}
{dede:field name='pubdate'}2011-03-25 11:23:16{/dede:field}
{dede:field name='body'}<p>　　3月18日下午，中国人民大学法学院、宪政与行政法治研究中心续聘日本九州大学研究生院法学研究院木佐茂男教授担任客座教授，仪式在明德法学楼725室举行。中国人民大学宪法与行政法治研究中心执行主任莫于川教授主持仪式，他对木佐教授在日本遭遇9.0级大地震，尚需接待从日本东北地方来避难的诸多亲友的忙碌情况下仍按原计划到访法学院表示钦佩与慰问。法学院副院长兼宪政与行政法治研究中心主任胡锦光教授致欢迎词。王贵松副教授、喻文光讲师、王旭讲师等青年教师出席。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fy2zzbnf-hymml.jpg" /></p>
<p>　　胡锦光教授首先代表法学院和宪政与行政法治研究中心对木佐茂男教授在上一聘期积极履职给予了高度评价，并向木佐教授颁发了新聘书。木佐教授对学院的续聘决定表示衷心感谢，表示今后将继续认真履行客座教授职责，为中日法学教育交流尽绵薄之力。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fy2hbmkf-bkmbl.jpg" /></p>
<p>　　简短的聘任仪式后，木佐教授以《行政与私人缔结契约的各种问题&mdash;&mdash;以公害防止协定为中心》为题做了主题学术演讲。他首先向在座师生展示了自己在日本作为律师参与相关诉讼时拍摄的照片，并根据自己亲身经历，详细介绍了日本的&ldquo;公害防止协定&rdquo;制度。他强调，日本的公害防止协定主要采取企业与地方自治共同体签署行政合同的方式，在日本学界被认为是行政合同与行政指导的一种典型表现。随后，他以亲身参与的诉讼案件为例，剖析了这一制度的利弊得失与相关学理问题，在肯定其成绩的同时，也指出了其存在的一系列问题。最后，他诚恳地表示，中国的高速发展带来的环境问题与日本有许多相似之处，希望自己的介绍能为解决相关问题提供借鉴。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fy2bfzkf-ynlz2.jpg" /></p>
<p>　　演讲结束后，王贵松副教授、喻文光讲师对木佐教授的演讲进行了精彩点评，并就自己关心的问题与木佐教授进行了交流。木佐教授一一回答了与会者的提问。在活跃的互动交流结束后，莫于川教授代表法学院暨宪政研究中心向木佐教授赠送了礼品。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fy2bbzf-khnzz.jpg" /></p>
<p>　　木佐茂男教授是日本著名行政法学教授，先后编写出版著作、教材三十多部，发表论文二百余篇，其代表作是《人的尊严与司法权》，曾参与日本《行政诉讼法》、《行政不服审查法》等法律起草工作。2006年10月起被聘为法学院暨宪政研究中心客座研究员、客座教授。 </p>
<p>（编辑：吴琰坤）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fy2zzbnf-hymml_lit.jpg{/dede:field}
