{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院“中国金融硕士国际项目”举行开班仪式{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财金学子杂志社 姚泽宇 刘腾{/dede:field}
{dede:field name='pubdate'}2010-09-26 11:57:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月21日，由中国人民大学财政金融学院开设的首届&ldquo;中国金融硕士国际项目（Master of Science in Finance International Program）&rdquo;在明德主楼举行开班仪式。财政金融学院副院长赵锡军教授、副院长何平教授、项目主任陈忠阳教授、应用金融系主任汪昌云教授、货币金融系副主任张成思教授、保险系副主任魏丽副教授、以及相关负责人员参加了开班仪式。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c101124/z2mfbnmkblmmlbf-nzh2k.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 项目主任陈忠阳教授主持了开班仪式。陈忠阳教授向留学生们详细介绍了与会的领导和老师，并向美国留学生简要说明了&ldquo;中国金融硕士国际项目&rdquo;的构想及其教学方案。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 项目的主管院长何平副院长代表财政金融学院对留学生们表示热烈的欢迎，并对项目的宗旨和实施方案进行了补充说明。他指出，该项目的成功必须依靠教与学双方的共同努力和良性互动，希望通过本项目，将留学生培养成为既通晓一般金融理论，又熟悉中国金融运行特征的人才。他鼓励留学生们要迎难而上，刻苦钻研，并充分利用学院特地设置的中文课程，积极参加学术交流活动，增加对中国学术文化的了解。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 赵锡军副院长向留学生们介绍起中国特色社会主义政治、经济与美国的差异，希望留学生们能联系中国社会实际状况，深入分析金融学在中国的发展与应用。张成思教授则联系自己在英国曼彻斯特大学学习的经历，谈及对异国文化适应的艰难，并衷心希望留学生们能很快融入到中国文化当中。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在自由交流阶段，参加会议的教授与在座的留学生们寒暄，聊到他们在美国的毕业院校和家乡等，让留学生们倍感亲切和温馨。留学生们纷纷感谢学院对他们的热情接待。大家都表示精神饱满，对成功完成学业充满信心，并表达了对学术研究的热忱以及对中国文化认知的强烈渴望。 最后，何平副院长向留学生们分发了特别为他们准备的月饼，向美国留学生说明这代表在中国传统节日中秋节送上最诚挚的祝福，使留学生们倍感温暖。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;中国金融硕士国际项目&rdquo;是财政金融学院在全球化背景下，进行人才培养国际化的全新探索。表示该项目是财政金融学院人才培养模式的又一创新，语言文化上的障碍以及课程较高的难度对学生们都将是极大挑战。面对来自美国、完全在美式教育环境下成长起来的学生，对教师队伍的素质将提出新的要求，必将推动人民大学人才培养国际化发展。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnmkblmmlbf-nzh2k_lit.jpg{/dede:field}
