<?php
$z[0]=Array("sppage","",0,41);
$z[0][4]['sptype']="full";
$z[1]=Array("previewurl","http://www.ruconline.com/news.asp?newsid=224",43,122);
$z[2]=Array("keywordtrim","",124,161);
$z[3]=Array("descriptiontrim","",163,208);
$z[4]=Array("item","\r\n   {dede:match}<font color=#ff0000><b>[内容]</b></font>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",210,389);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",389,529);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}来源：[内容]<{/dede:match}\r\n   {dede:trim replace=\"\"} {/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",529,717);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}<div align=\"center\"> 发布时间：[内容] 此新闻{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",717,902);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<td height=\"200\" valign=\"top\"><br>[内容]</td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"30\">{/dede:match}\r\n   {dede:trim replace=\"\"}<span([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</span>{/dede:trim}\r\n{dede:trim replace=\"\"}<FONT([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</FONT>{/dede:trim}\r\n{dede:trim replace=\"\"}来源：人大新闻网{/dede:trim}\r\n{dede:trim replace=\"\"}</TD></TR></TBODY></TABLE>{/dede:trim}\r\n{dede:trim replace=\"\"}<TABLE width=\"100%\">([^>]*)<TD style=\"PADDING-BOTTOM: 20px; LINE-HEIGHT: 22px; PADDING-LEFT: 20px; PADDING-RIGHT: 20px; FONT-SIZE: 10.5pt; TEXT-DECORATION: none\" vAlign=top width=\"90%\" align=left>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",902,1690);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>