{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国际劳工组织高级经济学家Wolfgang SCHOLZ先生访问统计学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-11-07 05:26:12{/dede:field}
{dede:field name='body'}<HTML><HEAD><TITLE> 国际劳工组织高级经济学家Wolfgang SCHOLZ先生访问统计学院 </TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style><!--
 .iframestyle{height:expression(1);aho:expression(autoResize()) 
}
-->
</style>
<script>
function autoResize()
{
try
{
 document.all["showDemand"].style.height=showDemand.document.body.scrollHeight
}
 catch(e){}
}
 </script><body><P>&nbsp;&nbsp;&nbsp; 应统计学院王晓军教授的邀请，国际劳工组织社会保障部高级经济学家 Wolfgang SCHOLZ先生一行于11月3日下午对中国人民大学统计学院进行了访问并做了题为“社会预算模型”（Social Budget Models）的精彩演讲。　　</P>
<P>&nbsp;&nbsp;&nbsp; 演讲的内容包括什么是社会预算，为什么需要社会预算，Wolfgang SCHOLZ先生还运用清晰的框架、生动的图形和案例介绍了国际劳工组织的社会预算模型。　　</P>
<P>&nbsp;&nbsp;&nbsp; 通过Wolfgang SCHOLZ先生的讲演，统计学院的师生对世界和中国社会保障问题有了新的认识，获得很大的收获。</P>
<P>&nbsp;</P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
