<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","国际劳工组织高级经济学家Wolfgang SCHOLZ先生访问统计学院",89,182);
$z[2][4]['name']="title";
$z[3]=Array("field","",184,223);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",225,272);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-11-07 05:26:12",274,333);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<HTML><HEAD><TITLE> 国际劳工组织高级经济学家Wolfgang SCHOLZ先生访问统计学院 </TITLE><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><style><!--\n .iframestyle{height:expression(1);aho:expression(autoResize()) \n}\n-->\n</style>\n<script>\nfunction autoResize()\n{\ntry\n{\n document.all[\"showDemand\"].style.height=showDemand.document.body.scrollHeight\n}\n catch(e){}\n}\n </script><body><P>&nbsp;&nbsp;&nbsp; 应统计学院王晓军教授的邀请，国际劳工组织社会保障部高级经济学家 Wolfgang SCHOLZ先生一行于11月3日下午对中国人民大学统计学院进行了访问并做了题为“社会预算模型”（Social Budget Models）的精彩演讲。　　</P>\r\n<P>&nbsp;&nbsp;&nbsp; 演讲的内容包括什么是社会预算，为什么需要社会预算，Wolfgang SCHOLZ先生还运用清晰的框架、生动的图形和案例介绍了国际劳工组织的社会预算模型。　　</P>\r\n<P>&nbsp;&nbsp;&nbsp; 通过Wolfgang SCHOLZ先生的讲演，统计学院的师生对世界和中国社会保障问题有了新的认识，获得很大的收获。</P>\r\n<P>&nbsp;</P>",335,1299);
$z[6][4]['name']="body";
$z[7]=Array("field","",1301,1340);
$z[7][4]['name']="litpic";

?>