{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院成功举办首届中国人民大学-辅仁大学社会学系交流活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会学系{/dede:field}
{dede:field name='pubdate'}2010-10-08 08:40:18{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月27日至9月29日，第一届中国人民大学社会系-辅仁大学社会学系交流活动在社会与人口学院举行。本次交流活动主要包括两系教授交流会和辅仁大学教授与人民大学学生座谈会两部分。参加本次交流活动的有中国社会学会名誉会长、中国人民大学社会学理论与方法研究中心主任郑杭生教授，社会与人口学院党委书记兼副院长郭星华教授，社会与人口学院副院长兼社会学系主任李路路教授以及辅仁大学社会学系主任鲁贵显教授，社会学系张汉音教授，谢宏仁教授等老师。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 27日上午，两系教授交流会在科研楼A座512会议室召开。交流会由社会与人口学院党委书记郭星华教授主持。交流会伊始，中国人民大学社会学系主任李路路教授与辅仁社会学系主任鲁贵显教授分别致辞并分别介绍两系的基本情況。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，参加此次交流会的教授们分别就自己的研究成果作简短的报告。社会与人口学院社会学系的老师分别围绕社会学本土化与社会学者理论自觉等多个主题进行报告。辅仁大学方面则分别就行动者网络与技术等不同问题展示自己的研究成果。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲演结束后，李路路教授与鲁贵显教授分别就报告作简要点评。李路路教授在发言时提出，希望通过两系老师、学生之间的交流，促进双方的了解。鲁贵显教授则表示，期待交流活动的深入开展。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 交流会当天恰逢台湾的教师节，交流会筹备组的同学将人民大学同学制作的贺卡作为礼物送给鲁贵显教授一行。交流会在掌声与欢笑中圆满结束。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 28日上午，作为两系交流的另一重要组成部分，两系学生座谈会及赴台交换生学习生活感受介绍会在同一地点举行。辅仁大学社会学系主任鲁贵显教授，王庆中教授，吴宗昇教授以及中国人民大学社会学系廖菲副教授参加了座谈会。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，鲁贵显教授用图文并茂地介绍了辅仁大学的地理位置、师资配备、国际交流等情况，并特意解释了辅仁大学对于大学生培养、训练的理念。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，四位人民大学交换生代表先后上台，与在座同学分享在辅仁大学学习生活的感受。在师生互动环节中，多位同学就学分转换、学业论文、赴台深造等问题同与会的辅仁大学老师开展了深入交流。来自台湾的老师也强调了大陆学生赴台湾交流学习应注意的问题。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参加座谈会的同学在谈自己的感受时说，辅仁大学的教授和参与过交换项目的师兄师姐的详细介绍让自己体会到了辅仁大学师生的热情，也增进了对辅仁大学的了解。希望能有机会赴台湾学习深造，进一步感受当地的文化。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，第二届两系交流活动将于明年在台湾辅仁大学举行。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
