{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院洪大用教授出席世界社会学大会并发表演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2010-07-16 04:38:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应第十七届世界社会学大会组委会和国际社会学会环境与社会研究委员会（RC24）邀请，7月10日-15日，社会与人口学院教授、社会学理论与方法研究中心副主任、环境社会学研究所所长洪大用出席了在瑞典哥德堡举行的世界社会学大会并发表演讲。本次会议关注变动中的世界对社会学的挑战，呼吁社会学的变革。大会设置5个贯穿全会始终的主题会议，内容涉及暴力与冲突、可持续性与环境、现代性与制度、社会行动、社会学理论与方法等。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月15日，在&ldquo;可持续性与环境&rdquo;主题会议上，洪大用教授发表了题为&ldquo;理解中国社会的可持续性&rdquo;的大会演讲，集中讨论了中国社会的可持续性议题以及中国社会变迁对于社会学发展的意义，受到与会代表的广泛关注。洪大用教授认为，可持续性应是指人类社会整体的可持续性，而不是个体或小群体的可持续性，是一种动态的而非静止的可持续性，是兼顾环境与社会的可持续性，是一种相对意义上的可持续性。认识中国社会的可持续性需要用辨证的观点、动态的观点，应当避免结构主义倾向，并且不能把中国与世界割裂开来。当前中国社会同时并存着不可持续因素与可持续因素，科学发展观则是中国政府追求可持续性的新战略。洪大用教授指出，中国社会的巨变要求中国社会学深入反思其在中国社会变迁中的作用，反思社会学者与其所研究的对象&mdash;&mdash;社会&mdash;&mdash;之间的关系，拓展对于其研究对象的理解，同时要求中国社会学者保持清醒的理论自觉，致力于发展出整合性的社会学学科，不断创新社会学的研究方法。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月13日，在国际社会学会环境与社会研究委员会（RC24）组织的世界社会学大会&ldquo;社会理论与环境&rdquo;分论坛上，洪大用教授也作了题为&ldquo;中国低碳社会建设&rdquo;的发言，就低碳经济与低碳社会的关系、中国建设低碳社会的困境与出路等发表了自己的看法。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大会期间，洪大用教授还于7月10日-11日出席了国际社会学会环境与社会研究委员会（RC24）与瑞典一些大学合作举办的&ldquo;环境社会学与可持续发展国际学术研讨会&rdquo;，以及一些相关分论坛，会见了环境与社会研究委员会新任主席澳大利亚国立大学Stewart Lockie教授和前任主席加拿大渥太华大学Raymond Murphy教授、荷兰瓦汉宁根大学Arthur Mol教授、美国俄克拉荷马州立大学Riley Dunlap教授，并与来自不同国家和地区的学者进行了学术交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在国际社会学会环境与社会研究委员会（RC24）前不久举行的换届选举中，洪大用教授当选为2010-2014年环境与社会研究委员会执行委员会成员。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
