{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}维也纳大学罗马法教授Herbert Hausmaninger访问法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-31 08:55:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月29日上午11时，法学院韩大元院长在法学楼二楼贵宾室会见了来自奥地利维也纳大学法学院的Herbert Hausmaninger教授，法学院民商法教研室朱岩副教授陪同参加了会见。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylbzkllf-zzyfn.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 作为法学院&ldquo;海外杰出法学家课程&rdquo;系列的第一位主讲人，Herbert Hausmaninger教授的到来受到了法学院师生的热烈欢迎。教授此行的目的是为人民大学学生开设为期两周的罗马法课程。从3月29号到4月9号，他将在每周一、三、五各为同学们讲授3个小时的罗马法。韩院长代表中国人民大学法学院对他的辛勤付出表示感谢，并就青年教师培养、罗马法教材编订、学生交流三个方面同Herbert Hausmaninger教授展开交流。</p>
<p>　　在青年教师培养方面，韩院长提出目前人民大学法学院亟需既精通罗马法，又熟悉拉丁文的青年教师，希望人民大学法学院和维也纳大学法学院能进一步展开教师的交流培养活动。对此，Herbert Hausmaninger教授予以了积极的回应，他表示罗马法是维也纳大学的优势学科，同时拉丁语又是他本人的第一外语，因此他很高兴有机会为人民大学罗马法青年教师的培养贡献一份力量。</p>
<p>　　在教材编订方面，韩院长指出罗马法不仅在私法领域有举足轻重的地位，而且越来越多的公法学说也从中寻找依据，这使得罗马法受到了公私领域众多学者的共同关注。在这种形势下，编写出一本人民大学自己的罗马法教材是十分有意义的。因此，韩院长邀请Herbert Hausmaninger教授参与到教材编订的过程中，给予指导并提出宝贵意见。Herbert Hausmaninger教授愉快的接受了邀请。</p>
<p>　　在学术交流层面，Herbert Hausmaninger教授向韩院长介绍了维也纳大学现有的暑期项目。该项目采用英文授课，提供有关法律、经济、政治等方面的一系列课程。韩院长详细询问了该项目的学费、住宿、奖学金等问题，并进一步提出希望能和维也纳大学法学院之间建立学生交流项目，让人民大学的学生到维也纳大学进行为期一年的学习，法学院承认学分。此外，韩院长还表示欢迎维也纳大学派学生代表团来访，为学生的发展提供更好的平台，让学生成为双方交流合作的主体。</p>
<p>　　最后，韩院长邀请Herbert Hausmaninger教授参加即将于今年十月举行的六十年院庆，并且希望在此次短期授课之后，教授可以考虑来人民大学法学院开展更长期的课程。Herbert Hausmaninger对韩院长的盛情邀请表示感谢，宾主双方互赠了礼物并合影留念。 </p>
<p>　　（编辑：张利英）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylbzkllf-zzyfn_lit.jpg{/dede:field}
