{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院举办第二十五期“科学—社会—人文”论坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-03-22 11:07:26{/dede:field}
{dede:field name='body'}<p>　　3月19日，第二十五期&ldquo;科学&mdash;社会&mdash;人文&rdquo;论坛在人民大学哲学院人文楼6层会议室举办，报告的题目为&ldquo;进化心理学的新进展：我们的过去与现在&rdquo;。论坛由北京师范大学认知精神科学与学习国家重点实验室教授刘嘉担任报告人，由北京大学哲学系教授刘华杰担任评论人，由中国人民大学哲学院教授刘晓力担任主持人。 </p>
<p>　　刘嘉教授首先提出了主要讨论的论题&ldquo;现在行为受从过去至今的进化的影响有多少以及这种影响是否在继续&rdquo;。接下来，刘嘉教授从人类大脑进化开始谈起，介绍了人类行为形成最基本的一点即&ldquo;条件反射&rdquo;这样一种联想式学习，并通过论证得出了人的甚至动物的行为都是为自私的基因所操控的结论，同时他还指出了存在社会基因的传播问题。刘嘉教授讲课通俗易懂，语言平实，举例幽默，除了用文字图形来说明，还辅以视频，让听众能更形象地理解教授的思想。 </p>
<p>　　接下来由北京大学的刘杰华教授进行点评。他幽默风趣，积极质疑，并对以后的研究进行了设想。报告最后由听众提问，大家踊跃发言，并同刘嘉教授进行了深入的、激烈的研讨，用哲学的思维质疑科学的合理性，碰撞出智慧的火花。 </p>
<p>　　这次报告圆满结束，给哲学院的学生以及老师上了一节生动的心理课，拓展了思维，启发了辩证，促进了学术交流。</p>
<p>　　（编辑：安娜）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
