{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院多位校友出席中国空间法学会换届大会并出任该学会重要职务{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-04-12 02:30:47{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月2日，中国空间法学会第三次全国会员代表大会暨第三届理事会第一次会议在北京隆重召开。中国航天科技集团公司副总经理袁家军、袁洁，国家国防科技工业局系统工程一司司长张炜，外交部条约法律司司长黄惠康，国务院法制办工交司司长赵晓光，中国科学院高技术研究与发展局副局长董永初、中国航天科工集团公司总经理助理谢良贵等领导及140名专家学者应邀出席本次大会。大会由法学院2005级校友、中国航天科技集团公司总法律顾问巴日斯主持。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经过大会选举，中国人民大学法学院副院长龙翼飞教授当选为中国空间法学会第三届理事会常务理事，法学院2005级校友巴日斯当选中国空间法学会第三届理事会副理事长，法学院2009届法学硕士张振军当选中国空间法学会第三届理事会常务理事兼秘书长，法学院2010届法学硕士崔桂台律师当选为中国空间法学会第三届理事会理事。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院领导与多位校友此次当选中国空间法学会重要职务，为人大法学院与空间法学研究组织、空间技术研究机构等有关部门和单位之间的联系与合作构筑了渠道和平台，必将进一步推动法学院更好地参与中国航天事业特别是中国航天立法工作。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国空间法学会成立于1997年, 是由国家有关部门和空间法学研究机构、空间科学技术研究和应用机构及空间法学领域专家学者组成的国家一级学术社团组织，是组织开展空间法和空间政策研究及应用活动、开展空间法国际合作与交流、推进外层空间活动法治化建设的重要力量。</p>
<p>（编辑：刘德萍）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
