{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大学生梁文豪夺得亚冬会男子短道速滑500米冠军{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2011-02-09 07:02:32{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在2月1日举行的第七届亚洲冬季运动会男子短道速滑500米决赛中，新闻学院2010级本科学生梁文豪发挥出色，夺得冠军。</p>
<p align="center"><img height="626" alt="" width="500" src="/uploads/allimg/c110419/zlflznzbyb2ylmf-zbmm2.jpg" /></p>
<p align="center">（图片来源：新华社）&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 出生于1992年的梁文豪为中国短道速滑队现役运动员，短道速滑500米世界锦标赛冠军，2010年9月被录取为中国人民大学本科学生。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;媒体链接： <a href="http://sports.sina.com.cn/o/p/2011-02-01/19335438581.shtml">[新华社]男子500米梁文豪夺冠 梦想就在前方</a>（图文）&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://sports.sohu.com/20110130/n279168454.shtml">[新华社]2011亚冬会开幕式 中国队旗手梁文豪</a> （图文）</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://sports.sohu.com/20110202/n279199267.shtml">[人民日报]小将梁文豪夺500米金牌</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://news.163.com/11/0202/12/6RSVBKMA00014AED.html">&nbsp;[北京晚报]中国梁豪气冲天</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://bjyouth.ynet.com/article.jsp?oid=76523560">[中国青年报]梁文豪 &ldquo;接班&rdquo; 李佳军</a> </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）<br />
<br />
</p>
<p>&nbsp;</p>
<p><br />
&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzbyb2ylmf-zbmm2_lit.jpg{/dede:field}
