{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院周珂教授为中央党校全体学员授课{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-02 09:16:34{/dede:field}
{dede:field name='body'}　　3月31日下午，中共中央党校举行了由全体学员参加的学术讲座，人民大学法学院周珂教授讲授做了题为&ldquo;可持续发展与低碳经济法律问题&rdquo;的讲座。这是继曾宪义教授、王利明教授、韩大元教授之后法学院教师第四次为中央党校全体学员授课。讲座受到教师和学员的好评，中共中央党校还邀请周珂教授于下周为学员进行专题的讲座。 <br />
　　（编辑　陈慧茹）{/dede:field}
{dede:field name='litpic'}{/dede:field}
