{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}董克用教授主持课题获得中国工程院和环境保护部表彰{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-02-28 05:29:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在近日举行的&ldquo;中国环境宏观战略研究&rdquo;总结表彰大会上，董克用教授因为&ldquo;表现突出，成绩显著&rdquo;，被中国工程院和环境保护部授予&ldquo;先进个人&rdquo;称号。同时，公共管理学院也被授予&ldquo;先进集体&rdquo;称号。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2007年，公共管理学院院长董克用教授受中国工程院和环境保护部委托，作为首席专家参与了为期3年的&ldquo;中国环境宏观战略研究&rdquo;，并作为子课题负责人主持了&ldquo;中国环境宏观战略研究体制保障子课题&rdquo;研究。环境学院院长马中教授作为核心教授参与该项研究，公共管理学院李文钊老师和环境学院安树民老师作为课题组核心成员为课题做出了重要贡献。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;中国环境宏观战略研究&rdquo;是中国环境领域国家最高层面的研究，着眼于中国未来30年到50年的环境宏观战略探讨，中国工程院原院长徐匡迪和环境保护部部长周生贤亲自主持该研究，国务院副总理李克强多次听取研究成果汇报。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 董克用教授主持的&ldquo;体制保障子课题&rdquo;主要是从宏观战略的高度，着眼于未来50年中国新型环境保护体制的建构。整个研究报告分五个部分，从公共管理的角度思考中国环境管理体制改革和设计问题，核心内容包括：建构中国环境保护体制的分析框架；中国环境管理体制的历史沿革与问题识别；中国环境管理体制改革的背景、必要性和基本挑战；国外环境管理体制改革的经验和教训；中国环境管理体制改革的总体思路，共计13余万字。董克用教授的研究成果，首次从公共管理的理论和视角研究、诊断和设计中国环境管理体制改革，给人耳目一新的感觉，给环境领域的官员、学者和研究人员留下深刻印象。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在参与&ldquo;中国环境宏观战略研究&rdquo;期间，董克用教授领导的课题组也得到了亚洲开发银行的资助，与国外专家一起探讨了经济增长与环境保护的和谐共生问题，并用英文撰写了有关中国环境管理体制的历史与变迁的章节，该英文著作已经出版。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
