{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院成功举办第十二期“青年哲学论坛”报告会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2009-10-15 10:18:32{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月14日下午2点30分，在人文楼6层哲学院会议室，哲学院举办了第十二期&ldquo;青年哲学论坛&rdquo;报告会。报告会在听众们热烈的掌声里拉开帷幕，主持人首先介绍了哲学院青年哲学论坛的设立初衷在于恢复良好的学统，为青年学者提供一个交流和学习的平台，接下来他为大家介绍了本期的主讲人、哲学院骨干青年教师&mdash;&mdash;聂敏里副教授。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在接下来的一个小时的时间里，聂敏里副教授引领听众开始了一段奇妙的旅程。在讲演中，他指出在中西哲学比较上存在着一个基本的错误，这就是将本来属于时间性的文化差异错误地解读为属于地方性的文化差异，西方哲学代表着现代性，而中国哲学则是传统和古代形态的哲学。长期以来，我们将中西哲学置于地方性文化的框架中来予以考察，结果造成了中西哲学乃至中西文化在根本上隔阂和不可沟通。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接下来的时间里，他为听众们介绍了这一错误的历史成因，并进一步讨论了中西哲学各自的普遍的文化特征。在讲解这些问题的同时，他还针对理性、尤其是理论理性和科学理性这一公认为西方文化传统的因素，给出一个特殊的解释。最后，在聂敏里副教授和听众深度的交流之中，本次报告会画上了句点。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据了解，这次的论坛旨在搭建一个对话的平台，让拥有不同学术背景和学术兴趣的哲学思考者就当前的哲学前沿问题进行充分沟通，砥砺学术并且激发思想，增进哲学思考的深度与广度，营建浓郁的学术氛围，这将进一步促进哲学事业的共同发展。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑 丹丽）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
