{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院本科生张琦万元捐助献爱心{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-01-21 05:18:39{/dede:field}
{dede:field name='body'}<p>　　2011年1月17日，经济学院团委收到山东省枣庄市峄城区古邵镇前朱园村村民褚夫涛及家人寄来的感谢信及锦旗一面。来信中说，褚夫涛之子在2010年夏天患上了一种罕见的肺炎，褚夫涛夫妇变卖房子、借遍亲友也无法负担治病的费用。中国人民大学张琦同学在通过媒体得知消息后，连夜赶到山东，向他们捐赠了自己平时积攒和打工所得的一万元钱。褚夫涛及家人特别来信感谢中国人民大学培养了这样一位有爱心、善良的好学生。 </p>
<p align="center"><img height="662" src="/uploads/allimg/c110217/z2mkmlhhl2fknnf-2n2by.jpg" width="500" alt="" /></p>
<p><br />
　　张琦同学是经济学院2008级国民经济管理专业的本科生，思想进步，品学兼优。 </p>
<p>附感谢信：</p>
<p>&nbsp;</p>
<p align="center"><img height="717" src="/uploads/allimg/c110217/z2mkmlhhlhm2flf-lzyyz.jpg" width="500" alt="" /></p>
<p align="center"><img height="717" src="/uploads/allimg/c110217/z2mkmlhhlyyyfkf-hbhhl.jpg" width="500" alt="" /></p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110217/z2mkmlhhl2fknnf-2n2by_lit.jpg{/dede:field}
