{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“中国双赢的能源政策经济学分析”研讨会在环境学院举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-05-26 03:54:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月24日上午，中国人民大学环境学院和哈佛大学肯尼迪政府学院联合课题组在人大环境学院举办研讨会，与中国政府有关部门的决策者及中国有关学术机构的专家就该项目的研究成果展开了交流和研讨。来自科技部、国家发改委、外交部、财政部、环保部、中国清洁发展机制管理基金会、中国电力企业联合会、国家发改委宏观经济研究院能源研究所、科技日报社等单位的政府官员和专家学者出席了会议。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议由科技部全球环境办公室副主任、联合国清洁发展机制执行理事会委员吕学都博士主持。肯尼迪政府学院Teresa and John Heinz环境政策教授、科技与公共政策项目主任John Holdren和中国人民大学环境学院副院长、环境经济与管理系系主任邹骥教授联合向与会者介绍了项目所取得的结果及其政策含义。John Holdren教授还介绍了三位美国总统候选人及部分参议员关于气候变化政策立场的最新动态。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该项目由美国William and Flora Hewlett基金会资助，由来自美国、巴西、印度和中国等四国在环境与能源经济学和公共政策等领域的学者参与，是一个多国联合的国际合作项目。邹骥教授任项目国际指导委员会成员并任中国各参与机构的总协调人。中方参与单位还包括中国科学院热工程物理研究所和中国汽车科学技术发展研究院。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邹骥教授领导的人大课题组主要以燃煤热电部门和汽车制造部门为案例，对相关的技术选择和能源与气候政策进行经济分析。基于该项目所形成的研究成果，邹骥教授进一步将分析延伸到气候政策中的技术开发与转让、行业方法等国际热点问题上，引起了有关决策部门的重视。环境学院吴健副教授、许光清副教授和博士生冯相昭、王海芹，硕士生傅莎、杨宝路、郑露蓉、林殷及本科生岳坤等同学深入参与了该项目的研究工作并形成了若干博士、硕士和学士论文及发表的文章。该项目不但在科学研究和决策支持等方面产生了影响，在人才培养方面也取得了显著的成果。&nbsp;<br />
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：文静）&nbsp;<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
