{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘元春教授就热点宏观经济问题接受媒体采访{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-03-08 04:32:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月4-5日，经济学院副院长刘元春教授分别接受新华社、北京电视台财经频道、广东电视台的采访，就两会讨论的宏观经济热点问题和温家宝总理所做的政府工作报告进行解读。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
