<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","英国纽卡斯尔大学王学峰副研究员访问经济学院",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",212,259);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-24 04:57:24",261,320);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　1月24日上午，英国纽卡斯尔大学城市和区域发展研究中心副研究员王学峰博士访问经济学院。经济学院区域与城市经济研究所所长孙久文教授、经济学院院长助理郑新业副教授、区域与城市经济研究所张可云教授、付晓东副教授，经济学院虞义华博士在明德主楼614会议室与王学峰副研究员进行了座谈。 </p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c110217/z2mkmlhhlm2byyf-ybz2z.jpg\" width=\"500\" alt=\"\" /></p>\r\n<p><br />\r\n　　郑新业院长助理首先代表经济学院杨瑞龙院长对王学峰副研究员的来访表示欢迎。接下来，双方就玛丽&bull;居里行动&mdash;&mdash;国际研究人员交流计划（Marie Curie Action _ International Research Staff Exchange Scheme）的基本内容、合作关系、财务问题、评估标准、实际意义，以及国际人才交流和区域经济学前沿等方面的问题进行了深入的交流和讨论。 </p>\r\n<p>\r\n</p>",322,1118);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110217/z2mkmlhhlm2byyf-ybz2z_lit.jpg",1120,1212);
$z[7][4]['name']="litpic";

?>