<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院举办“碳税的减排效果与经济影响”学术讨论会",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",220,267);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-02-25 08:45:29",269,328);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月6日，经济学院和中国经济体制改革研究会共同举办&ldquo;碳税的减排效果与经济影响&rdquo;学术研讨会。本次研讨会共发表了六篇关于二氧化碳排放方面的研究成果。国家财政部、国家发改委、国家税务总局、电监会的政府官员，清华大学、北京大学、中国社会科学院、华北电大、美国VASSAR 大学、《中国社会科学》杂志社等机构的专家学者，以及经济学院师生30余人参加了讨论会。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzhkhnykhyf-2nllk.jpg\" alt=\"\" /></p>\r\n<p><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，北京大学国际关系学院查道炯教授发表了题为&ldquo;碳排放与全球政治&rdquo;的演讲；中央财经大学财政与公共政策研究院张莉副教授发表了题为&ldquo;中国碳排放：地区与产业视角&rdquo;的演讲；中国人民大学经济学院夏明副教授发表了题为&ldquo;宏观总需求与碳排放&rdquo;的演讲；中国人民大学经济学院张红霞副教授发表了题为&ldquo;碳税与碳排放：产业数据&rdquo;的演讲；中国人民大学经济学院陶然教授发表了题为&ldquo;碳排放：中国的国际策略研究&rdquo;的演讲；中国人民大学经济学院郑新业副教授发表了题为&ldquo;碳税的减排效果及对经济的冲击研究&rdquo;的演讲。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次讨论会上发布的研究成果受到了与会来宾的高度评价。研讨会取得了圆满成功。 </p>\r\n<p>\r\n<br />\r\n</p>",330,1597);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100619/z2kymzhkhnykhyf-2nllk_lit.jpg",1599,1691);
$z[7][4]['name']="litpic";

?>