{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}盛唐国际文化传播有限公司向中国人民大学艺术学院捐款300万元{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-10-28 03:52:07{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月27日上午，盛唐国际文化传播有限公司向中国人民大学艺术学院捐赠仪式在逸夫会议中心贵宾厅隆重举行。中国人民大学常务副校长袁卫、盛唐国际文化传播有限公司董事长高健等领导出席捐赠仪式。中国人民大学教育基金会秘书长彭和平、中国人民大学艺术学院党委书记兼副院长郑晓华、艺术学院常务副院长徐唯辛，学校办公室、艺术学院等相关负责人参加仪式。捐赠仪式由彭和平秘书长主持。 <br />
</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 首先，常务副校长袁卫代表学校对高健女士此次向艺术学院捐赠表示感谢。他指出，艺术的发展对于一个国家的发展十分重要，人文学科的发展不仅仅是教育的发展，还是一个国家战略发展的必要组成部分。他介绍了中国人民大学的发展历史，并阐述了中国人民大学的办学宗旨&ldquo;立学为民、治学报国&rdquo;，以及中国人民大学校徽中三个人字的寓意&ldquo;人民、人本、人文&rdquo;的深刻涵义，希望高健女士作为企业家，能为国家文化的传承、复兴一起努力。这次捐赠是合作的开始，希望能和高健女士在文化领域继续合作下去。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 高健女士认为艺术的传承很重要也很难度。通过参观艺术学院的创作室，她感触很深。她建议应该呼吁社会各界关注艺术学院，关心文化事业的发展，为学生学习创造更好的条件。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 彭和平秘书长赞扬了高健女士作为一个企业家的强烈的社会责任感，以及她对文化教育事业发展做出的贡献。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艺术学院常务副院长徐唯辛代表学院表示一定会合理使用这笔300万元的捐款做好学科建设，不断扩大学院的影响力。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhmzfbznf-zfhnzf.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，三方代表签署捐赠协议。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhmzbknhf-zzmmbm.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 袁卫常务副校长为高健女士颁发捐赠证书和中国人民大学董事会聘书。 </p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhmzfbznf-zfhnzf_lit.jpg{/dede:field}
