{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院严金明副院长应邀出席深圳经济特区建立30周年理论研讨会并做大会发言{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-09-08 04:14:09{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8月22-23日，公共管理学院副院长严金明教授应邀出席深圳经济特区建立30周年理论研讨会，并在大会上做了题为&ldquo;积极探索高度城市化地区土地制度与管理的新模式&rdquo;的发言，新华网、中国新闻网、《南方日报》等媒体均刊发了其发言内容。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhb2ylnlf-zflfzm.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次研讨会由中共中央文献研究室、中共中央党史研究室、《人民日报》社、《求是》杂志社和中共深圳市委、深圳市人民政府联合举办，主题为 &ldquo;经济特区与中国特色社会主义&rdquo;。来自全国各地的百余位专家学者齐聚一堂，全面总结深圳经济特区过去三十年的成功经验，并为下一步的改革发展出谋划策；广东省委常委、深圳市委书记王荣，市长许勤等出席了研讨会。会议期间，严金明教授应邀出席了《改革开放总设计师邓小平大型展览》开幕式，并参观了展览。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhblzlfbf-zznnyz.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在此之前，严金明教授曾作为专家嘉宾参加了中央电视台《对话》节目&mdash;&mdash;&ldquo;特区转型答辩会&rdquo;，并就&ldquo;深圳建设现代化、国际化的先进城市&rdquo;议题与王荣书记进行了交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhb2ylnlf-zflfzm_lit.jpg{/dede:field}
