<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院举行“ECFA后经济合作前景学术研讨会”",89,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","",214,253);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-24 04:51:34",255,314);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　1月13日上午，&ldquo;ECFA后经济合作前景学术研讨会&rdquo;在人民大学明德主楼经济学院0734会议室举行。台湾政治大学社会科学学院副院长、经济系主任莊奕琦教授，台湾政治大学经济系暨&ldquo;国家政策研究基金会&rdquo;科技经济组召集人林祖嘉教授，台湾大学政治系暨&ldquo;国家政策研究基金会&rdquo;内政组召集人蕭全政教授，&ldquo;国家政策研究基金会&rdquo; 科技经济组譚瑾瑜副研究员等一行来校参会。中国人民大学经济学院院长杨瑞龙教授、经济学院方福前教授、李军林教授，经济学院院长助理王晋斌教授、郑新业副教授，经济学院杨其静副教授、谢富胜副教授，经济学院党委副书记丁凯博士等参加研讨会。 </p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c110217/z2mkmlhhlnzbm2f-bhzzl.jpg\" width=\"500\" alt=\"\" /></p>\r\n<p><br />\r\n　　两岸学者就ECFA后两岸经济合作与产业技术合作现况及未来发展趋势等问题进行了深入而热烈的讨论。双方还就建立紧密的互动机制、积极开展合作研究等事宜达成了一致意见。 </p>\r\n<p>\r\n</p>",316,1235);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110217/z2mkmlhhlnzbm2f-bhzzl_lit.jpg",1237,1329);
$z[7][4]['name']="litpic";

?>