{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院郭星华书记为院党校作专题报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院 李晓阳 张浣珺  图 李晓阳{/dede:field}
{dede:field name='pubdate'}2009-04-09 09:34:06{/dede:field}
{dede:field name='body'}<p>　　4月8日下午，社会与人口学院第十期党校第二次讲座举行，院党委书记郭星华教授为全院76名入党积极分子作了题为&ldquo;关于&lsquo;中国特色社会主义&rsquo;的几点思考&rdquo;的专题报告。 <br />
<br />
　　郭星华书记指出，胡锦涛总书记在党的十七大报告中提出高举中国特色社会主义伟大旗帜，坚持中国特色社会主义道路、坚持中国特色社会主义理论体系，中国特色社会主义伟大旗帜是当代中国发展进步的旗帜，是全党全国各族人民团结奋斗的旗帜，党的十七大报告这篇&ldquo;旗帜论&rdquo;回答了当前我们党应该&ldquo;举什么旗，走什么路&rdquo;的问题。中国特色社会主义旗帜经过三十年发展与创新，科学地将马克思主义的基本立场基本方法同中国改革开放的具体实际结合起来，与时俱进，形成了邓小平理论、&ldquo;三个代表&rdquo;和科学发展观重要思想，形成了完整的理论体系，作为社会科学的学习者和研究者广大同学要深刻学习领会，并应用这些理论成果指导自身的学习和工作。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c100622/z2kkzlknbnlfyzf-zyfff.jpg" width="500" alt="" /></p>
<p><br />
<br />
　　报告从&ldquo;中国特色社会主义是马克思主义中国化的继续&rdquo;、&ldquo;中国特色社会主义理论体系是不断发展的&rdquo;、&ldquo;中国特色社会主义是对中国国情的科学认识&rdquo;三个方面对社会主义进行了完整阐述。整个报告从宏观的视角，运用中国特色社会主义理论同社会学理论相结合的眼光，深入分析了中国近代以来中国社会的发展历程，解释了我国在社会主义革命、社会主义建设和改革开放新时期的各种社会政策和问题。报告深入浅出，通过详实的资料和对当今中国和世界的整体局势的探讨为同学们上了生动的一课。 <br />
<br />
　　在提问环节，同学们踊跃发言，就中国特色社会主义下社会学的作用和党在我国整个国家体系中的地位等问题展开了讨论。 <br />
<br />
　　讲座结束后，同学们纷纷表示，听了郭书记的报告受益匪浅，更加坚定了为中国特色社会主义事业奋斗的决心，在日常的学习工作中要更加严格要求自己，争取早日加入党组织。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlknbnlfyzf-zyfff_lit.jpg{/dede:field}
