{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院主办的“日本产业界咨询会”在日本东京成功召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-10-31 08:53:59{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月26日，由环境学院主办的&ldquo;日本产业界咨询会&rdquo;在日本东京成功召开。中国人民大学环境学院邹骥教授一行4人于日本东京与日本产业界人士就环境友好技术的开发与转让问题进行了座谈。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次&ldquo;日本产业界咨询会&rdquo;是环境学院邹骥教授领导的研究团队为开展国家科技部&ldquo;十一五&rdquo;科技支撑项目而设计的一系列咨询会和研讨会的一个组成部分，其成果有望为中央有关部门在气候变化谈判方面的决策提供参考。此外也期望通过这种研讨形式搭建一个政府、企业、研究机构的信息交流平台，探索形成长期的互动合作机制，并最终支持中国政府有针对性地在联合国气候变化谈判中提出符合各方利益的提案。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，中国政府在参加联合国气候变化谈判的进程中，为了在2009年哥本哈根第15次缔约方大会上形成协议，拟提交关于技术转让问题的中国提案，科技部专设&ldquo;十一五&rdquo;科技支撑计划，支持该项议题的研究工作。中国人民大学环境学院邹骥教授领导的研究团队承担了该研究工作。 <br />
<br />
（编辑：刘恒） <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
