{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大徐唯辛教授油画作品在瑞士展出 中国驻瑞大使出席开幕式{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2009-11-19 04:39:54{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月13日，中国人民大学艺术学院副院长徐唯辛教授油画作品参加在瑞士瓦莱州立博物馆举行的题为《劳动者》的油画作品展。中国驻瑞士大使董津义、文化参赞李克明、前瑞士联邦主席库什潘、瑞士瓦莱州州长、清华大学副校长汪劲松等嘉宾以及400多位瑞士各界人士出席了当天的开幕式。</p>
<p align="center">&nbsp;<img height="281" alt="" width="500" src="/uploads/allimg/c110725/zlzzbyzhnflyfmf-lmnlbk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font size="1">图片说明：前瑞士联邦主席库什潘（左三）、瓦莱州州长（右一）、中国驻瑞士大使董津义（左四）、文化参赞李克明、清华大学副校长汪劲松（左二）、徐唯辛教授（右三）</font> </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该展展出了中国人民大学艺术学院教授徐唯辛和清华大学美术学院教授王宏剑、忻东旺的油画作品30余幅。3位艺术家均为国内具像写实绘画领域的代表人物，在国内屡获大奖。他们的笔触不约而同地伸向社会底层，记录了中国经济崛起背景下的当代农民打工者和工人的奉献精神和生存状态，同时也展示了中国学院艺术家对社会的关注以及精湛的艺术造诣。徐唯辛教授此次展出的作品以矿工肖像为主，在传统油画写实技法中融入了现代视觉观念，其强烈的视觉冲击力彰显了画家深厚的人文精神和社会责任感。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 展览受到瑞士各界的关注。瑞士瓦莱州立博物馆为画展作了招贴，3位艺术家的作品在瑞士各大城市街头展示，瑞士国家电视台、瓦莱州电视台等当地媒体对画家进行了采访报道。 </p>
<p align="center">&nbsp;<img height="281" alt="" width="500" src="/uploads/allimg/c110725/zlzzbyzhnfkyz2f-hfybmk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 展览期间，展览主办方还为3位艺术家安排了同观众进行交流互动以及在瓦莱州立大学进行学术交流等活动。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 预计展览到明年2月结束。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhnflyfmf-lmnlbk_lit.jpg{/dede:field}
