<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国宏观经济论坛第四季度报告受到上级部门高度关注",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",218,265);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由中国人民大学经济学院副院长、经济研究所联席副所长刘元春教授等人共同主持完成的&ldquo;中国宏观经济论坛&rdquo;第四季度报告《共识中的变数：理解2010年中国宏观经济的几个要点》 ，由中宣部社科规划办以&ldquo;成果要报&rdquo;的形式报送上级机关。报告得到国务院、银监会等相关部门领导的高度重视，并做了批复。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",267,686);
$z[5][4]['name']="body";
$z[6]=Array("field","1267994111",688,738);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",740,779);
$z[7][4]['name']="litpic";

?>