{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京市统计局、国家统计局北京市调查总队领导到统计学院座谈{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2007-03-08 06:23:06{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp;&nbsp; 3月7日下午，北京市统计局和国家统计局北京调查总队八位局级领导及随行人员在局长崔述强和总队长潘璠的率领下来到统计学院，与常务副校长袁卫、科研处处长杜鹏、统计学院院长金勇进、书记王晓军等举行座谈。</P>
<P align=center><A><IMG src="http://images.ruc.edu.cn/bximages/col18/07381654.jpg" align=" " border=0></A>&nbsp;　　</P>
<P>&nbsp;&nbsp;&nbsp; 北京市统计局是统计学院的实习基地，多年来，在人才培养和科学研究方面一直保持着密切的合作关系。会谈中双方相互感谢了对方多年来一贯的支持，进一步讨论了今后深入交流与合作的具体计划。具体商定从2007年起，北京市统计局每年接受人大相关院系1-2名教师在合适的岗位上挂职，与人大相关院系合作开展有关首都建设、特别是大都市统计建设的科研项目，与国际上几个大都市的统计部门建立联系，开展关于大都市统计的国际研讨会等。 　　</P>
<P>&nbsp;&nbsp;&nbsp; 崔局长希望北京市统计局能够为人民大学各相关院系所的师生服务，实实在在的成为人民大学在教学、科研、人才培养方面的基地。袁卫常务副校长对北京统计局多年来的支持表示感谢，希望双方能够本着务实的精神加强沟通、深化合作，为我国的统计事业，特别是大都市统计的发展做出更大的贡献。 <BR>　　 <BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
