{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院举办第四期学生团校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月27日至11月10日，经济学院团委举办了第四期学生团校。本期团校分为三讲，分别由中国人民大学团委书记费佳、校团委副书记李建希和青年人大编辑张程主讲。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhbyfmkkf-llzhh.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 费佳老师以学生干部与学生活动为主题，根据自己多年从事学生活动的经验，向与会同学介绍了学生干部的性质、分类、目的，简单提出了几点对学生干部的要求。同学们从费佳书记的话中获益良多，现场掌声连连。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhbymzylf-h22nk.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李建希老师着重强调了八个关系：学习与学生工作的关系、整体与细节的关系、理想与现实的关系、过程与结果的关系、做学生干部利与弊的关系，竞争与合作的关系，为人与处世的关系，得与失的关系。李建希老师精彩的发言博得了满堂喝彩。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhbkzmykf-bmnlf.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张程同学主讲人物采访。她向与会同学详细地阐述了人物采访前期注意事项、采访技巧以及采访稿的书写。最后，同学们纷纷提问实际采访中碰到的问题，张程同学也一一耐心解答。通过此次培训，同学们都感到受益匪浅。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 学生团校在提高经济学院学生干部的综合素质，更好地开展学生活动，丰富广大同学的课余生活等方面都发挥了重要的作用，得到了同学们的欢迎和好评。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1289856007{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhbyfmkkf-llzhh_lit.jpg{/dede:field}
