{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国蒙特雷国际研究院国际政策和管理研究生院院长访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-11-12 10:57:02{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月10日，美国蒙特雷国际研究生院（MIIS）国际政策与管理学院院长施瑜玮教授及该院研究生事务主管Toni Thomas和Devin Lueddeke访问经济学院，经济学院院长杨瑞龙教授会见了蒙特雷学院一行。经济学院副院长刘元春教授，程大为副教授、范志勇副教授和党委副书记丁凯等陪同会见。 </p>
<p align="center"><img height="335" src="/uploads/allimg/c101124/z2mfbmzhhynnnf-kzhfn.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 目前，经济学院与蒙特雷国际研究生院均致力于培养能够解决当今世界经济关键问题的高端人才，并且都预见到中美两国乃至全球对高水平、国际化、同时熟悉公共机构和私人部门运作的国际商务专门人才的需求。经济学院拟与蒙特雷学院就我校新设立的国际商务硕士（MIB）的联合培养、海外实习等方面开展合作。会见中，双方回顾并确立了前期谈判过程中达成的共识，并就合作方式、奖学金项目、实习项目、双学位项目、教师互访和合作研究等问题进行了深入讨论。双方还就奖学金名额、学期安排、课程设置、学分互认等事宜进行了反复讨论，力图为进入合作项目的学生设计出一套有吸引力、可行性强、方便实施的联合培养方案。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会见结束后，施瑜玮院长一行与经济学院MIB项目的骨干教师在明德主楼729会议室进行了座谈，座谈会由刘元春副院长主持。刘元春副院长向来宾简单介绍了经济学院MIB项目的师资力量。施瑜玮院长结合蒙特雷学院办学和教学情况，就案例教学、课程设置以及对学生在实习环节的有效指导等方面做了介绍。经济学院MIB项目的教师积极参与了讨论，气氛热烈而融洽，大家纷纷表示获益良多。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhhkklnkf-nznm2.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当日上午，经济学院还特意安排了施瑜玮院长一行与学生的见面会。施瑜玮院长为学生们做了题为Some New Trends in Business and Management Education的讲座，两位研究生事务主管也为学生详细介绍了蒙特雷国际研究生院对申请者的要求和待遇，学生们反响热烈。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 美国蒙特雷国际研究院成立于1955年，是一所以培养高层次专业人员为主的研究生学校。2005年，它成为了美国佛盟特州明德学院（Middlebury College）的联盟成员。2009年，该校原有的四个学院：费希尔国际商业学院、国际政策研究学院、高级翻译学院、语言与教育学院整合成为国际政策和管理与翻译、口译和语言教育两个学院。施瑜玮教授出任国际政策和管理学院的院长。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhhynnnf-kzhfn_lit.jpg{/dede:field}
