{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院学者荣获北京市第十一届哲学社会科学优秀成果奖多项{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 日前，北京市第十一届哲学社会科学优秀成果奖经北京市评奖委员会全体会议审核通过并公示完毕。此次共评出特等奖一项，一等奖39项，二等奖169项，评奖范围限2007年7月至2009年6月底期间发表的哲学社会科学研究成果。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经济学院方福前教授的论文《中国居民消费需求不足原因研究》（《中国社会科学》2009年3月第2期）荣获一等奖；刘元春教授的专著《中国通货膨胀成因的研究》（中国人民大学出版社2008年11月版）和黄隽教授的论文《商业银行竞争、效率及其关系研究&mdash;&mdash;以韩国、中国台湾和中国大陆为例》（《中国社会科学》2008年1月第1期）荣获二等奖。 </p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='pubdate'}1288558473{/dede:field}
{dede:field name='litpic'}{/dede:field}
