{dede:noteinfo notename="新闻—人大艺术学院" channelid="1" macthtype="string"
	refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl=""
startid="1" endid="" addv="1" urlrule="area" musthas=""
 nothas="" listpic="0" usemore="0"}
	{dede:addurls}http://news1.ruc.edu.cn/102449/102450/102502/list.html{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<table width="743" cellspacing="1" bgcolor="#CACCCE">{/dede:areastart}
	{dede:areaend}</table>
<table width="100%"><tr><td align=right>        
    <div class="page"{/dede:areaend}
{/dede:listrule}
