{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}程天权书记视察经济学院并祝贺新年{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-01-27 03:11:10{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月27日上午，程天权书记到经济学院视察，亲切慰问学院教职员工，并向大家致以新年祝福。经济学院院长杨瑞龙、党委书记张宇、校办副主任李家福等陪同。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c100619/z2kymzhklm2hlhf-znlzk.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记详细询问了经济学院研究生招生、经济学－数学双学位实验班、学术期刊建设、中国宏观经济论坛等方面的情况，杨瑞龙院长一一做了详细回答。程天书记还与经济学院负责人就能源经济学和城市发展等学术问题进行了讨论。程天书记希望经济学院能够继续办好中国宏观经济论坛，多出高质量、高水平的研究成果，为国家经济建设和社会发展提供智力支持，当好智库；加大对学生课外学术实践活动的支持力度，培养高层次的优秀人才；要格外关心留校过春节的学生，做好相关安排，组织丰富多彩的活动，让他们在学校也能过个好年。最后，程天书记还饶有兴致地参观了经济学院教师年终教学科研量考核的统计榜。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhklm2hlhf-znlzk_lit.jpg{/dede:field}
