{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}台湾中山大学公共事务管理研究所MPA师生代表团访问公共管理学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-11 09:55:57{/dede:field}
{dede:field name='body'}<p>　　3月31日下午，台湾中山大学公共事务管理研究所所长汪明生教授率该所MPA师生代表团访问公共管理学院。公共管理学院院长、全国MPA教育指导委员会秘书长董克用教授和校国际交流处港澳台交流科马琰老师会见了客人，公共管理学院副院长蓝志勇教授，副院长、MPA教育中心主任许光建教授和MPA教育中心办公室主任王春老师等师生代表参加了会谈。</p>
<p>　　会谈期间，董克用院长向代表团表示欢迎，并介绍了大陆公共管理领域的研究探索情况以及公共管理学院的发展历程和现状；汪明生所长介绍了台湾中山大学公共事务管理研究所的学科特色和发展规划，希望能以此次访问为契机，进一步深化包括学生交流、学者交流、合作研究在内的形式灵活的多方面合作。</p>
<p>　　会谈结束后，公共管理学院副院长蓝志勇教授主持了由公共管理学院MPA研究生和台湾代表团共同参与的案例研讨课。海峡两岸MPA研究生们就两岸的社会管理、社会保障、住房、教育、地震应急等问题展开了热烈交流和讨论。通过研讨，两校公共管理硕士（MPA）对两岸社情、民情有了更深入的了解，为今后进一步的交流合作奠定了基础。</p>
<p>　　（编辑：苏璇）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
