{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院青年志愿者协会举办“浇灌爱”阳光义卖活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-31 02:57:02{/dede:field}
{dede:field name='body'}<p>　　3月27、28日，法学院青年志愿者协会携手西城区培智中心学校，在学生活动中心门前成功开展了&ldquo;浇灌爱&rdquo;阳光义卖活动，进行爱的传递。 </p>
<p>　　周末，沐浴在阳光下的义卖作品迎风飘扬，引来无数行人驻足观赏。本次的义卖品全部由西城区培智中心学校的残障儿童亲手制作，形式多样、内容丰富，蜡笔画、剪纸、小手工制作、精美的瓷盘等，应有尽有。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylbhynflf-2m2bf.jpg" /></p>
<p>　　当听到这些充满想象力和阳光气息的作品都是由可能患有严重自闭症的智障儿童一点一点制作出来的后，许多好心人士被培智中心的儿童们的那份坚强和乐观所感动。大家不仅争相购买义卖作品，更是写下了自己对培智中心小朋友的真诚祝福，希望这些聪慧的孩子们能永远快乐。更值得一提的是，每幅义卖作品的背后都留下了作者小朋友的亲笔签名及他们的基本信息，同时每份作品的买主也都留下了自己的联系方式&mdash;&mdash;让宝贵的爱能一直延续下去，永不降温，这也正是这次活动的意义所在。 </p>
<p>　　北京市西城区培智中心学校自1981年开始接收智力残障儿童入学，是全国最早为智力残疾儿童提供特殊教育的学校。学校在&ldquo;挖掘潜能、差异发展、服务生活、着眼未来，让每个人都有尊严地生活&rdquo;的办学理念指导下，致力于智力残疾学生的教育、康复、训练等多方面的实践和研究，赢得了社会各界的赞誉。 </p>
<p>　　中国人民大学法学院青年志愿者协会携手残疾人权益保障法律研究与救助中心一直致力于残疾人权益保障事业，与培智学校建立起了各种合作关系。春天已至，阳光普照，法学院的青年志愿者们希望助残爱心能够通过这次&ldquo;浇灌爱&rdquo;阳光义卖活动更广泛的传递下去，让更多的残疾人小朋友沐浴在爱的阳光之下。 </p>
<p>　　（编辑：於萍萍）<br />
</p>
<p>&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylbhynflf-2m2bf_lit.jpg{/dede:field}
