{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国贝茨大学Ganesh Trichur副教授为经济学院学生讲授专业课{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应经济学院邀请，美国贝茨大学Ganesh Trichur副教授来校为经济学院2008级国经贸专业本科生讲授《东亚经济与中国经济》的专业课，为期三个月，每周2个小时，2个学分。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为落实学校&ldquo;十年腾飞&rdquo;学科发展规划和学校《全面提升国际性行动计划纲要》的有关精神，经济学院拟在几年内引进、聘请优秀海外教师来校使用外语为学生讲授专业课程。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1285697913{/dede:field}
{dede:field name='litpic'}{/dede:field}
