<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","美国贝茨大学Ganesh Trichur副教授为经济学院学生讲授专业课",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",226,273);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应经济学院邀请，美国贝茨大学Ganesh Trichur副教授来校为经济学院2008级国经贸专业本科生讲授《东亚经济与中国经济》的专业课，为期三个月，每周2个小时，2个学分。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为落实学校&ldquo;十年腾飞&rdquo;学科发展规划和学校《全面提升国际性行动计划纲要》的有关精神，经济学院拟在几年内引进、聘请优秀海外教师来校使用外语为学生讲授专业课程。 </p>\r\n<p>\r\n</p>",275,750);
$z[5][4]['name']="body";
$z[6]=Array("field","1285697913",752,802);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",804,843);
$z[7][4]['name']="litpic";

?>