{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院董克用院长应邀参加全国行政机关公务员培训工作会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 03:07:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月13日，国家公务员局培训与监督司在北京会议中心召开全国行政机关公务员培训工作会议。国家公务员局党组书记、副局长杨士秋，国家公务员局党组成员、副局长吴云华，中组部干部教育局副局长王新堂等领导出席会议。会上杨士秋副部长做了&ldquo;推进公务员培训科学发展，建设以人为本执政为民的公务员队伍&rdquo;的重要讲话。公共管理学院董克用院长作为特邀嘉宾参与会议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
