{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}香港浸会大学代表团访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/港澳台办公室  图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-01-10 09:59:49{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月6日上午，香港浸会大学校长陈新滋教授率团访问人民大学。人民大学校长纪宝成、副校长杨慧林在逸夫会堂会见了代表团一行。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪校长对代表团的来访表示热烈欢迎。纪校长向客人们简要地介绍了人民大学的历史发展、学科特色和对外交流情况。他表示，人民大学在人文社会科学领域处于国内领先地位，希望双方在相关学科深入交流，在学生交换等领域拓展双方的合作。 </p>
<p align="center"><img alt="" width="531" height="333" src="/uploads/allimg/c110113/z2mhnn2m2mbkbyf-kzlyl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈新滋校长表示，中国人民大学是一所有着光荣历史传统并富有时代特色的著名大学。长期以来，两校保持着密切的交往。希望双方在学生交换、学生联合培养等方面进一步开展合作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，两校相关院系的负责人就具体合作事宜进行了商谈。 </p>
<p align="center"><img alt="" width="531" height="333" src="/uploads/allimg/c110113/z2mhnn2m2mmhlmf-nlz2m.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学新闻学院常务副院长倪宁、文学院院长孙郁、港澳台办公室主任唐忠教授以及国学院、理学院、社会与人口学院等学院的负责人陪同会见。</p>
<p align="center"><img alt="" width="531" height="333" src="/uploads/allimg/c110113/z2mhnn2mlffz2yf-m2yfb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟&nbsp; 思颖） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2mbkbyf-kzlyl_lit.jpg{/dede:field}
