{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2fmlzbz.jpg' text='中国人民大学东门' width='450' height='291'} /uploads/allimg/100612/2-zffyz2fmlzbz.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2fml2ll.jpg' text='中国人民大学东门' width='450' height='338'} /uploads/allimg/100612/2-zffyz2fml2ll.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2fmlhbh.jpg' text='中国人民大学东门' width='420' height='296'} /uploads/allimg/100612/2-zffyz2fmlhbh.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2fmlnbb.jpg' text='中国人民大学西门' width='450' height='338'} /uploads/allimg/100612/2-zffyz2fmlnbb.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2fmhbzl.jpg' text='中国人民大学西门' width='450' height='338'} /uploads/allimg/100612/2-zffyz2fmhbzl.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2fmhbzk.jpg' text='中国人民大学西门' width='450' height='349'} /uploads/allimg/100612/2-zffyz2fmhbzk.jpg {/dede:img}
