{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}党委常务副书记、纪委书记牛维麟参加教育部直属高校纪委书记座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}纪委办公室{/dede:field}
{dede:field name='pubdate'}2011-03-30 02:34:04{/dede:field}
{dede:field name='body'}<p>　　3月28日至29日，人民大学党委常务副书记、纪委书记牛维麟参加了教育部直属高校纪委书记座谈会，并就如何进一步加强基建工程监督工作，有效防范工程领域廉政风险问题提出工作建议。 </p>
<p>　　此次座谈会由教育部纪检组、监察局召集，中央纪委驻教育部纪检组组长王立英主持，北京大学、中国人民大学等26所部属高校纪委书记参加。会议期间，各高校纪委书记围绕如何破解高校反腐倡廉建设重点难点的工作举措及适应新形势新情况的工作方法进行了深入探讨。 </p>
<p>　　（编辑：易晨）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
