{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙教授应邀到全国政协发表演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为认真落实中央精神，全国政协经济委员会于11月10日召开&ldquo;积极调整国民收入分配结构，深化收入分配制度改革&rdquo;专题研讨会。经济学院院长杨瑞龙教授应邀在会上做了专题演讲。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙教授在演讲中，就农民工工资上涨所引发的农民工工资形成机制变革，及其对我国收入分配结构、经济结构调整所产生的效应及变革意义进行了深入而生动的阐释。演讲引起了与会者的极大兴趣，他们对杨瑞龙教授的观点给予了高度的评价。杨瑞龙教授还就相关问题和与会者进行了深入讨论。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王宝奎；核稿：丁凯)</p>{/dede:field}
{dede:field name='pubdate'}1289530882{/dede:field}
{dede:field name='litpic'}{/dede:field}
