<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","美国密苏里大学哥伦比亚分校副教务长一行访问中国人民大学",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","国际交流处",224,273);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月11日下午，中国人民大学副校长杨慧林教授会见了来访的美国密苏里大学哥伦比亚分校副教务长翰迪&bull;威廉姆森(Handy Williamson)教授一行。陪同来访的还有该校国际事务主任Wen Ouyang女士。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨慧林副校长首先威廉姆森教授一行的到来表示欢迎。他向客人介绍了人民大学的学科特色和国际化发展战略，特别强调希望通过国际小学期及全英文硕士项目吸引更多来自密苏里大学的师生，并积极拓展两校间教师互访、学生交流、以及合作科研等多层次的交流与合作。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 威廉姆森教授介绍了密苏里大学的特色学科，希望在两校均有较强科研实力的学科，如农业经济学、新闻学、商学等方面开展深入合作。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 商学院副院长毛基业教授、新闻学院院长助理雷蔚真副教授、国际交流处副处长程鑫参加了会谈，并分别介绍了各自学院的情况和主要国际合作项目。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 密苏里大学成立于1839年，拥有全球第一家新闻学院。该校共有四所分校，分别是哥伦比亚分校、罗拉分校、堪萨斯分校和圣路易斯分校，其中，哥伦比亚分校学术科研水平最高，素有&ldquo;公立常春藤名校&rdquo;的美誉。该校的农学院、工学院与传播学院的学术成就闻名全球。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />\r\n</p>",275,1630);
$z[5][4]['name']="body";
$z[6]=Array("field","1289505698",1632,1682);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1684,1723);
$z[7][4]['name']="litpic";

?>