{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本电通广告公司代表团访问中国人民大学新闻学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院  文\ 裴峥  图\陈凯茵{/dede:field}
{dede:field name='pubdate'}2010-09-19 11:17:42{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月17日上午，日本电通公司代表团在教育部国际司亚非处、国际留学生基金委欧亚非事务部、学校国际交流处工作人员的陪同下，来中国人民大学新闻学院访问交流。新闻学院党委书记高钢会见了来访宾客，学校国际交流处副处长石佳友、学院院长助理雷蔚真、办公室主任甘光千，以及曾经和将要参加电通合作项目学习交流的杨钢元老师、王润泽老师、丁汉青老师、王菲老师、王树良老师、黄河老师出席。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbmff2nf22hf-zyhzf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 高钢书记首先对代表团的来访表示了热烈欢迎，并向客人们介绍了新闻学院基本情况，表示电通广告公司与我国学习合作的良好关系，希望双方能够继续拓宽学术交流通道。教育部国际司亚非处吴劲松处长介绍了&ldquo;电通中国广告人才培养基金项目&rdquo;的情况。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 电通公司冈崎先生说：&ldquo;在我们眼里，人民大学是一所随时代发展，既有历史又有朝气的大学。我们很高兴能有合作的机会。自1996年起，人民大学先后有16位老师到日本东京参加研修项目，这在我们公司交流活动历史上是最多的。希望贵校今后会有更多的老师参加这个项目。&rdquo; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，来访者与师生们进行了交流，曾经到过东京电通总部研修的老师们讲述了当年在日本的学习与生活情景。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 日本电通公司是全球最大的综合性广告公司、全球五大传播集团之一，以创意能力见长。早至1996年，电通公司就开始对中国高校的广告教育和人才培养提供支援，许多进入&ldquo;培养基金&rdquo;项目的教师已经成为广告教育界的权威人士。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）</p>
<p>&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmff2nf22hf-zyhzf_lit.jpg{/dede:field}
