{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院副院长刘元春教授就中国宏观经济问题出席系列活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近期，经济学院副院长、经济研究所联席副所长刘元春教授就中国宏观经济问题出席系列活动。11月21日，刘元春教授应邀出席&ldquo;上海国际发展论坛&rdquo;，并作了《未来30年经济增长展望》的主题发言。 11月22日，刘元春教授应中央电视台新闻频道邀请，介绍目前宏观经济与房地产的关系。11月26日，刘元春教授应中央电视台国际频道邀请，解读目前国际资本流动情况。</p>
<p>（编辑：王宝奎）</p>{/dede:field}
{dede:field name='pubdate'}1259866284{/dede:field}
{dede:field name='litpic'}{/dede:field}
