{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2000年诺贝尔经济学奖获得者McFadden教授访问人民大学并发表学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-01-18 11:05:29{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月15日上午，2000年诺贝尔经济学奖获得者、加州大学伯克利分校计量经济学实验室主任麦克法登教授（Daniel L McFadden）访问人民大学。中国人民大学副校长陈雨露教授在明德主楼1409会议室会见了麦克法登教授，经济学院院长杨瑞龙教授、院长助理郑新业副教授以及王湘红副教授等陪同。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhkzkml2mf-h22kk.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈雨露副校长向麦克法登教授介绍了人民大学的校史和在学科建设、学生培养等方面取得的成绩，他还重点介绍了人民大学经济学－数学双学位实验班的举办情况，并向麦克法登教授推荐了人民大学的优秀学子。麦克法登教授高度赞扬了人民大学近年来取得的成绩，并特别强调了经济学－数学双学位实验班在人才培养中的重要意义。他还介绍了美国加州大学伯克利分校经济政策研究中心利用实验方法进行经济学研究的经验。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhk2flbyf-by2l2.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会见前，麦克法登教授在王湘红副教授和郑新业副教授等的陪同下参观了中国人民大学经济组织与经济行为实验室。麦克法登教授表示实验室的硬件条件非常好，设施配备齐全；人民大学学者等所进行的研究工作非常有意义，应该继续努力下去。他还对实验室的进一步发展提出了建议。</p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhk222hhzf-y2n22.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 访问期间，麦克法登教授在杨瑞龙院长的陪同下，参观了经济学院院史展，他充分肯定了经济学院近年来在学科建设、人才培养和社会服务等方面所取得的成绩。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhk2knm2mf-khblz.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，麦克法登教授在经济学院世纪经英讲坛上发表了题为REGULATION OF PRIVATE HEALTH INSURANCE MARKETS 的学术演讲。经济学院院长杨瑞龙教授出席演讲会，演讲会由王湘红副教授主持。郑新业副教授、陶然教授、章艳红副教授、孙文凯博士、虞义华博士等参加了演讲会。麦克法登教授就健康保险市场的规范与管理等方面的问题进行了阐述，并与现场经济学院的师生们进行了深入交流。 <br />
<br />
演讲人简介： </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhk2mnmfyf-nlnhl.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 丹尼尔&bull;麦克法登（Daniel L McFadden）1937年生于美国北卡罗来那州的瑞雷(Raleigh, NC)，在明尼苏达大学 (University of Minnesota)物理系获得学士学位后改念经济，1962 年于同校获得博士学位。曾在匹兹堡大学、耶鲁大学、麻省理工学院、和柏克莱加州大学任教，1990年后是柏克莱加州大学的讲座教授，现为加州大学伯克利分校经济学教授和计量经济学实验室主任。 <br />
　　他的研究领域包括：计量经济学及经济学理论。研究课题包括：隐含变量模式、选择模式及应用、大规模抽样计量经济学、抽样理论、经济生产理论、消费理论、老龄化趋势经济学、储蓄行为，人口统计学趋势、住房流动性、健康和死亡比例研究、利用计量心理学数据进行的消费者需求分析以及计量经济学模拟方法研究。2000年以&ldquo;对分析离散选择的原理和方法所做出的发展和贡献&rdquo;而获诺贝尔经济学奖。 <br />
　　麦克法登最主要的贡献在于，对诸如不同交通工具或不同职业等的&ldquo;类别选择&rdquo;(Discrete Choices) 问题上，发展出一套完整的理论和实证方法。和赫克曼一样，麦克法登也很擅长于将经济理论和计量方法紧密结合起来，并将之应用到许多不同领域 (例如生产经济理论、运输经济学、环境经济学等) 的实证研究中。在一九七零年代以前， 经济理论和计量经济学的分析都局限于数值连续的经济变数 (像消费、所得、价格等) ，类别选择的问题虽然是无所不在，传统上却没有一个严谨的分析架构，麦克法登填补了这个空隙，他对类别选择问题的研究在很短的时间内就发展成为一个新兴领域，大大的扩充了经济理论和计量经济学的范围和适用性，许多其他社会科学的学门也因此获得一个十分有用的实证研究工具。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkzkml2mf-h22kk_lit.jpg{/dede:field}
