{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院举行毕业生座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2009-04-20 10:26:04{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月15日下午，外国语学院本科毕业生座谈会在明德国际楼0501室举行。会议由外国语学院党委副书记齐畅主持，外国语学院团委书记商竞参加了此次会议。会议主要讨论了2005级本科毕业生就业困难的问题。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 党委副书记齐畅和团委书记商竞针对每个就业困难学生的不同情况，具体问题具体分析，给出了详细和有效的解决意见。团委书记齐畅表示，在全球金融危机的大背景下，外国语学院的就业形势仍然是相当良好的，鼓励就业困难的学生调整心态，振作信心，充分吸取自己的和别人的经验，实现学生间的就业信息资源共享，并祝愿就业困难学生能够尽快找到自己适合的工作岗位。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次会议充分显示了学院对学生的关心。齐畅副书记表示，此次会议的召开，不仅帮助了2005级的学生尽快解决就业问题，而且有利于学院了解学生在就业中遇到的具体问题，为后来者积累经验，增加学院的就业率，加强学院建设。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
