{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院首期金融学博士论坛成功开讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财金金融学院{/dede:field}
{dede:field name='pubdate'}2010-04-22 09:30:05{/dede:field}
{dede:field name='body'}<p>　　4月20日下午，中国人民大学财政金融学院金融学博士论坛第一讲在明德主楼509会议室成功举办。首期主讲人为财政金融学院2009级博士研究生，现任中国银行股份有限公司风险管理部副总经理兼新巴塞尔协议办公室主任张守川。 </p>
<p>　　主讲人以新巴塞尔协议在我国商业银行的实践及其效果为主题，作了一次理论与实践相结合的精彩演讲，参会博士生绕论坛主题展开了热烈而充分的讨论。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlkhyylfmzf-zfnmkb.jpg" width="500" height="333" alt="" /></p>
<p>　　本次博士论坛是在财政金融学院副院长何平教授的大力倡导和积极组织下举办的，论坛旨在促进学术交流、加强相互协作，启迪创新思维，搭建良好的学术互动平台。金融博士论坛将定期举行，并逐步将其办成博士生学术交流的盛会。 </p>
<p>　　（编辑：苗育婧） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlkhyylfmzf-zfnmkb_lit.jpg{/dede:field}
