{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}校医院在经济学院举办“家庭保健员培训班”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月9日至11日，校医院在经济学院举办了为期三天的&ldquo;家庭保健员培训班&rdquo;。培训班由校医院院长助理张冬梅大夫、保健科董华大夫和王南晔大夫主讲，经济学院杨瑞龙院长、明占生副书记、丁凯副书记及十余位教职员工参加了培训。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhyn2fybf-zhnbk.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张冬梅大夫介绍了家庭保健员计划的重要意义和详细内容，并向大家讲解如何综合防治慢性病等知识。董华大夫讲解了如何保持身体健康和心态平和，以及一些常见病的防治。王南晔大夫则重点向大家讲解了冠心病的防治和急救的方法。参加培训的老师都签署了家庭保健员承诺书，并填写回答了慢性病防治知识问卷。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 结业仪式上，杨瑞龙院长认真听取了校医院专家的讲解，并表示学习保健知识具有重要的现实意义，特别是对于长时间从事研究工作、缺乏锻炼的老师更是有指导作用，希望大家要认真学习。 </p>
<p align="center"><img height="334" src="/uploads/allimg/c101124/z2mfbmzhymf2hnf-2llyl.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，参加培训的老师们全部通过了结业考试，校医院向他们授予了《北京市慢性病防治家庭保健员合格证书》。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1290022490{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhyn2fybf-zhnbk_lit.jpg{/dede:field}
