{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}清华大学教授王宁应邀到外国语学院做学术报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2008-11-24 08:39:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月19日下午，来自清华大学外语系的博士生导师王宁教授在中国人民大学明德国际楼做了题为&ldquo;比较文学的危机和世界文学的兴盛&rdquo;的学术报告。此次报告会吸引了众多学生和老师。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告会开始，中国人民大学外国语学院英语系的陈世丹教授做了开场白，并隆重介绍了王宁教授。身为英语语言学专业博士点第一带头人兼首席导师的王宁教授著作颇丰，对比较文学研究有着深刻的见解。王宁教授讲到，比较文学的危机体现在其研究领域日益狭窄；而此方面的专家学者大多具备多学科知识，精力难免分散，这也和比较文学的危机有一定关联。在论及世界文学和比较文学的关系时，王教授总结道：&ldquo;比较文学的早期阶段是世界文学，它也必将回归到世界文学。&rdquo;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，学术报告会在王宁教授和在场听众的交流中结束。</p>
<p>（编辑：陈相宜）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
