{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}谢菲尔德大学法学院Morgan教授在法学院举办留学交流会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-29 10:29:22{/dede:field}
{dede:field name='body'}<p>　　3月24日下午，谢菲尔德大学（University of Sheffield）法学院的Morgan教授和周奇博士来到明德法学楼602，和法学院学生就留学项目展开交流。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylh2bzbkf-hkbnz.jpg" /></p>
<p>　　Morgan教授首先介绍了谢菲尔德大学的概况。谢菲尔德大学是英国6所最佳研究型大学之一，并且是英国最受海外学生欢迎的5所大学之一。经过一百多年的发展，谢菲尔德大学在教学与研究方面建立起卓越了的声誉。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100619/z2kymzylhl2bkhf-bmbzz.jpg" /></p>
<p>　　接下来，Morgan教授重点介绍了谢菲尔德大学法学院目前开展的针对留学生的英文法律课程，包括针对本科生、研究生和成人的不同项目。并且进一步介绍了课程的内容、所需花费、取得学位情况等细节问题。之后，周奇博士结合自身的留学经验，根据同学们的具体情况对各个项目做了有针对性的分析。 <br />
<br />
　　最后，Morgan教授和周奇博士解答了大家关于留学问题的疑惑，并与到场同学合影留念，交流会在轻松友好的氛围中落下帷幕。</p>
<p>　　（编辑：於萍萍）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylh2bzbkf-hkbnz_lit.jpg{/dede:field}
