{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}程天权书记出席中关村科学城项目进展情况汇报会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文化科技园{/dede:field}
{dede:field name='pubdate'}2011-01-10 02:35:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月9日，程天权书记亲自出席在北京航空航天大学唯实大厦举行的中关村科学城项目进展情况汇报会并与北京市主管领导充分交流沟通。会议由北京市政府戴卫副秘书长主持，市委常委、海淀区委书记、中关村科技园区管理委员会党组书记书记赵凤桐,副市长苟仲文，市委副秘书长李福祥，各相关委办局负责人，中关村科技园区管理委员会领导以及中关村科学城第一、二批签约单位负责人参加会议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 市经信委梁胜副主任首先汇报了中关村科学城第一、二批签约项目总体进展情况，各签约项目单位代表随之先后发言。中国人民大学文化科技园管委会办公室主任彭翊代表学校介绍了中国人民大学创意产业技术研究院的筹备建设进展、产业化项目筛选等情况。市领导在最后的讲话中，传达了中央领导近期视察中关村的指示精神，明确了下一步工作的思路和政策。会间，北京市领导、各兄弟高校对中国人民大学文化科技园的运营绩效及对北京市地方经济发展所做的贡献给予了高度评价。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
