<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公共管理学院成功举办亚太住房联盟国际学术研讨会",89,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",216,267);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-03 03:17:43",269,328);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8月21日，由中国人民大学公共管理学院土地管理系承办的&ldquo;2010年亚太住房联盟国际学术研讨会&rdquo;在人民大学逸夫会议中心顺利召开。来自英国、德国、日本等12个国家和地区的专家学者，以及人民大学土地管理系的师生共100多人参加了本次会议。 </p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c101124/z2mfbnnhmfl2yf-lmk2f.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本年度会议的主题是&ldquo;住房的可支付性、宜居性和可持续性&rdquo;。会议中，中国科学院院士、香港大学叶嘉安教授，英国伦敦经济学院和剑桥大学双聘教授Christine Whitehead，北京大学-林肯研究院满燕云教授，英国格拉斯哥大学Mark Stephens教授，澳大利亚新南威尔士大学Vivienne Milligan教授针对会议主题，分别做了报告。在其后的分论坛中，各国学者就&ldquo;各国住房政策的比较&rdquo;、&ldquo;住房的可支付性&rdquo;、&ldquo;城市宜居性&rdquo;、&ldquo;住房的可持续发展&rdquo;等四个主题展开了深入的讨论与交流。会后，参会学者们前往海淀区保障住房建设项目进行实地考察，并与海淀区房管局领导就住房保障相关政策进行了交流。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议期间，土地管理系系主任叶剑平教授，向与会代表分别介绍了中国人民大学公共管理学院土地资源管理和房地产经济学两个学科的基本情况，以及它们近年来所取得的令人瞩目的成绩。、叶教授还向各位来宾介绍了土地管理系的国际化进程，并与国外相关院系的负责人讨论了学术交流和人才培养方面的合作事宜。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n</p>",330,1777);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c101124/z2mfbnnhmfl2yf-lmk2f_lit.jpg",1779,1870);
$z[7][4]['name']="litpic";

?>