<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","外国语学院教师龙艳做客人民网谈“全球化时代的语言问题以及经典教育”",89,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院",236,285);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-10-07 09:03:33",287,346);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月6日，中国人民大学外国语学院教师龙艳与著名哲学家、解释学专家、语言史、欧洲学术史专家汉斯&middot;魏兹曼，希腊文化专家、法国国家科研中心高级研究员、法国高等社会科学院博士生导师皮埃尔&middot;于戴&middot;德&middot;拉贡伯做客人民网强国论坛，以全球化时代的语言问题以及经典教育为题与网友进行在线交流。 </p>\r\n<p align=\"center\"><img height=\"333\" alt=\"\" width=\"500\" src=\"/uploads/allimg/c100621/z2kkzlbnbnzklhf-blz2h.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 网友就全球化时代强势语言对弱势语言及文化的影响、国人学外语和外国人学汉语的比较、英语和世界语的关系、美国的价值观、法国大革命中&ldquo;自由、平等、博爱&rdquo;三个词的理解等方面向龙艳老师提出了问题，龙老师都一一做了回答。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp; 相关链接<a href=\"http://www.people.com.cn/GB/32306/54155/57487/8137351.html\">：【人民网】中欧学者谈&ldquo;全球化时代的语言问题以及经典教育&rdquo;</a></p>\r\n<p>（编辑/廖雪婷）</p>",348,1329);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100621/z2kkzlbnbnzklhf-blz2h_lit.jpg",1331,1423);
$z[7][4]['name']="litpic";

?>