{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院召开2011年管理工作会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-31 11:59:27{/dede:field}
{dede:field name='body'}<p>　　12月30日，经济学院2011年管理工作会议在明德主楼734会议室召开。经济学院杨瑞龙院长、张宇书记、明占生副书记出席大会并致辞，经济学院全体管理职员参加会议。会议由经济学院丁凯副书记主持。 <br />
　　会上，杨瑞龙院长和张宇书记分别宣布了学院科级干部的任命和行政科室的调整，并就2011年学院管理工作做了讲话。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110113/z2mhnnh22yfhlf-zflnf2.jpg" width="500" alt="" /></p>
<p><br />
　　杨瑞龙院长指出，经济学院管理团队是一只强有力的工作队伍，岗位职责明确，秉承一切为了学生的宗旨，工作勤勉尽责，并且大家在工作中团结互助，共同营造了和谐的工作氛围。他还表示，学院一直以来致力于维护管理职员的利益，为大家提供尽可能好的发展机会，对待所有人一视同仁，并最大限度的为大家创造良好的工作环境。最后，杨瑞龙院长希望大家要更加爱岗敬业，全心全意为师生服务。 <br />
　　张宇书记首先充分肯定了学院管理队伍在过去的一年里取得的成绩，并提出工作要求：一要忠于职守，严格按规章制度办事；二要以人为本，对待老师学生一视同仁，更好地为全院师生服务；三要共同营造团结和谐的工作氛围；四要注意加强学习，不断提升个人修养。 <br />
明占生副书记希望大家进一步做好学生思想政治工作，建立良好的育人环境，并通过言传身教对学生起到示范作用。 <br />
　　丁凯副书记就下一步的管理工作对大家提出了要求。 <br />
　　会议下发了《经济学院管理岗位说明书》、《经济学院管理制度汇编》等文件，学院各科室负责人分别报告了本科室的工作情况。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnh22yfhlf-zflnf2_lit.jpg{/dede:field}
