<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","德国柏林自由大学Schularick教授访问经济学院并发表学术演讲",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",226,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-15 03:34:04",275,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　2011年3月14日，德国柏林自由大学Moritz Schularick教授访问经济学院，经济学院国际经济教研室主任于春海副教授、范志勇副教授和赵勇博士等会见了Schularick教授。会见中，于春海副教授向Schularick先生介绍了经济学院举办的&ldquo;中国宏观经济论坛&rdquo;的相关情况，并向其赠送了英文版的2010年《中国宏观经济分析与预测报告》。Schularick教授表示会认真阅读，并希望自己及柏林自由大学的同事以后能更多地到经济学院访问。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflznzknlfb22f-lmznk.jpg\" alt=\"\" /></p>\r\n<p><br />\r\n　　随后，Schularick教授在&ldquo;世纪经英讲坛&rdquo;上发表题为&ldquo;外部失衡与金融危机：140年来的经验&rdquo;的学术演讲，就经济结构外部失衡与金融危机的联系等问题进行了阐述和分析。Schularick教授还与经济学院师生就金融工具的多样性与系统风险、中德两国的宏观经济现状及走势等问题进行了热烈的讨论。 　</p>\r\n<p>\r\n</p>",336,1197);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflznzknlfb22f-lmznk_lit.jpg",1199,1291);
$z[7][4]['name']="litpic";

?>