{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}德国柏林自由大学Schularick教授访问经济学院并发表学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-15 03:34:04{/dede:field}
{dede:field name='body'}<p>　　2011年3月14日，德国柏林自由大学Moritz Schularick教授访问经济学院，经济学院国际经济教研室主任于春海副教授、范志勇副教授和赵勇博士等会见了Schularick教授。会见中，于春海副教授向Schularick先生介绍了经济学院举办的&ldquo;中国宏观经济论坛&rdquo;的相关情况，并向其赠送了英文版的2010年《中国宏观经济分析与预测报告》。Schularick教授表示会认真阅读，并希望自己及柏林自由大学的同事以后能更多地到经济学院访问。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzknlfb22f-lmznk.jpg" alt="" /></p>
<p><br />
　　随后，Schularick教授在&ldquo;世纪经英讲坛&rdquo;上发表题为&ldquo;外部失衡与金融危机：140年来的经验&rdquo;的学术演讲，就经济结构外部失衡与金融危机的联系等问题进行了阐述和分析。Schularick教授还与经济学院师生就金融工具的多样性与系统风险、中德两国的宏观经济现状及走势等问题进行了热烈的讨论。 　</p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzknlfb22f-lmznk_lit.jpg{/dede:field}
