{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院广泛、深入开展“创先争优”系列活动，取得阶段性成效{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-11-23 05:21:26{/dede:field}
{dede:field name='body'}<p>　　5月14日，学校召开深入开展创先争优活动动员部署会，下发《中国人民大学关于在全校基层党组织和共产党员中开展创先争优活动的实施方案》、《中国人民大学开展创先争优活动第一阶段工作计划》，全校范围内，以&ldquo;创先争优促发展 十年腾飞跻一流&rdquo;为主题的创先争优活动广泛开展。 </p>
<p>　　公共管理学院党委积极响应学校号召，广泛宣传、全面动员，调动全院师生的积极性，精心组织、统筹协调，充分发挥基层党组织优势，坚持以科学发展观为指导，以改革为动力，以发展为主题，以质量为核心，在全院范围内广泛、深入开展创先争优活动，取得阶段性成果。 <br />
</p>
<p>　　（编辑：刘伟伟）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
