{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学法律诊所师生获赠锦旗及感谢信{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-12 02:20:48{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月6日，&ldquo;雷小平诉北京华审普惠餐饮有限公司工伤损害赔偿案&rdquo;原告雷小平与妻子来到人民大学法学院，将一面锦旗和一封感谢信交给法学院副院长王轶教授、地石律师事务所马野铭律师以及人民大学法律诊所的同学们。这起困扰当事人近三年的案件，在法律诊所师生的共同努力下，终于画上了一个圆满的句号。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyhkbhbzkf-lmhnn.jpg" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2007年，原告当事人在原工作单位从事食品加工作业时，被机器绞伤手臂，致右前臂骨折。原单位为了免于承担医疗费用，强迫原告以单位股东名字入院治疗、填写住院材料。前期治疗结束后，原单位拒绝支付后续治疗的费用。原告与单位协商未果，前来人民大学法律诊所寻求法律援助。三年来，在地石律师事务所马野铭律师的带领下，先后有四届法律诊所学生投入此案的办理工作，在原告与被告未签订劳动合同、无法从医院获得病历材料、无法进行工伤认定的不利情况下，克服种种困难和被告的阻挠，通过劳动仲裁、劳动关系确认之诉确认了劳动关系，提起工伤损害赔偿诉讼。并最终促成本案于今年4月14日以和解方式结案，给当事人争取到四万元人民币的赔偿金，使其得以进行后续的治疗。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在接受锦旗和感谢信后，当事人夫妇与王轶教授、马野铭律师和法律诊所代理案件的同学进行了交谈。当事人夫妇对以潘文军、刘刚老师为代表的法学院师生三年来为其案件做出的不懈努力深表感谢。王轶教授向当事人介绍了法律诊所的法律援助实践。他了解了其伤情的康复状况及现在的生活境况，表示法学院师生将会继续关注当事人的情况，随时提供力所能及的帮助。同时，王轶教授还勉励在场同学们以本案的圆满解决为激励，将课堂所学与社会实践相结合，为社会低收入群体提供更多更好的法律援助，为推动提高全民法律意识、推动国家法治化进程贡献法学学子的力量。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学法律诊所是面向本科三年级学生开设的一门法律实践课程，选修学生在课下依托人民大学法学院和地石律师事务所向社会弱势群体提供包括法律咨询、出庭代理在内的义务法律援助。自2000年9月开设以来，已经先后办理各类案件300余件，提供法律咨询近500次，产生了良好的社会影响，成为北京高校法律诊所教育的旗帜之一。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyhkbhbzkf-lmhnn_lit.jpg{/dede:field}
