{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本关西学院大学栗田匡相副教授访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-21 10:54:45{/dede:field}
{dede:field name='body'}<p>　　3月14日至18日，日本关西学院大学经济学部栗田匡相副教授访问经济学院，并进行多方面的学术交流。 <br />
　　3月17日，杨瑞龙院长在明德主楼614会议室会见了栗田匡相副教授，胡霞副教授陪同。杨瑞龙院长首先对此次日本人民所遭受的灾害表示慰问，对栗田匡相副教授的此次交流予以肯定，并祝愿两校经济学院的友好交流更上一层楼。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzknymnm2f-hnhml.jpg" width="500" height="333" alt="" /></p>
<p><br />
　　访问期间，栗田匡相副教授还与经济学院师生进行了一系列的学术交流活动。 <br />
　　3月16日，栗田匡相副教授就&ldquo;日本东北大地震对日本经济以及中日国际贸易的影响&rdquo;问题与经济学院教师进行学术交流，经济学院关权教授、门淑莲副教授、胡霞副教授参加了交流活动。 <br />
　　3月17日，栗田匡相副教授在公教2118室就&ldquo;日本农业现代化与中国现代农业建设&rdquo;的问题参加了学生的讨论课，并与同学们进行了十分热烈的讨论。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzknkyf2yf-bnhln.jpg" width="500" height="332" alt="" /></p>
<p><br />
　　3月18日，栗田匡相副教授在明德主楼2102室发表了题为&ldquo;发展经济学的未来发展趋势&rdquo;和&ldquo;中国和印度两国城乡不平衡发展问题的实证研究&rdquo;的学术演讲。经济学院130余名同学们参加了演讲会。同学们兴趣非常浓厚，并表示通过演讲会开阔了视野。 <br />
　　栗田匡相副教授此次来访基于两校间的校级交流协议，这种形式多样的交流无疑会使两校经济学院的教师和学生合作更加密切。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzknymnm2f-hnhml_lit.jpg{/dede:field}
