<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","外国语学院接待比利时布鲁塞尔自由大学代表团来访",89,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院 文/连欢",216,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-15 03:35:42",275,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　4月14日下午，中国人民大学外国语学院在明德国际楼505室接待了比利时布鲁塞尔自由大学代表团。外国语学院副院长贾国栋、法语系主任徐艳等到场。比方代表为比利时布鲁塞尔自由大学教授Annick Englebert，比利时王国大使馆驻华代表团团长Marc Kohen和比利时法语区外籍教师Corinne Bricman。 </p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c110419/zlflznzm2hmkkkf-z2zlf.jpg\" />&nbsp;</p>\r\n<p>　　首先，贾国栋副院长表达了外国语学院与海外大学合作建立交换项目的意愿，并简单介绍了人大已有的交换模式，如&ldquo;7+1&rdquo;项目（七个学期在人大学习和一个学期海外交流）和暑期学校等。随后，两方开始商讨校际间合作交流的方式，最终提出了暑期学校、秋季学期学生交换和教师交流三种模式。另外，比利时布鲁塞尔自由大学即将建立亚洲语系学院，因此非常欢迎人大的教师和学生来到中文系短期任教和交换学习。这次会议奠定了两校间合作交流的基础，进一步细节的敲定有待完成。 </p>\r\n<p>　　\r\n</p>",336,1224);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflznzm2hmkkkf-z2zlf_lit.jpg",1226,1318);
$z[7][4]['name']="litpic";

?>