{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国社会舆情（2010上半年度）舆情报告发布{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-10-14 09:58:30{/dede:field}
{dede:field name='body'}<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国社会舆情（2010上半年度）舆情报告发布会10月13日由中国人民大学舆论研究所发布，中国人民大学常务副校长袁卫教授出席发布会并致辞，中国人民大学中国调查与数据中心副主任彭非教授、中国人民大学新闻学院常务副院长倪宁教授等专家学者参加了会议，中国人民大学新闻学院副院长喻国明教授主持了发布会，来自人民日报、新华社、光明日报和中国青年报等主要中央新闻媒体报道。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbmff2nmznyf-hzzzm.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告主要梳理了上半年每个月度舆情变化及典型事件，盘点了上半年大众媒体、网络意见领袖、网民等不同舆论场域的热点事件及其影响力指数，并对上半年网络热点人物和社会文化思潮做了盘点，并对上半年舆情变化规律进行理论总结，在此基础上对全国31个省区进行了舆情压力指数的测算，并将此排行榜对去年各省舆情压力指数进行比较。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbmff2m2kyhf-bmybn.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 袁卫常务副校长在致辞中代表学校向在座嘉宾表示热烈欢迎和诚挚感谢。他在讲话中指出，近十年，随着互联网技术的飞速发展和中国网民数量的激增，网络在社会生活中的角色越来愈重要，网络舆论场域与社会舆论场域逐步交融汇流，成为社会舆论场域的风向标，正如德国传播学者伊丽莎白&bull;诺依曼所说&ldquo;舆论是社会的皮肤&rdquo;。党的十七大以来，胡锦涛等中央领导同志高度重视网络，强调要高度重视网络舆论，掌握网络舆论的主动权，并开通网络民意直通车，中国人民大学之所以研究和发布中国社会舆情报告，一方面表达了我们对社会环境和舆情变化的学术关切，另一方面是主动履行大学所担负的责任，努力形成一套科学的指标体系，来科学衡量和评价社会舆情变化的态势和规律，为构建社会主义和谐社会做出应有的贡献。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，中国人民大学中国调查与数据中心副主任彭非教授致辞，他认为对社会舆情的研究在现代信息发达的社会尤为必要和紧迫，中国调查与数据中心以后会进一步支持该项工作的展开。</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学新闻学院常务副院长倪宁教授在讲话中指出，中国人民大学舆论研究所作为国内高校中最早的民意调查研究机构，具有很高的品牌度和影响力，新闻学院将进一步加大对这项工作支持的力度，将之打造成为人大一个重要的研究品牌。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbmff2mllzyf-ykzkz.jpg" />&nbsp;</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，中国人民大学舆论研究所所长喻国明教授详细介绍了上半年度的总体舆情报告，并与2009年上半年做了对比，并就上半年全国各省区舆情压力指数排行榜做了详细介绍。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbmff2mlnmzf-kmbfy.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;原文链接： <a href="http://news.gmw.cn/2010-10/15/content_1311844.htm">中国社会舆情（2010上半年度）舆情报告发布 </a></p>
<p align="left">　　（编辑：卢思颖）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmff2nmznyf-hzzzm_lit.jpg{/dede:field}
