{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}统计学院王晓军教授带领学生赴台湾进行学术交流{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-12-20 09:41:22{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp;&nbsp; 应台湾辅仁大学和国立政治大学统计系的邀请，12月9日至17日，统计学院王晓军教授带领16名博士和硕士研究生赴台湾进行访问与学术交流。访问中双方对应用统计相关领域的学术问题进行了深入的讨论与交流，统计学院有9名学生报告了他们的论文。</P>
<P>&nbsp;&nbsp;&nbsp; 在台期间，还参观了微软台湾分公司，以及美丽的阿里山和日月潭等自然景观，领略了祖国宝岛的美丽风光。&nbsp;<BR><BR><BR><BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
