{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}马俊杰副书记会见“斯坦福大学北京朋辈互助心理辅导工作坊”专家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学工部{/dede:field}
{dede:field name='body'}<p>　　11月8日至12日，由中国人民大学心理健康教育与咨询中心与北京大学心理健康教育与咨询中心联合主办的斯坦福大学北京朋辈互助心理辅导工作坊分别在北京大学和中国人民大学开展。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c101126/z2mfkyfhn2zlynf-khmfl.jpg" /></p>
<p>　　11月11日上午，中国人民大学党委马俊杰副书记在人民大学会见了本次朋辈心理辅导工作坊指导-斯坦福大学心理咨询中心主要负责人Alejandro Martinez教授。马俊杰副书记向Alejandro Martinez教授表示感谢，认为本次大学生朋辈心理辅导工作坊是一次很有意义的尝试，希望双方以此次合作为契机，继续加强在其它相关领域的合作。Alejandro Martinez教授表达了进一步开展大学生朋辈心理辅导工作坊的意愿，并充分肯定学员们的学习，认为这样的合作值得推广。国际交流处程鑫副处长、学生处张玲玲副处长陪同会见。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhn2mfbkf-nnhzl.jpg" /></p>
<p>　　朋辈互助是一种特殊的心理咨询形式，是指在人际交往过程中人们相互给予心理安慰和支持的过程。与专业咨询相比，朋辈互助具有自发性、亲情性和有效性的特点，因而在大学生群体中广泛推广，在高校的心理健康教育中发挥着日益重要的作用。作为斯坦福大学学生心理咨询中心的主要负责人、朋辈心理辅导项目&ldquo;桥&rdquo;的督导师，Alejandro Martinez教授投身大学心理教育与辅导事业已有三十余载。他在大学生行为健康、项目评估、临床干预等不同领域出版发行五十余种读物；指导并协助多种研究项目，是三十余个心理委员会、董事会和相关组织的成员。在人大站，Alejandro Martinez教授着重讲解了人际冲突、危机咨询、降低自杀风险、朋辈辅导员的自我关怀、开展自己的朋辈咨询项目等相关概念和技巧。Alejandro Martinez教授平静的语调中略带幽默，平实的讲解中充实着鲜活的事例，讲解过程中学员与培训师的互动频繁，并就工作中遇到的相关问题做了深入交流。 随后，马俊杰副书记和Alejandro Martinez教授团队以及全体参会人员在明德楼前合影留念。参加本次工作坊的教师分别来自中国人民大学、北京大学、复旦大学和上海交通大学等不同高校。 </p>
<p>　　斯坦福大学心理专家Dr. Martinez教授对工作坊感到满意，他说：&ldquo;中国的老师和辅导员们对于解决大学生心理问题的积极态度和意愿让我深有感触。中国和美国在进行朋辈互助时虽然存在一些差异，但是大家也给了我许多启发。希望在以后的交流中加入具体操作的示范，通过类似的工作坊来推广解决大学生心理问题的技巧和方法。&rdquo;</p>
<p>　　相关链接：<a href="http://news1.ruc.edu.cn/102449/102451/102473/72026.html">美国斯坦福大学心理咨询中心主任参观学校心理咨询中心</a></p>
<p>　　（编辑：易晨）</p>{/dede:field}
{dede:field name='pubdate'}1289523829{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhn2zlynf-khmfl_lit.jpg{/dede:field}
