{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学艺术学院常务副院长徐唯辛教授荣获第三届德艺双馨文艺工作者称号{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-06-23 03:10:07{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月20日，由中宣部、人力资源和社会保障部、中国文联共同主办的第三届全国中青年德艺双馨文艺工作者表彰大会在京召开。中共中央政治局委员、中央书记处书记、中宣部部长刘云山出席会议并讲话。这次表彰的文艺工作者来自中国文联36个团体会员，其中包括19个省级团体会员，涵盖了12个艺术门类，共54人。出席表彰大会的有中宣部、中国文联、人力资源和社会保障部、解放军总政治部、文化部、国家广电总局、新闻出版总署、中国作协等有关领导。中国人民大学艺术学院常务副院长徐唯辛教授荣获本届德艺双馨文艺工作者称号并出席表彰大会。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 徐唯辛教授长期坚持教学的同时，关注社会现实和弱势群体，多次深入煤矿及农民工的工棚体验生活，主动为受难矿工家属捐款，被山西高阳煤矿授予&ldquo;荣誉矿工&rdquo;称号。徐唯辛教授近年创作的油画作品以强烈的视觉艺术语言表达出深厚的人文关怀。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 徐唯辛教授多年来在艺术创作中勤奋耕耘，佳作频出，影响广泛，先后在国内外举办作品展览，代表作有《馕房》、《酸雨》、《矿工肖像系列》、《历史中国众生相1966&mdash;&mdash;1976》等，并荣获中国油画展优秀作品奖，全国美展银奖、铜奖、北京市政府文学艺术奖、中国年度艺术家奖、美国耶鲁大学&ldquo;杰出艺术成就&rdquo;奖等奖项。今年4月赴美国哈佛大学举办个人作品展，为中国人民大学与哈佛大学的交流合作做出了应有的贡献。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
