{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}拓展视野培养卓越人才：法学院推行学生国际化战略成果显著{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/校报 法学院 图/法学院{/dede:field}
{dede:field name='pubdate'}2010-06-07 04:23:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在中国人民大学实施&ldquo;十年腾飞&rdquo;发展规划和全面提升国际性发展战略的背景下，人大法学院围绕建设成为世界一流法学院的目标，坚持以学生为本，以学术为根，以学院为依托，大力推动实施学生国际化战略，致力于为中国培养出具有国际视野、熟悉国际法律事务和专业知识、具有国际竞争力、能够在国际和地区舞台上有效维护国家利益的优秀国际型法律人才。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院院长韩大元教授强调，学生是教育之本，是学院发展的核心竞争力，一流学生的培养是建设世界一流法学院的重中之重，推行学生国际化战略是实现学院国际化建设的重要一环。一年多来，为把学生国际化推向一个新的高度，法学院开展了系列工作并取得了积极的进展。 <br />
<br />
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 编织学术大师的摇篮&mdash;&mdash;&ldquo;未来学术大师培养计划&rdquo;</strong> <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近年来，随着人大实施&ldquo;十年腾飞&rdquo;发展规划和全面提升国际性发展战略，法学院也迎来了新的机遇，但是，人大法学学科未来要在世界法律界立足也面临着新的挑战。在新的形势下，人大法学院必须要有一批具有国际影响力的学术大师。除了引进最尖端的人才，培养人才、创造人才更是立学之本。&ldquo;未来学术大师培养计划&rdquo;应运而生，是法学院挖掘学术人才潜力、储备国际化高端学术人才的重要项目，也是推进学生国际化战略、着眼于长远人才培养的新亮点。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈怡伊，法学院2007级本科生，在三年的大学时光中，她不仅学习成绩名列前茅，而且积极钻研科研问题，在《法制日报》、《检察日报》以及《中国律师》等刊物上发表了多篇学术文章。她积极参与了中欧反酷刑研究和量刑程序改革等多个课题，多次随人大法学院代表团赴荷兰和美国访问，曾获得宝钢优秀学生奖学金。对于陈怡伊这样的学生，如果按照以往的培养模式，只能在国内接受教育，今后能否走上学术道路，成为学术大师很难预测。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 然而，随着今年人大法学院&ldquo;未来学术大师培养计划&rdquo;的推出，她与熊焰、冯雅杉等三位同学经过严格的考核，成为这一计划的第一批人选。今后法学院将对这批学生进行重点培养，通过各种形式推荐其至国外一流大学法学院接受专业训练并继续深造，毕业后作为人才引进回学院。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;未来学术大师培养计划&rdquo;是从长远的角度储备未来法学院师资的新思路，有利于培养学生追踪国际法律理论前沿、进行创造性研究的能力，使参加计划的学生能够与国际法学界展开高水平的对话，具备成为有国际影响力的学术大师的潜质和实力。 <br />
<br />
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 海外杰出法学家课程&mdash;&mdash;把世界学术大师请回家</strong> <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 以往为了增加学生与世界法学大师接触的机会，人大法学院多方邀请名家大师到学院开设讲座。但这只是蜻蜓点水式的方法，并不能深入学生与大师的交流。为了向学生提供向世界一流法学家学习、扩展国际视野的机会和平台，法学院邀请多位享誉海内外的杰出法学家开设&ldquo;海外杰出法学家系列课程&rdquo;，真正意义上引入国际优质的教学资源。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 今年3月,&ldquo;海外杰出法学家系列课程&rdquo;第一讲即由世界知名罗马法学家和比较法学家、奥地利维也纳大学Herbert Hausmanninger教授为人大学子讲授了为期一个月的罗马法课程。法学院还积极利用学校现有资源，聘请中国人民大学长江学者讲座教授、国际著名历史学家黄宗智教授为法学院兼职博导，今年9月起将在法学院开设&ldquo;法律、社会与经济&mdash;&mdash;历史与理论&rdquo;课程，并以此拓展跨学科的研究领域，培养法律与人文领域的专门人才。最近，法学院更是利用先进的网络设备让学生能够在远距离之外聆听世界知名法学教授的授课，真正做到了足不出户学遍全球。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与此同时，卢森堡大学法学院Gilles Cuniberti教授、英国以及百慕大注册律师Stephen Leonard教授、乔治敦大学法学院教授Lucille Barale均为法学院学生开设了课程。法学院还结合知识产权学院、律师学院的国际教学资源，为在校学生开设国际法律事务技能课程。这些具有国际视野的课程增强了法学院学生适应国际法律事务的能力。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyylzf2mzf-hlf2h.jpg" /></p>
<p align="center">图为海外法学家系列讲座之卢森堡大学法学院Gilles Cuniberti教授的讲座</p>
<p align="left"><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为了让学生顺利获得国外优秀教育资源，法学院将联合培养作为一条捷径并尽力为学生提供优越的条件。如开展中法欧洲法项目、从具有复合性专业背景的法律硕士研究生中选拔20余名学生到国外院校学习、与国外法学院联合培养优秀博士研究生、与美国乔治敦大学法学院联合培养硕士研究生。如今，在法学院的鼓励和支持下，学生们可以参与法学院与国外法学院的多个联合培养项目，这为希望获得国外先进法律知识的优秀学生提供了实现个人愿望的机会。同时，这种联合培养模式也拓宽了培养国际优秀法律人才的渠道。 <br />
<br />
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大胆&ldquo;引进来&rdquo;，积极&ldquo;走出去&rdquo;&mdash;&mdash;换了主角的学术新戏 <br />
</strong><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 今年3月10日，首届学生国际学术研讨会&ldquo;人民大学法学院&mdash;早稻田大学法学院学生圆桌讨论会&rdquo;在明德法学楼内举行。研讨会由日本早稻田大学法学院院长近江幸治教授携多名教授和学生成员与人民大学法学院师生展开了学术交流，是第一次由国外法学院院长带领学生出席的学生学术研讨会，也是第一次本、硕、博学生与教授们共同参加的研讨会，掀开了法学院与国外知名法学院学生开展学术讨论会的新篇章。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一个星期后，来自哈佛大学法学院的20多名学生与人大法学院学生会联合举办了&ldquo;中国人民大学法学院&mdash;哈佛大学法学院学生圆桌讨论会&rdquo;。随后不久，&ldquo;中国人民大学法学院与爱尔兰都柏林大学法学院博士生圆桌讨论会&rdquo;、英国谢菲尔德大学访问团学生交流会相继在人大法学院举行。学生圆桌讨论会的步伐未曾停歇，今年6月法学院还将举办&ldquo;中国&mdash;&mdash;美国法科大学学生国际圆桌会&rdquo;和&ldquo;人大法学院&mdash;&mdash;牛津大学法学院学术圆桌会议&rdquo;。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyyl2ykmlf-bklhl.jpg" /></p>
<p align="center">图为人大法学院与哈佛大学法学院学生举行圆桌会议</p>
<p align="left"><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在请来世界知名法学院优秀学子来校访问的同时，法学院还将利用暑期积极&ldquo;走出去&rdquo;，组织学生到世界著名大学法学院访问学习。这一计划被形象的称为&ldquo;学生暑期海外游学系列&rdquo;活动。作为该系列活动的重要内容之一，人大法学院与英国牛津大学Oriel College已签订合作协议。牛津大学Oriel College将面向中国人民大学法学院招生参加英文暑期学校项目，在今年8月举办为期四周的英文暑期课程。近期，法学院正在组织筹划学生参加剑桥大学&ldquo;学术先锋&rdquo;暑期课程。今年暑假，法学院还将组织15名学生前往日本东京、京都、大阪地区，对日本高校、法院、律所等机构进行为期两周的访问考察。目前人员选拔工作已经基本完成。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 通过这些&ldquo;引进来&rdquo;和&ldquo;走出去&rdquo;，法学院学生真正领略到了世界一流法学院的所应有的气度和实力，学生国际化战略真正成为惠及全体学生的福祉。&nbsp;<br />
<br />
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;国际舞台尽显风采&mdash;&mdash;积极参加海外实习和国际大赛</strong> <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在世界知识产权组织位于日内瓦的总部内，郝卓然、侯磊两名青年正埋头于手上繁忙的工作。这是我国高校第一次有组织地向世界知识产权组织派出实习生。在法国斯特拉斯堡的欧洲人权法院的大厅里，来自人民大学的聂笑阳是欧洲人权法院第一次接受的来自非欧洲国家的实习生。在为期六个月的实习中，这三名来自中国的青年将肩负着为继续顺利派出实习生担任开路先锋的责任。促成他们成行的是人大法学院推出的&ldquo;选派优秀学生赴国际机构实习计划&rdquo;，这一计划的目的是为国家培养锻炼一批具有开放的国际视野、具备国际竞争力、系统掌握国内法律和国外法律知识体系的法律人才。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyyllklhkf-yknln.jpg" /></p>
<p align="center">图为法学院实习生在世界知识产权组织实习</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyylhnmm2f-kknzz.jpg" /></p>
<p align="center">图为赴国际机构实习欢送会</p>
<p align="left"><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在三名人大学子欧洲实习的同时，另一批学生正踏上飞往美国华盛顿的飞机。他们此行是去参加&ldquo;杰赛普（Jessup）国际法模拟法庭比赛&rdquo;。&ldquo;杰赛普国际法模拟法庭比赛&rdquo;是由美国国际法学生联合会主办的专业性法律辩论赛，是目前国际上规模最大、历史最悠久的模拟法庭比赛，被誉为国际法学界的&ldquo;奥林匹克竞赛&rdquo;。今年3月，&ldquo;中国第八届杰赛普（Jessup）国际法模拟法庭辩论赛&rdquo;在中国人民大学举行，人大法学院学生代表队获得第二名的佳绩，随后赴美国华盛顿参加了全球Jessup的比赛。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyylyhbzkf-nlmnn.jpg" /></p>
<p align="center">图为法学院代表队赴华盛顿参加杰塞普国际法模拟法庭比赛与法官和其他国家队员合影</p>
<p align="left">&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一年来，法学院学生先后参加了&ldquo;杰赛普（Jessup）国际法模拟法庭辩论赛&rdquo;、日本&ldquo;亚洲杯&rdquo;国际法模拟法庭比赛以及中国第七届&ldquo;贸仲杯&rdquo;国际商事仲裁模拟辩论赛、第三届&ldquo;红十字国际人道法模拟法庭竞赛&rdquo;，均取得了较好的成绩。今年11月法学院还将组队赴香港参加香港基本法模拟法庭比赛。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院在推进学生国际化战略中积极组织学生参加重要的国际赛事，在激烈的竞争中使人才脱颖而出。国际赛事给各国学生提供了与国外学生切磋学术造诣的广阔舞台，培养锻炼了更多懂法律、懂外语、懂实务的复合型人才。 <br />
<br />
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;团队作战&rdquo;的责任和荣耀&mdash;&mdash;积极为学生提供人员、资金支持</strong> <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为保障学生国际化战略顺利实施，法学院外事工作机构、团学组织和教务部门密切配合，做了大量工作，与国外院校有密切联系的教师也积极参与到推动学生国际化的工作中。同时，法学院还成立专门机构&mdash;&mdash;比较法学教研室负责联络筹划，承担比较法教学、研究工作，负责开展与明尼苏达大学、印第安纳大学合作的&ldquo;中国法暑期班&rdquo;项目等人才联合培养工作。比较法教研室作为法学院机构建设的新举措，甫一创立便迅速成为法学院国际化教育教学的重要力量，学院选派具有丰富国外教学科研经验的教师充实到比较法教研室中，极大地推动了法学院学生国际化与教学国际化进程。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 推动学生参与国际交流和实习需要大量的资金支持，为把资金筹措的钱柜子打开，法学院想到了成立专项基金的办法，2010年&ldquo;中国人民大学法学院学生国际交流基金&rdquo;顺利设立，基金将全部用于支持与鼓励法学院学生参加高水平海外交流活动，包括攻读学位、短期交流、参加国际会议等。这一基金吸引了一大批有志于为中国国际化法学人才培养做贡献的律师事务所、大型企业等机构和个人。例如，杰赛普模拟法庭举办得到了方达律师事务所、路伟律师事务所、white &amp; case律师事务所等单位的赞助。&ldquo;亚洲杯&rdquo;国际法模拟法庭比赛，也得到了校研究生院和日本在华律师事务所的大力支持。此外，法学院努力与国外合作院校和机构进行协商，使接收高校同意减免全部或部分费用，这极大地减轻了学生的负担。&nbsp;</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为了促成学生在国际机构中实习，法学院不仅积极与世界知识产权组织和欧洲人权法院进行联系派出事宜，为了解决同学们经济上的后顾之忧，还多方寻求资金支持，为同学们安心实习提供了有力的保障。今后法学院还将与顶尖的国际机构进一步建立长期、机制化的联系，使更多人大法学院的学生、更多的中国学子有机会步入这些机构的殿堂。同时将不断扩大学生到国际性、地区性机构实习的范围，为学生提供更多的交流的平台。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;一百多年前，梁启超先生在传世名作《少年中国说》中写道&ldquo;少年智则国智，少年富则国富，少年强则国强，少年独立则国独立，少年自由则国自由，少年进步则国进步，少年胜于欧洲，则国胜于欧洲，少年雄于地球，则国雄于地球&rdquo;，中国的发展仰赖于莘莘学子的自立自强，在全球化的背景下，中国法科学生欲与各国竞争必先参与到全球化的大潮中，而学生国际化正是应然之举。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在以世界为背景的法学院竞争中，人大法学院未来能否实现&ldquo;世界一流&rdquo;的目标，能否在学校&ldquo;十年腾飞&rdquo;战略中跟上队伍，做出成就，也寄希望于略显稚嫩但生气勃勃的青年学生。学生国际化战略的顺利迈出不仅为学生的未来种下了希望的种子，也为法学院的未来打开了一扇新的窗户。 </p>
<p align="left">（编辑&nbsp;&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyylzf2mzf-hlf2h_lit.jpg{/dede:field}
