<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<dt class=\\\"img\\\"><a href=\\\"{@me['arcurl']}\\\"><img onload=\\\"hideno(this)\\\" alt=\\\"\\\" src=\\\"{@me['litpic']}\\\"/></a></dt>\"); ",7,205);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",221,236);
$z[2]=Array("title","",250,264);
$z[3]=Array("description","",281,301);
$z[4]=Array("pubdate","",313,355);
$z[4][4]['function']="GetDateMK(@me)";
$z[5]=Array("arcurl","",373,388);

?>