{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院博士生赴日参加“中日韩世界经济危机青年学者联合讨论会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-01-05 08:36:17{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月22-25日，受日本京都大学邀请，经济学院三名博士生于赴京都参加了由日本京都大学经济学研究所和京都大学&mdash;中国人民大学联合经济研究中心举办的国际讨论会，与日本京都大学和韩国国立庆北大学的青年学者共同研讨世界经济危机问题。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，三位博士生分别宣读了自己的英文论文：《汇率制度、金融发展与&lsquo;创造性毁灭&rsquo;&mdash;开放经济中的熊彼特假说和证据》（07级博士生黄阳华）、《中国与欧元区货币政策效果比较研究》（08级博士生伍艳艳）、《中国经济反衰退政策与后危机发展》（08级博士生朱君），并与日韩学者共同进行了讨论和评论。他们的扎实的学术功底和出色的演讲表现得到了各方的肯定和好评。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学经济学院和京都大学经济学部一直保持密切的学术交流，积极推进双方博士研究生的交流，过去几年里已经共同举办过多次研讨会。本次会议的组织者、日本京都大学经济学部大西广教授对中国人民大学经济学院的学术水平给予了高度的评价，并希望进一步深化双边的学术联系和交流。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
