{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院颁发2009—2010学年第二学期安然助学金{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-11 10:08:33{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月9日中午，助学金获评学生座谈会暨2009&mdash;&mdash;2010学年第二学期安然助学金颁发仪式在明法616会议室举行。法学院党委副书记郑小敏，院团委常务副书记邢姝，团委副书记方兴嵩、徐隽出席座谈会。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郑小敏副书记在讲话中说，定期举行与受助学生的座谈会，是履行资助协议，指导受助学生合理使用助学金，了解受助学生的学习、生活、社会实践情况和实际困难的有效途径。他希望同学们畅所欲言、交流思想，更希望大家在大学生活中互相鼓励、互相帮助、共同进步。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，郑小敏副书记向法学院2008、2009级四名学生颁发了2009&mdash;&mdash;2010学年第二学期安然助学金。这四名受助学生是入学时自主申请，经安然助学金评审委员会从申请学生中评选出来的。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在座谈会上，助学金获得者们介绍了自己在校学习、生活、工作等的情况，相互交流学习经验、学习心得。会前，受助学生还提交了上一学期学习成绩单和以《我的大学生活》为题的报告。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 安然助学金是中国人民大学校友霍先生赵女士夫妇设立的，旨在帮助成绩优异、经济困难的法学院学生完成学业，促进不同经济条件学生间的平等竞争，鼓励学生走向社会后回报社会。目前共资助四名学生，每人每学年10000元港币，连续资助三年。在学院和霍先生赵女士夫妇的关心支持下，四名受助学生很快适应了大学生活，学习努力、工作积极、生活健康、奋发向上，取得了良好的成绩。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
