{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学2010年香港信善奖助学金签约暨颁奖仪式举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学生处{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月7日下午，中国人民大学2010年香港信善奖助学金签约暨颁奖仪式在逸夫会堂举行。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学党委副书记马俊杰、香港信善基金会陈观威、黄秀德、杜俊基出席仪式，并为获奖教师、学生代表颁发了证书。信善奖教金获奖教师代表王珊教授、秦宣教授、毛基业教授、王孝群教授以及获得信善奖助学金的100余名学生代表参与了颁奖仪式。仪式由学生处处长张晓京主持。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m2kbnyf-zn2zl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 马俊杰副书记代表学校，向香港信善基金会对人大学子长久以来的关心和支持表示感谢，他回顾了十一年来信善基金会和人民大学结下的不解之缘和感人事迹，并希望获奖的老师和同学们要多学习、多研究，多出成果，常怀仁爱之心，多做为善之事。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m2km22lf-2mfzy.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，陈观威先生代表信善基金会向在座的老师和同学们表达了参与颁奖活动的激动心情，他希望同学们能够认真学习、努力创新，不要忘记自己的父母、家乡、母校和祖国，要成为有益于国家和社会的人才。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m2kmbkhf-lymnl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接下来，获奖教师代表商学院毛基业教授、受助学生代表农业与农村发展学院陈赴望同学、获奖学生代表新闻学院裴峥同学分别发言，一方面表达了对香港信善基金会的感谢，另一方面也与在座的老师和同学交流了工作和学习经历。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2m2nfff2f-hzk2y.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在仪式上，马俊杰副书记和陈观威先生共同签署了信善奖助学金捐赠协议，商定继续在人民大学捐资设立信善奖助学金项目。据悉，信善奖助学金已经在人民大学设立十一年，捐赠奖助学金680余万元，奖励资助学生已超过2000人。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
<br />
</p>{/dede:field}
{dede:field name='pubdate'}1294625930{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2kbnyf-zn2zl_lit.jpg{/dede:field}
