{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国乔治华盛顿大学国际新闻实习项目负责人访问新闻学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/新闻学院 吴储岐 吴尚蔚 图/新闻学院 裴峥{/dede:field}
{dede:field name='pubdate'}2011-03-18 09:26:51{/dede:field}
{dede:field name='body'}<p>　　3月15日下午，中国人民大学新闻学院倪宁常务副院长会见了来访的美国乔治&bull;华盛顿大学国际新闻实习项目负责人Amos Gelb教授。 </p>
<p>　　倪宁常务副院长对Amos Gelb教授的来访表示热烈欢迎，并向其介绍了学院的基本情况，强调要积极加强两校之间的交流，希望能够在国际新闻等领域加强与乔治&bull;华盛顿大学的合作。倪宁教授还详细了解了Amos Gelb教授此次来访新闻学院的情况，并对Amos Gelb教授提出的新闻跨媒体实习的理念表示了赞同。 </p>
<p>　　Amos Gelb教授对倪宁常务副院长的热情接待表示衷心的感谢，并赞扬了新闻学院学生的专业素养和学习热情，并提出希望能够在暑期开展优秀学生的交流活动。Amos Gelb教授还向倪宁常务副院长表示，希望今后有更多的机会到人大进行互访交流。 </p>
<p>　　会见结束后，倪宁常务副院长代表新闻学院，向Amos Gelb教授赠送了礼品并合影留念。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110419/zlflznzbkfbnmyf-zhmky.jpg" /></p>
<p>　　会见之前Amos Gelb教授为新闻学院09级部分同学进行了题为《未来的挑战--中美新闻学所共同面临的挑战与迎战之道》的讲座，并与同学进行了交流。 </p>
<p>（编辑：吴琰坤）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzbkfbnmyf-zhmky_lit.jpg{/dede:field}
