<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","澳大利亚莫道克大学一行四人访问心理学系",89,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","心理学系",208,255);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-28 02:28:46",257,316);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　9月24日，西澳大利亚著名大学莫道克大学（Murdoch University）科学、工程及可持续学院院长J Stuart Bradley教授一行四人访问了中国人民大学心理学系，心理学系系主任孙健敏教授进行了接见。双方互相介绍了各自在心理学及相关学科的教学和科研方面的情况，并就研究生和教师两个层次，以及心理学相关的学术研究和职业培养两个方面的合作进行了充分讨论，达成了诸多合作意向。 </p>\r\n<p>　　来访的四位教授分别是莫道克大学科学、工程及可持续学院院长J Stuart Bradley教授，外事处处长Hendrik Halim教授，创意技术与媒体学院院长Jeremy Bean教授，学生学习中心的Martin Gwyn-Fawke教授。心理学系的部分教师陪同孙健敏教授进行了接见和会谈。 </p>\r\n<p>　　\r\n</p>",318,976);
$z[6][4]['name']="body";
$z[7]=Array("field","",978,1017);
$z[7][4]['name']="litpic";

?>