{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院2011届毕业作品展演拉开帷幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：校报学生记者 蒋明艳{/dede:field}
{dede:field name='pubdate'}2011-05-10 05:19:38{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月9日上午，艺术学院2011届绘画专业毕业生作品展在教一1301教室举行。人民大学副校长杨慧林以及党委组织部、党委宣传部、发展规划处、科研处、教务处、审计处等有关部门负责人，美国南犹他州大学表演与视觉艺术学院艺术系主任Eric Brown 教授、Ben Sowards教授等出席开幕式并参观画展，艺术学院徐悲鸿艺术研究院院长徐庆平，艺术学院顾问邱承德、潘吾华，艺术学院分党委书记兼副院长郑晓华、常务副院长徐唯辛与学院师生参加开幕式。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学艺术学院成立十多年来，坚持&ldquo;宽口径&rdquo;、&ldquo;厚基础&rdquo;、&ldquo;多学科复合&rdquo;的教学理念，除了必要的人文素养、外语、计算机基础课程，在专业上力求互相打通，以实现传统艺术与现代知识的融合对接，立足东西文化交流前沿，培养既具深厚传统功底、又具宽阔国际视野，一专多能的高素质艺术人才。据悉，在最近有关机构主持的《2011中国大学评价》中，中国人民大学艺术学院音乐表演专业在全国1 63所艺术院校中排名第3，等级为A++，属得分最高的2%；绘画专业等级为A+。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhkffhhlf-yklll.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式上，杨慧林副校长代表学校向本届毕业生表示祝贺，并对艺术学院师生为营造浓厚的校园艺术氛围所发挥的作用表示肯定和赞赏。他指出，人文社会科学与艺术学科的相互依存、互相促进，使得人民大学的人才培养环境更加充满了人文气息。&nbsp;</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhkflnfzf-kny2f.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艺术学院常务副院长徐唯辛介绍了此次展览情况。本届毕业生中，绘画专业25人、国画专业13人、油画专业12人以及研究生5名，他们以自己精心创作的作品作为4年学习的总结和汇报。与此同时，艺术学院系列毕业展演活动将在校园内举行，包括艺术设计专业毕业生作品展和音乐表演专业毕业生4场音乐会。&nbsp;</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhkfhlbmf-nmy2m.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次展览的作品有油画、国画、书法、连环画等，充分展现了艺术学院的教学实践水平以及学生的综合素养。在油画展区，作品《众里寻他》（356X140cm）不论是巨大的画幅尺寸，还是贴近生活的内容，都受观众瞩目。作者苏晓敏同学介绍说，她所画的都是身边的朋友，表现他们的生活状态和精神状态，以及他们追求的目标。完成这件作品用了3个多月的时间，大学4年的文化知识和绘画技法的学习、积累，都试图通过作品给予表现。苏晓敏说，作为以人文社会科学为主的综合性大学艺术专业学生，虽然在美术专业上的接触面有限，但学校深厚的人文底蕴以及辅导老师的影响，都让她得到了很大的收获。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 前来参观展览的艺术学院大三学生赵子鉴说，艺术学院的每一个学生都要经历这个毕业作品展，前来参观学习对自己的学习和创作都有启发。</p>
<p>（编辑：刘德萍）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkffhhlf-yklll_lit.jpg{/dede:field}
