{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院举办与台青年大学生圆桌会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2010-04-12 09:36:58{/dede:field}
{dede:field name='body'}<p>　　4月7日中午，中国人民大学社会与人口学院在2419教室举办了&ldquo;我和你：与台青年大学生圆桌会议&rdquo;。活动由社会与人口学院廖菲副教授发起，邀请来自台湾辅仁大学、台湾政治大学和台湾清华大学的6名交换生，与我校09级社会学系硕士生交流对话，受到了同学们的热烈欢迎。 </p>
<p>　　会议流程紧凑新颖，气氛友好开放，话题设置由浅入深、层层推进。&ldquo;前测&rdquo;环节，运用&ldquo;镜中我&rdquo;理论，要求与会同学列举几个词形容对方所在地区和居民，了解自己在对方心目中的形象，并就对方观点中的偏颇之处称述了自己的看法。&ldquo;快速连环问&rdquo;环节，以举手表决的方式，推选出了两岸大学生各自喜爱的明星、休闲的方式、心仪的职业和忧虑的问题，从而勾勒出了彼此的生活图景和价值观念。&ldquo;话题聚焦&rdquo;环节，通过深入讨论，比较了两岸高等学校在课堂互动、学生管理、治学风格等方面的差异，交换了对社会学在社会转型中的学科地位和历史责任的认识。 </p>
<p>　　本次圆桌会议的宗旨是&ldquo;沟通对话&mdash;&mdash;探究他者，重识自我&rdquo;。&ldquo;我们在征集交流话题的过程中，有台湾同学问道：&lsquo;为什么你们喜欢喝烧焦了的豆浆？&rsquo;一次偶然的遭遇被放大为普遍的现象，这就犯了盲人摸象的错误。同理，两岸青年学子之间，既有了解对方的好奇心和愿望，也存在不少片面的认识。圆桌会议的特点是平等、对话，本次活动就是一种增进两岸理解和情感的窗口的努力！&rdquo; </p>
<p>　　（编辑：於萍萍）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
