{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院龙翼飞教授等出席中国法学会婚姻法学研究会2010年年会暨婚姻法颁布60周年纪念会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图／文　法学院{/dede:field}
{dede:field name='pubdate'}2010-11-15 03:21:15{/dede:field}
{dede:field name='body'}<p>　　中国法学会婚姻法学研究会2010年年会暨婚姻法颁布60周年纪念会于11月6日至7日在海南海口举行。本次年会由中国法学会婚姻法学研究会主办，海南大学法学院承办。参加本次年会的代表主要有全国各高校从事婚姻家庭法学教学与研究的教师、研究机构的专职研究人员、司法实务部门的律师、法官等，共计130余人。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbmzffkb2ykf-2h2lf.jpg" alt="" /></p>
<p>　　本次会议的主要内容有纪念婚姻法颁布60周年、家庭暴力防治法主旨报告以及《婚姻法》司法解释（三）草案主旨报告。中国人民大学法学院龙翼飞教授主持了本次年会并作了人格权法的专题演讲，刘素萍教授作了关于纪念婚姻法颁布60周年专题演讲，孙若军副教授撰写的论文《离婚时处理按揭房屋的法律问题探析》获得学会2009&mdash;2010年度优秀科研成果论文类一等奖。</p>
<p>　　（编辑：苏璇）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzffkb2ykf-2h2lf_lit.jpg{/dede:field}
