{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院教师王孝松荣获第十六届安子介国际贸易研究奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月18日，第十六届安子介国际贸易研究奖颁奖典礼在对外经贸大学诚信楼报告厅举行，经济学院教师王孝松博士同他人合著的论文《美国对华贸易政策的决策和形成因素&mdash;&mdash;以PNTR议案投票结果为例的政治经济分析》（2009年1月发表于《经济学（季刊）》第8卷第2期）获得论文类二等奖。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbmzhnbyfmmf-znzh2z.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;安子介国际贸易研究奖&rdquo;在国际贸易研究领域中已经声誉卓著，被视为中国国际经贸领域中的最高学术奖。教育部已将该奖定为省部级奖，在国内外具有较大影响。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1290376529{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhnbyfmmf-znzh2z_lit.jpg{/dede:field}
