{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}河北东旭集团董事长李兆廷受聘中国人民大学董事会董事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}校报 孙诗颖{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月18日上午，河北东旭集团有限公司董事长李兆廷受聘中国人民大学董事会董事和教育基金会名誉理事。中国人民大学校长纪宝成出席聘任仪式，向李兆廷董事长颁发聘书、纪念牌。仪式由中国人民大学党委常务副书记牛维麟主持，河北东旭集团有限公司副总经理上官白阳，中国人民大学校长助理、学校办公室主任刘向兵以及招生就业处、教育基金会、文学院、体育部、校团委有关负责人出席聘任仪式。&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c101126/z2mfkyfhmhmnbhf-hzmfk.jpg" alt="" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 聘任仪式上，李兆廷董事长与中国人民大学教育基金会秘书长彭和平签署了捐赠协议，并向纪宝成校长递交了捐赠支票。&nbsp;</p>
<p align="center"><img src="/uploads/allimg/c101126/z2mfkyfhmbkzyzf-b2hfy.jpg" alt="" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李兆廷董事长在致辞中表示，他为加入中国人民大学的团队感到十分荣幸。他介绍说，东旭集团作为民族产业，在党和政府多年的关心、指导下不断积累经验，实现了快速的发展，并以其自主创新与多元化等突出特点得到了政府部门的积极评价与支持。李兆廷董事长表示，人民大学作为中国人文社会科学的重要基地在未来发展中具有不可估量的作用，他愿意为学校学生的实习、培训提供场所，并十分期待与学校在信息技术人才等方面加强交流与合作。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长在致辞中指出，教育与经济社会应和谐发展，他赞扬了李兆廷董事长作为企业家在社会发展中作出的杰出努力，对李兆廷董事长支持教育的举动表示感谢。纪宝成校长表示，学校一定会将李兆廷董事长捐赠的款项用好，并将主要用于学生培养和基础学科与新兴学科的建设。纪宝成校长提出，人文社会科学要从实践中吸取经验，希望学校能加强与东旭集团在培训、研讨、咨询等方面的合作。 <br />
<br />
■<strong>相关连接</strong>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李兆廷，1965年出生，中共党员，1986年毕业于河北工业大学，1997年创建河北东旭投资集团有限公司。现任东旭集团董事长、中国硅酸盐协会电子玻璃分会副理事长、河北省优秀青年企业家。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 东旭集团是一家集科技研发、产业投资、项目运营、工程设计、技术服务、工厂管理、资本运营和装备制造等于一体的大型多元化高科技产业集团。2010年东旭集团成功重组并控股大型国有企业石家庄宝石集团，李兆廷出任宝石集团董事长。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李兆廷董事长满怀振兴民族工业的赤子之情，以&ldquo;感恩做人，敬业做事&rdquo;为宗旨，率领300多名包括德国、日本、韩国、印度、台湾、中国大陆等海内外顶级专家和15000名高素质干部员工，用十年时间将东旭集团发展成为总投资230亿元，拥有五个产业集群，十大产业基地和两家上市公司的大型高科技产业集团，并力争再用五年时间将东旭集团发展成为全球最具竞争能力的高科技产业集团。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='pubdate'}1290111116{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhmhmnbhf-hzmfk_lit.jpg{/dede:field}
