{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院07－08级本科生党支部新生见面交流会顺利召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院新闻中心记者/孙雅晴{/dede:field}
{dede:field name='pubdate'}2008-10-15 06:11:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15日下午，&ldquo;靠近你、温暖我&rdquo;外国语学院07－08级本科生党支部新生见面交流会在明德国际楼310教室顺利召开。外国语学院党支部书记毕文锐主持了交流会。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 外国语学院分党委副书记齐畅出席会议并发表讲话。齐老师强调，大一新生不仅应该发愤学习，争当先进，还应该独立思考今后的人生，规划自己的人生，在政治上有所追求，在思想上有所进步。齐老师以外国语学院优秀学生党员代表为例，简述了学生党员的成长历程，希望大一学生主动要求进步，积极向党组织靠拢，同时希望同学们在严格要求自己的同时，牢记自己责任感与使命感，培养自己奉献精神与服务精神。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在介绍了党支部委员之后，党支部书记毕文锐向大一新生讲述了07－08级本科党支部的基本情况，指出在积极发展党员、增强党员的党性修养和理论水平的同时，开展一系列支部活动，建立一个属于我们自己的党支部是党支部的主要职责和任务。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大一新生党员和预备党员主动走上讲台与同学们见面，他们活泼多样的自我介绍一下了拉近了和其他同学的距离，让交流会的气氛变得轻松又温暖。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 党支部的几位委员分别上台分享了自己的入党感受，并从入党程序、党校学习等角度详细地为大一新生作介绍。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，大一新生听得津津有味，他们踊跃发言，提出自己对入党的疑问，分享自己对入党的感受，体验党支部生活的多姿多彩。 </p>
<p>&nbsp;</p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
