{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“黄达—蒙代尔讲座”：G20的费雪与凯恩斯视角及金融危机的全球应对{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-04-06 08:46:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月2日下午3:30，来自加拿大西安大略大学的经济学教授John Whalley在明德主楼801会议室举办小型学术报告会。会议以&ldquo;G20的费雪与凯恩斯视角及金融危机的全球应对&rdquo;为主题，曾在加拿大西安大略大学作访问教授和研究员的张顺明教授作为嘉宾介绍了John Whalley教授，我院应用金融系主任汪昌云教授也出席讲座，与John Whalley教授和张顺明教授共同探讨了相关学术问题。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlkhb2flkhf-zkmlh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为了让同学们更好地理解G20的作用，John Whalley教授从世界银行、国际货币基金组织和世界贸易组织的起源和发展， 讲到2008年全球金融危机，从而进一步解释到G20的成立是为了让有关国家就国际经济、货币政策举行非正式对话，以利于国际金融和货币体系的稳定。 随后，John Whalley教授与大家探讨了全球金融危机的政策回应等相关问题，并向在场同学介绍了他带来的费雪和凯恩斯的文集。他认为，面对金融危机的冲击，经济学家们应该多从先哲们的思想中获得灵感，不能固守数学模型。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;最后，在comments and questions环节中，John Whalley教授为同学们解答了疑惑，并与教授们简要交流相关的经济学思想。整个演讲持续约1小时，John Whalley教授独到的见解给同学们的思想带来了无尽的启迪。 <br />
&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （文 图/闫昕&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 编辑：陈汉南）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlkhb2flkhf-zkmlh_lit.jpg{/dede:field}
