{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京市破产法学会成立   法学院王欣新教授当选会长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-03 08:44:52{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月31日， 由中国人民大学法学院法学院、首都经济贸易大学法学院、北京市炜衡律师事务所等单位发起成立的北京市破产法学会第一次会员代表大会在北京友谊宾馆隆重召开。这是迄今为止中国成立的首家破产法学会。来自北京市及中央在京高等院校、科研机构、立法机关、人民法院、政府机关的法学、法律工作者以及律师、注册会计师、清算师等法律从业者共100多人出席了大会。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzybyykhyyf-zymf2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大会表决通过了《北京市破产法学会筹备工作报告》、《北京市破产法学会组织机构选举办法》、《北京市破产法学会章程》等文件，并按程序选举了理事、常务理事、会长、副会长、秘书长、副秘书长和监事长。中国人民大学法学院破产法研究中心主任、教授、博士生导师王欣新当选为会长。刘兰芳、尹义省、陈海鸥、钱晓晨、符启林、尹正友当选为副会长。尹正友兼任秘书长，刘敏、容红、赵继明、韩长胜、杨东当选为副秘书长。朱庆标当选为监事长。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;北京市法学会副会长杜石平为北京市破产法学会成立授牌并发表重要讲话。中国人民大学法学院院长韩大元教授到会致辞，祝贺学会的成立。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;北京破产法学会将对破产法领域重大理论和实务问题开展深入而务实的讨论，努力推进我国破产法研究工作，同时，参与立法、行政和司法机关的立法活动，就与破产法有关的法律、法规、规章和司法解释制订和完善提供参考意见。</p>
<p>（编辑：程远芳）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzybyykhyyf-zymf2_lit.jpg{/dede:field}
