{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}朱双和先生受聘为统计学院兼职教授{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-10-12 03:12:38{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp; 10月11日澳大利亚保险集团研发部主任、中国保监会非寿险部首席顾问朱双和先生被统计学院聘任为兼职教授，聘期三年。{/dede:field}
{dede:field name='litpic'}{/dede:field}
