<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","朱双和先生受聘为统计学院兼职教授",89,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",202,249);
$z[4][4]['name']="source";
$z[5]=Array("field","2006-10-12 03:12:38",251,310);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp; 10月11日澳大利亚保险集团研发部主任、中国保监会非寿险部首席顾问朱双和先生被统计学院聘任为兼职教授，聘期三年。",312,476);
$z[6][4]['name']="body";
$z[7]=Array("field","",478,517);
$z[7][4]['name']="litpic";

?>