{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院博士生赵斌等获中国医疗保险研究会2010年学术论文征集活动两个一等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-01-30 09:47:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 日前，公共管理学院社会保障研究所、医改研究中心博士生赵斌与硕士生严婵等合作的两篇论文《基本医疗保险关系转移接续问题研究&mdash;&mdash;基于权利与义务相对应的视角》和《城镇基本医疗保险门诊统筹费用支付方式探讨&mdash;&mdash;基于欧盟成员国门诊费用支付方式经验》获得中国医疗保险研究会2010年医疗保险学术论文征集活动两个一等奖，包揽了全部最高奖项。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次论文征集活动，中国医疗保险研究会面向全国有关医疗保险的机构和研究单位/大专院校征集论文，共征集到659篇论文。经匿名评审，专家委员会审核，产生优秀论文99篇，其中一等奖2篇，二等奖4篇，三等奖17篇，优秀奖76篇。 <br />
</p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
