{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院举办“祝贺张象枢教授执教58周年暨80寿辰学术研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2010-05-20 03:06:44{/dede:field}
{dede:field name='body'}<p>　　5月17日下午，人大环境学院在理工楼为环境经济学创始人、原环境经济研究所第一任所长张象枢教授隆重举行&ldquo;祝贺张象枢教授执教58周年暨80寿辰学术研讨会。&rdquo; </p>
<p>　　中国人民大学党委副书记马俊杰、中国人民大学工会常务副主席余浩、环境学院院长马中、环境学院党委书记刘鹏、副院长邹骥、副院长王洪臣等领导出席了研讨会。参加研讨会的还有人口、资源与环境经济学专业全体教师、在读研究生以及张教授的学生代表。会议由环境学院院长马中教授主持。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100622/z2kkzlnfbmyflyf-byz2y.jpg" /></p>
<p>　　首先，马中教授介绍了张象枢教授硕果累累的学术生涯，并代表大家对张象枢80大寿表示祝贺。马俊杰书记以风趣幽默的语言致以贺词，赞赏张教授谈吐儒雅、潜心教书育人。在热烈的掌声中，张教授接受了学生代表敬献的花篮。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100622/z2kkzlnfyflfhkf-ybzmb.jpg" /></p>
<p>&nbsp;</p>
<p>　　张教授做了题为《开来学 拓新路&mdash;&mdash;文明更替与环境社会系统科学与工程的任务》的学术报告。报告中指出，中国处在农业文明向工业文明，记忆工业文明向生态文明两种文明更替的特殊阶段。创建环境社会系统科学与工程对成功完成这一更替可能有一定作用。张教授分析了环境社会系统的特点及其存续与演化的前提条件并探讨了在两种文明更替背景下实现生产、生活和生态共赢的途径。张教授认为，应结合整体论和系统观解决环境社会系统中的问题。以保护和增强元生产力为途径，促进和保障环境社会系统的演进。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100622/z2kkzlnfyfkzbzf-khbyk.jpg" /></p>
<p>　　在不到一个小时的报告中，张象枢教授较为系统全面而又生动地为在场所有师生讲解了环境生态系统的运行。其旁征博引国内外各领域经典，视野广阔，展现了学术大师的巍巍风范。张教授&ldquo;多读书、多下乡、多交友&rdquo;的人生座右铭更是激励了在场的师生立学为民、严谨求学的热情。</p>
<p>　　<a href="http://envi.ruc.edu.cn/envicn/html/shiziduiwu/jiaoshou/2009/1114/666.html">相关链接：张象枢教授简介</a>&nbsp;</p>
<p>　　（编辑：苗育婧） <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfbmyflyf-byz2y_lit.jpg{/dede:field}
