{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院举行79级院友返校座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2009-10-26 04:11:20{/dede:field}
{dede:field name='body'}<p>　　10月24日下午，哲学院79级院友返校座谈会在人文楼五层会议室举行。校长助理、哲学院院长郝立新教授、副院长张风雷教授、韩东晖教授及原哲学院党委副书记朱淑然老师与返校的15名校友亲切座谈。</p>
<p>　　会上，郝立新院长向各位校友介绍了哲学院近年来的办学规模、发展情况及学科建设的突出特色。张风雷副院长与韩东晖副院长就校友们针对哲学学科发展的问题做出了解答。朱淑然老师与各位校友们一起回忆了三十年前大学时代的美好时光。院友们高度评价了哲学院的学科建设工作，并就哲学院如何长远发展这一主题展开了热烈的讨论，院友们纷纷表示愿意为母校的建设添砖加瓦，贡献自己的力量。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnhhklmlkf-zlhll.jpg" alt="" /></p>
<p>　　郝立新院长表示，哲学院将一如既往地坚持学院的优良传统，坚持正确的理论导向，坚持与时俱进，充分尊重教育发展和学科发展的规律，以师为本、以生为本，进一步加大学科建设力度，为实现哲学学科的全面繁荣贡献力量。座谈会在热烈的气氛中圆满结束。</p>
<p>　　（编辑：杨高敏）&nbsp;<br />
<br />
<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnhhklmlkf-zlhll_lit.jpg{/dede:field}
