{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}朱景文教授主编《中国法律发展报告——数据库和指标体系》获中国大学出版社图书奖首届优秀学术著作奖一等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-12-06 09:08:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在日前结束的中国大学出版社图书奖的评奖中，法学院朱景文教授主编的《中国法律发展报告&mdash;&mdash;数据库和指标体系》（中国人民大学出版社2007年版）获得中国大学出版社图书奖（优秀学术著作）一等奖。《中国法律发展报告》从2010年起已被纳入到人民大学研究报告系列，与经济发展报告，社会发展报告和人文社会科学发展报告并列为四大报告，也是法学院重点资助的标志性课题。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接： <a href="http://www.sinobook.com.cn/press/newsdetail.cfm?iCntno=11133">中国大学出版社图书奖（优秀学术著作）一等奖获奖名单 </a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
