<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","朱景文教授主编《中国法律发展报告——数据库和指标体系》获中国大学出版社图书奖首届优秀学术著作奖一等奖",89,227);
$z[2][4]['name']="title";
$z[3]=Array("field","",229,268);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",270,315);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-06 09:08:11",317,376);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在日前结束的中国大学出版社图书奖的评奖中，法学院朱景文教授主编的《中国法律发展报告&mdash;&mdash;数据库和指标体系》（中国人民大学出版社2007年版）获得中国大学出版社图书奖（优秀学术著作）一等奖。《中国法律发展报告》从2010年起已被纳入到人民大学研究报告系列，与经济发展报告，社会发展报告和人文社会科学发展报告并列为四大报告，也是法学院重点资助的标志性课题。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接： <a href=\"http://www.sinobook.com.cn/press/newsdetail.cfm?iCntno=11133\">中国大学出版社图书奖（优秀学术著作）一等奖获奖名单 </a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />\r\n<br />\r\n</p>",378,1096);
$z[6][4]['name']="body";
$z[7]=Array("field","",1098,1137);
$z[7][4]['name']="litpic";

?>