<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院代表团访问德国科隆媒体艺术学院",89,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",208,261);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-17 04:41:57",263,322);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应德国科隆媒体艺术学院邀请，人民大学徐悲鸿艺术学院王英健副院长及设计系部分教师于12月1日至6日访问德国科隆媒体艺术学院。双方就两院学科发展，特别是艺术学科的发展思路和经验进行了深入交流。&nbsp;</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110725/zlzzbyzhynzybbf-2bh2b.jpg\" alt=\"\" /></p>\r\n<p align=\"left\"><br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 德国科隆媒体艺术学院建院已有20年，但在德国仍然是最年轻的艺术学院。在其创办和建设过程中，德国政府起了很大的推动作用。学院现有3个主要学术方向：艺术与技术的结合、电影与电视、艺术媒体理论。学院的教学以鼓励学生自己找到自己的发展道路为基本方针，学生入学后的前两年采取各方向融合的教学方式，在第三年确定个人的具体发展方向。学院现有4年制本科生360名，理论方向博士生20人，计划将来招收5年制专业硕士。学院现有教学面积7100平米，教职工约100名。学院财政主要由政府及私人投资解决。目前，学院正积极地在全球范围内寻找5~6个合适的学术合作伙伴。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />\r\n</p>",324,1386);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhynzybbf-2bh2b_lit.jpg",1388,1480);
$z[7][4]['name']="litpic";

?>