{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《中国法律发展报告2010——中国立法60年》发布会暨学术研讨会在中国人民大学隆重举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-01 10:45:49{/dede:field}
{dede:field name='body'}<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fnflbyhf-znfnz.jpg" /></p>
<p>　　2月26日，中国人民大学《中国法律发展报告&bull;2010 &mdash;&mdash;中国立法60年》发布会暨学术研讨会在中国人民大学明德法学楼601国际学术报告厅隆重举行。出席发布会的有：全国人大常委会顾问、十届全国人大法律委员会主任杨景宇同志，中国人民大学校长纪宝成教授，最高人民检察院副检察长孙谦同志，中国法学会副会长周成奎同志，八、九届全国人大常委会法工委副主任、中国法学会立法学研究会会长张春生同志，中国人民大学副校长兼副书记王利明教授，全国人大常委会法工委国家法室主任许安标同志，司法部法制宣传司司长肖义舜同志，北京市检察院副检察长甄贞同志，国家法官学院院长高憬宏教授、国家检察官学院院长石少侠教授，教育部社科司规划处徐青森处长，中国人民大学科研处处长杜鹏教授，中国人民大学法学院院长韩大元教授、院党委书记兼副院长林嘉教授、副院长刘明祥教授、副院长胡锦光教授等，来自北京大学、清华大学、中国社科院、中国政法大学、中央党校、北京航空航天大学等兄弟院校和科研机构的知名学者，以及新华社、中央电视台、光明日报、法制日报、检察日报、北京电视台、新浪网、正义网等新闻媒体的代表等一百余人参加了此次会议。会议包括开幕式、中国法律发展报告发布暨学术研讨、媒体提问等三个单元，会议开幕式由中国人民大学出版社总编辑周蔚华教授主持。 </p>
<p>　　在开幕式上，中国人民大学校长纪宝成教授首先致辞。纪宝成校长说，在全国两会召开前夕，中国人民大学发布《中国法律发展报告2010&mdash;&mdash;中国立法60年》并举行学术研讨会，对中国60年立法的变迁，立法的相关内容做相关的研究和总结，具有重要意义。人民大学近年来连续推出了具有重要影响的研究报告，即中国经济发展报告、中国社会发展报告、中国人文社会科学发展报告，现在增加了中国法律发展报告。四大报告以事实说话，用数据说话，具有较高的学术水准和理论水平，产生了一定的社会影响，受到了国家和有关部门的高度重视和专家学者的广泛好评。中国法律发展报告的发布，发挥了中国人民大学的整体学科优势，系统总结了60年来的立法工作体制，立法机构，立法数量等方面的指标和内容，力求公正客观的评价。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fnfk2yhf-2bffz.jpg" /></p>
<p>　　纪校长表示，中国人民大学法学院成立于1950年，是新中国最早成立的法学院之一，是新中国创立的第一所正规的高等法学教育机构，被誉为中国法学教育的&ldquo;工作母机&rdquo;，在不同历史时期为中国法律的完善做出了的贡献，在教育部全国一级学科评估中，人民大学法学学科居全国第一。纪宝成校长希望与会的领导和专家提出建议帮助课题组进一步改进和完善研究工作，使中国法律发展报告成为一个更具权威性的法律指标体系，为建设社会主义法治国家做出更大的贡献。 </p>
<p>　　全国人大常委会顾问、十届全国人大法律委员会主任杨景宇同志，最高人民检察院副检察长孙谦同志、中国法学会副会长周成奎同志，八、九届全国人大常委会法工委副主任、中国法学会立法学研究会会长张春生同志等先后致辞。 </p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnfkkzzf-lbk2m.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnfnllbf-hzmyk.jpg" /></p>
<p align="center"><img height="531" alt="" width="333" src="/uploads/allimg/c110419/zlflzn2fnzz2hnf-bzzkl.jpg" /></p>
<p align="center"><img height="531" alt="" width="333" src="/uploads/allimg/c110419/zlflzn2fnzhllyf-yy2kb.jpg" /></p>
<p>　　中国人民大学党委副书记兼副校长王利明教授在讲话中指出，中国法律发展报告内容非常丰富，数据充实、完整，为法学研究提供了非常宝贵的资料。王利明副校长说，中国特色社会主义法律体系已经建立，我们还要认识到法律体系也是动态发展的，需要不断的完善，特别是现有的法律还要体系化。王利明副校长还以民法为例进行了阐述。王利明副校长表示，中国特色社会主义法律体系的完善和发展，我们法学工作者任重而道远，希望全体法律人共同努力，为社会主义法治建设作出更大的贡献。 </p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnznfkf-kbfl2.jpg" /></p>
<p>　　法学院院长韩大元教授代表会议承办单位向各位领导、专家和媒体朋友们的到来表示衷心的感谢。韩大元院长说，中国法律发展报告的编纂发布，是我们贯彻落实胡总书记视察人大重要指示精神的具体措施，也是人大法学院强化问题意识，强调以问题为导向进行研究，服务国家法治建设的理念的体现。2010年是中国特色社会主义法律体系形成之年，为了对新中国成立以来的立法机构设置，立法人员的构成以及立法程序做全面的研究，为社会主义法治建设提出有战略性和前瞻性的对策和建议，中国人民大学法律发展报告课题组推出了这一研究成果。人民大学将法律发展报告列为学校四大发展报告之一，说明中国人民大学高度重视法学学科的发展。韩大元院长向校领导表示感谢，同时也感谢洪范法律研究所、中国人民大学科研处、中国人民大学出版社给予的支持。韩大元院长还向与会代表介绍了我院根据国家十二五规划和国家发展战略所确定的近四年法律发展报告的主题。 </p>
<p align="center"><img height="531" alt="" width="333" src="/uploads/allimg/c110419/zlflzn2fn2znnf-nlmzy.jpg" /></p>
<p>　　第二单元的学术研讨和第三单元媒体提问由中国人民大学法学院副院长胡锦光教授主持。 </p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fn2b2yhf-mb2yk.jpg" /></p>
<p>　　朱景文教授首先就中国法律发展报告一书做了介绍。本报告由导论、全国人大及其常委会立法、国务院及其所属部委立法、各省、自治区、直辖市和较大的市立法、司法解释五部分组成。报告对中国立法的分析从四个层次进行，即全国人大及其常委会所制定的法律，国务院及所属各部委所制定的行政法规和部门规章（包括中央军委各总部、军兵种、军区发布的军事法规、规章），各省、自治区、直辖市所制定的地方法规和地方政府规章（包括国务院确定的较大的市所制定的地方法规和政府规章），最高人民法院和最高人民检察院所发布的司法解释（包括两高、司法部、公安部等联合发布的司法解释）。每个层次又分为立法机构、立法人员、立法程序、立法数量和立法种类五个方面。 </p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fn2mmnkf-zfbhkn.jpg" /></p>
<p>　　朱景文教授重点阐述了报告中的总结出的中国法律发展的规律，重点从立法轨迹、我国法律体系的&ldquo;中国特色&rdquo;、立法体制、立法专业化和民主化四个部分进行了详细阐述。 </p>
<p>　　在学术研讨阶段，全国人大常委会法工委国家法室许安标主任、中央党校研究生院院长卓泽渊教授、洪范法律与经济研究所所长梁治平教授、中国社科院法学所研究员刘作翔教授、清华大学法学院高其才教授、国家法官学院院长高憬宏教授、北京市人民检察院甄贞副检察长、中央党校法律部主任张恒山教授等先后作了评议。 </p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnlhlybf-zzbzlf.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnlnbhhf-z22klk.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnhlfnbf-zl2khn.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnhkhzbf-zhlmfm.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnb2lfnf-zb2fbn.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnbyklnf-zylfh2.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnyfnhf-zkymfh.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnybflyf-znzfkk.jpg" /></p>
<p align="center"><img height="333" alt="" width="531" src="/uploads/allimg/c110419/zlflzn2fnymkm2f-zmhzkl.jpg" /></p>
<p>　　本次研讨会最后，朱景文教授就新闻媒体提出的的问题一一作答。 </p>
<p>　　《中国法律发展报告2010 &mdash;&mdash;中国立法60年》由中国人民大学法学院朱景文教授主编的本报告受到洪范法律和经济研究所、中国人民大学科学研究基金（中央高校基本科研业务费专项资金资助）和中国人民大学法学院重点标志性项目的资助，2010年纳入中国人民大学发展研究报告报告系列。《中国法律发展报告2010 &mdash;&mdash;中国立法60年》是课题组继《中国法律发展报告&mdash;&mdash;数据库和指标体系》（中国人民大学出版社2007年版）之后推出的第二份权威力作，为中央宣布我国已经形成中国特色社会主义法律体系重大成果献上了一份厚礼。</p>
<p>&nbsp;　　（编辑：卢思颖 文静）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fnflbyhf-znfnz_lit.jpg{/dede:field}
