{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长应邀赴河南财经政法大学做报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月16日至17日，纪宝成校长应邀到河南财经政法大学做报告。在题为&ldquo;关于高等学校科学发展的几点思考&rdquo;的报告中，纪宝成校长提出，正确认识人文社会科学的内涵、特点和作用，促进人文社会科学的发展和繁荣是文科类高等院校贯彻落实科学发展观的重要方面。他指出，高等学校要实现科学发展，需要从把握方向、科学定位、内涵提高、特色强校、协调发展和加强领导等方面进行努力。纪宝成校长还回答了现场提问。河南财经政法大学校长李小建教授主持报告会，该校全体中层干部和教授出席会议。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长代表人民大学，对河南财经政法大学即将举行组建揭牌典礼表示祝贺，并带去了人民大学的贺信。纪校长还向河南财经政法大学图书馆赠送了《大学的探索》、《中国古代治国要论》、《中国统一市场新论》等著作。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在郑州期间，纪宝成校长还会见了人民大学河南校友会的有关负责人和校友代表，并向校友们介绍了学校目前的情况和胡锦涛总书记视察我校的重要讲话精神。校友们深受鼓舞，深感振奋。人民大学河南校友会会长、原河南省政协副主席赵江涛出席。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='pubdate'}1290019665{/dede:field}
{dede:field name='litpic'}{/dede:field}
