<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","学校第六届青年教师教学基本功比赛落下帷幕 7名教师获特等奖",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","校工会",226,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-04-14 03:54:51",273,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月13日下午，学校第六届青年教师教学基本功比赛复赛在公共教学一楼举行。法学院高仰光、公共管理学院唐钧、商学院蒋晶、马克思主义学院郗戈、财政金融学院张成思、物理系张威、化学系张璞等7位老师荣获特等奖，其他8位复赛选手荣获一等奖，只参加初赛的20位老师荣获优秀奖。</p>\r\n<p align=\"center\"><img height=\"333\" alt=\"\" width=\"500\" src=\"/uploads/allimg/c110418/zlflzzhbnfbkfnf-byk2k.jpg\" />&nbsp;</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校党委副书记、校工会主席马俊杰，副校长杨慧林等学校领导在人事处处长郭洪林、教务处副处长旋天颖等相关部门负责人陪同下，亲临赛场，认真听取了选手的现场精彩授课。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经过初赛的选拔，计有15位青年教师进入复赛，他们被分为两个组别进行复赛。在邀请专家评委和学生评委的同时，比赛面向全校征募学生观众和青年教师前来观摩，并得到了广大师生的积极响应，赛场气氛十分热烈。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href=\"http://news1.ruc.edu.cn/102392/75183.html\">学校第六届青年教师教学基本功比赛初赛举行</a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（编辑：文静）&nbsp;<br />\r\n</p>",334,1449);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110418/zlflzzhbnfbkfnf-byk2k_lit.jpg",1451,1543);
$z[7][4]['name']="litpic";

?>