{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}学校第六届青年教师教学基本功比赛落下帷幕 7名教师获特等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}校工会{/dede:field}
{dede:field name='pubdate'}2011-04-14 03:54:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月13日下午，学校第六届青年教师教学基本功比赛复赛在公共教学一楼举行。法学院高仰光、公共管理学院唐钧、商学院蒋晶、马克思主义学院郗戈、财政金融学院张成思、物理系张威、化学系张璞等7位老师荣获特等奖，其他8位复赛选手荣获一等奖，只参加初赛的20位老师荣获优秀奖。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110418/zlflzzhbnfbkfnf-byk2k.jpg" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校党委副书记、校工会主席马俊杰，副校长杨慧林等学校领导在人事处处长郭洪林、教务处副处长旋天颖等相关部门负责人陪同下，亲临赛场，认真听取了选手的现场精彩授课。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经过初赛的选拔，计有15位青年教师进入复赛，他们被分为两个组别进行复赛。在邀请专家评委和学生评委的同时，比赛面向全校征募学生观众和青年教师前来观摩，并得到了广大师生的积极响应，赛场气氛十分热烈。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href="http://news1.ruc.edu.cn/102392/75183.html">学校第六届青年教师教学基本功比赛初赛举行</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（编辑：文静）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbnfbkfnf-byk2k_lit.jpg{/dede:field}
