{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}杨立新教授和金玄卿讲师参加韩国“现代民事法的动向与发展”国际学术研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院   文/金玄卿{/dede:field}
{dede:field name='pubdate'}2010-12-14 08:39:53{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月26日，中国人民大学民商事法律科学研究中心主任杨立新教授和金玄卿讲师应邀参加了由韩国岭南大学法学院主办的国际学术研讨会，会议主题为&ldquo;现代民事法的动向与发展&rdquo;。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmhfylhmf-zhhnz.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在为期一天的国际会议中，法学院两位学者先后进行了主题发言。其中，杨立新教授以&ldquo;中国侵权责任法律制度的现状与展望&rdquo;为主题进行了发言，金玄卿讲师也以&ldquo;中国物权法的现状与展望&rdquo;为主题作了报告。此外，我国台湾地区东吴大学法律学系主任郑冠宇教授作了&ldquo;台湾物权法的发展&rdquo;的主题报告；韩国江原大学法学院安秉何教授作了&ldquo;韩国不当得利法的展望&rdquo;的主题报告。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议就上述问题以及中国和韩国的物权法、侵权责任法的发展问题，进行了深入的讨论。通过讨论，使与会者对中国的侵权责任法以及物权法的现状和发展有了更加深入的了解，对中国侵权责任法和物权法规定的很多新制度表现了极大的兴趣。 </p>
<p align="center"><img height="361" src="/uploads/allimg/c110113/z2mhnnhmhhy2k2f-2lk2y.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议取得圆满成功，与会各方都对此次合作和学术交流成果表示满意，并且决定在今后适当时候，进行再次合作。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmhfylhmf-zhhnz_lit.jpg{/dede:field}
