{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2011年“首都大学生心理健康节”在中国人民大学隆重开幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/学生工作部 图/新闻中心  罗豫伟{/dede:field}
{dede:field name='pubdate'}2011-04-08 01:59:21{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月7日上午，&ldquo;北京高校心理素质教育工作会暨2011年首都大学生心理健康节&rdquo;开幕式在中国人民大学逸夫会议中心第二报告厅隆重举行。教育部思政司司长杨振斌、市委教育工委常务副书记刘建、市委教育工委副书记王民忠、市教委副主任付志峰、团市委副书记刘震、中国人民大学党委副书记马俊杰以及各高校主管校领导、学工部长、心理咨询中心主任、学生代表等二百余人出席了开幕式。 <br />
</p>
<p align="center"><img src="/uploads/allimg/c110418/zlflzzhbyylzf-yzffl.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届&ldquo;首都大学生心理健康节&rdquo;活动主题为&ldquo;亲近你我，给力幸福&rdquo;，由市委教育工委、市教委举办，北京高教学会心理咨询研究会承办，各高校共同组织参加。活动旨在进一步推动北京高校心理素质教育工作，提升首都大学生心理健康水平，构建和谐校园。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式由北京市教委付志峰副主任主持。北京市委教育工委王民忠副书记在会上对心理健康节工作进行部署，鼓励各高校以生动活泼的形式开展系列活动，进一步拓展心理素质教育工作覆盖面，争取让每一个学生都了解心理健康知识，拥有健康的心态。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，中国人民大学学生代表闫东洁宣读了《2011年首都大学生心理健康节活动倡议书》。北京高教学会心理咨询研究会副会长蔺桂瑞教授介绍了《北京高校心理素质教育疾病预防与危机干预工作手册》的相关情况。中国人民大学、首都师范大学、北京科技大学三所高校做了经验交流。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学党委副书记马俊杰对各位领导和同行的到来表示热烈的欢迎，并率先向与会人员介绍了人民大学心理健康教育工作的理念、方法、内容和取得的成果。</p>
<p align="center"><img src="/uploads/allimg/c110418/zlflzzhbyyn2lmf-knm2f.jpg" width="483" height="322" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 他表示，作为国内较早配备专职工作人员进行大学生心理健康教育与咨询的高校之一，中国人民大学一贯重视对学生综合素质的培养，重视学生的健康成长、和谐发展。在持续完善学校学生心理咨询服务体系和制度的同时，中国人民大学的心理健康通识课经过了3年的教学实践尝试，得到广大学生的认可。在学期末学校进行的课堂教学效果评价中，心理健康教育与咨询中心的三位授课教师的评价分数保持在90-93分（满分为95分）的水平。心理健康通识课成为了一门学生想听、爱听、切实发挥作用的&ldquo;口碑课&rdquo;。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨振斌司长在会上讲话。他指出，根据2009年卫生部公布的数据，教育部直属高校大学生的自杀率维持在较低水平，这得益于现阶段大学生心理健康教育工作有条不紊的开展。他特别肯定我校心理健康通识必修课的教学模式，鼓励高校互相学习交流，做到心理健康教育的&ldquo;全覆盖&rdquo;。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后市委教育工委常务副书记刘建做了会议总结，并预祝本次心理健康节圆满成功。 </p>
<p>（编辑&nbsp; 燕燕）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbyylzf-yzffl_lit.jpg{/dede:field}
