{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院陈彦斌教授主持的国家农业部“十二五”规划重点研究课题顺利完成{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-04-02 06:09:23{/dede:field}
{dede:field name='body'}<p>　　近期，经济学院院长助理陈彦斌教授主持的国家农业部农业和农村经济&ldquo;十二五&rdquo;规划重点研究课题《&ldquo;十二五&rdquo;时期宏观经济走势对农业农村经济影响研究》顺利完成。课题成果在深入分析&ldquo;十二五&rdquo;期间世界经济走势和我国宏观经济走势的基础上，全面研判了其对农业农村经济发展带来的机遇和挑战。成果受到农业部有关领导的高度评价，部分成果将体现在《全国农业和农村经济发展第十二个五年规划》和《现代农业发展规划》中。 <br />
　　农业和农村经济&ldquo;十二五&rdquo;规划重点研究课题由农业部设立，旨在对涉及&ldquo;十二五&rdquo;农业和农村经济发展全局的一系列重大问题开展研究，为科学编制《农业和农村经济发展第十二个五年规划（2011-2015年）》提供决策参考。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
