{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院副教授和博士后入选第二届中国法学青年论坛主报告人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-20 03:29:05{/dede:field}
{dede:field name='body'}<p>　　4月17日，第二届中国法学青年论坛在中国政法大学昌平校区隆重举行，此次论坛的主题为&ldquo;法律传统、法律移植与法律输出&mdash;&mdash;全球浪潮中的中国法治之路&rdquo;。经过严格评审，法学院杨东副教授、博士后研究人员王建学的论文从八十余篇论文中脱颖而出，均被遴选为此次论坛的主报告人。</p>
<p>　　中国法学青年论坛是面向全国法学青年的高规格、多学科、宽领域的学术交流平台，其宗旨在于发现、汇聚和培育青年法学人才，推动法学理论和法治实践创新；呼吁全社会关注法学青年的成长，帮助青年才俊更快地脱颖而出；使论坛成为法学新秀辈出的&ldquo;孵化器&rdquo;，打造出中国未来法学家的&ldquo;名人堂&rdquo;。作为论坛的共同发起单位，首期论坛暨启动仪式已于2009年12月28日在中国人民大学法学院成功举办，产生了较大的社会影响。本次论坛的12名主报告人中，中国人民大学法学院就有两位，充分显示了人民大学青年法学人才的风采和实力。 </p>
<p>　　此外，法学院的朱景文教授、范愉教授和马小红教授应组委会邀请，担任了大会的单元总主持人、单元总评论人和评论人。</p>
<p>&nbsp;</p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
