{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院学生受邀参加美国使馆世界地球日活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-05-04 11:05:01{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月22日是世界地球日。为了庆祝地球日，美国驻华大使馆美国教育交流中心举行了&ldquo;庆祝世界地球日，环保电影观影与讨论&rdquo;活动，中国人民大学环境学院22名学生特别受邀参加了此次活动，在美国大使馆度过了一个愉快的夜晚。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参加活动的学生先后观看了关于当今环境问题和可能解决途径的纪录片《第十一个小时》、《蜜蜂的消失》，听取了美国大使馆工作人员关于影片的介绍，并与环境专家进行了交流和互动。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
