{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学哲学院温海明副教授赴夏威夷参加国际非暴力研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-11-22 08:59:38{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学哲学院温海明副教授于10月2日至16日在夏威夷参加国际非暴力研讨会时发表了题为《中国儒家非暴力哲学 Confucianism as a non-violent philosophy》的演讲。温教授以深厚的学养和中西比较哲学的学术视野阐发了儒家哲学的非暴力性质。温教授指出，儒家哲学诞生在礼崩乐坏、诸侯纷争、人心失范的春秋末期，是在充满屠杀（killing）的血腥时代背景中产生的规范世道人心的非屠杀（non-killing）、非暴力（non-violent）哲学思想体系。在中国漫长的历史长河中，儒家哲学的非暴力性质经受住了各种各样的考验。历朝历代的儒家学者信守&ldquo;修身齐家治国平天下&rdquo;的和合太平理想，在异常艰难的时代困境面前躬身自省、&ldquo;克己复礼&rdquo;，以期达到&ldquo;天下归仁&rdquo;的大同之境，其间克服了各种各样的理论和现实困难。如今虽然世界范围内的屠杀和暴力还在继续，但是经历了历史上长期血与火的洗礼的儒家哲学将不比圣雄甘地（Mohandas Karamchand Gandhi）和马丁&bull;路德&bull;金（Martin Luther King, Jr）的非暴力思想逊色，儒家哲学的非暴力维度必将能够在建构一个日趋和平、并逐步消灭屠杀（non-killing）的和谐世界中。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这是中国学者第二次参加此研讨会，上次参加该研讨会的是中国政治学元老、北京大学资深教授赵宝煦先生。会议参加者来自全球五大洲二十余个国家，与会者围绕如何在当今这样一个充满暴力和屠杀的时代把世界建设成为一个和平、和谐的非暴力、非屠杀的世界而努力。会议的主题涉及全球非暴力运动的历史、文化和哲学，屠杀与非屠杀的思想、历史与现状，建构非屠杀世界的挑战、问题和可能性等等。出席该研讨会和发表演讲的有美国总统奥巴马的妹妹Dr. Maya Soetoro-Ng，爱尔兰诺贝尔和平奖获得者Mairead Maguire，利比里亚的参议员，东西方中心和亚太研究中心的专家学者等等。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该国际研讨会的主办方是全球非屠杀研究中心（Center for Global Nonkilling , CGNK），该中心几十年来在当代著名非暴力政治学者Glenn D. Paige的领导下，致力于在全球范围内促进非暴力和非屠杀的研究和宣传，Paige的重要著作《全球非屠杀政治学 Nonkilling Global Political Science》已经被翻译成多国文字，在世界范围内产生了重要影响。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该中心目前正在全球范围内寻求合作伙伴，以期为建构一个和平、和谐、安全的非屠杀世界而努力。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As our Governing Council and Leadership Team are based around the world, we need to expand our funding base around the world. To that end, we seek your counsel and ideas. If you are aware of institutions, organizations or individuals in your sphere of influence who you think might become advocates and potential financial supporters of CGNK's mission, please contact Professor Greg Bourne at gbourne@nonkilling.org . </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If you can &quot;open the door&quot; to potential supporters, Professor Bourne can follow-up and begin discussions with them, either jointly or separately. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
