{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学校友骆惠宁当选青海省省长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月30日，在青海省第十一届人民代表大会第三次会议上，中国人民大学校友骆惠宁当选为青海省人民政府省长。经济学院杨瑞龙院长向骆惠宁校友发去贺信表示热烈祝贺。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 骆惠宁，男，汉族，1954年10月生，籍贯浙江省义乌市，生于安徽省当涂县，1970年9月参加工作，1982年3月加入中国共产党。2000－2003年就读于中国人民大学经济学院政治经济学专业，获经济学博士学位。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2007年人民大学70周年校庆期间，骆惠宁校友和国家质量技术检验检疫总局副局长、十七届中央纪委委员支树平校友曾率经济系2003届博士生向学校和学院分别敬赠了校庆纪念铜鼎，祝愿母校、母院事业鼎盛，桃李满天下。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1264990588{/dede:field}
{dede:field name='litpic'}{/dede:field}
