{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第三届明德杯八院友谊辩论赛圆满落幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2010-12-24 11:02:05{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月18日晚，第三届明德杯八院友谊辩论赛决赛在明法楼0301打响。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 决赛的辩题是：人生不能重来是喜剧还是悲剧。本次决赛邀请了5位在人大辩坛驰骋了多年的硕士研究生担当评委，并由外国语学院辩论队队长林迪尼担任主持。而今天的主角&mdash;&mdash;从三轮选拔中脱颖而出的6位参赛辩手，个个身经百战，实力不凡。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 正式比赛开始前，比赛现场播放了由主办方精心准备的人大明星辩手们感人至深而又令人捧腹的寄语，其中也包括上届明德杯六位决赛辩手的祝福。其后决赛正式开始。首先是一辩陈词环节。正方一辩提出人生不能重来符合人的独特性、人生的特性及人生的未知性，人生的遗憾和懊悔让我们学到经验、懂得把握，主张人生不能重来是喜剧。反方一辩巧用比喻击破对方立论，随后旁征博引诗词歌赋引出人生不能重来是悲剧的论点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 对辩环节是明德杯的特色环节。叶恬阅在她的对辩中，敏锐地指出对方把事物的影响和事物本身混为一谈，从而抓住对方漏洞，进行了精彩的论证。在随后的自由辩环节中，双方你来我往，你推我挡，抓漏洞，找矛盾，比赛进入高潮。在正反双方情理并举的总结陈词中，比赛结束。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 国际关系学院09级硕士研究生许瑶师姐对本次辩论赛做了精到的点评，她肯定了决赛选手的水平，期待选手更好的表现。最终，评委裁定反方为获胜队。财政金融学院10级的周莹摘得最佳辩手称号。其他五位辩手获得优秀辩手称号。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 至此，&ldquo;第三届明德杯八院友谊辩论赛&rdquo;圆满落幕。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
