{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}何家弘教授参加国际错案研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-04-14 02:25:26{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;4月7日至11日，何家弘教授应邀参加了在美国辛辛那提市举行的&ldquo;2011年无辜者协作网研讨会&mdash;&mdash;错判的国际探索&rdquo;（2011 Innocence Network Conference: an International Exploration of Wrongful Conviction）。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;无辜者协作网是一个松散型民间组织，每年召开一次研讨会。最初只有美国的无辜者中心参加，后来吸收了英国、加拿大等国的无辜者中心参加，至今已召开了11届。今年第一次邀请其他国家关注刑事错案问题的专家和学者参加，因此称为&ldquo;首次国际错案研讨会&rdquo;。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次研讨会共有来自二十多个国家的约500人参加，其中颇为引人注目的是102位已被平反的&ldquo;老冤&rdquo;。他们绝大多数是美国人，也有几个外国人，分别来自日本、墨西哥、尼加拉瓜等国家。何家弘教授在研讨会上做了主题发言，介绍了中国大陆地区刑事错案问题的研究情况，并且与其他国家的专家学者进行了内容广泛的交流。何家弘教授在正义网的法律博客上发表了&ldquo;国际错案研讨会的日志和照片&rdquo;。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fbkhh2zf-myymb.jpg" /></p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fbkkn2yf-zfyzky.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;（编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fbkhh2zf-myymb_lit.jpg{/dede:field}
