{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}耶鲁大学法学院葛维宝教授一行访问中国人民大学法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 09:59:16{/dede:field}
{dede:field name='body'}<p>　　4月9日下午，王利明副校长、韩大元院长在明德法学楼206会议室会见了耶鲁大学法学院中国法律研究中心主任葛维宝教授（Paul Gewirtz）一行，民商法教师教研室张新宝教授、姚辉教授、杨立新教授、朱岩副教授陪同参加了会见。</p>
<p>　　耶鲁大学葛维宝教授一行此次访问人民大学法学院的目的是参加由中国人民大学法学院与耶鲁大学法学院合作举办的&ldquo;大规模侵权法律对策国际研讨会&rdquo;。在此次国际研讨会中，耶鲁大学葛维宝教授、斯坦福法律学院Deborah R.Hensler教授、Norbert Wuehler博士、杜克大学法学院Francis E. McGovern教授等将进行主题发言。</p>
<p>　　会见中，韩大元院长向葛维宝教授简单介绍了法学院的情况，并指出，相比耶鲁大学法学院，人大法学院无论是在学生数量上还是在教员上，都比较庞大，所以不可能像耶鲁大学一样实行小班教学制，并向葛维宝教授咨询了小班教学的情况。葛维宝教授表示，实行小班教学，有利于在学生间组织讨论，学生也可以有更多的机会同教授进行交流，但小班教学需较高教学经费。耶鲁大学的教学经费，除了来自学生的学费外，大部分来自耶鲁大学基金会。他建议，人民大学也可以利用校友资源，培养校友对学校的归属感，倡导校友捐款，壮大校友基金会，以便将有更多的经费来支持学校的持续发展。此外，在学生培养方面，葛维宝教授表示，学校不仅要培养学生学习能力、与他人合作能力及适应社会的能力，更要注重培养学生成为一个优秀的领袖能力。耶鲁大学也在朝着这方面努力。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fyz2lfyf-zlzyh.jpg" /></p>
<p>　　会见结束后，王利明副校长、韩大元院长向葛维宝教授一行赠送了学院礼物。</p>
<p>　　(编辑：席嘉怡)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fyz2lfyf-zlzyh_lit.jpg{/dede:field}
