{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/100613/2-zffyzlfm2kfl.jpg' text='中国人民大学校园环境' width='450' height='300'} /uploads/allimg/100613/2-zffyzlfm2kfl.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100613/2-zffyzlfm2kfy.jpg' text='中国人民大学校园环境' width='450' height='300'} /uploads/allimg/100613/2-zffyzlfm2kfy.jpg {/dede:img}
