<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/100613/2-zffyzlfm2kfl.jpg ",93,260);
$z[1][4]['ddimg']="/uploads/allimg/100613/2-zffyzlfm2kfl.jpg";
$z[1][4]['text']="中国人民大学校园环境";
$z[1][4]['width']="450";
$z[1][4]['height']="300";
$z[2]=Array("img"," /uploads/allimg/100613/2-zffyzlfm2kfy.jpg ",262,429);
$z[2][4]['ddimg']="/uploads/allimg/100613/2-zffyzlfm2kfy.jpg";
$z[2][4]['text']="中国人民大学校园环境";
$z[2][4]['width']="450";
$z[2][4]['height']="300";

?>