{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大经济研究所创办中国宏观经济论坛月度数据分析报告会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为进一步增强宏观经济研究的及时性和新鲜度，中国人民大学经济研究所、经济学院在多次成功举办中国宏观经济论坛的基础上正式创办了月度数据分析报告会。报告会每月一次，在每个月国家统计部门发布当月宏观统计数据后，对本月（或本季度）的宏观经济数据进行深度解读；同时邀请1-2名相关领域的资深宏观经济学家作为嘉宾进行深入点评和讨论，并与参会师生展开研讨。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月12日，由该报告会的第一期活动&mdash;&mdash;中国宏观经济论坛月度数据分析报告会（2010年3月）在明德主楼经济学院617会议室举办。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzhkyhybzbf-hkny2.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告会由中国人民大学经济学院副院长、经济研究所联席副所长刘元春教授主持。泰康资产管理公司首席经济学家张敬国研究员、国家信息中心经济预测部宏观经济研究室主任牛犁研究员、经济学院院长杨瑞龙教授、经济学院胡乃武教授、研究生院副院长刘凤良教授以及经济研究所的研究人员参加了报告会。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告会上，经济学院院长助理王晋斌教授发布了题为《经济未过热、通胀渐行渐近，全年出现&ldquo;双超&rdquo;态势》的月度数据分析报告。王晋斌教授通过对1-2月份数据的解读，认为经济未出现过热现象。他认为，目前中国的消费恢复性增长，投资处于次高位运行，全年财政赤字预算规模加大，赤字/GDP比例与去年接近，进出口同比上升，环比下降，出口形势不容乐观，规模以上工业增加值出现复苏性增长，经济流动性的交易需求处于引而未发状态。因此，中国经济目前还不是强劲的&ldquo;V&rdquo;型反转，也不是&ldquo;W&rdquo;型调整，而是处于回升态势，但经济内生性的需求仍处于企稳&mdash;复苏的中间态势。2010年中国经济GDP增长将超过8%，通货膨胀率可能超过3%，出现&ldquo;双超&rdquo;态势。王晋斌教授还分析了中国经济运行中存在的主要风险：人民币汇率升值压力和通货膨胀风险。报告最后提出了相应的政策建议。精彩的演讲获得了现场观众的阵阵掌声。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100619/z2kymzhkybnyyhf-bmlf2.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张敬国研究员发表了自己的观点。作为金融企业的研究人员，他的分析的角度和视野与高校并不相同。他认为，目前中国经济出现很明显的过热现象，而中国的利率水平还偏低。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛犁研究员通过对1-2月宏观数据进行分析，认为通胀压力的上升使得政府刺激政策面临退出压力。同时，由于各类贸易摩擦不断增加，人民币升值压力加大。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经济学院的师生也就当前关注问题与几位主讲人及嘉宾展开了热烈的交流，现场气氛十分热烈，经济思想在碰撞中得以升华，在讨论中加以深化。两个小时匆匆过去，与会的老师和学生都感到意犹未尽。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经济观察报、21世纪经济报道等多家媒体参加并报道了此次月度数据分析报告会。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1268620982{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkyhybzbf-hkny2_lit.jpg{/dede:field}
