{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院土地管理系成功举办“2010年第二届全国土地资源管理博士生论坛”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-11-22 08:31:53{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月13日，由全国土地资源管理院长（系主任）联谊会发起，中国人民大学公共管理学院土地管理系、土地政策研究中心和《中国土地科学》联合主办的&ldquo;2010年第二届全国土地资源管理博士生论坛&rdquo; 在中国人民大学成功举办。来自中国人民大学、中国农业大学、中国地质大学（北京）、南京农业大学、中国矿业大学（徐州）等招收土地资源管理博士生高校的60余名博士研究生集聚一堂，围绕&ldquo;发展方式转变与土地合理利用&rdquo;主题，就土地资源管理领域的最新研究成果进行了广泛交流。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhbzkfblf-ybzlb.jpg" alt="" /></p>
<p align="center">图为土地管理系主任叶剑平主持开幕式</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhb2zmnhf-khfyb.jpg" alt="" /></p>
<p align="center">图为土地管理系前任系主任、专业创始人林增杰致辞</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 公共管理学院土地管理系主任叶剑平主持开幕式并致欢迎词，对出席本次论坛的专家和博士研究生表示热烈欢迎。公共管理学院土地管理系前任系主任、专业创办人林增杰，国土资源部土地整理中心副主任郧文聚研究员，南京农业大学公共管理学院院长欧名豪先后致辞，表达了对此次论坛的重视与期望，希望广大博士生注重自身理论水平的提高，关心国家发展，热爱土管事业，充分利用好论坛平台开展学术交流。南京农业大学副校长曲福田，中国土地勘测规划院副院长高平研究员、南京大学国土资源与旅游学系主任黄贤金，中国地质大学（北京）土地管理系吴克宁，《中国土地科学》编辑部主任冯广京研究员，台湾逢甲大学土地管理学系韩乾在专家席就座。公共管理学院副院长严金明、土地管理系吕萍等教师出席了开幕式，土地管理系博士生、硕士生和本科生参与了本次论坛活动。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhb22mnmf-nhkmm.jpg" alt="" /></p>
<p align="center">图为公共管理学院副院长严金明做主题演讲</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式后举行了四场精彩主题报告：南京农业大学副校长曲福田做了题为&ldquo;城乡统筹与土地管理制度创新&rdquo;的主题演讲。曲教授从问题的起源、城乡统筹的实质、城乡统筹中的土地问题、基于城乡统筹的土地制度创新等四个方面进行阐述，报告深入浅出，令人深思；中国土地勘测规划院副院长高平研究员做了&ldquo;当前土地研究热点问题&rdquo;的主题演讲，她全面分析了我国土地管理当前面临的形势和挑战，对&ldquo;如何实现数量管理与质量管理、生态管护并举&rdquo;、&ldquo;如何实行差别化的土地利用管理&rdquo;、&ldquo; 如何促进土地利用方式的根本转变&rdquo;、&ldquo; 如何运用高新技术促进土地利用方式转变&rdquo;等热点问题谈了自己的观点；台湾逢甲大学韩乾教授就&ldquo;土地的伦理观&rdquo;进行了演讲；公共管理学院副院长严金明做了题为&ldquo;城乡统筹发展与土地制度改革的导向选择&rdquo;的主题演讲，探讨了城乡规划与城乡土地增减挂钩等问题，并对农地增值分配谈了自己的构想。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhb2lnmf-mbnkb.jpg" alt="" /></p>
<p align="center">图为分论坛讨论现场</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 主题演讲结束后，60余位论文作者分别在五个分论坛&mdash;&mdash;&ldquo;集体土地征收、流转与耕地保护&rdquo;，&ldquo;土地整理与土地利用方式转变&rdquo;，&ldquo;土地利用效率与效益&rdquo;，&ldquo;土地利用与社会协调发展&rdquo;及&ldquo;土地制度改革&rdquo;上与大家分享了自己的研究成果和学术心得。来自不同高校的博士生聚集一堂，相互切磋，气氛十分活跃。论坛最后由专家评选出20篇优秀论文。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次论坛为全国土地资源管理专业的博士研究生搭建了一个高起点、大范围、多领域的学术交流平台，提供了一个学术交流和思想启迪的机会，对全国土地资源管理学科高层次人才培养将产生积极影响。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhbzkfblf-ybzlb_lit.jpg{/dede:field}
