{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}澳大利亚新西兰政府学院Allan Fels教授为公共管理学院师生做讲座{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-10-20 04:18:24{/dede:field}
{dede:field name='body'}<p>　　10月19日下午，应公共管理学院&ldquo;公共管理创新与发展高层论坛&rdquo;之&ldquo;知名学者论坛&rdquo;（第十八讲）的邀请，澳大利亚新西兰政府学院Allan Fels教授为公共管理学院师生做了题为&ldquo;行政垄断：澳大利亚、美国、欧盟以及中国的实践&rdquo;的专题讲座。曾经来公共管理学院访问过的澳大利亚Monash Universtiy的Owen Hughes教授以及原英国约克大学的Mark Evans教授一同来访。本次讲座由公共管理学院院长助理刘昕教授主持。</p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c101124/z2mfbnnhbnkly2f-2nhfm.jpg" /></p>
<p>　　Allan教授主要围绕市场竞争与反垄断的公共政策问题展开，讨论了美国、澳大利亚以及欧盟等在反垄断以及促进市场竞争方面的立法和政策，重点强调了澳大利亚政府在协调各种竞争政策方面的主要做法（Allan教授自1995-2003担任澳大利亚竞争与消费者委员会主席），同时也结合他对中国竞争问题的研究分析了中国的竞争法律以及竞争政策问题（Allan教授是中国竞争问题研究中心联合主任）。在讲座中，Allan教授还谈到在反垄断方面所面临的一些政策困境。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbnnhbmz2hhf-lk2nm.jpg" /></p>
<p>　　最后，Allan教授与参加讲座的同学进行了精彩的对话，同学们结合国内存在的各种垄断和竞争问题与教授展开了热烈的讨论。讲座结束时，公共管理学院董克用院长向AlIan Fels教授赠送了纪念相框。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhyfflyyf-hbnbk.jpg" alt="" /></p>
<p align="justify">　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhbnkly2f-2nhfm_lit.jpg{/dede:field}
