{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院土地管理系代表团赴台参加第十五届亚洲房地产学会年会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-07-20 09:33:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年7月9-12日，公共管理学院土地管理系部分师生参加了在台湾高雄市举办的第十五届亚洲房地产学会年会，这是近期土地管理系继出席世界华人不动产学会第二届年会后赴台参加的又一项大型学术交流活动。来自美洲、欧洲、亚洲、澳洲及两岸四地学术机构、商业团体和政府部门的近300位专业人士参加了本届年会。亚洲房地产学会是目前世界上最有影响力的房地产学会之一，每年在世界各地举行年会暨国际房地产研讨会。</p>
<p>&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议期间，与会嘉宾就当前亚洲房地产市场的热点问题进行了讨论，其中来自美国德克萨斯大学奥斯丁分校的Sheridan Titman教授和加州大学伯克利分校的Robert H. Edelstein教授分别发表了题为《集聚agglomeration与交通：区位的价值》和《全球房地产市场、金融体系和世界经济》的主旨演讲。此外会议举办了4个圆桌论坛，讨论了可支付住房、宏观调控下房地产市场在金融危机中的表现、房地产信托投资基金（REITs）、绿色城市与房地产市场发展等问题；会议还包括7个分组讨论议程，发表论文200多篇。此次会议的召开对亚洲房地产市场尤其是我国房地产市场在后金融危机时期的发展具有重要意义。 <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
