{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院朱大旗教授应邀在人民大会堂和网民就《车船税法（草案）》有关问题开展互动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图／文　法学院{/dede:field}
{dede:field name='pubdate'}2010-12-20 02:49:05{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月25日至28日举行的十一届全国人大常委会第十七次会议对《车船税法（草案）》进行了初次审议，引起社会的广泛关注。常委会会议后，全国人大常委会办公厅通过中国人大网全文公布了《车船税法（草案）》，向社会征求意见。迄11月30日，中国人大网共收到97295条意见和40封群众来信。在征求意见期间，有关报刊、媒体和网站也陆续登载了社会有关方面对《车船税法草案》的意见和建议。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为便于大家进一步了解《车船税法（草案）》，听取人民群众对车船税法修改工作的意见和建议，12月17日上午，由人大常委会法工委组织，中国人大网、人民网、新华网联合邀请全国人大常委会法工委有关部门负责同志和税务法律专家在人民大会堂台湾厅举行在线访谈，就《车船税法（草案）》的有关问题与公众互动，现场交流大家关心的问题。 </p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110113/z2mhnnhmbkfkfbf-2kkyl.jpg" alt="" /></p>
<p>　　法学院经济法教研室朱大旗教授和全国人大常委会法工委经济法室黄建初主任、财政部财政科学研究所副所长苏明研究员、中央财经大学高萍副教授应邀出席。朱大旗教授主要就《车船税法（草案）》&ldquo;为什么不以车船价值而以排气量作为计税依据&rdquo;和&ldquo;不需要办理车船登记的企业内部作业车船为什么也要缴纳车船税&rdquo;的问题和网民进行了互动。 </p>
<p>　　（编辑：王强）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhmbkfkfbf-2kkyl_lit.jpg{/dede:field}
