<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院杨瑞龙院长看望慰问宋涛教授家属",89,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",208,255);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-13 04:08:14",257,316);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　2月11日下午，杨瑞龙院长看望慰问宋涛教授家属，对宋涛教授逝世表示悼念。杨瑞龙院长表示要尽全力办好宋涛教授的后事和悼念活动，并就相关事宜征求了宋涛教授家属的意见。宋涛教授家属表示感谢。 <br />\r\n　　经济学院党委副书记丁凯陪同看望。 </p>\r\n<p>\r\n</p>",318,604);
$z[6][4]['name']="body";
$z[7]=Array("field","",606,645);
$z[7][4]['name']="litpic";

?>