{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙院长看望慰问宋涛教授家属{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-13 04:08:14{/dede:field}
{dede:field name='body'}<p>　　2月11日下午，杨瑞龙院长看望慰问宋涛教授家属，对宋涛教授逝世表示悼念。杨瑞龙院长表示要尽全力办好宋涛教授的后事和悼念活动，并就相关事宜征求了宋涛教授家属的意见。宋涛教授家属表示感谢。 <br />
　　经济学院党委副书记丁凯陪同看望。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
