{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}香港城市大学课程进修班学生到法学院学习访问{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-27 09:05:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月21日至23日，香港城市大学法学院的17位2008级进修生由香港校友会负责人徐晶带队，来人大法学院进行学习访问。院长韩大元教授、主管副院长胡锦光教授、院党委副书记郑小敏老师、院团委书记兼办公室主任乔鹏老师分别接见了到访团成员。法学院专门为访问团学员组织了法学界热点问题简介座谈会。刘计划、邵明、史际春、莫于川、时延安等老师分别介绍了当前法学界热点问题。座谈会由胡锦光副院长主持，郑小敏副书记参加。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 香港学生还旁听了法学院在校硕士生答辩，教务秘书为他们介绍了答辩的全过程。另外图书馆为来访的香港学生制作了院图书馆的阅览证。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
