{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院创先争优系列活动之一：行政管理学系本科学生党支部重阳节慰问人大社区老职工{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-10-19 03:18:04{/dede:field}
{dede:field name='body'}<p>　　10月16日下午，公共管理学院行政管理学系本科学生党支部16名学生党员来到人民大学社区，看望在这生活的老职工及职工家属。 </p>
<p>　　本次活动在社区内的老年活动室中进行。活动开始前，党支部成员为各位老职工及职工家属送上了事先购买的水果和温馨的祝福。活动以支部党员王鲲鹏同学的一曲《我和我的祖国》拉开序幕。随后，支部党员仲婧然、钱小宇、郭勇帅和马天航等同学分别为老奶奶们带来了小提琴独奏《梁祝》、二重唱《军港之夜》和京剧小段等节目。老奶奶们或为表演者拍手打着节拍，或随表演者哼唱起了那些熟悉的曲目。活动在欢乐愉快的气氛中进行着。表演活动的最后，党支部所有成员和老奶奶们一起合唱了歌曲《夕阳红》，以此表达党支部成员对所有老年人晚年美满生活的祝福。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhbblkbnf-llkly.jpg" alt="" /></p>
<p>　　表演活动结束后，曾受公共管理学院返聘的老职工董老师代表参加此次活动的老职工及职工家属和同学们进行交流。她首先对支部能开展本次关怀活动表示了由衷的感谢，并希望支部在今后的志愿服务工作中，能更多关注老年人，为老年人送去关怀和祝福。同时，董老师为我们介绍了其现在所做的社区公益工作，并表示，支部党员同学们的到来使他们倍感鼓舞，他们也将在今后的社区公益工作中更加努力。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhbyzlnkf-hybbf.jpg" alt="" />&nbsp;</p>
<p>　　本次活动是公共管理学院行政管理学系本科党支部&ldquo;创先争优&rdquo;系列活动的第一阶段活动。在接下来的一个月内，行管本科学生党支部还将举行政治理论学习与民主讨论会等活动，藉此全面提高支部党员的理论和实践水平。</p>
<p>　　&nbsp;
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhbblkbnf-llkly_lit.jpg{/dede:field}
