{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院第十届“经英杯”论文比赛拉开帷幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2009-12-15 03:06:15{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月25日下午，经济学院第十届&ldquo;经英杯&rdquo;论文比赛启动仪式在明德主楼728经济学院大讲堂举行，经济学院院长杨瑞龙教授出席仪式并致辞。同日下午和12月2日下午，第十届&ldquo;经英杯&rdquo;论文比赛的两场指导讲座也分别如期举行，经济学院院长助理郑新业副教授和校团委学术部副部长马文浩就论文写作对同学们进行了指导。第二场讲座结束后，第九届&ldquo;经英杯&rdquo;特等奖获得者蒋敏杰同学和王晗同学还和在座同学分享了他们参加论文竞赛的个人经验与感悟。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzhyhlnlh2f-bbfbb.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长在启动仪式上指出，举办&ldquo;经英杯&rdquo;论文比赛是提高学生科研素质的一个重要途径。对于学生而言，科研活动在大学本科学习中极其重要，科研能力是学分绩之外区分学生之间能力高低的另一个重要指标。因此，在掌握书本知识的基础上，学院鼓励学生积极参加课外科研活动，将理论和实践结合起来，活学活用。杨瑞龙院长还特别强调科研成果对于保研的关键作用。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在第一场指导讲座中，郑新业副教授向大家介绍了经英杯论文比赛的具体要求和选题建议。针对同学们不知道如何选择论文题材的问题，郑新业副教授分别对高年级和低年级的学生给出了不同的建议。他还详细列举和简单分析了一些典型的研究项目供大家参考。他还向同学们详细地介绍了论文的规范格式，着重提醒同学们要注明论文的数据来源，尊重他人的知识成果。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c100619/z2kymzhyhkkbzlf-ylbfm.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在第二场指导讲座中，马文浩副部长以表格的形式详细地列出了2001年以来，人大学生在全国&ldquo;挑战杯&rdquo;论文比赛的获奖情况，并对其中一些获奖论文进行了重点介绍。之后，马文浩副部长又简要介绍了首都&ldquo;挑战杯&rdquo;论文比赛和中国人民大学&ldquo;创新杯&rdquo;论文比赛。马文浩老师还提到，随着比赛层次的提高，学生将有更多的机会得到更多专家的指导，对于自身的学术发展将起到极大的促进作用。关于如何写好论文的问题，马文浩副部长着重强调论文选题的重要性。通过回顾获奖论文，他总结出选题最要注意的三方面：从高处着眼、从细处着手、从矛盾处着力。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhyhmkymzf-kbyzm.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在第二场指导讲座结束后，第九届&ldquo;经英杯&rdquo;特等奖获奖者蒋敏杰同学和王晗同学还和在座同学分享了他们参加论文竞赛的个人经验与感悟。蒋敏杰同学向大家介绍了写作论文前期准备中的调研方法、统计方法和论文写作的规范格式。王晗同学则强调了与老师进行课内外互动的重要性，并且指出参加各类学术比赛将为同学们以后学术的进一步发展打下良好的基础。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;经英杯&rdquo;论文比赛已经连续成功举办了九届，向学校&ldquo;创新杯&rdquo;和首都、国家&ldquo;挑战杯&rdquo;等赛事输送了大量优秀学术作品，也发掘了大批经济学人才。在已经结束的第九届&ldquo;经英杯&rdquo;论文比赛中，共评出理论类获奖作品16件，实践类获奖作品20件，另外又从获奖作品中筛选了15篇参加学校&ldquo;创新杯&rdquo;比赛。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhyhlnlh2f-bbfbb_lit.jpg{/dede:field}
