<?php
$z[0]=Array("match","<tr><td width=\"90%\" align=\"left\" valign=\"top\" style=\"PADDING-RIGHT: 20px; PADDING-LEFT: 20px;PADDING-BOTTOM: 20px;FONT-SIZE: 10.5pt; LINE-HEIGHT: 22px; TEXT-DECORATION: none\">[─┌╚▌]</td>\r\n	</tr>\r\n<tr><td><img src=\"http://images.ruc.edu.cn/templates/",5,279);
$z[1]=Array("trim","ги▒р╝нг║(.*)гй<br />",284,338);
$z[1][4]['replace']="";
$z[2]=Array("function","",343,374);

?>