{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杰出院友、安徽省副省长黄海嵩致函母院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-31 11:44:34{/dede:field}
{dede:field name='body'}<p>　　近日，经济学院杰出院友、安徽省副省长黄海嵩校友致函母院，对于学院推选他担任第二届院友会副会长表示感谢，并表示作为一名人大经济学院毕业的学生，为母院在人才培养和学术研究等方面取得的丰硕成果以及为国家建设和民族进步做出的重要贡献深感振奋和自豪，并表示将继续秉承人大精神，以人大优秀毕业学生为榜样，立足本职，恪尽职守，努力为母校增光添彩。 <br />
　　在2010年10月31日召开经济学院第二届院友大会前夕，黄海嵩院友向母院赠送了纪念铜鼎，上面镌刻&ldquo;资政国器&rdquo;四字，祝愿母校、母院千秋鼎盛、桃李芬芳。 </p>
<p><br />
<br />
黄海嵩校友简历 </p>
<p align="center"><img height="180" src="/uploads/allimg/c110113/z2mhnnh22hbknlf-nzbml.jpg" width="138" alt="" /></p>
<p><br />
　　黄海嵩，男，汉族，1953年7月生，河南禹州人，1972年9月参加工作，1984年6月入党，1984年9月至1986年7月在中国人民大学计划经济系国民经济计划学专业学习。在职研究生学历、管理学硕士。2004年2月至今安徽省政府副省长、党组成员。中共十六大代表，九届、十届全国人大代表，中共安徽省七届、八届委员会委员。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnh22hbknlf-nzbml_lit.jpg{/dede:field}
