{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}华南理工大学经济与贸易学院代表团访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月9日上午，华南理工大学经济与贸易学院代表团访问经济学院，双方在明德主楼729会议室举行座谈。代表团由华南理工大学经济与贸易学院党委书记吴业春副研究员带队，副院长田秋生教授、副院长丁焕峰教授、经济系主任郭守前教授、金融系主任杨春鹏教授、物流系副主任张志勇副教授组成。经济学院院长杨瑞龙教授、党委书记张宇教授、副院长刘瑞教授、经济系副主任李军林教授、国际经济系副主任韩玉军教授、国民经济管理系副主任方芳教授出席座谈会，会议由经济学院党委副书记丁凯主持。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhyhf2yhkf-hmk2h.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长首先代表学院对来访的华南理工大学同仁表示欢迎，并简要介绍了学院的科研教学、学科评估和宏观经济论坛等方面的情况。随后，双方就经济学科建设及211、985经费使用、师资队伍建设、科研管理与科研基地建设、本科生与研究生培养、学生工作、行政队伍建设与党建工作、办公环境管理等方面问题进行了深入的交流。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，华南理工大学经济与贸易学院代表团对学院提供各种经验材料表示感谢，对学院在各个方面取得的优异成绩表示祝贺，并对学院第一流经济学院的地位表示了由衷的认可和赞扬。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1260300274{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhyhf2yhkf-hmk2h_lit.jpg{/dede:field}
