<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","赵方教授作品获“北京市庆祝新中国成立六十周年文艺作品征集评选”佳作奖",89,195);
$z[2][4]['name']="title";
$z[3]=Array("field","",197,236);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",238,291);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-07 09:33:39",293,352);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　中国人民大学艺术学院音乐系赵方教授的声乐作品《心中的河》在&ldquo;北京市庆祝新中国成立六十周年文艺作品征集评选&rdquo;中技压群芳，从近千首音乐作品里脱颖而出，以思想性和艺术性的完美融合喜获佳作奖。</p>\r\n<p align=\"center\"><img alt=\"\" width=\"500\" height=\"333\" src=\"/uploads/allimg/c110725/zlzzbyzhnzkzfhf-hbzbmk.jpg\" /></p>\r\n<p>　　此次评选活动由北京市文学艺术界联合会、北京市文化局、北京市广播电影电视局、北京市新闻出版局、北京日报报业集团、北京出版集团有限责任公司共同主办。</p>\r\n<p align=\"center\"><img alt=\"\" width=\"333\" height=\"500\" src=\"/uploads/allimg/c110725/zlzzbyzhn22hhnf-hy2bkf.jpg\" /></p>\r\n<p>　　在近日举行的盛大颁奖典礼上，赵方教授作曲的《心中的河》被现场演唱，气势磅礴，激昂深情，赢得了热烈好评。</p>\r\n<p>　　（编辑：郑觅）</p>",354,1135);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhnzkzfhf-hbzbmk_lit.jpg",1137,1230);
$z[7][4]['name']="litpic";

?>