{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}赵方教授作品获“北京市庆祝新中国成立六十周年文艺作品征集评选”佳作奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-01-07 09:33:39{/dede:field}
{dede:field name='body'}<p>　　中国人民大学艺术学院音乐系赵方教授的声乐作品《心中的河》在&ldquo;北京市庆祝新中国成立六十周年文艺作品征集评选&rdquo;中技压群芳，从近千首音乐作品里脱颖而出，以思想性和艺术性的完美融合喜获佳作奖。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhnzkzfhf-hbzbmk.jpg" /></p>
<p>　　此次评选活动由北京市文学艺术界联合会、北京市文化局、北京市广播电影电视局、北京市新闻出版局、北京日报报业集团、北京出版集团有限责任公司共同主办。</p>
<p align="center"><img alt="" width="333" height="500" src="/uploads/allimg/c110725/zlzzbyzhn22hhnf-hy2bkf.jpg" /></p>
<p>　　在近日举行的盛大颁奖典礼上，赵方教授作曲的《心中的河》被现场演唱，气势磅礴，激昂深情，赢得了热烈好评。</p>
<p>　　（编辑：郑觅）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhnzkzfhf-hbzbmk_lit.jpg{/dede:field}
