<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","加拿大女王大学梁鹤年教授访问公共管理学院城市规划与管理系并做学术报告",89,195);
$z[2][4]['name']="title";
$z[3]=Array("field","",197,236);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",238,289);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-17 08:57:00",291,350);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应公共管理学院城市规划与管理系主任叶裕民教授邀请，加拿大女王大学城市与区域规划学院院长梁鹤年（Hok Lin Leung）教授于3月10日访问公共管理学院城市规划与管理系。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 梁鹤年教授在城市与区域规划领域具有突出的造诣和卓越的成就，并且长期致力于发展中加友好关系，在规划、科技、经济、资源等多方面领域为中国的发展出谋划策。他组织的&ldquo;国家公共不动产高级官员论坛&rdquo;、&ldquo;企业地产高级研修班&rdquo;、&ldquo;大使论坛&rdquo;在加拿大和亚太地区具有广泛的影响和学术号召力。2002年，梁鹤年教授荣获中国国务院授予外国专家的最高奖&mdash;&mdash;国家友谊奖，2003年入选《加拿大名人录》。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在与城市规划与管理系部分师生进行了热烈而友好的交流后，梁鹤年教授做了题为&ldquo;公共政策分析与评价&rdquo;的学术讲座。梁教授用生动的语言和形象的比喻给大家梳理了西方公共政策分析的发展脉络，告诉大家做一名好的规划师应该怎样理解信仰与理性的关系；而且还从自己几十年的西方留学和工作经历谈起，认为若想实现&ldquo;洋为中用&rdquo;，必须先弄懂&ldquo;洋为洋用&rdquo;，只有真正了解了西方的文化本质，才能正确地吸收和借鉴。讲座深刻的思想性和活泼的形式引发了听众的思考与提问，受到了师生们的欢迎。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />",352,1688);
$z[6][4]['name']="body";
$z[7]=Array("field","",1690,1729);
$z[7][4]['name']="litpic";

?>