{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国宏观经济论坛第四季度报告受到上级部门高度关注{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-03-08 04:35:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由中国人民大学经济学院副院长、经济研究所联席副所长刘元春教授等人共同主持完成的&ldquo;中国宏观经济论坛&rdquo;第四季度报告《共识中的变数：理解2010年中国宏观经济的几个要点》 ，由中宣部社科规划办以&ldquo;成果要报&rdquo;的形式报送上级机关。报告得到国务院、银监会等相关部门领导的高度重视，并做了批复。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
