<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院王晋斌教授做客北京电视台专题访谈",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",210,257);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-22 04:54:59",259,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年10月至2011年2月，经济学院院长助理王晋斌教授多次做客北京电视台财经频道《财经五连发》节目和和中国新华新闻电视网，就宏观经济形势和世界经济等问题接受了采访。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",320,603);
$z[6][4]['name']="body";
$z[7]=Array("field","",605,644);
$z[7][4]['name']="litpic";

?>