{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院王晋斌教授做客北京电视台专题访谈{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-22 04:54:59{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年10月至2011年2月，经济学院院长助理王晋斌教授多次做客北京电视台财经频道《财经五连发》节目和和中国新华新闻电视网，就宏观经济形势和世界经济等问题接受了采访。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
