{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}庆祝人民大学图书馆命名组建60周年大会召开 林岗副校长出席并致辞{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图书馆{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为庆祝中国人民大学图书馆命名组建60周年，人民大学图书馆于11月11日上午召开&ldquo;庆祝人大图书馆命名组建60周年大会&rdquo;。中国人民大学林岗副校长出席大会并致辞。人民大学图书馆现任馆领导、前任馆领导以及图书馆离退休人员、在职全体馆员参加了大会。大家共同回顾人民大学图书馆发展的历程，一起展望人民大学图书馆美好的未来。庆祝大会由图书馆副馆长武继山主持。&nbsp;</p>
<p align="center"><img height="333" src="/uploads/allimg/c101126/z2mfkyfhnfhhfmf-z22yk.jpg" width="500" alt="" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，林岗副校长首先代表学校对人民大学图书馆命名组建60周年表示祝贺，对历届图书馆人为人民大学做的贡献表示感谢。图书馆新馆即将建成投入使用，人民大学图书馆迎来新的大发展局面，林岗副校长希望人民大学图书馆能围绕人民大学建成&ldquo;人民满意、世界一流&rdquo;大学的目标，努力建成一流图书馆。</p>
<p align="center"><img height="333" src="/uploads/allimg/c101126/z2mfkyfhnfnkhbf-2kflk.jpg" width="500" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接着，刘大椿馆长做了题为&ldquo;图书馆发展回顾与展望&rdquo;的报告，以人民大学图书馆为纪念命名组建60周年制作的《人图六十年藏书票》为窗口，从历任国家领导人到访视察人民大学图书馆，人民大学图书馆特藏、馆舍建设、服务类型、经费投入、对外交流、发展战略理念等方面全面回顾了人民大学图书馆60年来的发展，并展望了新馆建成后图书馆美好的发展前景。</p>
<p align="center"><img src="/uploads/allimg/c101126/z2mfkyfhnfmkmzf-lkbfk.jpg" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，宋继芳副馆长做了关于图书馆新馆建设的发言，着重介绍了新馆概况、建筑风格、楼层布局、管理和服务理念、RFID管理等。新馆总建筑面积44625平方米，将成为学校东北区地标式建筑，与西北区明德楼相互辉映，体现&ldquo;人文、人本、人民&rdquo;理念，体现现代、通透、流畅、人性化、多元化的特色。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图书馆原办公室主任杨培菊代表离退休馆员做了发言，从硬件环境、人员知识结构、服务理念方式手段等方面谈了人民大学图书馆60年间的变化，表示作为老一辈图书馆人，亲眼目睹人图60年的巨变感到由衷高兴，衷心祝愿人大馆越办越好，再创辉煌。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 采编部主任胡宁代表全体在职馆员做了发言。他在发言中表示，他个人随着人民大学图书馆的发展也在不断成熟成长，并表示今后要继续学习老一辈图书馆人积极进取的精神，不断提升业务水平，提高服务质量。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学图书馆从命名开始，风风雨雨已走过了60年的历程，是从传统图书馆向现代化图书馆发展变革的阶段。图书馆馆藏从60年前的几十万册到如今的300余万册纸质资源和300余种数据库电子资源；读者服务从60年前单纯的借还服务到如今的借阅、咨询、检索、音像、馆际互借、文献传递、引文统计、读者培训等传统服务与现代服务相结合的多类型、多层次服务；在职馆员从60年前40余人到如今的150余人；馆舍从60年前的封闭式馆舍到如今4.5万余平方米的新馆，人民大学图书馆无论从量还是质上都发生了翻天覆地的变化，服务水平迈向了一个新台阶。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学图书馆承担着为人大师生读者提供教学、科研服务的重任，是学校最为重要的公共服务平台之一。图书馆事业是一种生生不息，永远传承的事业，图书馆的每一步发展，都凝聚着一代代图书馆人的辛勤耕耘和无私奉献。在过去60年发展的基础上，人民大学图书馆将秉承艰苦奋斗，踏实肯干的传统，继往开来，努力打造&ldquo;数字人图、特色人图、专家人图&rdquo;，努力实现&ldquo;师生满意、业界一流&rdquo;的目标。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='pubdate'}1289425251{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhnfhhfmf-z22yk_lit.jpg{/dede:field}
