{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院青年志愿者协会组织爱心系列活动之走进明圆学校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/法学院 陈楚琪 任新鑫 岳振宇{/dede:field}
{dede:field name='pubdate'}2010-04-06 10:12:37{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月31日，法学院院青年志愿者协会4名志愿者赴北京明圆学校开展定期支教活动。本次活动旨在通过表达对电影《千与千寻》的观后感，培养孩子们的语言组织能力和表达能力。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在电影播放完后，志愿者们用启迪性的语言告诉孩子们电影的主题，鼓励孩子们将自己心中所思所想勇敢地表达出来。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开始时，从未接触过此类形式课程的孩子们稍有不习惯，主动发言者寥寥无几。志愿者鼓励他们，并对发言同学予以奖励，而孩子们的积极性也慢慢地被调动了起来，抢着发言。有许多同学的发言甚为深入，活动逐渐引入了&ldquo;爱&rdquo;的主题。一位学生说，看完电影后逐渐明白了&ldquo;爱&rdquo;不只局限在男女之间，在父母、同学、朋友之间都存在着爱，这是一种更为深沉的爱。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 孩子们发言结束后，志愿者向大家总结了《千与千寻》的主题，即&ldquo;爱&rdquo;是一种广义的概念，爱最重要的是善待他人。爱它不但产生于男女，也产生于亲人、朋友、同事、同乡、同类之间。真正伟大的爱甚至包括对敌人、对生态环境等世界上一切值得我们珍惜的爱。<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（编辑：陈汉南） <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
