<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","法学院青年志愿者协会组织爱心系列活动之走进明圆学校",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","文/法学院 陈楚琪 任新鑫 岳振宇",220,289);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-06 10:12:37",291,350);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月31日，法学院院青年志愿者协会4名志愿者赴北京明圆学校开展定期支教活动。本次活动旨在通过表达对电影《千与千寻》的观后感，培养孩子们的语言组织能力和表达能力。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在电影播放完后，志愿者们用启迪性的语言告诉孩子们电影的主题，鼓励孩子们将自己心中所思所想勇敢地表达出来。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开始时，从未接触过此类形式课程的孩子们稍有不习惯，主动发言者寥寥无几。志愿者鼓励他们，并对发言同学予以奖励，而孩子们的积极性也慢慢地被调动了起来，抢着发言。有许多同学的发言甚为深入，活动逐渐引入了&ldquo;爱&rdquo;的主题。一位学生说，看完电影后逐渐明白了&ldquo;爱&rdquo;不只局限在男女之间，在父母、同学、朋友之间都存在着爱，这是一种更为深沉的爱。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 孩子们发言结束后，志愿者向大家总结了《千与千寻》的主题，即&ldquo;爱&rdquo;是一种广义的概念，爱最重要的是善待他人。爱它不但产生于男女，也产生于亲人、朋友、同事、同乡、同类之间。真正伟大的爱甚至包括对敌人、对生态环境等世界上一切值得我们珍惜的爱。<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（编辑：陈汉南） <br />",352,1558);
$z[6][4]['name']="body";
$z[7]=Array("field","",1560,1599);
$z[7][4]['name']="litpic";

?>