<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","环境学院院长马中当选2009绿色中国年度人物",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","环境学院",210,257);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-26 09:03:47",259,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　近日，中国人民大学环境学院院长马中当选为&ldquo;2009绿色中国年度人物&rdquo;。</p>\r\n<p align=\"center\">环境与经济学领域的开拓者 <br />\r\n<img style=\"WIDTH: 304px; HEIGHT: 375px\" height=\"375\" alt=\"\" width=\"324\" src=\"/uploads/allimg/c110113/z2mhnnbkynfzynf-zn2y2.jpg\" /><br />\r\n中国人民大学环境学院院长 马中 </p>\r\n<p>　　&ldquo;绿色中国年度人物&rdquo;是由中共中央宣传部、全国人大环境与资源保护委员会、全国政协人口资源环境委员会、环境保护部、文化部、国家广播电影电视总局、共青团中央七部委联合主办的政府奖项，得到联合国环境规划署的特别支持，由中国环境文化促进会承办，由公众、专家按照科学、公开、公平的方法评选出来的中国环保人物奖，具有权威性、公众性和国际性的特点。 </p>\r\n<p>　　经过社会调查,专家评委投票,网民投票和公众评委投票,马中教授从188位提名人中脱颖而出,成为6位获奖人之一。</p>\r\n<p>　　&nbsp;相关链接：<a href=\"http://www.zhb.gov.cn/ztbd/shbz/ndrw/\">中华人民共和国环境保护部</a><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"http://www.cenews.com.cn/xwzx/zhxw/qt/201011/t20101126_689744.html\">&nbsp;绿色中国年度人物介绍 </a></p>\r\n<p>　　（编辑：刘伟伟）</p>\r\n<p><br />\r\n</p>",320,1568);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110113/z2mhnnbkynfzynf-zn2y2_lit.jpg",1570,1662);
$z[7][4]['name']="litpic";

?>