<?php
$z[0]=Array("field","",48,76);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",78,111);
$z[1][4]['name']="typename";
$z[2]=Array("field","",152,180);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n            <li><span>[field:pubdate function=&quot;MyDate('m-d',@me)&quot;/]</span><a href=\"[field:arcurl /]\">[field:title \r\n			/]</a></li>\r\n            ",260,467);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>