{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}充分肯定成绩 努力再创新业 纪宝成校长视察国际学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际学院（苏州研究院）{/dede:field}
{dede:field name='pubdate'}2011-03-31 08:39:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月25日至29日，中国人民大学校长纪宝成一行来国际学院（苏州研究院）视察，检查学院各方面工作，并在学院全体教师会上作重要讲话，要求国际学院的发展要继续坚持&ldquo;高水平、有特色、国际性&rdquo;的目标定位，在办学模式上进行适当转变，实现新的发展，创造新的业绩。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 25日晚，纪宝成校长一行抵苏，在国际学院院领导的陪同下视察了校园建设情况，了解敬斋的运营情况。纪宝成校长强调，建设国际学院是解决学校办学空间紧张、创新办学模式的战略举措，要继续办好国际学院。纪宝成校长对美丽的校园大加赞赏，并欣然为学院乐湖畔的两个小亭命名并题字：&ldquo;至喜亭&rdquo;、&ldquo;裕舒亭&rdquo;。&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbbybb2lf-hzfnl.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 26日至27日，学校高等教育研究室在国际学院敬斋宾馆就高等教育研究课题进行讨论，纪宝成校长出席了讨论会。&nbsp;<br />
<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbbymf2bf-bnfln.jpg" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 28日下午，纪宝成校长出席国际学院全体教师会议并作重要讲话，国际学院全体院领导、各部门负责人以及全体教师参加会议。会议由陈甬军常务副院长主持。</p>
<p align="center"><img alt="" width="333" height="500" src="/uploads/allimg/c110418/zlflzzhbbymhhzf-ymkh2.jpg" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长在讲话中指出，国际学院教学工作井然有序，学生学习生活也非常稳定，学院的各项工作都走上了正轨，总体运行平稳，并展现出强劲的发展势头和巨大的发展潜力，社会各界也对学院的发展给予高度评价，&ldquo;延伸办学&rdquo;这一模式和路径行之有效。纪宝成校长表示，国际学院这些成绩的取得离不开学校有关部处、学院以及独墅湖高教办的大力支持，更离不开学院全体教职员工的辛勤努力。纪宝成校长表示，此次来到苏州，就是特地来看望大家，问候大家，感谢大家。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长强调，国际学院所采取的&ldquo;延伸办学&rdquo;模式要继续进行探索和经验总结，但同时也要在原有基础上进行适当转变，实现&ldquo;延伸办学&rdquo;和&ldquo;自主办学&rdquo;相结合的新运作模式和发展路径。国际学院要加快发展，在培养高水平人才和产出高水平科研成果的同时，要进一步发展自身的教师队伍，&ldquo;自主办学&rdquo;的模式要开展起来。学校支持国际学院进一步加大人才引进力度，组建新的研究机构，并在条件允许的情况下建立独立的系，以实现学院自身发展。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长要求，国际学院要继续坚持&ldquo;高水平、有特色、国际性&rdquo;的目标定位。国际学院要围绕这一目标定位进行细化、贯彻和落实，在异地办学中仍旧保持学校本部的高水平人才培养和高水平科学研究，要成为科学研究的重要基地。要敢于争先，成为长三角地区的亮点，体现出人民大学的水平和特色。国际学院的二期建设如何建、建什么，要与学院的发展规模相适应。学校有决心把国际学院发展地更好，大家要同心同德，共同努力，扎实做事，真正办好国际学院，实现可持续发展。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110418/zlflzzhbbymn2kf-kkkb2.jpg" /></p>
<p>&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在苏期间，纪宝成校长会见了苏州市委常委、苏州工业园区党工委书记马明龙、独墅湖高等教育区管理办公室主任叶峰，就中国人民大学国际学院资产回购、中法学院报批、师资队伍建设等问题进行了商谈。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长还与正在国际学院调研的湖南商学院访问团成员一同考察了苏州评弹学校，了解该校在传承和弘扬传统文化方面所采取的措施。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbbybb2lf-hzfnl_lit.jpg{/dede:field}
