<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","人民大学学生随中国青年代表团访问德国并受到默克尔总理接见",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","李娜",226,269);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-10-26 10:59:27",271,330);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月13日至20日，中国人民大学外国语学院德语专业学生李娜、于南、沈瑶纤等三人参加了全国青联派遣的中国青年代表团，随团对德国进行了为期8天的访问，并受到德国总理默克尔接见。 </p>\r\n<p align=\"center\"><img height=\"350\" alt=\"\" width=\"500\" src=\"/uploads/allimg/c100621/z2kkzlbnybyzzhf-llmbm.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 作为中德两国总理达成的青年互访计划的一部分，应德国联邦家庭、老人、妇女与青年部邀请，由团中央书记处第一书记陆昊率领的代表团一行400人访德，旨在促进两国青年交流，为中德关系的健康发展打下良好基础。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次代表团成员由青年工作者、公务员、教科文卫体界代表、新闻工作者、企业界代表和大学生代表组成，在德期间，代表团分赴德国16个州，与德国各界青年进行广泛交流，并开展了丰富多彩的活动。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在德期间，代表团对柏林进行了为期一天的访问，参观了议会大厦、联邦总理府、勃兰登堡门等标志性建筑。德国总理默克尔于14日中午会见了代表团全体成员。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在此之后，人大的三名同学分别前往北莱茵－威斯特法伦州、巴登符腾堡州和巴伐利亚州，参观了当地政府及青年机构，与当地青少年进行座谈交流。</p>\r\n<p>（编辑：彭大伟）</p>",332,1587);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100621/z2kkzlbnybyzzhf-llmbm_lit.jpg",1589,1681);
$z[7][4]['name']="litpic";

?>