{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院教授李义平出席中国西促会新春联谊会并作演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-01-17 09:24:07{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月9日下午，中国西部研究与发展促进会在北京饭店举行2011年新春联谊会。中国人民大学经济学院李义平教授应邀在主桌就座，并在中国西促会理事长程路致辞之后，就当前宏观经济形势进行演讲。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 全国政协副主席郑万通，全国政协副主席阿不来提&bull;阿不都热西提，全国人大常委，民建中央副主席辜胜阻，全国政协常委、原国家民委主任李德洙，全国政协副秘书长王胜洪，国务院发展研究中心副主任侯春云，国家民委副主任吴仕民等多位领导出席了联谊会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;李义平教授的演讲赢得了两位政协副主席的赞赏和全场热烈的掌声。李义平教授是当天联谊会上唯一的演讲嘉宾。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href="http://se.ruc.edu.cn/zgjs_displaynews2.asp?id=2211">李义平教授简历</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
