<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院教授李义平出席中国西促会新春联谊会并作演讲",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",220,267);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-17 09:24:07",269,328);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月9日下午，中国西部研究与发展促进会在北京饭店举行2011年新春联谊会。中国人民大学经济学院李义平教授应邀在主桌就座，并在中国西促会理事长程路致辞之后，就当前宏观经济形势进行演讲。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 全国政协副主席郑万通，全国政协副主席阿不来提&bull;阿不都热西提，全国人大常委，民建中央副主席辜胜阻，全国政协常委、原国家民委主任李德洙，全国政协副秘书长王胜洪，国务院发展研究中心副主任侯春云，国家民委副主任吴仕民等多位领导出席了联谊会。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;李义平教授的演讲赢得了两位政协副主席的赞赏和全场热烈的掌声。李义平教授是当天联谊会上唯一的演讲嘉宾。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href=\"http://se.ruc.edu.cn/zgjs_displaynews2.asp?id=2211\">李义平教授简历</a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）<br />\r\n</p>",330,1256);
$z[6][4]['name']="body";
$z[7]=Array("field","",1258,1297);
$z[7][4]['name']="litpic";

?>