{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}央视英语新闻频道与新闻学院联合举办“CCTVnews进校园”活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-11-30 02:27:07{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月18日下午，&ldquo;CCTVnews进校园&rdquo;在中国人民大学新闻学院网真演播室进行。本次活动探讨和交流的主题是&ldquo;中国媒体国际化探讨&rdquo;。活动由新闻学院常务副院长倪宁主持，中央电视台英语新闻频道《对话》和《世界观察》栏目的主持人田薇担任嘉宾。田薇向同学们介绍了CCTVnews频道的概况和央视&ldquo;寻找中国面孔&rdquo;的活动，并就我国国际传播的现状等问题与新闻学院的同学们进行了互动。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllk2lylyf-zmzlz.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 活动开始，倪宁常务副院长向同学们介绍了田薇女士丰富的媒体工作经历和开阔的国际视野。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllk2yfmkf-2mhzk.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 田薇女士在演讲中向同学们介绍，央视英语新闻频道改为&ldquo;CCTVnews&rdquo;之后，突出新闻立台，广泛派驻记者，并在节目中更多地宣传亚洲人的理念。她所主持的《对话》节目旨在搭建一个交流的平台，让各方嘉宾在这里进行思想的碰撞；《世界观察》则将视野放在全球，用英语与世界各地的演播室连线，让各地嘉宾进行交流和辩论。&ldquo;寻找中国面孔&rdquo;活动旨在寻找一些具有中国文化背景又热爱祖国，渴望为国家发出声音做贡献的年轻人来加入对外传播的行列。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllk2ybl2f-lzfmb.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲之后，田薇女士与现场同学进行了互动。对同学们提出的纸质媒体的前景、国内主流报道如何做到公正平衡、什么是国际话语权和如何争取国际话语权等问题，田薇女士都一一作了回答。田薇表示她对纸媒的前景和主流媒体受众的日益成熟都持乐观态度,举出了她自己就台湾问题采访白宫官员时的亲身经历，说明要以人性化的方式来和国外进行交流，进而争取话语权；消除国外受众的偏见，满足他们的兴趣，以大家都能理解的语言来讲述中国的逻辑。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 田薇还回答了网友提出的一些问题，更为全面的让在场的同学们感受到了她作为&ldquo;记者型主持人&rdquo;的魅力。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 倪宁常务副院长最后总结说：&ldquo;田薇老师带来了精彩的演讲，也带了一连串的生动的故事，通过这么一个活动，我们对于田薇老师本人，对于CCTVNEWS，对于中国传媒的发展，对于国际传播报道都有了一些新的认识和思考。在场的每位同也在思考在今后的国际传播格局里边，为我们国家的新闻事业发展，为增强国际传播力，如何发挥自己的才智，贡献自己的力量。竞争是人才的竞争，国际传播的竞争需要创新型的新闻传播人才。&rdquo;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;（编辑：刘伟伟）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnllk2lylyf-zmzlz_lit.jpg{/dede:field}
