{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院举办“碳税的减排效果与经济影响”学术讨论会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月6日，经济学院和中国经济体制改革研究会共同举办&ldquo;碳税的减排效果与经济影响&rdquo;学术研讨会。本次研讨会共发表了六篇关于二氧化碳排放方面的研究成果。国家财政部、国家发改委、国家税务总局、电监会的政府官员，清华大学、北京大学、中国社会科学院、华北电大、美国VASSAR 大学、《中国社会科学》杂志社等机构的专家学者，以及经济学院师生30余人参加了讨论会。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhkhnykhyf-2nllk.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，北京大学国际关系学院查道炯教授发表了题为&ldquo;碳排放与全球政治&rdquo;的演讲；中央财经大学财政与公共政策研究院张莉副教授发表了题为&ldquo;中国碳排放：地区与产业视角&rdquo;的演讲；中国人民大学经济学院夏明副教授发表了题为&ldquo;宏观总需求与碳排放&rdquo;的演讲；中国人民大学经济学院张红霞副教授发表了题为&ldquo;碳税与碳排放：产业数据&rdquo;的演讲；中国人民大学经济学院陶然教授发表了题为&ldquo;碳排放：中国的国际策略研究&rdquo;的演讲；中国人民大学经济学院郑新业副教授发表了题为&ldquo;碳税的减排效果及对经济的冲击研究&rdquo;的演讲。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次讨论会上发布的研究成果受到了与会来宾的高度评价。研讨会取得了圆满成功。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='pubdate'}1267058729{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkhnykhyf-2nllk_lit.jpg{/dede:field}
