{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}王利明教授应武汉仲裁委员会邀请作《中华人民共和国侵权责任法》专题讲座{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-11 02:20:27{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月30日，中国人民大学党委副书记、副校长王利明教授应邀到武汉仲裁委员会，就《中华人民共和国侵权责任法》进行专题讲座。讲座由仲裁委副主任刘健勤同志主持。湖北省、武汉市有关部门领导、武汉仲裁委员会仲裁员、仲裁委办工作人员共200余人参加了讲座。讲座结束后，武汉市市委常委、常务副市长袁善腊同志会见了王利明教授。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王利明教授采取理论结合实例的方法，对《侵权责任法》的重要法条进行了系统、透彻、精彩的讲解，并围绕《侵权责任法》的名称、保护范围、归责原则、侵权责任形态以及责任承担方式等问题进行了重点阐述，使大家对《侵权责任法》与传统侵权行为法的区别、《侵权责任法》权益保护范围的特点、多元归责原则的内涵和适用方法、多数人责任的具体划分、《侵权责任法》在责任承担方式上取得的新突破等问题有了更加深入的认识。在讲座互动阶段，王利明教授认真回答了仲裁员现场提出的问题，显示出一名法学大家深厚的理论功底和成熟的法律思维。讲座在大家的热烈掌声中结束。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《中华人民共和国侵权责任法》将于2010年7月1日起施行，是继2007年《中华人民共和国物权法》实施后，我国民事立法活动的又一项重要成果。该法对于保护公民、法人的合法权益，明确侵权责任，预防并制裁侵权行为，化解社会矛盾，减少民事纠纷，促进社会公平与正义具有重要意义。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：徐晶晶）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
