{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙院长出席全国高校国家经济学基础人才培养基地工作会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年11月6日，按照教育部&ldquo;本科教学质量与教学改革工程&rdquo;建议要求，为进一步推进经济学专业教育教学改革和创新人才培养， &ldquo;全国高校国家经济学基础人才培养基地工作会议&rdquo;暨&ldquo;第九届经济学基础人才培养基地学生科研讨论会&rdquo;在南京大学召开。十三个国家经济学基础人才培养基地的负责人和相关教师等参加了会议。南京大学党委书记洪银兴教授出席了开幕式并作重要讲话。 </p>
<p align="center"><img height="332" src="/uploads/allimg/c101124/z2mfbmzhhhyhmnf-bnhbh.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学经济学院院长、经济学基础人才培养基地主任杨瑞龙教授，中国人民大学经济学基础人才培养基地秘书长李军林教授，经济学院韩松副教授等出席了会议。大会安排杨瑞龙院长在开幕式上作了主题发言。杨瑞龙院长在会上介绍了中国人民大学经济学院在经济学本科教育，特别是在&ldquo;经济学基地班&rdquo;和&ldquo;经济学－数学双学位实验班&rdquo;的改革思路和具体做法，并对国家经济学基础人才培养基地的未来发展提出了建议。他的发言引起了与会学者专家的广泛共鸣，并展开了深入地讨论。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhhblyblf-ym2nb.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 同时，来自中国人民大学、北京大学、复旦大学、南开大学、南京大学等十三所高校的30多位学生代表，就自己提交大会的论文进行了学术讨论，并对经济学研究及学习的心得与看法进行了交流。经济学院07级基地班同学郭琦，徐沛东及冯焌昽三位同学作为中国人民大学经济学院学生代表参加了会议，并在大会上宣读了论文。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1289525216{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhhhyhmnf-bnhbh_lit.jpg{/dede:field}
