{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院李艳芳教授应邀参加国务院法制办《能源法》（讨论稿）专家座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-17 11:04:10{/dede:field}
{dede:field name='body'}<p>&nbsp;　　3月11-12日，国务院法制办组织召开《能源法》（讨论稿）专家座谈会，法学院李艳芳教授应邀出席专家座谈会，并就《能源法》的框架、结构、与相关法律的关系以及具体制度与主要条款存在的问题提出了意见和建议。</p>
<p>　　由国家能源局组织起草的《能源法》（征求意见稿）2008年底上报国务院法制办后，国务院法制办先后多次召开座谈会征求专家、部门和企业意见，并形成《能源法》（讨论稿）。李艳芳教授应邀参加了2009年1月召开的专家座谈会、2009年11月举办的中欧能源法国际研讨会和本次专家座谈会。</p>
<p>　　出席本次专家座谈会的有能源产业、政策和法律专家6人，还包括国家发展改革委能源研究所研究员周大地、国务院发展研究中心产业经济研究部部长冯飞、中国欧盟商会能源委员会主席陈新华、中国法学会能源法研究会会长叶荣泗、中国能源网首席信息官韩晓平。</p>
<p>（编辑：邢鹏）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
