{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}荷兰瓦赫宁根大学Arthur Mol教授访问人大环境学院并发表演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2010-06-03 03:58:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年6月2日上午，应中国人民大学环境学院邀请，人大环境学院讲座教授、荷兰瓦赫宁根大学教授Arthur Mol访问环境学院，并在理工楼905会议室带来题为&ldquo;International Environmental Policy&rdquo;的讲座。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnfylhnm2f-zkkb2.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Mol教授开场提出研究国际性环境政策的研究来源于环境问题的跨国界性和对于全球经济需求的标准要求。紧接着，Mol教授向大家展示了国际环境政策研究的必要性，包括全球环境问题，同时也指出国际环境政策所面临的诸如国家主权限制、南北差异和政策执行等多方面的挑战。随后，Mol教授以臭氧层空洞和森林保护为实例，介绍了国际环境政策的应用。最后他谈到在全球贸易进程中对经济利益的追逐与保护环境的冲突。讲座之后，同学们就关心的与宫教授进行了积极的交流。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次，Mol教授与同学们交流了关于环境与贸易的关系、国际组织在环境政策中的角色、国际环境政策面临的挑战等很多问题，Mol教授在长达3个小时的讲座中向同学们详细介绍了关于国际环境政策研究的诸多方面。通过本次讲座，同学们了解了国际环境政策研究领域的发展与挑战，对这一方面表现了浓厚的兴趣。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnfyhfmbzf-2kmkb.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Arthur Mol 于2009年12月受聘中国人民大学讲座教授，他是荷兰瓦赫宁根大学副校长、Mansholt研究生院院长、环境政策系主任，是国际著名的环境社会学家，他新近刚刚获得国际环境社会学界的两项荣誉，分别是由国际社会学学会(ISA)颁发的&ldquo;Frederick H. Buttel 杰出环境社会学家&rdquo;奖，该奖项是为了纪念著名环境社会学家Frederick H. Buttel而设立的，每4年颁发一次，被公认为环境社会学界的最高奖项之一；美国社会学学会(ASA) 颁发的&ldquo;杰出贡献奖&rdquo;，是该奖自1983年设立以来第一个非美国籍获奖者。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfylhnm2f-zkkb2_lit.jpg{/dede:field}
