{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院志愿者走进芙蓉里敬老院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-16 09:07:20{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月13日上午8点，随着六名志愿者踏上前往芙蓉里敬老院之路，新学期法学院青年志愿者协会敬老助老服务拉开帷幕。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 春寒料峭，天气还有一丝寒冷，但是低温冻不住志愿者服务的火热之心。上午8点20左右，志愿者一行六人到达敬老院，开始了与老人们的交流。志愿者们分工明确，一人帮助奶奶洗衣服，其余五人则陪奶奶们聊天。大到人际关系，小到家长里短，志愿者们与奶奶们无所不谈，十分快乐。从交谈之中看出来奶奶们迥异的性格，或童心不泯，或老练稳重，或健谈风趣，或沉默严肃。正所谓和而不同，正是这不同的风格才使敬老院充满了生机与活力。时间过得很快，两个小时的敬老服务转瞬间结束了，在奶奶们即将吃午饭之际，志愿者们离开了敬老院。也许是志愿者们的服务深深打动了奶奶们，临走前大家依依不舍，一位老人将志愿者们送至门口目送着离开。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzy2mkyhknf-z2hmz.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 上午11点，从敬老院回到了学校，结束了这一次短暂而充满感动与温馨的敬老院之行。 <br />
<br />
</p>
<p align="center">&nbsp;</p>
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzy2mkyhknf-z2hmz_lit.jpg{/dede:field}
