<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院刘元春教授就热点宏观经济问题接受媒体采访",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",218,265);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月4-5日，经济学院副院长刘元春教授分别接受新华社、北京电视台财经频道、广东电视台的采访，就两会讨论的宏观经济热点问题和温家宝总理所做的政府工作报告进行解读。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",267,547);
$z[5][4]['name']="body";
$z[6]=Array("field","1267993959",549,599);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",601,640);
$z[7][4]['name']="litpic";

?>