{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院2011届毕业作品展开幕 程天权书记莅临贺展观看{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-05-20 04:19:04{/dede:field}
{dede:field name='body'}<p>　　5月16日至21日，中国人民大学艺术学院设计系2011届毕业作品展在公共教学一楼1301和艺术学院小展厅同时举行。本次毕业设计作品在平面、景观、动画和新媒体四个专业方向的学生和指导老师的共同努力下，取得了耀目的成效。作品选题广泛、构思新异、表征创新、制作精道，受到了参观者的一致赞许，普遍认为是近年来设计系毕业作品较好的一次。 </p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhkfblnnf-mhmzb.jpg" alt="" /></p>
<p>　　5月16日下午，学校党委书记程天权在艺术学院书记郑晓华、副院长王英健和副书记别敏的陪同下，莅临贺展观看并仔细听取了教师及学生对作品设计创意构思的讲释，书记事务助理兼校办副主任李家福、校办副主任李惠一同观看了此次作品展。 </p>
<p>　　程天权书记对本次展览给予了&ldquo;设计作品有水平，有创意，有思想，眼光超前&rdquo; 的评价并即兴进行了热情的讲话。他嘱咐同学们：设计要源于生活，要关心社会，关心时事，抓住社会的脉搏，设计的方向要积极、乐观、团结、向上。他还勉励即将毕业的同学们，要勇于面对困难，闯出一番天地，做出一番事业，为国家、为社会做出应有的贡献。希望同学们把自己的理想与国家、社会的需要结合起来，在奉献祖国、服务人民的过程中实现自己的人生价值。 </p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhkfmmlf-zfmbnb.jpg" alt="" /></p>
<p>　　最后，程书记与艺术学院领导和设计系师生合影留念。 </p>
<p>　　（编辑：贾晓旭）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkfblnnf-mhmzb_lit.jpg{/dede:field}
