{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}武汉大学国学院院长郭齐勇主讲哲学家讲坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-11-29 09:20:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月26日下午两点半，由哲学院主办的哲学家讲坛在逸夫会议中心第二报告厅举行。本期讲座邀请了武汉大学国学院院长、博士生导师郭齐勇教授做题为《关于儒家政治哲学与正义论的思考》的讲座。本次讲坛由哲学院副院长干春松教授主持，北京大学彭永捷教授担任主讲人。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座开始，干春松教授首先介绍了郭齐勇教授近年的研究方向&mdash;&mdash;儒家哲学、二十世纪中国思想文化史。在干春松教授介绍完毕之后，郭齐勇教授正式开始了他的学术讲座。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郭齐勇教授开门见山地指出：儒家政治哲学在分配方面的&ldquo;应得&rdquo;、&ldquo;配得&rdquo;以及机会公平、对&ldquo;最不利者&rdquo;的关怀及其制度建构方面都与亚里士多德的政治学和罗尔斯的正义论遥相呼应。从亚里士多德的两种平等观和罗尔斯关于正义的两种原则来看儒家，孔子非常尊重老百姓的生存权和私利，提倡中正平和的执政理念。孟子的言论则涉及生存权、财产权之平等和社会保障方面的制度设计，注重教育公平、平民参政、尊重民意、防止公权力的滥用。在《周礼》和《礼记》中提到了荒政，以及有关于养老恤孤、居住、土地、赋税、商业的制度。所以说儒家的伦常之道有利于社会的和谐化、秩序化、公平化，其制度背后是以仁爱为核心的价值体系。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 从西方政治学看，孔孟之道与亚里士多德的政治学、罗尔斯的正义观都有内在相通性。在政治权利的源头、合法性、分配和制衡看，&ldquo;天&rdquo;、&ldquo;昊天&rdquo;、&ldquo;帝&rdquo;、&ldquo;上帝&rdquo;是夏商周三代王权政治合法性的来源，而在盘庚迁都的告文中就已经包含了尊重民意、民权、民生之意，是人文主义的萌芽。在殷周之际，周公等人的观念已经从&ldquo;以祖配天&rdquo;变为&ldquo;以德配天&rdquo;，他们指出：君主由天命选定，但民意可以改变之，关键是看君主的作为。中国的民本主义是从&ldquo;敬天&rdquo;的观念中逐渐脱胎出来的对社会精英的高级要求。秦之后，儒家知识分子不断与国家进行斗争，代表平民利益的内容被不断地写入法典中。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郭教授还提到，传统中国是儒家的中国，是典型的小政府大社会，传统中国的社会管道、中间组织很多，在一定意义上就是地方自治、社会自治。不是由政府包打天下，而是靠以血缘、地缘为纽带的社会团体管理。知识分子代表人民的利益，反映人民的心声。中国政治制度文明的传统是皇权、地方权、知识分子力量的合力。关于儒家的&ldquo;道德政治&rdquo;及其现代转化，郭教授认为儒家政治哲学的核心是&ldquo;仁义&rdquo;价值与&ldquo;仁政&rdquo;学说儒家主张的政治是&ldquo;道德政治&rdquo;，人们应该追求道德的政治，批判不道德的政治。其政治理念强调政治的正当性以及对人的尊重。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnbmhlhhf2f-zzkn2.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郭齐勇教授演讲结束后，彭永捷教授评论道，现在对传统文化的发掘力度很大，也有很多人注重中西方的比较研究。郭齐勇教授把中国儒家哲学与亚里士多德、罗尔斯的学说比较研究为我们指出一条学术研究的新道路，值得我们借鉴学习。彭永捷教授评论后，郭齐勇教授回答了现场师生们的提问。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnbmhlhhf2f-zzkn2_lit.jpg{/dede:field}
