<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","“第二届商界领袖金融投资高级研修班”开学典礼举办",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","财金学院",218,265);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-26 11:06:02",267,326);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4月24日，由财政金融学院举办的&ldquo;第二届商界领袖金融投资高级研修班&rdquo;开学典礼在浙江温州举行，薛浣白副校长出席典礼并讲话，财政与金融学院党委书记王宏伟陪同出席。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;薛浣白副校长在讲话中指出，在我国经济全面融入全球经济并一体化的今天，随着全球经济的全面下滑和国内生产资料成本的大幅提高，我国企业面临着前所未有的挑战。如何自如应对宏观环境的急剧变化是每位企业家面临的新课题，希望各位学员能够在增长才学，启迪思维的同时，全面提升自我，获得一个没有边界的资源平台。 </p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c100622/z2kkzlkhkzlyhyf-bkhfm.jpg\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;商界领袖金融投资高级研修班&rdquo;是学校财政金融学院组织专家设计出的一套具有国际水准的投融资管理课程，旨在帮助企业高层管理人员准确判断宏观经济形势，全面掌握资金、资本市场规律和运作手段，有效利用资本市场强大的输血和造血功能，保障企业良性的资金循环和快速的资本扩张，实现企业稳步快速发展。</p>\r\n<p>（编辑：程远芳）&nbsp;<br />\r\n</p>",328,1392);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100622/z2kkzlkhkzlyhyf-bkhfm_lit.jpg",1394,1486);
$z[7][4]['name']="litpic";

?>