{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院举行院友座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月13日，经济学院举行院友座谈会，中国农科院党组书记、1978级区域经济系校友薛亮，中央财经领导小组办公室局长、1978级计划系校友张松涛，人力资源和社会保障部劳动关系司司长、1982级计划系校友邱小平，中国房地产开发集团公司副总经理、1984级经济系校友诸一军等返回母校。经济学院院长杨瑞龙教授、副院长郭杰教授、党委副书记丁凯博士等出席了座谈会并与校友亲切交流。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhyhbmhhf-zzzhm2.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长对校友们返校表示热烈欢迎，他首先向校友们介绍了首届院友会成立三年以来开展工作的情况以及2010年10月31日第二届院友大会召开的情况，并介绍了经济学院近年来在学科建设和人才培养方面开展的工作及所取得的成绩。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhybhbfnf-z2lnbn.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当日返校的校友都是受邀参加经济学院第二届院友大会，但当天有其他工作安排未能与会的，他们对于重返母校并与昔日同学相见感到十分激动。大家都表示，虽然毕业多年，但一直对母校和母院怀有很深的感情，一直在关注和关心母校和母院的发展。在听取了杨瑞龙院长的介绍之后，校友们尤其对母校和母院的良好发展势头和经济学科建设所取得的成绩感到十分欣喜，并表示将会继续关心母校和母院的发展，进一步支持经济学院院友会的建设。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='pubdate'}1289857788{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhyhbmhhf-zzzhm2_lit.jpg{/dede:field}
