{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国康涅迪克大学法学院保险法中心主任Patricia A. McCoy教授做客法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-28 11:26:35{/dede:field}
{dede:field name='body'}<p align="left">　　5月25日下午，在明德法学楼601国际学术报告厅，美国康涅迪克大学法学院保险法中心主任Patricia A. McCoy教授做客法学院&ldquo;海商法保险法前沿系列&rdquo;，为法学院师生做了题为&ldquo;The Current U.S. Financial Crisis: Causes and Lessons Learned&rdquo;的主题讲座。康涅迪克大学法学院Hong yan女士、法学院黎建飞教授、邢海宝、杨东副教授出席了讲座，徐孟洲教授主持了这一讲座。 <br />
<br />
　　Patricia A. McCoy教授是美国知名的金融法学者、公认的研究次贷危机的权威专家。她的教学研究涉猎广泛，包括银行、证券、保险和社会保障等。她著述颇多，还是一些权威出版物的顾问。她积极参与社会活动，曾经出席美国国会听证会，产生了较大的社会影响。 <br />
<br />
　　Patricia A. McCoy教授首先指出引起美国金融危机的两大原因：金融产品创新导致的次贷市场发展；联邦法律监管的缺失。随后，她详细介绍了次级贷款市场的发展情况，并就美国次级贷款市场的急速膨胀和最终失败的几个诱因做了深度解剖。接着，她结合美国历史上几次经济危机，揭示了市民短期储蓄和银行长期放贷的矛盾。这次金融危机也是这一矛盾激化的结果。Patricia A. McCoy教授还富有逻辑地分析了这次金融危机的整个过程，由此得出的经验教训是政府需要推行统一的最低贷款标准，在证券化的过程中建立一套完善的体系，以鼓励市场参与者积极避免不良贷款，选择优质贷款。整个讲座数据详实，图文并茂。 <br />
　　</p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzyblnyfbyf-zy2nl.jpg" alt="" /></p>
<p align="left"><br />
　　接下来，徐孟洲、黎建飞教授、邢海宝、杨东副教授分别针对Patricia A. McCoy教授的讲座做了交流，认为讲座很具启发性，是一套难得的学术盛餐，并结合中国国情与Patricia A. McCoy教授探讨了中国应对金融危机的困境和策略。同学们也踊跃提问，积极参与讨论。 <br />
<br />
　　讲座结束，全场师生对Patricia A. McCoy教授报以热烈的掌声。Patricia A. McCoy教授对人大法学院师生睿智的提问和讨论表示欣赏。 </p>
<p>　　（编辑：王强）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyblnyfbyf-zy2nl_lit.jpg{/dede:field}
