{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}安徽大学法学院来人民大学法学院访问{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-30 10:16:59{/dede:field}
{dede:field name='body'}<p>　　3月28日下午，法学院党委书记兼副院长林嘉教授、副院长龙翼飞教授、副院长王轶教授在明德法学楼二层会议室会见了安徽大学法学院程雁雷院长一行。来访的嘉宾还有安徽大学法学院副院长陈结淼、徐淑萍等。法学院党委副书记郑小敏老师、办公室主任兼团委书记乔鹏老师、教务科科长郝晓明老师陪同参加了会见。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fyhhlzzf-zlnzk.jpg" alt="" /></p>
<p>　　林嘉书记兼副院长首先代表人大法学院对安徽大学法学院一行的到来表示欢迎，并希望进一步加强人大法学院和安徽法学院的合作与交流。 </p>
<p>　　龙翼飞副院长随后向安徽大学法学院介绍了我院硕士研究生的培养模式，生源情况以及苏州研究院的发展，并与安徽大学法学院副院长陈结淼、徐淑萍针对在职法硕的招收和培养进行了深入交流与探讨。 </p>
<p>　　王轶副院长将我院本科生培养方针和思路进行了介绍，安徽大学法学院程雁雷院长对我院针对本科生因材施教、分类培养的模式以及学生国际化的思路很感兴趣并表示赞同，并就具体细节问题进行了探讨。 </p>
<p>　　安徽大学法学院程雁雷院长表示此次是第一次来访人大，期望今后能够进一步加强安徽大学法学院和人大法学院在学术和教学等方面的联系与合作。 </p>
<p>　　（编辑：王强）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fyhhlzzf-zlnzk_lit.jpg{/dede:field}
