{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}《复印报刊资料》(2010)转载学术论文指数排名发布{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}中国人民大学人文社会科学学术成果评价研究中心{/dede:field}
{dede:field name='pubdate'}2011-03-29 09:34:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 日前，中国人民大学人文社会科学学术成果评价研究中心正式发布了&ldquo;2010年度《复印报刊资料》转载学术论文指数排名&rdquo;及《研究报告》。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该排名根据人大《复印报刊资料》100多种学术系列期刊在2010年度转载的学术论文数据，对我国人文社科学术期刊和教学科研机构进行了统计排名。包括： <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ●<strong> 综合性学术期刊按系统排名</strong>：从转载量、转载率和综合指数三个量度，对我国高等院校、社科院（联）、党政干部院校三大系统主办的综合性期刊进行排名。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ● <strong>学术期刊按专业学科排名</strong>：从转载量、转载率和综合指数三个量度，按学科对众多学术期刊进行专业学科排名。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;●<strong> 教学科研机构排名</strong>：根据论文作者所属单位，从转载量和综合指数两个量度，对我国高等院校、社科院（联）、党政干部院校三大系统内各教学科研单位进行排名。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ● <strong>高等院校及其二级院所按学科排名</strong>：根据论文作者所属单位，从转载量和综合指数两个量度，按专业学科对高校及其二级院所进行排名。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2001年起每年3月份，《光明日报》以及近年增加的《中国新闻出版报》、千龙网、新华网、新浪网、中国高校人文社科网、中国人民大学网等媒体，都同时发布这个年度&ldquo;转载排行榜&rdquo;。该统计排名和研究报告提供了有价值的客观数据和信息，一定程度地反映了我国人文社科学术期刊阵营和学术研究机构的分类、布局、水平、变化和发展态势等状况，一直受到学术期刊界、教学科研单位和广大人文社会科学工作者的高度关注和广泛重视。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与往年相比，2010年度的排名有两大变化：一是首次采用了&ldquo;综合指数&rdquo;排名；二是在按学科排名中，将学科分类由13个细化为21个。该排名共计166个排名表。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>&nbsp; 完整数据详见：</strong><a href="http://www.zlzx.org/rssi2010/index.htm"><strong><font color="#0000ff">http://www.zlzx.org/rssi2010/index.htm</font></strong></a>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接<a href="http://epaper.gmw.cn/gmrb/html/2011-03/29/nw.D110000gmrb_20110329_1-07.htm?div=-1">：[光明日报] 2010年度《复印报刊资料》转载学术论文指数排名</a> </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.chinaxwcb.com/2011-03/29/content_219507.htm">[中国新闻出版报]2010年度《复印报刊资料》转载学术论文指数研究报告</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.chinaxwcb.com/2011-03/29/content_219508.htm"> [中国新闻出版报]学术期刊与评价体系的新探索</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://data.chinaxwcb.com/epaper/2011/2011-03-29/9208.html"> [中国新闻出版报]2010年度《复印报刊资料》 转载学术论文指数排名（一）</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://data.chinaxwcb.com/epaper/2011/2011-03-29/9209.html">[中国新闻出版报]2010年度《复印报刊资料》 转载学术论文指数排名（二）<br />
</a><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：文静 周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
