{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国际区域科学协会前主席Geoffrey教授访问经济学院并发表学术演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月13日上午，国际区域科学协会前主席、美国伊利诺伊大学香槟-厄巴那分校（UIUC）经济系主任、区域经济应用实验室（REAL）主任Geoffrey J.D. Hewings 教授访问经济学院，并在明德主楼734会议室发表学术演讲。经济学院区域与城市经济研究所所长孙久文教授出席演讲会并致辞，区域与城市经济研究所付晓东副教授、姚永玲副教授参加了演讲会。演讲会由文余源副教授主持。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzzmfynmhf-bhbhy.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 首先，孙久文教授对Geoffrey J.D. Hewings 教授的到来表示热烈欢迎，并就区域与城市经济研究所近年来的发展情况向Geoffrey J.D. Hewings 教授做了简要介绍。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，Geoffrey J.D. Hewings 教授发表了题为《港口效率与区域发展》和《基于地震减轻战略的区域宏观经济与网络系统的整合》两场学术报告。Geoffrey J.D. Hewings 教授从目前的研究现状与有待解决的问题讲起，引出文章的研究目的与研究目标，然后分别结合巴西和美国的情况，对模型的构造过程和构造方法进行了系统阐述。在此基础上进行了仿真模拟。最后，Geoffrey J.D. Hewings 教授与经济学院师生进行了热烈的讨论。 <br />
<br />
Geoffrey J.D. Hewings 教授简介 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Geoffrey J.D. Hewings 教授现为美国伊利诺伊大学香槟-厄巴那分校（UIUC）经济系主任、区域经济应用实验室（REAL）主任，国际投入产出协会顾问（2007-2015）。2001-2002年曾担任国际区域科学协会主席，2006-2007年任西部区域科学协会主席。2003年因其对区域科学的杰出贡献，被授予艾萨德奖。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='pubdate'}1287028866{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzzmfynmhf-bhbhy_lit.jpg{/dede:field}
