{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}马俊杰副书记参加班级元旦联欢活动 与学生共迎2011年新年{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/学生处 图/网新社 王开{/dede:field}
{dede:field name='body'}<p>　　12月31日晚，校党委副书记马俊杰教授来到公共教学二楼，亲切看望正在这里举行元旦联欢活动的学生并送上节日的祝福和礼包。学校办公室、学生工作部、校团委负责人陪同看望。 </p>
<p>　　马俊杰副书记首先来到2403教室，文学院2010级本科基地班的同学正在举行主题为&ldquo;家园&rdquo;的班级元旦共庆会，这是他们在人民大学度过的第一个新年。马俊杰副书记仔细聆听了主持人对班级情况的介绍，当得知该班一位同学不幸患病住院，是全班同学的热情关怀和悉心照顾使他走出困境并康复出院时，他深受感动并高度赞扬了班级同学之间互相帮助的真挚情谊，他对该班级在短短半年内所形成的凝聚力给予充分肯定，并为康复的同学送上了贺礼，预祝他今后的学习生活顺利。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mmzhnfhf-zmz2y.jpg" /></p>
<p>　　随后，马俊杰副书记一行依次来到2405和2409教室，教室里张灯结彩、暖意融融，充满着欢声笑语。新闻学院2010级新闻广电硕士班和财政金融学院2010级金融实验班的同学们载歌载舞，喜迎新年佳节。马俊杰副书记代表学校向同学们致以新年的祝福，寄语同学们在新的一年里身体健康、学习进步、团结友爱，同学们也将精心准备的贺卡和礼物送给马俊杰副书记。</p>
<p>　　在2216教室，商学院2010级<span style="WIDOWS: 2; TEXT-TRANSFORM: none; TEXT-INDENT: 0px; BORDER-COLLAPSE: separate; FONT: medium Simsun; WHITE-SPACE: normal; ORPHANS: 2; LETTER-SPACING: normal; COLOR: rgb(0,0,0); WORD-SPACING: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px" class="Apple-style-span"><span style="FONT-FAMILY: Tahoma, Verdana, STHeiTi, simsun, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: 12px" class="Apple-style-span">工商管理英文教学实验班</span></span>的同学正在联欢。马俊杰副书记与学生工作部张晓京部长在校团委书记费佳优美的歌声中，为大家献上优美的舞蹈，博得了同学们的阵阵掌声，将&ldquo;元旦狂欢夜&rdquo;的气氛推向了高潮。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mmznzbhf-2bzkb.jpg" /></p>
<p>　　最后，马俊杰副书记来到2221教室。经济学院2010级经济学本科班正在这里包饺子迎新年，马俊杰副书记恭祝大家节日快乐，温馨提示同学们注意身体，认真备战即将到来的期末考试。</p>
<p>　　马俊杰副书记每到一个教室，都为联欢的同学送上了大礼包和新年的祝福，受到了同学们的热烈欢迎。文学院院长孙郁教授、党委书记王贵元教授、党委副书记王林英老师，经济学院党委副书记明占生，财政金融学院党委副书记黄文彬，新闻学院党委副书记罗建晖，商学院党委副书记赵锦兰等各学院学生工作负责人和班主任老师及各学院团委书记们在新年到来的前夜，与同学们共度元旦佳节。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mmznkfyf-l2zhb.jpg" /></p>
<p>　　近年来，我校一直倡导以班级为单位在元旦前夕举办联欢活动，为同学们营造祥和的节日氛围。大量特色鲜明、亮点纷呈的集体活动在人大校园里涌现，这一举措加强了师生之间的沟通，增强了学院、班级、宿舍等各个学生集体的凝聚力，使同学们充分感受到师长的关爱、集体的温暖和校园的和谐。</p>
<p>　　（编辑：毛岩政）</p>{/dede:field}
{dede:field name='pubdate'}1294005489{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mmzhnfhf-zmz2y_lit.jpg{/dede:field}
