<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院杨瑞龙教授应邀到全国政协发表演讲",89,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",210,257);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-12 11:01:22",259,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为认真落实中央精神，全国政协经济委员会于11月10日召开&ldquo;积极调整国民收入分配结构，深化收入分配制度改革&rdquo;专题研讨会。经济学院院长杨瑞龙教授应邀在会上做了专题演讲。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙教授在演讲中，就农民工工资上涨所引发的农民工工资形成机制变革，及其对我国收入分配结构、经济结构调整所产生的效应及变革意义进行了深入而生动的阐释。演讲引起了与会者的极大兴趣，他们对杨瑞龙教授的观点给予了高度的评价。杨瑞龙教授还就相关问题和与会者进行了深入讨论。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王宝奎；核稿：丁凯)</p>",320,971);
$z[6][4]['name']="body";
$z[7]=Array("field","",973,1012);
$z[7][4]['name']="litpic";

?>