<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","日本富山大学教授代表团访问公共管理学院公共财政研究所并参加学术研讨会",89,195);
$z[2][4]['name']="title";
$z[3]=Array("field","",197,236);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",238,289);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-31 08:59:44",291,350);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月29日，日本富山大学经济学部主管中国人民大学交流事务的负责人中村和之教授、经济学科学科长垣田直树教授、龙世祥教授，远东地域研究中心山本雅志副教授访问公共管理学院公共财政研究所。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 访问期间，中日学者共同参加了以环境经济为主题的学术研讨会。首都经济贸易大学财政税务学院焦建国教授、中央财经大学财政学院杨华副教授，公共管理学院副院长兼公共财政研究所所长许光建教授、黄燕芬教授、崔军副教授、娜拉博士等中方学者参加了研讨会。会议由崔军副教授主持。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研究会上，中日学者就近期各界关注的环境政策、中国资源税改革、环境质量评价、环保产业发展、废弃物收入关系、环境NGO发展和循环经济国际分工等议题发表了演讲，并进行了热烈的讨论和交流。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />",352,1260);
$z[6][4]['name']="body";
$z[7]=Array("field","",1262,1301);
$z[7][4]['name']="litpic";

?>