{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}音乐系毕业生林静在美国国际声乐比赛中获得大奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-05-06 11:00:35{/dede:field}
{dede:field name='body'}<p>　　4月，在美国伊斯曼音乐学院举行的Lotte Lenya Competition国际声乐比赛总决赛中，艺术学院音乐系02级优秀毕业生林静，以扎实的基本功、完美的艺术表现，获得并列第二名的优异成绩和八千美元的奖金。 </p>
<p>　　Lotte Lenya Competition国际声乐比赛是一项难度极高的声乐赛事，要求参赛选手同时驾驭演唱歌剧和音乐剧曲目及片段两方面的专业技能，林静是第一位进入该国际大赛的亚洲人。其获奖新闻分别被美国的多家报纸和网络媒体报道，为人民大学和艺术学院争得了荣誉。 </p>
<p>　　林静在校期间，专业指导教师为杨明明讲师。</p>
<p>相关链接：<a href="http://news1.ruc.edu.cn/102449/102450/102502/74887.html">艺术学院毕业生林静晋级美国国际声乐大赛决赛 为首位入选亚洲人 </a></p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
