
-----------------------------------------------

<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='在线报名模块' link='catalog_do.php?dopost=guestbook' rank='plus_baoming' target='main' />
<m:item name='在线报名Ruc' link='catalog_do.php?dopost=guestbook' rank='plus_在线报名Ruc' target='main' />

  <m:item name='咨询会报名' link='catalog_do.php?dopost=zixunhui' rank='10' target='main' />
</m:top>

<m:top name='UCenter模块' c='6,' display='block' rank=''>
<m:item name='UCenter配置' link='api_ucenter.php' rank='' target='main' />
</m:top>
<m:top name='圈子管理' c='6,' display='block'>
<m:item name='分类设置' link='group_store.php' rank='group_All' target='main'/>
<m:item name='圈子列表' link='group_main.php' rank='group_All' target='main'/>
<m:item name='主题管理' link='group_threads.php' rank='group_All' target='main'/>
</m:top>
<m:top name='问答管理' c='6,' display='block' rank=''>
  <m:item name='栏目管理' link='../ask/admin.php?ct=asktype' rank='' target='main' />
  <m:item name='问题管理' link='../ask/admin.php?ct=issue' rank='' target='main' />
  <m:item name='答案管理' link='../ask/admin.php?ct=answer' rank='' target='main' />
  <m:item name='幻灯片管理' link='../ask/admin.php?ct=slide' rank='' target='main' />
</m:top>











-----------------------------------------------
