<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","外国语学院召开学科发展规划会议",89,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院",200,249);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-11-17 08:19:48",251,310);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月5日，外国语学院在明德国际楼学院会议室召开学科发展规划会议。学院领导班子全体成员、学术委员会委员、系部主任、学科带头人以及全部教授参加。会议由外国语学院院长何其莘教授主持。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 何其莘院长对学院2007-2010年的学科建设规划作了总结，并就下一个五至十年的学科建设规划有关问题进行了说明和工作部署。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 何其莘院长指出，外国语学院2007-2010年的学科发展规划大部分工作已基本完成，其余部分正在有条不紊的进行当中。要更好的完成下一个五至十年计划，外国语学院目前还存在着一些需要认真解决的问题。全院师生要抓住机遇，共同努力，让外语学科早日成为人民大学的主流学科，让外国语学院跻身国内先进行列。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会后，各教研室围绕会上布置的内容进行了细致的讨论。</p>\r\n<p>（编辑：刘恒）&nbsp;<br />\r\n</p>",312,1227);
$z[6][4]['name']="body";
$z[7]=Array("field","",1229,1268);
$z[7][4]['name']="litpic";

?>