<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国人民大学艺术学院音乐教学实践基地在深圳挂牌",89,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",216,269);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-15 10:27:41",271,330);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，经友好协商，中国人民大学艺术学院教学实践基地在深圳交响乐团正式挂牌。深圳交响乐团团长陈川松和艺术学院副院长赵方、音乐系副主任王玫及部分音乐系师生出席了挂牌仪式。 </p>\r\n<p align=\"center\"><img height=\"361\" src=\"/uploads/allimg/c110725/zlzzbyzhykyf2yf-zk2l2.jpg\" width=\"500\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 深圳交响乐团创办于1982年。在深圳市政府的大力支持下，经过20多年奋斗，已成长为中国优秀的职业交响乐团之一，在国内、国际乐坛有重要影响。艺术学院音乐表演系自创建以来，一贯注重教学实践，注重课堂教学和社会实践相结合，培养学生对未来实际工作的适应能力。此次&ldquo;深圳交响乐团教学实践基地&rdquo;的正式挂牌，为中国人民大学艺术学院音乐表演专业学生开展教学实践活动又提供了一个良好平台。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）</p>\r\n<p><br />\r\n<br />\r\n<br />\r\n</p>",332,1233);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhykyf2yf-zk2l2_lit.jpg",1235,1327);
$z[7][4]['name']="litpic";

?>