{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院与安国市举办“遏制艾滋 共建和谐社会”义演{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-05-25 10:02:22{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月23日，由安国市疾控中心、中国人民大学社会与人口学院、安国市东北药业协会主办的&ldquo;遏制艾滋 共建和谐社会&rdquo;公益晚会在安国市东方药城国贸会展中心广场举行。保定市卫生局、安国市相关部局领导以及社会与人口学院医学人类学刘谦老师、院团委书记唐颖老师出席此次活动。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlknyhkk2kf-z2lnb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 作为&ldquo;国际药材交流节&rdquo;开幕活动之一，晚会吸引了千余人到现场观看。社会与人口学院07级本科的孙骁骁、伍海诚同学与当地艺术家同台演出，带来的《We are Ready》、《少年》等节目，引得观众一片沸腾，将晚会推向最高潮。演出过程中，同时向观众发放了社会与人口学院与安国市共同编撰的艾滋病防治知识宣传品，还穿插了艾滋病、H1N1的防治知识竞答环节，观众踊跃参与，场面十分活跃。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，安国市古称&ldquo;祁州&rdquo;，是全国最大的中药材集散地，流动人口规模庞大，是我国防控传染病尤其是艾滋病疫情的重点地区。根据国务院《遏制与防治艾滋病行动计划2006&mdash;2010年》，中国人民大学社会与人口学院与安国市合作开展了预防艾滋病宣传干预的国家级项目。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张丽）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlknyhkk2kf-z2lnb_lit.jpg{/dede:field}
