{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}八百人大上演辩论盛宴{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院记者 杨晓晓 陈曦{/dede:field}
{dede:field name='pubdate'}2009-05-18 04:50:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月16日下午，由外国语学院分团委和学生会主办的中国人民大学第四届二十院友谊辩论赛总决赛暨明星赛在求实楼八百人教室举行。经过一番激烈的辩论，持&ldquo;回顾历史，我们更应该铭记苦难&rdquo;的反方经济学院辩论队战胜持&ldquo;回顾历史，我们更应该铭记辉煌&rdquo;的正方法学院辩论队，摘得桂冠。法学院三辩章真获得&ldquo;最佳辩手&rdquo;称号。至此，持续两个月的二十院友谊辩论赛圆满落下帷幕。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 担任本次比赛的评委有公共管理学院08级研究生木其坚、信息学院05级本科生章孜、公共管理学院05级本科生范丽莎、财政金融学院05级本科生焦乐，国际关系学院05级本科生许瑶以及外国语学院05级本科生舒柯榕等学校辩坛名人。外国语学院08级徐初照担任主席。校团委书记郑品石、经济学院党务秘书彭和、法学院团委书记郑小敏、法学院团委副书记何霞翔、校团委学术部部长康健以及外国语学院分团委书记商竞出席了本次比赛。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 双方选手从唐山地震的教训、大学生出国留学、民族工业的发展和食品安全等方面展开激烈争论。正方认为：百年的屈辱史让我们对苦难的记忆使我们丢失了许多对于辉煌的传承。处在这样一个和平发展的年代，要实现更大的突破，更需要铭记辉煌。这能让国人从自卑中走出，为我们迎接新的挑战增添信心、提供经验。而苦难给人们更多的，只能是痛苦、压抑和恐惧。</p>
<p align="center"><img src="/uploads/allimg/c100621/z2kkzlbnkknbhyf-zl2by.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 反方经济学院辩论队从&ldquo;中国并不缺乏自信&rdquo;入手批驳正方的观点，指出&ldquo;战胜苦难&rdquo;并不能简单的归为&ldquo;辉煌&rdquo;的定义，最后引出铭记苦难&ldquo;反思&rdquo;、&ldquo;批判&rdquo;和&ldquo;求变&rdquo;的三个作用。反方指出：铭记苦难可以带给国人更多的民族归属感，让国家在面对困难时坚不可摧；从认识未来看，铭记苦难带来了更加深刻的反思，更能激发起人的求变意识，给民族带来希望。在最后的总结陈词中双方坚定各自立场，以极富有渲染力和号召力的总结做画龙点睛，为整场比赛画上了浓墨重彩的一笔。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自公共管理学院的知名辩手木其坚从&ldquo;合理&rdquo;和&ldquo;合情&rdquo;两方面对决赛进行了精彩点评。他对选手们的表现给予了充分的肯定和赞扬。同时也指出了辩论过程中存在的问题。希望选手们在解读辩题时，注意向&ldquo;合情&rdquo;方向侧重，紧扣立论，坚定立场，在现场感染力方面再多下功夫。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经过多位评委的郑重商议，经济学院辩论队在决赛中更胜一筹，摘得了决赛桂冠。法学院的三辩彭真获得&ldquo;最佳辩手&rdquo;称号。</p>
<p align="center"><img src="/uploads/allimg/c100621/z2kkzlbnknlmzkf-2z2zl.jpg" alt="" /></p>
<p align="center"><img src="/uploads/allimg/c100621/z2kkzlbnknkf22f-lyyb2.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经济学院三辩秦世哲告诉记者，作为唯一一支经过加赛才进入八强的队伍，经济学院辩论队的晋级道路充满坎坷。&ldquo;我总是觉得肩负着那么多支持我们、教导我们的人的期望，心里有一种神圣的使命感。今天，使命完成了，与比赛开始时相比，我的心情少了些激动，多了丝淡然的平静，&rdquo;秦世哲说，&ldquo;我要特别感谢队友们出色的发挥。希望我们通过不懈的努力和更加默契的配合能在今后的比赛中取得满意的成绩，以此回报大家对我们的信任和支持。&rdquo; </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 二十院友谊辩论赛是由外国语学院辩论队于2006年春季发起的，主要面向大一本科生的全校性辩论赛事，旨在活跃校园辩论气氛，为秋季举行的校辩论赛培养辩论人才。第四届二十院友谊辩论赛于三月初拉开帷幕，共有外国语学院、农业与农村发展学院、经济学院、法学院、财政金融学院、新闻学院、国学院、信息资源管理学院、统计学院、公共管理学院、马克思主义学院、社会与人口学院、商学院、历史学院、文学院、哲学院、国际关系学院、信息学院、理学院以及环境学院等二十个学院辩论队参加。二十院友谊辩论赛每场比赛都由高年级的优秀辩手担任评委，它为新老辩手交流辩论经验打造了一个良好的平台，吸引了学校师生的广泛关注。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbnkknbhyf-zl2by_lit.jpg{/dede:field}
