{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第六届中俄大众传媒发展学术研讨会在京举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-06-22 11:32:02{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月12-13日，由俄罗斯莫斯科大学新闻系、中国人民大学新闻与社会发展研究中心、中国传媒大学电视与新闻学院主办的第六届中俄大众传媒发展学术研讨会在北京广播大厦召开。本次会议由传媒大学电视与新闻学院承办。来自俄罗斯莫斯科大学、乌拉尔大学和中国人民大学、中国传媒大学、清华大学、华中科技大学、南京大学、暨南大学等中国各高校、新闻媒体的学者70余人出席会议。新闻学院郑保卫教授、陈力丹教授、赵永华副教授、博士后许海等出席会议并在会上做了发言。他们的发言主题分别是&ldquo;论社会转型与传媒责任&rdquo;、&ldquo;传媒对于事实的判断要有基本的法治和政策意识&rdquo;、&ldquo;《纽约时报》对乌克兰橙色革命报道的框架分析&rdquo;、&ldquo;转型社会特征与媒介功能定位&rdquo;。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会开幕式由中国传媒大学电视与新闻学院党总支书记兼新闻系主任雷跃捷主持，中国传媒大学副校长丁俊杰致欢迎词，中国传媒大学电视与新闻学院院长高晓虹、莫斯科大学新闻系顾问扎苏尔斯基和中国人民大学新闻与社会发展研究中心主任郑保卫致辞。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmffnmlfn2f-z2mbk.jpg" /></p>
<p align="center">郑保卫教授在研讨会上评议</p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次研讨会设置了&ldquo;转型时期中俄大众传媒研究&rdquo;、&ldquo;社会转型与大众传媒&rdquo;、&ldquo;金融危机对大众传媒的影响&rdquo;、&ldquo;媒介融合背景下的大众传媒&rdquo;、&ldquo;转型时期的传媒公信力等&rdquo;五个子论题。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmffnmbyz2f-2nhyy.jpg" /></p>
<p align="center">陈力丹教授在研讨会上发言</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中俄大众传媒发展学术研讨会是中俄学者在新闻与传播学术领域开展学术交流与合作的平台，从2005年开始，由莫斯科大学新闻系、中国人民大学新闻与社会发展研究中心、中国传媒大学电视与新闻学院每年轮流举办一次，今年是第六届会议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经三家主办单位协商，第七届中俄大众传媒发展学术研讨会定于明年4月在莫斯科大学召开。</p>
<p>（编辑：程远芳）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmffnmlfn2f-z2mbk_lit.jpg{/dede:field}
