{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}芬兰赫尔辛基大学法学院代表团访问人民大学法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图/文 法学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 11:02:33{/dede:field}
{dede:field name='body'}<p>　　4月13日下午，中国人民大学法学院韩大元院长在明德法学楼205会议室会见了芬兰赫尔辛基大学法学院院长Kimmo Nuotio教授一行，国际法教研室赵秀文教授、外事秘书董立阳、陈磊陪同参加了会见。</p>
<p>　　芬兰赫尔辛基大学法学院代表团此次访问人民大学法学院的目的是向法学院学生推荐赫尔辛基大学法学院的学习项目，同时寻求与人大法学院就学生交流、教师交流方面的合作。赫尔辛基大学法学院院长Kimmo Nuotio教授首先简要介绍了赫尔辛基大学法学院及其今年秋季学期首次举办的国际法硕士项目，该硕士项目计划面向世界各国法学院院校招生30名并免学费。随着中国在世界舞台地位的提升，了解和熟悉中国法律的重要性与日俱增，因此，赫尔辛基大学法学院希望能与中国的法学院进行合作，促进学院教师、学生对中国法律的了解。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fyzyfmbf-22nnh.jpg" alt="" /></p>
<p>　　韩大元院长首先代表人民大学法学院对Kimmo Nuotio教授一行的来访表示欢迎。韩大元院长向Kimmo Nuotio教授简要介绍了人大法学院，并指出作为国内知名法学院，人大法学院正在努力寻求与世界知名法学院合作，为法学院学生创造更多的国际交流机会，从而培养更多国际化人才。目前，人大法学院与芬兰拉普兰大学已经建立合作伙伴关系，每年都有教师和学生赴芬兰拉普兰大学进行交流。赵秀文教授去年就受拉普兰大学法学院邀请在拉普兰大学从事教学活动，法学院董安生教授目前正在芬兰拉普兰大学法学院从事教学研究活动。赫尔辛基大学法学院是北欧地区著名的学术机构，人大法学院也希望能与赫尔辛基大学法学院合作。 人大法学院会将赫尔辛基大学法学院的项目介绍给法学院学生，如果学生对赫尔辛基大学法学院项目感兴趣，人大法学院将与赫尔辛基大学法学院探讨合作的相关细节。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fyzmbykf-lzhbh.jpg" alt="" />&nbsp;</p>
<p>　　会见中，双方还就各自法学院的学制、开展合作研究的资金来源等问题进行了探讨。</p>
<p>　　（编辑：苏璇）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fyzyfmbf-22nnh_lit.jpg{/dede:field}
