{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}统计学院高敏雪教授参加商务部考察团出访欧洲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-09-20 10:49:35{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp; 9月5日至15日，高敏雪教授作为主要技术专家参加商务部服务贸易考察团赴欧洲考察交流。&nbsp;&nbsp;&nbsp; </P>
<P>&nbsp;&nbsp;&nbsp; 访问单位包括联合国贸发会议（UNCTAD）统计司和贸易司、世贸组织（WTO）统计司和贸易司、经合发组织（OECD）统计司、欧盟经济部、意大利统计局和生产活动部、法国经济财政与工业部、比利时比中经贸委员会。&nbsp;&nbsp; </P>
<P>&nbsp;&nbsp;&nbsp; 伴随世界服务贸易的发展，中国已经开始关注国际服务贸易促进政策的研究和统计基础的建设，本次考察的主题主要集中于服务贸易统计和政府对服务贸易促进手段两个方面。此前高敏雪教授承担了《中国国际服务贸易统计制度》的设计工作。</P>
<P>&nbsp;</P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
