{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学-日本一桥大学2010共同论坛在深圳举办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月19日，主题为探讨世界经济增长与亚洲作用的中国人民大学&bull;日本一桥大学共同论坛2010在深圳举行。中国人民大学常务副校长袁卫教授，日本一桥大学副校长田近荣治教授，瑞穗实业银行（中国）有限公司深圳分行行长浅井邦夫等出席论坛并致辞。论坛由中国人民大学深圳研究院常务副院长陈建教授和日本一桥大学商学部三隅隆司教授共同主持。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 论坛闭幕式上，中国人民大学经济学院院长杨瑞龙教授和日本一桥大学研究生院商学研究科科长小川英治教授就全天的演讲和讨论进行了总结。两位教授充分肯定了此次共同论坛所取得的成果，同时希望未来两校能在更为广阔的领域展开更深入的合作。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届论坛由中国人民大学、日本一桥大学联合主办，瑞穗金融集团特别协办，中国人民大学经济学院、中国人民大学深圳研究院、北京长安投资集团有限公司、中山证券有限共同协办的。中央电视台、广东电视台、深圳特区报、深圳商报、深圳新闻网、深圳晚报等多家媒体对论坛进行了全面、深度的采访和报道。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1287524080{/dede:field}
{dede:field name='litpic'}{/dede:field}
