{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}教育部社会科学委员会哲学学部2009年度工作会议召开 冯惠玲副校长出席{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2009-11-24 09:48:54{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月21日至22日，由教育部社会科学委员会哲学学部主办、中国人民大学哲学院承办的教育部社会科学委员会哲学学部2009年度工作会议暨学科建设研讨会在友谊宾馆召开。中国人民大学副校长冯惠玲教授出席并致辞。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自全国各地的教育部社会科学委员会哲学学部委员和来自中国社会科学院、中共中央党校、国家行政学院和兄弟院校特邀专家和媒体嘉宾近40人参加了会议。与会专家学者围绕当前我国哲学学科发展的状况，面临的机遇、挑战和对策，哲学学科学风建设、人才培养等问题，进行了多方面的交流和深入的讨论。会上还就教育部社会科学委员会哲学学部2010年度工作规划进行了研讨。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
