{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}香港大学法学院访问人民大学法学院  王利明副书记兼副校长、法学院韩大元院长会见{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/法学院 丁玉琼、程静、王伟{/dede:field}
{dede:field name='pubdate'}2010-04-06 09:23:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月2日中午，人民大学王利明副书记兼副校长、法学院院韩大元院长于明德法学楼贵宾室会见了香港大学法学院陈弘毅教授、郁光华教授与陈伟汉教授一行，法学院宪法与行政法教研室许崇德教授参加了会见。陈弘毅教授为全国基本法委员会委员。郁光华教授是香港大学中国法研究中心主任。陈伟汉教授现任香港大学法学院副院长。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会见中，王利明副校长详细介绍了近三年来法学院硕博招生情况，比对了近两年法学院与北京其他高校法学院在数量、生源和专业分布等各方面的情况。韩院长追溯了人大法学院与港大法学院合作的历史，表示非常欢迎与港大法学院的合作，感谢港大法学院对中国人民大学法学院60周年院庆活动的关注，并热情邀请各位来宾参加法学院60周年院庆活动。三位来宾介绍了港大法学院的师资力量，简要说明了此次将在人民大学法学院举办的关于法律博士（JD）以及普通法硕士项目招生推介会的基本情况，并表示愿意积极与人民大学法学院以此次推介会为契机展开全方位的合作交流。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylykz2kbf-zlknf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后韩院长向三位来宾分别赠送了礼物，来宾向王副校长、韩院长和许教授回赠了礼品。会谈气氛轻松活泼，各位教授回顾了在全国基本法委员会工作的情景，深入交流了近期的学术研究动态并交换征询了意见。会见取得了圆满成功。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南） <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylykz2kbf-zlknf_lit.jpg{/dede:field}
