{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国务院参事、中央文史研究馆馆员聘书颁发仪式举行  温家宝为人大教授戴逸、时殷弘颁发聘书{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻中心{/dede:field}
{dede:field name='pubdate'}2011-04-15 09:42:45{/dede:field}
{dede:field name='body'}<p>　　4月14日上午，中共中央政治局常委、国务院总理温家宝在中南海向新聘任的８位国务院参事和５位中央文史研究馆馆员颁发聘书，并同参事、馆员座谈。中国人民大学教授戴逸、时殷弘分别以新聘任的中央文史研究馆馆员和国务院参事身份参加此次仪式和座谈。中国人民大学教授方立天也参加座谈并发言。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbnhbb2nf-ymhzl.jpg" /></p>
<p align="center">（温家宝等与新聘任的参事、馆员合影。 新华社记者黄敬文摄 ）</p>
<p>　　上午９时，聘书颁发仪式在中南海紫光阁举行。国务委员兼国务院秘书长马凯宣读国务院聘任通知。在热烈的掌声中，温家宝向新聘任的国务院参事王明明、汤敏、施祖麟、刘桓、时殷弘、张纲、王石奇、李烈和新聘任的中央文史研究馆馆员戴逸、汤一介、马振声、刘梦溪、陶思炎颁发聘书。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbnb2mmf-khlmm.jpg" /></p>
<p align="center">（温家宝向新聘任的中央文史研究馆馆员戴逸颁发聘书。 新华社记者黄敬文摄）</p>
<p>　　随后，温家宝在国务院小礼堂主持召开座谈会，这是他担任总理以来第五次同参事、馆员座谈。座谈会上，夏斌、陈全生、杨世基、蔡来兴、曲维枝、车书剑、袁行霈、方立天就经济社会发展、科技教育、改善民生、文化宗教等问题先后发言。</p>
<p>　　在听取发言后，温家宝指出，大家的意见非常中肯，国务院及有关部门要认真研究。知者尽言，国家之利。政府的决策要符合实际，符合人民的意愿，就必须倾听来自人民的意见，集思广益。&ldquo;贤路当广而不当狭，言路当开而不当塞。&rdquo;我们鼓励讲真话，讲真话就要有听真话的条件。要创造条件让人民讲真话，让参事、馆员讲真话，在国家科学民主决策中发挥重要作用。 </p>
<p>　　温家宝对参事室、文史馆工作提出四点要求：第一，加强对经济社会发展中重大问题的政策研究。第二，重视对历史和国际经验的比较研究。第三，注重对社会转型期道德文化建设的研究。第四，发扬崇尚理性、追求真理的科学精神。</p>
<p>　　温家宝最后说，一个国家一个民族总要有一批心忧天下、勇于担当的人，总要有一批从容淡定、冷静思考的人，总要有一批刚直不阿、敢于直言的人。这是千百年来中国仁人志士崇高的精神追求，参事、馆员也要有这样的境界和追求。希望通过不懈努力，把参事室建成高水平的政府咨询机构，为推进中国特色社会主义伟大事业做出更大贡献。</p>
<p>　　马凯、杜青林以及有关部门负责人出席座谈会。</p>
<p>　　相关链接：　<a href="http://paper.people.com.cn/rmrb/html/2011-04/15/nw.D110000renmrb_20110415_1-03.htm">[人民日报]新聘任国务院参事、中央文史研究馆馆员聘书颁发仪式举行</a> </p>
<p>　　　　　　　　<a href="http://news.xinhuanet.com/politics/2011-04/14/c_121306390.htm">[新华网]温家宝与新聘任国务院参事、中央文史研究馆馆员座谈</a></p>
<p>　　　　　　　　<a href="http://politics.gmw.cn/2011-04/14/content_1833482.htm">[光明日报]温家宝：我们要创造条件让人民讲真话</a></p>
<p>　　　　　　　　<a href="http://news1.ruc.edu.cn/102376/103150/103154/58867.html">[人大新闻网]戴逸：潜心治史 淡泊名利</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://news1.ruc.edu.cn/102380/75290.html">[人大新闻网]个性学者时殷弘访谈：&ldquo;我是一个根本上受惠于中国和中国人民、因而理应为之好好服务的人&rdquo;</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://news.ruc.edu.cn/102392/66657.html">[人大新闻网]&nbsp;中国人民大学附属中学校长刘彭芝受聘为国务院参事</a></p>
<p>　　（编辑：文静 苏璇）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbnhbb2nf-ymhzl_lit.jpg{/dede:field}
