{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院徐唯辛教授出席哈佛中国论坛并演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-04-25 03:17:08{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第13届哈佛中国论坛于4月16日至4月18日在美国波士顿哈佛大学举行，中国人民大学艺术学院常务副院长徐唯辛教授应邀出席并作演讲。 <br />
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhn2nlh2f-hmznzn.jpg" alt="" /></p>
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一年一度的哈佛中国论坛作为北美最大的围绕中国问题的主题会议，以&ldquo;旨在促进中国与国际社会学术、经济和文化领域交流&rdquo;为主旨，将对于中国发展的讨论展现在世界舞台之上。今年哈佛中国论坛以&ldquo;新中国的成长与展望&rdquo;为主题，邀请了包括教育、传媒、金融、医疗、保险等各领域具有影响力的人士参与。本届论坛第一次尝试加入艺术分论坛&mdash;&mdash;&ldquo;中国当代艺术之路&rdquo;。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在当地时间4月17日的艺术论坛上，著名艺术家、艺术学院常务副院长徐唯辛教授做了题为《中国当代艺术现状及我的艺术实践》的演讲。徐唯辛教授梳理了改革开放30多年来中国当代艺术起源、发展的线索及标志性事件，介绍了近年来随着中国经济腾飞、文化发展当代艺术呈现的多元化趋势。他分析认为，由于国内外资本大规模进入艺术市场，当代艺术家面临自我重复及商业化、娱乐化趋势，当代艺术出现了于社会发展滞后的现象，艺术家应如何超越自我、推动社会的进步？徐唯辛教授提出了艺术家需要对社会问题有独到的思考和形式表达突破的问题。徐唯辛教授通过PPT还介绍了自己近年来的艺术创作实践，从矿工、农民工题材到大型装置作品《历史中国众生相》的创作，无论是思想内涵到艺术形式都表达了一位当代艺术家的探索和创新。&ldquo;艺术家如何对待艺术市场？&rdquo;在回答现场听众提问时，徐唯辛教授认为，艺术家应该坚持艺术理想，既尊重市场规律，又要与市场保持距离。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月19日，徐唯辛教授还前往美国西雅图华盛顿大学进行访问交流，并为该校艺术学院的师生和有关学者做了题为《艺术&bull;社会&bull;历史&mdash;&mdash;实践与思考》的演讲，同时进行了交流互动。 <br />
<br />
（编辑&nbsp; 燕燕）{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhn2nlh2f-hmznzn_lit.jpg{/dede:field}
