{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大研究生奋勇救火 山东省依汶镇人民政府致信学校表示感谢{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2009-03-02 10:20:16{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，山东省沂南县依汶镇人民政府给中国人民大学发来感谢信，对外国语学院研究生赵明明在春节返乡期间带领群众奋勇扑灭火情表示了诚挚的感谢。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 附信： </p>
<p align="center">感谢信 <br />
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学领导： </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 去信，首先祝各位领导工作顺利，身体健康，前程似锦！ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 感谢贵校为社会培养出了一位优秀的研究生赵明明，该同志政治素质高，集体荣誉感强，遇到突发事件，处事果断，一马当先，是广大人民群众的学习榜样。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 春节期间，由于我地群众用火不当，突发一次火情，赵明明同志见状，毫不犹豫，第一时间组织部分青年冲向火场，实施扑救，为我们顺利灭火起到至关重要的作用。该同志之所以表现的如此果敢是与贵校的培养教育分不开的，为表示谢意，特书此信。 <br />
</p>
<p align="right">沂南县依汶镇人民政府 <br />
2009年2月6日 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
