{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院同学喜获“创业之星”最高奖项{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-06-22 09:13:43{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月14日，中国人民大学首届学生&ldquo;创业之星&rdquo;大赛决赛在逸夫会堂举行。由环境学院博士生傅毅明带队，环境学院李佩洁、信息学院陈德良和朱清华组成的&ldquo;新社区节能减排服务&rdquo;项目团队荣获&ldquo;创业之星&rdquo;最高奖项，并获得学生创业园入驻钥匙，优先进入人大学生创业园孵化。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 比赛由中国国际金融有限公司执行总经理姚磊、泰山天使投资人曾炜安、汉能投资集团总经理余治华、《创业家》杂志社社长牛文文、中国青年创业国际计划（YBC）创业导师刘永印、黄华及中国人民大学文化科技园副总经理王国成等专家担任评委。知名主持人陈伟鸿、篮球评论员徐济成担任决赛主持人。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次创业大赛由中国人民大学文化科技园、中国人民大学学生就业指导中心、《创业家》杂志社、中国人民大学校友工作办公室等单位联合主办。大赛于2009年4月正式启动，经过创业指导培训、职业生涯规划测评、并经过初赛选拔，33支参赛队伍中的9支优胜队伍进入了总决赛。最终决出了&ldquo;创业之星&rdquo;最高奖项和最佳创意奖、最佳创业方案奖、最佳团队合作奖、最佳商业模式奖、最佳表现奖五个单项奖以及大赛优胜奖。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
