<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院杨瑞龙院长赴日本京都大学发表学术演讲",89,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",214,261);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年11月28日，受日本京都大学经济学院的邀请，经济学院院长杨瑞龙教授赴日本参加了由京都大学主办的&ldquo;中国经济结构的转化&mdash;&mdash;日本的经验及其比较&rdquo;国际学术会议。杨瑞龙院长发表了题为&ldquo;后金融危机时代中国经济增长的源泉及其可行路径&rdquo;的学术演讲。与会专家对杨瑞龙院长提出的有关中国的产业升级及现代服务业的发展、技术创新对未来中国经济长期增长的作用及机制的相关观点产生了浓厚的兴趣，并展开了热烈的讨论。会上，杨瑞龙院长还介绍了人民大学的常设性论坛&ldquo;中国宏观经济论坛&rdquo;及其影响力，与会嘉宾会后纷纷就如何与人大开展宏观经济方向的合作研究与交流展开了广泛的讨论。会上，复旦大学经济学院袁志刚院长、国家发改委胡春力研究员及京都大学多名教授发表了演讲，会议取得了圆满成功。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzhylllh2zf-22fmh.jpg\" alt=\"\" /></p>\r\n<p><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议期间，杨瑞龙院长会见了京都大学经济学部学部长八木纪一郎教授。2009年9月，两院之间签署了合作协议，在人民大学成立了&ldquo;中国人民大学-京都大学联合经济研究中心&rdquo;。本次会谈就如何进一步加强双方的教师合作与学生交流、建设联合经济研究中心展开了深入的讨论。特别是双方在联合申请课题方面已取得了突破性进展，并决定今后每年轮流在对方召开学术研讨会，并就互派学生，特别是合作培养研究生方面达成了一致的看法。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzhylkynzmf-l2kfy.jpg\" width=\"500\" height=\"332\" alt=\"\" /></p>\r\n<p>\r\n</p>",263,1724);
$z[5][4]['name']="body";
$z[6]=Array("field","1260211306",1726,1776);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c100619/z2kymzhylllh2zf-22fmh_lit.jpg",1778,1870);
$z[7][4]['name']="litpic";

?>