{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院优质成长计划促进大学人才培养{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-09-16 09:00:06{/dede:field}
{dede:field name='body'}<p>　　9月11日上午，作为社会与人口学院(SSPS)首创的人才培养项目，筹备近两年的&ldquo;优质成长计划&rdquo;网站启动仪式在求是楼举行。社会与人口学院院长翟振武教授、院党委书记郭星华教授启动网站，人民大学一级荣誉教授、著名人口学家邬沧萍老师出席了启动仪式。</p>
<p>　　&ldquo;优质成长计划&rdquo;旨在以自主化（self-dependent）、社会化（socialized）、专业化（professional）、系统化（systematic）的育人机制，服务学生的全面成长。该计划依照大学生的成长特点和规律，将本科划分为三个阶段，每个阶段分别对应不同的成长主题和中心任务：大一阶段&ldquo;转变社会角色，适应大学生活&rdquo;，称为&ldquo;萌动&rdquo;；大二、大三阶段&ldquo;提升个人价值，感受专业魅力&rdquo;，称为&ldquo;炫彩&rdquo;；大四阶段&ldquo;确定人生航向，成就职场达人&rdquo;，称为&ldquo;蝶变&rdquo;。</p>
<p>　　同时，六条主线贯穿其中：职业规划、社会交往、心理健康、学业指导、体能训练、艺术修养，概括了学生成长的六个基本维度，也阐明了不同时期学生工作的重点。作为&ldquo;计划&rdquo;的纸质载体，《成长手册》在记录成长足迹、把握成长方向、提升成长质量等方面发挥着至关重要的作用。</p>
<p>　　社会与人口学院的相关负责人和本硕博近三百名新生参加了仪式。启动仪式上，领导小组向2009级本科新生发放了&ldquo;成长手册&rdquo;，以指导他们今后的学习和生活。&nbsp;</p>
<p>　　链接：&ldquo;优质成长计划&rdquo;网站　<a href="http://ssps.ruc.edu.cn/hdp/">http://ssps.ruc.edu.cn/hdp/</a></p>
<p>　　（编辑　徐静 ）<br />
&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
