{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学段成荣教授荣获“腾讯公益新公民创新奖”影响力大奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-12-23 04:34:09{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月19日下午，&ldquo;腾讯公益新公民创新奖&rdquo;颁奖仪式在北京举行。中国人民大学社会与人口学院党委副书记、人口学系主任段成荣教授荣获&ldquo;腾讯公益新公民创新奖&rdquo;影响力大奖。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;腾讯公益新公民创新奖&rdquo;影响力大奖共设两项，&ldquo;传播类&rdquo;用于奖励媒体，&ldquo;学术贡献类&rdquo;则用于奖励专家学者。本次该两项影响力大奖分别由《人民日报》社和段成荣教授获得。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为了宣传和推广为农民工子女受教育环境的改善做出过重要贡献的地方政府、企业、公益机构、媒体、学校和个人，21世纪教育研究院、腾讯公益慈善基金会、南都公益基金会、北京市西部阳光农村发展基金会、新公民之友等组织联合组织了此次&ldquo;腾讯公益新公民创新奖&rdquo;评选活动。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在评选活动的第一阶段，经过专家提名，来自中国人民大学、教育部基础教育司、教育部中央教育科学研究所、北京大学、华中师范大学、北京市社科院等单位的10位专家学者入围学术贡献奖候选人。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据了解，早在2000年，段成荣教授就明确指出了流动儿童少年教育问题具有&ldquo;长期性和全局性&rdquo;的特点，并提出&ldquo;城市和城镇教育系统应以积极的态度在流动儿童少年教育问题上发挥更大的作用&rdquo;；&ldquo;允许流动人口举办打工子弟学校&rdquo;；&ldquo;教育部在进行入学率和巩固率等教育统计时，将统计口径由现行的&lsquo;户籍人口&rsquo;统计口径改革为&lsquo;常住人口&rsquo;统计口径，从而将流动儿童少年教育问题纳入流入地的教育考核之中&rdquo;等观点，这些观点都具有一定的前瞻性。段成荣教授还利用2000年第五次全国人口普查的数据来概括和分析全国流动儿童的各项特征，为流动儿童面临的各方面问题，如教育、保健问题等的解决提供了一个基本的人口学依据，其中他推算出来的关于流动儿童和留守儿童数量，为学界所广泛引用。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在评选活动的第二阶段，因为在流动儿童和留守儿童研究领域做出的突出贡献和产生的广泛影响，段成荣教授不仅获得了网民的广泛支持，所获支持在10位候选人中遥遥领先；而且在由来自北京大学、复旦大学、北京师范大学、国家教育发展研究中心、新华社、《中国青年报》等单位的15位资深专家学者组成的专家委员会投票中也优势明显，因而荣膺学术贡献类影响力大奖。主办方在介绍段成荣教授的获奖理由时强调，他长期重视流动儿童教育问题的理论研究，创新性地引入统计资料研究的方法；在改善农民工子女教育问题上作为先锋具有不可替代的作用。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉)</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
