{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}张勇先教授等荣获“澳大利亚政府翻译图书奖”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}许道芝{/dede:field}
{dede:field name='pubdate'}2010-11-10 09:07:45{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月28日晚，澳大利亚政府澳中理事会在上海世博会澳大利亚馆举行颁奖仪式，授予中国人民大学澳大利亚研究中心主任张勇先教授及中心翻译成员&ldquo;澳中理事会2010年度翻译著作奖&rdquo;，以表彰中国人民大学澳研中心翻译澳大利亚大卫&bull;沃克教授的专著《澳大利亚与亚洲》，该译著于2009年由中国人民大学出版社出版并发行。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbnmmhlkkymf-lznmy.jpg" />&nbsp;</p>
<p align="center"><img height="500" alt="" width="333" src="/uploads/allimg/c101124/z2mfbnmmhhzbkf-hmmby.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大卫&bull;沃克教授是澳大利亚历史与文化研究的重要学者，现为澳大利亚人文学院院士和社科研院士。《澳大利亚与亚洲》（Anxious Nation: Australia and the Rise of Asia 1850-1939）一书回顾了1850年至1939年间澳大利亚对亚洲的认识与了解，书中引用了大量的史实及文学资料，以深刻的洞察力及精妙的笔法讲述了澳大利亚对近邻亚洲的&ldquo;焦虑和顾忌&rdquo;，是迄今为止对澳大利亚与亚洲历史最重要、最引人深思和最具启发性的学术专著。该译著的出版对增进澳大利亚历史的了解，促进澳中关系研究具有重大的意义。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnmmhlkkymf-lznmy_lit.jpg{/dede:field}
