<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","德国吉森大学Martin Glaum教授访问经济学院并发表学术演讲",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",224,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-29 10:15:58",273,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　3月23日下午，德国吉森大学Martin Glaum教授访问经济学院并发表学术演讲。经济学院院长助理郑新业副教授会见了Martin Glaum教授。经济学院教师虞义华博士、宋枫博士和杨继东博士参加会见。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflznzknnmfk2f-zkfnh.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p><br />\r\n　　郑新业副教授在会见中首先介绍了经济学院的总体情况，随后向Martin Glaum教授详细介绍了中国经济英文硕士项目。Martin Glaum教授表示对该项目有浓厚的兴趣，并希望双方未来能够有更深入的交流和合作。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110419/zlflznzknm2mhbf-2kyfm.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p><br />\r\n　　会见后，Martin Glaum教授在明德主楼728会议室世纪经英讲坛发表了题为&ldquo;国际会计准则与提高信息披露质量的重要性&rdquo;的学术演讲。Martin Glaum教授的演讲分两个部分，第一部分是一个关于会计准则差异及变化趋势的演讲。在这一部分，Glaum教授用其丰富的知识告诉学生们由于市场体制、税收体制及法律体系的不同，各国的会计制度本来是差异很大的。但随着国际化组合投资的剧烈增加，资本市场投资者对于企业信息披露的要求不断增加，各国会计制度呈现出趋同现象。第二部分，Martin Glaum教授介绍了他的研究成果 ，即国际上采用了IFRS即国际财务报表准则后，德国的企业确实提高了会计信息披露的质量，而信息披露质量的改善确实有利于投资者减少投资误判。 </p>\r\n<p>\r\n</p>",334,1648);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflznzknnmfk2f-zkfnh_lit.jpg",1650,1742);
$z[7][4]['name']="litpic";

?>