{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院陈立鹏副教授应邀参加中国少数民族双语教育研究会第十六次学术研讨会并做主题报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-07-22 07:03:29{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年7月15-18日，中国少数民族双语教育研究会第十六次学术研讨会在内蒙古自治区锡林格勒盟锡林浩特市隆重举行，来自国家民委、教育部、北京大学、中央民族大学、北京师范大学等单位的200余位代表参加了会议。与会代表围绕双语教育的和谐发展与可持续发展进行了广泛的交流与讨论。应学会会长丁文楼教授的邀请，公共管理学院教育研究所副所长陈立鹏副教授应邀参加了会议，并做了题为&ldquo;西藏双语教育：现状、问题与对策&rdquo;的主题报告，报告以西藏双语教育为个案，对我国双语教育及双语教育政策的现状、问题进行了分析，提出了进一步推动少数民族双语教育改革与发展的对策建议。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国少数民族双语教育研究会成立于1979年，是研究交流民族双语教育、民族教育的国家一级学会，业务指导单位为国家民族事务委员会。</p>
<p>（编辑：罗豫伟）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
