{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}药品和医疗技术准入与评估研讨会顺利召开，牛维麟常务副书记出席会议并致辞{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-07-22 04:04:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年7月18-19日，由中国人民大学公共管理学院和医改研究中心主办的&ldquo;药品和医疗技术准入与评估研讨会&rdquo;（RUC-NICE Annual Conference）在逸夫会议中心顺利召开。来自国家八个部委的领导，公立医院高级管理人员代表，国内十三家核心及行业代表性报刊杂志的社长、主编人员，国际知名医药企业代表，以及来自世界银行、世界卫生组织、英国驻华使馆、意大利驻华使馆等近150名代表出席了会议。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校党委常务副书记牛维麟教授出席会议并致辞。牛维麟常务副书记在讲话中肯定了医改研究中心和英国国家卫生医疗质量标准署（National Institute for Health and Clinical Excellence，NICE）的合作以及取得的成就，并希望医改研究中心能够一如既往地致力于我国卫生医疗体制改革和公共卫生政策的研究，在为政府部门提供学术支持和决策参考方面做出新的贡献。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 公共管理学院院长董克用教授、副院长蓝志勇教授出席会议并分别主持了两天的会议日程。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 医改研究中心主任王虎峰以&ldquo;药品和医疗技术评估是一个世界性课题&mdash;&mdash;与NICE合作的研究成果&rdquo;为题做开场演讲，系统汇报了合作研究的成果，提出了进一步建立和完善我国相关制度的建议和研究思路。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; NICE主席迈克尔&bull;洛林斯（Michael Rawlins）先生、澳大利亚药物报销目录评估委员会（Pharmaceutical Benefits Advisory Committee，PBAC）主席劳埃德&bull;桑瑟姆（Lloyd Sansom）先生、NICE技术评估委员会（Technology Appraisals Committee，TAC）主席安德鲁&bull;史蒂文斯（Andrew Stevens）先生、NICE国际部主任卡里普索&bull;查肯都（Kalipso Chalkidou）女士和美国哥伦比亚大学的专家麦可&bull;古斯曼诺（Michael Gusmano）分别就英国、澳大利亚、美国的药品和医疗技术准入的制度运行、政策体系、管理等有关方面进行系统介绍和深入讨论。人力资源和社会保障部医疗保险司司长姚宏、国家食品药品监督管理局政策法规司巡视员许嘉齐、卫生部医政司医疗管理处处长焦雅辉、国家发展和改革委员会价格司医药价格处副处长朱德政等嘉宾分别就我国药物准入、药品目录管理、药品价格管理、医疗技术准入问题进行了演讲和讨论。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年8月，医改研究中心与国际上久负盛名的NICE签署了合作备忘录，建立了学术合作机制，加强了我校在卫生医疗服务标准体系方面的研究。本次研讨会后，医改研究中心将继续定期开展交流活动并召开研讨会，同时积极借鉴国际经验，为制定和完善我国卫生医疗服务标准做出更大的贡献。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
