<dl>
	dfdfdfd[field:array runphp='yes']@me = (empty(@me['litpic']) ? &quot;&quot; : &quot;<dt class=\"img\"><a href=../ructpl/\%22{@me[%27arcurl%27]}\%22><img onload=\"hideno(this)\" alt=\"\" src=../ructpl/\%22{@me[%27litpic%27]}\%22/></a></dt>&quot;); 
	[/field:array]
	<dt><a href="../ructpl/[field:arcurl/]" class="tit">[field:title/]</a> </dt>
	<dd>[field:description/]...&#65533;&#65533;<span>_[field:pubdate 
	function=&quot;GetDateMK(@me)&quot;/]</span>&#65533;&#65533;<a href="../ructpl/[field:arcurl/]">&#65533;&#65533;&#1016;&gt;&gt;</a></dd>
</dl>