{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学和UNDP在哥本哈根联合举办“中国低碳发展道路”高层研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-12-24 09:37:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随着联合国哥本哈根气候变化大会进入冲刺阶段， 12月15日，由中国人民大学&ldquo;能源与气候经济学项目&rdquo;与联合国开发计划署联合举办的&ldquo;中国低碳经济发展道路&rdquo;高层研讨会在哥本哈根成功举办。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfbklzllf-zkkbz.jpg" />&nbsp;</p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国国家人口和计划生育委员会副主任赵白鸽，联合国开发计划署署长海伦&bull;克拉克，挪威环境与发展大臣索尔海姆，联合国环境规划署执行主任阿齐姆&bull;施泰纳，联合国驻华系统协调代表兼联合国开发计划署驻华代表马和励，&ldquo;壹基金&rdquo;创始人李连杰，中国人民大学教授、2009/10年中国国家人类发展报告负责人邹骥、中国社会科学院城市发展与环境研究中心主任潘家华，斯德哥尔摩国际环境研究院执行院长约翰&bull;洛克斯特略姆，德国波茨坦气候影响研究所所长谢尔洪伯教授等和来自各国非政府组织、媒体的200余人出席了此次会议。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国国家人口和计划生育委员会副主任赵白鸽宣读了讲话稿。他指出中国将从加强政策引导和宏观协调，贯彻落实各项政策措施，部署发展低碳经济试点工作，提高发展低碳经济相关能力建设，加强宣传教育，提高全民意识，组织开展对外交流与合作等六个方面推动低碳经济的发展。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议发布了2009/10年中国人类发展报告《中国的低碳经济和社会之路》中的初步研究成果。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学邹骥教授代表&ldquo;2009/10年中国人类发展报告&rdquo;项目组向与会来宾介绍了该报告的主要发现。他提出：&ldquo;发展低碳经济应充分考虑人类发展的需求和国别差异。中国作为发展中国国家，面临着发展低碳经济的种种机遇与挑战，仍需将提高人类发展水平和实现可持续发展作为发展低碳经济的首要目标，在为发展低碳经济而配置社会资源时要合理兼顾不同政策目标，包括兼顾更为紧迫的消除贫困、加大民生工程建设的需求等&rdquo;。他指出&ldquo;报告基于对中国经济长期发展趋势的判断，利用自下向上的能源技术非线性优化模型，开展了中国低碳经济情景研究。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研究发现，当把中国的碳强度控排目标设定为40%以上时，增量成本则将加速倍增。如果把控排目标分别设定在40%、45%和50%时，对应的增量减排成本将从不大于0的水平经每年300亿美元迅速上升到860亿美元，单位减排成本也从不大于0经14迅速倍增至27美元/吨CO2。同时，研究发现向低碳经济的成功转型需要有62种关键的专门技术和通用技术的支撑，而在其中的42种关键技术中，中国目前并不掌握核心技术&rdquo;。基于以上分析，邹骥教授强调：&ldquo;发达国家在资金、技术转让和能力建设上的行动将对中国的低碳转型起重要作用，基于&ldquo;共同但有区别的责任，发达国家应当为应对气候变化承担更多的责任，也应当履行向发展中国家提供资金、技术和能力建设支持的责任&rdquo;。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfbkmfyzf-2mhkf.jpg" />&nbsp;</p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 发言结束后，挪威环境与发展大臣索尔海姆向邹骥教授提出了问题：中国政府控排目标相对于全球控温2度的目标而言是否仍然不够？对此，邹骥教授坦率回应，认为原因之一是发达国家提供的技术资金支持不够。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 联合国开发计划署署长海伦&bull;克拉克也在会上致词并进一步指出：&ldquo;2009/10年中国人类发展报告的发布将有助于推动关于中国向低碳经济转型问题的讨论&rdquo;。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009/10年中国人类发展报告是由中国人民大学和联合国开发计划署驻华代表处联合撰写的，报告以低碳经济和社会为主题，从构造反映中国国情和利益的低碳经济概念入手，讨论了发展低碳经济，建设低碳社会与提高人类发展水平之间的关系，识别了中国建设低碳经济社会的关键影响因素和所面临的挑战和机遇，探讨了中国未来低碳发展路径及相应的资金、技术、体制、政策需求。报告全文将以中、英文两种语言出版，预计将于2010年年初正式发布。</p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c100622/z2kkzlnfbn2zhkf-lz22m.gif" /></p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑&nbsp; 刘男）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfbklzllf-zkkbz_lit.jpg{/dede:field}
