{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院教授代表团赴台湾世新大学出席首届“传播研究与实践”研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2011-03-08 03:11:03{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应台湾世新大学邀请，中国人民大学荣誉一级教授方汉奇先生、新闻学院常务副院长倪宁教授、新闻史论教研部陈力丹教授、王润泽副教授组成的新闻学院教授代表团2月24日出席了在台北举行的第一届&ldquo;传播研究与实践&rdquo;研讨会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;研讨的主题包括&ldquo;新闻史的过去现在与未来&rdquo;、&ldquo;跨学科视角下的传播发展历程&rdquo;、&ldquo;两岸传播教育发展论坛、传播领域的分立和整合&rdquo;等。&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次研讨会是由中国人民大学、复旦大学和世新大学等高校联合主办的，旨在促进两岸三地新闻传播学术研究特别是新闻传播史的研究。经协商，香港中文大学也加入到主办行列，并力争使研讨会形成常态化机制。第二届&ldquo;传播研究与实践&rdquo;研讨会将于2012年在中国人民大学举行。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻学院教授代表团还访问了台湾政治大学。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
