{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大舆论研究所与波兰人类思维和大脑研究中心签署学术合作协议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院　文/石春凝 图/赖曾濂{/dede:field}
{dede:field name='pubdate'}2011-03-11 03:08:49{/dede:field}
{dede:field name='body'}<p>　　3月9日下午，在新闻学院常务副院长倪宁和众多师生的见证下，学院副院长喻国明和著名的潜意识研究专家Rafal Ohme教授分别代表中国人民大学舆论研究所和波兰人类思维和大脑研究中心签订了学术合作协议。该协议的签订为促进传播学和认知神经学科间的互动交流、拓展研究视野、形成跨学科合作提供了良好的平台，也使得中国人民大学新闻学院成为大陆唯一拥有能够从认知神经学科进行传播学研究技术和人才的新闻类院系。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110419/zlflznzbyybbhzf-lmnhh.jpg" /></p>
<p>　　合作协议签署前，继去年12月后，第二次来新闻学院访问的Rafal Ohme教授还为学院师生带来了题为&ldquo;21世纪传播的七大发现&rdquo;讲座。讲座将认知神经学科研究领域的技术手段和最新成果与传播学相结合，向大家介绍了如何通过对受众脑部的直接观察，了解受众对不同广告、电影、音乐等刺激的脑部反应，从而更好的进行传播效果研究。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflznzbyk22kmf-hkfb2.jpg" /></p>
<p>　　Rafal Ohme2003年在波兰华沙科学院获得教授资格，现供职于华沙社会科学院人类思维和大脑研究中心，为美国广告协会、美国心理学会、 欧洲广告研究院等知名专业协会会员。Ohme的研究主要集中于潜意识信息的信息处理、生理历程的神经心理的测量等。他在上述领域进行了多项有影响的实验研究、撰写了多篇学术论文和专著，并组织过多场国际性会议。 </p>
<p>　　（编辑：易晨）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzbyybbhzf-lmnhh_lit.jpg{/dede:field}
