{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长应邀为教育部高等教育司工作人员作专题报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月12日，纪宝成校长应邀为教育部高等教育司全体工作人员作了题为&ldquo;关于高等文科教育的几点思考&rdquo;的报告。在报告中，纪宝成校长系统阐述了人文社会科学的内涵、特点及其对社会发展和物质生产的重要作用。他提出，要树立问题意识、开放意识、学科交叉融合的意识，发展与时俱进的人文社会科学；要坚持马克思主义的指导地位，注重当代中国的国情和实践，注重中国传统文化的研究和弘扬，注重出精品，发展中国特色、中国风格、中国气派的人文社会科学。他还指出，当前发展人文社会科学存在着重理轻文、&ldquo;四个同等重要&rdquo;在制度上尚未落实、投入不足、学风问题和优质教育资源匮乏等问题，而解决这些问题需要大家的共同努力。纪校长还回答了现场提出的问题。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部部长助理林蕙青在报告前会见了纪宝成校长。高教司张大良司长主持报告会。高教司副司长及全体工作人员，社科司、学生司和学位办有关干部参加了报告会。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='pubdate'}1289500049{/dede:field}
{dede:field name='litpic'}{/dede:field}
