{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院王虎峰副教授应邀赴英国参加学术研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-03-29 08:41:58{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应英国国家卫生质量标准署(National Institute for health and Clinical Excellence, NICE)邀请，公共管理学院王虎峰副教授于近日赴英国伦敦参加主题为&ldquo;社会价值在药品和医疗技术准入中的应用&rdquo;研讨会，作为中国专家代表介绍中国药品和医疗技术准入中社会价值的体现和公众参与状况，并参加专家组工作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会由英国国家卫生质量标准署主办，来自10多个国家和世界卫生组织的20余位专家学者参会并研讨，会议旨在交流国际经验，为建立一个国际通用的在药品和医疗技术准入中体现社会价值的制度框架和原则提供借鉴。本会议的主题和合作网络组织将长期保持下去，定期开展交流，最终形成全球影响的指导标准。今年6月将在里约热内卢召开第二次工作会议。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
