<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","人大环境学院邀请美国里士满大学法学院教授Joel B. Eisen学术交流",89,188);
$z[2][4]['name']="title";
$z[3]=Array("field","",190,229);
$z[3][4]['name']="writer";
$z[4]=Array("field","环境学院",231,278);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-03-19 10:51:51",280,339);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　3月17日，美国里士满大学(University of Richmond)法学院教授、中国政法大学富布赖特法学教授Joel B. Eisen应邀来人大环境学院进行学术交流。Joel Eisen教授做了主题为&rdquo;Environmental Aspects of Urban Renewals in U.S. and China&rdquo;的讲座。Eisen教授简要介绍了自己的研究领域，从环境法的角度重点讲解了中美城市&ldquo;棕色地&rdquo;问题的性质、重要性及存在的问题，分析美国现行的相关法律政策，指出政府可以实行一些政策措施以激励企业或个人自愿治理城市&ldquo;棕色地&rdquo;。讲座期间，Eisen教授巧妙地用问题带动和激发在座师生的参与和思考，引发了深入而激烈的讨论，使与会者受到许多启发。讲座受到广大师生的欢迎。 <br />\r\n<br />\r\n　　人大环境学院马中院长、吴俊杰等教授以及各专业学生参加了此次交流。</p>\r\n<p>　　（编辑：陈燕）</p>",341,1094);
$z[6][4]['name']="body";
$z[7]=Array("field","",1096,1135);
$z[7][4]['name']="litpic";

?>