{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本大使馆官员访问法学院 商议举办“中日劳动政策高峰论坛”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-24 09:03:10{/dede:field}
{dede:field name='body'}<p>　　5月13日下午，法学院林嘉书记会见了来访的日本大使馆官员中村宇一、罗佳，商议联合举办&ldquo;中日劳动政策高峰论坛&rdquo;。法学院院长助理杨东副教授陪同会谈。 <br />
<br />
　　经过商议，人民大学法学院和日本大使馆、日本厚生劳动省、中国政府相关机构等，定于6月29日（星期二）在中国人民大学联合举行&ldquo;中日劳动政策高峰论坛&rdquo;。该高峰论坛作为中国人民大学法学院创立60周年纪念活动的一环，由中国人民大学与日本厚生劳动省共同主办。日本厚生劳动省细川副大臣和相关主管官员，以及日本劳动法专家学者和日本驻华大使馆有关人员将出席本研讨会。中国人力资源和社会保障部官员及中国劳动法领域的著名专家学者亦将出席本研讨会。本研讨会致力于中国和日本共同面对的劳动问题的探讨，将主要围绕&ldquo;工资及差距&rdquo;和&ldquo;劳动纠纷和劳动者权益保护&rdquo;两个主题展开讨论。中日双方参会人员将分别就两国关于最低工资的发展动向、劳资之间如何实现工资调整、各类劳动者的收入差距、劳动纠纷的发生情况及最近趋势和纠纷解决机制等问题发表意见并交换看法。 </p>
<p>　　（编辑：於萍萍）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
