<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",18,95);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",137,153);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",155,240);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",271,286);
$z[4]=Array("imgwidth","",300,318);
$z[5]=Array("alttext","",324,341);
$z[6]=Array("linkurl","",393,409);
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",411,497);
$z[7][4]['runphp']="yes";
$z[8]=Array("alttext","",517,534);
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",578,658);
$z[9][4]['runphp']="yes";

?>