{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长一行到心理学系调研{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}心理学系{/dede:field}
{dede:field name='body'}<p>　　11月18日下午，纪宝成校长一行来到心理学系，就心理学系的筹建和发展情况进行调研，袁卫常务副校长陪同。心理学系系主任孙健敏就心理学系的建设和未来发展思路作了工作汇报。校长助理、财务处处长查显友，校长助理、学校办公室主任刘向兵，人事处处长郭洪林、发展规划处处长胡娟、教务处处长洪大用、科研处处长杜鹏、研究生院副院长刘凤良、实验室建设与设备管理处副处长张小岗、资产与后勤管理处副处长张卯、理学院党委书记李欣欣及心理学系教职工代表参加了调研会。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhmzlzzlf-bmbmm.jpg" /></p>
<p>　　纪校长首先指出，建设心理学系是人民大学提升国际性，建设世界一流大学的战略举措之一，是人民大学未来新的增长点。纪校长对心理学系建系以来取得的成绩给予了高度肯定，认为心理学系的建设已初成局面，初具规模，感到很满意，很欣慰，认为心理学系领导和教职工在初创阶段艰苦创业，做了大量工作，各部处也通力配合，他代表学校表示感谢。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhmzklnf-yblz2.jpg" />&nbsp;</p>
<p>　　针对心理学系的建设和未来发展的要求，纪校长在原来&ldquo;高起点、入主流&rdquo;的基础上，提出了&ldquo;国际性、高水平&rdquo;的新要求。纪校长充分肯定了心理学系提出的提升国际性的&ldquo;115工程&rdquo;，即以研究中国特色问题为突破口，提升国际发表的数量和质量（10种重点期刊），加大与国际机构的合作与联系（10所重点大学），通过国际会议和国际发表（5个重要学会），实现国际接轨，希望心理学系在师资队伍建设、教学活动安排、国际发表、国际交流等方面充分体现&ldquo;国际性&rdquo;的要求；希望心理学系尽快赶超国内心理学界的第二梯队，争取早日进入第一梯队，体现&ldquo;高水平&rdquo;。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhmzknknf-kmlyn.jpg" /></p>
<p>　　纪校长希望心理学系充分发挥&ldquo;后发&rdquo;优势，在学术氛围培育、教师关系处理、教学质量、制度建设等方面要有创新精神，树立新风气，建成一个&ldquo;小而精&rdquo;的心理学系。 </p>
<p>　　纪校长还就实验室用房、人才引进、经费支持、教师待遇等方面现场办公，解决了心理学系目前发展的诸多难题。 </p>
<p>　　会上，孙健敏教授向学校领导汇报了心理学系建系以来的工作、国内外心理学系发展状况、今后发展思路以及目前发展面临的挑战等方面，学校各部处也表示将全力支持心理学系的建设和发展。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfhmznh2nf-nbzbh.jpg" />&nbsp;</p>
<p>　　会后，纪校长一行参观了心理学系的实验室，并与心理学系教职工合影留念。 </p>
<p>　　（编辑：刘伟伟　易晨）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1290132159{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhmzlzzlf-bmbmm_lit.jpg{/dede:field}
