{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学艺术学院绘画系主任王克举教授举办个人画展{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-12-21 11:49:45{/dede:field}
{dede:field name='body'}<p>　　12月11日下午，由中国人民大学艺术学院、山东艺术学院、山东省美术家协会主办的&ldquo;山河之舞&rdquo;王克举油画作品展在山东省济南市山东博物馆开幕。本次展览展出的是王克举教授自2005年以来作品中精选出来的60余幅优秀之作。 </p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110725/zlzzbyzhklkfkmf-znlffk.jpg" alt="" /></p>
<p>　　中国人民大学艺术学院常务副院长徐唯辛、中国油画学会副主席张祖英、山东省美协主席、山东艺术学院院长张志民等参加了开幕式。在开幕式上，王克举教授向山东博物馆捐赠了油画作品一幅。 </p>
<p align="center"><img src="/uploads/allimg/c110725/zlzzbyzhkh2hbnf-zmzmbz.jpg" alt="" /></p>
<p>　　这次展览是王克举教授近年来风景写生新作的集中展示，同时也是他赴北京工作6年之后首次回到家乡举办大型个展。 </p>
<p>　　本次展览时间为12月11日至12月20日。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhklkfkmf-znlffk_lit.jpg{/dede:field}
