<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","人民大学艺术学院绘画系主任王克举教授举办个人画展",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",218,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-21 11:49:45",273,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　12月11日下午，由中国人民大学艺术学院、山东艺术学院、山东省美术家协会主办的&ldquo;山河之舞&rdquo;王克举油画作品展在山东省济南市山东博物馆开幕。本次展览展出的是王克举教授自2005年以来作品中精选出来的60余幅优秀之作。 </p>\r\n<p align=\"center\">&nbsp;<img src=\"/uploads/allimg/c110725/zlzzbyzhklkfkmf-znlffk.jpg\" alt=\"\" /></p>\r\n<p>　　中国人民大学艺术学院常务副院长徐唯辛、中国油画学会副主席张祖英、山东省美协主席、山东艺术学院院长张志民等参加了开幕式。在开幕式上，王克举教授向山东博物馆捐赠了油画作品一幅。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110725/zlzzbyzhkh2hbnf-zmzmbz.jpg\" alt=\"\" /></p>\r\n<p>　　这次展览是王克举教授近年来风景写生新作的集中展示，同时也是他赴北京工作6年之后首次回到家乡举办大型个展。 </p>\r\n<p>　　本次展览时间为12月11日至12月20日。 </p>\r\n<p>　　\r\n</p>",334,1157);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhklkfkmf-znlffk_lit.jpg",1159,1252);
$z[7][4]['name']="litpic";

?>