{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}刘俊海教授作客青岛电视台315特别节目“消费与民生”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院 文/李培华{/dede:field}
{dede:field name='pubdate'}2011-03-14 10:14:36{/dede:field}
{dede:field name='body'}<p>　　3月11日，刘俊海教授应邀赴青岛作客青岛电视台315特别节目&ldquo;消费与民生&rdquo;，并就《消费者权益保护法》颁布实施以来的社会、经济与法治意义，以及青岛如何创建全国消费放心满意城市发表了专家意见。</p>
<p>　　青岛市委常委、副市长长秦敏就青岛创建全国消费放心满意城市的总体思路发表了意见。青岛市工商局、青岛市质监局等部门的相关负责人以及中国消费者协会原副秘书长武高汉等专家学者也参加了电视访谈。</p>
<p>　　(编辑：席嘉怡)</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
