{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院举办第16届教授沙龙  何家弘教授“刑事错案的实证研究”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-20 09:03:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 18日中午，法学院第16届教授沙龙在明德法学楼601室举行，主题是&ldquo;刑事错案的实证研究&rdquo;。何家弘教授以近几年来对刑事错案的研究成果介绍了近日备受关注的&ldquo;赵作海涉嫌杀人冤案&rdquo;发生和纠正的过程，并从证据的角度对案件进行了分析。何家弘教授认 为，赵作海是个&ldquo;幸运的不幸者&rdquo;。说他不幸，是因为他受到了冤枉。而在只有&ldquo;证据确凿&rdquo;才能纠正错案的情况下，本案的&ldquo;被害人&rdquo;竟然生还，赵作海又是&ldquo;幸运&rdquo;的。接着，何家弘教授介绍到，错案问题并不是仅在中国发生的，他结合今年2月到美国辛辛那提大学法学院讲学的经历介绍了美国的刑事错案问题。目前，辛辛那提大学法学院正在筹备在明年的4月召开一个全球性的刑事错案研讨会，该校还有一个&ldquo;无辜者救援中心&rdquo;。并且从上个世纪九十年代中期开始，美国很多州就都成立了类似&ldquo;无辜者救援中心&rdquo;的组织，有&ldquo;无辜者行动计划&rdquo;（Innocent Project）。该计划主要是运用DNA技术对原来案件中的证据进行复查，来纠正可能存在错案。根据该校提供的数字，从九十年代中期到现在，该校的&ldquo;无辜者救援中心&rdquo;已经纠正了242起错案，这些被纠正的错案主要是强奸案，并且75%的案件都存在辨认错误。接下来何家弘教授具体以Joseph Abbitt Case为例，分析了美国刑事错案中的证据问题。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100619/z2kymzybflymmlf-2nzyl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 何家弘教授还介绍了他近年来对刑事错案进行实证研究的概况。自2006年以来，通过举办论坛、座谈会、研讨会、问卷调查和典型案例分析等方式，何家弘教授带领课题组对刑事错案的若干问题进行了实证研究。对&ldquo;刑事错案的产生原因&rdquo;和&ldquo;刑事错案与七种证据&rdquo;两个问题，课题组通过问卷调查的方式进行了实证研究。何家弘教授用一系列数字对研究结果做了介绍并讲述了50起错案和刑讯逼供问题的实证研究成果。 <br />
何家弘教授以&ldquo;石东玉杀人案&rdquo;为例进行了个案的错案剖析，并用幻灯片展示了来源于该案的一系列证据的照片，生动形象地向与会者介绍了一个错案的发生、发现和纠正的过程。对此，他感慨万千：一个错案的发生是比较容易的，&ldquo;一不留神&rdquo;就错了，但是纠正起来确十分难。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为什么会出现形式错案？何家弘教授认为：刑事司法存在着几个难题：即思维具有逆向性，认知具有间接性，结果具有模糊性，裁判具有明确性。 首先，证据问题是发生刑事错案的主要原因；其次，完善非法证据排除规则是防止刑事错案的当务之急；第三，提高办案人员收集运用证据的能力至关重要。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;针对错案，何家弘教授还分析了&ldquo;错判&rdquo;和&ldquo;错放&rdquo;的关系，提出在疑罪的情况下宁可错放也不能错判。面对错案，我们要吸取教训，推动司法改革。就此何家弘教授提出了自己的几点想法： <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 首先要从侦查中心走向审判中心； <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 其次从单轨调查走向双轨调查； <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第三从形式庭审走向实质庭审； <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第四从封闭裁判走向开放裁判。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;何家弘介绍提出了&ldquo;从法学到文学&rdquo;的概念，介绍了他根据&ldquo;石东玉杀人案&rdquo;创作《血之罪》。这是一本&ldquo;以错案为视角，以防范为动机，以人性为本源，以法治为皈依&rdquo;的反映刑事错案的小说。与会师生在入场的时候就获赠了何家弘教授新修订出版的这本书。 <br />
此次教授沙龙由法学院副院长胡锦光教授主持，我院数十位师生参加了本次沙龙。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 主讲阶段过后，孙国华教授、莫于川教授、杨晓青副教授等与会师生同何家弘教授进行了互动和热烈的讨论。讨论的话题涉及陪审团制度、&ldquo;无辜者救援中心&rdquo;在中国能不能搞、法学院的教育、政法委的地位和角色、错案的纠正、刑事案件中公诉人代表国家进行诉讼的宪法地位、司法的权威以及司法腐败等问题。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，胡锦光教授总结了本次沙龙，沙龙在大家热烈的掌声中结束。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzybflymmlf-2nzyl_lit.jpg{/dede:field}
