{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}薛浣白副校长赴广州参加亚洲大学校长论坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际交流处{/dede:field}
{dede:field name='body'}<p>　　11月12日-14日，薛浣白副校长赴广州参加了由教育部主办的&ldquo;亚洲大学校长论坛&rdquo;。</p>
<p>　　此次论坛是首次由政府牵头举办的亚洲地区大学校长论坛。来自印度、韩国、日本、新加坡、泰国、叙利亚、哈萨克斯坦以及中国等23个亚洲国家的80多所知名大学的校长参加了会议。参会代表围绕&ldquo;亚州高等教育面临的机遇与挑战&rdquo;、&ldquo;区域经济调整与大学学科专业建设&rdquo;以及&ldquo;高校发挥科技支撑作用促进区域经济发展&rdquo;等议题进行了充分讨论和交流。 </p>
<p>　　(编辑：王开)</p>{/dede:field}
{dede:field name='pubdate'}1289937125{/dede:field}
{dede:field name='litpic'}{/dede:field}
