{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}吴玉章学术讲座：葛墨林院士谈基础研究与技术创新{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}科研处{/dede:field}
{dede:field name='pubdate'}2012-06-05 11:17:23{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月30日下午，中国人民大学著名学术品牌&mdash;&mdash;&ldquo;吴玉章学术讲座&rdquo;在逸夫第一报告厅隆重拉开帷幕，著名理论物理学家、中国科学院院士葛墨林先生做了题为&ldquo;宁拙毋巧 宁朴毋华：漫谈基础研究与技术创新&rdquo;的精彩学术报告。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 冯惠玲副校长首先致欢迎词，她回顾了吴玉章讲座的历史和传统，对葛墨林院士的到来表示感谢，并向葛先生赠送了吴玉章学术讲座特制纪念杯。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在学术报告中，葛院士简要回顾了物理学的发展历程，着重介绍了当前物理学与其它学科交叉融合的趋势。葛院士强调，基础研究在以个人兴趣与求知为动力的同时，应当重视国家重大需求，注意物理效应的潜在应用，以及对技术发展的促进。葛院士以压缩感知理论和电磁斗篷技术这两个当代科技的最新成果为例，说明基础研究成果如何启发科技创新的思路。葛院士还与同学们介绍分享了他在与陈省身、杨振宁等前辈学术大师学习交往中受到的教益，谈了中国古代&ldquo;讲信修睦&rdquo;的传统思想对当今学风建设的启示。报告结束后，葛院士与同学们进行了积极互动，即席回答了关于学习和研究方面的疑问。在两个小时的报告中，葛院士广博的学识和幽默的语言引发了同学们的阵阵掌声。本次讲座不仅帮助听众了解了物理学原理的普遍性，也为人文社科的老师和同学带来了新的启迪，对于进一步推动文理学科的交叉、交融和渗透起到了良好作用。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告会前，冯惠玲副校长会见了葛墨林院士，双方就人民大学理工科建设等诸多问题进行了深入交谈。葛院士表示，人大近几年来在理工科方面发展迅速，成绩有目共睹。冯惠玲副校长对近年来科学界同仁对人大理工科建设的支持表示了感谢，并希望葛院士今后多到人大访问交流。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 校长助理、理工建设处处长王孝群教授和科研处谷曙光副处长参加了会见。学术讲座由王孝群教授主持，物理系系主任朱传界教授及多位教师参加。此次讲座也是物理学系第三十期名家讲坛。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c120620/zlhfzkl2zzy2nyf-k2kzn.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>附葛墨林院士简介：</strong></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 葛墨林，理论物理学家，中国科学院院士，中国科学院物理所学术委员会副主任。教育部科技委副主任，战略委员会委员；南开大学数学所副所长；北京理工大学物理学院院长。早期从事基本粒子理论、广义相对论研究，后来长期集中于数学物理、电动力学及量子力学的基础理论研究。近年来，转入物理与数学的基础理论研究及在国防科学技术中的应用，促进新的物理研究成果向科学技术应用的转化。迄今，发表了论文160余篇，编辑外文书刊七部，出版国内著作三部。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href="http://news1.ruc.edu.cn/102376/104690/">中国人民大学75周年校庆系列学术讲座专题</a></p>
<p>（编辑&nbsp; 燕燕）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120620/zlhfzkl2zzy2nyf-k2kzn_lit.jpg{/dede:field}
