{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“大规模侵权法律对策国际研讨会”隆重举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-04-12 03:50:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月9日下午&mdash;10日，&ldquo;大规模侵权法律对策国际研讨会&rdquo;在法学院明法601会议室隆重召开。本次会议由中国人民大学法学院、中国法学会民法学研究会、中国人民大学民商事法律科学研究中心及耶鲁大学中国法律研究中心共同主办，由来自美国耶鲁大学、斯坦福大学、杜克大学等世界知名学府的外国专家，来自中国人民大学、复旦大学、中南财经政法大学、清华大学、浙江大学等国内著名高校及科研单位的学者，以及来自全国人大法工委、最高人民法院、国务院法制办等实务部门的专家共三十余人参加会议。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbhkkzf-zyhny.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会开始前，中国人民大学副校长王利明教授、法学院院长韩大元教授会见了耶鲁大学中国法律研究中心主任葛维宝教授（Paul Gewirtz）及同行外方专家。法学院民商法教研室杨立新教授、姚辉教授、张新宝教授及朱岩副教授参加了会见。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbbylf2f-2ynbl.jpg" /></p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbbym2bf-l2mnf.jpg" /></p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbbkhbkf-hmlzb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月9日下午14时，研讨会正式开始。王利明教授、韩大元教授及葛维宝教授（Paul Gewirtz）分别代表中外双方致辞。双方回顾了中美法学教育与学术交流的发展历程，高度评价了法学院与耶鲁大学中国法律研究中心长期合作取得的丰硕成果，并对本次研讨会主题研讨的意义给予了充分肯定。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议研讨阶段，法学院朱岩副教授首先简要介绍了近几年国内发生的典型大规模侵权案件，包括三鹿奶粉事件、齐二药案、重庆开县中石油气井井喷案、大连油气管道爆炸案、银广夏案等，并总结了目前我国调整相关问题的法制资源。来自全国人大法工委、最高人民法院及国务院法制办的专家分别介绍了应对大规模侵权赔偿的立法、司法及行政实践。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbbnmllf-bkzfl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 美国斯坦福大学法学院的Deborah R.Hensler教授与长期在世界各国从事大规模侵权赔偿实务及管理的Norbert Wuehler博士分别作主题报告，介绍了美国及其相关国际组织在处理如911案件、BP公司石油泄露案等大规模侵权赔偿案件的经验。杜克大学法学院的Francis E. McGovern教授就&ldquo;大规模侵权的索赔评估和解决方案设计&rdquo;作主题报告，详尽介绍了确定赔偿数额的考量因素、假设模型及数理分析方法等问题，为我国处理大规模侵权案件提供了宝贵的操作经验。浙江大学光华法学院副院长王冠玺教授介绍了我国台湾地区大规模侵权的现状与司法对策。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbyfmbhf-ynn2k.jpg" /></p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbylfhnf-kynnz.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 国内学者也纷纷就我国大陆大规模侵权法律对策的理论及实践问题发表主题报告，包括大规模侵权的本质属性、典型特征、制度功能等理论问题，也包括预防机制、救济方式及应对模式等实践问题，特别是张新宝教授提出了设立大规模侵权损害救济(赔偿)基金的制度构想及运作方式设计。既讨论了《侵权责任法》等实体法依据的理解，也涉及了集团诉讼、代表人诉讼等相关程序问题的完善。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2fbyhkm2f-nbhfl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，由中国人民大学民商事法律科学研究中心主任杨立新教授与耶鲁大学中国法律研究中心研究员魏天熙（Timothy Webster）先生代表中外双方就研讨成果作总结发言。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在一天半的会议中，会场讨论热烈，中外专家相互交流切磋，就当前大规模侵权事件频发的背景下，如何妥善处理赔偿纠纷、保障受害人权益及维护社会稳定等问题达成了丰硕的成果与广泛的共识。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议结束后，韩大元院长代表法学院主持欢送晚宴，就中外学者继续加强交流与合作提出了希望。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fbhkkzf-zyhny_lit.jpg{/dede:field}
