{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长率团参访台湾“中央研究院”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}人民大学赴台代表团{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应台湾&ldquo;中央研究院&rdquo;副院长王汎森院士等人的邀请，纪宝成校长于11月8日上午率中国人民大学代表团访问了台湾&ldquo;中央研究院&rdquo;及其下属的历史语言研究所。就双方之间建立学术联系，开展人文社会科学研究方面的合作与交流进行了洽谈协商，形成积极的共识。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c101126/z2mfkyfhkknkbmf-zz2hlh.jpg" /></p>
<p>&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 台湾&ldquo;中央研究院&rdquo;副院长王汎森院士在该院会议室迎候纪宝成校长一行的到访。他对纪校长的访问表示由衷的欢迎，并向纪校长具体介绍了台湾&ldquo;中央研究院&rdquo;的历史与现状，他指出，中国人民大学是大陆地区一所人文社会科学师资雄厚、研究成果丰硕、在海内外享有很高声誉的重点高校，台湾&ldquo;中央研究院&rdquo;及其相关研究所有意愿与中国人民大学及其相关院系开展多层次全方位的交流与合作。他强调，在此之前，双方学者个人、院所之间早已有了一定的联系与交流，如今纪校长的来访，则具有双方之间启动全面合作的标志性意义，必将产生深远的影响。&nbsp;</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c101126/z2mfkyfhknbmf-z22fzb.jpg" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长对王汎森副院长的接待和介绍表示感谢。他向王汎森副院长扼要介绍了中国人民大学的基本情况和在学科建设、学术研究方面所取得的成就。纪校长说，人民大学从战略的高度，重视与海内外著名高等院校、科研机构之间的合作与交流，台湾&ldquo;中央研究院&rdquo;历史悠久、学科完整、成绩卓著、影响广泛，是一家值得信赖与合作的重要科研机构。纪宝成校长表示，非常欣喜地看到双方之间学者已有了形式多样、内容丰富的学术交流，并希望以这次中国人民大学代表团的访问为契机，使双方之间的合作制度化、规范化，具有可持续性和可操作性，在当前，尤其要推动人民大学人文学科相关院系与台湾&ldquo;中央研究院&rdquo;下属的史语所、文哲所之间开展人员互访、课题研究、信息分享、资料交换以及联合举办学术会议等方面的合作事宜。王汎森副院长赞同纪宝成校长的意见，表示将责成该院相关部门就双方所达成的基本共识进行具体的细化论证，为彼此间系统深入的交流与合作创造条件。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈结束后，纪宝成校长向王汎森副院长赠送了由他主编的《中国古代治国要论》、《国学学刊》等书刊，王汎森副院长高兴地接受了这些礼品，并向纪宝成校长以及代表团各位成员回赠礼物。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhknknzmf-zlyb2f.jpg" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，纪宝成校长及学校代表团一行应邀参观了设立在台湾&ldquo;中央研究院&rdquo;院内的胡适纪念馆、胡适故居、历史语言研究所及其历史文物陈列馆。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 台湾&ldquo;中央研究院&rdquo;建立于1928年，蔡元培、朱家骅、胡适、王世杰、钱思亮、吴大猷、李远哲等著名学者先后担任该院院长，现任院长为化学家翁启惠院士。它下辖30余个研究所，有专职与兼任研究人员8000余人，是目前台湾地区最高科研机构，在自然科学、人文社会科学的研究领域均有相当突出的建树。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学访台代表团其他成员随同纪宝成校长一起参访了台湾&ldquo;中央研究院&rdquo;。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>相关链接：</strong></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="javascript:void(0);/*1289463608437*/">[海峡两岸校长论坛系列报道]论坛将登场 欢迎晚宴为纪宝成校长庆生</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71672.html">纪校长率团赴台参加第三届海峡两岸大学校长论坛并作主题发言</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71728.html">纪宝成校长拜会吴伯雄先生、刘兆玄先生</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71725.html">纪宝成校长接受台湾媒体采访</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71729.html">人民大学与台湾清华大学签订校际协议</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71803.html">中国国民党荣誉主席连战会见纪宝成校长</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://news1.ruc.edu.cn/102392/71835.html">台湾新党主席郁慕明宴请纪宝成校长一行</a></p>
<p>　　<a href="http://news1.ruc.edu.cn/102392/71852.html">中国人民大学台湾校友会热烈欢迎纪校长访台<br />
</a><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='pubdate'}1289418250{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhkknkbmf-zz2hlh_lit.jpg{/dede:field}
