{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国财政部副部长助理博纳与经济学院学者讨论宏观经济问题{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-04 05:01:09{/dede:field}
{dede:field name='body'}<p>　　3月3日上午，在美国驻华使馆的安排下，美国财政部分管亚洲事务的副部长助理罗伯特&bull;博纳先生访问人民大学经济学院，就当前宏观经济和中美经贸关系等问题与经济学院学者进行研讨。经济学院副院长、经济研究所副所长刘元春教授，经济学院陶然教授等会见了博纳先生一行。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzkkl2zzkf-zzyby.jpg" alt="" /></p>
<p><br />
　　关于中国宏观经济，博纳先生提出了两个问题：一是当前中国宏观经济所面临的挑战有哪些？特别是通货膨胀的问题。二是在世界经济格局调整以及寻求再平衡的过程中，中国如何定位及应对？刘元春副院长就这两个问题就给予了细致而深刻的解答。他深入剖析了中国通胀现象的深层次成因以及可能导致的影响，并与博纳先生共同探讨了中国宏观经济面临的其他挑战，如经济结构调整与转型、泡沫经济、投资机制等。就第二个问题，刘元春教授着重强调了中国在解决经济外部不均衡的努力中，扩大国内需求，尤其是消费需求的重要性，并就中美两国学者对此问题的研究进行了对比。博纳先生表示基本同意刘元春教授的观点，尤其表示中国经济调整与改革是一个长期的、循序渐进的过程，不应一蹴而就。之后，博纳先生介绍了美国国内的宏观经济状况，对当前美国经济增长动力不足表示担忧，并指出就业问题是美国政府及民众最关心的问题。 <br />
　　会见中，刘元春副院长还向博纳先生介绍了经济学院主办的&ldquo;中国宏观经济论坛&rdquo;的相关情况，并向其赠送了2010年及2011年第一季度的《中国宏观经济分析与预测报告》。博纳先生表示会认真阅读，并希望自己及美国财政部的同事以后能更多地到经济学院访问。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzkklyknkf-2m2zb.jpg" width="500" height="333" alt="" /></p>
<p><br />
　　博纳先生从媒体和美国驻华使馆等处了解到人民大学经济学院举办&ldquo;中国宏观经济论坛&rdquo;并发布宏观经济分析与预测报告的情况，认为人大经济学院是中国最具实力的政府智库之一，专程到人民大学与经济学院学者讨论中国宏观经济问题，深觉获益匪浅，并表示要经常来我校开展研讨。</p>
<p>（编辑：王宝奎；核稿：丁凯）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzkkl2zzkf-zzyby_lit.jpg{/dede:field}
