{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}黄达—蒙代尔讲座：我国税收征管改革、创新的探讨{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/姚泽宇 图/刘腾{/dede:field}
{dede:field name='pubdate'}2010-06-03 09:00:36{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月1日晚，国家税务总局征管和科技发展司司长、国家税务总局信息化领导小组办公室主任李林军在明德主楼830黄达&mdash;蒙代尔讲堂以&ldquo;我国税收征管改革、创新的探讨&rdquo;为主题发表了精彩演讲。出席本次讲座的领导和嘉宾有：北京市地税局副局长郝硕博、国家税务总局征管和科技发展司处长李伟、国家税务总局征管和科技发展司韩启蕾博士；财政金融学院院长郭庆旺、院学术委员会主任朱青、财政系教授谭荣华等。讲座由财政金融学院副院长岳树民主持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李司长首先从对我国税务征管的现状着手，通过与美国等发达国家的对比，具体分析了我国当前税收征管存在的评估与稽查制度不够完善等突出问题。在十二五规划中，税收征管改革已被提上议程。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李司长指出，为完善我国税收征管制度，借鉴国际税收征管的先进理念和经验是必须的，但前提是改革创新得立足在中国实际的基础之上。征管和科技发展司在接下来对税收征管改革和创新的工作中，将以信息化为支撑，实行税收风险管理来完成纳税遵从的根本任务和目标。把有限的资源合理分配到风险大的纳税者和领域，并且对不同风险等级的纳税者和领域采取不同的应对策略。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 岳树民副院长在总结中指出，我国税收征管改革、创新的探讨立足于征管理念、税源专业化管理模式、征管手段、征管法律制度的创新，定能让我们的税收环境更美好，让纳税人的合法权益得到保护。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：徐晶晶）&nbsp;</p>
<p><br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
