<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院毕业生林静晋级美国国际声乐大赛决赛 为首位入选亚洲人",89,186);
$z[2][4]['name']="title";
$z[3]=Array("field","",188,227);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",229,282);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-24 02:34:56",284,343);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艺术学院音乐系02级优秀毕业生林静在2011年3月纽约举办的&ldquo;2011 Lotte Lenya Competition&rdquo;国际声乐大赛中获得佳绩，成功晋级四月份在美国伊斯曼音乐学院举行的总决赛。该大赛要求参赛者同时驾驭演唱歌剧和音乐剧两方面的专业技能，因对选手严苛的要求而享誉国际声乐界。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林静是第一位进入该国际大赛的亚洲人，其获奖新闻分别被美国的多家报纸和网络媒体报道，为艺术学院争得了荣誉。</p>\r\n<p align=\"center\"><img height=\"333\" alt=\"\" width=\"500\" src=\"/uploads/allimg/c110725/zlzzbyzhynbbbzf-ll2hh.jpg\" /></p>\r\n<p align=\"left\">（编辑：刘德萍）</p>",345,1006);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhynbbbzf-ll2hh_lit.jpg",1008,1100);
$z[7][4]['name']="litpic";

?>