{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院毕业生林静晋级美国国际声乐大赛决赛 为首位入选亚洲人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-03-24 02:34:56{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 艺术学院音乐系02级优秀毕业生林静在2011年3月纽约举办的&ldquo;2011 Lotte Lenya Competition&rdquo;国际声乐大赛中获得佳绩，成功晋级四月份在美国伊斯曼音乐学院举行的总决赛。该大赛要求参赛者同时驾驭演唱歌剧和音乐剧两方面的专业技能，因对选手严苛的要求而享誉国际声乐界。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林静是第一位进入该国际大赛的亚洲人，其获奖新闻分别被美国的多家报纸和网络媒体报道，为艺术学院争得了荣誉。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110725/zlzzbyzhynbbbzf-ll2hh.jpg" /></p>
<p align="left">（编辑：刘德萍）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhynbbbzf-ll2hh_lit.jpg{/dede:field}
