{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}西班牙拉斯帕尔马斯大学代表团访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际交流处{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月9日下午，杨慧林副校长会见了来访的西班牙拉斯帕尔马斯大学校长何塞&bull;雷西多&bull;加西亚（Jose Regidor Garcia）、副校长Rosario Berriel Martinez女士一行等8人。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfhkhly2lf-zy2ln.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨慧林副校长愉快地回忆了今年4月在西班牙参加中西大学校长论坛的情况，向来宾介绍了人民大学的学科特色、共建的孔子学院概况及国际小学期项目，希望以此次来访为契机，寻求两校合作的可能性。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfhkhk2fyf-22hmm.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 何塞&bull;雷西多校长向杨慧林副校长介绍了拉斯帕尔马斯大学的国际交往、学科特色等情况，重点说明了该校连接非洲、欧洲和拉丁美洲的地理优势及在语言文学领域的专业设置，希望从增进语言文学领域的相互了解出发，推动两校合作。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfhkhkkkhf-lynhh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 文学院副院长耿幼壮及国际交流处副处长程鑫会谈时在座。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1289352366{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhkhly2lf-zy2ln_lit.jpg{/dede:field}
