{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}教育部社会科学委员会哲学学部2010年度工作会议召开  研讨哲学界未来发展战略{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院 臧峰宇{/dede:field}
{dede:field name='pubdate'}2010-11-15 09:51:52{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为了从战略高度规划和推动哲学学科的研究，确定哲学研究的重大领域和重点选题，11月1日，教育部社会科学委员会哲学（含宗教学、逻辑学）学部2010年度工作会议暨学科战略研讨会在武汉召开。武汉大学校长顾海良教授、教育部社科司张东刚副司长到会致辞。哲学学部召集人之一陶德麟教授讲话。来自中国社会科学院、中共中央党校、中央编译局、中国人民大学、北京大学、清华大学、北京师范大学、复旦大学、吉林大学、中山大学、南京大学、南开大学、武汉大学等单位的60余位专家学者与会。 <br />
</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnfmkzk22f-zkfby.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 哲学学部秘书长、中国人民大学郭湛教授介绍了哲学学部一年来的工作和本次会议的主旨。按照教育部社科司的要求，开展高校哲学未来五至十年战略规划的研究，应聚焦中国社会发展的现实需要，凝练学术研究方向，提出有重大意义的当代课题，推动哲学社会科学的繁荣与发展。孙正聿、李景源、鞠实儿、王东、李维武、何锡蓉、朱志方、干春松、周北海、李德顺、丰子义、鲁克俭、汪信砚、何萍、阎孟伟、刘晓力、张风雷、欧阳谦、葛晨虹、陈慕泽、牛宏宝、孙伟平等与会专家学者，就哲学的问题意识、学科特点、现实关注等方面展开广泛深入的研讨。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与会学者们认为，哲学研究应增强问题意识，哲学家面对的问题是现实的，回答的方式是理论的，哲学研究应进一步促进理论与实践相结合。制定哲学发展的战略规划，既要关注重大的社会现实问题，也要考虑哲学自身的特点。当代哲学研究要谋求创新，哲学研究者既要有宽广的国际视野，又要&ldquo;让哲学讲中国话&rdquo;，推动各研究领域与多种研究方式的对话，为当代中国社会发展提供思想、理论和观念的支撑。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 教育部社会科学委员会哲学（含宗教学、逻辑学）学部召集人为中国人民大学陈先达教授和武汉大学陶德麟教授，学部秘书处秘书长为中国人民大学郭湛教授，副秘书长为武汉大学汪信砚教授和中国人民大学郝立新教授。哲学学部秘书处办公室设在中国人民大学哲学院，张文喜教授为办公室主任。 <br />
</p>
<p>（编辑&nbsp; 燕燕）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnfmkzk22f-zkfby_lit.jpg{/dede:field}
