{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院承办环保部污染防治司“区域和城市清洁空气研究项目”启动会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/图 环境学院{/dede:field}
{dede:field name='pubdate'}2010-05-21 04:13:07{/dede:field}
{dede:field name='body'}<p>　　由环保部污染防治司主办、人民大学环境学院承办、能源基金会协办的&ldquo;区域和城市清洁空气研究项目启动会&rdquo;于5月20日上午在北京新世纪日航饭店三层世纪1厅举行。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnfyzllybf-nbflb.jpg" alt="" /></p>
<p>　　该项目由环保部污染防治司主持，能源基金会支持，中国人民大学环境学院、环保部环境规划研究院、中国环境科学研究院、清华大学等联合执行，为进一步推动区域和城市空气质量改善，保护公众身体健康提供科研支持。环境学院马中教授、吴健副教授、庞军博士、石磊博士、杨鹂博士等为项目主要研究人员。</p>
<p>　　会议期间，环境学院石磊博士、庞军博士分别就《清洁空气政策综合研究》和《城市天然气利用的政策研究》两个主题发表了演讲，阐述了相关研究背景、内容和研究计划。在最后的座谈环节，马中教授就项目整体研究方案提出了建议。</p>
<p></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfyzllybf-nbflb_lit.jpg{/dede:field}
