<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","外国语学院学生暑期社会志愿服务收获社会好评",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院 王梦霞",212,268);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-09-26 02:36:29",270,329);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 暑假期间，中国人民大学外国语学院09级英语系的彭廉坡同学参与了 &ldquo;送信息下乡&rdquo;社会实践活动。彭廉坡同学不畏酷暑高温、路途颠簸、生活不便等艰苦条件，来到资阳农村地区进行志愿服务工作，积极的态度受到了主办方中国电信资阳分公司的来信感谢。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国电信资阳分公司在信中高度赞扬了彭廉坡作为人民大学学生，在暑假中近一个月时间的实践活动，称赞他的思想素质、情感魅力、实干技能和吃苦耐劳、服务奉献的精神，并对中国人民大学对其推进农村信息化工作的大力支持表示诚挚的感谢。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n</p>",331,983);
$z[6][4]['name']="body";
$z[7]=Array("field","",985,1024);
$z[7][4]['name']="litpic";

?>