{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院法律硕士校友会启动为院庆献礼书法活动和校友捐赠活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-24 02:49:13{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月19日晚，由法学院法律硕士校友会组织的校友联写&ldquo;法&rdquo;字为法学院60周年院庆献礼活动启动，校友代表宋鱼水、庄伟、陈岳琴、吴革等相聚明德法学楼校友会馆，共同学写书法，法学院党委副书记郑小敏出席活动。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 按照法律硕士校友会的计划，今年院庆期间，将由60位法律硕士校友现场书写60个不同字体的&ldquo;法&rdquo;字，并制作成长卷赠送给学院，作为对法学院成立60周年的献礼。法律硕士校友会邀请中国人民大学徐悲鸿艺术学院常务副院长郑晓华教授辅导校友学写书法，校友们从本周开始将陆续到校友会馆学习书法。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为响应法学院校友会发出的&ldquo;人大法律人，人大法律情&rdquo;&mdash;&mdash;法学院60周年院庆校友捐赠倡议，法律硕士校友代表在活动现场进行了捐赠，院庆办公室路磊接受了法律硕士校友代表的首批捐赠。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
