{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“第三届徐悲鸿杯国际青少年儿童美术比赛获奖作品颁奖仪式暨画展”在人民大学开幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-12-29 11:50:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由香港青年协会、香港金声艺术协会、徐悲鸿艺术委员会、中国人民大学徐悲鸿艺术研究院联合主办的&ldquo;第三届徐悲鸿杯国际青少年儿童美术比赛获奖作品颁奖仪式暨画展&rdquo;于12月23日下午2：30在中国人民大学展览中心开幕。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhk2fll2f-zhk2f2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;香港徐悲鸿杯国际青少年儿童美术大赛&rdquo; 由香港青年协会、香港金声艺术协会、徐悲鸿艺术委员会、中国人民大学徐悲鸿艺术研究院联合举办，每两年举办一届，是面向港澳台及国际华人社区中小学美术教育界重要赛事，在世界各地华人社区中小学广泛征集优秀的青少年儿童美术作品。举办这一活动的目的，在宏扬徐悲鸿先生爱国主义精神，联络海内外美术教育同仁，推广青少年儿童美术教育事业，传承中华民族文化，普及艺术审美教育。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次大赛获得了世界各地空前的反响和支持，比赛分在三个赛区进行颁奖和展览，分别是国内赛区和香港赛区及北美赛区。香港赛区在香港青年协会的领导下，于9月3日至5日在香港中央图书馆展览会举行了盛大的颁奖仪式和展览，参赛人数二万多人，非常踊跃。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhk2kfkkf-zbb2lk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次来北京参加颁奖典礼暨画展开幕式的有来自国内和海外各分赛区的老师和学生。大家对徐悲鸿大师高尚的爱国主义情怀和精湛的艺术造诣都抱有高山仰止之情，通过大赛互相观摩和学习。在京期间，中国人民大学徐悲鸿艺术研究院将为海内外师生代表安排知名艺术家讲座，增进他们对中国传统艺术的了解。获奖学生还将受邀进入中国人民大学艺术学院专业教学课堂观摩，体验艺术学院大学生学习和生活。通过系列活动，增加海内外学生对中国文化的认同，增进对祖国文化的情感。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhk2nfzhf-zyhylf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经过两年时间的精心策划和准备，本届参赛作品超过六万幅，创历届参赛记录。这次晋京展出的450幅获奖作品，都经过反复评比而选出。反映了国内、香港地区和海外华人社区中小学美术教学的水平。徐悲鸿纪念馆馆长廖静文先生观看参赛作品时说：&ldquo;玲琅满目，美不胜收&rdquo;。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110725/zlzzbyzhkl2zkyf-zkbbhf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 出席本次颁奖典礼的嘉宾有：徐悲鸿纪念馆馆长廖静文、香港青年协会总干事王易鸣、中国人民大学常务副校长袁卫、副校长薛浣白、徐悲鸿艺术委员会理事长、中国人民大学徐悲鸿艺术研究院院长徐庆平、中国红十字基金会党委书记王志、中国儿童少年基金会秘书长宋丽英、中共中央党校理论网主编谭荣邦、中共中央党校马克思主义基金会主任李满龙、香港金声艺术协会副会长林惠强、中国人民大学艺术学院党委书记兼副院长郑晓华、常务副院长徐唯辛、党委副书记别敏。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhk2fll2f-zhk2f2_lit.jpg{/dede:field}
