{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院成立公共治理与和谐城市研究中心{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-01-14 09:46:10{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为加强政府管理和公共政策研究，推动公共管理学科建设，学校经研究，决定在公共管理学院成立中国人民大学公共治理与和谐城市研究中心。公共管理学院副院长蓝志勇教授任中心主任。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学公共治理与和谐城市研究中心将以发展公共管理学科为使命，从政府管理和公共政策的视角，跟踪国际公共管理学术前沿、深入进行中国改革与发展的理论和实践问题的调研和学术探讨，审视中国进一步改革发展的重大理论和实践问题，引领学术讨论，为政府创新、城市治理、公共政策的有效制定和实施、中国社会的全面可持续性和谐发展，提供理论探讨和实践经验总结的学术平台。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 蓝志勇教授是千人计划的国家特聘专家。他于1991年获得美国雪城大学麦克斯威尔公共管理学院公共管理博士，美国亚利桑那大学公共管理学院终身职教授，从事美国公共管理改革与实践的教学和研究近二十年，是美国公共管理学界的知名学者，世界银行、联合国亚洲中心、世界经合组织、港台新加坡高校的聘请专家和美国、中国数个城市的顾问，国内外多种杂志的主编和编委。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
