<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院《中国宏观经济分析与预测》被确立为2009年度国家社会科学基金决策咨询项目",89,205);
$z[2][4]['name']="title";
$z[3]=Array("field","",207,246);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",248,295);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，经济学院举办的&ldquo;中国宏观经济论坛&rdquo;的研究成果《中国宏观经济分析与预测》经全国哲学社会科学规划领导小组批准，被确立为2009年度国家社会科学基金决策咨询项目。教育部对该成果也十分重视，要求将研究成果同时上报给教育部社科司。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",297,653);
$z[5][4]['name']="body";
$z[6]=Array("field","1264359018",655,705);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",707,746);
$z[7][4]['name']="litpic";

?>