{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}马来西亚南方学院代表团访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/国际交流处 图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-04-18 09:47:52{/dede:field}
{dede:field name='body'}<p>　　4月14日下午，杨慧林副校长会见了来访的马来西亚南方学院代表团。代表团由该校董事长张文强拿督率领，成员包括该院院长祝家华博士以及校董事会及理事会成员一行共12人。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbnmky2kf-lbbnf.jpg" /></p>
<p>　　杨慧林副校长首先欢迎代表团的到来，接着，简要介绍了人民大学的学科特色和国际化发展情况，重点介绍了中国人民大学的国际小学期项目。杨慧林副校长表示，希望通过南方学院此次来访能促成两校进一步开展实质合作，人民大学也愿意为该校品学兼优的优秀学生提供来人大就读的奖学金或其它形式的资助。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbmfzhnyf-hzkbl.jpg" /></p>
<p>　　张文强拿督对杨慧林副校长的欢迎表示感谢。张文强拿督简要介绍了南方学院的基本情况，并对中国人民大学给予的帮助表示感谢，希望可以借助此次访问增进南方学院与人民大学的关系，也希望人民大学在南方学院的发展过程中给予更多的支持。</p>
<p>　　教务处、国际交流处、哲学院的相关负责人及老师陪同会见。</p>
<p>　　南方学院是马来西亚教育部于1990年批准创办的唯一一所华人非盈利大专院校，由华人慈善家、企业家及热心人士捐资成立，1998年与中国人民大学签署合作协议。该校在过去21年的发展中得到了包括中国人民大学在内的多所国内高校的帮助。</p>
<p>　　(编辑：席嘉怡)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbnmky2kf-lbbnf_lit.jpg{/dede:field}
