{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学法学院与北京大学法学院签署合作协议 举行联谊交流活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-16 10:56:45{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月13日，中国人民大学法学院与北京大学法学院教师联谊交流活动在人民大学举行。北京大学法学院院长张守文教授，副院长汪建成教授、沈岿教授、王锡锌教授，党委副书记杨晓雷，湛中乐教授、谷凌副教授以及办公室、图书馆教师代表出席活动；法学院院长韩大元教授，党委书记兼副院长林嘉教授，副院长刘明祥教授、王轶教授，党委副书记肖中华教授、郑小敏老师，教师代表何家弘教授、周珂教授、李学军教授，院长助理、图书馆常务馆长郭禾教授，院长助理杨东副教授、邵明副教授，姚海放讲师等出席活动，双方部分教师和行政、教务以及图书馆工作人员参加了活动。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fmnlzmyf-hyffb.jpg" /></p>
<p align="left">　　双方在明德法学楼601国际学术报告厅举行了本科生培养工作交流会并签署了合作协议。会议由法学院副院长王轶教授主持。 <br />
<br />
　　张守文院长首先致辞。他对法学院的热情接待表示感谢，并希望两院在未来可以进一步加强在教学、科研、管理等方面的交流合作，促进双发的共同进步，推动中国法学的繁荣发展。</p>
<p align="left">　　韩大元院长在致辞中回顾了双方悠久的合作历史和友谊，并对北大法学院长期以来对法学院的支持表示感谢。他说，此次合作协议的签署是对两院几十年友谊的总结，有利于进一步加强两院的合作与交流，建立共同发展、相互尊重的新机制，共同努力促进中国法学教育的进步与发展，推动中国法学教育走向世界。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fmmfhh2f-bbmnk.jpg" /></p>
<p align="left">　　随后，韩大元院长与张守文院长一同签署了合作协议。他们表示将尽快启动这一新的合作机制，实现双方的优势互补。按照合作协议，双方将在教学资源交流方面进行建设性的合作，双方开展法学本科和法学硕士研究生的教学资源交流，并在进行交流的课程范围内实行学分互认。同时双方还将开展教师互派、图书馆资源共享等方面的合作。</p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110419/zlflzn2fmmfmkyf-ynhbb.jpg" /></p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fmmzhn2f-khlkk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fmm2h2yf-nn2kz.jpg" /></p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在座谈会上，双方教师围绕本科生培养模式，培养经验和发展思路，教师团队建设和奖励机制，教学管理、思想政治工作四个议题展开了热烈的讨论，并着重探讨了两院在推免制度、课程设置中遇到的问题。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院党委书记兼副院长林嘉教授为会议做总结发言。她表示，双方在共同利用教学资源、共同提升教学质量方面具有广阔的合作空间，希望今后能进一步加强合作，实现共同发展。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fmmlnlzf-m2kfz.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 举行座谈会前，双方教师代表在我校世纪馆举行了羽毛球友谊赛。比赛分为男单、女单、男双、女双和混双五场进行。双方势均力敌，经过几轮激战，法学院取得了女双、男双、混双的胜利，北大法学院取得了男单、女单的胜利。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110419/zlflzn2fmmyzkf-zfy2z2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中午，韩大元院长、林嘉书记陪同北大法学院张守文院长一行参观了我院院史展览、校友会馆、图书馆、教授工作室、行政办公室及明德法学楼教师休息室等。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院办公室主任兼团委书记乔鹏，办公室副主任、教务科科长郝晓明，办公室副主任、综合科科长洪荞老师，图书馆副馆长李岸曰，办公室副主任路磊，团委常务副书记邢姝，办公室韩松、程志红，民商事法律科学研究中心卢淑贞等老师参加了有关活动。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次联谊交流活动进一步密切了北大法学院和人大法学院的联系，增进了友谊，双方在学科建设、人才培养和教学科研等方面达成了共识，为今后的共同发展打下良好基础。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fmnlzmyf-hyffb_lit.jpg{/dede:field}
