<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","哲学院举办“以文启智”首场讲座",89,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",200,245);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-04-02 03:08:31",247,306);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　毕业季将近，为提高哲学院硕士、博士研究生的学术素养及论文写作水平，尤其是提高毕业论文的质量，哲学院研究生会急学生所需，特承办&ldquo;以文启智&rdquo;主题讲座。3月31日下午，哲学院&ldquo;以文启智&rdquo;系列讲座首场&mdash;&mdash;&ldquo;大哲学类学生毕业论文开题释疑&rdquo;在教三3301教室开讲。</p>\r\n<p>　　首场讲座特邀哲学院马克思主义哲学专业博士生导师郭湛教授，郭教授结合自己治学的经历现身说法，并为到场的同学赠送核心学术刊物。整场讲座围绕&ldquo;如何进行学术研究和论文写作&rdquo;这一同学们普遍关心的话题展开，主要分为三个部分&mdash;&mdash;&ldquo;学术问题的深入研究&rdquo;、&ldquo;学术写作：研究成果的表述&rdquo;以及&ldquo;学术论文的写作步骤&rdquo;。讲座期间，郭湛教授以生动的实例把理论内容具体化。他讲到，想要把论文的写作当作艺术创作，既需要对学术的澎湃激情，又需要严谨细致的态度，这样的学术才是有生命力的真学术。在场的同学都感到受益匪浅，深感学术研究不仅是论文的写作，更是学者将学术当作生命的彰显过程。&nbsp;</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c100622/z2kkzlnhbm2bzmf-2mzfl.jpg\" /></p>\r\n<p>　　整场讲座氛围轻松愉快，师生互动讨论热烈，讲座收效明显，受到了全院师生的一致好评。</p>\r\n<p></p>",308,1454);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100622/z2kkzlnhbm2bzmf-2mzfl_lit.jpg",1456,1548);
$z[7][4]['name']="litpic";

?>