{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学深圳研究院成功举办深圳市重点民营企业家卓越研修班{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}深圳研究院{/dede:field}
{dede:field name='body'}<p>　　11月5日晚上，深圳市重点民营企业家卓越研修班（第二期）开班仪式在北京湘鄂情大酒店隆重举行。中国人民大学常务副校长袁卫，中国人民大学教育基金会秘书长彭和平，深圳研究院常务副院长陈健等领导以及参加此次研修班的全体师生共约70人出席了开办仪式。开班仪式由学员代表王李中馨女士主持。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhk2ky2hf-zbkhnh.jpg" /></p>
<p>　　袁卫常务副校长首先代表学校对全体学员返回母校学习表示热烈的欢迎，接着他简要向学员们介绍了学校的历史背景，学科特色，学校近几年来的发展情况以及未来的发展方向，并表示学校将在本世纪新的腾飞的十年中，努力将人民大学建设成为人民满意、世界一流的大学。最后他对学员们的北京之行表达了衷心的祝福。彭和平秘书长向各位学员们介绍了校友会的发展情况，并希望全体学员以后能加强沟通与联谊，促进校友与校友间、校友与母校间、母校与社会间的交流与互动。随后，学员代表刘丹宁女士交流了自己返回母校学习的意义和感受，她代表全体学员向母校表示，一定要学有所成，努力塑造社会责任型企业。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhklzybf-zy2zky.jpg" /></p>
<p>　　开班仪式上，学员们还向母校捐赠了&ldquo;实事求是&rdquo;的书法作品以及若干份纪念礼物，大家纷纷表示，一定要牢记母校校训，管理好自己的企业，为社会，为母校的发展做出新的更大的贡献。 </p>
<p>　　此次研修班由深圳市中小企业服务中心主办，中国人民大学深圳研究院承办，之前已经成功举办一期。来自深圳市民营领军骨干企业，已上市公司的董事长总经理共计60人将参加本次研修班的学习。在一年的学习期间里，学员们将分别被安排在北京、上海、香港、台湾和深圳进行每次3-7天的集中学习，并随课程内容走进当地知名企业、国内知名企业和学员企业，进行实地考察学习。 </p>
<p>　　（编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1289250632{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhk2ky2hf-zbkhnh_lit.jpg{/dede:field}
