{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语学院德语系主任赵蕾莲出席德国著名作家马丁瓦尔泽报告会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}施敏霞{/dede:field}
{dede:field name='pubdate'}2008-10-28 04:10:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月21日，德国国宝级著名作家马丁&bull;瓦尔泽（Martin Walser）在中国社会科学院做题为&ldquo;批判&bull;认同&bull;现时代精神&rdquo;的报告，中国人民大学外国语学院德语系主任赵蕾莲教授应邀出席。出席当天报告会的还有中国日尔曼学者、中国作家以及日耳曼学研究生，外国语学院德语系部分学生也有幸到现场聆听报告。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 瓦尔泽先生以具体事例为线索，生动具体地阐释了批判、认同和现时代精神三者在文学中的相互作用，整个报告深入浅出，其高超的演讲水平亦不时赢得阵阵掌声。报告结束后，瓦尔泽先生与在场的学者、作家及学生进行了热烈的自由交流。作为唯一一位没有踏上过中华大地的德国元老级作家，瓦尔泽对中国和古老的中国文化有着强烈的兴趣和好感，他也给予了此次座谈会高度的评价：&ldquo;我从来没有经历过这样一场讨论，能和这么多作家、青年学子坐在一起对文学进行讨论，这对我来说是一次难以言表的美好经历。&rdquo; <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，此次瓦尔泽先生应北京大学和歌德学院的联合邀请首次访华，社科院的报告会为其访华系列活动之一。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 现年81岁的瓦尔泽是当今德国最著名、最有文学成就和社会影响力的作家之一，在战后德国文学史上与海因里希&bull;伯尔和君特&bull;格拉斯的地位相当。中国读者对于马丁&bull;瓦尔泽的作品并不陌生：《爱情的彼岸》、《批评家之死》、《惊马奔逃》、《迸涌的流泉》、《菲利普斯堡的婚事》等等 。今年刚一出版便进入畅销书排行榜的小说《恋爱中的男人》正在翻译之中，译本有望在明年与国内读者见面。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
