<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","法学院王利明、曾宪义、高铭暄三位教授受聘“最高人民法院特邀咨询员”",89,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",236,281);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-02-23 04:00:48",283,342);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院近日召开第三届特邀咨询员会议，就法院工作和《最高人民法院工作报告》（征求意见稿）征求建议和意见。中国人民大学法学院王利明教授、曾宪义教授、高铭暄教授被聘任为最高人民法院第三届特邀咨询员。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院党组书记、院长王胜俊出席会议并讲话，并向第三届特邀咨询员40人颁发了聘任证书。&nbsp;</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />\r\n</p>",344,908);
$z[6][4]['name']="body";
$z[7]=Array("field","",910,949);
$z[7][4]['name']="litpic";

?>