{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院王利明、曾宪义、高铭暄三位教授受聘“最高人民法院特邀咨询员”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-02-23 04:00:48{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院近日召开第三届特邀咨询员会议，就法院工作和《最高人民法院工作报告》（征求意见稿）征求建议和意见。中国人民大学法学院王利明教授、曾宪义教授、高铭暄教授被聘任为最高人民法院第三届特邀咨询员。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院党组书记、院长王胜俊出席会议并讲话，并向第三届特邀咨询员40人颁发了聘任证书。&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
