{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}密歇根大学常务副教务长兰斯特孟茨教授来访{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际交流处{/dede:field}
{dede:field name='pubdate'}2011-04-18 10:38:27{/dede:field}
{dede:field name='body'}<p>　　4月16日，杨慧林副校长会见美国密歇根大学常务副教务长兰斯特&bull;孟茨（Lester Monts）教授一行，国际交流处副处长石佳友陪同会见。孟茨教授此次来访主要是商谈5月24日密歇根大学管乐团来人民大学演出的相关事宜。</p>
<p>　　会见中，孟茨教授介绍了密歇根大学管乐团此次巡演的一些进展以及细节安排，并回顾了两校在艺术方面的交流，表示密歇根大学将继续支持人民大学师生前往该校开展交流活动。杨慧林副校长向孟茨教授介绍了学校目前的接待安排，学校将多层次、多方位地利用此次活动加强双方师生的互动交流。</p>
<p>　　密歇根大学管乐团受中国国家汉语国际推广领导小组办公室邀请，将于2011年5月8日-5月26日来华巡演，巡演地点包括浙江大学、上海交通大学、上海大剧场、西安音乐厅、辽宁大学、国家大剧院、天津大剧院、中国人民大学。</p>
<p>　　（编辑：苏璇）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
