{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}杰赛普国际法模拟法庭辩论赛第八届中国赛区选拔赛在人民大学开幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-02 11:32:49{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 被誉为国际法学界&ldquo;奥林匹克竞赛&rdquo;的杰赛普国际法模拟法庭辩论赛第八届中国赛区选拔赛3月1日在中国人民大学开幕。来自中国、美国、加拿大、英国、澳大利亚、法国、新加坡等国的专家学者、法律界人士以及参赛学校的师生百余人参加了开幕式。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;杰赛普（Jessup）国际法模拟法庭辩论赛&rdquo;是由美国&ldquo;国际法学生联合会&rdquo;主办的专业性法律辩论赛。该辩论赛旨在为在全球范围内推动对国际公法的学习与研究，并通过模拟国际法院的审判方式来培养学生运用法律进行专业辩论的能力。比赛自1959年首次举办以来，至今已有50余年的历史，现在每年有100多个国家的900余所大学参赛，是目前国际上规模最大、历史最悠久的模拟法庭比赛。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自2003年由中国人民大学引进并举办第一届全国杰赛普（Jessup）国际法模拟法庭辩论赛以来，该项赛事的规模和影响力不断扩大。本届比赛共有包括中国人民大学、北京大学、南开大学等在内的34所国内高校的代表队报名参加，参赛人数总计200余人，是历年规模最大的一届。经过为期四天的比赛，将有四支队伍胜出并代表中国参加2010年3月底在美国华盛顿举行的国际决赛。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院副院长万鄂湘、中国人民大学校长纪宝成及加拿大、德国、巴基斯坦、美国驻华大使等人出席比赛开幕式并讲话。美国联邦法院法官O&rsquo;Scannlain先生等30余位来自美国、英国、法国等国家的著名国际法专家、学者应邀出席比赛开幕式并将担任此次模拟法庭比赛的法官。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 万鄂湘副院长说，杰塞普国际法模拟法庭比赛为提升中国国际法人才培养质量提供了一个重要的平台、也为中国培养国际化的国际法人才打开了一扇了解世界的窗户。同时，中国在法治建设方面取得的成就也应该为国际法的发展作出贡献，需要各位国际法学人的不懈努力。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长说，在全球化背景下，中国要在国际舞台上发挥更大的作用，离不开大量优秀的国际法人才。我们法学教育的目标，要求法律学生不仅有扎实的理论功底，还有着对法律的深刻理解，又能用法律理论来解释和解决实际问题。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;杰赛普（Jessup）国际法模拟法庭辩论赛&rdquo;是世界范围内重要的国际法模拟法庭比赛，也是各国国际法学教育水平的集中展示。本次比赛对于提升中国法学教育水平，推动国际法的发展及促进法学院校的国际化将产生深远的影响。借助于该项赛事，国内法学院校将与世界知名大学法学院加强交流，借鉴其培养法律人才尤其是国际法专业人才的经验，从而加快推动中国国际法人才的培养工作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 媒体链接： <a href="http://www.chinanews.com.cn/edu/news/2010/03-02/2145446.shtml">[中新社]国际法模拟法庭辩论赛在北京开赛</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news.xinhuanet.com/legal/2010-03/01/content_13077607.htm">[新华网]国际法学&ldquo;奥林匹克竞赛&rdquo;中国赛区选拔赛在京开幕</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
