{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大法学院朱景文、邵沙平教授赴重庆参加“涉黑性质犯罪与法律控制理论研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-04 09:36:26{/dede:field}
{dede:field name='body'}<p>　　4月26日至28日，人民大学法学院朱景文教授、邵沙平教授赴重庆参加由重庆市法学会和西南政法大学联合主办的&ldquo;涉黑性质犯罪与法律控制理论研讨会。朱景文教授主持了第三单元的会议，邵沙平教授就国际打黑问题作大会发言。来自中国人民大学、北京大学、清华大学、中国政法大学、中国社科院法学所、中国青年政治学院、公安大学、吉林大学、武汉大学、南京大学、山东大学等高校和来自最高人民法院、最高人民检察院、公安部、中国法学会的120多位专家学者参加了会议。 </p>
<p>　　会议期间，与会代表参观了由重庆市公安局举办的重庆打黑成果展览。中共中央政治局委员、重庆市委书记薄熙来同志会见了部分参加会议的代表，朱景文、邵沙平教授参加了会见活动，朱景文教授在会见时就重庆打黑的意义发言。4月28日晚朱景文教授还应邀在西南政法大学做了题为&ldquo;法律职业化的反思&rdquo;的学术讲座，西南政法大学校长付子堂教授主持了此次讲座。 </p>
<p>　　（编辑：苗育婧）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
