{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学与世界自然基金会联合主办气候变化技术转让研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-03-16 03:17:49{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学环境学院与世界自然基金会（WWF）于3月10日在北京国宏宾馆共同举办了题为&ldquo;环境友好技术开发、转让和部署：搭建通往哥本哈根协议的桥梁&rdquo;的研讨会。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该研讨会旨在进行非正式的沟通、咨询和辩论，就中国、欧盟和美国三方关于技术转让的谈判立场开展交流，并通过企业代表的经验交流来识别关键领域、障碍，从而为确定谈判立场、制定谈判政策和方案提供参考。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会上，中国国家发改委应对气候变化司谈判处处长李高，美国大使馆环境科技和健康处参赞Brent Christensen先生以及欧盟委员会驻华代表团一等秘书Magnus Gislev先生首先做了主题发言，分别介绍了中国、欧盟和美国在技术开发与转让议题上所持的观点。中国人民大学环境学院副院长邹骥教授结合各国政府代表的发言及其本人多年亲临谈判的经历，对今年年底哥本哈根会议上关于技术开发与转让议题的谈判前景进行了展望，归纳总结了未来谈判中需要突出的10个要点。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由邹骥教授领导的&ldquo;能源与气候经济学项目&rdquo;科研团队，一直从事气候变化经济学与政策方面的研究工作，并代表中国人民大学为中国政府参加联合国气候谈判提供技术支持。据悉，邹骥教授团队自2007年以来与WWF以学术交流、执行研究课题等形式，持续开展了一系列的合作。本次研讨会是双方系列合作的组成部分之一。此外，双方就气候变化技术开发与转让议题所开展的案例研究正在进行之中。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自联合国开发计划署（UNDP）等国际机构，来自英国、荷兰等驻华使馆，来自国家发改委、科技部、外交部、中国气象局、财政部，环境保护部等政府部门，来自中国社会科学院、清华大学、国家发改委能源研究所等国内研究机构，来自绿色和平组织（Green Peace）、第三世界网络（TWN）、全球战略联盟、第三代环境主义者（E3G）等国际知名非政府组织，以及来自中国风能协会、上海电气、壳牌公司等国内外知名企业和行业协会，共80多人参加了此次研讨会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
