<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国人民大学艺术学院室内乐演出小组在宜昌大获成功",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",218,271);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-03 08:48:26",273,332);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月28、29日，中国人民大学艺术学院室内乐演出小组应三峡大学、长江大学的邀请，在艺术学院副院长赵方教授的带领下分别在以上两所大学进行了交流演出。音乐会演奏了世界经典的室内乐作品，受到了宜昌市各界的高度评价和热烈欢迎。演出结束后，宜昌市委副书记李亚隆、三峡大学党委书记刘德富以及长江大学副校长李家宝及两校师生向参加演出的人民大学室内乐演出小组的老师们表示了热烈的祝贺。 </p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c110725/zlzzbyzhmzyyfhf-z2kfyn.jpg\" width=\"500\" alt=\"\" />&nbsp;</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演出当天晚上，音乐厅内座无虚席。音乐会结束后，他们纷纷表示这是他们第一次听到这么精彩的高水平室内乐音乐会。宜昌市委副书记李亚隆激动地说，&ldquo;迄今为止这是他在这座城市听到的最高水平的音乐会。&rdquo; </p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c110725/zlzzbyzhm2zhymf-zl2fhf.jpg\" width=\"500\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 通过这两场音乐会，宜昌人民了解到中国人民大学艺术学院音乐系的办学优势与特点。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n<br />\r\n<br />\r\n</p>",334,1482);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhmzyyfhf-z2kfyn_lit.jpg",1484,1577);
$z[7][4]['name']="litpic";

?>