{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院举行2010级公共管理硕士（MPA）开学典礼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-01 04:47:35{/dede:field}
{dede:field name='body'}<p>　　3月28日，公共管理学院2010级公共管理硕士（MPA）开学典礼在公共管理学院报告厅隆重举行。校党委常务副书记、纪委书记牛维麟，人力资源和社会保障部中国人事科学研究院副院长、党委副书记罗双平，住房和城乡建设部政策研究中心副主任王珏林，研究生院招生办公室主任宋东霞，公共管理学院院长、全国公共管理硕士（MPA）专业学位研究生教育指导委员会秘书长董克用，公共管理学院副院长蓝志勇、党委副书记王丹，部分合作办学单位负责人以及MPA教师出席会议，2010级MPA新生参加了本次开学典礼。开学典礼由公共管理学院副院长、MPA教育中心主任许光建主持。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bhymlf-2hhnl.jpg" alt="" /></p>
<p>　　开学典礼在庄严的国歌声中开始。牛维麟常务副书记代表学校热烈欢迎125名2010级MPA新生，他肯定了公共管理学院在MPA教育和人才培养方面取得的显著成绩，鼓励MPA新生们要着眼国家与社会，树立&ldquo;立学为民，治学报国&rdquo;的远大理想。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bhnzyznf-lmmzn.jpg" alt="" /></p>
<p>　　董克用院长代表学院对新生的到来表示欢迎，希望MPA研究生牢记&ldquo;实事求是&rdquo;校训和&ldquo;远见、求是、创新、奉献&rdquo;的院训，抓住在中国人民大学学习的宝贵机会和时光，深入、系统地学习，注重理论联系实际，争取为全面建设小康社会贡献应有力量。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bbfnzfyf-hnfyh.jpg" alt="" /></p>
<p>　　罗双平副书记代表合作单位发言，他回顾了中国人事科学研究院与公共管理学院在教学、科研方面的合作情况，指出了MPA教育在建设专业化公共管理专业人才队伍的地位和作用，肯定了与我校在合作培养MPA人才过程中取得的成果。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bbfmzfzf-blbkb.jpg" alt="" /></p>
<p>　　2010级新生代表方友刚同学和MPA研究生会主席王葛杨同学两位学生代表发言做出郑重承诺，以科学发展观为指导，践行校训和院训，以&ldquo;国民表率、社会栋梁&rdquo;为标准要求自己，刻苦学习、主动思考、学以致用，以实际行动为学校和学院增光添彩。</p>
<p>　　校领导、院领导还为MPA新生代表佩戴了校徽，向2009-2010学年MPA优秀学位论文作者及其指导教师颁发了荣誉证书。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2bbz2mfhf-yzmkz.jpg" alt="" /></p>
<p>　　（编辑：贾晓旭）</p>
<p>&nbsp;</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2bhymlf-2hhnl_lit.jpg{/dede:field}
