{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学公共管理学院与日本一桥大学协商合作交流事宜{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-11-12 04:37:54{/dede:field}
{dede:field name='body'}<p>　　11月2日，应日本国立大学法人一桥大学副校长田近幸治邀请，公共管理学院严金明副院长前往新世纪日航酒店，与一桥大学代表团进行了会谈。一桥大学国际公共关系学院前原康宏院长、国际交流处以及北京办事处的负责人出席会谈。 </p>
<p>　　田近副校长首先通报了今年6月与公共管理学院合作向日本文部科学省申请中日韩三国联合培养创新人才项目的情况，并表示一桥大学希望继续与公共管理学院开展交流合作，正式邀请公共管理学院派遣教师赴日讲学，并希望以此为契机，正式启动双方的实际交流合作。 </p>
<p>　　严金明副院长表示，一桥大学在人文社科研究领域富有盛名，公共管理学院非常愿意与日方开展交流合作，并表示希望今后能够与日方就双方教师、学生的交流以及项目研究进一步开展富有成效的交流与合作。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
