{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院国际新闻专业硕士赴延安参加“三项学习教育”新闻夏令营{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-07-15 04:14:32{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7月12日下午，中国人民大学新闻学院十名国际新闻传播专业硕士生参加了在中国记协举行的&ldquo;三项学习教育&rdquo;新闻夏令营活动出发仪式。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmffmzmlybf-lznf2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这次活动是在中宣部指导下，由新闻战线&ldquo;三项学习教育&rdquo;活动领导小组办公室组织，旨在加强对国际新闻传播后备人才&ldquo;三个代表&rdquo;重要思想、马克思主义新闻观以及新闻职业道德的教育。10名学生将与来自清华大学、北京外国语大学、中国传媒大学的同学共同前往延安，开始为期一周的参观学习活动。人大新闻学院国际新闻硕士班班主任高贵武老师带队前往延安。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国记协党委书记、三项教育领导小组组长翟惠生发表了动员讲话。他指出，这是首次针对在校学生举行的活动，旨在把&ldquo;三项学习教育&rdquo;活动向新闻队伍源头延伸，加强对国际新闻传播硕士的国情教育。他号召大家在放眼世界的同时不忘扎根国内，紧跟时代潮流也不忘革命传统。鼓励大家&ldquo;深入群众，不尚空谈&rdquo;。</p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmffm2lm2nf-hll2h.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新闻学院传播系主任胡百精老师代表人民大学发表了精彩致辞，他指出，新闻专业学生深入农村，亲近自然，能够加深对国家、民族、社会的认识，延安之旅将是一次深刻的&ldquo;历史之旅&rdquo;、&ldquo;知识之旅&rdquo;、&ldquo;责任之旅。&rdquo;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 活动期间，学生们将接受有关延安精神的革命传统教育和新闻工作传统教育；参观延安的革命旧址及新闻纪念馆；与当地新闻单位交流座谈；深入延安市所属区县农村农户家体验生活，与农户同吃同住同劳动，深入了解社情民意。此外，学生们必须至少学会干一样农活，并在老师指导下以稿件、视频、博客、微博等方式记录自己的所见所闻所感。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民日报、新华社、中央电视台、中国国际广播电台的资深记者编辑，将作为此次活动的业务老师，指导学生撰写新闻稿件，并主持优秀新闻稿件的评比。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101124/z2mfbmffm2hbykf-bblkb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 参加此次活动的国际新闻硕士，是在国家加强国际传播能力，大力培养高层次应用型国际新闻传播专门人才的背景下，经中宣部、教育部决定，自2009年起，由中国人民大学等高校试点培养的。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmffmzmlybf-lznf2_lit.jpg{/dede:field}
