{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}爱尔兰都柏林大学副校长率代表团访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际交流处{/dede:field}
{dede:field name='body'}<p>　　11月15日上午，爱尔兰都柏林大学副校长Brigid Laffan教授率代表团访问中国人民大学，薛浣白副校长会见了代表团一行。代表团成员包括该校经济学院院长David Madden教授，应用社会科学学院Anthony Fahey教授，人文学院研究生院院长Johan Elkink博士，地理、规划和环境政策学院Enda Murphy博士等。 </p>
<p align="center"><img src="/uploads/allimg/c101126/z2mfkyfhnmfyylf-zbknb.jpg" alt="" /></p>
<p>　　薛浣白副校长首先对Brigid Laffan教授一行表示欢迎，并回顾了两校以孔子学院为平台开展的各项合作，介绍了人民大学的国际化发展战略。Brigid Laffan教授简要介绍了此次的中国之行，希望加强两校在政治学、经济学、管理学、社会政策、环境政策以及城市规划等方面的合作，相信两校相近的国际化发展战略必将促进两校在未来开展更高、更深层次的交流与合作。随后，两校的相关学院分别就具体的合作细节进行了深入的磋商。 </p>
<p>　　学校公共管理学院、国际关系学院、环境学院、经济学院、社会与人口学院以及国际交流处等院系和部处有关人员参加了活动。 </p>
<p>　　（编辑：贾晓旭）<br />
</p>{/dede:field}
{dede:field name='pubdate'}1289876746{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhnmfyylf-zbknb_lit.jpg{/dede:field}
