<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","台湾世新大学传播学院院长到访中国人民大学新闻学院",89,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",218,265);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-07-26 11:15:48",267,326);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p align=\"center\"><img src=\"/uploads/allimg/c101124/z2mfbmffkfzzymf-hbhfm.jpg\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;7月20日，台湾世新大学传播学院院长陈清河教授和夫人到访中国人民大学新闻学院。新闻学院常务副院长倪宁教授、《国际新闻界》主编陈力丹教授与陈清河院长就两院的学术交流与合作事项进行了详尽的讨论，并就明年初在台湾世新大学共同召开&ldquo;新闻传播理论与实践&rdquo;学术会议达成协议。方洁博士参加会见。会见后，倪宁教授宴请陈清河夫妇，陈力丹、方洁和新闻学院办公室主任甘光千陪同。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈清河教授曾长期在台湾政治大学任教，担任政治大学广播电视系主任和政大之声电台台长；2007年曾任台湾电视公司董事长。2009年8月起就任世新大学传播学院院长。他现在还是台湾新闻局广播电视和网络传播领域四个委员会的委员。 <br />\r\n（编辑：罗豫伟）</p>",328,1160);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c101124/z2mfbmffkfzzymf-hbhfm_lit.jpg",1162,1254);
$z[7][4]['name']="litpic";

?>