<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","哲学院召开学院校友会筹备会",89,153);
$z[2][4]['name']="title";
$z[3]=Array("field","",155,194);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",196,241);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-11-11 03:37:47",243,302);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月9日，哲学院召开校友会筹备工作会。国家发改委黄勇处长，校长助理、哲学院院长郝立新教授，国学院党总支书记徐飞老师，哲学院党委副书记苏昊老师等相关老师参加了会议。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郝立新院长向各位老师和校友介绍了哲学院校友工作的现状以及哲学院校友会工作的设想。与会各位老师和校友表示将会认真配合哲学院做好校友工作。各位老师和校友结合自身实际，对哲学院校友会筹备工作提出了许多建设性的意见和建议。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 哲学院校友会筹备工作会的召开，标志着学院校友会筹备工作正式开始。接下来，学院校友工作办公室将根据筹备会工作的意见和建议，认真做好校友资料的搜集工作，为明年哲学院校友会成立大会圆满召开打下基础。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：王开)<br />\r\n</p>",304,1134);
$z[6][4]['name']="body";
$z[7]=Array("field","",1136,1175);
$z[7][4]['name']="litpic";

?>