{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘瑞教授赴厦门出席能源高峰会议并开展学术交流活动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-01-13 02:54:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月7-9日，经济学院副院长刘瑞教授应厦门大学能源研究院的邀请，出席了该院举办的中国能源环境高峰论坛&mdash;&mdash;海峡西岸峰会，并在金融与能源分会场上发表了题为&ldquo;中国经济增长低碳化&rdquo;的讲演。中国能源环境高峰论坛作为厦门大学建校90周年庆祝活动的首场学术论坛，由厦门大学、台湾清华大学与中国人民银行共同举办，来自自然科学和社会科学领域的专家学者及企业和政府的业界人士共计200人参加了本次峰会。 <br />
　　与会期间，刘瑞教授开展了一系列学术交流活动。他拜访了厦门大学能源经济研究中心林伯强教授，探讨了建设能源经济学科事宜。他还会见了厦门大学计划统计系主任朱建平教授等，共同商议了如何加强国民经济学科建设事宜。同时他还参加了由中国人民银行研究局主持完成的《厦门建设海西区域性金融服务中心》课题结项论证会。 </p>
<p>
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
