{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}南洋理工大学传播与信息学院在人大新闻学院举办毕业生交流会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院 吴尚蔚{/dede:field}
{dede:field name='pubdate'}2011-03-18 09:24:04{/dede:field}
{dede:field name='body'}<p>　　3月16日下午，新加坡南洋理工大学传播与信息学院在中国人民大学新闻学院举办毕业生交流会，南洋理工大学传播与信息学院副院长郝晓鸣出席并演讲。 </p>
<p>　　&ldquo;优秀的学生资源，来自世界各地的师资力量，开放的社会条件，对大学来说是重要的因素。&rdquo;会上，郝晓鸣副院长给同学们介绍了南洋理工大学及其传播与信息学院的基本情况，鼓励同学们申报其研究生课程。在同学们的提问环节当中，他还介绍了目前新加坡的媒体就业状况。 </p>
<p>　　郝晓鸣博士曾任新华社记者，毕业于美国密苏里大学新闻学院，现任新加坡南洋理工大学黄金辉传播与信息学院副院长，国际中华传播学会会长。其主要研究方向包括新闻理论、媒介效应、国际传播、新传媒技术对社会的影响等。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
