{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院与光明日报合作开设“法律体系史话”专栏{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-11 02:59:43{/dede:field}
{dede:field name='body'}<p>【开栏的话】 </p>
<p>　　中国特色社会主义法律体系的如期形成,是新中国民主法制建设史上的一个重要里程碑。这个科学、和谐、统一的法律体系,是由一部部具体的法律所构成的。如果说法律体系是一座坚固的大厦,每一部法律就是一块块基石。光明日报与中国人民大学法学院合作开设了&ldquo;法律体系史话&rdquo;专栏,邀请一批见证了重要法律诞生的法学家讲述他们参与立法的故事、细节,与读者一起回顾新中国波澜壮阔的立法进程。</p>
<p>以下是每期文章的链接： </p>
<p>　　<a href="http://epaper.gmw.cn/gmrb/html/2011-03/03/nw.D110000gmrb_20110303_3-10.htm">许崇德：千里之行 始于足下&mdash;&mdash;记新中国成立初期的立法活动</a> </p>
<p>　　<a href="http://epaper.gmw.cn/gmrb/html/2011-03/04/nw.D110000gmrb_20110304_2-11.htm">杨大文：两部婚姻法 三个里程碑</a> </p>
<p>　　<a href="http://epaper.gmw.cn/gmrb/html/2011-03/05/nw.D110000gmrb_20110305_4-07.htm?div=-1">高铭暄：浅忆新中国刑法的制定与发展</a> </p>
<p>　　<a href="http://epaper.gmw.cn/gmrb/html/2011-03/07/nw.D110000gmrb_20110307_1-10.htm?div=-1">王利明：亲历民法通则的制定</a>&nbsp;</p>
<p>　　<a href="http://epaper.gmw.cn/gmrb/html/2011-03/08/nw.D110000gmrb_20110308_1-10.htm?div=-1">江 伟：民事诉讼法立法往事</a> </p>
<p>　　<a href="http://epaper.gmw.cn/gmrb/html/2011-03/10/nw.D110000gmrb_20110310_1-10.htm?div=-1">陈卫东：刑事诉讼法修改背后的故事</a> </p>
<p>　　（编辑：贾晓旭）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
