{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}巴黎十大BENAVENT教授访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>　　12月11日上午，巴黎十大经济学院双文凭研究生项目负责人BENAVENT教授和中国项目负责人韩淑艳老师访问人民大学。经济学院院长杨瑞龙教授在明德主楼1103会见了BENNAVENT教授一行。经济学院副院长刘元春教授、经济学院院长助理王晋斌教授、经济学院院长助理郑新业副教授、经济学院院长助理陈彦斌副教授、研究生院招生办公室马小侠主任、国际交流处副处长石佳友副教授参加会见。与会双方就联合培养经济管理学研究生的具体事宜进行了深入探讨。</p>
<p>　　（编辑　慧茹）</p>{/dede:field}
{dede:field name='pubdate'}1261448628{/dede:field}
{dede:field name='litpic'}{/dede:field}
