{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长新年前夕专程赴苏看望国际学院师生 共迎元旦佳节{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}国际学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年12月31日，中国人民大学校长纪宝成专程来到国际学院（苏州研究院），在校党委副书记兼副校长、国际学院院长王利明，国际学院常务副院长陈甬军等陪同下，出席学院迎新年系列活动，亲切看望国际学院师生。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 31日傍晚，纪宝成校长刚抵苏州，就出席了国际学院（苏州研究院）工会组织的教职工集体婚礼仪式。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnn2mnknzl2f-yyl2z.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长在为学院三对新人主婚时表示，经过多年的建设和发展，国际学院在各方面取得了长足的进步。三对新人在收获工作成就的同时，也收获了圆满的爱情。纪校长祝愿新人们百年好合、永结同心，希望国际学院越办越好、喜事越来越多。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 晚上八点半，纪宝成校长一行又来到&ldquo;姑苏弦歌&mdash;&mdash;国际学院（苏州研究院）新年晚会&rdquo;的现场，与全院师生一道观看晚会。纪宝成校长的到来让在场的600多名师生备受鼓舞，全场欢声雷动。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mnnk2f2f-klhzk.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪宝成校长在致辞中首先对大家表示新年的祝福，并强调，国际学院是中国人民大学的一个重要的有机组成部分，是学校事业发展的增长点，国际学院的重要性会随着时间的推移凸现出来。纪宝成校长表示，在苏州这样的地方学习和生活会是同学们一生的宝贵财富，希望同学们珍惜在苏州学习的时光，认真学习，适意生活，茁壮成长。纪校长还对同学们精彩的演出给予高度的肯定和称赞。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在零点钟声到来之际，纪宝成校长再次来到国际学院（苏州研究院）新年舞会的现场，与全场师生一同倒数读秒喜迎新年。伴随着钟声的响起，全场师生共同迎来了2011年。在欢庆的气氛中，纪宝成校长再次表达了对大家的祝福，希望国际学院的同学们在新年取得更多的成绩。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mnnkyzkf-nzzmz.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;元旦上午，纪宝成校长还在学院和高教区领导陪同下检查了校园建设及敬斋酒店运营情况。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mnnnlynf-mbkln.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在苏期间，江苏省委常委、省委组织部部长石泰峰，江苏省委常委、苏州市委书记蒋宏坤，苏州工业园区工委书记马明龙等省市领导会见和宴请了纪宝成校长一行，就加强合作交流等问题进行了商谈。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学校长助理、财务处处长査显友，人事处处长郭洪林，研究生院副院长刘凤良，校园建设管理处副处长李明等陪同看望。 <br />
</p>
<p>（编辑&nbsp; 燕燕）</p>{/dede:field}
{dede:field name='pubdate'}1294003578{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mnknzl2f-yyl2z_lit.jpg{/dede:field}
