{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院证据学教研室多篇论文获北京市刑侦学研究会优秀论文奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-02 09:46:53{/dede:field}
{dede:field name='body'}　　3月31日上午，北京市刑事侦查学研究会第十三次学术年会在北京市公安局刑侦总队召开。在本次年会上，法学院证据学教研室提交的多篇论文获奖。其中，刘品新副教授的论文《论电子取证及其法律规则》、廖明和俞楠的论文《法治视野下的网络侦查陷阱研究》、刘燕和刘晶的论文《论网络搜索及其法律规则》、李慧的论文《试论诱惑侦查的理论基础》、杨建国的论文《论视频监控的犯罪侦查价值》获得了年会优秀论文二等奖。而吕泽华的论文《论网络通缉及其法律规则》获得了三等奖。此外，法学院证据学教研室还获得了优秀组织奖。 <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
