{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}忆革命传统  走红色之旅——记外国语学院参观革命圣地西柏坡{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图/文　外国语学院{/dede:field}
{dede:field name='pubdate'}2010-10-25 05:19:01{/dede:field}
{dede:field name='body'}<p>　　为了深入贯彻党中央和北京市委精神，围绕学校中心工作，结合学习贯彻胡锦涛总书记考察中国人民大学重要讲话精神，积极开展组织学习、研究和各类主题实践活动，进一步推动创先争优活动的深入开展，10月16日至17日，外国语学院院党委、院工会共同组织了&ldquo;忆革命传统走红色之旅&mdash;&mdash;参观革命圣地西柏坡&rdquo;主题活动。在党委书记张卫平、党委副书记齐畅的带领下，50名教工党员及部分入党积极分子奔赴西柏坡红色革命圣地进行参观、学习。</p>
<p>　　西柏坡是党中央&ldquo;解放全中国的最后一个农村指挥所&rdquo;， 是中国共产党领导全国人民和人民解放军与国民党进行战略大决战的指挥中心。此外，中国共产党曾在此领导了全国土地改革运动，召开了七届二中全会等重大会议。</p>
<p>　　外国语学院的师生们怀着无比崇敬的心情参观了西柏坡纪念馆、名人石刻园，瞻仰了领袖故居、军委作战室和中共中央旧址，近距离&ldquo;触摸了&rdquo;革命岁月，重温了革命传统，坚定了将&ldquo;西柏坡精神&rdquo;时时刻刻融入日常工作、生活中的决心。</p>
<p>　　在七届二中全会旧址，党员们面对鲜红的党旗庄严宣誓，重温了入党誓词，深感作为一名共产党员的使命与责任。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnmmhllnkhf-2blly.jpg" width="500" height="333" alt="" /></p>
<p>　　在为期两天的参观、学习之后，参与此次活动的50名教工党员及部分入党积极分子纷纷表示对&ldquo;西柏坡精神&rdquo;以及其蕴含的优秀革命传统有了更深刻、更全面的理解。其中，学生党员连世龙表示：&ldquo;这次西柏坡红色之旅，使我更加坚定了奋斗目标，作为一名共产党员，我要学习西柏坡精神，在学习和生活中发挥模范带头作用！&rdquo; </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnmmhllnkhf-2blly_lit.jpg{/dede:field}
