<?php
$z[0]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />\r\n<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n<m:item name='在线报名模块' link='catalog_do.php?dopost=guestbook' rank='plus_在线报名模块' target='main' />\r\n\r\n  <m:item name='在线报名 italy' link='catalog_do.php?dopost=guestbook_italy' rank='10' target='main' />\r\n",53,762);
$z[0][4]['item']="7";
$z[0][4]['name']="辅助插件";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n<m:item name='UCenter配置' link='api_ucenter.php' rank='' target='main' />\r\n",766,909);
$z[1][4]['name']="UCenter模块";
$z[1][4]['c']="6,";
$z[1][4]['display']="block";
$z[1][4]['rank']="";
$z[2]=Array("top","\r\n<m:item name='分类设置' link='group_store.php' rank='group_All' target='main'/>\r\n<m:item name='圈子列表' link='group_main.php' rank='group_All' target='main'/>\r\n<m:item name='主题管理' link='group_threads.php' rank='group_All' target='main'/>\r\n",911,1211);
$z[2][4]['name']="圈子管理";
$z[2][4]['c']="6,";
$z[2][4]['display']="block";
$z[3]=Array("top","\r\n  <m:item name='栏目管理' link='ask_type.php' rank='' target='main' />\r\n  <m:item name='问题管理' link='ask_admin.php' rank='' target='main' />\r\n  <m:item name='答案管理' link='ask_answer.php' rank='' target='main' />\r\n",1213,1496);
$z[3][4]['name']="问答管理";
$z[3][4]['c']="6,";
$z[3][4]['display']="block";
$z[3][4]['rank']="";

?>