{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长出席中国战略文化促进会成立大会并被聘为高级顾问{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='pubdate'}2011-01-06 09:10:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国战略文化促进会成立大会于1月5日举行，全国政协副主席郑万通出席第一届会员代表大会并当选为会长。中国人民大学校长纪宝成出席并被聘为高级顾问，中国人民大学国际关系学院黄嘉树教授当选为副会长，金灿荣教授当选为理事。文学院国剧研究中心孙萍教授参加了成立大会。 <br />
&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国战略文化促进会是由从事国际问题研究、台湾问题研究和文化问题研究的专家、学者、团体和社会活动家组成的全国性、非营利性民间社会团体，旨在通过对中国战略文化的研究、传播和交流，为促进亚太地区安全稳定与台湾海峡两岸和平发展作出贡献。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
