<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","纪宝成校长出席中国战略文化促进会成立大会并被聘为高级顾问",89,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","学校办公室",226,275);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-06 09:10:51",277,336);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国战略文化促进会成立大会于1月5日举行，全国政协副主席郑万通出席第一届会员代表大会并当选为会长。中国人民大学校长纪宝成出席并被聘为高级顾问，中国人民大学国际关系学院黄嘉树教授当选为副会长，金灿荣教授当选为理事。文学院国剧研究中心孙萍教授参加了成立大会。 <br />\r\n&nbsp;<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国战略文化促进会是由从事国际问题研究、台湾问题研究和文化问题研究的专家、学者、团体和社会活动家组成的全国性、非营利性民间社会团体，旨在通过对中国战略文化的研究、传播和交流，为促进亚太地区安全稳定与台湾海峡两岸和平发展作出贡献。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）</p>",338,1037);
$z[6][4]['name']="body";
$z[7]=Array("field","",1039,1078);
$z[7][4]['name']="litpic";

?>