{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院王虎峰副教授参加北京市“十二五”卫生规划衔接交流会并作主题发言{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-09-17 10:52:10{/dede:field}
{dede:field name='body'}<p>　　8月26-27日，为积极推进《北京市&ldquo;十二五&rdquo;时期卫生事业发展改革规划》编制工作，增进市级、区县卫生事业规划以及各卫生专项规划间的沟通和交流，北京市卫生局组织召开了北京市卫生系统&ldquo;十二五&rdquo;规划编制工作衔接交流会。会议由北京市卫生局发展计划处肖大伟处长主持，市药监局、中医局、卫生局有关处室规划工作负责人以及16个区县卫生局规划编制工作分管领导和科室负责人100余人参会。市卫生局副局长郭积勇到会讲话。 </p>
<p>　　公共管理学院医改研究中心主任王虎峰副教授作为《北京市&ldquo;十二五&rdquo;时期卫生事业发展改革规划研究》课题负责人介绍了课题研究的整体思路、前一阶段课题调研和研究所取得的成果，分析了规划编制需要重点关注和研究的领域和问题，并就此提出了规划研究框架思路和政策建议体系，取得了与会者的共识和肯定。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
