{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院参与举办第二届少数民族地区信息传播与社会发展论坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-11-05 09:41:39{/dede:field}
{dede:field name='body'}<p>　　10月24&mdash;26日，由中国人民大学新闻学院参与主办的第二届少数民族地区信息传播与社会发展论坛在西藏民族学院召开。</p>
<p>　　本次论坛以&ldquo;传播&middot;团结&middot;发展&rdquo;为主题，共分&ldquo;少数民族地区新闻事业研究&rdquo;、&ldquo;少数民族新闻传播研究&rdquo;等八个子论坛，来自西藏、新疆、内蒙、宁夏等少数民族地区和中国人民大学、复旦大学、南京大学、中央民族大学、中国西藏信息中心、《西藏日报》等40余家高等院校、新闻媒体、研究机构在内的百余名学者，就民族地区新闻传播的现状及发展战略等问题展开了深入研讨。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmffl2blhyf-z2mzl.jpg" />&nbsp;<br />
中国人民大学新闻学院常务副院长倪宁教授在会上致辞</p>
<p>　　新闻学院院长、全国政协外事委员会主任、原国务院新闻办主任赵启正同志专门给论坛发来贺信，新闻学院常务副院长倪宁教授受邀在论坛开幕式上致辞。 </p>
<p>　　开幕式上，中国人民大学新闻与社会发展研究中心与西藏民族学院联合挂牌成立了 &ldquo;西藏新闻传播与社会发展研究所&rdquo;。这也是国内第一家针对西藏新闻传播事业的研究机构，新闻学院郑保卫教授受邀担任名誉所长。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmffllzzzlf-2yfzm.jpg" /><br />
西藏民族学院院长刘洪顺为郑保卫教授颁发聘书</p>
<p>　　本届论坛邀请的嘉宾还有国家民委政策研究室主任金星华、中共陕西省委宣传部常务副部长晏朝、西藏自治区党委宣传部常务副部长王明星、复旦大学新闻学院常务副院长黄瑚教授等。新闻学院周建明教授、张征教授也出席论坛并发言。</p>
<p>　　（编辑：易晨）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmffl2blhyf-z2mzl_lit.jpg{/dede:field}
