{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“中国宏观经济论坛（2011年第一季度）”在人民大学举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-28 02:56:32{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月26日，由中国人民大学经济研究所、东海证券有限责任公司、中国诚信信用管理有限公司主办，中国人民大学经济学院承办的&ldquo;中国宏观经济论坛（2011年第一季度）&rdquo;在逸夫会堂第一报告厅举行，这是人大经济研究所举办的第17期论坛。中国人民大学副校长林岗教授出席论坛并致辞，论坛开幕式由经济学院院长、经济研究所联席所长杨瑞龙教授主持。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110419/zlflznzkym2lf2f-zbnn2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国社会科学院学部委员、经济研究所原所长刘树成研究员, 中国银行业协会专职副会长杨再平研究员, 中国人民大学校长助理、研究生院常务副院长吴晓求教授，中国人民大学经济研究所联席所长毛振华教授，人民大学经济学院院长、经济研究所联席所长杨瑞龙教授，人民大学经济学院副院长、经济研究所联席副所长刘元春教授，经济学院胡乃武教授，经济学院区域与城市经济研究所所长孙久文教授，经济学院雷达教授，东海证券研究所所长、人民大学经济研究所联席副所长朱戎博士，中国诚信信用管理有限公司副总裁、人民大学经济研究所联席副所长阎衍博士等宏观经济研究领域的一流专家和业界代表，以及人大经济研究所的全体研究人员参加了本次论坛。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c110419/zlflznzkymbnnhf-22f2l.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林岗副校长就当前治理通胀问题发表了自己的看法。他说，目前我国通货膨胀的治理越来越复杂，应该有针对性地考虑到各方面不利因素的变动，要从供给和需求两个方面来分析。通货膨胀的治理还需要政府提高政策操作水平，做到长期目标和短期目标相协调。同时，通货膨胀的治理和失业问题的解决也要结合起来，不能顾此失彼。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkymylmlf-lnkhf.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长向与会者介绍了历次中国宏观经济论坛举办的情况和论坛的主要特点，并对各位嘉宾的到来表示热烈欢迎。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkymymfmf-hkyhk.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 坛上，中国人民大学经济学院院长助理陈彦斌教授代表经济研究所课题组发布了《中国宏观经济形势分析与预测报告（2011年第一季度）&mdash;&mdash;经济增长与民生目标冲突下的中国通货膨胀》。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告认为，在经历了2009年的下跌之后，我国价格总水平在2010年开始回升，并呈现逐季上涨态势，2010年CPI涨幅达到3.3%。如果考虑到房价没有充分计入CPI、食品价格上涨幅度较大、物价是在2007-2008年高位基础上的继续上涨以及行政管制的干预等因素，当前的通胀形势可能比CPI所显示的更为严峻。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkymk2nhf-b2hfy.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 从经济和社会的双重视角来看，通货膨胀问题的重要性并不亚于经济增长。过去30年，解决十几亿人口的吃饭穿衣问题并逐步迈向小康社会是人民最迫切的愿望，保持经济快速增长是我国最主要的任务。但是，在高速的经济增长过程中也积累了大量的社会冲突，尤其是产生了较为严重的贫富差距。而我国通胀对中低收入家庭和弱势群体的影响较为严重，会进一步恶化本已严重的贫富差距，而目前脆弱的社会结构可能难以承受这种进一步加大的社会不稳定因素。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkkffzlf-yzz2b.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在资本深化、房地产深刻影响宏观经济、刘易斯拐点逐渐到来等大背景下，我国当前通胀形成机制出现了一些新变化：首先，2009年过度宽松的货币政策、2010年超计划的货币投放和不断攀升的外汇占款等因素导致的充裕流动性在农产品市场和房地产市场寻找出口，直接造成了物价和房价的迅速上升，而外资的涌入和高通胀预期下的高货币流通速度则进一步加剧了这一过程；其次，刘易斯拐点的逐渐到来带动了低端劳动力工资的持续上涨，造成了低端服务业和农产品价格上涨；再次，国际粮价和国际原材料价格通过影响国内农产品价格来推高CPI，输入型通胀逐渐显现。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkkflnknf-kzfz2.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告指出，改革开放以来，我国经常面临通胀压力，特别是2003年以来，通胀逐渐出现常态化的趋势。我国之所以经常面临通胀压力，其根源在于增长主义的发展模式。我国长期以来一味追求经济的高速增长，特别是希冀以单纯的经济更高速增长来解决或掩盖发展过程中出现的各种矛盾和问题，已经表现出明显的&ldquo;增长依赖症&rdquo;和&ldquo;投资饥渴症&rdquo;。这种增长模式带来的高增长和高投资容易导致经济体出现资源紧张、经济过热，引发需求拉动型的通货膨胀。另外，以增长为首要目标的宏观调控体系为经济体注入大量流动性，更加剧了通胀压力。因此，不改变我国当前这种增长主义发展模式，不将增长主义政府转型为公共服务型政府，就难以从根本上改变我国经常出现通胀的局面。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkkfklbyf-nbzl2.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 依据中国人民大学中国宏观经济分析与预测模型（CMAFM）测算，2011年我国将存在温和的通胀，全年通胀率预计为4.5%，高点将出现在第二季度。流动性存量较大、信贷惯性较大和外汇占款比重较高等因素使得2011年的物价上涨仍有较为充足的流动性基础。受春季干旱、输入型价格上涨、农业劳动力机会成本增加、国家粮食收购价格提高和大量闲散资金流入的影响，农产品价格在2011年可能会进一步上涨并推高整体物价。2011年美国等主要发达经济体将继续推行宽松货币政策，将进一步推高国际能源和金属等大宗原材料价格，这势必增加输入型通胀压力。但是，实体经济基本保持平衡，宏观调控政策的基调已回归稳健，因而2011年并不存在出现恶性通胀的基础。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkkzfm2lf-mll2l.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 报告的主要政策建议包括：全年尤其是上半年应实施稳健偏紧的货币政策。积极发展实体经济，着力推动民营经济发展。加大支农力度，增强农业综合生产能力，进一步加强和巩固农业基础地位，积极保障粮食安全。加强能源储备建设，提高能源利用效率，积极保障能源安全。积极推进工资形成机制市场化变革，建立工资的通胀指数化机制。加强对房地产市场的调控，抑制房价泡沫。积极推进中长期改革，推动治理通货膨胀水平的有效提升。陈彦斌教授的精彩演讲博得现场观众的阵阵掌声。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110419/zlflznzkkzhyzyf-zfzkzz.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，各位领导和专家也围绕人大报告，就本轮物价上涨出现的新现象、新原因、新机制和新问题，本轮通胀的根源是源于中国内生性的制度安排，还是气候、国际输入等外生因素的产物，核心CPI与CPI的偏离与民生目标是否存在冲突，是否意味着通胀治理的宏观目标与民生目标存在本质的冲突，中国4%&mdash;5%的通胀率是否将常态化，中国通胀治理如何展开民生工具与宏观工具、外部措施与内部措施、数量工具与价格工具的匹配，中国CPI权重与测算方法，是否会引起分析与决策的系统偏差等问题进行了积极有益的讨论。他们睿智精辟的演讲，引起与会者的强烈兴趣与共鸣。 </p>
<p align="center"><img height="334" src="/uploads/allimg/c110419/zlflznzkkznblbf-zzbnkh.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新华社、光明日报、经济日报、中国证券报、21世纪经济报道、第一财经日报、经济观察报、中国经济导报等20余家社会媒体对论坛进行了采访和报道，和讯网对论坛进行了现场直播。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 和讯网直播链接：<a href="http://news.hexun.com/2011/rdhg/">http://news.hexun.com/2011/rdhg/</a> <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzkym2lf2f-zbnn2_lit.jpg{/dede:field}
