{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院朱景文、范愉、肖建国教授应邀参加全国人大内务司法委员会人民调解立法座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-19 02:57:46{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月18日上午，中国人民大学法学院朱景文、范愉、肖建国三位教授应全国人大内务司法委员会的邀请，参加《中华人民共和国人民调解法（草案）》立法座谈会。会议听取了与会专家学者对人民调解法草案的意见。来自中央综治办、最高人民法院、最高人民检察院、公安部、民政部、司法部、财政部、国务院法制办、全国总工会、全国妇联等部门、单位的与会人员也表达了对人民调解法尽快出台的期许，并提出了若干进一步完善的建议。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议围绕人民调解法草案，重点讨论了人民调解的定位、适用范围、基本原则、调解组织和调解员、调解程序、调解协议的效力、人民调解协议的司法确认、人民调解与行业调解和商事调解等民间调解的关系、人民调解法与民诉法的关系等问题展开了讨论，提出了完善人民调解法，推动人民调解法尽早出台的若干具体建议。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《中华人民共和国人民调解法（草案）》由司法部牵头起草，历经数年，几易其稿，先后多次征求过专家学者和相关部门的意见。人民大学法学院范愉教授、陈桂明教授、肖建国教授均被司法部聘为起草咨询专家，全程参与了人民调解立法工作。本次座谈会讨论的《中华人民共和国人民调解法（草案）》已由国务院常务会议讨论并原则通过，并提交全国人大审议。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
