<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","第五届中国人民大学-辅仁大学联合研讨会成功举行",89,172);
$z[2][4]['name']="title";
$z[3]=Array("field","",174,213);
$z[3][4]['name']="writer";
$z[4]=Array("field","港澳台办公室",215,266);
$z[4][4]['name']="source";
$z[5]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月8日，第五届中国人民大学-辅仁大学联合研讨会在人民大学逸夫会议中心举行。中国人民大学副校长杨慧林教授出席开幕式并致辞。辅仁大学国际教育处处长蔡淑梨教授一行参加了研讨会。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式上，杨慧林副校长首先代表中国人民大学致欢迎辞，对到会的台湾辅仁大学二十位专家学者表示热烈的欢迎，并表示两校有多年的友好交流与合作，希望在原有基础上进一步扩大交流的内涵和深度。辅仁大学国际教育处处长蔡淑梨教授则在致辞中表示愿意继续为两校实质性交流作出努力，进一步开展学生交换学习项目以及双联学位等项目，以期取得互利双赢的良好效果。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会围绕着&ldquo;全球化背景下的合作共享与文化超越&rdquo;这一主题进行了深入的研讨，会议分为三个分会场，参加此次研讨会的学院有商学院、财政金融学院、理学院等。商学院张凯、刘军，财政金融学院涂永红、陈忠阳，理学院物理系鲍威、张芃，化学系李志平、曹廷炳、于安池、徐立进等老师分别发表了论文。经过两校专家学者充分的研讨，会议取得了良好的效果。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7日晚，人民大学举行欢迎晚宴，招待台湾辅仁大学代表团，薛浣白副校长出席并发表了热情洋溢的讲话。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会后，辅仁大学代表团分别参访学校相关院系，进行深入沟通交流，加深了解。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />",268,1701);
$z[5][4]['name']="body";
$z[6]=Array("field","1289508360",1703,1753);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1755,1794);
$z[7][4]['name']="litpic";

?>