{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}邹骥教授应邀出席联合国经济与社会理事会特别会议并发表演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-05-20 10:32:00{/dede:field}
{dede:field name='body'}<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnf2zybmmf-bymky.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应联合国经济与社会理事会主席的邀请，2008年5月2日邹骥教授在纽约联合国总部经济与社会理事会出席其举办的题为&ldquo;实现千年发展目标，应对气候变化挑战（Achieving the MDGs and Coping with the Challenge of Climate Change）&rdquo;的特别会议并作为主讲人在大会上做了题为&ldquo;关于气候有益技术开发与转让的观点&rdquo;的主题演讲。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应邀在会上做主题演讲的还有：英国新经济学基金会政策事务主任和气候变化项目负责人Andrew Simms先生，政府间气候变化专门委员会第三工作组联合主席及塞拉利昂大学研究生院长Ogunlade Davidson教授，印度能源与资源研究所（TERI）执行主任Leena Srivastava, 美国美林公司负责公共政策事务的高级副总裁Mark Goldfus先生。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次会议旨在为即将举行的部长级会议做准备，就如何将实现联合国千年发展目标与应对气候变化结合起来这一主题听取国际专家代表的意见。经社理事会成员国常驻联合国使团的代表出席了会议并就上述专家的发言进行了质询。联合国负责经济与社会事务的副秘书长沙祖康先生出席大会并致词。在大会开始之前，沙祖康副秘书长会见了邹骥教授并就气候变化国际体制安排和跨国技术合作等问题的方案进行了讨论。中国驻联合国使团参赞白永杰女士和联合国经济社会理事会能源与交通处项目官员李少义先生还在会后专门宴请了邹骥教授。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邹骥教授领导的课题组多年来一直开展气候有益技术国际开发与转让领域的研究。其研究成果在国内外的影响不断扩大。2007年5月16日联合国气候变化框架公约附属机构第26次会议期间，邹骥教授曾作为中国政府推荐的专家在会上发表了专题演讲。同年，世界自然基金会资助邹骥教授课题组开展了专题研究并在印尼巴厘岛举办的联合国气候变化框架公约第13次缔约方大会期间向参加会议的各国谈判者发布了其研究成果。2008年4月24日至25日，在由中国科技部、发改委等部委联合举办的&ldquo;气候变化与科技创新国际论坛&rdquo;上，邹骥教授应邀发表演讲，进一步阐述其课题组的研究成果。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnf2zybmmf-bymky_lit.jpg{/dede:field}
