<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","耶鲁大学校长致信纪宝成校长祝贺人民大学命名组建六十周年大会成功召开",89,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻中心",236,283);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，耶鲁大学校长理查德&bull;雷文致信纪宝成校长，对人民大学命名组建六十周年大会的成功召开表示祝贺。&nbsp;</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 理查德&bull;雷文校长表示，他是从人民大学和耶鲁大学的共同校友张磊处获悉人民大学命名组建六十周大会办得隆重而热烈，特此对纪宝成校长的出色工作表示祝贺。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 信中还提到了今年教师节前夕胡锦涛总书记考察人民大学一事。理查德&bull;雷文校长写道：&ldquo;胡锦涛主席用半天的时间亲临贵校表示庆祝，这是对您卓越工作的一种非凡的肯定。我对您所做的一切深表钦佩，我们在耶鲁大学对我们之间的友谊和合作而感到自豪。&rdquo; </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href=\"http://news1.ruc.edu.cn/102447/71211.html\">中国人民大学隆重庆祝命名组建60周年</a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href=\"http://news1.ruc.edu.cn/102376/103845/\">[专题新闻]：胡锦涛总书记考察人民大学</a></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />\r\n</p>",285,1392);
$z[5][4]['name']="body";
$z[6]=Array("field","1289353999",1394,1444);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1446,1485);
$z[7][4]['name']="litpic";

?>