{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院举行2010新年联欢会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2009-12-29 10:03:44{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月26日晚，经济学院2010新年联欢会隆重举行。学校党委书记程天权教授、副校长林岗教授等出席联欢会并致辞。经济学院院长杨瑞龙教授主持了联欢会开幕式。经济学院110余位教职工欢聚一堂，共庆佳节。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhymyhkbyf-zzmkm.jpg" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 程天权书记首先转达了中央领导、教育部领导和学校领导对全体教师的节日问候。他指出，在过去的一年里，国家整体保持了良好的发展势头，国庆60周年的系列庆典更是向世界展示了中国高昂的精神面貌；人民大学也在教育部直属高校绩效评价和学生就业等各个方面取得了优异的成绩。程天权书记表示，经济学院是学校的一张&ldquo;名片&rdquo;，是一个有着悠久历史和优良学风的学院，一级学科在全国的历次评估中始终保持领先位置，他希望经济学院的学者能够更好地总结中国的发展经验，对于国家未来发展进行前瞻性研究，在为国家做出更大贡献的同时，继续做好学科建设和人才培养工作。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林岗副校长也代表学校向 经济学院全体教职工致以新年的问候，他祝愿大家新年好，万事如意。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhymnfbyhf-2zy2n.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长在致辞中总结了学院在2009年在学科建设、人才培养、国际性提升、社会服务等方面所取得的工作成绩，并对2010年学院的工作安排进行了展望。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新年联欢会由经济学院陈建教授主持。陈建教授以生动活泼、幽默风趣的主持给联欢会掀起了一个又一个高潮，杨瑞龙院长、刘瑞副院长、高成兴教授、陈建教授、雷达教授、关雪凌教授、方竹兰教授，各教研室代表和管理职员代表等，或一展歌喉，或展示才艺，奉献了一场精彩的文艺节目。&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;各位老师都经过了精心准备。雷达教授和关雪凌教授还专程到KTV进行了彩排，为大家奉献了高水准的表演。整个联欢会充满了欢声笑语，大家载歌载舞，情绪昂扬，气氛热烈。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在游戏抽奖环节中，老师们积极参与，认真比赛，台上台下积极互动，联欢会的气氛达到最高潮。 </p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzhymm2mfyf-lll2z.jpg" width="500" height="333" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 新年联欢会是经济学院全体老师欢聚一堂，总结过去，展望未来，沟通交流的重要平台，学院领导高度重视，亲自挂帅，每年都要投入大量的人力物力，力求给全体教职工营造一个欢乐祥和、温情热烈的节日氛围。近几年以来，学院新年联欢会的参与度越来越高，规模越来越大，已经成为了全体教职工热切企盼的年度聚会，是学院的&ldquo;春晚&rdquo;。今年尤是如此，这充分体现了学院的凝聚力和向心力，展现了经济学院&ldquo;和谐经院一家人&rdquo;的良好文化氛围。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhymyhkbyf-zzmkm_lit.jpg{/dede:field}
