{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院院长郭庆旺教授当选中国财政协会副会长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-04-13 02:46:07{/dede:field}
{dede:field name='body'}<p>　　4月10&mdash;12日，中国财政学会2010年年会暨第18次全国财政理论讨论会在北京召开。中央有关部门和研究机构、地方财政厅局和研究机构、高等财经院校等77个理事单位的近300名代表参加了会议。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 大会选举产生了由287名理事组成的中国财政学会第八届理事会，选举财政部长谢旭人为中国财政学会第八届理事会会长。中国人民大学财政金融学院院长郭庆旺教授当选为副会长，朱青教授当选为常务理事，岳树民教授、刘晓路副教授、贾俊雪副教授当选为理事。 </p>
<p>　　中国财政学会是在民政部登记注册、由财政部主管的国家一级群众性社会学术团体。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
