{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}外国语院第十三届创新杯参赛作品初审结果公布{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2011-03-28 08:37:06{/dede:field}
{dede:field name='body'}<p>　　3月23日，外国语院第十三届创新杯参赛作品初审结果公布，经过学院评审委员会初审，16组参赛作品脱颖而出，将代表学院参加学校的评选，与其他院系的作品一决高下。最终结果将于5月初在人大青年网上公布。</p>
<p>　　&ldquo;创新杯&rdquo;中国人民大学学生课外学术论文及科技作品竞赛是由学校团委、学生会、研究生会主办，在学生处、教务处、研究生院支持下开展的大学生课外学术科技活动中一项具有导向性、示范性和群众性的竞赛活动，至今已成功举办十二届。</p>
<p>　　外国语院历来重视培养学生的创新能力和实践能力，在院领导的大力支持和鼓励下，&ldquo;创新杯&rdquo;学生课外学术科技作品竞赛得到了学生们的广泛响应和积极参与。在此平台上，同学们的创新意识和调研能力都得到了增强。</p>
<p>　　（编辑：苏璇）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
