<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","社会与人口学院举行年度评选盛典",89,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","李龙",200,243);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-12-25 04:28:21",245,304);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月22日，社会与人口学院年度盛典评选圆满举行，共评出&ldquo;创新奖&rdquo;&ldquo; 特殊贡献奖&rdquo;&ldquo;学术奖&rdquo;等十个奖项。社会与人口学院院长翟振武教授、院党委书记郭星华教授、院党委副书记段成荣教授、院党委副书记张茹老师，社会工作系系主任隋玉杰副教授，院团委书记唐颖老师等院领导与教职工、特邀嘉宾和学生齐聚逸夫会议中心第一报告厅，共同见证了各奖项的出庐。这些奖项是对社会与人口学院一年以来的突出团体、活动和事迹的肯定。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年社会与人口学院首创的复合型人才培养体系&mdash;&mdash;&ldquo;优质成长计划&rdquo;正式开始运行，针对不同年级学生的需求，经过社会学、心理学分析，为学生培养制定了详细的计划，与此相配套的各类活动顺利举行，如第二届&ldquo;歌之翼&rdquo;校园红歌大赛、&ldquo;青春&bull;祖国红色诗歌朗诵会&rdquo;等。同时，承办了国际社会学学会&ldquo;社会分层与流动研究委员会&rdquo;2009年年会，联合国教科文组织&ldquo;给妇女一个没有暴力的世界&rdquo;反对家庭暴力学术研讨会等一系列国际学术活动。</p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100622/z2kkzlknkhzkhmf-2bhbm.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次年度评选盛典在对社会与人口学院过去一年所取得成绩的回顾与总结中圆满结束。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：焦文雅）</p>",306,1649);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100622/z2kkzlknkhzkhmf-2bhbm_lit.jpg",1651,1743);
$z[7][4]['name']="litpic";

?>