<?php
$z[0]=Array("sppage","",0,41);
$z[0][4]['sptype']="full";
$z[1]=Array("previewurl","http://news1.ruc.edu.cn/102392/72514.html",43,119);
$z[2]=Array("keywordtrim","",121,158);
$z[3]=Array("descriptiontrim","",160,205);
$z[4]=Array("item","\r\n   {dede:match}<td width=\"90%\" align=\"center\" style=\"FONT-WEIGHT: bold; padding-top:20px; FONT-SIZE: 12pt; COLOR: #ff0000; LINE-HEIGHT: 28pt\" ><div>[内容]</div></td>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",207,496);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",498,638);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}<tr><td width=\"90%\" colSpan=2 align=\"center\">作者：[内容]</td>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",640,842);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}<tr><td width=\"90%\" align=\"center\" style=\"FONT-SIZE: 7pt; COLOR: #999999; FONT-FAMILY: Verdana\"><div>([内容])</div></td>{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",844,1124);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<tr><td width=\"90%\" align=\"left\" valign=\"top\" style=\"PADDING-RIGHT: 20px; PADDING-LEFT: 20px;PADDING-BOTTOM: 20px;FONT-SIZE: 10.5pt; LINE-HEIGHT: 22px; TEXT-DECORATION: none\">[内容]</td>\r\n	</tr>\r\n<tr><td><img src=\"http://images.ruc.edu.cn/templates/{/dede:match}\r\n   {dede:trim replace=\"<p>\"}<p>（编辑：(.*)）<br />{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",1126,1575);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>