{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2010年诺贝尔经济学奖得主克里斯托弗教授为公管师生作专题演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-03-23 09:45:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月19日下午，应公共管理学院邀请，2010年诺贝尔经济学奖获得者、伦敦经济学院教授克里斯托弗&bull;皮萨里德斯 （Christopher A. Pissarides）专门为公共管理学院师生做了一场题为&ldquo;福利政策与工作时间的分配：税收、社会补贴与工作时间分配&rdquo; 的专题演讲。 </p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2bhlyfnnf-lbmmz.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 克里斯托弗&bull;皮萨里德斯教授基于自己的一项长达五年多的研究课题，分析了政府的税收政策对于一个国家的劳动者在几种不同部门之间的工作时间分配情况所产生的影响，尤其是在卫生保健、社会工作部门内部以及其他服务部门内部，税收政策是如何影响家庭生产和市场购买两种不同服务提供方式之间的替代情况。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演讲结束后，克里斯托弗教授热情洋溢地回答了部分与会者提出的问题。</p>
<p align="center"><img alt="" width="500" height="333" src="/uploads/allimg/c110419/zlflzn2bhhhh2yf-h2nnz.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，董克用院长代表公共管理学院向克里斯托弗教授颁发了此次演讲的纪念相框。演讲由刘昕教授主持。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/74785.html">【相关链接】&ldquo;中国政府债务管理与资产价格风险&rdquo;研讨会成功举办</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2bhlyfnnf-lbmmz_lit.jpg{/dede:field}
