{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学环境学院团委书记王炜入围“2009全国高校辅导员年度人物评选”候选人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2010-04-06 09:50:59{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由教育部思想政治工作司指导，全国高校辅导员工作研究会、中国教育报、中国教育电视台共同主办，新华网提供独家网络支持的&ldquo;2009年度全国高校优秀辅导员&rdquo;评选活动第一阶段评选告一段落，200名入围者名单已于4月1日由新华网向社会公布。中国人民大学环境学院团委书记王炜同志作为中国人民大学唯一候选人顺利入围。 </p>
<p>　　王炜在600多位参评优秀辅导员中脱颖而出，入围200强。在担任中国人民大学环境学院团委书记期间，他以满腔的热情和充沛的精力积极投入到学生工作中，秉承&ldquo;学校、学院、学生、学风&rdquo;互动发展的工作理念，关注广大学生的成长，关心他们的生活，特别在北京奥运会、残奥会，以及建国六十周年群众游行等工作中表现突出，赢得各项荣誉。 </p>
<p>　　此次评选活动于2009年12月9日启动，由教育部思想政治工作司指导，全国高校辅导员工作研究会、中国教育报举办，旨在宣传表彰长期以来，特别是2009年度在为人师表、爱岗敬业、无私奉献等方面有突出表现的优秀辅导员。各地高校踊跃参与，共有653位辅导员获得推荐参加评选。</p>
<p>　　相关链接：　　</p>
<p>　　<a href="http://www.xinhuanet.com/edu/fdy.htm">新华网&ldquo;2009全国高校辅导员年度人物评选&rdquo;主题页面</a></p>
<p>　<a href="http://news.xinhuanet.com/edu/2010-03/28/content_13264643.htm">　王炜老师事迹</a></p>
<p>　　（编辑：苗育婧）</p>
<p>&nbsp;</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
