{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}澳大利亚精算学会主席一行访问统计学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-10-01 11:01:39{/dede:field}
{dede:field name='body'}<P>&nbsp;&nbsp;&nbsp; 9月26日下午，澳大利亚精算学会主席Martin Stevenson先生一行应邀访问了统计学院，与统计学院精算专业方向的教师就国际和中国精算教育等方面的问题进行了交流。之后，Martin先生为统计学院的师生做了题为“21世纪老年人收入支柱” (Old age income support in the 21st century) 的学术报告。<BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
