{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院魏娜教授当选北京志愿服务发展研究会副会长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 04:48:30{/dede:field}
{dede:field name='body'}<p>　　4月9日，北京志愿服务发展研究会第一次会员大会在北京奥运大厦召开。来自中国社会科学院、北京大学、中国青年政治学院、国家行政学院等高校和科研机构的五十余位专家学者作为会员参加了会议。大会选举产生了第一届理事会与会长、副会长。公共管理学院行政管理学系魏娜教授当选为研究会副会长。 </p>
<p>　　北京志愿服务发展研究会是全国第一家专业从事志愿服务研究的社会团体，由共青团北京市委作为业务主管单位。研究会的成立旨在广泛联系社会各界研究力量，深入推动志愿服务学术研究成果的固化、转化及推广工作，为政府决策提供科学的理论依据，为志愿服务事业发展和社会建设提供有力的智力支持。 </p>
<p>　　
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
