{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}财政金融学院多位教授在“学科高被引作者”指数中名列前茅{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}财政金融学院{/dede:field}
{dede:field name='pubdate'}2010-10-14 05:19:58{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据最近出版的《中国期刊高被引指数》，在&ldquo;2009年学科高被引作者&rdquo;的&ldquo;经济学&rdquo;类中，财政金融学院郭庆旺教授位列第一，张杰教授位居第九，在&ldquo;经济学&rdquo;期刊论文总被引频次的前十名作者中我院教授占20%。在&ldquo;2009年学科高被引作者&rdquo;的&ldquo;财政金融&rdquo;类中，安体富教授、张杰教授、陈雨露教授分别位列第一、第四和第十，在&ldquo;财政金融&rdquo;期刊论文总被引频次的前十名作者中学院教授占30%。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《中国期刊高被引指数》每年由科学技术文献出版社出版。新近出版的指数对2009年的&ldquo;高被引期刊&rdquo;、&ldquo;高被引机构&rdquo;、&ldquo;高被引作者&rdquo;等进行了具体排名。该书由中国科学技术信息研究所、万方数据股份有限公司联合编制，并被列为&ldquo;国家科技支撑计划项目&rdquo;。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：周庆誉） <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
