<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","财政金融学院多位教授在“学科高被引作者”指数中名列前茅",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","财政金融学院",224,275);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-10-14 05:19:58",277,336);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据最近出版的《中国期刊高被引指数》，在&ldquo;2009年学科高被引作者&rdquo;的&ldquo;经济学&rdquo;类中，财政金融学院郭庆旺教授位列第一，张杰教授位居第九，在&ldquo;经济学&rdquo;期刊论文总被引频次的前十名作者中我院教授占20%。在&ldquo;2009年学科高被引作者&rdquo;的&ldquo;财政金融&rdquo;类中，安体富教授、张杰教授、陈雨露教授分别位列第一、第四和第十，在&ldquo;财政金融&rdquo;期刊论文总被引频次的前十名作者中学院教授占30%。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《中国期刊高被引指数》每年由科学技术文献出版社出版。新近出版的指数对2009年的&ldquo;高被引期刊&rdquo;、&ldquo;高被引机构&rdquo;、&ldquo;高被引作者&rdquo;等进行了具体排名。该书由中国科学技术信息研究所、万方数据股份有限公司联合编制，并被列为&ldquo;国家科技支撑计划项目&rdquo;。&nbsp;<br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：周庆誉） <br />",338,1261);
$z[6][4]['name']="body";
$z[7]=Array("field","",1263,1302);
$z[7][4]['name']="litpic";

?>