{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院举行第五届“《时尚》奖学金”颁奖大会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-11-19 03:02:45{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月11日，第五届《时尚》奖学金颁奖大会暨时尚传媒集团校园宣讲招聘会在逸夫会议中心第二会议室举行。新闻学院常务副院长倪宁、《时尚&bull;COSMOPOLITAN》执行出版人兼主编徐巍、时尚传媒集团人力资源总监刘蓉及《男性健康》资深编辑杨南出席了本次大会，学院党委副书记罗建晖主持了颁奖仪式。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbmffylffbnf-ylhyh.jpg" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 颁奖会现场，倪宁常务副院长和徐巍主编共同为20位获奖的同学颁发了&ldquo;《时尚》奖学金&rdquo;荣誉证书，其中一等奖5名，二等奖15名。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 倪宁常务副院长在致辞中首先表达了对时尚传媒集团的感谢以及对获奖学生的祝贺。他谈到，&ldquo;《时尚》奖学金&rdquo;的设立有利于激励新闻学院同学更好的学习和自我发展，同学们要面对当今科技发展，新媒体不断涌现、媒介形态不断变化的挑战，首先要打好基础，以不变应万变，以一种永恒的、真实的、可应对各种挑战的真才实学去适应变化。他同时也要求同学们要努力学习，以实际行动去回馈社会。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 徐巍主编在致辞中表示，设立奖学金不仅是为了奖励那些学习成绩优秀的学生，更是为了能够把中国本土时尚期刊杂志多年来的一些办刊经验与大学生进行分享和交流。希望同学们多多关注时尚传媒领域的发展，有机会也可以投身到这个行业中实现自我价值。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;《时尚》奖学金&rdquo;获得者，07级新闻学林雪同学在会上代表获奖同学发言。她感谢时尚传媒集团开创了时尚类媒体在高校设立奖学金的先河。她说：&ldquo;&lsquo;《时尚》&rsquo;奖学金对我来说不仅是物质上的资助，更是精神上的肯定，&lsquo;《时尚》&rsquo;奖学金是对我们一年来辛苦付出的褒奖，它让我们在前行的道路上走得更加自信、稳健，也让我们在不断追求卓越的过程中更有动力。&rdquo;</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbmffyllhlnf-khhmf.jpg" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 颁奖结束后，倪宁常务副院长和徐巍主编代表新闻学院与时尚传媒集团互赠了礼物。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在随后进行的时尚传媒集团招聘宣讲会上，徐巍主编及杨南编辑就自己在时尚传媒的从业经历给予同学们许多求职建议。人力资源总监刘蓉最后介绍了时尚集团的福利待遇及应届生招聘计划。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;《时尚》奖学金&rdquo;由时尚传媒集团与中国人民大学于2006年联合设立，目的是奖励新闻学院品学兼优、关注平面媒体、热爱时尚类期刊行业的同学，至今已历五届。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmffylffbnf-ylhyh_lit.jpg{/dede:field}
