<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","统计学院王晓军教授应邀出席日本东京“养老金与社会保障精算管理”学术研讨会并作主题发言",89,211);
$z[2][4]['name']="title";
$z[3]=Array("field","",213,252);
$z[3][4]['name']="writer";
$z[4]=Array("field","统计学院",254,301);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-10-12 03:27:30",303,362);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><span class=\"text\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应国际精算协会养老金与社会保障委员会的邀请，统计学院王晓军教授应邀出席了于10月4日-6日在日本东京举行的主题为&ldquo;养老金与社会保障精算管理&rdquo;的学术研讨会，她在大会上做了题为&ldquo;中国养老金制度面临的挑战&rdquo;的主题发言，同时，作为主要嘉宾参加了会议的主旨专题讨论。</span></p>\r\n<p><span class=\"text\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>&nbsp;</p>",364,832);
$z[6][4]['name']="body";
$z[7]=Array("field","",834,873);
$z[7][4]['name']="litpic";

?>