{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}统计学院王晓军教授应邀出席日本东京“养老金与社会保障精算管理”学术研讨会并作主题发言{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2009-10-12 03:27:30{/dede:field}
{dede:field name='body'}<p><span class="text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应国际精算协会养老金与社会保障委员会的邀请，统计学院王晓军教授应邀出席了于10月4日-6日在日本东京举行的主题为&ldquo;养老金与社会保障精算管理&rdquo;的学术研讨会，她在大会上做了题为&ldquo;中国养老金制度面临的挑战&rdquo;的主题发言，同时，作为主要嘉宾参加了会议的主旨专题讨论。</span></p>
<p><span class="text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>&nbsp;</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
