{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学获2009年“关爱女孩”行动“优秀组织奖”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2010-06-23 09:03:00{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，&ldquo;2009年&lsquo;关爱女孩&rsquo;青年志愿者行动总结表彰会暨2010年暑期调研工作启动会&rdquo;在国家和人口计划生育委员会举行，国家人口计生委直属机关党委专职副书记张旭光，国家人口计生委宣教司副司长施春景，社会与人口学院院长、中国人口学会常务副会长翟振武教授等出席了会议，社会与人口学院团委常务副书记冯启娜和人民大学的志愿者参加了会议。中国人民大学志愿们的调研获得多个奖项，以出色的表现为学校赢得了&ldquo;优秀组织奖&rdquo;的殊荣。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议伊始，由国家人口计生委直属机关团委书记胡强强作2009年志愿者工作总结。他回顾了这一年来&ldquo;关爱女孩&rdquo;志愿者开展活动及调研的过程，对志愿者们的表现给予了高度评价。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在志愿者发言环节中，中国人民大学志愿者、社会与人口学院07级学生张浣珺与在场老师和同学分享了自己所在团队在江西九江的调研经历和感想，并希望通过&ldquo;关爱女孩&rdquo;这个项目让更多的人参与进来。参加发言的还有北京中医药大学的志愿者团队。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 社会与人口学院院长翟振武教授对本次调研的获奖作品进行点评。他充分肯定了获奖论文的专业水平和社会价值，他同时强调，同学们在选题的时候只有选择好合适的切入点进行调研，才能让调研结果更加具有社会价值。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 接下来施春景副司长发表讲话，张旭光副司长宣布2010年&ldquo;关爱女孩&rdquo;青年志愿者行动暑期调研正式启动。随后，翟振武教授就调研中应注意的问题做了简短的讲授，并希望今年的志愿者们能够取得更加优异的成绩。会议在热闹的讨论中结束。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据了解，&ldquo;关爱女孩&rdquo;行动是由国家人口和计划生育委员会发起的，旨在促进和宣传男女平等，减少出生性别选择、关心女孩成长，培养女儿成才，更好地实现科学计划生育的大型志愿者活动，自2002年启动以来，至今已历8届，中国人民大学的志愿者在往届行动中均有不俗的表现。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 附：中国人民大学志愿者获奖情况： </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一等奖： 《社会性别不平等：从乡风民俗看男孩偏好》（张浣珺、赵梦晗、王欢欢、商成果） </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 二等奖： 《建国以来中国女性婚育模式变化》（钱岳、靳永爱） 、《农村妇女婚姻质量与婚姻问题研究》（任慧、江梅、张现苓、王淼）</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：张利英）&nbsp;<br />
&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
