{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“新中国外国法制史学科发展60年研讨会暨林榕年教授从教60年庆典”隆重举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/法学院 崔璨 图/新闻中心 罗豫伟{/dede:field}
{dede:field name='pubdate'}2011-04-11 04:59:39{/dede:field}
{dede:field name='body'}<p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c110418/zlflzzhbkzfbnbf-zhlhlf.jpg" />&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;4月9日，&ldquo;新中国外国法制史学科发展60年研讨会暨林榕年教授从教60年庆典&rdquo;在中国人民大学汇贤大厦401会议室隆重举行。来自全国外国法制史研究会的会长、副会长以及常务理事，北京大学、清华大学、华东政法大学、中国政法大学、西北政法大学、复旦大学、中南财经政法大学、厦门大学、湘潭大学、华中科技大学等全国高校的专家学者以及林榕年教授的历届学生等近百人参加了会议。来自新华社、人民日报等媒体的记者参与报道此会。 <br />
</p>
<p align="center">&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c110418/zlflzzhbkzhzmf-zbhf2b.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林榕年教授是新中国外国法制史学科的奠基人，曾任中国人民大学法律系法制史教研室主任。1950年在苏联专家的指导下，林榕年教授在全国最早开创了外国法制史学科，成为全国外国法制史课程第一位主讲教师，并使中国人民大学成为这门学科最早的教学与研究基地。六十年来，林榕年教授一直从事外国法制史的教学和研究工作，为新中国培养了大量外国法制史教学科研人才和法律事务人才，为外国法制史学科的发展和我国的法学教育事业做出了重要贡献。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式由中国人民大学法律文化研究中心主任、全国外国法制史研究会副会长叶秋华教授主持。华东政法大学校长、全国外国法制史研究会会长何勤华教授，中国人民大学党委书记程天权教授，中国人民大学党委副书记兼副校长王利明教授，中国人民大学法学院院长韩大元教授等与会代表先后致辞，对林榕年教授从教60年表示衷心的祝贺，对林榕年教授60年来对外国法制史学科建设和发展所做的贡献给予高度赞赏，同时对中国人民大学作为外国法制史学科的开创与研究的重地在该学科所取得的成就表示充分肯定。&nbsp; 中国人民大学校长纪宝成教授也发来贺信向林榕年教授从教60年表示祝贺，对林教授在外国法制史学科建设和人才培养等方面所做的贡献表示肯定。 </p>
<p align="center">　<img alt="" src="/uploads/allimg/c110418/zlflzzhbkzhynnf-zyl2yn.jpg" /></p>
<p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图为程天权书记致辞</p>
<p align="center">　<img alt="" src="/uploads/allimg/c110418/zlflzzhbkzb2hf-zkzbkf.jpg" /></p>
<p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图为王利明副书记致辞</p>
<p align="center">　<img alt="" src="/uploads/allimg/c110418/zlflzzhbk2hh2mf-znkhnh.jpg" /></p>
<p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图为韩大元院长致辞</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与会代表向林榕年教授送上象征健康吉祥的鲜花等礼物。&nbsp;</p>
<p align="center">&nbsp; <img alt="" src="/uploads/allimg/c110418/zlflzzhbk2hmkhf-zmkl2y.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 在简短而隆重的开幕式之后，会议转入学术研讨。与会代表围绕&ldquo;外国法制史学科回顾与展望&rdquo;和&ldquo;外国法制史学研究的现代价值&rdquo;两个议题，对新中国外国法制史学科60年发展的风雨历程进行了回顾和展望，畅谈了林榕年教授从教60年来对外国法制史学科做出的贡献。北京大学外国法制史学科资深学者由嵘教授，著名中青年学者华东政法大学校长、全国外国法制史研究会会长何勤华教授，中国艺术研究院中国文化研究所副所长、洪范法律与经济研究所所长梁治平教授，厦门大学徐国栋教授，北京大学贺卫方教授等都在会上做了发言。</p>
<p align="center">&nbsp;&nbsp;&nbsp;<img alt="" src="/uploads/allimg/c110418/zlflzzhbklfl2mf-2fllyl.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会后，与会嘉宾与林榕年教授合影留念。 </p>
<p align="center">&nbsp;&nbsp; <img alt="" src="/uploads/allimg/c110418/zlflzzhbklyffnf-2zkkmm.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑&nbsp; 燕燕&nbsp; 王强）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbkzfbnbf-zhlhlf_lit.jpg{/dede:field}
