{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}跨文化中德青年对话：德国“外交协会青年论坛”代表团访问外国语学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2011-04-18 02:55:37{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月13日下午，来自德国&ldquo;外交协会青年论坛&rdquo;代表团一行29人访问了中国人民大学外国语学院，并与德语专业的同学举行了一场生动热烈的&ldquo;跨文化中德青年对话&rdquo;活动。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此次活动包括两大部分内容。首先，德语专业孟虹副教授为同学们做了关于&ldquo;青年精英在中国社会的作用&rdquo;的专题报告；随后，中德两国同学分别就&ldquo;青年知识精英&rdquo;、&ldquo;青年政治精英&rdquo;、&ldquo;青年经济精英&rdquo;和&ldquo;青年文化精英&rdquo;四个主题进行了报告和讨论。活动由德语专业研究生于南和外国语学院学生会主席璩传奇主持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来访的德国代表团成员主要为慕尼黑各大学的政治、法律、经济系学生和年轻毕业生，他们首先进行了有关德国各类精英的介绍。外国语学院德语系三年级的同学结合本学期德语国家文化课课程分为四组，以丰富多彩的图片和文字向德国青年介绍了我国高等教育和精英人才培养机制、年轻市长和大学生村官及大学学生会干部、青年企业家、青年艺术家等情况，为来自德国的年轻一代展示了中国青年精英活跃于社会各领域的生动事例。期间，双方同学就感兴趣的问题互相提问，展开热烈讨论。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;此次对话活动为中德两国青年提供了一个加深了解、结实新友的良好平台。参加此次交流活动的还有德语系部分二年级学生。同学们纷纷表示，对话有助于大家更直接地了解德国国情，同时也为大家提供了一次重要的跨文化德语交流和展示机会。同学们高水平的报告及良好的德文表达能力令德国学生们感到惊讶。活动后，两国同学交流联系方式，青年人之间结下了良好的友谊。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;外交协会青年论坛&rdquo;（Junges Forum）成立于2005年，隶属于德国外交协会（GFA），该创建于半个世纪前，位于德国慕尼黑。论坛成员均为关心国际事务的年轻大学生和高校毕业生。此次代表团是应中国教育国际交流协会的邀请前来北京访问。在京期间，代表团还先后访问了外交部欧洲司德国处、中央电视台、国家知识产权局及部分在京德国驻华机构等。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陪同代表团一行来人民大学访问的还有中国教育国际交流协会欧洲事务处主任助理孙洪墨女士。此次活动得到了外国语学院领导的关心和大力支持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
