{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本一桥大学副校长田近荣治教授访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-02-25 08:42:39{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月5日，日本一桥大学副校长田近荣治教授、校长助理前原康宏教授、北京事务所所长志波干雄一行访问经济学院。经济学院杨瑞龙院长会见了日本客人，双方就即将于今年4月在日本东京由两校联合举办的的&ldquo;中国人民大学&mdash;日本一桥大学第一届亚洲政策论坛&rdquo;举行第二轮磋商。双方就若干重大问题取得了一致意见，并就下一步合作事宜做出了分工。经济学院关权教授、郑新业副教授陪同会见。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
