{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}国务院研究室向经济学院致新春感谢信{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-02-01 10:13:54{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，国务院研究室向经济学院副院长、经济研究所联席副所长刘元春教授及经济研究所全体研究人员发来新春感谢信，感谢刘元春教授及经济研究所在2009年提供了许多重要的观点和建议。感谢信中说，刘元春同志：一年来，您和您的团队为我们提供了许多重要观点和建议，对我们的工作给予了积极的支持和帮助，希望继续密切合作，积极为政府决策献计献策。值此新年来临之际，谨向您及团队表示衷心的感谢和良好的祝愿！ <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 人民大学经济研究所举办的&ldquo;中国宏观经济论坛&rdquo;所发布的宏观经济形势分析与预测报告，多次被国务院研究室采纳并上报党中央、国务院，得到了党和国家领导人的肯定和重视。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
