{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}马俊杰副书记出席北京大学生艺术团工作总结研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}校团委{/dede:field}
{dede:field name='pubdate'}2010-12-23 04:47:07{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月23日，北京大学生艺术团工作总结研讨会在九华山庄隆重举行。中国人民大学党委副书记马俊杰出席会议并讲话，校团委相关负责人陪同出席。市教委副主任郑萼、市教委体育美育处相关负责人以及获奖高校代表近百人参加了会议。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 马俊杰副书记结合人民大学学生艺术团的具体情况，从&ldquo;轻与重&rdquo;、&ldquo;多与少&rdquo;、&ldquo;内与外&rdquo;、&ldquo;上与下&rdquo;四个方面向与会各高校阐述了艺术教育的育人作用、思想引领功能以及艺术活动覆盖性等问题，并表示希望加强和各高校之间的合作交流，实现优势互补。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据了解，在刚刚结束的第三届北京大学生艺术展演比赛中，我校学生艺术团获得声乐专场普通A组合唱比赛一等奖、小合唱比赛一等奖、器乐专场普通A组西洋管弦乐比赛一等奖、民族管弦乐比赛一等奖、舞蹈专场普通A组舞蹈比赛一等奖、戏剧专场普通A组京剧比赛一等奖，人民大学获得优秀组织奖，取得历史最好成绩，是北京各高校里参赛项目最多，获奖项目最多的学校。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
