{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国著名诗人、剧作家James Ragan在人民大学做学术报告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/校报学生记者 孙雅晴  图/网络新闻社 杨依军{/dede:field}
{dede:field name='pubdate'}2008-10-18 11:50:20{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15日晚，应外国语学院英语专业副教授李华的邀请，美国著名诗人、剧作家James Ragan来到中国人民大学，在逸夫会议中心第二报告厅做了题为&ldquo;戏剧结构的艺术&rdquo;的报告。 </p>
<p align="center"><img height="334" src="/uploads/allimg/c100621/z2kkzlbnyfymb2f-zkk2b.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ragan教授从自己的写作经历讲起，生动具体地为听众描绘了自己撰写《In the talking hours》《Womb-Weary》等作品的心路，阐述了他对剧作、对电影创作理念的理解。他强调，文学艺术创作是为了传递自己的声音，我们应该用世界性的视角思考问题、分析问题，用我们的力量去拉近国家与国家的距离，消除国家之间的误解，推倒不同社会文明之间的壁垒，让整个世界融为一体。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在Ragan教授的报告之后，外国语学院英语专业的学生上台表演了James Ragan的艺术喜剧作品《Ardor Under the Arbor》，学生们幽默的语言、精彩的表演，赢得了现场观众的一阵又一阵的掌声。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 表演结束后，James Ragan教授与在场的老师和学生进行了自由交流。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; James Ragan博士是南加州大学写作专业前主任，美国当代著名诗人、剧作家、文学批评家和电影编剧家。他的诗作被译为12种语言，其中《Womb-Weary》被提名为普利策奖。Ragan博士早在1988年便受邀来华采访我国剧作家曹禺，交流中美戏剧写作。 </p>
<p align="center"><img height="334" src="/uploads/allimg/c100621/z2kkzlbnyzh2mbf-2yhny.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 此次讲座是由外国语学院英语专业承办的，目的是让教师们了解英语文学创作学科的生命力和发展前景，促进该学科在人民大学的发展；同时也让学生们近距离感受美国诗人、剧作家的风采，提高文学文化素养。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 外国语学院英语专业陈世丹教授、刁克利教授等出席了学术报告会。</p>
<p>（编辑：周卓斌）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbnyfymb2f-zkk2b_lit.jpg{/dede:field}
