{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院刘瑞教授接受土尔其国家电视台记者采访{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-01-13 02:51:48{/dede:field}
{dede:field name='body'}<p>　　1月5日，经济学院副院长刘瑞教授接受了土尔其国家电视台驻北京站记者热娜的采访，就中国2011年提高贫困线标准以及缩小贫富差距等回答了相关问题，对中国在十二五规划中提出的缩小收入分配差距政策做出了评价。中国国内的规划和发展日益引起国际媒体的关注，显示中国经济对世界经济的影响力日益增强。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
