{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院方汉奇教授、王润泽副教授参加“成舍我与民国新闻史”国际学术研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2011-04-01 09:36:42{/dede:field}
{dede:field name='body'}<p>　　3月26日，&ldquo;成舍我与民国新闻史&rdquo;国际学术研讨会在北京大学举行。中国新闻史学会名誉会长、人民大学新闻学院方汉奇教授参加研讨会并在开幕式上致辞，学院新闻史论教学研究部副主任王润泽副教授在研讨会上作了演讲，并同与会者进行了交流和探讨。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzbkbfynyf-zlznn.jpg" alt="" /></p>
<p>　　方汉奇教授回顾了成舍我早年从事新闻活动的情况以及和北京大学的渊源。他特别指出，成舍我先生 在中国新闻史上占据着重要的地位，为新闻事业付出了一生的心血：他办报时间最长，创办的报刊最多，从事新闻教育时间最长，他所主持的《立报》曾创下旧中国 报纸发行量之最。方汉奇高度肯定了研讨会的意义，并希望在此基础上推进民国新闻史的研究广度和深度。</p>
<p>　　在研讨环节，新闻学院新闻史论教学研究部副主任王润泽副教授作了演讲，并与来自台湾世新大学、暨南大学、华中科技大学、清华大学、中国传媒大学教授、南开大学的专家学者进行了交流和探讨。今年适逢成舍我先生逝世20周年，与会者围绕著名报人成舍我长达七十余年的新闻生涯，就成舍我在办报、兴学、问政三个方面的探索和成就进行了深入、广泛的探讨。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzbkbhmhnf-2mfyy.jpg" alt="" /></p>
<p>　　本次研讨会由中国新闻史学会、台湾世新大学舍我纪念馆和美国柏克莱加州大学东亚研究院共同主办。</p>
<p>　　（编辑：苏璇）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzbkbfynyf-zlznn_lit.jpg{/dede:field}
