<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院杨志教授参加北京市“群众心目中的好党员”朝阳、海淀专场报告会",89,195);
$z[2][4]['name']="title";
$z[3]=Array("field","",197,236);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",238,285);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-16 05:32:53",287,346);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2010年11月9日和10日，北京市&ldquo;群众心目中的好党员&rdquo;先进事迹巡回宣讲团分别在朝阳区和海淀区举行专场报告会。来自各区直系统所属各机关单位的党委、党总支、党支部书记、委员和党员代表共500余人参加了报告会。作为五位宣讲团成员之一，杨志教授作了两场先进事迹报告。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨志教授用平凡而鲜活的语言讲述了自己身为共产党员的体验与感悟，以&ldquo;真情&bull;真想&bull;真干&rdquo;展现了新时期共产党员的风采，赢得了在场党员的感动与尊重。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 目前，&ldquo;群众心目中的好党员&rdquo;先进事迹宣讲团已经陆续进行了3场宣讲活动，接下来还将陆续奔赴各区县、各系统进行十余场巡回宣讲活动。 </p>\r\n<p>\r\n</p>",348,1104);
$z[6][4]['name']="body";
$z[7]=Array("field","",1106,1145);
$z[7][4]['name']="litpic";

?>