{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学2008英语风采大赛落幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院新闻中心{/dede:field}
{dede:field name='pubdate'}2008-11-27 04:08:58{/dede:field}
{dede:field name='body'}<p>　　11月26日晚，中国人民大学2008年英语风采大赛决赛在逸夫会议中心第一报告厅举行。社会与人口学院王梦真获得一等奖，李惠兰、王江川获二等奖，黄芃、杨映雪、应晓妮、郝汉、吴健毓获三等奖。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100621/z2kkzlbnk2bhzhf-zhmyf.jpg" /></p>
<p>　　参加决赛的8名选手是从全校100多名参赛选手中决出的。本次比赛覆盖了学校23个学院，并有留学生参与，其中二等奖获得者李惠兰即为韩国留学生。</p>
<p>　　决赛分为DV自我展示、主题演讲、看图即兴演讲、问答、才艺展示环节、亲友团互动等环节。选手们通过DV介绍自己的所见所闻所思；作以&quot;Making my voice heard&quot;为话题的3分钟演讲；充分发挥想象力，看图说话；回答评委问题；接受5个脑筋急转弯似的问题的挑战，感叹英语的博大精深；才艺展示中各显神通，配音、演唱等精彩调动了现场气氛，场下掌声不断，喝彩迭起。</p>
<p>　　本次比赛评委之一、外国语学院李华老师赛后表示，参赛选手准备充分，表现投入，他们精彩的展示为观众献上了一场视听盛宴。同时，李老师建议选手们在以后的比赛中注意介绍自己的搭档，增强主体意识。</p>
<p>　　&ldquo;感谢主办方和今晚与我同台比赛的同学，是你们给与了我鼓励，减轻了我的心理压力&rdquo;。 一等奖获得者王梦真的喜悦溢于言表，&ldquo;希望可以与每一位支持自己的人一起分享。&rdquo;她说。</p>
<p>　　本届英语风采大赛由外国语学院分团委主办，外国语学院青年志愿者协会承办。外国语学院谢江南副教授，杨敏副教授，李华副教授以及外籍专家Mr.Knowles担任评委。外国语学院负责人到场观看了比赛，并为获奖选手颁发获奖证书和奖品。</p>
<p>　　（编辑　徐静） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100621/z2kkzlbnk2bhzhf-zhmyf_lit.jpg{/dede:field}
