<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公共管理学院董克用院长、崔军副书记看望广东校友并参加校友代表座谈会",89,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",236,287);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-05 11:36:34",289,348);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月2-3日，公共管理学院董克用院长、崔军副书记赴广东东莞参加2010级MPA研究生复试，期间亲切看望了广州、东莞两地的公共管理学院校友并与校友代表举行座谈。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在校友代表座谈会上，董克用院长代表学院和在校师生向广大校友致以新年的祝福，通报了学院近年来的发展状况和取得的成绩以及未来的发展方向，并对广东校友会以及东莞分会的成立提出了希望和要求，同时热情邀请广大校友今年重返母校参加学院十周年院庆系列活动。与会的校友代表向学院领导汇报了校友会筹备工作的基本思路和相关情况，同时对学院的各项工作和今后的发展提出了建议和设想。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;\r\n</p>",350,1055);
$z[6][4]['name']="body";
$z[7]=Array("field","",1057,1096);
$z[7][4]['name']="litpic";

?>