<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","哲学院周濂副教授和温海明副教授寒假赴雅典参加元伦理学工作坊",89,185);
$z[2][4]['name']="title";
$z[3]=Array("field","",187,226);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",228,273);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-02-25 05:27:39",275,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>　　1月14日至30日，哲学院周濂副教授和温海明副教授赴希腊雅典参加&ldquo;伦理学基础（The Foundations of Morality）&rdquo;元伦理学工作坊。来自全国各高校和美国、香港的十多位具有海外博士学位和科研背景的青年学者参加研讨。 </p>\r\n<p align=\"center\">&nbsp;<img src=\"/uploads/allimg/c110419/zlflzn2yhk2mmf-z22zz.jpg\" alt=\"\" /></p>\r\n<p>　　为期半月的研讨过程中，两位美国教授详细主讲了当代元伦理学领域的各种前沿观点，参会的学者们积极认真地交流讨论。周濂副教授在工作坊上交流了论文&ldquo;Can Constructivism Solve The Euthyphro Dilemma? In Reply to Shafer-Landau&rdquo;；温海明副教授在工作坊上交流了论文《好的道德理由是内在地还是外在地导致道德行为：王阳明论道德判断与动机 Emotional Internalism or externalism: Wang Yang Ming on moral judgment and motivation》。</p>\r\n<p>　　元伦理学工作坊是美国Templeton 基金会资助的关于中国哲学项目的一部分，由美国加尔文学院（Calvin College）组织。</p>\r\n<p>　　（编辑：易晨）&nbsp;</p>",336,1278);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110419/zlflzn2yhk2mmf-z22zz_lit.jpg",1280,1371);
$z[7][4]['name']="litpic";

?>