<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院李义平教授在北京市教委中心学习组及多个高校党委中心学习组作辅导报告",89,201);
$z[2][4]['name']="title";
$z[3]=Array("field","",203,242);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",244,291);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-31 11:28:08",293,352);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中共十七届五中全会召开之后，人民大学经济学院教授李义平立即应邀在人民网、中国经济网作了访谈和视频，解读相关文件精神。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随之李义平教授应邀在中共北京市教委中心学习组做了十七届五中全会和十二五规划建议的辅导报告。市委教育工委副书记刘健主持报告会，在市委教育工委中心学习组的辅导报告受到一致好评。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 另外，北京市教委新任副书记、副校长的学习班，北京高校主管宣传的副书记和宣传部长学习班，老干部学习班，哲学社会科学副教授学习班，北京林业大学，北京联合大学，首都体育学院的中心学习组也分别邀请李义平教授作了辅导报告。其中这三所大学的党委书记亲自主持了辅导报告会。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这期间，李义平教授还在北京市委党校司局级干部学习班，中央社会主义学院香港有关人士学习班，以及北京大学马克思主义学院举办的全国党校教师学习班作了相关辅导报告。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李义平教授的报告受到普遍好评，为人民大学赢得了荣誉。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />\r\n</p>",354,1484);
$z[6][4]['name']="body";
$z[7]=Array("field","",1486,1525);
$z[7][4]['name']="litpic";

?>