{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙、刘元春获2009年度国家社科基金重大项目资助{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由全国哲学社会科学规划办公室组织的2009年度国家社科基金重大项目招投标和评审工作日前圆满结束，由经济学院杨瑞龙教授担任首席专家的课题《扩大内需与稳定外需协调发展研究》和由经济学院刘元春教授担任首席专家的课题《保持经济平稳较快发展、调整经济结构与管理通胀预期的关系研究》中标并获得资助。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='pubdate'}1264391613{/dede:field}
{dede:field name='litpic'}{/dede:field}
