{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院室内乐演出小组访台获得圆满成功{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2011-05-10 10:41:12{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应台湾&ldquo;教育部&rdquo;邀请，4月26至30日，艺术学院教师室内乐演出小组由赵方副院长带队，参加了在台湾师范大学举行的音乐节活动。演出博得台湾音乐界、艺术教育界和师生们的盛赞，获得圆满成功。</p>
<p align="center"><img height="333" src="/uploads/allimg/c110725/zlzzbyzhymbnzkf-bl2f2.jpg" width="500" alt="" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在此期间，教师演出小组还对台湾辅仁大学、师范大学、东吴大学和台南大学等艺术院、系进行了访问，就进一步加强院系级学术交流等事项达成共识。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 访问期间，演出小组的老师还分别举办了大师班授课，受到了同学们的高度赞扬。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhymbnzkf-bl2f2_lit.jpg{/dede:field}
