<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","艺术学院室内乐演出小组访台获得圆满成功",89,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","作者：艺术学院",208,261);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-05-10 10:41:12",263,322);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应台湾&ldquo;教育部&rdquo;邀请，4月26至30日，艺术学院教师室内乐演出小组由赵方副院长带队，参加了在台湾师范大学举行的音乐节活动。演出博得台湾音乐界、艺术教育界和师生们的盛赞，获得圆满成功。</p>\r\n<p align=\"center\"><img height=\"333\" src=\"/uploads/allimg/c110725/zlzzbyzhymbnzkf-bl2f2.jpg\" width=\"500\" alt=\"\" />&nbsp;</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在此期间，教师演出小组还对台湾辅仁大学、师范大学、东吴大学和台南大学等艺术院、系进行了访问，就进一步加强院系级学术交流等事项达成共识。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 访问期间，演出小组的老师还分别举办了大师班授课，受到了同学们的高度赞扬。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）&nbsp;<br />\r\n<br />\r\n</p>",324,1110);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110725/zlzzbyzhymbnzkf-bl2f2_lit.jpg",1112,1204);
$z[7][4]['name']="litpic";

?>