{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院院长董克用教授率队参加第八届全国MPA论坛{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-12-03 04:41:10{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月27日至28日，公共管理学院院长董克用教授率MPA教育中心谢佳宏老师、MPA双证试点班研究生刘伯盈和何汇参加了第八届全国MPA论坛。本届论坛由重庆大学承办，得到了重庆市政府的高度重视和大力支持，来自全国88所MPA培养院校的268人参加论坛。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 作为全国MPA教育指导委员会委员，董克用院长受邀作了题为&ldquo;我国个人收入分配政策的思考&rdquo;的学术报告，全面阐释了改革开放以来我国个人收入增长情况，深入分析了个人收入差距扩大的五个根本原因，结合实际国情指出了当前相关政策调节的难度，最后给出了三大具体政策建议。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 另外，应主办方邀请，MPA双证试点班研究生何汇同学在分论坛进行了主题发言。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
