{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}台湾政治大学王文杰教授一行访问法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-22 09:06:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月21日，法学院韩大元院长、王轶副院长在明德法学楼206会议室会见了来访的中国台湾政治大学法学院的王文杰教授一行，双方就两院合作的相关事宜深入交换了相关意见并达成诸多共识。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fkzkbnzf-zlklf.jpg" alt="" /></p>
<p>&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩大元院长和王轶副院长对于王文杰教授一行的到来表示了热烈的欢迎。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王文杰教授代表方嘉麟院长邀请韩大元院长出席政治大学法学院的50周年院庆，韩大元院长欣然同意，说明两院的合作交流源远流长，人民大学法学院很希望能够进一步巩固和发展两院的合作与交流。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王文杰教授首先介绍了政治大学将于今年7月10日至16日开展的&ldquo;亚太法律精英营&rdquo;暑期项目，该项目汇聚两岸、新加坡、香港等地的法律精英，从学术到实务等方面均有所涉及，同时为参与这一项目的法学院学生提供体验台湾生活，与其他院校的学生同台竞技的机会。王文杰教授表示希望人民大学法学院的学生能够积极参与这一项目。韩大元院长也向王文杰教授介绍了人民大学的亚太法学院的筹办情况，说明这一项目开展之后，将与澳大利亚、日本、韩国以及东南亚地区其他国家的知名高校建立紧密的合作关系。韩院长说明也期望台湾政治大学法学院能够参与到这一项目之中。王文杰教授表示将进一步请示方嘉麟院长确定相关详情。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王文杰教授同时介绍了台湾地区《招收大陆地区研究生方式相关说明》的具体细节，并说明期望人民大学法学院的学生参与这一项目。这一项目中政治大学法学院有三个招收名额。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩大元院长、王轶副院长与王文杰教授就两院的联合培养硕士生项目交换了具体的意见，并就相关细节进行了细致地探讨，双方达成初步合作意愿，并拟于下一学期开展相关项目。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会见结束后，双方交换了纪念品并合影留念。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉 ) <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fkzkbnzf-zlklf_lit.jpg{/dede:field}
