{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}英国桑德兰大学教授Andrew Crisell应邀到新闻学院作主题演讲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-11-30 02:33:07{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月24日下午，英国桑德兰大学广播电视学者Andrew Crisell教授应邀来中国人民大学新闻学院与师生们进行交流。新闻学院广播电视系全体老师和广播电视新闻学、国际新闻专业同学参加了此次活动。</p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllk2khhyf-hnlzb.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在题为&ldquo;Popular and qualilty on news of BBC Radio&rdquo;的演讲中，Andrew Crisell教授从广播与电视、报纸的不同媒介特点出发，阐述了广播在当前媒介竞争中的特质。他特别指出，尽管电视是当前影响力巨大的媒介，但是画面也会带来很多&ldquo;冗余&rdquo;信息，有时甚至会分散人们接收主体信息的注意力。而广播在对信息的精确表达、特别是对&ldquo;不可见&rdquo;的抽象信息的表达方面具有独特优势。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 主题演讲之后，Andrew 教授就广播媒介如何维持受众注意力、如何适应新的媒介环境并吸引青年受众、公共广播系统与商业广播系统的关系等问题与师生们进行了现场交流。 </p>
<p align="center"><img src="/uploads/allimg/c110113/z2mhnnllklzhkbf-bhyl2.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 交流活动结束后，本次活动的主持人周晓普教授代表师生向Andrew Crisell教授的来访表示衷心感谢。她指出，现在国内对广播电视发展的理念多承袭自美国，而英国的广电发展情况与美国有很大不同，通过Andrew教授的演讲，新闻学院师生更多地了解了英国广电行业的历史与现状，这对师生们今后的学习和研究有很大启发意义。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnllk2khhyf-hnlzb_lit.jpg{/dede:field}
