{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}冯玉军教授应邀在天津市宗教事务局做专题讲座{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-09 09:39:53{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月3日上午，法学院冯玉军教授应天津市人民政府宗教事务局邀请，赴津给天津市2011年宗教界代表人士培训班授课。该培训班以天津市各宗教团体秘书长以上负责人、各区县宗教工作部门负责同志为主体，共80余人参加。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 冯玉军教授首先阐述了法律与宗教问题的基本理论，介绍了我国有关宗教法律法规的主要内容。而后冯玉军教授重点围绕刚刚完成的司法部重点课题成果《中国宗教事务法制化调研报告》展开培训。借助于已进行的问卷调查、实地调研访谈和数十次与爱国宗教界人士的座谈会素材，冯玉军教授从实际出发、用数据说话，通过40多个问题的统计分析，力求客观、全面地把握我国五大宗教教职人员、信教群众以及普通非信教群众对当前我国宗教事务政策与法律实施状况的评价，为未来我国宗教事务法律体系的完善、宗教事务管理工作的优化以及宗教信仰自由的全面保护提供参考。讲座受到与会听讲者的好评。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（编辑：王强）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
