{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国人民大学法学院代表团成功访问韩国庆北大学法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-04-12 11:44:59{/dede:field}
{dede:field name='body'}<p>　　近日，中国人民大学法学院副院长王轶教授与民商法教研室主任姚辉教授、副主任叶林教授以及高圣平副教授、金玄卿讲师一行5人成功访问了韩国国立庆北大学，并会见了庆北大学法学院院长张在贤教授、法学研究院院长辛奉起教授等学者。 <br />
<br />
<br />
　　双方在韩国庆北大学法学院举行了&ldquo;第四届中国人民大学&mdash;韩国庆北大学学术会议&rdquo;，韩国庆北大学法学研究院院长辛奉起教授主持了本次会议。辛奉起教授对中国人民大学法学院教授的到访表示热烈欢迎，王轶副院长也对庆北大学法学院的周到安排表示了谢意。 <br />
<br />
<br />
　　本次学术会议的主题是&ldquo;转型时期的民事法律制度----中韩民事法律疑难问题&rdquo;。会议上，中方先后作了&ldquo;中国民事立法中的&lsquo;中国要素&rsquo;&rdquo;、&ldquo;中国侵害人格权责任方式&rdquo;、 &ldquo;中国担保制度的发展与非典型担保的命运&rdquo;、 &ldquo;私法中的权利转换&mdash;&mdash;以团体法为视角&rdquo;的学术报告，韩方也先后作了 &ldquo;死因赠与为目的的为第三人利益合同&rdquo;、&ldquo;有关韩国三人关系不当得利的最近判例动向&rdquo;、&ldquo;日本民法修订的最新动向&rdquo;、&ldquo; 2009年修订商法（公司篇）的争论焦点&rdquo;的学术报告。 <br />
<br />
<br />
　　中国人民大学法学院代表团的此次庆北大学之行，虽然时间短暂，行程紧凑，但对于推动人民大学法学院与庆北大学法学院的进一步深入合作，加深中韩法学者之间的相互了解与友谊，起到了积极作用。</p>
<p>（编辑　安娜）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
