{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙院长赴宋涛教授家中看望家属{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-02-25 11:09:57{/dede:field}
{dede:field name='body'}<p>　　2月23日下午，杨瑞龙院长来到宋涛教授家中，看望了宋涛教授的夫人陈建民老师及其家属。杨瑞龙院长向宋涛教授的家属介绍了学校和学院组织的治丧和悼念活动的相关情况，转达了学校领导和全院师生的慰问，说明了经济学院近期拟开展的深切缅怀宋涛教授、弘扬宋涛教授精神的系列活动安排。杨瑞龙院长还将学校工会&ldquo;师生关爱基金&rdquo;资助的一万元慰问金以及抚恤金、丧葬费等转交到宋涛教授的夫人手中，并表示今后家中有什么困难尽管向学院提出。宋涛教授的夫人及家属对学校和学院领导的关怀以及治丧和悼念活动的精心组织表示感谢。 <br />
　　经济学院党委副书记丁凯陪同看望。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
