<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","法学院吴宏伟教授出席“第四届两岸民法暨经济法论坛”",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","法学院",220,265);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-20 11:35:23",267,326);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由辅仁大学法律学院主办的&ldquo;第四届两岸民法暨经济法论坛&rdquo;于12月9日至13日在台湾举行。参加本届论坛的有来自两岸十余所教学科研机构的从事民法与经济法研究的二十余位专家学者。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c110113/z2mhnnhmbyylmnf-zb2ny.jpg\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学法学院吴宏伟教授、09级经济法专业吴长军博士生应邀参加了这次学术会议。在本次论坛上，吴宏伟教授提交了&ldquo;行政垄断的规制与反思&rdquo;论文并作了主题演讲，吴长军博士生提交了&ldquo;中国出口退税法律政策论纲&rdquo;论文并作了学术交流。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;（编辑：刘伟伟）<br />\r\n</p>",328,1059);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c110113/z2mhnnhmbyylmnf-zb2ny_lit.jpg",1061,1153);
$z[7][4]['name']="litpic";

?>