{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}牛维麟常务副书记到环境学院低碳水环境技术实验室调研{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/环境学院  图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-04-02 11:00:22{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月1日上午，牛维麟常务副书记、实验室建设与设备管理处武宝瑞处长一行到环境学院低碳水环境技术实验室进行调研，并与环境学院院长马中、党委书记刘鹏、副院长王洪臣就环境学院实验室建设进行了研究。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhby2kkmzf-khzkk.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 实验室负责人王洪臣教授就实验室建设过程、研究方向的凝练、课题的申请、教学研究队伍的建设以及发展目标等方面向牛书记等领导做了详细汇报。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbyl2bzlf-nbzll.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛维麟常务副书记对实验室结合国家重大需求提出的研究方向及教学研究团队建设方案给予充分肯定，对实验室在较短时内就承担了数项国家重大课题表示满意，希望环境学院继续高目标、高起点、高质量地开展实验室建设，为学校&ldquo;精干的理工科&rdquo;建设做贡献。 <br />
</p>
<p>（编辑&nbsp; 燕燕&nbsp; 豫伟）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhby2kkmzf-khzkk_lit.jpg{/dede:field}
