{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大统计学院首开研究生免费独立科研中心{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}统计学院{/dede:field}
{dede:field name='pubdate'}2006-04-22 04:08:41{/dede:field}
{dede:field name='body'}<HTML><HEAD><TITLE> 人大统计学院首开研究生免费独立科研中心 </TITLE><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style><!--
 .iframestyle{height:expression(1);aho:expression(autoResize()) 
}
-->
</style>
<script>
function autoResize()
{
try
{
 document.all["showDemand"].style.height=showDemand.document.body.scrollHeight
}
 catch(e){}
}
 </script><body><P>&nbsp;&nbsp;&nbsp; 4月21日中午，中国人民大学统计学院学生科研中心启用仪式在明德楼1030学院讲堂隆重举行，从4月24日起，明德楼1031室将作为统计学院学生科研中心开放，统计学院也成为人民大学第一个专门为在校研究生提供免费独立科研场地的学院。<BR>　　<BR>&nbsp;&nbsp;&nbsp; 统计学院党委书记王晓军教授、党委副书记宋大我老师出席了启用仪式。统计学院博士、硕士和本科生代表约80人参加了启用仪式。启用仪式由统计学院团委书记张麟老师主持，仪式上公布了《统计学院学生科研中心使用公告》。学院领导为首批申请使用科研中心的同学颁发了使用卡。<BR>　　<BR>&nbsp;&nbsp;&nbsp; 科研中心由十四个独立的科研小间组成，内设有桌椅、柜子等常用设施，并可以提供无线上网。科研中心面向统计学院全体在校研究生开放，为研究生的学术研究提供了独立自由的使用空间、舒适便利的科研环境和距离导师更近的便利条件。科研中心建设经费源于“十五”“211工程”拨款及学院自筹资金，充分体现了人民大学“以生为本”的办学理念。<BR>　　<BR>&nbsp;&nbsp;&nbsp; 为确保科研中心顺利投入使用，统计学院制定了科研中心的管理办法和详细的申请制度，并安排了志愿者作为值班人员负责科研中心日常事务的管理。</P>
<P>（编辑：文静）<BR>　　<BR></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
