{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院2010级新生参加长江奖获奖者与新闻院校学生见面会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2010-09-15 02:49:12{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月11日，《长江自有后来人》第二辑发布会暨长江奖获奖者与新闻院校学生见面会在北京大学英杰交流中心举行。新闻学院2010级国防班、2010级本科新闻4班部分新生参加了见面会，聆听了六位长江奖获奖者的精彩报告。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次活动由中华慈善总会、中华全国新闻工作者协会、中国新闻史学会主办。六位长江奖获奖者与包括北京大学新闻与传播学院、中国人民大学新闻学院在内的10所新闻学院的学生面对面交流。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第六届长江新闻奖获奖者，《中国青年报》记者刘畅在演讲中为大家讲述了自己从年轻记者成长为长江奖获奖者的历程；山西黄河电视台知名记者肖亚光阐释了成功记者必备的三要素&mdash;&mdash;&ldquo;新闻灵感&rdquo;、&ldquo;热爱&rdquo;以及&ldquo;阅历&rdquo;&hellip;&hellip;六位获奖者通过自己的发言，从不同方面解读了优秀新闻记者所必备的素质，为到场2010级新生上了生动的一课。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会后，2010级新闻4班本科新生王娟表示，&ldquo;通过这次和优秀记者的交流，我了解到了做记者的奔波劳累&hellip;&hellip;但他们勇识过人，甘于奉献。只有热爱这份职业才会如此敬业，非常值得我们这些新生学习。&rdquo;&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
