{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学法学院与北京市高级人民法院签订双向交流合作协议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-22 02:43:51{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月18日，中国人民大学法学院与北京市高级人民法院签订双向交流合作协议。法学院院长韩大元、党委书记林嘉、党委副书记郑小敏出席签约仪式，韩大元院长代表法学院签署了合作协议。最高人民法院党组成员、政治部主任周泽民、北京市政法委副书记李万钧、北京市高级人民法院院长池强等领导到会讲话并对法学院表示祝贺。仪式由北京市高级人民法院党组成员、政治部主任鲁桂华主持。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fk2blzbf-lylkl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 法学院与北京市法院系统有着良好的合作传统，本次签约是在双方经过认真调研、友好协商的基础上确定的，既是法学院深化与法学实务界合作交流的新起点，也是北京市法院系统与在京高校双向交流合作机制的重要组成部分。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fk2nnfkf-hbh2k.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，法学院与北京市高院未来将主要采取合作形式进行系列课题研究，选派优秀法官赴法学院进修学习、讲授诉讼实务，邀请法学院优秀教授赴北京市法院系统挂职、授课、提供专家咨询意见等方式进行双向合作交流。同时，法学院将在与北京市高级人民法院协商的基础上，向在校学生提供参加庭审观摩和实践锻炼的机会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最高人民法院政治部法官管理部部长冯跃、中国政法大学校长黄进、北京大学法学院院长张守文、清华大学法学院党委书记车丕照等领导也出席了签约仪式。中国政法大学、北京大学法学院、清华大学法学院与人民大学法学院一道，共同成为双向交流合作机制的签约高校。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fk2blzbf-lylkl_lit.jpg{/dede:field}
