<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","经济学院赵国庆教授荣获中国数量经济学会2010年年会优秀论文一等奖",89,189);
$z[2][4]['name']="title";
$z[3]=Array("field","",191,230);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",232,279);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-12-04 08:18:20",281,340);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15-17日，中国数量经济学会2010年年会在华侨大学（厦门校区）召开，国内外学者500余人参会。经济学院赵国庆教授与其博士生张中元合作撰写的论文《经济开放、金融发展与消费平滑》获大会优秀论文一等奖。</p>\r\n<p>（编辑：王宝奎；核稿：丁凯）</p>",342,658);
$z[6][4]['name']="body";
$z[7]=Array("field","",660,699);
$z[7][4]['name']="litpic";

?>