{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院赵国庆教授荣获中国数量经济学会2010年年会优秀论文一等奖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-04 08:18:20{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15-17日，中国数量经济学会2010年年会在华侨大学（厦门校区）召开，国内外学者500余人参会。经济学院赵国庆教授与其博士生张中元合作撰写的论文《经济开放、金融发展与消费平滑》获大会优秀论文一等奖。</p>
<p>（编辑：王宝奎；核稿：丁凯）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
