{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国俄勒冈大学商学院和健康与人类学院两位院长访问环境学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-02-23 10:31:07{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月12日至2月14日期间，美国俄勒冈大学商学院院长Ilene K. Kleinsorge教授与健康和人类学院院长Tammy M. Bray教授对环境学院进行了为期三天的访问。</p>
<p align="center"><img height="333" src="/uploads/allimg/c100622/z2kkzlnflbnyl2f-z2bhf.jpg" width="500" alt="" /></p>
<p align="left">&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学环境学院院长马中教授，国际交流处、环境学院相关负责人一同参加了会谈。会议由马中院长主持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 马中院长向来访专家表示热烈欢迎。他简要介绍了环境学院的基本情况，以及近年来环境学院在教学科研及国际合作与交流等方面所取得的丰硕成果。接着，俄勒冈大学商学院院长Ilene K. Kleinsorge教授代表俄勒冈大学，向与会人员介绍了俄勒冈大学的发展情况，以及正在开展的国际合作项目。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈双方就国际交流合作，及互派学生交流项目等事宜进行了探讨。双方均表达了强烈的合作意向，并就合作形式等具体问题进行了磋商。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnflbnyl2f-z2bhf_lit.jpg{/dede:field}
