{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院举办“中国环境经济学与环境管理学术论坛及学科建设研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-05-22 09:57:30{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月20日，由环境学院主办的&ldquo;中国环境经济学与环境管理学术论坛及学科建设研讨会&rdquo;在中国人民大学逸夫第二会议室举行。校长助理兼研究生院常务副院长吴晓求教授、人事处处长郭洪林教授、科研处副处长牟峰教授应邀出席了论坛。出席论坛的还有环境学院党委书记王平副教授、副院长兼环境经济系主任邹骥教授、党委副书记吴健副教授、环境科学系主任宋国君教授以及环境学院的部分师生。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议由环境学院院长马中教授主持。校长助理兼研究生院常务副院长吴晓求教授代表学校领导为大会致辞，人事处郭洪林处长作了重要讲话。<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 应邀出席这次论坛的主要演讲嘉宾有：全国政协人口资源环境委员会副主任、中国环境科学学会理事长、原国家环保总局副局长、国家核安全局局长王玉庆教授，北京奥组委高级环境顾问、香港特区政府环境运输及工务局前局长廖秀冬博士，中国科学院首席研究员蒋高明博士，荷兰瓦格宁根大学Arthur Mol教授，美国俄勒冈大学讲习教授、原国家环保总局政研中心学术委员会主任胡涛博士等。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在上午的主题演讲阶段中，王玉庆教授和廖秀冬博士分别就&ldquo;大力发展绿色技术 引领未来可持续发展&rdquo;和&ldquo;经济发展中的环境挑战&rdquo;题目做了精彩的学术演讲，副院长兼环境经济系主任邹骥教授对两位嘉宾的演讲进行了深入的点评。随后，蒋高明博士、Arthur Mol教授和胡涛博士分别做了题为&ldquo;我国经济高速发展的环境代价&rdquo;、&ldquo;Education in environmental social sciences &rdquo;和&ldquo;虚拟的环境物品和服务：贸易如何影响环境？&rdquo;的学术演讲，环境科学系主任宋国君教授对三位嘉宾的演讲进行了细致的点评。历时三个半小时，嘉宾的演讲和专家的点评十分精彩，博得了参会师生们的阵阵掌声。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 下午，与会嘉宾与来自环境学院的师生就环境经济学与环境管理学科建设和发展进行了深入的研讨。马中院长首先介绍了中国人民大学的环境经济学与环境管理学教育的总体情况，随后邹骥副院长就中具体的科学研究情况做了说明，然后，由吴健副书记对教学情况进行了补充。 <br />
接下来，王玉庆教授结合其长期从事环境保护领导工作的实际经验对中国人民大学环境经济学与环境管理的教学与科研工作提出了几点重要意见。Arthur Mol教授、蒋高明博士和胡涛博士也分别结合自己的专业领域就这一主题与大家进行了深入地探讨，环境学院教师和学生也就自己的研究领域和对学科建设的看法与嘉宾进行了交流。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 论坛的五位演讲嘉宾均有应聘于环境学院的意向，他们对今后在人民大学环境学院任教表示出热切的希望和极大的信心。而这些具有国际水准的一流学者的到来也必将为环境学院环境经济学与环境管理的学科建设和发展做出积极的贡献，对于把环境学院建设成为&ldquo;国内一流、国际知名&rdquo;的环境学院具有重要而实际的意义。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{/dede:field}
{dede:field name='litpic'}{/dede:field}
