{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院代表团访问日本东京国立艺术大学并达成合作协议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-11-05 10:32:00{/dede:field}
{dede:field name='body'}<p>　　10月30日至11月3日，中国人民大学艺术学院学术代表团访问日本东京国立艺术大学，并达成合作协议。 </p>
<p>　　此次艺术学院代表团由艺术学院党委书记郑晓华、常务副院长徐唯辛、副院长王英健、校董高健女士等组成。访问期间，代表团观摩考察了东京艺术大学美术学院学生及教师工作室以及雕刻、陶艺、金工等实践工房，并就双方展开学术交流与合作进行了探讨。双方一致认同在相关艺术领域积极推进协作的重要性，并就举办两校教师作品展览及在中国人民大学艺术学院共同设立绘画材料技法研究室等方面达成了具体协议。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110725/zlzzbyzhm22zmf-zhknyl.jpg" /></p>
<p>　　日本东京国立艺术大学是日本的顶级艺术大学，在国际上也享有很高的学术声望。日本东京国立艺术大学的前身是&ldquo;东京美术学院&rdquo;和&ldquo;东京音乐学院&rdquo;，二者均创建于1887年。两校于1949年合并，命名为&ldquo;国立东京美术与音乐大学&rdquo;，2004年该大学更名为国立东京艺术大学（以下简称东京艺大）。自创立以来历经一个多世纪，美术与音乐一直是东京艺大学科设置的主题内容。2005年，在原有美术及音乐类学科构成的基础上，东京艺大增设了电影与新媒体研究生院。目前东京艺大各个学科分布在上野、茨城及横滨等校区，其中上野校区为美术与音乐学院的所在地，茨城校区以实践工房为主，而电影与新媒体研究生院则设置在横滨校区。 </p>
<p>　　东京艺大美术学院包含油画、日本画、雕塑、工艺、设计、建筑、综合媒体艺术、美学史论等系。本次中国人民大学艺术学院学术代表团所访问的油画系涵盖油画、版画、现代日本画等多个学科。 </p>
<p>　　（编辑：贾晓旭）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhm22zmf-zhknyl_lit.jpg{/dede:field}
