{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“中西形上学比较”北京研讨会在人大哲学院召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2009-07-28 06:11:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月26日下午，&ldquo;中西形上学比较&rdquo;北京研讨会在中国人民大学哲学院召开，来自美国、希腊的多位学者与哲学院的老师们在事先认真阅读彼此论文而充分准备的基础上展开了热烈而富有建设性的学术交锋和切磋讨论。会议由哲学院外事办公室主任温海明老师主持，聂敏里老师做了主题发言，惟善法师多次发表回应。哲学院院长郝立新教授主持会议开幕式并发表讲话，他说本次会议是哲学院配合我校国际化战略的重要步骤之一，今后将继续举办一系列以英文为主要工作语言的国际性学术研讨会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
