{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院韩立余教授入选WTO争端解决专家组指示性名单{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-05 03:03:04{/dede:field}
{dede:field name='body'}<p>　　2月18日，WTO争端解决机构（DSB）例会正式决定，将中国政府推荐的6名专家列入WTO争端解决专家组指示性名单，中国人民大学法学院韩立余教授入选名单。依据WTO《关于争端解决规则与程序的谅解》的相关规定，这6名专家将供WTO成员选择争端解决专家组成员时参考。</p>
<p>　　此前，2004年2月，张玉卿、曾令良、朱榄叶等3位教授成为第一批列入WTO争端解决机构专家组成员的指示名单的中国籍专家。2006年11月，董世忠和张月娇教授成为第二批列入该名单的中国籍专家。连同本次成功入选的6位专家，目前中国共有11名专家被列入WTO争端解决专家组指示性名单。其中，张月娇女士还于2007年11月被DSB任命为WTO上诉机构成员。</p>
<p>　　对比中国政府前两次的遴选，本次推荐名单中加大了&ldquo;学者型官员&rdquo;的比例。韩立余教授系中国人民大学法学院WTO研究领域的著名学者；其他五名专家则均有在商务部（前外经贸部）负责和参与WTO事务的工作经历，其实务经验更为丰富。李仲周先生还是我国&ldquo;复关&rdquo;与&ldquo;入世&rdquo;谈判的亲历者和主要领导之一。</p>
<p>　　WTO争端解决机制是解决WTO成员间的贸易争端，保证WTO成员认真履行WTO义务的重要手段。对于具体案件，一般由三位从指示性名单中选出的专家组成专家组，以个人身份，对案件作出裁决。推荐专家组成员，是WTO成员的一项重要权利。此次成功推荐上述6名专家列入WTO专家组成员指示性名单，对中国在更宽领域、更深层次上参与WTO事务具有重要意义。</p>
<p>　　（编辑　陈慧茹）&nbsp;</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
