<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","巴黎十大BENAVENT教授访问人民大学",89,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",202,249);
$z[4][4]['name']="source";
$z[5]=Array("field","2009-12-22 10:01:29",251,310);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月11日上午，巴黎十大经济学院双文凭研究生项目负责人BENAVENT教授和中国项目负责人韩淑艳老师访问人民大学。经济学院院长杨瑞龙教授在明德主楼1103会见了巴黎十大BENNAVENT教授一行。经济学院副院长刘元春教授、经济学院院长助理王晋斌教授、经济学院院长助理郑新业副教授、经济学院院长助理陈彦斌副教授、研究生院招生办公室马小侠主任、国际交流处副处长石佳友副教授参加会见。与会双方就联合培养经济管理学研究生的具体事宜进行了深入探讨。</p>\r\n<p>（编辑：王宝奎）</p>",312,839);
$z[6][4]['name']="body";
$z[7]=Array("field","",841,880);
$z[7][4]['name']="litpic";

?>