{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长出席MPA教育新春茶话会并讲话{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2011-01-19 05:03:06{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月14日，全国公共管理硕士（MPA）专业学位教育指导委员会在北京举行新春茶话会。中国人民大学校长、全国MPA教指委副主任委员纪宝成到会并讲话。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 他说，习近平副主席最近到国家行政学院视察工作，观看了2009级MPA班的案例教学，给予积极肯定的评价，指出&ldquo;案例教学是现在正在探索和尝试的一种新的教学方式，很有效果&rdquo;。我们要认真贯彻习近平副主席的指示精神，继续努力推动和推广案例教学。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪校长说，习近平副主席把MPA教育与建设学习型党组织联系起来，强调理论联系实际，这都有深刻的现实意义和指导意义，我们MPA教育指导委员会和各MPA培养院校都要认真领会，坚决贯彻。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 纪校长最后说，全国MPA教育指导委员会要适应研究生教育和干部培训的要求，创新工作，加强教学监督和评估，可以借鉴国际上MBA教育的做法，设计出MPA培养院校教育合格的认证制度。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
