{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院代表团赴韩参加“中日韩三国大学国际研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-11-12 03:45:24{/dede:field}
{dede:field name='body'}<p>　　10月30&mdash;31日，中国人民大学法学院代表团前往韩国釜山大学参加了东亚三国民法的现代化曁形成共同法的基础国际研讨会。会议在韩国釜山大学仁德馆举行，中国人民大学法学院龙翼飞副院长、王轶副院长等五位学者，韩国高丽大学河京孝教授（高丽大学法学院院长，韩国民事法学会会长）、池元林教授，韩国釜山大学姜大燮院长，庆熙大学崔光濬教授以及日本一桥大学法学院院长松本教授等六位学者，以及韩国民法学界著名学者和事务界人士共计六十余人共同参加了此次会议。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmzffn2hm2f-ll2nf.jpg" /></p>
<p>　　本次会议以&ldquo;东亚三国民法的现代化曁形成共同法的基础&rdquo;为主题，包括九个分主题，池元林教授、龙翼飞教授、松本教授共同讨论了&ldquo;亚洲合同法原则的可能性&rdquo;，金大贞教授、滝沢教授(日)、姚辉教授就&ldquo;中日韩三国合同法的成立与展开&rdquo;进行了讨论，角田教授(日)、王轶教授、李丙儁教授共同讨论了&ldquo;中日韩三国合同法的现代化动向与展望&rdquo;，贾林青教授、成升鉉教授、小野教授(日)就&ldquo;形成共同法的可能性探索-CISG与国内买卖合同法&rdquo;进行了讨论。三国知名大学学者就东亚民法的现代化及形成共同法的基础问题进行了热烈讨论，精彩点评，达到了充分沟通、相互促进、相互学习的会议目的。</p>
<p>　　&ldquo;中日韩三国大学国际研讨会&rdquo;的目的是为了促进三国知名大学法学院的国际交流和研究促进，由中国人民大学法学院、日本一桥大学法学院和韩国国立釜山大学法学院每年轮流召开。本次会议是第四届。第一届会议于2007年在日本一桥大学召开，第二届会议于2008年在中国人民大学召开，第三届会议于2009年在日本一桥大学召开。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbmzffnbm22f-hyylb.jpg" /></p>
<p>　　（编辑：贾晓旭）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzffn2hm2f-ll2nf_lit.jpg{/dede:field}
