{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学第四届院际友谊辩论赛成功举办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}施扬灵{/dede:field}
{dede:field name='pubdate'}2009-03-16 03:53:11{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月14日晚18：30，由外国语学院分团委、学生会举办的第四届院际友谊辩论赛小组赛第一轮比赛在明德主楼414、418教室举行。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 首场比赛辩题为&ldquo;环境保护应以人为本还是以自然为本&rdquo;，分别由经济学院对阵财政金融学院，公共管理学院对阵信息资源管理学院。比赛由各学院辩论队的优秀队员担任评委。比赛进行得十分精彩，场内座无虚席，并不时爆发出热烈的掌声。最终，经济学院与公共管理学院分别取得胜利。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第二场小组赛参赛队伍为：信息学院对阵马克思主义学院，新闻学院对阵农村与农业发展学院。辩题为&ldquo;网络时代，普通人能不能承担新闻记者的社会功能&rdquo;。最终，信息学院与马克思主义学院战成平局，新闻学院胜农村与农业发展学院。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 院际友谊辩论赛是人民大学每年一届的全校性赛事，此次已是第四届。外国语学院学生会负责人表示，比赛已经在人大校园掀起了浓厚的辩论氛围，对丰富和发展学校的校园文化起到了积极作用。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
