{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杰出校友、原越共中央政治局委员潘演回访母校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9月30日，经济学院杰出校友、原越共中央政治局委员、书记处书记潘演回访母校。经济学院杨瑞龙院长，刘瑞副院长，刘成瑞教授等与潘演校友亲切座谈，国际交流处副处长李轶群，经济学院国民经济管理系中青年教师和学生代表，越南籍优秀留学生代表等参加了座谈会。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzznkmnnmf-zlkbn.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长首先对潘演校友返校表示热烈欢迎，他重点向潘演校友介绍了近年来经济学院学科发展和人才培养所取得的成绩，并介绍了人大的理论经济学与应用经济学在中国国内学科排名中的领先位置。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 潘演校友表示对能够重返母校感到十分激动和欣喜，他对人民大学的良好发展势头和经济学院学科建设的成绩给予了高度赞赏。他认为，人民大学的毕业生是国家人才的重要来源，在各自的岗位上出色地发挥了自己的作用。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，潘演校友在刘瑞副院长的陪同下，参观了校史馆、命名组建六十周年展览和博物馆等并合影留念。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzznnkkzf-2nlyh.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当日，程天权书记会见并宴请了潘演校友，经济学院杨瑞龙院长出席了午宴。 <br />
　　潘演校友1956－1960年在人大计划经济系学习，后历任越共第七届中央委员，第八届、第九届中央政治局委员。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1286761047{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzznkmnnmf-zlkbn_lit.jpg{/dede:field}
