{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院韩大元院长会见王氏基金会执行主席及美国联邦第九巡回法院大法{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院　董立阳{/dede:field}
{dede:field name='pubdate'}2010-03-05 05:18:31{/dede:field}
{dede:field name='body'}<p>　　3月3日上午，法学院韩大元院长在明德法学楼贵宾室205会见了美国王氏基金会执行主席Francis SL Wang，美国第九巡回上诉法院法官DIARMUID F．O&rsquo; SCANNLAIN及其夫人，法学院副院长王轶教授，院长助理冯玉军教授、丁相顺副教授等参加了会见活动。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c100619/z2kymzy2ynhfkf-h2bbz.jpg" /></p>
<p>　　韩大元院长首先就两位嘉宾为JESSUP国际法模拟法庭所作的工作致谢。韩院长简要介绍了人民大学法学院60周年的风雨历程和光辉传统，人民大学法学院历经10届院长，为中国法律界培养了大量人才，更为重要的是，人民大学法学院一直注重培养学生的人文精神和社会服务意识。几位贵宾对此大为赞赏。</p>
<p>　　随后，韩大元院长和丁相顺副教授同王氏基金会执行主任Francis SL Wang 就王氏基金会和人民大学法学院在推动中国法律变革和培养国际性的法律人才方面可能开展的合作方式和具体细节进行了深入交流。Francis SL Wang 表示非常乐于帮助人民大学法学院达成法律学生国际化的愿景，并表示乐于参与人民大学法学院的论坛等活动。双方还针对中国和外国的法律培养模式以及教学方式的差异性也进行了细致的讨论。</p>
<p>　　会谈后，韩大元院长邀请两位嘉宾参加人民大学法学院60周年的院庆活动，两位嘉宾都表示乐于参与这一盛事并愿意为期间将要举办的国际法学院院长论坛做出自己的贡献。韩大元院长代表人民大学法学院向两位嘉宾赠送了礼品。</p>
<p>　　在会谈中，美国第九巡回上诉法院法官DIARMUID F．O&rsquo; SCANNLAIN接受法学院的邀请，在人民大学法学院大法官论坛举办名为&ldquo;审判的公正性和独立性&rdquo;的讲座。</p>
<p>　　（编辑　陈慧茹）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzy2ynhfkf-h2bbz_lit.jpg{/dede:field}
