<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","日本早稻田大学中村教授和田中教授为经济学院研究生授课",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",222,269);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 根据中国人民大学经济学院和日本早稻田大学政治经济学部签署的学术交流协议，早稻田大学政治经济学部中村慎一郎（Shinichiro Nakamura）教授和田中久稔（Hisatoshi Tanaka)）副教授分别于2010年9月17日-20日和9月24日-26日来我校，为经济学院硕士研究生讲授《现代日本经济》课程。该课程设为1学分，用英语授课。 <br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 该课程是经济学院与早稻田大学政治经济学部学术交流项目的重要内容之一。根据协议，双方互派教师为硕士研究生开设相关课程或讲座，用英语授课，并相互承认学分。 </p>\r\n<p>\r\n</p>",271,861);
$z[5][4]['name']="body";
$z[6]=Array("field","1285442530",863,913);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",915,954);
$z[7][4]['name']="litpic";

?>