{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中国经济学家年度论坛（2010）在人民大学举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为打造中国经济学高端学术交流平台，促进经济学研究的持续繁荣，彰显人大经济学科在全国的领军地位，11月20日，中国人民大学经济研究所联合董辅礽经济科学发展基金会、北京大学经济研究所、武汉大学经济研究所、上海交通大学安泰经济与管理学院等机构，共同举办中国经济学家年度论坛暨中国经济理论创新奖（2010）颁奖典礼。论坛在中国人民大学逸夫会堂第一报告厅隆重举行，由中国人民大学经济学院、董辅礽经济科学发展基金会承办。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhnkhf2mf-zmbhzk.jpg" width="500" alt="" /></p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhnn2kmnf-2fklfm.jpg" width="500" alt="" /><br />
全国政协副主席郑万通 </p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学副校长林岗教授出席论坛开幕式并致辞。他指出，在过去30多年中，中国的经济结构发生了深刻的变化，目前中国的经济正以世界罕见的发展速度发展着，与此同时，一代又一代中国经济学人通过对改革开放实践科学总结和概括，产生了大量兼具中国特色和世界性的研究成果，不断丰富和完善具有中国特色的社会主义经济理论。他希望经济学研究者在马克思主义经济学的指导下，理论联系实际，不断探索和推动中国经济科学的创新与进步。论坛开幕式由中国人民大学经济研究所联席所长毛振华教授主持。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhnnkbfbf-2zmzfh.jpg" width="500" alt="" /><br />
中国人民大学副校长林岗 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhnmy2nmf-22hb2l.jpg" width="500" alt="" /><br />
北京大学光华管理学院名誉院长厉以宁</p>
<p align="left"><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 论坛上，清华大学经济管理学院院长钱颖一、北京大学光华管理学院院长张维迎、中国人民大学经济学院院长杨瑞龙、北京大学经济学院院长孙祁祥、武汉大学经济与管理学院教授伍新木、董辅礽经济科学发展基金会会长陈东升、中国人民大学校长助理、研究生院常务副院长吴晓求、中国建设银行股份有限公司党委书记、董事长郭树清、中国政法大学终身教授江平、北京大学光华管理学院名誉院长厉以宁等先后围绕&ldquo;经济转型与发展&rdquo;的主题发表了学术演讲。论坛由北京大学经济研究所常务副所长杨云龙教授和中国人民大学经济学院副院长、经济研究所联席副所长刘元春教授共同主持。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmfbbm2f-2lz2ll.jpg" width="500" alt="" /><br />
中国人民银行行长周小川 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmzlbkbf-2hnkzb.jpg" width="500" alt="" /><br />
中国人民大学经济学院院长、经济研究所联席所长杨瑞龙 </p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 第三届中国经济理论创新奖经过向经济学界公开征集候选经济理论，进行了两轮评审专家投票，以透明公开的程序评选出最终获奖者。&ldquo;整体改革理论&rdquo;得票数名列第一，国务院发展研究中心研究员吴敬琏、中国人民银行行长周小川、中国建设银行董事长郭树清等为该理论主要贡献人。</p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmzmmnzf-2bkyfm.jpg" width="500" alt="" /><br />
清华大学经济管理学院院长钱颖一 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhm2kznzf-2yllyl.jpg" width="500" alt="" /><br />
北京大学光华管理学院院长张维迎 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmlhhflf-2khhmz.jpg" width="498" alt="" /><br />
北京大学经济学院院长孙祁祥 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmhzfb2f-2n22zk.jpg" width="500" alt="" /><br />
武汉大学经济与管理学院教授伍新木 </p>
<p>&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 颁奖典礼由中国人民大学经济研究所联席所长毛振华教授代表组委会致辞，中国人民大学经济学院院长、经济研究所联席所长杨瑞龙宣读了颁奖辞。中国人民银行行长周小川代表获奖者出席颁奖典礼。北京大学光华管理学院名誉院长厉以宁、全国政协副主席郑万通、董辅礽经济科学发展基金会会长陈东升分别为周小川先生颁发了获奖证书、奖牌和奖金。典礼上，周小川行长发表了学术演讲。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmbfynmf-2mn2hm.jpg" width="500" alt="" /><br />
董辅礽经济科学发展基金会会长陈东升 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmbkyylf-lf2yyk.jpg" width="500" alt="" /><br />
中国人民大学校长助理、研究生院常务副院长吴晓求 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmybbzbf-lzyllz.jpg" width="500" alt="" /><br />
中国建设银行股份有限公司党委书记、董事长郭树清 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmk2ymnf-l2mzl2.jpg" width="500" alt="" /><br />
中国政法大学终身教授江平 </p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国经济理论创新奖是我国第一个由经济学界以学术民主投票并公开计票的方式进行评选的经济学大奖，是经济理论界对改革开放以年来我国经济研究成果的系统梳理和盘点。2008年以杜润生及农村发展问题研究组作为主要贡献人的&quot;农村家庭联产承包责任制理论&quot;获得首届中国经济理论创新奖；2009年以厉以宁作为主要贡献人的&ldquo;国有企业股份制改革理论&rdquo;获得第二届中国经济理论创新奖。</p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmkmyhyf-llnbhn.jpg" width="500" alt="" /><br />
中国人民大学经济研究所联席所长毛振华 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmnyk2yf-lhhnz2.jpg" width="500" alt="" /><br />
北京大学经济研究所常务副所长杨云龙 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhmmb2mhf-lbhkhn.jpg" width="500" alt="" /><br />
中国人民大学经济学院副院长、经济研究所联席副所长刘元春 </p>
<p>（编辑：王宝奎；核稿：丁凯）&nbsp;<br />
</p>{/dede:field}
{dede:field name='pubdate'}1290566836{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhnkhf2mf-zmbhzk_lit.jpg{/dede:field}
