{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纪宝成校长会见西班牙桑坦德银行集团总裁埃米利奥博廷先生{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学生处{/dede:field}
{dede:field name='pubdate'}2011-04-11 08:30:46{/dede:field}
{dede:field name='body'}<p>　　4月9日下午，纪宝成校长会见了来访的西班牙桑坦德银行集团总裁埃米利奥&bull;博廷先生（Mr. Emilio Bot&iacute;n, Chairman of Banco Santander）一行，双方就正在合作开展的学生国际交流奖学金项目、西班牙语培训项目等进行了愉快的交谈。</p>
<p align="center"><img src="/uploads/allimg/c110418/zlflzzhbynhnfbf-hlkyk.jpg" alt="" />&nbsp;</p>
<p>　　在会见中，纪宝成校长介绍了近年来人民大学发展状况、学科特色、实力排名以及国际交流情况，并重点介绍了学校金融管理方面的学术实力、科研发展、国内国际影响以及与国外学界的交流合作情况。博廷先生也向纪宝成校长介绍了桑坦德银行的历史、规模以及发展战略，并对桑坦德银行大学项目的执行情况进行了简要介绍。博廷先生高度评价人民大学在人才培养和国际交流方面取得的成绩，并表示将继续积极推动并加强与人民大学的合作关系。</p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110418/zlflzzhbynkmmf-bybmb.jpg" alt="" /></p>
<p>　　2010年4月，西班牙桑坦德银行与中国人民大学签订合作协议，每年投入17万美元，用于支持中国人民大学学生国际交流奖学金项目、青年教师和研究人员交流项目、本科学生西班牙语培训计划及其他学术项目。在会谈过程中，博廷先生也表示将在已有合作协议的基础上增加对人民大学的支持。</p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110418/zlflzzhbynnlnbf-yhfn2.jpg" alt="" /></p>
<p>　　在纪宝成校长会见之前，马俊杰副书记陪同博廷先生一行参观了商学院。</p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110418/zlflzzhbynnnhlf-kllff.jpg" alt="" /></p>
<p>　　学校党委副书记马俊杰教授、学生处处长张晓京、商学院副院长毛基业、国际交流处副处长程鑫参加了会见和参观。西班牙桑坦德银行集团方面陪同来访的还有桑坦德总裁秘书哈维&bull;穆纽斯先生（Mr. Javier Munoz Grandes）、集团执行主任兼执行副主席胡安&bull; 因西亚特先生（Mr. Juan Rodriquez Inciarte）、集团亚太区首席执行官胡安&bull;罗曼先生（Mr. Juan Manuel San Rom&aacute;n）、桑坦德银行大学事务部主任萨尔瓦多&bull;梅迪纳先生（Mr. Salvador Medina Chao）、桑坦德银行北京代表处首席代表王凤娜女士（Ms. Ana Wang）、桑坦德银行高级顾问秦雷女士（Ms. Qin Lei）、桑坦德银行大学事务部主任助理伊内斯&bull;玛克塔（Ms. Ines Maqueda）。 </p>
<p>　　(编辑：席嘉怡)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbynhnfbf-hlkyk_lit.jpg{/dede:field}
