{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院在四川省广安市建立本科教学实习基地{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2010-12-22 10:36:38{/dede:field}
{dede:field name='body'}<p>　　12月17日，中国人民大学社会与人口学院与四川省广安市人口和计划生育委员会共建本科教学实习基地签约仪式在四川省广安市举行。学院党委书记兼副院长郭星华教授与主管本科教学的教务秘书彭雁、王蕊老师组成的代表团出席了签约挂牌仪式。郭星华书记代表学院与广安市相关部门的领导共同签署了协议书。</p>
<p>　　四川省广安市市委常委、市总工会主席肖雷，广安市人民政府副市长陈彬，广安市人口和计划生育委员会主任黄勇等相关领导出席了签约挂牌仪式。</p>
<p>　　据了解，建立本科实习基地，是社会与人口学院加强本科生培养的重要途径，较大程度上满足了本科教学全面培养创新实用型人才的需要，为学院本科生提高综合素质、增强社会实践和课外学术科研能力提供了保障。本科教学实习基地是学院和地方共同建设的服务学校和社会的平台，也成为了学院和地方沟通合作的桥梁。广安市相关领导表示，相关部门将尽全力创造良好条件，全力支持学院的教学实习工作。</p>
<p>　　(编辑：王开)</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
