{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}艺术学院师生作品入选第十一届全国美展{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2009-09-28 04:01:26{/dede:field}
{dede:field name='body'}<p>　　9月10日，&ldquo;第十一届全国美展&mdash;&mdash;动漫、综合画种作品展&rdquo;在哈尔滨国际会展体育中心开幕。艺术学院有2名教师和8名学生的漫画作品入选&ldquo;动漫展区&rdquo;漫画部分展览。</p>
<p>　　全国美展每五年一届，是我国水平最高、规模最大、影响最广的美术展览。第十一届全国美展被中宣部列为新中国成立60周年庆典的重要文化项目。与往届展会不同，为了推动中国本土动漫艺术的发展，本届大展首次设立了动漫专项展，充分体现出国家为扶持中国民族动漫文化的繁荣发展所做出的努力。</p>
<p>　　本次展览共有207件（部）动漫作品入选，其中动画125件，漫画82件。艺术学院师生能在这样高水平高规格的大展中，在全国众多艺术家的搏击中，以较多的作品参展，充分展示了艺术学院教学的实力和艺术学院学生的专业水平，为艺术学院赢得了荣誉。</p>
<p align="center">参展作品：</p>
<p align="center"><img height="238" alt="" width="480" src="/uploads/allimg/c110725/zlzzbyzhkbnkzbf-2lbzfh.jpg" /></p>
<p align="center">绘画系教师洪涛作品《三顾茅庐》</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhkylhkbf-2hmm2f.jpg" /></p>
<p align="center">设计系教师焦振涛作品《京城新貌》</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhkybzbbf-2bblmf.jpg" /></p>
<p align="center">插图专业2005届学生吴卓作品《新野变》</p>
<p align="center"><img height="480" alt="" width="341" src="/uploads/allimg/c110725/zlzzbyzhkyy2khf-2y2mmn.jpg" /></p>
<p align="center">插图专业2005届学生张群作品《圣矛传奇》</p>
<p align="center"><img height="480" alt="" width="357" src="/uploads/allimg/c110725/zlzzbyzhkkhf2mf-2kblkn.jpg" /></p>
<p align="center">插图专业2005届学生张胜男作品《你好》</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhknfzh2f-2nk2n2.jpg" />&nbsp;</p>
<p align="center">插图专业2007届学生张占勤作品《大城小事》 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhknbbbf-2mhzlh.jpg" /></p>
<p align="center">插图专业2007届学生康毅作品《两件风衣》 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhknyzzmf-lfhfln.jpg" /></p>
<p align="center">插图专业2009届研究生温婷作品《寂寞日记》 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhknyyzyf-lzllyf.jpg" /></p>
<p align="center">插图专业2008级研究生邢蕾作品《寻找丽江》</p>
<p align="center"><img height="480" alt="" width="195" src="/uploads/allimg/c110725/zlzzbyzhknkhbhf-l2zn2b.jpg" /></p>
<p align="center">插图专业2008级研究生崔京文作品《风筝》 </p>
<p align="left">　　（编辑　杨高敏）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkbnkzbf-2lbzfh_lit.jpg{/dede:field}
