<?php
$z[0]=Array("item","",4,72);
$z[0][4]['name']="栏目管理";
$z[0][4]['link']="ask_type.php";
$z[0][4]['rank']="";
$z[0][4]['target']="main";
$z[1]=Array("item","",76,145);
$z[1][4]['name']="问题管理";
$z[1][4]['link']="ask_admin.php";
$z[1][4]['rank']="";
$z[1][4]['target']="main";
$z[2]=Array("item","",149,219);
$z[2][4]['name']="答案管理";
$z[2][4]['link']="ask_answer.php";
$z[2][4]['rank']="";
$z[2][4]['target']="main";

?>