{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京市法学会法律图书馆与法律信息研究会成立　人大法学院图书馆副馆长当选副会长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院图书馆{/dede:field}
{dede:field name='pubdate'}2010-04-07 02:39:00{/dede:field}
{dede:field name='body'}<p>　　4月2日， &ldquo;北京市法学会法律图书馆与法律信息研究会&rdquo;第一次会员代表大会暨学术研讨会在清华大学法学院明理楼隆重召开。来自国家图书馆、中国图书馆学会以及高校、研究机构法律图书馆和政府、人大、司法系统法律图书馆的百余名代表出席了大会。 <br />
<br />
　　大会讨论通过了《北京市法学会法律图书馆与法律信息研究会组织规则》及《北京市法学会法律图书馆与法律信息研究会首届会长、副会长、秘书长选举办法》，并按程序选举理事、常务理事、会长、副会长、秘书长和副秘书长。中国人民大学法学院图书馆副馆长李岸曰等当选副会长，杨淑玲当选常务理事，王明英、杨连长、吴赤工等当选理事。 李岸曰副馆长还宣读了当选会长、副会长、秘书长、常务理事、理事名单。 <br />
<br />
　　成立仪式结束后，与会专家围绕&ldquo;学术社团的角色：责任与活力&rdquo;、&ldquo;法律知识增长与法律图书馆功能扩张&rdquo;、&ldquo;北京地区法律图书馆与法律信息事业建设的回顾与展望&rdquo;等主题展开了热烈而深入的研讨，以期推动法律图书馆与法律信息事业的发展。 </p>
<p>　　（编辑：於萍萍）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
