{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院邹骥教授演讲“中国控排目标解读与哥本哈根会议展望”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2009-12-08 03:19:15{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月25日，在中国政府向世界宣布&ldquo;到2020年单位GDP二氧化碳排放量将比2005年降低40%到45%&rdquo;的承诺后，社会各界对中国实现控排目标的成本和影响广泛关注。12月2日晚上7点，中国人民大学环境学院副院长、世界资源研究所中国区首席代表邹骥教授，在逸夫会议中心第一报告厅发表主题为&ldquo;哥本哈根回合：中国的挑战与机遇&rdquo;的演讲，全面解读中国政府日前发布的温室气体控排目标，并展望即将召开的联合国哥本哈根气候变化会议。</p>
<p>　　在讲座中，邹骥教授指出，由于中国目前的人口和城市化水平、经济结构、经济发展阶段、能源资源禀赋、技术水平和国际分工等现实原因，中国的碳排放总量呈现上升的趋势，要作出减缓气候变化的努力对中国来说并不容易。&ldquo;光看能源资源禀赋，我们脚底下埋的是煤,而不是石油、天然气。消耗相同的热量，我们排的碳要比别人多，这使得我们在减排的起跑线上就慢了别人一拍。&rdquo;邹骥教授形象的说。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfbhyfhf-y2knn.jpg" /></p>
<p>　　邹骥教授介绍了由其领导的中国人民大学能源与气候经济学项目（PECE）研究团队的研究。基于该研究，对中国政府发布的温室气体控排目标进行了全面、深入的解读。根据PECE研究团队的研究成果，中国如果在2020年时达到碳排放比2005年减少45%的目标，则今后10年每年需要为此付出300亿美元的增量成本，相当于每户中国家庭每年要多负担64美元。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邹骥教授介绍说，PECE团队独立开发了基于二氧化碳削减技术减排潜力和边际成本信息的非线性优化模型。该模型涵盖了388种技术的减排潜力和成本信息，可以用于评价温室气体减排目标的可行性、技术需求和可能产生的社会经济影响。</p>
<p>　　</p>
<p>　　（编辑：潘成敏）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfbhyfhf-y2knn_lit.jpg{/dede:field}
