{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}程天权书记率团访问西班牙、希腊三所大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='pubdate'}2011-04-07 09:15:42{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月28日－4月4日，应西班牙马德里大学、巴塞罗那自治大学和希腊雅典大学邀请，程天权书记率中国人民大学代表团访问了西班牙和希腊，加强和推进了学校与西班牙、希腊三所著名大学的交流合作。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月28日，程天权书记率代表团访问西班牙马德里大学（Complutense University of Madrid）。马德里大学是西班牙最大的国立自治综合大学，现有学生75600余人，教师6000余人，有21个院系和研究中心，其学生人数、教师人数以及专业设置均名列西班牙大学榜首。诺贝尔医学奖得主拉蒙&bull;伊&bull;卡哈尔、文学奖得主塞拉&bull;阿美利科&bull;卡斯特罗以及西班牙一些大学的领导人、名教授以及政界要人都毕业于马德里大学。马德里大学主管国际交流事务副校长Lucila Gonz&aacute;lez Pazos教授会见了程天权书记一行，双方就加强教师互访、学术合作和学生交流等问题进行了实质性的商谈。Lucila Gonz&aacute;lez Pazos教授对代表团的来访表示了热烈欢迎，她介绍了马德里大学的基本情况，表达了要与人民大学签订校际合作协议的强烈愿望，希望两校在经济学、政治学、法学和自然科学等领域开展全方位、多层次的合作。程天权书记扼要介绍了学校的办学历史、学科优势以及国际化发展情况，重点推介了学校举办的国际小学期项目和全英文硕士项目，并表示赞同Lucila Gonz&aacute;lez Pazos教授关于加强两校交流与合作的建议。马德里大学法学院副院长Amparo Grau教授、哲学院Carlos Fern&aacute;ndez教授、Consuelo Marco教授、人事处处长Seraf&iacute;n Soli&ntilde;o先生等分别与韩大元教授、秦宣教授、郭洪林处长单独进行了专题交流。会谈前，Lucila Gonz&aacute;lez Pazos教授和国际交流处Mar&iacute;a Jos&eacute; Serna处长陪同程天权书记参观了马德里大学两个校区。会谈后，Lucila Gonz&aacute;lez Pazos教授宴请了代表团一行。程天权书记一行是中国人民大学访问马德里大学的第一个代表团，此次访问对于开启学校与马德里大学的合作交流具有十分重要的意义。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbybnznhf-lkbyk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;图为程天权书记一行与西班牙马德里大学代表会谈合影</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月31日，程天权书记一行访问巴塞罗那自治大学（Universitat Aut&ograve;noma de Barcelona）。巴塞罗那自治大学创立于1968年，是一所年轻但国际化程度极高的高水平大学，现有28283名本科生、5084名研究生、2800名教师。该校非常重视与外国大学交流学生及研究成果，有近6000名来自全世界不同国家的学生在该校学习，是西班牙拥有外国留学生最多的大学，同时也是被公认为欧洲最优秀的大学之一。巴塞罗那自治大学校长Ana Ripoll Aracil教授与程天权书记进行了亲切友好会谈，双方就开展学者学术交流、学生短期互派、人员互访以及分享孔子学院建设经验等进行了商谈。巴塞罗那自治大学副校长Carlos Jaime Cardial教授、法学院院长Josep Maria de Dios教授、经济学与商学院主管学生交换事务的副院长Mar&iacute;a Teresa Cabeza教授、翻译学院主管学术事务的副院长Jacqueline Minnet教授、国际交流处处长Marta Vilalta、翻译学院亚洲研究协调人Joaquin Beltran、巴塞罗那孔子学院院长Minkang Zhou、国际交流处Montserrat Alegre参加了与代表团的会谈，并各自介绍了开展国际合作交流的项目情况。Ana Ripoll Aracil校长十分重视中国人民大学代表团的访问，她回顾了与人民大学合作的历史，重点介绍了巴塞罗那自治大学的学科特色和国际化发展战略，并提出与人民大学进一步开展交流合作的设想。程天权书记重点介绍了人民大学的学科特色、专业特点、国际小学期及全英文硕士项目，表示根据学校提升国际性的发展战略，希望加强与欧洲著名大学的交往合作，建议加大两校学生交流、学者互访的力度和学院之间实质性的学术合作。巴塞罗那自治大学是人民大学在西班牙最早的伙伴院校，但近年来两校互访较少，人民大学代表团的此次访问对促进两校加大实质性的交流合作起到了重要的推动作用。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbyyznyzf-h2kyf.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;图为程天权书记一行与巴塞罗那自治大学代表会谈</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月4日，程天权书记和代表团成员访问了雅典大学（The National and Capodistrian University of Athens）。雅典大学全称为雅典国立与卡珀得斯兰大学，成立于1837年，是希腊最古老和最具影响力的大学，也是希腊最大的高等教育学院。现有80,000名学生、2000名教师，设有政治、医学、哲学、法律、理学、神学等6个学院，涵盖30个学科门类。雅典大学校长Theodosios N. Pelegrinis教授热情接待了程天权书记一行，双方就开展学术合作、学生交流和共同举办国际学术会议、推进中希两个文明古国文化交流进行了富有成效的商谈。Theodosios N. Pelegrinis校长重点介绍了雅典大学的历史和地位以及与中国学者、高校开展合作的基本情况，明确表示要与我校加强全面合作。程书记对Theodosios N. Pelegrinis校长的热情接待表示十分感谢，并特别介绍人民大学的学科特色和学术实力以及学校在中国高等教育体系中的重要地位和影响，提出了加强两校合作的具体建议，如继续推进双方学院之间的合作、继续加强两校学生、教师交流、共同发起并举办以东西方文化交流为主题的国际学术论坛等。雅典大学外事副校长Theodore D. Liakakos 教授、法律、经济及政治学院院长Michael Tsinisizelis教授、国际关系及欧洲教育项目委员会主席、历史与考古学院史前考古学Eleni Mantzourani教授、经济学系主任Ioannis C. Demetriou教授、传播与媒体学院Kalliroi Panagiotopoulou教授、公共与国际关系处Elias Marsellos处长参加了会谈，并与人民大学代表团成员就如何开展具体合作进行了交流沟通。在双方充分商谈并取得了不少共识的基础上，程天权书记和Theodosios N. Pelegrinis校长代表两校现场签订校际合作框架协议，这标志着人民大学与雅典大学的合作进入了一个新的阶段。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbyy2zkhf-bynyl.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图为程天权书记与雅典大学校长Theodosios N. Pelegrinis教授会谈<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 访问期间，程天权书记和代表团一行还访问了对人民大学给予了极大资助的西班牙最大金融机构桑坦德银行，拜会了中国驻西班牙大使馆教育组一秘王志伟、中国驻希腊大使馆临时代办郑曦原，感谢他们长期以来对学校的支持和帮助。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陪同程天权书记出访的中国人民大学代表团成员有法学院院长韩大元、马克思主义学院院长秦宣、人事处处长郭洪林、书记事务助理兼学校办公室副主任李家福、国际交流处杜尘程。 <br />
</p>
<p>（编辑&nbsp; 燕燕）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbybnznhf-lkbyk_lit.jpg{/dede:field}
