{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}冯玉军教授应邀参加国务院法制办“重大行政决策程序立法”座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院　文/苏志梅 王伟{/dede:field}
{dede:field name='pubdate'}2011-03-02 09:46:57{/dede:field}
{dede:field name='body'}<p>　　重大行政决策程序条例已经列为国务院2011年立法工作计划的三档项目。为尽快启动条例起草工作，国务院法制办政府法制研究中心于2月25日下午举行座谈会，就立法的可行性和必要性等问题听取各方面专家意见。法学院冯玉军教授应邀与会，就国务院制定重大行政决策程序条例的必要性和可行性，制定该条例的主要内容、起草原则及主要难点发表了自己的见解。</p>
<p>　　（编辑：卢思颖） <br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
