<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国伦理学会成立30周年庆典暨首届学术成果奖颁奖大会召开",89,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","伦理学与道德建设研究中心",224,287);
$z[4][4]['name']="source";
$z[5]=Array("field","<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c101126/z2mfkyfhm2fzmhf-mkbhz.jpg\" /></p>\r\n<p align=\"left\">　　为纪念中国伦理学会成立30周年，总结中国伦理学学科30年建设和发展的成就，由中国伦理学会主办，中国人民大学伦理学与道德建设研究中心承办的&ldquo;中国伦理学会成立30周年庆典暨首届学术成果奖颁奖大会&rdquo;于11月19日在逸夫会议中心第一报告厅隆重召开。</p>\r\n<p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c101126/z2mfkyfhmlzhnnf-zfhyyn.jpg\" /></p>\r\n<p>　　中共中央政治局委员、中央书记处书记、中宣部部长刘云山对会议作出重要批示。中宣部原常务副部长徐惟诚先生、中国人民大学副校长陈一兵、中国人民大学校长助理兼哲学院院长郝立新、中国伦理学会会长万俊人，及相关兄弟院校领导出席会议并致辞。来自海内外不同高校及科研机构近二百位伦理学者参加了会议。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c101126/z2mfkyfhml2lkf-zzlmyf.jpg\" alt=\"\" /></p>\r\n<p>　　在大会开幕式中，陈一兵副校长代表大会向罗国杰、徐惟诚等12位学界前辈颁发了中国伦理学会&ldquo;终身成就奖&rdquo;，以表彰他们对中国伦理学学科建设和发展所做出的卓越贡献。 </p>\r\n<p>　　万俊人、王小锡等一批学者获得了中国伦理学会首届&ldquo;学术成果奖&rdquo;，该奖项中获奖作品包括著作类51项、论文类19项、译著类6项。在学术报告阶段，学者代表就伦理学原理、中国传统伦理思想、西方伦理思想、应用伦理学等领域作了主题发言，与会学者对相关主题、当前伦理学热点和难点问题及学科发展方向等进行了热烈的讨论。 </p>\r\n<p>　　（编辑：刘伟伟）<br />\r\n</p>",289,1703);
$z[5][4]['name']="body";
$z[6]=Array("field","1290137280",1705,1755);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c101126/z2mfkyfhm2fzmhf-mkbhz_lit.jpg",1757,1849);
$z[7][4]['name']="litpic";

?>