{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院获评“2010年度北京市优秀教学团队”和“精品课程”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-05-05 09:04:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，北京市教育委员会公布了2010年度北京市精品课程和优秀教学团队评审结果。中国人民大学3门课程、3个教学团队分别获评2010年度北京市精品课程、优秀教学团队。其中，法学院韩大元教授领衔的&ldquo;宪法学与行政法学&rdquo;教学团队入选2010年度北京市优秀教学团队，冯玉军教授主讲的&ldquo;法律经济学&rdquo;课程入选2010年度北京市精品课程。 </p>
<p>　　优秀教学团队和精品课程建设是教育部和北京市&ldquo;质量工程&rdquo;的重要组成部分。优秀教学团队建设是为了提高教师素质和教学能力，建设一支理论功底深厚、实践经验丰富、教学水平高，富有协作和创新精神，可持续发展的优秀教学队伍，形成跨学科的教学团队效应，以适应教学改革发展的需要。精品课程是具有一流教师队伍、一流教学内容、一流教学方法、一流教材、一流教学管理等特点的示范性课程。精品课程建设始于2003年，其目的是利用现代化的教育信息技术手段，实现优质教学资源共享，同时努力提升教师队伍的整体水平。2007年，精品课程建设和教学团队建设被纳入&ldquo;质量工程&rdquo;。 </p>
<p>　　法学院历来重视精品课程和教学团队建设，并从政策和经费上给予了大力支持，截止到目前，共建设各类精品课程22门。本次评选中国共有3门课程、3个教学团队入选，其中法学院获选1门课程和1个教学团队。</p>
<p>　　（编辑：张利英）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
