<?php
$z[0]=Array("addurls","http://news1.ruc.edu.cn/102449/102450/102495/list.html\r\nhttp://news1.ruc.edu.cn/102449/102450/102495/list_12.html",3,145);
$z[1]=Array("batchrule","",148,181);
$z[2]=Array("regxrule","",184,215);
$z[3]=Array("areastart","<table width=\"743\" cellspacing=\"1\" bgcolor=\"#CACCCE\">",218,304);
$z[4]=Array("areaend","<table width=\"100%\"><tr><td align=right>",307,376);

?>