{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}生活处处是艺术：艺术学院2010“春艺盎然”学生文化周圆满落幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2010-05-31 08:45:38{/dede:field}
{dede:field name='body'}<p>　　近日，艺术学院2010&ldquo;春艺盎然&rdquo;学生文化周圆满落幕。整个文化周活动形式多样、异彩纷呈，得到了广大师生的热烈欢迎和广泛赞扬。 </p>
<p>　　作为艺术学院品牌学生活动，&ldquo;春艺盎然&rdquo;学生文化周已成功举办多年。今年的活动在以往的基础上又有了新的突破，分为文化衫、文化鞋、文化帽设计制作，飞机模型DIY，书法、画扇面、制脸谱等。各项活动结合艺术专业特色，发挥同学们的艺术特长，充分展现了&ldquo;艺术源于生活，生活处处是艺术&rdquo;的文化理念，体现了艺术学院凝聚向上、创新发展的精神风貌，对于发掘艺术人才和文化形式、丰富广大师生的校园文化生活具有积极作用。</p>
<p>　　（编辑：安娜）&nbsp;</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
