<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","公共管理学院蓝志勇教授参加全国人才工作会议并获聘“千人计划”国家特聘专家",89,199);
$z[2][4]['name']="title";
$z[3]=Array("field","",201,240);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",242,293);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-06-07 03:58:35",295,354);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月25-26日，公共管理学院副院长蓝志勇教授参加了中共中央、国务院召开的全国人才工作会议，并获聘&ldquo;千人计划&rdquo;国家特聘专家。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 胡锦涛、吴邦国、温家宝、贾庆林、李长春、习近平、李克强、贺国强、周永康出席会议。胡锦涛在会上发表重要讲话。大会向20名&ldquo;千人计划&rdquo;国家特聘专家代表颁发了证书。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;千人计划&rdquo;是中组部会同有关部门，于2008年组织实施的引进海外高层次创新创业人才工程。&ldquo;千人计划&rdquo;围绕国家发展战略目标，用5到10年时间，引进2000名左右人才并有重点地支持一批能够突破关键技术、发展高新产业、带动新兴学科的战略科学家和领军人才来华创新创业。截至目前，&ldquo;千人计划&rdquo;已分3批引进662名海外高层次创新创业人才，第四批&ldquo;千人计划&rdquo;的申报评审工作正在进行中。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n</p>",356,1291);
$z[6][4]['name']="body";
$z[7]=Array("field","",1293,1332);
$z[7][4]['name']="litpic";

?>