{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“大学与社会：走进商业连锁世界”大型公益系列讲座启动仪式暨首场讲座成功举办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2011-04-12 02:59:10{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4月6日下午14时，逸夫会议中心第二报告厅热闹非凡。由社会与人口学院与中国连锁经营协会共同主办的&ldquo;大学与社会：走进商业连锁世界&rdquo;大型公益系列讲座启动仪式暨首场讲座在这里举行。参加本次启动仪式的有社会与人口学院党委书记郭星华教授、中国人民大学招生就业办公室主任赵顶峰、社会与人口学院教师于显洋教授以及中国连锁经营协会会长郭戈平、副会长朱丽筠、秘书长裴亮、内蒙古餐饮连锁小肥羊有限公司副总裁卢文兵等。启动仪式由于显洋教授主持。启动仪式结束后，卢文兵以小肥羊公司的发展为案例，为现场师生作了专题讲座。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 仪式伊始，中国连锁经营协会秘书长裴亮首先致辞。他提到，中国连锁经营发展时间不长，但是很多品牌正在迅速成长，希望本次公益系列讲座能给同学们一个了解连锁经营的机会，同时通过不同企业的创业故事，给同学们带来启发。随后，社会与人口学院党委书记郭星华教授致辞。他说，学院不仅重视同学们的专业理论知识的学习，还十分注重社会实践能力的培养，这与学院的宗旨是密切相关的。他希望同学们能将理论知识与实践相结合，珍惜这次难得的机会，认真聆听与思考，将来有所成就。接下来，中国连锁经营协会会长郭戈平宣布本次共公益系列讲座正式启动。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2llkfhymf-byfbb.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 启动仪式结束后，首场讲座正式开始。小肥羊餐饮有限公司副总裁卢文兵以该公司的成长经历为引子，向在场师生讲授了企业创业与发展之道。他简单回顾了小肥羊从1999年创立直至近年来成为国内最大餐饮企业的发展历程，期间多次引用相关数据进行详细解说，并旁征博引，援引多家企业和成功企业家的案例进行深入独到的讲述。他重点提到了该公司变革的几个关键因素，如发展模式的转变、先进管理模式的采用以及对经营理念的坚持等。他肯定了企业发展中创新的重要性。他还谈到自己的一些思考，如当下创业的环境、大学生素质的培养等。他鼓励在校大学生深入社会中开展实践，认为这将是成长的重要经历。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2llklnykf-y2lfy.jpg" width="500" height="333" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 讲座结束后，于显洋教授进行了简单的总结。他说道，思考方式的培养非常重要，并希望同学们能够通过成功企业家的亲身故事能够有所收获。最后，卢文兵副总裁还与现场师生进行了答疑互动。退场时，现场观众对卢文兵副总裁的精彩报告报以热烈掌声。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据了解，&ldquo;大学与社会：走进商业连锁世界&rdquo;大型公益系列讲座本学期共计十场，接下来每周都会邀请多个成功企业的著名企业家走进校园，开展专题讲座。</p>
<p>（编辑：刘德萍）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2llkfhymf-byfbb_lit.jpg{/dede:field}
