{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“社会分层与流动研究委员会”年会在中国人民大学举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2009-05-21 10:37:49{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月14日至16日，国际社会学学会（ISA）&ldquo;社会分层与流动研究委员会&rdquo;（RC28）2009年年会在中国人民大学逸夫会议中心举行。这是该委员会自成立以来，首次在中国大陆举办年会。本次年会的主题为&ldquo;社会不平等与社会变迁&rdquo; (Social Inequality and Social Change)。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次RC28年会由中国人民大学社会与人口学院承办，中国社会科学院社会学研究所、北京大学社会学系、清华大学社会学系、美国密歇根大学社会学系协办。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届RC28主席为美国加利福尼亚大学洛杉矶分校教授Robert D. Mare。本次年会的主持人事中国人民大学社会与人口学院翟振武教授，年会学术委员会主席为谢宇教授、李路路教授。国内外著名社会学家Robert M. Hauser、Donald J. Treiman、Michael Hout、李培林、李强、卢汉龙等在年会上发表主题演讲，206位来自世界各地的社会分层与流动领域的学者参加了本次年会，230名来自于北京和全国各地共学生注册参加了本次年会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在5月14日上午的开幕式上，国家人口和计划生育委员会副主任王培安、中国人民大学常务副校长袁卫出席并发表致辞。5月15日晚，年会邀请美国国家科学院院士Robert M. Hauser，以&ldquo;Cognition and Consequences of Cognition across the Life Course&rdquo;为题，为400余师生举办了一场公开讲座。14日至16日期间，年会共举办了30场学术会议，150位学者就110篇论文发表主题演讲，90位学者以海报演讲的方式展示了60项研究成果。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 与会学者深入探讨了教育、收入、婚姻与家庭、健康、职业机会、性别、文化、种族、住房等领域的社会不平等现象，以及劳动力市场、社会网络和国际、城际、城乡移民等课题，既增进了国际社会学界的前沿交流，又向世界展示了中国社会学学科建设的成果，提升了中国人民大学的国际性，更有利于我们借鉴国外的先进理论和方法，推动我国的社会和谐与科学发展。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次年会的筹备工作历时1年，12名教师和35名学生志愿者参与其中。年会的成功举办受到了RC28委员会和与会国内外专家的高度赞扬。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，国际社会学学会&ldquo;社会分层与流动专业研究委员会&rdquo;成立于1950年。该委员会以提高社会分层与流动领域的研究质量、促进该领域科学信息的国际交流为宗旨，在国际社会学界以及国际社会科学领域中都具有非常广泛而深刻的影响。目前该委员会拥有来自70多个国家和地区的注册会员约1100人。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
