{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}社会与人口学院举办“骄子饺子”新年嘉年华{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}社会与人口学院{/dede:field}
{dede:field name='pubdate'}2010-01-04 09:33:46{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 为庆祝新年的到来， 1月3日晚，社会与人口学院09级社会学硕士党支部联合班委会、团支部，共同举办了&ldquo;骄子&bull;饺子&rdquo;嘉年华活动，使得这个寒冷的冬日洋溢着家一般的温暖。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlknkbfhmzf-lkmh2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Happy New Year&rdquo;的字体和五彩斑斓的气球为中区食堂增添了节日的气息。同学们自愿组成&ldquo;小郭饺子&rdquo;、&ldquo;大阔饺子&rdquo;和&ldquo;QQ&rdquo;三支队伍参赛。和面、簳皮儿、包馅，大家分工协作，忙得不亦乐乎；飞鸟、金鱼、星星、元宝，各式饺子造型创意迭出。最终，&ldquo;小郭饺子&rdquo;队以半小时238个饺子的战绩获得&ldquo;最快速度奖&rdquo;，李阔和武国英同学的作品被大众评审推选为&ldquo;最佳造型奖&rdquo;。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlknkbym2kf-hlmh2.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 热腾腾的饺子端上来后，同学们喜笑颜开地围坐在桌旁，一边品尝着自己的劳动成果，一边谈天说地，可谓其乐融融、亲如一家。不幸吃到糖果馅的饺子的同学还被要求出节目、做游戏，引发了欢声笑语不断。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;据党支部书记冯启娜介绍，09级社会学硕士党支部自本学期组建以来，以思想建设为先导，以组织建设为中心，开展了学习十七届四中全会精神、参观&ldquo;复兴之路&rdquo;展、趣味运动会等内涵丰富、形式活泼的主题活动，增强了支部和班级的凝聚力和向心力，切实发挥了基层学生党组织的政治核心和战斗堡垒作用。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlknkbfhmzf-lkmh2_lit.jpg{/dede:field}
