{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}江苏省委副书记朱善璐会见纪宝成校长　双方就加强省校合作事宜交换意见{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='pubdate'}2011-04-01 10:18:32{/dede:field}
{dede:field name='body'}<p>　　3月31日，江苏省委副书记朱善璐在南京会见纪宝成校长，双方就加强省校合作事宜交换了意见。南京市市长、人民大学校友季建业参加会见。</p>
<p>　　纪校长还应邀在南京财经大学做专题报告。在题为《深化高等教育改革的若干问题》的报告中，纪宝成校长从高等教育发展的一般规律和体制机制改革两个方面论述了提升教育质量，扩大优质教育资源，建设高教强国的主要任务。纪校长还对高等教育改革必须坚持实事求是的思想路线进行了深入阐述，他提出，实事求是是一种政治品质和精神境界，大学要具备高度的社会责任感，坚持实事求是地教书育人、研究学问、办好高等教育。南京财经大学徐从才校长主持报告会。</p>
<p>　　在宁期间，纪校长还会见了江苏省委常委、组织部长石泰峰。</p>
<p>　　（编辑：苏璇）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
