
   {dede:match}<td height="200" valign="top"><br>[内容]</td>
              </tr>
              <tr>
                <td height="30">{/dede:match}
   {dede:trim replace=""}<span([^>]*)>{/dede:trim}
{dede:trim replace=""}</span>{/dede:trim}
{dede:trim replace=""}<FONT([^>]*)>{/dede:trim}
{dede:trim replace=""}</FONT>{/dede:trim}
{dede:trim replace=""}来源：人大新闻网{/dede:trim}
{dede:trim replace=""}</TD></TR></TBODY></TABLE>{/dede:trim}
{dede:trim replace=""}<TABLE width="100%">([^>]*)<TD style="PADDING-BOTTOM: 20px; LINE-HEIGHT: 22px; PADDING-LEFT: 20px; PADDING-RIGHT: 20px; FONT-SIZE: 10.5pt; TEXT-DECORATION: none" vAlign=top width="90%" align=left>{/dede:trim}
   {dede:function}{/dede:function}
