{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院开办广西北部湾经济区高级管理人员培训班{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-11-24 10:23:25{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月21日上午，中国人民大学环境学院主办的&ldquo;广西北部湾经济区高级管理人员培训班&rdquo;开班典礼在理工楼905会议室隆重举行。中国人民大学常务副书记兼副校长牛维麟出席典礼并发表讲话。开班典礼由环境学院党委书记刘鹏主持。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;常务副书记兼副校长牛维麟在致辞中强调，建立校地合作平台，充分发挥高校自身蕴藏的丰富智力资源服务地方经济建设，是实现校地双赢、共同发展的一个重要课题，他表示非常欢迎并大力支持广西方面以中国人民大学为依托，以多种方式加快培养北部湾经济区开放开发所需的高层次、创新型和复合型人才。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfllzznhf-zykmf.jpg" /></p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 常务副书记兼副校长牛维麟向全体学员介绍了中国人民大学的光荣历史。他说，中国人民大学是我党亲手创办的第一所新型大学，经过七十年的发展，已成为&ldquo;中国人文社会科学高等教育的重镇&rdquo;和&ldquo;共和国建设者的摇篮&rdquo;，被广泛誉为&ldquo;中国人文社会科学领域的一面旗帜&rdquo;和我国经济建设和社会发展的&ldquo;思想库&rdquo;。</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 副书记兼副校长牛维麟说，广西有着优越的区位优势、资源条件和政策环境，在中国西部地区开放开发和中国&mdash;东盟自由贸易区建设中具有重要的战略地位。尤其是国家批准建设的广西北部湾经济区，对于国家实施区域发展总体战略和互利共赢的开放战略具有重要意义。加快推进北部湾经济区开放开发，既关系到广西自身发展，也关系到国家整体发展。在这样的重要背景和良好的发展环境下，人民大学与广西在人才培养与干部培训方面开展合作，有着巨大的空间和广阔的前景。</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 广西自治区北部湾开发办公室副主任李延强代表所有培训班学员，对中国人民大学为此次培训班所做的努力表示感谢，并呼吁广大学员能够珍惜这次宝贵的培训机会，不断加强自身的理论水平和管理能力，为广西乃至国家的经济建设做出积极贡献。</p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据悉，今年2月中国人民大学与广西自治区政府签订校地合作协议。按照协议，人民大学与广西壮族自治区就人才培养、项目开发、课题研究、挂职锻炼、实习就业、选调生推荐等方面与进行全面合作。广西北部湾经济区高级管理人员培训班是在该协议框架下，受广西自治区党委组织部、广西北部湾开发管理办公室委托举办的第一个人才培训合作项目。有50多名来自广西北部湾经济区六市的中层管理骨干参加为期14天的培训。该班受到人民大学的高度重视，环境学院院长马中、经济学院副院长刘元春、国际关系学院外交学系主任金正昆等20多名知名教授参加授课。 <br />
</p>
<p align="center"><img alt="" src="/uploads/allimg/c100622/z2kkzlnfllymnnf-2mhkm.jpg" /></p>
<p align="left">（编辑：刘恒）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfllzznhf-zykmf_lit.jpg{/dede:field}
