{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哈佛大学哲学系主任肖恩凯利教授访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图/文 哲学院{/dede:field}
{dede:field name='pubdate'}2010-12-23 11:27:07{/dede:field}
{dede:field name='body'}<p>　　应人民大学哲学院的邀请，哈佛大学哲学系主任肖恩&bull;凯利（Sean Kelly）教授12月18日-21日到人民大学访问。12月18日杨慧林副校长接见了凯利教授。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mlmbmhkf-zbkhn.jpg" /></p>
<p>　　在轻松友好的氛围中凯利教授和杨校长分别介绍了哈佛大学和中国人民大学的办学特色和学生培养情况，并探讨了未来两校在哲学领域进行多方面、多渠道交流与合作的可能性。杨慧林副校长还饶有兴趣地对凯利教授即将出版的新书《万物闪耀》中的文艺美学思想进行了讨论。参加会见的还有哲学院郝立新院长、韩东晖副院长、曾在哈佛大学访问过的现代逻辑与科学哲学研究所所长刘晓力教授、伦理学专业龚群教授，以及在凯利教授指导下目前在哈佛访学的哲学院博士生陶孝云。会见结束后凯利教授参观了人民大学哲学院，进一步深入了解了哲学院的教学和科研工作。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2mlmmlk2f-2n2nh.jpg" /></p>
<p>　　12月19日凯利教授参加了由人民大学哲学院、哈佛大学哲学系和现代逻辑与科学哲学研究所联合主办的&ldquo;2010年知觉与行动北京研讨会（2010 Beijing Workshop on Perception and Action）&rdquo;，并在会上做了基调报告&ldquo;思想与行动（Thought and Action）&rdquo;。20日凯利在&ldquo;哲学家论坛暨科学-社会-人文论坛&rdquo;上做了&ldquo;心理学哲学前沿问题&rdquo;（ Current Issues in Philosophy of Psychology）的报告，21日与现代逻辑与科学哲学研究所的部分博士生座谈，就心灵哲学和认知科学问题进行了细致的讨论。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王强）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2mlmbmhkf-zbkhn_lit.jpg{/dede:field}
