{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}昆士兰大学代表到中国人民大学澳大利亚研究中心参观交流{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}外国语学院{/dede:field}
{dede:field name='pubdate'}2010-10-15 10:13:25{/dede:field}
{dede:field name='body'}<p>　　10月14日下午，来自澳大利亚昆士兰大学的代表们来到中国人民大学澳大利亚研究中心进行参观和交流，来访代表分别是昆士兰大学国际部主任Alan Lawson,项目官员Liz Simmonds，继续教育项目负责人ChristineBundesen。此次活动在澳大利亚研究中心办公室举行，由外国语学院常务副院长、澳大利亚研究中心主任张勇先教授亲自接待。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101124/z2mfbnmmh2mbfbf-zzzfl.jpg" />&nbsp;</p>
<p>　　张勇先教授向外宾简介了澳大利亚研究中心的发展历程、课程设置、教材选择、成员的学习成果，以及澳研中心为了促进中澳发展交流举办的特色活动；他还向外宾介绍了中国人民大学暑期小学期项目，邀请昆士兰大学教授前来任教。来访代表对澳大利亚研究中心的活动和中国人民大学的英语培训方法表示了极大的兴趣，Alan Lowson表示，昆士兰大学愿意与外国语学院开展教师互访、学生互派等活动，以共同提高两校学术水平并促进中澳两国文化交流发展。 </p>
<p>　　随后，中心成员展示了澳大利亚文化中心的官方网站，并向代表们赠送精美纪念品。 </p>
<p>　　中国人民大学澳大利亚研究中心成立于1999年11月19日，是一所以研究澳大利亚社会、文化及澳大利亚英语为特色的研究与教学机构。截至2010年8月，中国人民大学澳大利亚研究中心已有32人获得硕士学位。目前，中心有13名教师成员，14名在读硕士研究生和3名在读博士研究生。</p>
<p>　　（编辑：易晨）&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnmmh2mbfbf-zzzfl_lit.jpg{/dede:field}
