{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“传播学与认知科学国际学术研讨会”在中国人民大学成功召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}图/文 新闻学院{/dede:field}
{dede:field name='pubdate'}2010-12-23 08:57:02{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月18日至19日，由中国人民大学新闻学院和泛媒研究院共同主办的&ldquo;传播学与认知科学国际学术研讨会&rdquo;在人民大学隆重召开。本次研讨会邀请了多位国内外认知神经科学和传播学研究的知名专家学者，旨在拓展传播学研究方法视野，提升传播学科研究的整体力量，促进多学科间的交流融合。 </p>
<p>　　中国人民大学新闻学院常务副院长倪宁教授、副院长喻国明教授、泛媒研究院院长、密歇根大学州立大学李海容教授以及学校科研处相关负责人等出席会议。美国马萨诸塞大学Daniel Anderson教授、波兰国家科学研究院Rafal Ohme教授参会并做主旨发言。其他来自包括日本、马来西亚等国高校的新闻传播学及认知科学的教师及博士生五十余人参与了研讨会期间的各种讨论和交流活动。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110113/z2mhnnllnfhz2nf-lzy2n.jpg" /></p>
<p>　　新闻学院常务副院长倪宁教授在致辞中表示，作为一个年轻的学科，传播学还有很多领域值得深入研究，而与其他学科如认知科学的互动交流则将有利于双方优势互补，拓展研究视野。杨艳萍副处长在会上致辞，转达了学校领导对本次国际学术会议的关心和重视。 </p>
<p align="center">&nbsp;<img alt="" src="/uploads/allimg/c110113/z2mhnnllnfkbkf-hhkkk.jpg" /></p>
<p align="left">　　本次研讨会内容包括传播学与认知科学对话、学界与业界对话等版块。会上，喻国明教授有关&ldquo;瞬间认知效果&rdquo;研究的介绍为突破当前传播学研究的&ldquo;瓶颈&rdquo;提供了可能的范式。人民大学博士后李彪还在会上展示了中国人民大学认知与传播实验室的四大研究成果，即简体中文报纸头版阅读规律研究、恐惧诉求的劝服模式ERP实验研究、意识阈限下信息刺激传播效果研究以及纸质报纸和电子书两种介质的ERP实验研究。 </p>
<p align="left">　　随后，日本电通广告有限公司策略开发本部部长小岛哲郎先生、华通明略研发总监谭北平先生、北京圣坤燕仑科技有限责任公司赵仑教授等业界精英就目前神经营销学的前沿议题和研究方法与学界进行了深刻探讨。 </p>
<p align="left">　　研讨会上还举行了&ldquo;国际传播与认知科学研究学会&rdquo;揭牌仪式。该研究学会旨在为传播学与认知科学的互动交流提供国际学术平台，以鼓励和培养更多的青年学术骨干在这两个研究领域作出更多探索。&nbsp;&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnllnfnzz2f-bnlk2.jpg" /></p>
<p align="left">　　作为本次研讨会系列活动之一，美国马萨诸塞大学Daniel Anderson教授和波兰国家科学研究院Rafal Ohme教授分别于12月20日和21日为新闻学院师生进行了讲座。两位教授通过将认知科学研究的理论、方法和技术应用于广告、儿童教育电视节目制作等领域，考察传播效果的变动。这种跨学科的研究方式为传播学研究提供了新的视角和图景，受到学院师生的欢迎。 </p>
<p align="left">　　（编辑：王强）<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnllnfhz2nf-lzy2n_lit.jpg{/dede:field}
