{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院叶剑平教授受邀出席深圳坪山新区管委会专题咨询座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-12-30 09:58:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月24日，受深圳市坪山新区管委会邀请，中国人民大学公共管理学院叶剑平教授赴该区就&ldquo;国土资源部和深圳市人民政府共建高度城市化地区土地管理制度改革试点&rdquo;专题接受咨询并参加座谈会。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当天，叶剑平教授就当前我国土地利用与管理热点难点问题与坪山新区管委会冯现学主任及新区国土规划、城市建设、发展改革、社会保障等相关部门进行深入交流和探讨，接受主办方咨询，并就新区发展、土地整备、征地拆迁、都市更新、土地&ldquo;资源、资产、资本&rdquo;管理、土地节约集约利用等内容讲授了自己的观点，并结合坪山新区发展现状和未来发展定位就新区土地利用与管理改革探索提出了相关建议。咨询座谈会结束后，坪山新区管委会党工委杨绪松书记会见并宴请叶剑平教授一行。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 今年1月17-18日，叶剑平教授曾受邀参加了&ldquo;新动力之城&bull;未来之城&rdquo;坪山新区发展战略国际咨询峰会并作主题发言。11月2日，叶剑平教授受邀为该区国土规划系统全体干部职工作了&ldquo;转型时期的城镇化与土地利用思考&rdquo;的专题讲座。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
