{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}日本神奈川大学法学院细田孝一教授参观法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-23 04:29:21{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;3月18日下午，日本神奈川大学法学院细田孝一教授在早稻田大学博士、中国政法大学教师陈景善的陪同下参观了法学院。院长助理宋彪副教授接待了细田孝一教授，并向来宾介绍了法学院发展情况。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;宋彪副教授首先与细田孝一教授就中国《反垄断法》制订与实施效果进行了深入探讨。双方就中央与地方政府在反垄断执法中的职责分工、法律责任分配、外资并购中资企业的实施细则、产业政策与国家安全审查等问题交换了各自看法。随后，宋彪副教授介绍了法学院东亚法学院的筹备、国际化战略、60周年院庆，以及反垄断法国际研讨会、反垄断法网站建设等情况，并表示欢迎细田孝一教授今后参加法学院相关学术活动。细田孝一教授欣然应允，并对东亚法学院、东亚产业政策法论坛等思路表示极大赞赏。最后，宋彪副教授陪同细田孝一教授一行参观了法学院图书馆、模拟法庭、教授工作室、法律诊所等。细田孝一教授对法学院为学生提供的舒适环境极为赞赏，感叹学生在人大法学院求学&ldquo;很幸运、很幸福&rdquo;。</p>
<p align="center"><img src="/uploads/allimg/c100619/z2kymzyl2bbzbmf-znmk2.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;细田孝一教授曾就职于日本公正交易委员会30余年，期间先后被委派到日本经济企划厅、外务省、财务省等任职。我国在制定《反垄断法》时，细田孝一教授也曾作为外国专家多次访问全国人大法工委并发表相关法律意见。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyl2bbzbmf-znmk2_lit.jpg{/dede:field}
