{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}中策资本总裁黄友权受聘人大校董并设立中策资本奖助学金励学助教{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}学校办公室{/dede:field}
{dede:field name='pubdate'}2010-12-21 04:05:31{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月21日，中策资本集团总裁黄友权受聘担任中国人民大学董事会董事，中策资本集团在中国人民大学设立&ldquo;中策资本奖助学金&rdquo;以励学助教。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中策资本集团总裁黄友权、中融资产管理有限公司总经理李兴录，中国人民大学党委常务副书记牛维麟、党委副书记马俊杰出席聘任仪式，中国人民大学教育基金会秘书长彭和平主持仪式，学校办公室、学生处等部门负责人参加。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2m2zlnnyf-z2nkl.jpg" />&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛维麟常务副书记向黄友权颁发中国人民大学董事会董事聘书、董事纪念牌。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2m2zklhf-22mzk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 马俊杰副书记与黄友权总裁分别代表双方签署&ldquo;中策资本奖助学金&rdquo;合作协议书。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 黄友权总裁在致辞中说，中策资本集团的发展历程和他本人的从业经历一再表明，知识改变命运、创新推动发展。他始终关心、关注高等教育事业和青年人才培养工作，希望通过设立奖助学金的方式鼓励青年学生努力奋发、积极进取，也希望中策资本集团与中国人民大学能在产学研结合和科技成果转化方面有更好的合作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 牛维麟常务副书记介绍了中国人民大学近年来的发展盛况和中国人民大学董事会组建情况。他指出，借助社会力量励学助教、汲取民间智慧办好大学，是中国人民大学成立董事会的重要目的。自校董会成立以来，各位董事为学校的改革发展作出了重要贡献，希望黄友权总裁能在人文社会科学成果转化、推进学校事业进一步提升等方面继续给予支持。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnn2m2zkkh2f-l2mfb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnn2m2zlnnyf-z2nkl_lit.jpg{/dede:field}
