<?php
$z[0]=Array("match","<tr><td width=\"90%\" align=\"left\" valign=\"top\" style=\"PADDING-RIGHT: 20px; PADDING-LEFT: 20px;PADDING-BOTTOM: 20px;FONT-SIZE: 10.5pt; LINE-HEIGHT: 22px; TEXT-DECORATION: none\">[─┌╚▌]</td>",5,216);
$z[1]=Array("trim","ги▒р╝н ╤ю─мгй",221,268);
$z[1][4]['replace']="";
$z[2]=Array("trim","ги▒р╝н ░▓─╚гй",270,317);
$z[2][4]['replace']="";
$z[3]=Array("function","",322,353);

?>