<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","瑞士高级公共管理研究院Jean-Patrick VILLENEUVE博士访问中国人民大学公共管理学院并授课",89,210);
$z[2][4]['name']="title";
$z[3]=Array("field","",212,251);
$z[3][4]['name']="writer";
$z[4]=Array("field","公共管理学院",253,304);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-11-18 08:42:16",306,365);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月12日，应中国人民大学公共管理学院邀请，瑞士高级公共管理研究院助理教授、公共管理学部主任Jean-Patrick VILLENEUVE博士访问中国人民大学公共管理学院，并给公共管理学院行政管理学系硕士开设题为&ldquo;Transparency in Public Management: Issue and Challenge &rdquo;（公共管理中的透明度问题：问题与挑战）的专题讲座。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Villeneuve博士的主要研究方向是公共部门组织绩效管理、公共服务体系建设以及博彩业监管与治理等。在专题授课中，他从近年来西方国家所兴起的信息公开建设运动为出发点，对欧洲各国政府的行政信息公开的过程进行了描述，并对其程度进行了测量与分析，并以瑞士联邦政府的信息公开法的制订和实施过程为典型案例，分析了欧洲国家政府信息公开和透明度建设的现状及所面临的挑战，具有较大的启发性。公共管理学院行政管理学系教师刘鹏博士参与了此次专题授课的组织工作。 </p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n</p>",367,1300);
$z[6][4]['name']="body";
$z[7]=Array("field","",1302,1341);
$z[7][4]['name']="litpic";

?>