{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院马中院长参加“全球当前的环境挑战与政府应对措施研讨会”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2008-05-20 10:34:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2008年4月25日至28日，环境学院院长马中教授应南加州华人环保协会（Southern California Chinese American Environmental Protection Association）之邀，参加在美国加利福尼亚州（加州）洛杉矶市举行的&ldquo;全球当前的环境挑战与政府应对措施研讨会&rdquo;（Symposium on Global Emerging Environmental Challenges and Government Responses ）。美国联邦环保局和加州环保局的相关高级官员、高等院校环境专业教学与科研人员及大型企业环保高级技术和管理人员参加了此次会议。研讨会专题涵盖了空气、土壤与水、固体废物、环保技术与服务等环境保护领域。此次研讨会的目的是将美国环保管理经验及环保技术介绍给全球的华人，并促进了全球华人环保界同行的交流。马中教授在会上就&ldquo;中国水污染控制&rdquo;发表了演讲。会议期间，马中教授还同美国加州环保局洛杉矶区域水质管理局专家就水质监测和管理进行了深入讨论。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：梁瑾）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
