{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}公共管理学院董克用院长率团参加第六届两岸四地公共管理学术研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-09-02 04:38:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8月19-20日，公共管理学院董克用院长率团参加了在高雄举行的第六届两岸四地公共管理学术研讨会。本次大会由台湾义守大学公共政策与管理学系承办，会议主题为&ldquo;华人地区公共治理变革与实践&rdquo;。本次大会研究专题十分广泛，涉及公共治理与公共部门改革；全球治理、两岸关系与永续发展；区域治理与都会发展；城乡发展与农村改造；协力型政府与新公共服务；公民社会、公众参与与社区治理；人事行政制度与人力资源管理；公共财政与社会福利政策；廉能政府与行政伦理、电子治理等领域的热点问题。来自两岸四地的81所大学的248位学者参加本次盛会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 公共管理学院院长董克用教授在大会开幕式上致辞。他简要回顾了历届两岸四地公共管理学术研讨会的发展历程，指出中国大陆经济社会发展进入转型期，在经济取得高速发展，百姓生活逐步富裕起来的同时，在公共管理和公共政策领域出现了诸多新问题、新情况，这为广大学者提出了挑战与研究空间。两岸四地学者具有共同的文化背景，需要通过不同层面和不同形式的学术交流和研究合作，诠释公共管理领域理论和实践，共同探讨华人地区的公共管理和公共政策，形成两岸四地公共管理学术研究特色。两岸四地公共管理学术研讨会为两岸四地学者提供了一个很好的研究和交流平台。 </p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhnmkhhkf-zkh2n.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 研讨会上，公共管理学院董克用院长、蓝志勇副院长、魏娜教授分别参加了公共管理研究发展、公共管理教育与实践发展、两岸四地大学合作交流学术论坛，就上述问题与两岸四地学者进行了沟通。公共管理学院魏娜教授、孙玉栋教授及胡平、张秀智、郑国、段晖、钟卫等老师分别在会上发表了论文，并与参会学者进行了广泛而深入的交流和讨论。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 自中国人民大学公共管理学院于2005年发起创办首届两岸四地公共管理学术研讨会以来，该研讨会每年举办一次，澳门大学、台湾世新大学、南昌大学、香港城市大学、台湾义守大学先后承办了2006-2010年的会议。六年来，在两岸四地公共管理领域学者的积极参与下，研讨会的研究议题呈现多元化趋势，学者之间的沟通更加深入，校际交流也进一步得到增强。2011年两岸四地公共管理学术研讨会将由中国人民大学公共管理学院承办。</p>
<p align="center"><img src="/uploads/allimg/c101124/z2mfbnnhmfzbyhf-2bkhl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：徐晶晶）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbnnhnmkhhkf-zkh2n_lit.jpg{/dede:field}
