<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","哲学院勇夺男篮甲级联赛冠军",89,153);
$z[2][4]['name']="title";
$z[3]=Array("field","",155,194);
$z[3][4]['name']="writer";
$z[4]=Array("field","哲学院",196,241);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-05-25 11:33:44",243,302);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p align=\"center\">&nbsp;<img src=\"/uploads/allimg/c100622/z2kkzlnhylnfnbf-lmmb2.jpg\" alt=\"\" /></p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月24日，中国人民大学男篮甲级联赛决赛行，哲学院与历史学院激烈争夺冠亚军，最终哲学院以71：43比分战胜历史学院，获得本年度男篮总冠军。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）</p>",304,690);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100622/z2kkzlnhylnfnbf-lmmb2_lit.jpg",692,784);
$z[7][4]['name']="litpic";

?>