{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}哲学院勇夺男篮甲级联赛冠军{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-05-25 11:33:44{/dede:field}
{dede:field name='body'}<p align="center">&nbsp;<img src="/uploads/allimg/c100622/z2kkzlnhylnfnbf-lmmb2.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5月24日，中国人民大学男篮甲级联赛决赛行，哲学院与历史学院激烈争夺冠亚军，最终哲学院以71：43比分战胜历史学院，获得本年度男篮总冠军。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnhylnfnbf-lmmb2_lit.jpg{/dede:field}
