{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院高铭喧、王利明、韩大元、林嘉等十位教授参加全国人大常委会法制工作委员会新春专家座谈会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-02-02 07:56:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月26日，法学院高铭喧教授、王利明教授、韩大元教授、林嘉教授、胡锦光教授、朱景文教授、陈卫东教授、徐孟洲教授、王作富教授、江伟教授参加了全国人大常委会法制工作委员会新春专家座谈会。高铭喧教授、韩大元教授、朱景文教授围绕&ldquo;中国特色社会主义法律体系特色的主要表现&rdquo;、&ldquo;进一步提高立法质量&rdquo;以及刑事立法体系的建设等问题做了专题发言。</p>
<p>（编辑&nbsp; 燕燕）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
