<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","北京市经济学总会新春工作会议在人民大学召开",89,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","经济学院",212,259);
$z[4][4]['name']="source";
$z[5]=Array("field","2010-01-22 03:05:32",261,320);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1月20日，北京市经济学总会新春工作会议在中国人民大学经济学院0734会议室召开。来自中国人民大学、北京大学、清华大学、北京师范大学、对外经贸大学、中央财经大学、中央党校、中国社会科院等单位的18位常务理事、监事参加了会议。 </p>\r\n<p align=\"center\"><img src=\"/uploads/allimg/c100619/z2kymzhklzmyhlf-mlybk.jpg\" width=\"500\" height=\"333\" alt=\"\" /></p>\r\n<p><br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学副校长林岗教授出席并主持了会议，经济学院院长杨瑞龙教授，中国改革与发展研究院常务副院长黄泰岩教授，经济学院胡乃武教授、李军林教授出席了会议。会议总结了2009年学会工作，商讨并确定2010年工作计划安排。会上，大家还对当前我国普遍关注的经济问题及宏观经济形势进行了热烈的讨论。 </p>\r\n<p>\r\n</p>",322,1096);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c100619/z2kymzhklzmyhlf-mlybk_lit.jpg",1098,1190);
$z[7][4]['name']="litpic";

?>