{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}伦敦城市大学Steve Schifferes教授访问新闻学院并为人大学子作讲座{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/新闻学院 陈荣华{/dede:field}
{dede:field name='pubdate'}2010-06-01 09:04:24{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 伦敦城市大学传媒教授Steve Schifferes于5月31日来人民大学新闻学院进行访问。人民大学新闻学院常务副院长倪宁教授会见了Steve Schifferes教授，就研究生课程设置、国际交流与合作、新闻教育的现状与趋势及新闻传播的研究方向等多个方面进行了交流。院长助理等相关负责人参与了会议。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Steve Schifferes教授面对人大学子作了题为&ldquo;媒体在金融危机中的作用&rdquo;的讲座。他从金融的全球化、金融媒体的转变、次贷危机的发生、媒体对金融危机的报道等方面重点阐释媒体在金融危机中应该承担的责任。 Steve Schifferes教授还与学生进行交流互动，讲座现场气氛热烈。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Steve Schifferes是伦敦城市大学传媒教授，金融新闻系的负责人，在电视和网络金融商业新闻领域都有丰富的从业背景。他曾经是BBC电视台货币节目的制作人，参与了G8和G20等世界级峰会的报道和采访，现任BBC新闻在线的经济专栏记者。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：陈汉南）</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
