{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院召开国际商务硕士（MIB）教材建设研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月15-16日，经济学院组织召开国际商务硕士（MIB）教材建设研讨会。中国人民大学原副校长、国际商务硕士专业学位专家委员会主任杜厚文教授,经济学院国际经济系全体教师参加会议。会议由教育部国际商务硕士专业学位教学指导委员会委员、经济学院副院长刘元春教授主持。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhfy2bkzf-bmlff.jpg" width="252" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本次会议的主要内容是针对老师们提交的国际商务硕士（MIB）项目系列教材提纲展开讨论，集全国经系教师的智慧，群策群力，为MIB项目编写出一流的教材体系。杜厚文教授就教材编写的基本要求、教材之间撰写的分工与配合提出了自己的指导性意见，并对每一本教材的结构安排、写作方法进行了细心指导。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会上，参会老师就国际商务、国际商法、国际市场营销、国际商务谈判、公司财务、商务外交、跨国公司经营与管理、世界经济案例、国际市场、国际金融市场与投融资、国际商务统计、国际商务中的环境与发展和跨文化管理等十三本教材的提纲进行了热烈而富有成效的讨论。会议明确了每一本教材在整个系列中的定位，明晰了整个系列教材的写作规范和要求，为MIB项目建设出一套结构完备、分工明确、风格一致、写作规范的教材体系奠定了坚实基础。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzhfybmf2f-ynfnm.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会议还指出，在MIB项目的教学过程中要切实的把双师的教学模式运行起来，把真正有实践经验的国际商务人才招揽到项目中。目前，MIB项目中心已经与中国水利水电总公司达成初步协议，对方董事长、总裁以及各业务板块的中层干部将以讲座和授课等不同形式参与到MIB项目的教学中来。同时，中心也已经与中国国际期货公司、国家商务部等单位和部门达成合作意向。这些单位将为MIB项目的学生提供大量的实习机会，为项目培养复合型、实践型人才提供机会。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1287448194{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzhfy2bkzf-bmlff_lit.jpg{/dede:field}
