<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","郑保卫教授应邀参加2010年环境保护部部属环境期刊审读工作总结会",89,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",230,277);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-03-29 08:56:15",279,338);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月23日，新闻学院郑保卫教授应邀参加了2010年国家环境保护部部属环境期刊审读工作总结会，并接受了环保部期刊审读专家聘书。会议总结了2010年环境期刊审读工作的成绩、经验和问题，并对2011年的审读工作作了部署，提出了要求。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郑保卫教授在会上发言，就如何提高环境类刊物的专业性、权威性和规范性，以争取学界和市场认可提出建议和意见。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />",340,876);
$z[6][4]['name']="body";
$z[7]=Array("field","",878,917);
$z[7][4]['name']="litpic";

?>