{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}郑保卫教授应邀参加2010年环境保护部部属环境期刊审读工作总结会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2011-03-29 08:56:15{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月23日，新闻学院郑保卫教授应邀参加了2010年国家环境保护部部属环境期刊审读工作总结会，并接受了环保部期刊审读专家聘书。会议总结了2010年环境期刊审读工作的成绩、经验和问题，并对2011年的审读工作作了部署，提出了要求。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 郑保卫教授在会上发言，就如何提高环境类刊物的专业性、权威性和规范性，以争取学界和市场认可提出建议和意见。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
