{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院党委召开深入开展创先争优活动暨纪念建党九十周年工作部署会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-03-08 05:30:30{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月4日下午，经济学院党委按照学校《中国人民大学深入开展创先争优活动工作安排（2010-2011学年第二学期）》和《进一步做好创先争优活动领导点评工作的方案》文件的指示精神，在明德主楼728会议室召开深入开展创先争优活动暨建党九十周年工作部署会。经济学院党委书记张宇、党委副书记明占生出席会议并讲话。经济学院全体党委委员、各教工党支部书记、各学生党支部书记和各班班长参加会议。 </p>
<p align="center"><img src="/uploads/allimg/c110419/zlflznzkn2zfy2f-zbkyz.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张宇书记指出，经济学院创先争优活动进入第二阶段，学院党委、各党支部要开展集中点评、个别点评、现场点评和随机点评等多种方式的点评活动，将创先争优活动进一步深入开展；动员各党支部积极参加和开展纪念建党九十周年的活动；党员要在维护安全稳定方面发挥模范带头作用，坚决抵制各种错误言论和非法活动，永远跟党走。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 明占生副书记向各党支部、各班部署了学院接下来将开展的&ldquo;学红史、读红书，唱红歌&rdquo;纪念建党九十周年系列活动的相关工作，包括建设专题网站、采编老教授回忆录、开展&ldquo;红歌&rdquo;歌咏比赛、举办读书会等。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟） <br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflznzkn2zfy2f-zbkyz_lit.jpg{/dede:field}
