{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}江西省副省长熊盛文受聘人民大学兼职教授{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-03-08 08:40:54{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月5日上午，江西省副省长熊盛文中国人民大学兼职教授聘任仪式在明德主楼举行。袁卫常务副校长代表学校向熊盛文副省长颁发了聘书。</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzhkbymymhf-zbzlf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;袁卫常务副校长作了简短的讲话。他指出，学校希望通过与广大校友的密切联系，整合资源，将学科建设深入下去。熊盛文教授作为人民大学的杰出校友，多年来一直对母校怀有很深的感情，一直关注和关心母校的发展，相信他此次受聘人民大学兼职教授，一定会进一步加强人大与地方政府，特别是江西省各部门的联系与合作，提高学校经济学科服务社会的水平。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;熊盛文副省长发表了答谢辞。他感谢母校聘请自己担任兼职教授，认为这是莫大的荣誉。他深情回顾了三十年前在母校读书时的难忘岁月，对于母校的培养和教育表示衷心的感谢。说到动情之处，熊盛文副省长起身向昔日授业的恩师胡乃武教授等深深地鞠了一躬。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 熊盛文副省长说，自己很高兴能在毕业多年后重返母校，参与教育事业，与青年学子深入交流，希望为学校的发展建设尽绵薄之力，做人民大学和江西省开展全方位合作的牵线人和使者。他还鼓励人大学子到&ldquo;物华天宝，人杰地灵&rdquo;的江西省去实现人生价值。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzhkbmlfzyf-222hl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈一兵副校长，经济学院胡乃武教授、刘成瑞教授、沈筱蓉教授等出席聘任仪式。经济学院杨瑞龙院长主持聘任仪式。&nbsp;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>熊盛文校友简介</strong> </p>
<p align="center"><img height="221" alt="" width="160" src="/uploads/allimg/c100619/z2kymzhkyzbfllf-llylh.jpg" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 熊盛文，男，汉族，1951年12月生，江西丰城泉港人。1982年12月加入中国共产党，1968年8月参加工作，大学学历，1979-1983年就读于中国人民大学国民经济计划专业。曾任江西省计划委员会综合处处长、副主任，江西省委办公厅主任，江西省委秘书长，萍乡市委副书记、市长。2003年2月任江西省劳动和社会保障厅厅长；2004年2月任江西省省长助理、省政府党组成员，省劳动和社会保障厅厅长；2005年7月任江西省省长助理、省政府党组成员、江西省委委员。2006年3月起任江西省副省长。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：王宝奎 文静）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzhkbymymhf-zbzlf_lit.jpg{/dede:field}
