{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}马来西亚马来亚大学代表团访问人民大学{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/国际交流处 图/新闻中心{/dede:field}
{dede:field name='pubdate'}2011-03-24 04:57:00{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月23日上午，杨慧林副校长会见了到访的马来亚 (University of Malaya)大学管理者高级研修班代表团。代表团由该校医学院寄生物学系加温（Prof. Dr. Suresh Kumar a/l P Govind）教授率团，成员包括来自该校艺术与社会科学学院、商业与会计学院、语言学学院、医学院、理学院等主要院系及部分职能部门的负责人一行共18人组成。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110418/zlflzzhbhbkbf2f-ll2h2.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨慧林副校长对马来亚大学代表团的来访表示诚挚的欢迎。他简要介绍了学校的学科特色，重点介绍了学生交流情况、暑期小学期和全英文课程等情况。杨慧林副校长希望通过马来亚大学的此次来访增进两校的相互了解，开展合作尤其是在学生交流方面开展合作。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在国际交流处处长唐忠教授的主持下，双方开展了自由交流。马来亚大学对人民大学的学科发展、教学科研、学生管理等表示了浓厚的兴趣，学校学生处处长张晓京、科研处副处长牟峰以及国际交流处副处长程鑫对各位代表的问题进行了详细的回答。通过问答和交流，马来亚大学代表对人民大学有了更深一步的了解，增进了与人大进行国际合作的意愿。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈结束后代表团参观了学校校史馆。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 马来亚大学是一所文科、理科和医学兼有的综合性大学，是马来西亚规模最大和最著名的大学之一，也是一所全马历史最悠久的学府。它的前身是1905年成立的爱德华七世王学院（Kolej King Edward VII）和1929年成立的莱佛士学院（Kolej Raffles）。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：文静&nbsp; 伟伟）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110418/zlflzzhbhbkbf2f-ll2h2_lit.jpg{/dede:field}
