<?php
$z[0]=Array("addurls","http://news1.ruc.edu.cn/102449/102450/102497/list.html\r\nhttp://news1.ruc.edu.cn/102449/102450/102497/list_23.html\r\nhttp://news1.ruc.edu.cn/102449/102450/102497/list_22.html\r\nhttp://news1.ruc.edu.cn/102449/102450/102497/list_21.html",3,263);
$z[1]=Array("batchrule","",266,299);
$z[2]=Array("regxrule","",302,333);
$z[3]=Array("areastart","<table width=\"743\" cellspacing=\"1\" bgcolor=\"#CACCCE\">",336,422);
$z[4]=Array("areaend","<table width=\"100%\"><tr><td align=right>",425,494);

?>