
	{dede:addurls}http://news1.ruc.edu.cn/102449/102450/102497/list.html
http://news1.ruc.edu.cn/102449/102450/102497/list_23.html
http://news1.ruc.edu.cn/102449/102450/102497/list_22.html
http://news1.ruc.edu.cn/102449/102450/102497/list_21.html{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<table width="743" cellspacing="1" bgcolor="#CACCCE">{/dede:areastart}
	{dede:areaend}<table width="100%"><tr><td align=right>{/dede:areaend}
