{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}第61期德恒证据学论坛成功举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院  文/万喆 李洪杰{/dede:field}
{dede:field name='pubdate'}2010-03-29 04:12:01{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月25日，证据法论坛第六十一讲在明法601成功举行。本次论坛的主题是&ldquo;手机取证的证据问题：信息与法学的对话&mdash;&mdash;从&times;&times;省地震门的模拟庭审谈起&rdquo;。本次论坛由刘品新副教授主持，信息专家、司法工作者、法律学者共同参与。主讲人被分为控辩双方：控方由最高人民检察院检察技术信息研究中心处长李运策、中国科学院软件研究所研究员丁丽萍担任，辩方由金杜律师事务所合伙人徐静、数据工程与知识工程教育部重点实验室教授石文昌担任。厦门美亚柏科资讯科技有限公司的三位鉴定专家，作为控方鉴定人参加了本次论坛。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylhyynnkf-nmbhf.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随着电子通讯技术的飞速发展，运用手机等通讯设备进行的犯罪活动已屡见不鲜，因此手机取证问题成为人们关注的焦点。手机取证过程是怎样进行的，电子证据是怎样保全的，电子证据如何确保真实，电子证据的证明力有多大？本次论坛从&times;&times;省地震门的模拟庭审谈起，专家们围绕这一问题展开了激烈辩论。模拟庭审现场，控方还请来了厦门美亚柏科资讯科技有限公司的鉴定专家针对手机取证过程进行了现场演示和说明，使听众们大开眼界。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzylhknmzmf-mnbhk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 整个论坛始终充满着新奇的氛围，听众们饶有兴趣地听着信息专家、司法工作者、法律学者的共同讲解，在信息与法学的交叉空间里积极探索着。一番激烈的庭审辩论过后，大家对我国目前的手机取证的基本程序有了一定了解。但是，由于电子信息技术的更新速度惊人，电子证据的安全性、稳定性、可信性依然是人们担心的问题。听众们针对各种疑惑踊跃发言，意犹未尽。会后，每位听众都得到了刘品新老师最新出版的《电子取证的法律规制》。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：徐晶晶）<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzylhyynnkf-nmbhf_lit.jpg{/dede:field}
