{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“日中SD人才培养说明会” 在人民大学举行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='body'}<p>　　11月22 日，由中国人民大学环境学院和日本京都大学东亚经济研究中心主办的&ldquo;日中SD（节能减排循环经济低碳发展以及可持续发展）人才培养说明会&rdquo;在逸夫会议中心第一会议室举行。中国人民大学副校长薛浣白出席会议并致辞，论坛开幕式由中国人民大学环境学院院长马中教授主持。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfbffklllf-zfnlll.jpg" /></p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfbf2bf22f-zz222y.jpg" /></p>
<p>　　日本驻中国大使馆公使山崎和之，京都大学地球环境学院植田和弘教授、刘德强教授、森晶寿副教授、金红实博士，松下（中国）有限公司环境本部部长齐腾博幸，人民大学环境学院院长马中教授，环境学院党委书记刘鹏，环境学院副院长王洪臣教授，环境学院党委副书记吴健副教授，环境学院环境经济与管理系主任靳敏副教授，环境学院蓝虹副教授、朱芬芬副教授，国际交流处王路芳老师，以及人民大学、京都大学约30名学生参加了此次说明会。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfbf2yfhbf-z2lmyb.jpg" /></p>
<p>　　中国人民大学副校长薛浣白在致辞中指出，可持续发展人才的培养对于保护环境、应对气候变化、发展低碳经济具有重要意义，中日双方在低碳发展的相关领域开展积极的合作，将有利于推进两国的低碳进程，代表学校表示对该项目积极支持，感谢日本政府对该项目的重视，感谢松下公司的协助，特别是感谢京都大学为此付出的诸多努力。 </p>
<p>　　京都大学的植田和弘教授介绍了中日SD人才培养教育项目计划，京都大学的刘德强教授和森寿晶副教授分别具体介绍了京都大学大学院经济学研究科和地球环境学堂的培养计划，松下（中国）有限公司环境本部部长齐腾博幸介绍了松下公司环境活动概要。双方老师、学生就合作内容和培养计划进行了探讨和交流，并就培养节能、减排、循环经济、低碳发展及可持续发展等方面的人才深入交换了意见。 </p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c101126/z2mfkyfbflflbzf-zlzbkn.jpg" /></p>
<p>　　（编辑：卢思颖）<br />
<br />
<br />
<br />
<br />
</p>{/dede:field}
{dede:field name='pubdate'}1290483697{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfbffklllf-zfnlll_lit.jpg{/dede:field}
