{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院赵晓耕教授、肖建国教授应邀出席“全国法院民事裁判文书师资研修班”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-17 02:54:58{/dede:field}
{dede:field name='body'}<p>　　6月12、14日，法学院赵晓耕教授、肖建国教授应邀出席最高人民法院政治部和国家法官学院主办的&ldquo;全国法院民事裁判文书师资研修班&rdquo;。研修培训在最高人民法院北戴河培训中心举行，来自全国各地的三级法院（高院、中院和基层法院）的170名资深民事法官参加了此次培训。 <br />
<br />
　　6月12日，国家法官学院副院长陈海光博士在开班典礼上讲话，之后，赵晓耕教授作了&ldquo;裁判文书与中国传统法律文化&rdquo;的演讲。6月14日，肖建国教授作了&ldquo;程序思维方法与法院裁判&rdquo;、&ldquo;判决主文与判决理由&rdquo;的演讲。 </p>
<p>　　（编辑：苗育婧）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
