{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}台湾新党主席郁慕明宴请纪宝成校长一行{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}人民大学赴台代表团{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月8日中午，台湾新党主席郁慕明宴请了在台访问的纪宝成校长和人民大学代表团。</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhkymmflf-mbbkb.jpg" /></p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 席间，大家回顾了2005年7月郁慕明主席在人民大学讲演的情景。郁慕明主席与纪校长还就两岸关系进行了亲切交谈。纪宝成校长邀请郁慕明主席再次到人民大学讲演，郁慕明主席愉快地接受了邀请。午宴之后，郁慕明主席办公室还特意安排人民大学代表团参观了正在台北举行的国际花卉博览会。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c101126/z2mfkyfhkkymzbf-zfnzn2.jpg" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陪同郁慕明主席出席午宴的有台湾&ldquo;中国广播公司&rdquo;董事长赵少康，&ldquo;总统府国策顾问&rdquo;陈癸淼，华德货柜股份有限公司董事长张德龄、中国文化大学教授陈义扬和新党主席办公室主任袁富仁。人民大学赴台代表团全体成员在座。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>相关链接：</strong></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102382/71662.html">[海峡两岸大学校长论坛系列报道] 论坛将登场 欢迎晚宴为纪宝成校长庆生</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71672.html">纪校长率团赴台参加第三届海峡两岸大学校长论坛并作主题发言</a>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71728.html">纪宝成校长拜会吴伯雄先生、刘兆玄先生</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71725.html">纪宝成校长接受台湾媒体采访</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71729.html">人民大学与台湾清华大学签订校际协议</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71803.html">中国国民党荣誉主席连战会见纪宝成校长</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102392/71836.html">纪宝成校长率团参访台湾&ldquo;中央研究院&rdquo;</a></p>
<p>　　<a href="http://news1.ruc.edu.cn/102392/71852.html">中国人民大学台湾校友会热烈欢迎纪校长访台<br />
</a><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />
</p>{/dede:field}
{dede:field name='pubdate'}1289417522{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101126/z2mfkyfhkymmflf-mbbkb_lit.jpg{/dede:field}
