{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院民商事法律科学研究中心举办“网络侵权与法律适用”研讨培训会议{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院 文/苏志梅 王伟{/dede:field}
{dede:field name='pubdate'}2011-03-02 09:55:22{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月26-27日，中国人民大学民商事法律科学研究中心与ICCD国际传播促进中心在北京蟹岛度假村举办&ldquo;网络侵权与法律适用&rdquo;研讨培训会议。会议主要邀请北京及周边地区的一线法官，以及媒体与法律领域知名学者专家，共同讨论《侵权责任法》颁布后的媒体侵权与法律适用的重要议题，并剖析了陆幽诉黄健翔名誉权案、金德管业公司诉百度名誉权案、北京三面向版权代理有限公司诉上海大学名誉权案等典型案例。法学院杨立新教授、姚辉教授、冯玉军教授、肖建国教授、王宗玉副教授等参加。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：卢思颖）<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
