<?php
$z[0]=Array("arcurl","",19,35);
$z[1]=Array("title","",47,62);
$z[2]=Array("arcurl","",75,91);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? &quot;&quot; : &quot;<dt class=\\\"img\\\"><a href=\\\"{@me['arcurl']}\\\"><img onload=\\\"hideno(this)\\\" alt=\\\"\\\" src=\\\"{@me['litpic']}\\\"/></a></dt>&quot;); \r\n	",133,354);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",381,397);
$z[5]=Array("title","",399,414);

?>