<dl>
<dt><a href="[field:arcurl /]" class="l">[field:title /]</a><a href="[field:arcurl /]" class="r">¸ü¶à&gt;&gt;</a></dt>
<dd>
	[field:array runphp='yes']@me = (empty(@me['litpic']) ? &quot;&quot; : &quot;<dt class=\"img\"><a href=\"{@me['arcurl']}\"><img onload=\"hideno(this)\" alt=\"\" src=\"{@me['litpic']}\"/></a></dt>&quot;); 
	[/field:array]

<ol>

<li>¡¤<a href="[field:arcurl /]">[field:title /]</a></li>

</ol>
</dd>
</dl>