{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京市人文知识竞赛人民大学学子再获佳绩{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}哲学院{/dede:field}
{dede:field name='pubdate'}2010-12-06 03:21:40{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月4日下午一时，由北京市教委主办，清华大学承办、中国劳动关系学院协办的第二届北京市人文知识竞赛决赛在清华大学蒙民伟楼举行。本届竞赛主题为&ldquo;观乎人文，化成天下&rdquo;，以文史哲的基础知识、必要的艺术修养、科学史与自然科学常识以及北京历史文化常识为主要命题内容，旨在拓宽大学生的知识视野，提高大学生的文化素质，促进北京高校大学生的文化素质教育，为大学生的成才奠定更为宽厚的基础。来自中国人民大学、清华大学、中国劳动关系学院、北京中医药大学、首都师范大学、北京语言大学六支代表队的18名选手参加本场比赛。人民大学副校长杨慧林出席比赛。 </p>
<p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本届比赛分为初试、半决赛和决赛三个环节，由国学院张耐冬老师、哲学院臧峰宇老师担任指导老师，教务处、哲学院团委组织开展校内选拔。人民大学推荐的两支代表队在初赛时名列榜首，分获第一、第二名的好成绩。因北京市人文知识竞赛赛制要求，每校按初赛成绩最多只可选送一支队伍参加决赛，另一支队伍直接获得二等奖。人民大学两支队伍充分发挥精诚团结、共同作战的集体精神。在第一轮诗词创作环节，人民大学选手以一首在15分钟内创作的五言律诗获得了评委老师的好评，各位评委纷纷亮出高分。第二轮抢答环节中，人民大学代表队积极表现，勇于拼抢，与中国劳动关系学院代表队同获全场最高分。第三轮即兴题环节中人民大学选手完美阐释了题目要求。最后进入第四轮演绎题环节，学校同学以&ldquo;归途&mdash;&mdash;郑和下西洋&rdquo;为主题，向观众们展现出了他们对个人与国家关系、历史浮沉的深刻思考。投入的表演、恢弘的背景音乐、深邃的主题赢得了满堂喝彩。四轮比赛过后，人民大学选手以469.8分的总分再次获得北京市人文知识竞赛一等奖，用丰厚的知识与完美的表演向全北京市的高校展现出了人民大学的人文精神和文化底蕴。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110113/z2mhnnbmhh2ybkf-lhlbh.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 一等奖队伍获奖学生名单： </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;付晓旭，财政金融学院2008级保险班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; 景风华，法学院2007级法学二班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;王 强，国学院2007级本科班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 甘沁鑫，新闻学院2009数字新闻传播班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 罗 鸿，国际关系学院2010级国际政治2班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 二等奖队伍获奖学生名单： </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 倪霄汉，哲学院2008级国防班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;廖 越，公共管理学院2010级公管2班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;李元骏，国学院2009级本科班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李雨童，国学院2010级本科班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 戈 弋，农业与农村发展学院2010级农发1班 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：苏璇）</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnbmhh2ybkf-lhlbh_lit.jpg{/dede:field}
