{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院召开2011年离退教师新年茶话会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-12-31 11:54:18{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12月29日，2011年经济学院离退教师新年茶话会在明德主楼734会议室举行。经济学院经济系、国经系、国管系、经济研究所、区域与城市经济研究所等的60余名离退教师参加了茶话会。经济学院院长杨瑞龙教授，党委书记张宇教授，党委副书记丁凯等出席。新年茶话会由张宇书记主持。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110113/z2mhnnh22hkzmzf-mzlhn.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长首先代表学院向参会的离退老教师表达了诚挚的节日问候，祝他们新年快乐、身体健康。他向离退教师传达了了9月9日胡锦涛总书记视察人民大学时发表的重要讲话的指示精神，将党和国家领导人的关怀传递给了每一位离退教师。杨瑞龙院长还介绍了学院2010年在教学、科研、国际交流和社会服务等方面取得的工作成绩。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 张宇书记向全体离退教师致以新年的问候，并希望老教师保重身体，为学院的发展多提宝贵建议。 <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 茶话会上，离退教师进行了亲切而热烈的交流。老教师们表示深受胡锦涛总书记&ldquo;9&bull;9&rdquo;讲话精神的鼓舞，同时对于学院领导离退老教师长期以来的关怀表示感谢，对于学院2010年在学科建设等方面取得的巨大成就感到欢欣鼓舞和无比欣慰，并祝愿学院在2011年事业有更大的发展，再创新的辉煌。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnh22hkzmzf-mzlhn_lit.jpg{/dede:field}
