{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人民大学师生迎接75周年校庆原创话剧《苏格拉底》上演{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}文/校团委 图/校团委 新闻中心 罗豫伟 网新社 刘长鑫 朱可然{/dede:field}
{dede:field name='pubdate'}2012-06-04 05:42:15{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月3日晚，中国人民大学75周年校庆开场大戏、由人民大学在校师生共同创作的大型原创话剧《苏格拉底》在明德堂隆重上演。北京市委常委、常务副市长吉林校友；中纪委常委、监察部副部长王伟校友；中宣部文艺局副局长汤恒；北京市教委副主任郑萼；中国石油大学校长张来斌；首都师范大学党委书记张雪；中国社科院外文所所长陈众议；德国著名汉学家顾彬；中国作家协会创研部主任梁鸿鹰；《文艺报》总编辑阎晶明；中国人民大学党委书记程天权，校长陈雨露，常务副书记牛维麟，副校长冯惠玲、杨慧林；著名书法家欧阳中石；著名艺术家王晓棠、丁道希、郑凯南；著名演员陈佩斯、朱时茂、牛群、刘蓓，中央电视台著名主持人刘建宏校友等各界知名人士与1000余名师生代表共同观看该剧。</p>
<p align="center"><img alt="" src="/uploads/allimg/c120620/zlhfzklzhzflhf-lnybl.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《苏格拉底》由人民大学教师劳马担任编剧。全剧重新演绎了古希腊哲学家、西方哲学的奠基者苏格拉底与青年人交流探索真理，却受到反对诬告和不公审判，最终坦然面对死亡的故事；刻画了苏格拉底、阿里斯托芬、美勒托、克珊西帕等多个生动鲜活的形象。八幕话剧情节环环相扣，矛盾冲突强烈，尤其是创造性地加入了苏格拉底与妻子的日常生活等情节，使人物形象更加丰满、立体，给观众留下了既深刻又可爱、既伟大又平易近人的苏格拉底形象。该剧台词通俗幽默但不乏深刻的哲理语言，避免了哲学概念的晦涩难懂，加深了观众对西方哲学智慧的理解。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 剧本创作完成后，人民大学学生艺术团团员进行了历时两个多月的排练，认真研读剧本、细心搜集资料、加深对人物和文化的了解。在排练过程中，大家精益求精地背台词、练形体、找感觉，力求进入所扮演角色的内心世界，着力呈献给大家一台深刻、精致、好看的文化盛宴。演出当晚，全体演员以稳健的台风、细腻的表演将剧中丰满的人物形象和强烈的戏剧冲突刻画得栩栩如生。抑扬顿挫的台词、声情并茂的表演、扣人心弦的剧情，让现场观众陶醉在以爱、美、智慧、真理、勇敢、正义为主题的哲学世界中，感受到话剧艺术的独特魅力，整场演出高潮迭起。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c120620/zlhfzklzb2kzhyf-hbmkk.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 原创话剧《苏格拉底》的创作与演出，是中国人民大学校园文化发展的又一重要成果。话剧充分展现了以苏格拉底为代表的哲学家对美的热爱、对爱的执着、对智慧的追求和对正义的向往。此外，在该剧的编创过程中，人民大学首次采用师生合作、自编自演的创作形式极大地提高了广大同学的创造力和参与度，有益于校园文化的不断丰富和发展。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 演出结束后，同学们表示，话剧活脱脱地展现给大家一个有血有肉的苏格拉底，他的形象不再陌生，那些深奥的哲学道理也不再难以理解；尽管苏格拉底生活的时代距离现在已经两千多年，然而他身上所体现出来的正直勇敢的品质和执着求知的精神始终是值得宣扬和学习的财富。</p>
<p align="center"><img height="333" alt="" width="500" src="/uploads/allimg/c120620/zlhfzklzy2mykyf-bbllb.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 《苏格拉底》是75周年校庆活动的开场大戏，是中国人民大学教师和学生自编、自导、自演的一出原创大戏，彰显了人民大学深厚的学术底蕴及文化原创力，成为引领校庆新模式的亮点。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 媒体链接：<a href="http://culture.people.com.cn/GB/40473/40476/18064641.html">[人民网]中国人民大学师生原创话剧《苏格拉底》精彩上演</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://news1.ruc.edu.cn/102382/82225.html">[中国新闻社]人大师生原创话剧《苏格拉底》首演</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 相关链接：<a href="http://news1.ruc.edu.cn/82255.html">人民大学师生原创话剧《苏格拉底》首演（图）</a></p>
<p>（编辑 杨默）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120620/zlhfzklzhzflhf-lnybl_lit.jpg{/dede:field}
