<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","外国语学院西方文化讲座举行第七讲：美国媒体和北京奥运",89,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","外国语学院团学新闻信息中心/施扬灵",222,294);
$z[4][4]['name']="source";
$z[5]=Array("field","2008-11-20 11:40:35",296,355);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月19日下午，公共教学一楼1602教室里气氛热烈，同学们争先恐后地向讲台上的美国老师提问。外国语学院西方文化系列讲座第七讲、由Tim Hathaway主讲的&ldquo;American Media and the 29th Beijing Olympic Games&rdquo;（美国媒体和北京奥运）成功举行。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tim老师由在2008年4月和8月分别对美国人所做的关于是否赞成中国举办奥运会的调查结果入手，介绍了美国报纸、广播、电视、网络等各类媒体的关注点和运行模式， 分析了美国媒体对北京奥运会的报道在美国民众中所产生的影响，并与同学们分享了同样参与了北京奥运会媒体报道工作的他对美国媒体工作状况的意见和看法。其明晰的观点、客观的评价引得到了在场听众的认同，场内不时响起热烈的掌声。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 据了解，来到讲座现场的不仅有人民大学各个专业的学生，也有在人大任教的外籍教师以及周边学校的同学。大家均表示受益匪浅。</p>\r\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：冷严军）&nbsp;<br />\r\n</p>",357,1313);
$z[6][4]['name']="body";
$z[7]=Array("field","",1315,1354);
$z[7][4]['name']="litpic";

?>