{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}俄罗斯科学院副院长涅基别洛夫访问经济学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10月14日下午，俄罗斯科学院副院长涅基别洛夫院士、中俄友协主席季塔连科院士及外事局局长马尔基阿诺夫一行访问人民大学经济学院。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzzmzyfmzf-y2nzm.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学副校长林岗教授会见了俄罗斯科学院代表团。林岗副校长与代表团成员一同回顾了两国在教育领域合作交流的历史，并向代表团介绍了人民大学的发展现状，尤其谈到了在人才培养和学术研究方面取得的丰硕成果。涅基别洛夫副院长详细介绍了俄罗斯科学院的机构设置，并专门介绍了其新增设的全球化和国际关系学部。代表团向林岗副校长表达了对学校领导的感谢之情以及对与经济学院学者进行学术交流的期待。经济学院院长杨瑞龙教授、党委书记张宇教授、俄罗斯研究中心主任关雪凌教授等参加了会见。&nbsp;</p>
<p align="center"><img height="333" src="/uploads/allimg/c101124/z2mfbmzzm22lhyf-kkzyf.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，中俄现代化与市场经济发展学术研讨会在经济学院0734会议室举行。经济学院院长杨瑞龙教授、党委书记张宇教授、俄罗斯研究中心主任关雪凌教授，经济学院彭刚教授、韩玉军教授等参加了研讨会。研讨会上，俄罗斯科学院代表团与经济学院的学者进行了热烈而富有成效的讨论。双方就政治经济学在中俄两国的研究范围、学科地位、研究方法、发展脉络与现状等进行了深入的探讨。杨瑞龙院长介绍了政治经济学在中国的历史沿革与新时期的发展变化，季塔连科院士对中国特色社会主义建设所取得的成就表示肯定，并阐述了两国建立友好合作伙伴关系的战略重要性。双方还就中俄两国的现代化建设和市场经济发展经验等问题进行了坦诚而愉快的交流，张宇教授从所有制、意识形态和政治制度等方面系统地阐释了中国特色的社会主义发展模式以及所面临的考验和挑战，彭刚教授分别从时代主题和社会发展阶段的角度总结并解释了中国特色社会主义的特殊性。最后，涅基别洛夫副院长重点强调了两国现代化建设互相借鉴经验、互相学习的重要性和必要性，并表达了加强双方交流与合作的愿望。 </p>
<p>
</p>{/dede:field}
{dede:field name='pubdate'}1287364828{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c101124/z2mfbmzzmzyfmzf-y2nzm_lit.jpg{/dede:field}
