{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}孟强、颜九红同学荣获“学术新星”称号 法学院连续四年获得“最佳组织奖”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-06-17 09:58:43{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月9日下午，由中国人民大学研究生院和校团委主办、校研究生会承办的第四届中国人民大学&ldquo;学术新星&rdquo;评选活动总结表彰大会在逸夫会堂第二报告厅隆重举行。校党委副书记马俊杰教授出席并向获奖代表颁奖，研究生院常务副院长吴晓求教授、法学院法律文化研究中心副主任马小红教授、团委书记乔鹏老师出席了表彰大会。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本届&ldquo;学术新星&rdquo;评选活动在汲取前三届活动经验的基础上，部署更加周密，评选机制更加健全。自2010年4月15日活动启动以来，经过推荐自荐、事迹筛选、综合评定、专家评审和现场答辩等环节，最终评选出&ldquo;学术新星&rdquo;10名，最佳提名奖12名，最佳组织奖1名。法学院2007级博士孟强、颜九红同学荣获&ldquo;学术新星&rdquo;称号；法学院团委再次荣获&ldquo;最佳组织奖&rdquo;。自首届&ldquo;学术新星&rdquo;评选活动举办至今，法学院团委已连续四年获得&ldquo;最佳组织奖&rdquo;的殊荣，共有19名同学获得单项奖。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在总结表彰大会现场，法学院马小红教授作为评审委员会代表、团委书记乔鹏老师作为&ldquo;最佳组织奖&rdquo;代表、&ldquo;学术新星&rdquo;获得者2007级博士生孟强相继发言，精彩的发言赢得了在场老师和同学们的热烈掌声。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 中国人民大学&ldquo;学术新星&rdquo;评选活动，旨在挖掘和宣传我校研究生中的学术新秀、杰出典型，为广大青年学生树立学习榜样，营造健康向上的校园学术氛围。 一直以来，法学院有着求真务实的学风，努力营造出勇于探索、共同进步的良好学术氛围。在本届&ldquo;学术新星&rdquo;评选活动中，法学院团委和研究生会积极为同学们服务，配合校团委在法学院广泛宣传，采取了多种方式组织动员研究生同学参加本次评选活动。法学院研究生同学在本次活动中再创佳绩，弘扬了法学院优良的学术传统，体现了广大研究生同学在学术之路勇于探索、不断创新的精神，激励同学们努力成为专业基础扎实、知识广博精深的优秀人才。</p>
<p>（编辑：程远芳）&nbsp;<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
