{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}环境学院邹骥教授做客“中国贵州生态文明大讲坛”  开讲“生态文明建设中的政府责任与行为”{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}环境学院{/dede:field}
{dede:field name='pubdate'}2010-06-17 08:51:14{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6月10日，由贵州省委宣传部主办、贵州省社科联承办的2010年&ldquo;中国&bull;贵州生态文明大讲坛&rdquo;第二、三场报告会在省委大会堂和贵阳市白云区会议中心举行。中国人民大学环境学院邹骥教授围绕&ldquo;生态文明建设中的政府责任与行为&rdquo;这一主题，对低碳经济的趋势、低碳经济的定义、发展低碳经济的机遇挑战与决定因素、中国需要什么样的低碳未来、低碳经济转型中政府的责任与行为等进行了充分阐述。</p>
<p align="center"><img src="/uploads/allimg/c100622/z2kkzlnfybnybyf-bmhhf.jpg" alt="" /></p>
<p>&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 邹骥教授指出，气候变化现在已不单纯是一个环境问题，它关系到人类核心利益和一个国家的发展前景。伴随气候变化问题而来的是低碳经济日益成为国际政治经济新趋势，尤其是在中国已经掀起了发展低碳经济的热潮。邹骥教授同时指出，关于如何在中国发展低碳经济，许多人并没有清晰的认识。邹骥教授结合他所领导的中国人民大学能源与气候经济学项目（PECE）的研究成果，指出发展低碳经济必须同改善民生、促进人类发展相联系，而且也必须符合中国的具体国情。在经济社会发展所处的历史阶段、自然资源禀赋和地理条件、科技发展水平与创新能力、社会意识与能力水平等背景因素下，最大限度提高碳生产力，提升经济社会发展水平，兼顾代际公平和代内公平，使社会经济沿着可持续发展的路径前进。邹教授强调，发展低碳经济是贯彻落实科学发展观的必然要求，也是应对诸多挑战、建设&ldquo;两型&rdquo;社会的现实需要，是我国推进经济转型升级、促进经济社会又好又快发展的题中应有之义。邹骥教授认为，地方政府发展低碳经济，要一切围绕着人类发展目标，在规划、招商引资、资源配置时设置碳排放门槛，同时密切注意国际国内相关政策的发展趋势。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;讲座吸引了来自贵州省和贵阳市党政机关、高等院校、科研院所、社会团体近千听众。听取讲座的党政机关干部表示，报告既有理论深度，又紧密联系实际，对党委政府部门全面把握推进生态文明建设所应担负的责任以及应该采取什么样的行为，具有很强的现实指导意义。</p>
<p>&nbsp;<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100622/z2kkzlnfybnybyf-bmhhf_lit.jpg{/dede:field}
