{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京市人大常委会赴人口学系开展专题调研{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}人口学系{/dede:field}
{dede:field name='pubdate'}2010-05-12 04:44:27{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 近日，北京市人大常委会内务司法委员会主任李小娟带领市人大常委会委员、市人大代表等一行11人来到社会与人口学院人口学系，就&ldquo;北京市人口规模调控&rdquo;问题进行专题调研。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 社会与人口学院院长翟振武教授，党委副书记、人口学系主任段成荣教授和陈卫教授、刘爽教授、侯东民教授、宋健副教授、张耀军副教授、周祝平副教授等出席研讨会。与会的各位学者结合自己的研究特长和多年研究积累，分别从北京市人口承载力、北京市人口增长的主要特点和未来变动趋势、北京市流动人口数量变动趋势、流动人口政策法规的演变和有关首都人口规模调控的建议等方面进行了深入分析，并就巴黎、纽约等国际大都市在调控人口规模方面的经验进行了介绍。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在听取了几位专家学者的介绍之后，前来调研的市人大常委委员及代表们表示，今年是&ldquo;十一五&rdquo;规划实施的最后一年，马上要着手编制&ldquo;十二五&rdquo;规划。人口问题作为关系国计民生的根本问题，意义重大，是政府决策的基石，受到了很多代表委员的高度关注。此次调研获益匪浅，各位专家的研究成果为下一步的政府工作提供了宝贵的资料，具有重要的参考价值。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉) <br />{/dede:field}
{dede:field name='litpic'}{/dede:field}
