{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zffzfm.jpg' text='中国人民大学明德楼' width='384' height='298'} /uploads/allimg/100612/2-zffyz2zffzfm.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zffzlf.png' text='中国人民大学明德楼主楼' width='450' height='299'} /uploads/allimg/100612/2-zffyz2zffzlf.png {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zff2f2.jpg' text='中国人民大学明德楼' width='480' height='334'} /uploads/allimg/100612/2-zffyz2zff2f2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/100612/2-zffyz2zff22y.jpg' text='中国人民大学明德楼' width='450' height='300'} /uploads/allimg/100612/2-zffyz2zff22y.jpg {/dede:img}
