<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/100612/2-zffyz2zffzfm.jpg ",93,258);
$z[1][4]['ddimg']="/uploads/allimg/100612/2-zffyz2zffzfm.jpg";
$z[1][4]['text']="中国人民大学明德楼";
$z[1][4]['width']="384";
$z[1][4]['height']="298";
$z[2]=Array("img"," /uploads/allimg/100612/2-zffyz2zffzlf.png ",260,429);
$z[2][4]['ddimg']="/uploads/allimg/100612/2-zffyz2zffzlf.png";
$z[2][4]['text']="中国人民大学明德楼主楼";
$z[2][4]['width']="450";
$z[2][4]['height']="299";
$z[3]=Array("img"," /uploads/allimg/100612/2-zffyz2zff2f2.jpg ",431,596);
$z[3][4]['ddimg']="/uploads/allimg/100612/2-zffyz2zff2f2.jpg";
$z[3][4]['text']="中国人民大学明德楼";
$z[3][4]['width']="480";
$z[3][4]['height']="334";
$z[4]=Array("img"," /uploads/allimg/100612/2-zffyz2zff22y.jpg ",598,763);
$z[4][4]['ddimg']="/uploads/allimg/100612/2-zffyz2zff22y.jpg";
$z[4][4]['text']="中国人民大学明德楼";
$z[4][4]['width']="450";
$z[4][4]['height']="300";

?>