{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}富山大学经济学部小仓利丸学部长率团访问公共管理学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}公共管理学院{/dede:field}
{dede:field name='pubdate'}2010-12-01 11:09:57{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月29日，富山大学经济学部学部长小仓利丸教授、该学部主管中国人民大学交流事务的负责人中村和之教授、经济学科学科长垣田直树教授以及龙世祥教授访问中国人民大学公共管理学院。公共管理学院院长董克用教授会见了来访的日本客人，院党委副书记崔军副教授陪同会见。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110113/z2mhnnbnh2znmhf-z2hmk.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在会见中，董克用院长首先对来宾的到访表示欢迎，随后简要介绍了中国人民大学的校史和学科特点，并从学科设置、师资队伍、学生培养、对外交流等方面详细介绍了公共管理学院的情况；小仓利丸学部长回顾了长期以来两院（部）良好的合作关系，表示双方的交流对学部的发展具有重大意义。双方就公共管理学院教师赴富山大学参加国际研讨会以及互派教师交流授课等事宜达成了初步的合作意向。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110113/z2mhnnbnh2kbmmf-2nkmh.jpg" width="500" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 29日下午，公共管理学院部分教师与来访的富山大学经济学部教授以环境保护为主题举行了小型研讨会，黄燕芬教授、崔军副教授、张磊博士、严平博士参加了研讨，会议由崔军副教授和日方龙世祥教授共同主持。双方参会人员就环保税、资源税、城市绿地的开发控制系统、废弃物处理政策、现代社会环境问题、循环经济国际分工与生态补偿等议题发表了演讲并进行了交流沟通。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnbnh2znmhf-z2hmk_lit.jpg{/dede:field}
