{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙院长亲切慰问“一二九”学生合唱队队员{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2010-11-25 02:48:16{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11月23日，经济学院杨瑞龙院长、明占生副书记在明德主楼728亲切慰问了经济学院&ldquo;一二九&rdquo;学生合唱队，给队员们带来了深切的关怀和问候，并给同学们发了水果、牛奶等慰问品。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110113/z2mhnnhzmlfzf2f-zyhbh.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在队员们深情地唱完一曲《天路》后，杨瑞龙院长和明占生副书记被深深的打动了，连连拍手称好，并给予了同学们热切的鼓励，并预祝经济学院蝉联冠军。期间，杨瑞龙院长还亲切地慰问队员是否有吃午饭，还一再地强调要把排练和保重身体并重。杨瑞龙院长鼓励队员们&ldquo;要展现出我们经济学院的精神风貌！&rdquo;此外，杨院长还一再地对队员一个月以来辛勤的排练表示了肯定，&ldquo;真的很感谢同学们为我们经济学院作出的贡献，你们为了排练花费了很多时间，但你们代表着我们经院2000多学生的形象，大家的努力一定会得到回报，经济学院今年肯定又是辉煌的一年！&rdquo;在对在场各位同学送上关心与祝福后，杨瑞龙院长给同学们发送了慰问品。同学们纷纷表示院长的慰问给予了大家莫大的鼓舞，极大地增强了大家的信心，大家一定努力练习，争取最好的成绩。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110113/z2mhnnhzmlkmfhf-2kmzm.jpg" width="500" alt="" /></p>
<p><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨瑞龙院长和明占生副书记的慰问大大激励了队员们的热情与信心，相信在此次&ldquo;一二九&rdquo;合唱比赛中，经济学院一定会赛出风采，赛出水平。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110113/z2mhnnhzmlfzf2f-zyhbh_lit.jpg{/dede:field}
