{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美国贝克麦坚时国际律师事务所贾殿安律师一行访问法学院{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-29 09:41:41{/dede:field}
{dede:field name='body'}<p>　　3月24日下午，法学院韩大元院长和林嘉书记兼副院长在明德法学楼贵宾室会见了来自美国贝克&middot;麦坚时国际律师事务所北京办事处的合伙人、首席代表贾殿安律师一行。</p>
<p>　　贝克&middot;麦坚时国际律师事务所作为国际知名的外资所之一，于2010年在法学院设立奖学金。韩院长首先代表法学院感谢贝克&middot;麦坚时律所在法学院设立奖学金，随后向贾律师等介绍了人民大学法学院国际化进程中的设想以及正在推动开展的项目，阐明了人民大学法学院有志于为中国的法律界培养一批具有国际视野的优秀学生的目标。他希望学院与律所能够有更多的交流合作，为学生构建一个法学理论与实务教育兼具的发展平台，承担一流法学院和国际知名大所应尽的社会责任，并推动中国法学教育的改革创新。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzyllnyyfnf-zmlmm.jpg" /><br />
<br />
　　</p>
<p align="left">　　林嘉书记兼副院长也表示了对双方在建设人民大学律师学院方面进一步合作期望，并就法学院与贝克&middot;麦坚时国际律师事务所的进一步交流合作与贾殿安律师等进行了详细沟通。 <br />
<br />
　　贾殿安律师表示完全赞同韩院长和林书记兼副院长的意见。他表示愿意加强同法学院在法律教育领域的合作与交流，包括为法学院学生开设法律实务类课程讲座、接受优秀的人大法学院学生到律所实习等。他也希望双方的努力能进一步完善法学教育体系，培养出更多有扎实的专业知识、良好的沟通能力和国际化视野的学生。 </p>
<p align="left">　　（编辑：於萍萍）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzyllnyyfnf-zmlmm_lit.jpg{/dede:field}
