{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}人大法学院在密云县人民检察院设立教学实践基地 冯军教授受聘密云县人民检察院副检察长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2011-03-01 03:07:28{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2月24日，法学院党委书记兼副院长林嘉教授一行前往密云县人民检察院，参加了法学院冯军教授挂职副检察长聘任仪式暨教学实践基地挂牌仪式。法学院韩玉胜教授、谢望原教授、郑小敏副书记、潘文军副教授、宋彪副教授、李奋飞副教授、乔鹏、邢姝等参加了仪式。密云县人民检察院党组书记、检察长陈平同志出席仪式，各相关部门负责人参加仪式，党组成员、副检察长王冀川同志主持了仪式。</p>
<p align="center">&nbsp;<img src="/uploads/allimg/c110419/zlflzn2fnkhf-2fkfbz.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 陈平同志首先宣读了密云县人大常委会任命决定，任命冯军同志担任密云县人民检察院副检察长、监察委员会委员。随后举行了教学实验基地挂牌仪式，双方签署并交换合作协议书，林嘉书记兼副院长向陈平同志赠送了教学实践基地牌匾和合作纪念牌。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fnknblkf-2zlfyl.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 林嘉书记兼副院长在讲话中对冯军教授的为人治学给予了高度的评价并向其表示祝贺，她表示法学院将支持冯军教授的检察实务工作，也希望冯军教授能够为双方事业的发展做出贡献。林嘉书记兼副院长提出，两个仪式的举行对于人大法学院和密云县人民检察院都具有重要的意义。长期以来，双方都保持着良好的合作关系。法学院一直以提升人才培养质量为核心事业，致力于培养符合国家法治发展需要的学生，此次与密云检察院建立教学实践基地，搭建课堂教学和司法实践紧密结合的桥梁，将为学生实践和就业提供便利的条件。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fnkmfhkf-22nzmb.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 冯军教授随后发表了简短的感言，他感谢密云检察院的信任及人大法学院的支持，并用了&ldquo;三件不能做得事情&rdquo;和&ldquo;三件必须做的事情&rdquo;表达了自己积极工作、不辜负双方重托的决心。</p>
<p align="center"><img src="/uploads/allimg/c110419/zlflzn2fnkmbf-2llmbk.jpg" alt="" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在其后的自由交流环节中，检、学双方分别就干警教育培训、专家学者指导交流、学生参观实习、就业招聘宣讲等工作进行了发言和交流讨论。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 密云县人民检察院党组书记、检察长陈平同志最后在总结讲话中表示，冯军教授受聘副检察长、中国人民大学法学院教学实践基地的成立是密云县人民检察院的两件大事、喜事，感谢人大法学院无私的支持和帮助，希望两院可以在司法实务、理论研究、教育培训、人才培养等各方面密切配合，实现双赢。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; （编辑：刘伟伟）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110419/zlflzn2fnkhf-2fkfbz_lit.jpg{/dede:field}
