{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}法学院韩大元院长会见芬兰拉普兰大学访问代表团{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}法学院{/dede:field}
{dede:field name='pubdate'}2010-03-10 03:11:04{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3月8日下午，中国人民大学法学院院长韩大元教授在明德法学楼贵宾室接待了来自芬兰拉普兰大学的代表团。法学院副院长王轶教授，法学院杨东副教授以及法学院团委书记兼办公室主任乔鹏老师参与了会见。拉普兰大学代表团一行四人，分别为芬兰拉普兰大学法学院院长Matti Niemivuo，国际交流处执行主任Harri Malinen，法学院教授Juha Karhu和研究员Matti Tjader。&nbsp;</p>
<p align="center"><img alt="" src="/uploads/allimg/c100619/z2kymzy2kymblyf-zblmb.jpg" /></p>
<p><br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 韩大元院长代表法学院师生欢迎拉普兰大学代表团的到来，并简要介绍了中国人民大学法学院在60年的岁月里取得的主要成就以及法学院未来的规划。韩大元院长代表人民大学法学院向四位来宾赠送了礼品，拉普兰大学法学院院长Matti Niemivuo代表拉普兰法学院回赠了礼品。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 拉普兰大学法学院院长Matti Niemivuo教授非常感谢人民大学法学院的盛情邀请，并对于此次交流寄予很高期望。Matti Niemivuo院长谈到正在拉普兰大学讲授中国法律的人民大学法学院张勇凡老师，称其表现十分出色，给拉普兰大学的其他教授留下了良好的印象；另外，今年前往拉普兰大学交流的5名法学院学生也十分优秀，深受芬兰师生的喜爱。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 王轶副院长代表人大法学院与拉普兰法学院就合作协议进行商讨，双方就教师交流、学生交流以及学术资料交流等三个方面进行了深入讨论，达成了良好的合作意向。王轶副院长详细介绍了人大正在推广的&ldquo;暑期学校&rdquo;项目和法学院来年将要开展的中国法项目，欢迎拉普兰大学的学生积极参与这些项目。拉普兰大学代表团表示非常乐意参与这些项目，也特别期望人大法学院能够向国际学生提供更多的机会。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 会谈结束后，王轶副院长带领四位贵宾参观了图书馆法学院分馆。&nbsp;<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (编辑：周庆誉)</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c100619/z2kymzy2kymblyf-zblmb_lit.jpg{/dede:field}
