{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}乌拉圭东岸共和国摄影艺术家作品展在中国人民大学隆重开幕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}作者：艺术学院{/dede:field}
{dede:field name='pubdate'}2009-11-17 04:53:52{/dede:field}
{dede:field name='body'}<p>　　11月16日下午，由中国人民大学艺术学院承办的乌拉圭东岸共和国摄影艺术家作品展在公共教学一楼1301多功能教室拉开帷幕。</p>
<p>　　玻利维亚共和国驻华大使罗德里格斯先生、智利共和国驻华大使费尔南多&middot;雷耶斯&middot;马塔先生、玻利维亚共和国驻华公使埃里克先生、乌拉圭东岸共和国驻华大使馆临时代办马赛罗先生、巴哈马共和国驻华公使谢拉&middot;凯丽女士、牙买加共和国驻华公使衔参赞朱丽亚&middot;海亚特女士、墨西哥共和国驻华公使阿尔弗雷多&middot;米兰达先生应邀出席开幕式。中国人民大学薛浣白副校长出席开幕式并致辞。艺术学院院长徐庆平教授、副院长许俊教授、党委副书记别敏、设计系主任祝东平教授以及艺术学院师生等百余人参加了开幕式。开幕式由别敏副书记主持。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhkmnkbkf-lykzyb.jpg" /></p>
<p>　　中国人民大学副校长薛浣白教授首先致辞。她代表学校向参加开幕式的美洲、非洲各国驻华使节和艺术家们表示热烈的欢迎，对展览开幕表示衷心的祝贺。她指出，中国人民大学历来非常重视与世界各国间的文化交往，本次展览为加强中国人民大学与美洲各国间的文化艺术交流起到积极的作用。</p>
<p>　　徐庆平院长代表艺术学院讲话。他认为艺术是各国人民沟通的重要纽带，本次展览为中外艺术家之间的交流提供了很好的平台。</p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhnf2hmlf-lkyhmn.jpg" /></p>
<p align="center">玻利维亚共和国驻华大使罗德里格斯先生致辞</p>
<p>　　玻利维亚共和国驻华大使罗德里格斯先生和乌拉圭东岸共和国驻华大使馆临时代办马赛罗先生也分别代表本国致辞。他们向在场各位来宾介绍摄影展和艺术家们的情况，对人民大学和艺术学院对此次展览给予的大力支持和协助表示衷心的感谢，同时希望今后能与中国人民大学开展更多的文化交流项目。 </p>
<p align="center"><img alt="" src="/uploads/allimg/c110725/zlzzbyzhnf2nkzf-ln2fbl.jpg" /></p>
<p>　　随后，出席开幕式的中外双方嘉宾为开幕式剪彩。</p>
<p>　　开幕式结束后，领导和来宾一起参观了名为&ldquo;对跖点&mdash;&mdash;从世界另一边投来的目光&rdquo;三位乌拉圭艺术家献上的摄影作品展。本次展览的五十余幅作品如实记录玻利维亚共和国的风土民情，内容丰富而情感真挚，充分展示了美洲艺术家关注人生、关注社会的创作理念和纯真的内心世界。</p>
<p>　　（编辑：王珏）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110725/zlzzbyzhkmnkbkf-lykzyb_lit.jpg{/dede:field}
