{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}“两岸人力资源开发与交流研讨会”召开{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}劳动人事学院{/dede:field}
{dede:field name='pubdate'}2012-06-04 04:45:42{/dede:field}
{dede:field name='body'}<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 经国务院台湾事务办公室立项，由中华海峡两岸人才交流协会、台湾发展研究院主办，中国人民大学劳动人事学院承办的&ldquo;两岸人力资源开发与交流研讨会&rdquo;于5月31日在中国人民大学逸夫会堂第二会议室举行。中国人民大学副校长杨慧林、台湾发展研究院董事赵守博、中华海峡两岸人才交流协会副会长李兵、国务院台湾事务办公室交流局副局长严中洲、中华海峡两岸人才交流协会秘书长刘永志、中国国际人才交流与开发研究会理事黄立金、中国人事科学研究院院长吴江等出席开幕式。</p>
<p align="center"><img alt="" src="/uploads/allimg/c120620/zlhfzklzzybyfnf-zynmy.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 开幕式由中国人民大学劳动人事学院院长曾湘泉主持。 </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 李兵副会长在致辞中高度评价了此次研讨会对于分享两岸在人力资源建设方面的经验，推进两岸人力资源开发与管理的理论研究和实践探索、推动两岸人才交流的发展所具有的积极意义。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 赵守博董事介绍了宝岛台湾人力资源开发的状况及其与台湾经济社会发展的联系。赵守博董事认为，随着经济的发展，人力资源成本不断提升，社会步入高工资时代，这是人力资源领域的重要课题，相信两岸专家学者及各界之间的交流有益于两岸的合作与两岸人民的福祉。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 杨慧林副校长表示，中国人民大学全力支持劳动人事学院就劳动科学领域与两岸的同仁开展交流与合作，并指出人力资源是国家最宝贵的第一资源，各地区各部门都在大力开发人力资源，中国人民大学通过各种努力吸引和汇聚了一大批一流人才，以此推动着学校各项事业的发展，希望两岸各方积极搭建平台、不断加强交流，共同为推动两岸关系发展、造福华人世界贡献力量。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 随后，来自两岸三方的与会嘉宾围绕&ldquo;人才引进与人才交流&rdquo;、&ldquo;人才培养与人力资源开发&rdquo;、&ldquo;劳动力市场、职业教育与培训&rdquo;和&ldquo;人才猎头、创新人才的引进&rdquo;等四个专题进行了深入的交流和探讨。刘永志秘书长，台湾发展研究院副院长江文国，中国人事科学研究院院长吴江，台湾中央大学哲学研究所冯沪祥教授，台湾明新科技大学校长冯丹白，中国人民大学劳动人事学院数据中心主任丁大建，台湾国立政治大学劳工研究所陈聪胜副教授，特波国际总经理萧世贵，美国百人会理事曾宪章，中国人才交流协会高级人才寻访专业委员会主任、北京市天之择人才发展有限责任公司董事长韩光耀、中国人民大学中国就业研究所助理研究员夏青云分别作报告。</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 最后，赵守博董事、曾湘泉院长和刘永志秘书长代表两岸三方对此次研讨会进行总结，大家认为人力资源开发与管理是当前的热点问题，加强两岸人力资源开发与交流功在当代、利在千秋，应该继续深化合作与交流，推动两岸人力资源领域学术交流的制度化和品牌化。</p>
<p align="center"><img alt="" src="/uploads/allimg/c120620/zlhfzklzlflyb2f-2ymnm.jpg" /></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 来自中华海峡两岸人才交流协会、台湾地区有关单位、中国人民大学的学生代表80余人以及劳动人事学院唐鑛教授、林新奇教授等参加研讨会。</p>
<p>（编辑 杨默）</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120620/zlhfzklzzybyfnf-zynmy_lit.jpg{/dede:field}
