{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}经济学院杨瑞龙教授再次受聘上海市人民政府决策咨询特聘专家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}经济学院{/dede:field}
{dede:field name='pubdate'}2011-01-18 12:18:10{/dede:field}
{dede:field name='body'}<p>　　近日，上海市人民政府发来专函，再次聘请经济学院院长杨瑞龙教授为上海市人民政府决策咨询特聘专家。 </p>
<p align="center"><img height="333" src="/uploads/allimg/c110217/z2mkmlhh2klnb2f-zynzy.jpg" width="500" alt="" /></p>
<p><br />
　　杨瑞龙教授曾于2008年12月受聘为上海市人民政府决策咨询特聘专家。他多次参加上海市经济发展的会议，为上海市的发展建言献策，得到了上海市领导的高度评价。此次，鉴于杨瑞龙教授为上海市发展做出的突出贡献，上海市人民政府再次聘请他为决策咨询特聘专家。 </p>
<p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c110217/z2mkmlhh2klnb2f-zynzy_lit.jpg{/dede:field}
