{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}新闻学院喻国明获第四届全国广电“十佳”理论人才称号{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}新闻学院{/dede:field}
{dede:field name='pubdate'}2011-01-26 08:42:54{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由中国广播电视协会主办的第四届全国&ldquo;十佳百优&rdquo;理论人才评选结果日前公布，中国人民大学新闻学院喻国明荣获&ldquo;十佳&rdquo;理论人才称号。同时获得&ldquo;十佳&rdquo;的还有白玲、杜永明、张长明、张君昌、陈梁、杨明品、孟建、黄升良、周旻等。 <br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 全国广播电视&ldquo;十佳&rdquo;&ldquo;百优&rdquo;理论人才每四年评选一次，是全国广播电视业界和学界最具有权威性和影响力的专家奖。评选活动旨在加强广播电视理论队伍建设，发现、奖励人品文品俱佳的广播电视理论工作者。此次评选历时半年，最终评出&ldquo;十佳&rdquo;广播电视理论人才10名和&ldquo;百优&rdquo;广播电视理论人才100名。{/dede:field}
{dede:field name='litpic'}{/dede:field}
