<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","新闻学院喻国明获第四届全国广电“十佳”理论人才称号",89,177);
$z[2][4]['name']="title";
$z[3]=Array("field","",179,218);
$z[3][4]['name']="writer";
$z[4]=Array("field","新闻学院",220,267);
$z[4][4]['name']="source";
$z[5]=Array("field","2011-01-26 08:42:54",269,328);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 由中国广播电视协会主办的第四届全国&ldquo;十佳百优&rdquo;理论人才评选结果日前公布，中国人民大学新闻学院喻国明荣获&ldquo;十佳&rdquo;理论人才称号。同时获得&ldquo;十佳&rdquo;的还有白玲、杜永明、张长明、张君昌、陈梁、杨明品、孟建、黄升良、周旻等。 <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 全国广播电视&ldquo;十佳&rdquo;&ldquo;百优&rdquo;理论人才每四年评选一次，是全国广播电视业界和学界最具有权威性和影响力的专家奖。评选活动旨在加强广播电视理论队伍建设，发现、奖励人品文品俱佳的广播电视理论工作者。此次评选历时半年，最终评出&ldquo;十佳&rdquo;广播电视理论人才10名和&ldquo;百优&rdquo;广播电视理论人才100名。",330,1015);
$z[6][4]['name']="body";
$z[7]=Array("field","",1017,1056);
$z[7][4]['name']="litpic";

?>