<?php
$z[0]=Array("myad","",67,99);
$z[0][4]['name']="zhuanyelinks";
$z[1]=Array("global","",148,174);
$z[1][4]['name']="cfg_address";
$z[2]=Array("global","",181,203);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",227,251);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",253,277);
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",289,315);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",315,339);
$z[6][4]['name']="cfg_beian";

?>