<?php
$z[0]=Array("channelartlist","<ul id=\"dropmenu{dede:field.typeid/}\" class=\"dropMenu\">\r\n{dede:channel type='son' noself='yes'} <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n{/dede:channel}\r\n</ul>\r\n",66,327);
$z[0][4]['typeid']="top";
$z[0][4]['cacheid']="channelsonlist";
$z[1]=Array("myad","",1354,1383);
$z[1][4]['name']="footLinks";
$z[2]=Array("global","",1421,1447);
$z[2][4]['name']="cfg_address";
$z[3]=Array("global","",1454,1476);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1499,1523);
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",1525,1549);
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",1561,1587);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",1675,1699);
$z[7][4]['name']="cfg_beian";

?>