<?php
$z[0]=Array("arclist","\r\n        [field:pubdate function=strftime('%Y-%m-%d',@me)/]\r\n        ",187,320);
$z[0][4]['row']="1";
$z[0][4]['titlelen']="24";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("channel","\r\n        <url>\r\n        <loc>http://www.ruconline.com[field:typelink /]</loc>\r\n        <changefreq>daily</changefreq>\r\n        <priority>0.8</priority>\r\n        </url>\r\n        ",431,658);
$z[1][4]['row']="23";
$z[1][4]['type']="top";
$z[2]=Array("arclist","\r\n        <url>\r\n        <loc>http://www.ruconline.com[field:arcurl/]</loc>\r\n        <lastmod>[field:pubdate function=strftime('%Y-%m-%d',@me)/]</lastmod>\r\n        <changefreq>monthly</changefreq>\r\n        </url>\r\n        ",668,944);
$z[2][4]['row']="2000";
$z[2][4]['orderby']="pubdate";

?>