<?php
$z[0]=Array("global","",786,811);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",877,902);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",964,989);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",1022,1048);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",1166,1193);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1269,1296);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1299,1325);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",1455,1482);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",1494,1526);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1573,1599);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",2234,2259);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",2299,2542);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[12]=Array("global","",2619,2644);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channelartlist","<ul id=\"dropmenu{dede:field.typeid/}\" class=\"dropMenu\">\r\n{dede:channel type='son' noself='yes'} <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n{/dede:channel}\r\n</ul>\r\n",2679,2940);
$z[13][4]['typeid']="top";
$z[13][4]['cacheid']="channelsonlist";
$z[14]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",4484,4614);
$z[14][4]['row']="10";
$z[14][4]['getall']="1";
$z[14][4]['sort']="month";

?>