<?php
$z[0]=Array("field","",313,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",926,973);
$z[4][4]['file']="inc/top.htm";
$z[4][4]['ismake']="yes";
$z[5]=Array("field","",1078,1107);
$z[5][4]['name']="position";
$z[6]=Array("field","",1174,1195);
$z[6][4]['name']="content";
$z[7]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\">[field:image/]<span class=\"title\">[field:title/]</span></a></li>",1316,1510);
$z[7][4]['row']="5";
$z[7][4]['orderby']="pubdate";
$z[7][4]['type']="image.";
$z[7][4]['imgwidth']="124";
$z[7][4]['imgheight']="94";
$z[8]=Array("channelartlist","\r\n<dl class=\"mold\">\r\n<dt><a href=\"{dede:field name='typeurl'/}\" class=\"l\">{dede:field name='typename'/}</a><a class=\"r\" href=\"{dede:field name='typeurl'/}\">¸ü¶à&gt;&gt;</a></dt>\r\n<dd>\r\n<ol>\r\n	{dede:arclist titlelen='160' row='10'}\r\n<li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title \r\n/]</a></li>\r\n{/dede:arclist}\r\n</ol>\r\n</dd>\r\n</dl>\r\n	",1582,2026);
$z[9]=Array("myad","",2193,2224);
$z[9][4]['name']="lianxiWomen";
$z[10]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",2323,2499);
$z[10][4]['type']="son";
$z[10][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"Hover\"> ~typename~</a></li>";
$z[11]=Array("field","",2592,2619);
$z[11][4]['name']="phpurl";
$z[12]=Array("myad","",2928,2959);
$z[12][4]['name']="rightCourse";
$z[13]=Array("include","",3081,3131);
$z[13][4]['file']="inc/footer.htm";
$z[13][4]['ismake']="yes";

?>