<?php
$z[0]=Array("field","",313,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",926,973);
$z[4][4]['file']="inc/top.htm";
$z[4][4]['ismake']="yes";
$z[5]=Array("field","",1079,1108);
$z[5][4]['name']="position";
$z[6]=Array("field","",1171,1192);
$z[6][4]['name']="content";
$z[7]=Array("channelartlist","\r\n<dl>\r\n<dt><a href=\"{dede:field name='typeurl'/}\" class=\"l\">{dede:field name='typename'/}</a><a href=\"{dede:field name='typeurl'/}\" class=\"r\">¸ü¶à&gt;&gt;</a></dt>\r\n<dd>\r\n<ol>\r\n	{dede:arclist titlelen='160' row='20'}\r\n<li>¡¤<a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n{/dede:arclist}\r\n</ol>\r\n</dd>\r\n</dl>\r\n	",1249,1609);
$z[8]=Array("myad","",1775,1806);
$z[8][4]['name']="lianxiWomen";
$z[9]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1905,2081);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"Hover\"> ~typename~</a></li>";
$z[10]=Array("field","",2174,2201);
$z[10][4]['name']="phpurl";
$z[11]=Array("myad","",2511,2542);
$z[11][4]['name']="rightCourse";
$z[12]=Array("include","",2665,2715);
$z[12][4]['file']="inc/footer.htm";
$z[12][4]['ismake']="yes";

?>