<?php
$z[0]=Array("global","",212,240);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",335,358);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",359,385);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",426,455);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",495,553);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",877,924);
$z[5][4]['file']="inc/top.htm";
$z[5][4]['ismake']="yes";
$z[6]=Array("field","",1030,1059);
$z[6][4]['name']="position";
$z[7]=Array("field","",1101,1122);
$z[7][4]['name']="content";
$z[8]=Array("channelartlist","\r\n<dl>\r\n<dt><a href=\"{dede:field name='typeurl'/}\" class=\"l\">{dede:field name='typename'/}</a>\r\n<a href=\"{dede:field name='typeurl'/}\" class=\"r\">¸ü¶à...</a>\r\n</dt>\r\n<dd>\r\n<ol>\r\n{dede:arclist titlelen='160' row='20'}\r\n<li>¡¤<a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n{/dede:arclist}\r\n</ol>\r\n</dd>\r\n</dl>\r\n",1178,1535);
$z[9]=Array("myad","",1693,1724);
$z[9][4]['name']="lianxiWomen";
$z[10]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1822,1995);
$z[10][4]['type']="son";
$z[10][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"Hover\">~typename~</a></li>";
$z[11]=Array("field","",2088,2115);
$z[11][4]['name']="phpurl";
$z[12]=Array("myad","",2420,2451);
$z[12][4]['name']="rightCourse";
$z[13]=Array("include","",2569,2619);
$z[13][4]['file']="inc/footer.htm";
$z[13][4]['ismake']="yes";

?>