<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("field","",839,866);
$z[6][4]['name']="phpurl";
$z[7]=Array("include","",938,973);
$z[7][4]['filename']="head.htm";
$z[8]=Array("field","",1107,1136);
$z[8][4]['name']="position";
$z[9]=Array("freelist","",1209,1225);
$z[10]=Array("pagelist","",1331,1402);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("arclist","\r\n          	<li><a href=\"[field:arcurl/]\">[field:title/]</a>\r\n            	<p>[field:description function='cn_substr(@me,80)'/]...</p>\r\n            </li>",1619,1829);
$z[11][4]['flag']="c";
$z[11][4]['titlelen']="42";
$z[11][4]['row']="6";
$z[12]=Array("arclist","\r\n                    	<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",2039,2187);
$z[12][4]['row']="10";
$z[12][4]['orderby']="click";
$z[13]=Array("include","",2271,2308);
$z[13][4]['filename']="footer.htm";

?>