<?php
$z[0]=Array("field","",313,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",926,977);
$z[4][4]['file']="inc/top2011.htm";
$z[4][4]['ismake']="yes";
$z[5]=Array("field","",1083,1112);
$z[5][4]['name']="position";
$z[6]=Array("field","",1422,1443);
$z[6][4]['name']="content";
$z[7]=Array("list","\r\n<div id=\"jianzhang\">\r\n<dl>\r\n<dt><a href=\"[field:arcurl /]\" class=\"l\">[field:title /]</a><a href=\"[field:arcurl /]\" class=\"r\">²é¿´ÏêÇé&gt;&gt;</a></dt>\r\n<dd>\r\n<div id=\"focusImg\">[field:image /]</div>\r\n<div id=\"jianzhangRight\">\r\n<div id=\"miaoshu\">[field:description /]</div>\r\n<div id=\"anniu\"><a href=\"[field:arcurl /]\" target=\"_blank\"><img src=\"/_res/btn_wyzx.gif\" alt=\"\" /></a>  <a href=\"[field:arcurl /]\" target=\"_blank\"><img src=\"/_res/btn_wybm.gif\" alt=\"\" /></a></div>\r\n</div>\r\n<div class=\"c\"></div>\r\n</dd>\r\n</dl>\r\n\r\n</div>\r\n",1476,2041);
$z[7][4]['pagesize']="1";
$z[8]=Array("pagelist","",2071,2149);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("myad","",2286,2317);
$z[9][4]['name']="lianxiWomen";
$z[10]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",2416,2592);
$z[10][4]['type']="son";
$z[10][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"Hover\"> ~typename~</a></li>";
$z[11]=Array("field","",2685,2712);
$z[11][4]['name']="phpurl";
$z[12]=Array("myad","",3022,3053);
$z[12][4]['name']="rightCourse";
$z[13]=Array("include","",3176,3226);
$z[13][4]['file']="inc/footer.htm";
$z[13][4]['ismake']="yes";

?>