<?php
$z[0]=Array("field","",313,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",923,970);
$z[4][4]['file']="inc/top.htm";
$z[4][4]['ismake']="yes";
$z[5]=Array("field","",1076,1105);
$z[5][4]['name']="position";
$z[6]=Array("field","",1151,1172);
$z[6][4]['name']="content";
$z[7]=Array("list","\r\n<dl>\r\n	[field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<dd><a href=\\\"{@me['arcurl']}\\\"><img onload=\\\"hideno(this)\\\" alt=\\\"{@me['title']}\\\" src=\\\"{@me['litpic']}\\\"/></a></dd>\"); [/field:array]\r\n	<dt><a href=\"[field:arcurl/]\" class=\"tit\">[field:title/]</a> </dt>\r\n</dl>\r\n			",1211,1536);
$z[7][4]['pagesize']="15";
$z[8]=Array("pagelist","",1591,1694);
$z[8][4]['listitem']="&quot;info,index,end,pre,next,pageno,option&quot;";
$z[8][4]['listsize']="&quot;5&quot;";
$z[9]=Array("myad","",1826,1857);
$z[9][4]['name']="lianxiWomen";
$z[10]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1956,2132);
$z[10][4]['type']="son";
$z[10][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"Hover\"> ~typename~</a></li>";
$z[11]=Array("field","",2225,2252);
$z[11][4]['name']="phpurl";
$z[12]=Array("myad","",2564,2595);
$z[12][4]['name']="rightCourse";
$z[13]=Array("include","",2719,2769);
$z[13][4]['file']="inc/footer.htm";
$z[13][4]['ismake']="yes";

?>