<?php
$z[0]=Array("field","",313,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",922,969);
$z[4][4]['file']="inc/top.htm";
$z[4][4]['ismake']="yes";
$z[5]=Array("field","",1075,1104);
$z[5][4]['name']="position";
$z[6]=Array("myad","",1156,1187);
$z[6][4]['name']="listContent";
$z[7]=Array("field","",1187,1208);
$z[7][4]['name']="content";
$z[8]=Array("list","\r\n			<dl>\r\n        		<dd>\r\n					<a href=\"[field:arcurl/]\" class=\"pic\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/></a></dd>\r\n				<dt><a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a></dt>\r\n				<dt><span class=\"date\"><small>最后更新：</small>[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n				</dt>\r\n        	</dl>\r\n		  ",1245,1645);
$z[8][4]['pagesize']="12";
$z[9]=Array("pagelist","",1727,1798);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("myad","",1955,1986);
$z[10][4]['name']="lianxiWomen";
$z[11]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",2084,2257);
$z[11][4]['type']="son";
$z[11][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"Hover\">~typename~</a></li>";
$z[12]=Array("field","",2350,2377);
$z[12][4]['name']="phpurl";
$z[13]=Array("myad","",2682,2713);
$z[13][4]['name']="rightCourse";
$z[14]=Array("include","",2834,2884);
$z[14][4]['file']="inc/footer.htm";
$z[14][4]['ismake']="yes";

?>