<?php
$z[0]=Array("global","",212,240);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",335,354);
$z[1][4]['name']="title";
$z[2]=Array("field","",395,417);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",457,515);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",836,883);
$z[4][4]['file']="inc/top.htm";
$z[4][4]['ismake']="yes";
$z[5]=Array("global","",980,1005);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1136,1278);
$z[6][4]['row']="60";
$z[6][4]['sort']="new";
$z[7]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1389,1533);
$z[7][4]['row']="60";
$z[7][4]['sort']="month";
$z[8]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1637,1781);
$z[8][4]['row']="100";
$z[8][4]['sort']="rand";
$z[9]=Array("include","",1826,1876);
$z[9][4]['file']="inc/footer.htm";
$z[9][4]['ismake']="yes";

?>