<?php
$z[0]=Array("myad","",0,28);
$z[0][4]['name']="topLinks";
$z[1]=Array("field","",74,100);
$z[1][4]['name']="title";
$z[2]=Array("myad","",203,228);
$z[2][4]['name']="topAD";
$z[3]=Array("channel","\r\n<li><a onmouseover=\"Menu(this)\" onmouseout=\"Menu(this)\" onfocus=\"this.blur()\" href=\"[field:typelink/]\">[field:typename/]</a></li>",373,698);
$z[3][4]['type']="top";
$z[3][4]['row']="12";
$z[3][4]['currentstyle']="<li class=\"Hover\"><a onmouseover=\"Menu(this)\" onmouseout=\"Menu(this)\" onfocus=\"this.blur()\" href=\"~typelink~\">~typename~</a></li>";

?>